package org.keycloak.representations.admin.v2;

import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import org.keycloak.representations.admin.v2.validation.PatchClient;
import org.keycloak.representations.admin.v2.validation.ProtocolUnmodified;
import org.keycloak.representations.admin.v2.validation.PutClient;
import org.keycloak.representations.admin.v2.validation.UuidUnmodified;
import org.keycloak.representations.admin.v2.validation.ValidRedirectUris;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.hibernate.validator.constraints.URL;

/**
 * 所有客户端类型的公共属性基类表示。
 * <p>
 * 通过 {@link #protocol} 字段作为 Jackson 多态鉴别器，具体子类型为
 * {@link OIDCClientRepresentation} 与 {@link SAMLClientRepresentation}。
 * 在 PUT/PATCH 时受 UUID、协议不可变及重定向 URI 等校验约束。
 */
@Schema(description = "Base client representation with common properties for all client types")
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = BaseClientRepresentation.DISCRIMINATOR_FIELD,
    visible = true,
    defaultImpl = BaseClientRepresentation.class
)
@JsonSubTypes({
    @JsonSubTypes.Type(value = OIDCClientRepresentation.class, name = OIDCClientRepresentation.PROTOCOL),
    @JsonSubTypes.Type(value = SAMLClientRepresentation.class, name = SAMLClientRepresentation.PROTOCOL)
})
@UuidUnmodified(groups = {PutClient.class, PatchClient.class}, affectedFieldNames = {"uuid"})
@ProtocolUnmodified(groups = {PutClient.class, PatchClient.class})
@ValidRedirectUris
public class BaseClientRepresentation extends BaseRepresentation implements RepresentationWithUuid {
    /** Jackson 多态鉴别字段名（值为 protocol）。 */
    public static final String DISCRIMINATOR_FIELD = "protocol";

    /** 服务端生成的 UUID，只读。 */
    @JsonPropertyDescription("UUID generated by the server")
    @Schema(description = "UUID generated by the server", readOnly = true)
    protected String uuid;

    /** 唯一标识客户端的 clientId，必填。 */
    @NotBlank
    @Size(min = 1, max = 255)
    @JsonPropertyDescription("ID uniquely identifying this client")
    protected String clientId;

    /** 客户端的人类可读显示名称。 */
    @Size(max = 255)
    @JsonPropertyDescription("Human readable name of the client")
    private String displayName;

    /** 客户端的人类可读描述。 */
    @Size(max = 255)
    @JsonPropertyDescription("Human readable description of the client")
    private String description;

    /** 客户端是否启用。 */
    @JsonPropertyDescription("Whether this client is enabled")
    private Boolean enabled;

    /** 该客户端所代表应用的主页 URL。 */
    @URL
    @Size(max = 255)
    @JsonPropertyDescription("URL to the application's homepage that is represented by this client")
    private String appUrl;

    /** 登录后浏览器可重定向到的 URI 集合。 */
    @Size(max = 100)
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonPropertyDescription("URIs that the browser can redirect to after login")
    private Set<@NotBlank @Size(max = 255) String> redirectUris = new LinkedHashSet<>();

    /** 与该客户端关联的角色名称集合。 */
    @Size(max = 300)
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonPropertyDescription("Roles associated with this client")
    private Set<@NotBlank @Size(max = 255) String> roles = new LinkedHashSet<>();

    /** 客户端协议（如 openid-connect、saml），亦作多态类型鉴别值。 */
    @JsonPropertyDescription("Client protocol")
    protected String protocol;

    /** 客户端创建时间戳，只读。 */
    @JsonPropertyDescription("Timestamp when the client was created")
    @Schema(description = "Timestamp when the client was created", readOnly = true)
    private Long createdTimestamp;

    /** 客户端最后更新时间戳，只读。 */
    @JsonPropertyDescription("Timestamp when the client was last updated")
    @Schema(description = "Timestamp when the client was last updated", readOnly = true)
    private Long updatedTimestamp;

    @Override
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getAppUrl() {
        return appUrl;
    }

    public void setAppUrl(String appUrl) {
        this.appUrl = appUrl;
    }

    public Set<String> getRedirectUris() {
        return redirectUris;
    }

    public void setRedirectUris(Set<String> redirectUris) {
        this.redirectUris = redirectUris;
    }

    public Set<String> getRoles() {
        return roles;
    }

    public void setRoles(Set<String> roles) {
        this.roles = roles;
    }

    public String getProtocol() {
        return protocol;
    }

    public Long getCreatedTimestamp() {
        return createdTimestamp;
    }

    public void setCreatedTimestamp(Long createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    public Long getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    public void setUpdatedTimestamp(Long updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof BaseClientRepresentation)) {
            return false;
        }
        BaseClientRepresentation that = (BaseClientRepresentation)o;
        return Objects.equals(uuid, that.uuid) && Objects.equals(clientId, that.clientId) && Objects.equals(displayName, that.displayName) && Objects.equals(description, that.description) && Objects.equals(enabled, that.enabled) && Objects.equals(appUrl, that.appUrl) && Objects.equals(redirectUris, that.redirectUris) && Objects.equals(roles, that.roles) && Objects.equals(protocol, that.protocol);
    }

    @Override
    public int hashCode() {
        return Objects.hash(uuid, clientId, displayName, description, enabled, appUrl, redirectUris, roles, protocol);
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "{" + "protocol=" + getProtocol()
        + ", uuid=" + uuid
        + ", clientId=" + clientId
        + ", displayName=" + displayName
        + ", description=" + description
        + ", enabled=" + enabled
        + ", appUrl=" + appUrl
        + ", redirectUris=" + redirectUris
        + ", roles=" + roles
        + ", updatedTimestamp=" + updatedTimestamp
        + ", createdTimestamp=" + createdTimestamp + "}";
    }
}
