// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/drone/go-scm/scm (interfaces: ContentService,GitService,OrganizationService,PullRequestService,RepositoryService,UserService)

// Package mockscm 是由 GoMock 自动生成的 go-scm SCM 接口模拟包。
package mockscm

import (
	context "context"
	reflect "reflect"

	scm "github.com/drone/go-scm/scm"
	gomock "github.com/golang/mock/gomock"
)

// MockContentService 是 ContentService 接口的 GoMock 模拟实现。
type MockContentService struct {
	ctrl     *gomock.Controller
	recorder *MockContentServiceMockRecorder
}

// MockContentServiceMockRecorder 是 MockContentService 的期望调用记录器。
type MockContentServiceMockRecorder struct {
	mock *MockContentService
}

// NewMockContentService 创建新的模拟实例。
func NewMockContentService(ctrl *gomock.Controller) *MockContentService {
	mock := &MockContentService{ctrl: ctrl}
	mock.recorder = &MockContentServiceMockRecorder{mock}
	return mock
}

// EXPECT 返回用于声明期望调用的记录器对象。
func (m *MockContentService) EXPECT() *MockContentServiceMockRecorder {
	return m.recorder
}

// Create 模拟底层接口方法。
func (m *MockContentService) Create(arg0 context.Context, arg1, arg2 string, arg3 *scm.ContentParams) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create 声明对 Create 的期望调用。
func (mr *MockContentServiceMockRecorder) Create(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContentService)(nil).Create), arg0, arg1, arg2, arg3)
}

// Delete 模拟底层接口方法。
func (m *MockContentService) Delete(arg0 context.Context, arg1, arg2 string, arg3 *scm.ContentParams) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete 声明对 Delete 的期望调用。
func (mr *MockContentServiceMockRecorder) Delete(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContentService)(nil).Delete), arg0, arg1, arg2, arg3)
}

// Find 模拟底层接口方法。
func (m *MockContentService) Find(arg0 context.Context, arg1, arg2, arg3 string) (*scm.Content, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Content)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find 声明对 Find 的期望调用。
func (mr *MockContentServiceMockRecorder) Find(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockContentService)(nil).Find), arg0, arg1, arg2, arg3)
}

// List 模拟底层接口方法。
func (m *MockContentService) List(arg0 context.Context, arg1, arg2, arg3 string, arg4 scm.ListOptions) ([]*scm.ContentInfo, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*scm.ContentInfo)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List 声明对 List 的期望调用。
func (mr *MockContentServiceMockRecorder) List(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContentService)(nil).List), arg0, arg1, arg2, arg3, arg4)
}

// Update 模拟底层接口方法。
func (m *MockContentService) Update(arg0 context.Context, arg1, arg2 string, arg3 *scm.ContentParams) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update 声明对 Update 的期望调用。
func (mr *MockContentServiceMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContentService)(nil).Update), arg0, arg1, arg2, arg3)
}

// MockGitService 是 GitService 接口的 GoMock 模拟实现。
type MockGitService struct {
	ctrl     *gomock.Controller
	recorder *MockGitServiceMockRecorder
}

// MockGitServiceMockRecorder 是 MockGitService 的期望调用记录器。
type MockGitServiceMockRecorder struct {
	mock *MockGitService
}

// NewMockGitService 创建新的模拟实例。
func NewMockGitService(ctrl *gomock.Controller) *MockGitService {
	mock := &MockGitService{ctrl: ctrl}
	mock.recorder = &MockGitServiceMockRecorder{mock}
	return mock
}

// EXPECT 返回用于声明期望调用的记录器对象。
func (m *MockGitService) EXPECT() *MockGitServiceMockRecorder {
	return m.recorder
}

// CompareChanges 模拟底层接口方法。
func (m *MockGitService) CompareChanges(arg0 context.Context, arg1, arg2, arg3 string, arg4 scm.ListOptions) ([]*scm.Change, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareChanges", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*scm.Change)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CompareChanges 声明对 CompareChanges 的期望调用。
func (mr *MockGitServiceMockRecorder) CompareChanges(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareChanges", reflect.TypeOf((*MockGitService)(nil).CompareChanges), arg0, arg1, arg2, arg3, arg4)
}

// CreateBranch 模拟底层接口方法。
func (m *MockGitService) CreateBranch(arg0 context.Context, arg1 string, arg2 *scm.ReferenceInput) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBranch 声明对 CreateBranch 的期望调用。
func (mr *MockGitServiceMockRecorder) CreateBranch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockGitService)(nil).CreateBranch), arg0, arg1, arg2)
}

// FindBranch 模拟底层接口方法。
func (m *MockGitService) FindBranch(arg0 context.Context, arg1, arg2 string) (*scm.Reference, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBranch", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Reference)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBranch 声明对 FindBranch 的期望调用。
func (mr *MockGitServiceMockRecorder) FindBranch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBranch", reflect.TypeOf((*MockGitService)(nil).FindBranch), arg0, arg1, arg2)
}

// FindCommit 模拟底层接口方法。
func (m *MockGitService) FindCommit(arg0 context.Context, arg1, arg2 string) (*scm.Commit, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCommit", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Commit)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindCommit 声明对 FindCommit 的期望调用。
func (mr *MockGitServiceMockRecorder) FindCommit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCommit", reflect.TypeOf((*MockGitService)(nil).FindCommit), arg0, arg1, arg2)
}

// FindTag 模拟底层接口方法。
func (m *MockGitService) FindTag(arg0 context.Context, arg1, arg2 string) (*scm.Reference, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTag", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Reference)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindTag 声明对 FindTag 的期望调用。
func (mr *MockGitServiceMockRecorder) FindTag(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTag", reflect.TypeOf((*MockGitService)(nil).FindTag), arg0, arg1, arg2)
}

// ListBranches 模拟底层接口方法。
func (m *MockGitService) ListBranches(arg0 context.Context, arg1 string, arg2 scm.ListOptions) ([]*scm.Reference, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.Reference)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBranches 声明对 ListBranches 的期望调用。
func (mr *MockGitServiceMockRecorder) ListBranches(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockGitService)(nil).ListBranches), arg0, arg1, arg2)
}

// ListBranchesV2 模拟底层接口方法。
func (m *MockGitService) ListBranchesV2(arg0 context.Context, arg1 string, arg2 scm.BranchListOptions) ([]*scm.Reference, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranchesV2", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.Reference)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBranchesV2 声明对 ListBranchesV2 的期望调用。
func (mr *MockGitServiceMockRecorder) ListBranchesV2(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranchesV2", reflect.TypeOf((*MockGitService)(nil).ListBranchesV2), arg0, arg1, arg2)
}

// ListChanges 模拟底层接口方法。
func (m *MockGitService) ListChanges(arg0 context.Context, arg1, arg2 string, arg3 scm.ListOptions) ([]*scm.Change, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChanges", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*scm.Change)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListChanges 声明对 ListChanges 的期望调用。
func (mr *MockGitServiceMockRecorder) ListChanges(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChanges", reflect.TypeOf((*MockGitService)(nil).ListChanges), arg0, arg1, arg2, arg3)
}

// ListCommits 模拟底层接口方法。
func (m *MockGitService) ListCommits(arg0 context.Context, arg1 string, arg2 scm.CommitListOptions) ([]*scm.Commit, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommits", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.Commit)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCommits 声明对 ListCommits 的期望调用。
func (mr *MockGitServiceMockRecorder) ListCommits(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommits", reflect.TypeOf((*MockGitService)(nil).ListCommits), arg0, arg1, arg2)
}

// ListTags 模拟底层接口方法。
func (m *MockGitService) ListTags(arg0 context.Context, arg1 string, arg2 scm.ListOptions) ([]*scm.Reference, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.Reference)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTags 声明对 ListTags 的期望调用。
func (mr *MockGitServiceMockRecorder) ListTags(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockGitService)(nil).ListTags), arg0, arg1, arg2)
}

// MockOrganizationService 是 OrganizationService 接口的 GoMock 模拟实现。
type MockOrganizationService struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationServiceMockRecorder
}

// MockOrganizationServiceMockRecorder 是 MockOrganizationService 的期望调用记录器。
type MockOrganizationServiceMockRecorder struct {
	mock *MockOrganizationService
}

// NewMockOrganizationService 创建新的模拟实例。
func NewMockOrganizationService(ctrl *gomock.Controller) *MockOrganizationService {
	mock := &MockOrganizationService{ctrl: ctrl}
	mock.recorder = &MockOrganizationServiceMockRecorder{mock}
	return mock
}

// EXPECT 返回用于声明期望调用的记录器对象。
func (m *MockOrganizationService) EXPECT() *MockOrganizationServiceMockRecorder {
	return m.recorder
}

// Find 模拟底层接口方法。
func (m *MockOrganizationService) Find(arg0 context.Context, arg1 string) (*scm.Organization, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*scm.Organization)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find 声明对 Find 的期望调用。
func (mr *MockOrganizationServiceMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockOrganizationService)(nil).Find), arg0, arg1)
}

// FindMembership 模拟底层接口方法。
func (m *MockOrganizationService) FindMembership(arg0 context.Context, arg1, arg2 string) (*scm.Membership, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMembership", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Membership)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindMembership 声明对 FindMembership 的期望调用。
func (mr *MockOrganizationServiceMockRecorder) FindMembership(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMembership", reflect.TypeOf((*MockOrganizationService)(nil).FindMembership), arg0, arg1, arg2)
}

// List 模拟底层接口方法。
func (m *MockOrganizationService) List(arg0 context.Context, arg1 scm.ListOptions) ([]*scm.Organization, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*scm.Organization)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List 声明对 List 的期望调用。
func (mr *MockOrganizationServiceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrganizationService)(nil).List), arg0, arg1)
}

// MockPullRequestService 是 PullRequestService 接口的 GoMock 模拟实现。
type MockPullRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestServiceMockRecorder
}

// MockPullRequestServiceMockRecorder 是 MockPullRequestService 的期望调用记录器。
type MockPullRequestServiceMockRecorder struct {
	mock *MockPullRequestService
}

// NewMockPullRequestService 创建新的模拟实例。
func NewMockPullRequestService(ctrl *gomock.Controller) *MockPullRequestService {
	mock := &MockPullRequestService{ctrl: ctrl}
	mock.recorder = &MockPullRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT 返回用于声明期望调用的记录器对象。
func (m *MockPullRequestService) EXPECT() *MockPullRequestServiceMockRecorder {
	return m.recorder
}

// Close 模拟底层接口方法。
func (m *MockPullRequestService) Close(arg0 context.Context, arg1 string, arg2 int) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close 声明对 Close 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) Close(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPullRequestService)(nil).Close), arg0, arg1, arg2)
}

// Create 模拟底层接口方法。
func (m *MockPullRequestService) Create(arg0 context.Context, arg1 string, arg2 *scm.PullRequestInput) (*scm.PullRequest, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.PullRequest)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create 声明对 Create 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestService)(nil).Create), arg0, arg1, arg2)
}

// CreateComment 模拟底层接口方法。
func (m *MockPullRequestService) CreateComment(arg0 context.Context, arg1 string, arg2 int, arg3 *scm.CommentInput) (*scm.Comment, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Comment)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateComment 声明对 CreateComment 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) CreateComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockPullRequestService)(nil).CreateComment), arg0, arg1, arg2, arg3)
}

// DeleteComment 模拟底层接口方法。
func (m *MockPullRequestService) DeleteComment(arg0 context.Context, arg1 string, arg2, arg3 int) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment 声明对 DeleteComment 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) DeleteComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockPullRequestService)(nil).DeleteComment), arg0, arg1, arg2, arg3)
}

// Find 模拟底层接口方法。
func (m *MockPullRequestService) Find(arg0 context.Context, arg1 string, arg2 int) (*scm.PullRequest, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.PullRequest)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find 声明对 Find 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) Find(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPullRequestService)(nil).Find), arg0, arg1, arg2)
}

// FindComment 模拟底层接口方法。
func (m *MockPullRequestService) FindComment(arg0 context.Context, arg1 string, arg2, arg3 int) (*scm.Comment, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Comment)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindComment 声明对 FindComment 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) FindComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindComment", reflect.TypeOf((*MockPullRequestService)(nil).FindComment), arg0, arg1, arg2, arg3)
}

// List 模拟底层接口方法。
func (m *MockPullRequestService) List(arg0 context.Context, arg1 string, arg2 scm.PullRequestListOptions) ([]*scm.PullRequest, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.PullRequest)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List 声明对 List 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPullRequestService)(nil).List), arg0, arg1, arg2)
}

// ListChanges 模拟底层接口方法。
func (m *MockPullRequestService) ListChanges(arg0 context.Context, arg1 string, arg2 int, arg3 scm.ListOptions) ([]*scm.Change, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChanges", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*scm.Change)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListChanges 声明对 ListChanges 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) ListChanges(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChanges", reflect.TypeOf((*MockPullRequestService)(nil).ListChanges), arg0, arg1, arg2, arg3)
}

// ListComments 模拟底层接口方法。
func (m *MockPullRequestService) ListComments(arg0 context.Context, arg1 string, arg2 int, arg3 scm.ListOptions) ([]*scm.Comment, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*scm.Comment)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListComments 声明对 ListComments 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) ListComments(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockPullRequestService)(nil).ListComments), arg0, arg1, arg2, arg3)
}

// ListCommits 模拟底层接口方法。
func (m *MockPullRequestService) ListCommits(arg0 context.Context, arg1 string, arg2 int, arg3 scm.ListOptions) ([]*scm.Commit, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommits", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*scm.Commit)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCommits 声明对 ListCommits 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) ListCommits(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommits", reflect.TypeOf((*MockPullRequestService)(nil).ListCommits), arg0, arg1, arg2, arg3)
}

// Merge 模拟底层接口方法。
func (m *MockPullRequestService) Merge(arg0 context.Context, arg1 string, arg2 int) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge 声明对 Merge 的期望调用。
func (mr *MockPullRequestServiceMockRecorder) Merge(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPullRequestService)(nil).Merge), arg0, arg1, arg2)
}

// MockRepositoryService 是 RepositoryService 接口的 GoMock 模拟实现。
type MockRepositoryService struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryServiceMockRecorder
}

// MockRepositoryServiceMockRecorder 是 MockRepositoryService 的期望调用记录器。
type MockRepositoryServiceMockRecorder struct {
	mock *MockRepositoryService
}

// NewMockRepositoryService 创建新的模拟实例。
func NewMockRepositoryService(ctrl *gomock.Controller) *MockRepositoryService {
	mock := &MockRepositoryService{ctrl: ctrl}
	mock.recorder = &MockRepositoryServiceMockRecorder{mock}
	return mock
}

// EXPECT 返回用于声明期望调用的记录器对象。
func (m *MockRepositoryService) EXPECT() *MockRepositoryServiceMockRecorder {
	return m.recorder
}

// CreateHook 模拟底层接口方法。
func (m *MockRepositoryService) CreateHook(arg0 context.Context, arg1 string, arg2 *scm.HookInput) (*scm.Hook, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHook", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Hook)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateHook 声明对 CreateHook 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) CreateHook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHook", reflect.TypeOf((*MockRepositoryService)(nil).CreateHook), arg0, arg1, arg2)
}

// CreateStatus 模拟底层接口方法。
func (m *MockRepositoryService) CreateStatus(arg0 context.Context, arg1, arg2 string, arg3 *scm.StatusInput) (*scm.Status, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Status)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateStatus 声明对 CreateStatus 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) CreateStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStatus", reflect.TypeOf((*MockRepositoryService)(nil).CreateStatus), arg0, arg1, arg2, arg3)
}

// DeleteHook 模拟底层接口方法。
func (m *MockRepositoryService) DeleteHook(arg0 context.Context, arg1, arg2 string) (*scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHook", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteHook 声明对 DeleteHook 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) DeleteHook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHook", reflect.TypeOf((*MockRepositoryService)(nil).DeleteHook), arg0, arg1, arg2)
}

// Find 模拟底层接口方法。
func (m *MockRepositoryService) Find(arg0 context.Context, arg1 string) (*scm.Repository, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*scm.Repository)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find 声明对 Find 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepositoryService)(nil).Find), arg0, arg1)
}

// FindHook 模拟底层接口方法。
func (m *MockRepositoryService) FindHook(arg0 context.Context, arg1, arg2 string) (*scm.Hook, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindHook", arg0, arg1, arg2)
	ret0, _ := ret[0].(*scm.Hook)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindHook 声明对 FindHook 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) FindHook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindHook", reflect.TypeOf((*MockRepositoryService)(nil).FindHook), arg0, arg1, arg2)
}

// FindPerms 模拟底层接口方法。
func (m *MockRepositoryService) FindPerms(arg0 context.Context, arg1 string) (*scm.Perm, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPerms", arg0, arg1)
	ret0, _ := ret[0].(*scm.Perm)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPerms 声明对 FindPerms 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) FindPerms(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPerms", reflect.TypeOf((*MockRepositoryService)(nil).FindPerms), arg0, arg1)
}

// List 模拟底层接口方法。
func (m *MockRepositoryService) List(arg0 context.Context, arg1 scm.ListOptions) ([]*scm.Repository, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]*scm.Repository)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List 声明对 List 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepositoryService)(nil).List), arg0, arg1)
}

// ListHooks 模拟底层接口方法。
func (m *MockRepositoryService) ListHooks(arg0 context.Context, arg1 string, arg2 scm.ListOptions) ([]*scm.Hook, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHooks", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.Hook)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListHooks 声明对 ListHooks 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) ListHooks(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHooks", reflect.TypeOf((*MockRepositoryService)(nil).ListHooks), arg0, arg1, arg2)
}

// ListNamespace 模拟底层接口方法。
func (m *MockRepositoryService) ListNamespace(arg0 context.Context, arg1 string, arg2 scm.ListOptions) ([]*scm.Repository, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNamespace", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*scm.Repository)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListNamespace 声明对 ListNamespace 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) ListNamespace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNamespace", reflect.TypeOf((*MockRepositoryService)(nil).ListNamespace), arg0, arg1, arg2)
}

// ListStatus 模拟底层接口方法。
func (m *MockRepositoryService) ListStatus(arg0 context.Context, arg1, arg2 string, arg3 scm.ListOptions) ([]*scm.Status, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*scm.Status)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListStatus 声明对 ListStatus 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) ListStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStatus", reflect.TypeOf((*MockRepositoryService)(nil).ListStatus), arg0, arg1, arg2, arg3)
}

// ListV2 模拟底层接口方法。
func (m *MockRepositoryService) ListV2(arg0 context.Context, arg1 scm.RepoListOptions) ([]*scm.Repository, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListV2", arg0, arg1)
	ret0, _ := ret[0].([]*scm.Repository)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListV2 声明对 ListV2 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) ListV2(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListV2", reflect.TypeOf((*MockRepositoryService)(nil).ListV2), arg0, arg1)
}

// UpdateHook 模拟底层接口方法。
func (m *MockRepositoryService) UpdateHook(arg0 context.Context, arg1, arg2 string, arg3 *scm.HookInput) (*scm.Hook, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHook", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*scm.Hook)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateHook 声明对 UpdateHook 的期望调用。
func (mr *MockRepositoryServiceMockRecorder) UpdateHook(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHook", reflect.TypeOf((*MockRepositoryService)(nil).UpdateHook), arg0, arg1, arg2, arg3)
}

// MockUserService 是 UserService 接口的 GoMock 模拟实现。
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder 是 MockUserService 的期望调用记录器。
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService 创建新的模拟实例。
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT 返回用于声明期望调用的记录器对象。
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// Find 模拟底层接口方法。
func (m *MockUserService) Find(arg0 context.Context) (*scm.User, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(*scm.User)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Find 声明对 Find 的期望调用。
func (mr *MockUserServiceMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserService)(nil).Find), arg0)
}

// FindEmail 模拟底层接口方法。
func (m *MockUserService) FindEmail(arg0 context.Context) (string, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEmail", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindEmail 声明对 FindEmail 的期望调用。
func (mr *MockUserServiceMockRecorder) FindEmail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEmail", reflect.TypeOf((*MockUserService)(nil).FindEmail), arg0)
}

// FindLogin 模拟底层接口方法。
func (m *MockUserService) FindLogin(arg0 context.Context, arg1 string) (*scm.User, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLogin", arg0, arg1)
	ret0, _ := ret[0].(*scm.User)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindLogin 声明对 FindLogin 的期望调用。
func (mr *MockUserServiceMockRecorder) FindLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLogin", reflect.TypeOf((*MockUserService)(nil).FindLogin), arg0, arg1)
}

// ListEmail 模拟底层接口方法。
func (m *MockUserService) ListEmail(arg0 context.Context, arg1 scm.ListOptions) ([]*scm.Email, *scm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmail", arg0, arg1)
	ret0, _ := ret[0].([]*scm.Email)
	ret1, _ := ret[1].(*scm.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEmail 声明对 ListEmail 的期望调用。
func (mr *MockUserServiceMockRecorder) ListEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmail", reflect.TypeOf((*MockUserService)(nil).ListEmail), arg0, arg1)
}
