package pattern

// lexer 为 pattern 表达式提供 ragel 驱动的词法分析器封装，实现 exprLexer 接口并向 yacc 传递 IDENTIFIER/LITERAL token。

import "unicode/utf8"

type lexer struct {
	data        []byte
	p, pe, cs   int
	ts, te, act int

	lastnewline int
	curline     int

	errs []parseError
	expr []node
}

func newLexer() *lexer {
	lex := &lexer{}
	lex.init()
	return lex
}

func (lex *lexer) setData(data []byte) {
	lex.data = data
	lex.pe = len(data)
	lex.lastnewline = -1
	lex.curline = 1
}

// Error 将 yacc 报错转为带行列号的 parseError 并追加到 errs。
// Error implements exprLexer interface generated by yacc (yyLexer)
func (lex *lexer) Error(e string) {
	lex.errs = append(lex.errs, newParseError(e, lex.curline, lex.curcol()))
}

// curcol calculates the current token's start column based on the last newline position
// returns a 1-indexed value
// curcol 基于 lastnewline 计算当前 token 的 1-indexed 列号。
func (lex *lexer) curcol() int {
	return (lex.ts + 1 /* 1-indexed columns */) - (lex.lastnewline + 1 /* next after newline */)
}

func (lex *lexer) handle(token int, err error) int {
	if err != nil {
		lex.Error(err.Error())
		return LEXER_ERROR
	}
	return token
}

func (lex *lexer) token() string {
	return string(lex.data[lex.ts:lex.te])
}

// nolint
// identifier 解析 <name> 尖括号内的捕获标识符。
func (lex *lexer) identifier(out *exprSymType) (int, error) {
	t := lex.token()
	out.str = t[1 : len(t)-1]
	return IDENTIFIER, nil
}

// nolint
func (lex *lexer) literal(out *exprSymType) (int, error) {
	decoded, _ := utf8.DecodeRune(lex.data[lex.ts:lex.te])
	out.literal = decoded
	return LITERAL, nil
}
// Lex 由 ragel 生成的主循环调用 identifier/literal 动作回调。
