/*
 * Copyright 2002-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.keycloak;

import java.util.List;

/**
 * WebAuthn 认证/注册流程中 UA 与 RP 之间 FreeMarker 模板绑定的常量名。
 */
public interface WebAuthnConstants {

    // FreeMarker 模板在 UA 与 RP 之间绑定的接口字段
    // Interface binded by FreeMarker template between UA and RP
    /** 用户 ID 表单字段名。 */
    String USER_ID = "userid";
    /** 用户名字段名。 */
    String USER_NAME = "username";
    /** 挑战值字段名。 */
    String CHALLENGE = "challenge";
    /** 来源（origin）字段名。 */
    String ORIGIN = "origin";
    /** 错误信息字段名。 */
    String ERROR = "error";
    /** 公钥凭据 ID 字段名。 */
    String PUBLIC_KEY_CREDENTIAL_ID = "publicKeyCredentialId";
    /** 凭据 ID 字段名。 */
    String CREDENTIAL_ID = "credentialId";
    /** clientDataJSON 字段名。 */
    String CLIENT_DATA_JSON = "clientDataJSON";
    /** authenticatorData 字段名。 */
    String AUTHENTICATOR_DATA = "authenticatorData";
    /** 签名字段名。 */
    String SIGNATURE = "signature";
    /** userHandle 字段名。 */
    String USER_HANDLE = "userHandle";
    /** attestationObject 字段名。 */
    String ATTESTATION_OBJECT = "attestationObject";
    /** 认证器展示标签字段名。 */
    String AUTHENTICATOR_LABEL = "authenticatorLabel";
    /** RP 实体名字段名。 */
    String RP_ENTITY_NAME = "rpEntityName";
    /** 签名算法列表字段名。 */
    String SIGNATURE_ALGORITHMS = "signatureAlgorithms";
    /** Relying Party ID 字段名。 */
    String RP_ID = "rpId";
    /** 认证传达偏好字段名。 */
    String ATTESTATION_CONVEYANCE_PREFERENCE = "attestationConveyancePreference";
    /** 认证器附着方式字段名。 */
    String AUTHENTICATOR_ATTACHMENT = "authenticatorAttachment";
    /** 平台内置认证器附着值。 */
    String AUTHENTICATOR_ATTACHMENT_PLATFORM = "platform";
    /** 跨平台认证器附着值。 */
    String AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM = "cross-platform";
    /** 支持的认证器附着方式列表。 */
    List<String> SUPPORTED_AUTHENTICATOR_ATTACHMENTS = List.of(AUTHENTICATOR_ATTACHMENT_PLATFORM, AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM);
    /** 是否要求 resident key 字段名。 */
    String REQUIRE_RESIDENT_KEY = "requireResidentKey";
    /** resident key 策略字段名。 */
    String RESIDENT_KEY = "residentKey";
    /** 用户验证要求字段名。 */
    String USER_VERIFICATION_REQUIREMENT = "userVerificationRequirement";
    /** 创建操作超时字段名。 */
    String CREATE_TIMEOUT = "createTimeout";
    /** 排除凭据 ID 列表字段名。 */
    String EXCLUDE_CREDENTIAL_IDS = "excludeCredentialIds";
    /** 允许的认证器列表字段名。 */
    String ALLOWED_AUTHENTICATORS = "authenticators";
    /** 用户是否已识别标志字段名。 */
    String IS_USER_IDENTIFIED = "isUserIdentified";
    /** 用户验证选项字段名。 */
    String USER_VERIFICATION = "userVerification";
    /** 传输方式字段名。 */
    String TRANSPORTS = "transports";
    /** 是否启用 WebAuthn 条件式 UI 字段名。 */
    String ENABLE_WEBAUTHN_CONDITIONAL_UI = "enableWebAuthnConditionalUI";
    /** mediation 模式字段名。 */
    String MEDIATION = "mediation";

    /** 是否为重试设置标志字段名。 */
    String IS_SET_RETRY = "isSetRetry";
    /** 是否展示认证器列表字段名。 */
    String SHOULD_DISPLAY_AUTHENTICATORS = "shouldDisplayAuthenticators";

    // 存储 RP（Keycloak）生成挑战值的 AuthenticationSession 属性键
    // key for storing onto AuthenticationSessionModel's Attribute challenge generated by RP(keycloak)
    /** WebAuthn 挑战值 auth note 键。 */
    String AUTH_CHALLENGE_NOTE = "WEBAUTH_CHALLENGE";

    /* WebAuthn 事件键 */

    // navigator.credentials.create() 生成的凭据 ID 事件键
    // Event key for credential id generated by navigator.credentials.create()
    /** 公钥凭据 ID 事件属性键。 */
    String PUBKEY_CRED_ID_ATTR = "public_key_credential_id";

    // 公钥凭据用户可编辑元数据事件键
    // Event key for Public Key Credential's user-editable metadata
    /** 公钥凭据标签事件属性键。 */
    String PUBKEY_CRED_LABEL_ATTR = "public_key_credential_label";

    // 公钥凭据 AAGUID 事件键
    // Event key for Public Key Credential's AAGUID
    /** 公钥凭据 AAGUID 事件属性键。 */
    String PUBKEY_CRED_AAGUID_ATTR = "public_key_credential_aaguid";

    /** 用户验证已检查标志。 */
    String USER_VERIFICATION_CHECKED = "web_authn_authenticator_user_verification_checked";
    /** 已认证用户 ID 属性键。 */
    String AUTHENTICATED_USER_ID = "web_authn_authenticated_user_id";
    /** 首次认证用户 ID 属性键。 */
    String FIRST_AUTHENTICATED_USER_ID = "first_authenticated_user_id";

    /** WebAuthn 认证错误标签。 */
    String AUTH_ERR_LABEL = "web_authn_authentication_error";
    /** WebAuthn 认证错误详情标签。 */
    String AUTH_ERR_DETAIL_LABEL = "web_authn_authentication_error_detail";

    /** WebAuthn 注册错误标签。 */
    String REG_ERR_LABEL = "web_authn_registration_error";
    /** WebAuthn 注册错误详情标签。 */
    String REG_ERR_DETAIL_LABEL = "web_authn_registration_error_detail";

}
