/*
 * Copyright 2016 The Netty Project
 *
 * The Netty Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.netty.util.internal;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.List;

/**
 * 异常/堆栈相关内部工具。
 */
public final class ThrowableUtil {

    private ThrowableUtil() { }

    /**
     * Set the {@link StackTraceElement} for the given {@link Throwable}, using the {@link Class} and method name.
     
 *
 * <p>用类名与方法名构造单帧堆栈并设置到 cause 上。</p>
 */
    public static <T extends Throwable> T unknownStackTrace(T cause, Class<?> clazz, String method) {
        cause.setStackTrace(new StackTraceElement[] { new StackTraceElement(clazz.getName(), method, null, -1)});
        return cause;
    }

    /**
     * Gets the stack trace from a Throwable as a String.
     *
     * @param cause the {@link Throwable} to be examined
     * @return the stack trace as generated by {@link Throwable#printStackTrace(java.io.PrintWriter)} method.
     
 *
 * <p>将异常堆栈打印为字符串（已废弃）。</p>
 */
    @Deprecated
    public static String stackTraceToString(Throwable cause) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintStream pout = new PrintStream(out);
        cause.printStackTrace(pout);
        pout.flush();
        try {
            return out.toString();
        } finally {
            try {
                out.close();
            } catch (IOException ignore) {
                // 不应发生，忽略
            }
        }
    }

    /** 是否支持 suppressed 异常（Java 7+ 恒为 true）。 */
    @Deprecated
    public static boolean haveSuppressed() {
        return true;
    }

    /** 若 suppressed 非 null 则添加到 target。 */
    public static void addSuppressed(Throwable target, Throwable suppressed) {
        if (suppressed != null) {
            target.addSuppressed(suppressed);
        }
    }

    /** 批量 addSuppressed 后清空列表。 */
    public static void addSuppressedAndClear(Throwable target, List<Throwable> suppressed) {
        addSuppressed(target, suppressed);
        suppressed.clear();
    }

    /** 将列表中所有 suppressed 异常添加到 target。 */
    public static void addSuppressed(Throwable target, List<Throwable> suppressed) {
        for (Throwable t : suppressed) {
            addSuppressed(target, t);
        }
    }

    /** 获取 suppressed 异常数组。 */
    public static Throwable[] getSuppressed(Throwable source) {
        return source.getSuppressed();
    }

    /**
     * Capture the stack trace of the given thread, interrupt it, and attach the stack trace as a suppressed exception
     * to the given cause.
     * @param thread The thread to interrupt.
     * @param cause The cause to attach a stack trace to.
     
 *
 * <p>捕获线程堆栈、中断该线程，并将 InterruptedException 作为 suppressed 附加到 cause。</p>
 */
    public static void interruptAndAttachAsyncStackTrace(Thread thread, Throwable cause) {
        Thread.State state = thread.getState();
        StackTraceElement[] stackTrace = thread.getStackTrace();
        InterruptedException asyncIE = new InterruptedException(
                "Asynchronous interruption: " + thread + " (" + state + ')');
        thread.interrupt();
        asyncIE.setStackTrace(stackTrace);
        addSuppressed(cause, asyncIE);
    }
}
