/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.12.08 at 05:45:20 PM CST
//

package org.keycloak.dom.saml.v2.ac;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PrivateKeyProtectionType complex type.
 * SAML 2.0 私钥保护类型：描述密钥激活、存储、共享及扩展元素。

 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PrivateKeyProtectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:2.0:ac}KeyActivation" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:2.0:ac}KeyStorage" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:2.0:ac}KeySharing" minOccurs="0"/>
 *         &lt;element ref="{urn:oasis:names:tc:SAML:2.0:ac}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrivateKeyProtectionType", propOrder = {"keyActivation", "keyStorage", "keySharing", "extension"})
public class PrivateKeyProtectionType {

    @XmlElement(name = "KeyActivation")
    protected KeyActivationType keyActivation;
    @XmlElement(name = "KeyStorage")
    protected KeyStorageType keyStorage;
    @XmlElement(name = "KeySharing")
    protected KeySharingType keySharing;
    @XmlElement(name = "Extension")
    protected List<ExtensionType> extension;

    /**
     * 获取 密钥激活 属性的值。
     *
     * Gets the value of the keyActivation property.
     *
     * @return possible object is {@link KeyActivationType }
     */
    public KeyActivationType getKeyActivation() {
        return keyActivation;
    }

    /**
     * 设置 密钥激活 属性的值。
     *
     * Sets the value of the keyActivation property.
     *
     * @param value allowed object is {@link KeyActivationType }
     */
    public void setKeyActivation(KeyActivationType value) {
        this.keyActivation = value;
    }

    /**
     * 获取 密钥存储 属性的值。
     *
     * Gets the value of the keyStorage property.
     *
     * @return possible object is {@link KeyStorageType }
     */
    public KeyStorageType getKeyStorage() {
        return keyStorage;
    }

    /**
     * 设置 密钥存储 属性的值。
     *
     * Sets the value of the keyStorage property.
     *
     * @param value allowed object is {@link KeyStorageType }
     */
    public void setKeyStorage(KeyStorageType value) {
        this.keyStorage = value;
    }

    /**
     * 获取 密钥共享 属性的值。
     *
     * Gets the value of the keySharing property.
     *
     * @return possible object is {@link KeySharingType }
     */
    public KeySharingType getKeySharing() {
        return keySharing;
    }

    /**
     * 设置 密钥共享 属性的值。
     *
     * Sets the value of the keySharing property.
     *
     * @param value allowed object is {@link KeySharingType }
     */
    public void setKeySharing(KeySharingType value) {
        this.keySharing = value;
    }

    /**
     * 获取 扩展（Extension） 元素列表。
     *
     * Gets the value of the extension property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the
     * returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the
     * extension property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ExtensionType }
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

}
