/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JavaCC: Do not edit this line. SelectorParserConstants.java */
package org.apache.rocketmq.filter.parser;

/**
 * 选择器词法分析器 token 字面量与序号常量。
 * <p>由 JavaCC {@code OtherFilesGen} 自动生成，勿手工修改。</p>
 */
public interface SelectorParserConstants {

    /** 文件结束标记。 */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int LINE_COMMENT = 6;
    /**
     * RegularExpression Id.
     */
    int BLOCK_COMMENT = 7;
    /** 关键字 NOT 的 token 序号。 */
    int NOT = 8;
    /** 逻辑与 AND。 */
    int AND = 9;
    /** 逻辑或 OR。 */
    int OR = 10;
    /**
     * RegularExpression Id.
     */
    int BETWEEN = 11;
    /** 集合成员 IN 运算符。 */
    int IN = 12;
    /**
     * RegularExpression Id.
     */
    int TRUE = 13;
    /**
     * RegularExpression Id.
     */
    int FALSE = 14;
    /**
     * RegularExpression Id.
     */
    int NULL = 15;
    /**
     * RegularExpression Id.
     */
    int IS = 16;
    /**
     * RegularExpression Id.
     */
    int CONTAINS = 17;
    /**
     * RegularExpression Id.
     */
    int STARTSWITH = 18;
    /**
     * RegularExpression Id.
     */
    int ENDSWITH = 19;
    /**
     * RegularExpression Id.
     */
    int DECIMAL_LITERAL = 20;
    /**
     * RegularExpression Id.
     */
    int FLOATING_POINT_LITERAL = 21;
    /**
     * RegularExpression Id.
     */
    int EXPONENT = 22;
    /**
     * RegularExpression Id.
     */
    int STRING_LITERAL = 23;
    /** 标识符 token。 */
    int ID = 24;

    /** 默认词法状态。 */
    int DEFAULT = 0;

    /** 各 token 序号对应的可读字面量描述。 */
    String[] TOKEN_IMAGE = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"\\f\"",
        "<LINE_COMMENT>",
        "<BLOCK_COMMENT>",
        "\"NOT\"",
        "\"AND\"",
        "\"OR\"",
        "\"BETWEEN\"",
        "\"IN\"",
        "\"TRUE\"",
        "\"FALSE\"",
        "\"NULL\"",
        "\"IS\"",
        "\"CONTAINS\"",
        "\"STARTSWITH\"",
        "\"ENDSWITH\"",
        "<DECIMAL_LITERAL>",
        "<FLOATING_POINT_LITERAL>",
        "<EXPONENT>",
        "<STRING_LITERAL>",
        "<ID>",
        "\"=\"",
        "\"<>\"",
        "\">\"",
        "\">=\"",
        "\"<\"",
        "\"<=\"",
        "\"(\"",
        "\",\"",
        "\")\"",
        "\"+\"",
        "\"-\"",
    };

}
