#!/usr/bin/env python3
"""Generate wave50b_replacements_rocketmq_store.py for store/tieredstore [15:30]."""
from __future__ import annotations

from pathlib import Path

OUT = Path("/workspace/scripts/wave50b_replacements_rocketmq_store.py")

R: dict[str, list[tuple[str, str]]] = {}

# --- ConsumeQueueStore ---
_CQS = "store/src/main/java/org/apache/rocketmq/store/queue/ConsumeQueueStore.java"
R[_CQS] = [
    ("public class ConsumeQueueStore extends AbstractConsumeQueueStore {",
     "/**\n * 默认 ConsumeQueue 存储实现：基于 MappedFile 管理 SimpleCQ/BatchCQ，\n * 提供刷盘、恢复、清理及逻辑 offset 校正等后台服务。\n */\npublic class ConsumeQueueStore extends AbstractConsumeQueueStore {"),
    ("    private final FlushConsumeQueueService flushConsumeQueueService;",
     "    /** CQ 定时刷盘服务。 */\n    private final FlushConsumeQueueService flushConsumeQueueService;"),
    ("    private final CorrectLogicOffsetService correctLogicOffsetService;",
     "    /** 逻辑 offset 校正服务（CommitLog 与 CQ 不一致时修复）。 */\n    private final CorrectLogicOffsetService correctLogicOffsetService;"),
    ("    private final CleanConsumeQueueService cleanConsumeQueueService;",
     "    /** 过期 CQ 文件清理服务。 */\n    private final CleanConsumeQueueService cleanConsumeQueueService;"),
    ("    private final AtomicInteger lmqCounter = new AtomicInteger(0);",
     "    /** LMQ（Light Message Queue）计数器。 */\n    private final AtomicInteger lmqCounter = new AtomicInteger(0);"),
    ("    public ConsumeQueueStore(DefaultMessageStore messageStore) {",
     "    /** 构造并初始化刷盘/校正/清理三个后台服务。 */\n    public ConsumeQueueStore(DefaultMessageStore messageStore) {"),
    ("    public void start() {",
     "    /** 启动刷盘服务并注册定时清理任务。 */\n    public void start() {"),
    ("    private void cleanQueueFilesPeriodically() {",
     "    /** 周期性执行逻辑 offset 校正与过期文件清理。 */\n    private void cleanQueueFilesPeriodically() {"),
    ("    public boolean load() {",
     "    /** 加载 SimpleCQ 与 BatchCQ 目录下的全部队列文件。 */\n    public boolean load() {"),
    ("    public void recover(boolean concurrently) {",
     "    /** 恢复全部 ConsumeQueue；{@code concurrently} 为 true 时并行恢复。 */\n    public void recover(boolean concurrently) {"),
    ("    /**\n     * Implementation of CommitLogDispatchStore.getDispatchFromPhyOffset() (inherited from ConsumeQueueStoreInterface).\n     * When recoverNormally is false, returns checkpoint's logicsPhysicalOffset so commitlog abnormal recovery starts\n     * from it.\n     */",
     "    /**\n     * {@link CommitLogDispatchStore#getDispatchFromPhyOffset()} 的实现。\n     * 正常恢复返回 CQ 最大物理 offset；异常恢复返回 checkpoint 的 logicsPhysicalOffset。\n     */"),
    ("    public boolean recoverConcurrently() {",
     "    /** 线程池并行恢复全部 ConsumeQueue。 */\n    public boolean recoverConcurrently() {"),
    ("    /**\n     * @param loadAfterDestroy file version cq do not need reload, so ignore\n     */",
     "    /**\n     * 销毁全部 CQ；{@code loadAfterDestroy} 对文件版 CQ 无意义，忽略。\n     * @param loadAfterDestroy 销毁后是否重新加载（文件版 CQ 忽略）\n     */"),
    ("    public void cleanExpired(long minCommitLogOffset) {",
     "    /** 清理物理 offset 小于 {@code minCommitLogOffset} 的过期 CQ 条目。 */\n    public void cleanExpired(long minCommitLogOffset) {"),
    ("    public void truncateDirty(long offsetToTruncate) {",
     "    /** 截断全部 CQ 中物理 offset 大于 {@code offsetToTruncate} 的脏文件。 */\n    public void truncateDirty(long offsetToTruncate) {"),
]

# --- RocksDBConsumeQueue ---
_RDBCQ = "store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueue.java"
R[_RDBCQ] = [
    ("public class RocksDBConsumeQueue implements ConsumeQueueInterface {",
     "/**\n * RocksDB 版 ConsumeQueue 门面：逻辑存储委托 {@link RocksDBConsumeQueueStore}，\n * 本类主要实现 {@link ConsumeQueueInterface} 的 offset/拉取/估算等 API。\n */\npublic class RocksDBConsumeQueue implements ConsumeQueueInterface {"),
    ("    private final MessageStoreConfig messageStoreConfig;",
     "    /** Broker 存储配置。 */\n    private final MessageStoreConfig messageStoreConfig;"),
    ("    private final RocksDBConsumeQueueStore consumeQueueStore;",
     "    /** 底层 RocksDB CQ 存储引擎。 */\n    private final RocksDBConsumeQueueStore consumeQueueStore;"),
    ("    private final String topic;",
     "    /** Topic 名称。 */\n    private final String topic;"),
    ("    private final int queueId;",
     "    /** 队列 ID。 */\n    private final int queueId;"),
    ("    /**\n     * Only used to pass parameters when calling the destroy method\n     *\n     * @see RocksDBConsumeQueueStore#destroy(ConsumeQueueInterface)\n     */",
     "    /**\n     * 仅用于 {@link RocksDBConsumeQueueStore#destroy(ConsumeQueueInterface)} 传参。\n     *\n     * @see RocksDBConsumeQueueStore#destroy(ConsumeQueueInterface)\n     */"),
    ("    /**\n     * We already implement it in RocksDBConsumeQueueStore.\n     * @see RocksDBConsumeQueueStore#getOffsetInQueueByTime\n     * @param timestamp timestamp\n     * @return\n     */",
     "    /**\n     * 已在 {@link RocksDBConsumeQueueStore} 中实现，此处返回 0。\n     * @see RocksDBConsumeQueueStore#getOffsetInQueueByTime\n     * @param timestamp 目标时间戳\n     * @return 占位返回值 0\n     */"),
    ("    /**\n     * We already implement it in RocksDBConsumeQueueStore.\n     * @see RocksDBConsumeQueueStore#getOffsetInQueueByTime\n     * @param timestamp    timestamp\n     * @param boundaryType Lower or Upper\n     * @return\n     */",
     "    /**\n     * 已在 {@link RocksDBConsumeQueueStore} 中实现，此处返回 0。\n     * @see RocksDBConsumeQueueStore#getOffsetInQueueByTime\n     * @param timestamp 目标时间戳\n     * @param boundaryType 下界或上界\n     * @return 占位返回值 0\n     */"),
    ("    /**\n     * Ignored, we already implement this method\n     * @see org.apache.rocketmq.store.queue.RocksDBConsumeQueueOffsetTable#getMinCqOffset(String, int)\n     */",
     "    /**\n     * 空实现；最小 offset 校正见 {@link RocksDBConsumeQueueOffsetTable#getMinCqOffset(String, int)}。\n     */"),
    ("    /**\n     * Ignored, in rocksdb mode, we build cq in RocksDBConsumeQueueStore\n     */",
     "    /** 空实现；RocksDB 模式下 CQ 条目由 {@link RocksDBConsumeQueueStore} 构建。 */"),
    ("    /**\n     * It is CPU-intensive with many offline group\n     * Optimize by caching their estimated info\n     */",
     "    /**\n     * 估算指定 offset 区间内匹配过滤器的消息数（采样统计）。\n     * 离线消费组较多时 CPU 开销大，可缓存估算结果优化。\n     */"),
    ("            // we will recover topic queue table from rocksdb when we use it.",
     "            // 首次使用时从 RocksDB 恢复 topic-queue offset 表"),
    ("    public void assignQueueOffset(QueueOffsetOperator queueOffsetOperator, MessageExtBrokerInner msg) throws RocksDBException {",
     "    /** 为消息分配 queueOffset，必要时从 RocksDB 恢复 offset 计数器。 */\n    public void assignQueueOffset(QueueOffsetOperator queueOffsetOperator, MessageExtBrokerInner msg) throws RocksDBException {"),
    ("    public void increaseQueueOffset(QueueOffsetOperator queueOffsetOperator, MessageExtBrokerInner msg, short messageNum) {",
     "    /** 批量发送后递增 queueOffset 计数器。 */\n    public void increaseQueueOffset(QueueOffsetOperator queueOffsetOperator, MessageExtBrokerInner msg, short messageNum) {"),
]

# --- RocksDBConsumeQueueOffsetTable ---
_RDBOFT = "store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueOffsetTable.java"
R[_RDBOFT] = [
    ("public class RocksDBConsumeQueueOffsetTable {",
     "/**\n * RocksDB ConsumeQueue Offset 表：维护 topic-queue 的 min/max 物理 offset\n * 与 CQ 逻辑 offset 映射，支持按时间查 offset 与 checkpoint 记录。\n */\npublic class RocksDBConsumeQueueOffsetTable {"),
    ("    /**\n     * Rocksdb ConsumeQueue's Offset unit. Format:\n     *\n     * <pre>\n     * ┌─────────────────────────┬───────────┬───────────────────────┬───────────┬───────────┬───────────┬─────────────┐\n     * │ Topic Bytes Array Size  │  CTRL_1   │   Topic Bytes Array   │  CTRL_1   │  Max(Min) │  CTRL_1   │   QueueId   │\n     * │        (4 Bytes)        │ (1 Bytes) │       (n Bytes)       │ (1 Bytes) │ (3 Bytes) │ (1 Bytes) │  (4 Bytes)  │\n     * ├─────────────────────────┴───────────┴───────────────────────┴───────────┴───────────┴───────────┴─────────────┤\n     * │                                                    Key Unit                                                   │\n     * │                                                                                                               │\n     * </pre>\n     *\n     * <pre>\n     * ┌─────────────────────────────┬────────────────────────┐\n     * │  CommitLog Physical Offset  │   ConsumeQueue Offset  │\n     * │        (8 Bytes)            │    (8 Bytes)           │\n     * ├─────────────────────────────┴────────────────────────┤\n     * │                     Value Unit                       │\n     * │                                                      │\n     * </pre>\n     * ConsumeQueue's Offset unit. Size: CommitLog Physical Offset(8) + ConsumeQueue Offset(8) =  16 Bytes\n     */",
     "    /**\n     * RocksDB CQ Offset 键值格式说明：\n     * Key = Topic 长度 + CTRL_1 + Topic 字节 + CTRL_1 + Max/Min 标记 + CTRL_1 + QueueId\n     * Value = CommitLog 物理 offset(8) + CQ 逻辑 offset(8)，共 16 字节。\n     */"),
    ("    /**\n     * We use a new system topic='CHECKPOINT_TOPIC' to record the maxPhyOffset built by CQ dispatch thread.",
     "    /**\n     * 使用系统 Topic {@code CHECKPOINT_TOPIC} 记录 CQ 分发线程已构建的最大物理 offset。"),
    ("    static final int OFFSET_PHY_OFFSET = 0;",
     "    /** Value 中 CommitLog 物理 offset 起始位置。 */\n    static final int OFFSET_PHY_OFFSET = 0;"),
    ("    static final int OFFSET_CQ_OFFSET = 8;",
     "    /** Value 中 CQ 逻辑 offset 起始位置。 */\n    static final int OFFSET_CQ_OFFSET = 8;"),
    ("    private static final byte[] MAX_BYTES = \"max\".getBytes(StandardCharsets.UTF_8);",
     "    /** Key 中 max offset 标记字节。 */\n    private static final byte[] MAX_BYTES = \"max\".getBytes(StandardCharsets.UTF_8);"),
    ("    private static final byte[] MIN_BYTES = \"min\".getBytes(StandardCharsets.UTF_8);",
     "    /** Key 中 min offset 标记字节。 */\n    private static final byte[] MIN_BYTES = \"min\".getBytes(StandardCharsets.UTF_8);"),
    ("    public static final int OFFSET_KEY_LENGTH_WITHOUT_TOPIC_BYTES = 4 + 1 + 1 + 3 + 1 + 4;",
     "    /** 不含 Topic 字节的 Key 固定长度。 */\n    public static final int OFFSET_KEY_LENGTH_WITHOUT_TOPIC_BYTES = 4 + 1 + 1 + 3 + 1 + 4;"),
    ("    private static final int OFFSET_VALUE_LENGTH = 8 + 8;",
     "    /** Value 固定长度：物理 offset + 逻辑 offset。 */\n    private static final int OFFSET_VALUE_LENGTH = 8 + 8;"),
]

# --- RocksDBConsumeQueueStore ---
_RDBST = "store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueStore.java"
R[_RDBST] = [
    ("public class RocksDBConsumeQueueStore extends AbstractConsumeQueueStore {",
     "/**\n * RocksDB 版 ConsumeQueue 存储：使用两张表分别存 CQ 单元与 offset 映射，\n * 通过 {@link RocksGroupCommitService} 批量写入并触发长轮询通知。\n */\npublic class RocksDBConsumeQueueStore extends AbstractConsumeQueueStore {"),
    ("    /**\n     * we use two tables with different ColumnFamilyHandle, called RocksDBConsumeQueueTable and RocksDBConsumeQueueOffsetTable.\n     * 1.RocksDBConsumeQueueTable uses to store CqUnit[physicalOffset, msgSize, tagHashCode, msgStoreTime]\n     * 2.RocksDBConsumeQueueOffsetTable uses to store physicalOffset and consumeQueueOffset(@see PhyAndCQOffset) of topic-queueId\n     */",
     "    /**\n     * 两张 RocksDB 表：\n     * 1. {@link RocksDBConsumeQueueTable} 存 CqUnit（物理 offset、消息大小、Tag 哈希、存储时间）\n     * 2. {@link RocksDBConsumeQueueOffsetTable} 存 topic-queue 的物理/逻辑 offset 映射\n     */"),
    ("    private final ConsumeQueueRocksDBStorage rocksDBStorage;",
     "    /** RocksDB 底层存储引擎。 */\n    private final ConsumeQueueRocksDBStorage rocksDBStorage;"),
    ("    private final RocksDBConsumeQueueTable rocksDBConsumeQueueTable;",
     "    /** CQ 单元表。 */\n    private final RocksDBConsumeQueueTable rocksDBConsumeQueueTable;"),
    ("    private final RocksDBConsumeQueueOffsetTable rocksDBConsumeQueueOffsetTable;",
     "    /** CQ offset 映射表。 */\n    private final RocksDBConsumeQueueOffsetTable rocksDBConsumeQueueOffsetTable;"),
    ("    private volatile boolean isCQError = false;",
     "    /** CQ 写入是否发生不可恢复错误。 */\n    private volatile boolean isCQError = false;"),
    ("    private final RocksGroupCommitService groupCommitService;",
     "    /** RocksDB CQ 批量提交服务。 */\n    private final RocksGroupCommitService groupCommitService;"),
    ("    /**\n     * there are two threads to notify longPolling when build cq successfully\n     *\n     * @see DefaultMessageStore.ReputMessageService#doReput()\n     * @see RocksGroupCommitService#groupCommit()\n     * <p>\n     * RocksDB CQ is build by RocksGroupCommitService, so we do not need to notify longPolling in\n     * ReputMessageService\n     */",
     "    /**\n     * 构造 RocksDB CQ 存储；CQ 由 {@link RocksGroupCommitService} 构建，\n     * 因此 {@link DefaultMessageStore.ReputMessageService} 无需再通知长轮询。\n     *\n     * @see DefaultMessageStore.ReputMessageService#doReput()\n     * @see RocksGroupCommitService#groupCommit()\n     */"),
    ("        if (checkFile.isFile()) { // probably used rocksdb in original/separate path",
     "        if (checkFile.isFile()) { // 检测到路径配置与已有 RocksDB 数据不兼容"),
    ("    public void start() {",
     "    /** 启动 RocksDB 引擎、批量提交与清理服务。 */\n    public void start() {"),
    ("    public boolean load() {",
     "    /** 加载 RocksDB 数据并恢复 offset 表。 */\n    public boolean load() {"),
    ("    public void recover(boolean concurrently) throws RocksDBException {",
     "    /** 恢复 RocksDB CQ；RocksDB 模式下恢复逻辑在 load 阶段完成。 */\n    public void recover(boolean concurrently) throws RocksDBException {"),
]

# --- SparseConsumeQueue ---
_SCQ = "store/src/main/java/org/apache/rocketmq/store/queue/SparseConsumeQueue.java"
R[_SCQ] = [
    ("public class SparseConsumeQueue extends BatchConsumeQueue {",
     "/**\n * 稀疏 Batch ConsumeQueue：BatchCQ 的变体，恢复时从倒数第三个 MappedFile 开始扫描，\n * 适用于批量消息场景下减少无效文件遍历。\n */\npublic class SparseConsumeQueue extends BatchConsumeQueue {"),
    ("    public void recover() {",
     "    /** 从倒数第三个 MappedFile 起扫描恢复，定位最后有效 CQ 条目。 */\n    public void recover() {"),
    ("                    byteBuffer.getLong();   //tagscode",
     "                    byteBuffer.getLong();   // Tag 哈希码"),
    ("                    byteBuffer.getLong();   //timestamp",
     "                    byteBuffer.getLong();   // 消息存储时间戳"),
    ("    public void putEndPositionInfo(MappedFile mappedFile) {",
     "    /** 在 MappedFile 末尾写入结束标记（稀疏 CQ 专用）。 */\n    public void putEndPositionInfo(MappedFile mappedFile) {"),
    ("    public boolean shouldRoll() {",
     "    /** 判断当前 MappedFile 是否应滚动到新文件。 */\n    public boolean shouldRoll() {"),
    ("    public boolean containsOffsetFile(final long physicalOffset) {",
     "    /** 判断指定物理 offset 是否落在当前 CQ 文件范围内。 */\n    public boolean containsOffsetFile(final long physicalOffset) {"),
    ("    public long getMaxPhyOffsetInLog() {",
     "    /** 返回 CommitLog 中已索引的最大物理 offset。 */\n    public long getMaxPhyOffsetInLog() {"),
    ("    public long getMaxMsgOffsetFromFile(String simpleFileName) {",
     "    /** 从指定 CQ 文件名解析最大消息物理 offset。 */\n    public long getMaxMsgOffsetFromFile(String simpleFileName) {"),
    ("    public void refresh() {",
     "    /** 刷新稀疏 CQ 内存状态与 MappedFile 队列。 */\n    public void refresh() {"),
]

# --- MessageRocksDBStorage ---
_MRS = "store/src/main/java/org/apache/rocketmq/store/rocksdb/MessageRocksDBStorage.java"
R[_MRS] = [
    ("public class MessageRocksDBStorage extends AbstractRocksDBStorage {",
     "/**\n * 消息 RocksDB 统一存储：管理 index/timer/trans 三个 ColumnFamily，\n * 为定时消息、事务消息及索引提供 KV 持久化能力。\n */\npublic class MessageRocksDBStorage extends AbstractRocksDBStorage {"),
    ("    private static final String ROCKSDB_MESSAGE_DIRECTORY = \"rocksdbstore\";",
     "    /** RocksDB 数据目录名。 */\n    private static final String ROCKSDB_MESSAGE_DIRECTORY = \"rocksdbstore\";"),
    ("    public static final byte[] TIMER_COLUMN_FAMILY = \"timer\".getBytes(StandardCharsets.UTF_8);",
     "    /** 定时消息 ColumnFamily 名称。 */\n    public static final byte[] TIMER_COLUMN_FAMILY = \"timer\".getBytes(StandardCharsets.UTF_8);"),
    ("    public static final byte[] TRANS_COLUMN_FAMILY = \"trans\".getBytes(StandardCharsets.UTF_8);",
     "    /** 事务消息 ColumnFamily 名称。 */\n    public static final byte[] TRANS_COLUMN_FAMILY = \"trans\".getBytes(StandardCharsets.UTF_8);"),
    ("    public static final byte[] SYS_TOPIC_SCAN_OFFSET_CHECK_POINT = \"sys_topic_scan_offset_checkpoint\".getBytes(StandardCharsets.UTF_8);",
     "    /** 定时系统 Topic 扫描 offset 检查点键。 */\n    public static final byte[] SYS_TOPIC_SCAN_OFFSET_CHECK_POINT = \"sys_topic_scan_offset_checkpoint\".getBytes(StandardCharsets.UTF_8);"),
    ("    public static final byte[] TIMELINE_CHECK_POINT = \"timeline_checkpoint\".getBytes(StandardCharsets.UTF_8);",
     "    /** Timeline 处理进度检查点键。 */\n    public static final byte[] TIMELINE_CHECK_POINT = \"timeline_checkpoint\".getBytes(StandardCharsets.UTF_8);"),
    ("    private volatile ColumnFamilyHandle timerCFHandle;",
     "    /** 定时消息 ColumnFamily 句柄。 */\n    private volatile ColumnFamilyHandle timerCFHandle;"),
    ("    private volatile ColumnFamilyHandle transCFHandle;",
     "    /** 事务消息 ColumnFamily 句柄。 */\n    private volatile ColumnFamilyHandle transCFHandle;"),
    ("    private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);",
     "    /** 定时 flush timer CF WAL 的调度器。 */\n    private final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);"),
    ("    public MessageRocksDBStorage(MessageStoreConfig messageStoreConfig) {",
     "    /** 初始化 RocksDB 路径并启动存储引擎。 */\n    public MessageRocksDBStorage(MessageStoreConfig messageStoreConfig) {"),
    ("    protected boolean postLoad() {",
     "    /** 打开 index/timer/trans 三个 ColumnFamily 并注册定时 flush 任务。 */\n    protected boolean postLoad() {"),
    ("                    log.info(\"MessageRocksDBStorage flush timer wal success\");",
     "                    log.info(\"MessageRocksDBStorage 定时 flush timer WAL 成功\");"),
]

# --- BrokerStatsManager ---
_BSM = "store/src/main/java/org/apache/rocketmq/store/stats/BrokerStatsManager.java"
R[_BSM] = [
    ("public class BrokerStatsManager {",
     "/**\n * Broker 统计管理器：聚合 Topic/Queue/Group 维度的收发 TPS、延迟、\n * 商业计费及连接数等指标，支持定时打印与账户级统计。\n */\npublic class BrokerStatsManager {"),
    ("    // For commercial",
     "    // 商业版计费指标（已废弃，保留兼容）"),
    ("    // Send message latency",
     "    // 发送消息延迟统计"),
    ("    // Pull Message Latency",
     "    // Pull 消息延迟统计"),
    ("    // Consumer Register Time",
     "    // 消费者注册次数统计"),
    ("    // Producer Register Time",
     "    // 生产者注册次数统计"),
    ("    public static final String DLQ_PUT_NUMS = \"DLQ_PUT_NUMS\";",
     "    /** 死信队列写入次数指标名。 */\n    public static final String DLQ_PUT_NUMS = \"DLQ_PUT_NUMS\";"),
    ("    public static final String BROKER_ACK_NUMS = \"BROKER_ACK_NUMS\";",
     "    /** Broker 级 ACK 次数指标名。 */\n    public static final String BROKER_ACK_NUMS = \"BROKER_ACK_NUMS\";"),
    ("    public static final String SNDBCK2DLQ_TIMES = \"SNDBCK2DLQ_TIMES\";",
     "    /** 重试消息转入 DLQ 次数指标名。 */\n    public static final String SNDBCK2DLQ_TIMES = \"SNDBCK2DLQ_TIMES\";"),
    ("    public void init() {",
     "    /** 初始化全部 StatsItemSet 与 StatisticsItem 并注册定时打印。 */\n    public void init() {"),
    ("    public void start() {",
     "    /** 启动统计定时打印任务。 */\n    public void start() {"),
    ("    public void shutdown() {",
     "    /** 关闭统计线程池。 */\n    public void shutdown() {"),
    ("    public void onTopicDeleted(final String topic) {",
     "    /** Topic 删除时清理相关统计项。 */\n    public void onTopicDeleted(final String topic) {"),
    ("    public void onGroupDeleted(final String group) {",
     "    /** 消费组删除时清理相关统计项。 */\n    public void onGroupDeleted(final String group) {"),
    ("    public void incQueuePutNums(final String topic, final Integer queueId) {",
     "    /** 递增指定队列写入消息条数。 */\n    public void incQueuePutNums(final String topic, final Integer queueId) {"),
    ("    public void incGroupGetNums(final String group, final String topic, final int incValue) {",
     "    /** 递增消费组拉取消息条数。 */\n    public void incGroupGetNums(final String group, final String topic, final int incValue) {"),
    ("    public String buildStatsKey(String topic, String group) {",
     "    /** 构造 topic+group 维度的统计键。 */\n    public String buildStatsKey(String topic, String group) {"),
]

# --- TimerMessageStore ---
_TMS = "store/src/main/java/org/apache/rocketmq/store/timer/TimerMessageStore.java"
R[_TMS] = [
    ("public class TimerMessageStore {",
     "/**\n * 定时消息存储核心：基于时间轮（TimerWheel）+ TimerLog 实现延迟投递。\n * 包含入队（enqueue）与出队（dequeue）两条异步流水线，支持 Master/Slave 角色切换。\n */\npublic class TimerMessageStore {"),
    ("    public static final int INITIAL = 0, RUNNING = 1, HAULT = 2, SHUTDOWN = 3;",
     "    /** 状态：初始 / 运行 / 暂停 / 关闭。 */\n    public static final int INITIAL = 0, RUNNING = 1, HAULT = 2, SHUTDOWN = 3;"),
    ("    public static final String TIMER_TOPIC = TopicValidator.SYSTEM_TOPIC_PREFIX + \"wheel_timer\";",
     "    /** 定时消息系统 Topic（时间轮专用）。 */\n    public static final String TIMER_TOPIC = TopicValidator.SYSTEM_TOPIC_PREFIX + \"wheel_timer\";"),
    ("    public static final int PUT_OK = 0, PUT_NEED_RETRY = 1, PUT_NO_RETRY = 2;",
     "    /** 写入结果：成功 / 需重试 / 不可重试。 */\n    public static final int PUT_OK = 0, PUT_NEED_RETRY = 1, PUT_NO_RETRY = 2;"),
    ("    // The total days in the timer wheel when precision is 1000ms.",
     "    // 精度 1000ms 时时间轮覆盖的总天数；Broker 停机超过此天数可能丢消息"),
    ("    public static final int TIMER_WHEEL_TTL_DAY = 7;",
     "    /** 时间轮 TTL（天），默认 7 天。 */\n    public static final int TIMER_WHEEL_TTL_DAY = 7;"),
    ("    public static final int MAGIC_DEFAULT = 1;",
     "    /** TimerLog 默认 magic 标记。 */\n    public static final int MAGIC_DEFAULT = 1;"),
    ("    public static final int MAGIC_ROLL = 1 << 1;",
     "    /** TimerLog roll（续期）magic 标记。 */\n    public static final int MAGIC_ROLL = 1 << 1;"),
    ("    public static final int MAGIC_DELETE = 1 << 2;",
     "    /** TimerLog 删除 magic 标记。 */\n    public static final int MAGIC_DELETE = 1 << 2;"),
    ("    protected final BlockingQueue<TimerRequest> enqueuePutQueue;",
     "    /** 入队写入请求队列。 */\n    protected final BlockingQueue<TimerRequest> enqueuePutQueue;"),
    ("    protected final BlockingQueue<List<TimerRequest>> dequeueGetQueue;",
     "    /** 出队读取批次请求队列。 */\n    protected final BlockingQueue<List<TimerRequest>> dequeueGetQueue;"),
    ("    protected final BlockingQueue<TimerRequest> dequeuePutQueue;",
     "    /** 出队写入目标 Topic 请求队列。 */\n    protected final BlockingQueue<TimerRequest> dequeuePutQueue;"),
    ("    private final TimerWheel timerWheel;",
     "    /** 时间轮：按槽位索引到期定时消息。 */\n    private final TimerWheel timerWheel;"),
    ("    private final TimerLog timerLog;",
     "    /** TimerLog：持久化定时消息元数据。 */\n    private final TimerLog timerLog;"),
    ("    private final TimerCheckpoint timerCheckpoint;",
     "    /** 检查点：记录 TimerLog/TimerWheel 刷盘进度。 */\n    private final TimerCheckpoint timerCheckpoint;"),
    ("    protected volatile long currQueueOffset; //only one queue that is 0",
     "    /** 当前 Timer Topic 队列 offset（仅 queueId=0）。 */\n    protected volatile long currQueueOffset;"),
    ("    //the dequeue is an asynchronous process, use this flag to track if the status has changed",
     "    // 出队为异步流程，此标志跟踪 Master/Slave 角色是否变更"),
    ("    protected volatile boolean shouldRunningDequeue;",
     "    /** 当前 Broker 是否应运行出队（Master 或 slaveActingMaster 最小 brokerId）。 */\n    protected volatile boolean shouldRunningDequeue;"),
    ("    private final Object lockWhenFlush = new Object();",
     "    /** TimerLog/TimerWheel 刷盘互斥锁。 */\n    private final Object lockWhenFlush = new Object();"),
    ("        // TimerWheel contains the fixed number of slots regardless of precision.",
     "        // 时间轮槽位总数固定，与精度无关"),
    ("        // timerRollWindow contains the fixed number of slots regardless of precision.",
     "        // Roll 窗口槽位数固定，与精度无关"),
    ("    public void initService() {",
     "    /** 初始化入队/出队/刷盘等后台 ServiceThread。 */\n    public void initService() {"),
    ("    public boolean load() {",
     "    /** 加载 TimerWheel 快照与 TimerLog，恢复检查点。 */\n    public boolean load() {"),
    ("    public void recover() {",
     "    /** 从 TimerLog 恢复 queueOffset 与时间轮状态。 */\n    public void recover() {"),
    ("    public void start() {",
     "    /** 启动全部定时消息后台线程。 */\n    public void start() {"),
    ("    public void shutdown() {",
     "    /** 优雅关闭定时消息存储并刷盘。 */\n    public void shutdown() {"),
    ("    public boolean enqueue(int queueId) {",
     "    /** 从 Timer Topic 拉取消息并入队到时间轮。 */\n    public boolean enqueue(int queueId) {"),
    ("    public boolean doEnqueue(long offsetPy, int sizePy, long delayedTime, MessageExt messageExt, boolean isFromTimeline) {",
     "    /** 将单条消息写入 TimerLog 并挂载到时间轮指定槽位。 */\n    public boolean doEnqueue(long offsetPy, int sizePy, long delayedTime, MessageExt messageExt, boolean isFromTimeline) {"),
    ("    public int dequeue() throws Exception {",
     "    /** 扫描到期槽位，批量出队并投递到目标 Topic。 */\n    public int dequeue() throws Exception {"),
    ("    public int doPut(MessageExtBrokerInner message, boolean roll) throws Exception {",
     "    /** 将到期消息写入目标 Topic CommitLog；{@code roll} 为 true 表示续期。 */\n    public int doPut(MessageExtBrokerInner message, boolean roll) throws Exception {"),
    ("    public boolean needRoll(int magic) {",
     "    /** 判断 TimerLog 条目是否需要续期（magic 含 ROLL 位）。 */\n    public boolean needRoll(int magic) {"),
    ("    public boolean needDelete(int magic) {",
     "    /** 判断 TimerLog 条目是否需要删除（magic 含 DELETE 位）。 */\n    public boolean needDelete(int magic) {"),
    ("    public class TimerEnqueueGetService extends ServiceThread {",
     "    /** 入队拉取线程：从 Timer Topic Pull 消息。 */\n    public class TimerEnqueueGetService extends ServiceThread {"),
    ("    public class TimerEnqueuePutService extends ServiceThread {",
     "    /** 入队写入线程：将拉取到的消息写入时间轮。 */\n    public class TimerEnqueuePutService extends ServiceThread {"),
    ("    public class TimerDequeueGetService extends ServiceThread {",
     "    /** 出队扫描线程：扫描到期槽位生成批次请求。 */\n    public class TimerDequeueGetService extends ServiceThread {"),
    ("    public class TimerDequeuePutMessageService extends AbstractStateService {",
     "    /** 出队写入线程：将到期消息投递到目标 Topic。 */\n    public class TimerDequeuePutMessageService extends AbstractStateService {"),
    ("    public class TimerDequeueGetMessageService extends AbstractStateService {",
     "    /** 出队读取线程：从 TimerLog 读取到期消息体。 */\n    public class TimerDequeueGetMessageService extends AbstractStateService {"),
    ("    public class TimerDequeueWarmService extends ServiceThread {",
     "    /** 出队预热线程：提前加载即将到期的 TimerLog 数据。 */\n    public class TimerDequeueWarmService extends ServiceThread {"),
    ("    public class TimerFlushService extends ServiceThread {",
     "    /** 定时刷盘线程：刷 TimerLog 与 TimerWheel 快照。 */\n    public class TimerFlushService extends ServiceThread {"),
]

# --- Timeline ---
_TL = "store/src/main/java/org/apache/rocketmq/store/timer/rocksdb/Timeline.java"
R[_TL] = [
    ("public class Timeline {",
     "/**\n * RocksDB 定时消息 Timeline：按时间线索引构建、转发、Roll 与删除定时消息，\n * 替代文件版 TimerWheel 的 RocksDB 持久化方案。\n */\npublic class Timeline {"),
    ("    private static final int ORIGIN_CAPACITY = 100000;",
     "    /** 原始定时消息队列容量。 */\n    private static final int ORIGIN_CAPACITY = 100000;"),
    ("    private static final int BATCH_SIZE = 1000, MAX_BATCH_SIZE_FROM_ROCKSDB = 8000;",
     "    /** 批处理大小 / RocksDB 单次最大读取条数。 */\n    private static final int BATCH_SIZE = 1000, MAX_BATCH_SIZE_FROM_ROCKSDB = 8000;"),
    ("    private final AtomicLong commitOffset = new AtomicLong(0);",
     "    /** Timeline 已处理 commit offset。 */\n    private final AtomicLong commitOffset = new AtomicLong(0);"),
    ("    private TimelineIndexBuildService timelineIndexBuildService;",
     "    /** 索引构建服务：扫描 RocksDB 定时消息建立时间线索引。 */\n    private TimelineIndexBuildService timelineIndexBuildService;"),
    ("    private TimelineForwardService timelineForwardService;",
     "    /** 转发服务：将到期消息投递到业务 Topic。 */\n    private TimelineForwardService timelineForwardService;"),
    ("    private TimelineRollService timelineRollService;",
     "    /** Roll 服务：处理超长延迟消息的续期。 */\n    private TimelineRollService timelineRollService;"),
    ("    private TimelineDeleteService timelineDeleteService;",
     "    /** 删除服务：清理已投递或取消的定时消息。 */\n    private TimelineDeleteService timelineDeleteService;"),
    ("    public void start() {",
     "    /** 启动索引构建、转发、Roll 与删除四个后台服务。 */\n    public void start() {"),
    ("    public void shutDown() {",
     "    /** 关闭全部 Timeline 后台服务。 */\n    public void shutDown() {"),
    ("    public void putRecord(TimerRocksDBRecord timerRecord) throws InterruptedException {",
     "    /** 将定时消息记录放入 Timeline 原始队列待索引构建。 */\n    public void putRecord(TimerRocksDBRecord timerRecord) throws InterruptedException {"),
    ("    public void addMetric(MessageExt msg, int value) {",
     "    /** 记录定时消息相关指标（入队/出队/roll 等）。 */\n    public void addMetric(MessageExt msg, int value) {"),
]

# --- TimerMessageRocksDBStore ---
_TMRS = "store/src/main/java/org/apache/rocketmq/store/timer/rocksdb/TimerMessageRocksDBStore.java"
R[_TMRS] = [
    ("public class TimerMessageRocksDBStore {",
     "/**\n * RocksDB 版定时消息存储：扫描系统 Timer Topic，配合 {@link Timeline}\n * 实现定时消息的入队、到期投递、Roll 与删除。\n */\npublic class TimerMessageRocksDBStore {"),
    ("    private static final String SCAN_SYS_TOPIC = \"scanSysTopic\";",
     "    /** 扫描系统 Topic 性能计数标签。 */\n    private static final String SCAN_SYS_TOPIC = \"scanSysTopic\";"),
    ("    private static final String OUT_BIZ_MESSAGE = \"outBizMsg\";",
     "    /** 投递业务消息性能计数标签。 */\n    private static final String OUT_BIZ_MESSAGE = \"outBizMsg\";"),
    ("    private final AtomicLong readOffset = new AtomicLong(0);//timerSysTopic read offset",
     "    /** Timer 系统 Topic 当前读取 offset。 */\n    private final AtomicLong readOffset = new AtomicLong(0);"),
    ("    private Timeline timeline;",
     "    /** Timeline 处理器。 */\n    private Timeline timeline;"),
    ("    private TimerSysTopicScanService timerSysTopicScanService;",
     "    /** 系统 Timer Topic 扫描服务。 */\n    private TimerSysTopicScanService timerSysTopicScanService;"),
    ("    private TimerMessageReputService expiredMessageReputService;",
     "    /** 到期消息重投服务。 */\n    private TimerMessageReputService expiredMessageReputService;"),
    ("    private TimerMessageReputService rollMessageReputService;",
     "    /** Roll 续期消息重投服务。 */\n    private TimerMessageReputService rollMessageReputService;"),
    ("    protected long precisionMs;",
     "    /** 定时精度（毫秒）。 */\n    protected long precisionMs;"),
    ("    public synchronized void start() {",
     "    /** 启动 Timeline 与扫描/重投服务。 */\n    public synchronized void start() {"),
    ("    public void shutdown() {",
     "    /** 关闭 RocksDB 定时消息全部后台服务。 */\n    public void shutdown() {"),
    ("    public synchronized boolean load() {",
     "    /** 加载 Timeline 检查点并恢复 readOffset。 */\n    public synchronized boolean load() {"),
    ("    public AtomicLong getReadOffset() {",
     "    /** 返回 Timer 系统 Topic 读取 offset 原子引用。 */\n    public AtomicLong getReadOffset() {"),
]

# --- MessageStoreConfig (tieredstore) ---
_MSC = "tieredstore/src/main/java/org/apache/rocketmq/tieredstore/MessageStoreConfig.java"
R[_MSC] = [
    ("public class MessageStoreConfig {",
     "/**\n * 分层存储（Tiered Store）配置：Broker 名称、存储级别、文件大小、\n * 元数据/后端 Provider、GroupCommit 与预读缓存等参数。\n */\npublic class MessageStoreConfig {"),
    ("    /**\n     * All fetch requests are judged against this level first,\n     * and if the message cannot be read from the TiredMessageStore,\n     * these requests will still go to the next store for fallback processing.\n     */",
     "    /**\n     * 分层存储级别：Fetch 请求先按此级别判断是否走 TieredStore，\n     * 读不到则回退到下层 MessageStore。\n     */"),
    ("        /**\n         * Disable tiered storage, all fetch request will be handled by default message store.\n         */",
     "        /** 禁用分层存储，全部 Fetch 走默认 MessageStore。 */"),
    ("        /**\n         * Only fetch request with offset not in disk will be handled by tiered storage.\n         */",
     "        /** 仅 offset 不在本地磁盘的消息走分层存储。 */"),
    ("        /**\n         * Only fetch request with offset not in memory(page cache) will be handled by tiered storage.\n         */",
     "        /** 仅 offset 不在内存（PageCache）的消息走分层存储。 */"),
    ("        /**\n         * All fetch request will be handled by tiered storage.\n         */",
     "        /** 全部 Fetch 请求优先走分层存储。 */"),
    ("    // CommitLog file size, default is 1G",
     "    // CommitLog 分段文件大小，默认 1G"),
    ("    // ConsumeQueue file size, default is 100M",
     "    // ConsumeQueue 分段文件大小，默认 100M"),
    ("    // file reserved time, default is 72 hour",
     "    // 分层文件保留时间，默认 72 小时"),
    ("    // time of forcing commitLog to roll to next file, default is 24 hour",
     "    // 强制 CommitLog 滚动间隔，默认 24 小时"),
    ("    // Cached message count larger than this value will trigger async commit. default is 4096",
     "    // 缓存消息数超过此值触发异步 GroupCommit，默认 4096"),
    ("    // Cached message count larger than this value will suspend append. default is 10000",
     "    // 缓存消息数超过此值暂停追加，默认 10000"),
    ("    private boolean readAheadCacheEnable = true;",
     "    /** 是否启用预读缓存（Caffeine）。 */\n    private boolean readAheadCacheEnable = true;"),
    ("    private String tieredMetadataServiceProvider = \"org.apache.rocketmq.tieredstore.metadata.DefaultMetadataStore\";",
     "    /** 元数据存储 Provider 类名。 */\n    private String tieredMetadataServiceProvider = \"org.apache.rocketmq.tieredstore.metadata.DefaultMetadataStore\";"),
    ("    private String tieredBackendServiceProvider = \"org.apache.rocketmq.tieredstore.provider.MemoryFileSegment\";",
     "    /** 后端文件分段 Provider 类名（默认内存实现）。 */\n    private String tieredBackendServiceProvider = \"org.apache.rocketmq.tieredstore.provider.MemoryFileSegment\";"),
]

# --- TieredMessageStore ---
_TMS2 = "tieredstore/src/main/java/org/apache/rocketmq/tieredstore/TieredMessageStore.java"
R[_TMS2] = [
    ("public class TieredMessageStore extends AbstractPluginMessageStore {",
     "/**\n * 分层消息存储插件：在默认 MessageStore 之上提供远端冷数据读写，\n * 通过 {@link MessageStoreFetcherImpl} 拉取、{@link MessageStoreDispatcherImpl} 分发写入。\n */\npublic class TieredMessageStore extends AbstractPluginMessageStore {"),
    ("    protected static final long MIN_STORE_TIME = -1L;",
     "    /** 无效存储时间戳占位值。 */\n    protected static final long MIN_STORE_TIME = -1L;"),
    ("    protected final MessageStore defaultStore;",
     "    /** 下层默认 MessageStore（热数据）。 */\n    protected final MessageStore defaultStore;"),
    ("    protected final MessageStoreConfig storeConfig;",
     "    /** 分层存储配置。 */\n    protected final MessageStoreConfig storeConfig;"),
    ("    protected final MetadataStore metadataStore;",
     "    /** Topic/Queue 元数据存储。 */\n    protected final MetadataStore metadataStore;"),
    ("    protected final FlatFileStore flatFileStore;",
     "    /** 扁平文件存储（CommitLog + CQ 分段）。 */\n    protected final FlatFileStore flatFileStore;"),
    ("    protected final MessageStoreFetcher fetcher;",
     "    /** 分层读路径：预读缓存 + 远端 Fetch。 */\n    protected final MessageStoreFetcher fetcher;"),
    ("    protected final MessageStoreDispatcher dispatcher;",
     "    /** 分层写路径：CommitLog 分发到 FlatFile。 */\n    protected final MessageStoreDispatcher dispatcher;"),
    ("    protected final MessageRocksDBStorage messageRocksDBStorage;",
     "    /** 共享 RocksDB 存储（索引/定时/事务）。 */\n    protected final MessageRocksDBStorage messageRocksDBStorage;"),
    ("    public TieredMessageStore(MessageStorePluginContext context, MessageStore next) {",
     "    /** 构造分层存储：初始化元数据、FlatFile、索引、Fetcher 与 Dispatcher。 */\n    public TieredMessageStore(MessageStorePluginContext context, MessageStore next) {"),
    ("    public boolean load() {",
     "    /** 加载元数据与 FlatFile，恢复分层存储状态。 */\n    public boolean load() {"),
    ("    public void destroy() {",
     "    /** 销毁分层存储：关闭 FlatFile、索引与元数据。 */\n    public void destroy() {"),
    ("    public void initMetrics(Meter meter, Supplier<AttributesBuilder> attributesBuilderSupplier) {",
     "    /** 注册 OpenTelemetry 分层存储指标。 */\n    public void initMetrics(Meter meter, Supplier<AttributesBuilder> attributesBuilderSupplier) {"),
    ("    /**\n     * In the original design, getting the earliest time of the first message\n     * would generate two RPC requests. However, using the timestamp stored in the metadata\n     * avoids these requests, although this approach might introduce some level of inaccuracy.\n     */",
     "    /**\n     * 异步获取队列最早消息时间：优先读元数据时间戳，避免两次 RPC，\n     * 可能存在一定精度误差。\n     */"),
    ("    public boolean fetchFromCurrentStore(String topic, int queueId, long offset) {",
     "    /** 按分层级别判断 offset 是否应从 TieredStore 读取。 */\n    public boolean fetchFromCurrentStore(String topic, int queueId, long offset) {"),
]

# --- MessageStoreFetcherImpl ---
_MSFI = "tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcherImpl.java"
R[_MSFI] = [
    ("public class MessageStoreFetcherImpl implements MessageStoreFetcher {",
     "/**\n * 分层存储读实现：按 offset 从 FlatFile 拉取消息，Caffeine 预读缓存\n * 减少重复远端请求，支持按时间戳查 offset 与最早消息时间。\n */\npublic class MessageStoreFetcherImpl implements MessageStoreFetcher {"),
    ("    protected static final String CACHE_KEY_FORMAT = \"%s@%d@%d\";",
     "    /** 预读缓存键格式：topic@queueId@offset。 */\n    protected static final String CACHE_KEY_FORMAT = \"%s@%d@%d\";"),
    ("    protected static final String FETCHER_GROUP_NAME = MixAll.CID_RMQ_SYS_PREFIX + \"FETCHER_TIMESTAMP\";",
     "    /** 按时间戳 Fetch 使用的虚拟消费组名。 */\n    protected static final String FETCHER_GROUP_NAME = MixAll.CID_RMQ_SYS_PREFIX + \"FETCHER_TIMESTAMP\";"),
    ("    private final Cache<String /* topic@queueId@offset */, SelectBufferResult> fetcherCache;",
     "    /** Caffeine 预读缓存：键为 topic@queueId@offset。 */\n    private final Cache<String /* topic@queueId@offset */, SelectBufferResult> fetcherCache;"),
    ("            // Clients may repeatedly request messages at the same offset in tiered storage,",
     "            // 分层存储中客户端可能重复请求同一 offset，"),
    ("            // causing the request queue to become full. Using expire after read or write policy",
     "            // 导致请求队列满；使用访问/写入过期策略刷新缓存"),
    ("            // to refresh the cache expiration time.",
     "            // 以延长热点 offset 的缓存存活时间"),
    ("            // Using the buffer size of messages to calculate memory usage",
     "            // 按消息 buffer 大小计算权重以限制内存"),
    ("        // return duplicate buffer here",
     "        // 返回 buffer 副本，避免缓存条目被修改"),
    ("    public CompletableFuture<GetMessageResult> getMessageAsync(\n        String group, String topic, int queueId, long queueOffset, int maxCount, final MessageFilter messageFilter) {",
     "    /** 异步按 CQ offset 拉取消息，命中预读缓存则直接返回。 */\n    public CompletableFuture<GetMessageResult> getMessageAsync(\n        String group, String topic, int queueId, long queueOffset, int maxCount, final MessageFilter messageFilter) {"),
    ("    public CompletableFuture<Long> getEarliestMessageTimeAsync(String topic, int queueId) {",
     "    /** 异步获取队列最早消息存储时间戳。 */\n    public CompletableFuture<Long> getEarliestMessageTimeAsync(String topic, int queueId) {"),
    ("    public CompletableFuture<Long> getMessageStoreTimeStampAsync(String topic, int queueId, long queueOffset) {",
     "    /** 异步按 CQ offset 获取消息存储时间戳。 */\n    public CompletableFuture<Long> getMessageStoreTimeStampAsync(String topic, int queueId, long queueOffset) {"),
]

# --- FlatMessageFile ---
_FMF = "tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatMessageFile.java"
R[_FMF] = [
    ("public class FlatMessageFile implements FlatFileInterface {",
     "/**\n * 单个 Topic-Queue 的扁平文件：包含 CommitLog 与 ConsumeQueue 两个分段，\n * 支持追加写入、按 offset 读取及元数据恢复。\n */\npublic class FlatMessageFile implements FlatFileInterface {"),
    ("    protected volatile boolean closed = false;",
     "    /** 文件是否已关闭。 */\n    protected volatile boolean closed = false;"),
    ("    protected TopicMetadata topicMetadata;",
     "    /** Topic 元数据（topicId 等）。 */\n    protected TopicMetadata topicMetadata;"),
    ("    protected QueueMetadata queueMetadata;",
     "    /** Queue 元数据（MessageQueue 信息）。 */\n    protected QueueMetadata queueMetadata;"),
    ("    protected final ReentrantLock fileLock;",
     "    /** 文件级互斥锁，保护追加与提交。 */\n    protected final ReentrantLock fileLock;"),
    ("    protected final Semaphore commitLock = new Semaphore(1);",
     "    /** GroupCommit 信号量，串行化提交。 */\n    protected final Semaphore commitLock = new Semaphore(1);"),
    ("    protected final FlatCommitLogFile commitLog;",
     "    /** CommitLog 分段文件。 */\n    protected final FlatCommitLogFile commitLog;"),
    ("    protected final FlatConsumeQueueFile consumeQueue;",
     "    /** ConsumeQueue 分段文件。 */\n    protected final FlatConsumeQueueFile consumeQueue;"),
    ("    protected final ConcurrentMap<String, CompletableFuture<?>> inFlightRequestMap;",
     "    /** 进行中的异步请求映射，用于去重与合并。 */\n    protected final ConcurrentMap<String, CompletableFuture<?>> inFlightRequestMap;"),
    ("    public TopicMetadata recoverTopicMetadata(String topic) {",
     "    /** 从 MetadataStore 恢复或创建 Topic 元数据。 */\n    public TopicMetadata recoverTopicMetadata(String topic) {"),
    ("    public AppendResult appendCommitLog(ByteBuffer message) {",
     "    /** 追加单条消息 buffer 到 CommitLog 分段。 */\n    public AppendResult appendCommitLog(ByteBuffer message) {"),
    ("    public AppendResult appendConsumeQueue(DispatchRequest request) {",
     "    /** 追加 ConsumeQueue 索引条目。 */\n    public AppendResult appendConsumeQueue(DispatchRequest request) {"),
    ("    public CompletableFuture<ByteBuffer> getMessageAsync(long queueOffset) {",
     "    /** 异步按 CQ offset 读取完整消息 ByteBuffer。 */\n    public CompletableFuture<ByteBuffer> getMessageAsync(long queueOffset) {"),
]

# --- IndexStoreFile ---
_ISF = "tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexStoreFile.java"
R[_ISF] = [
    ("/**\n * a single IndexFile in indexService\n */",
     "/**\n * 分层存储单个索引文件：Hash 槽 + 索引项链表，支持按 key/时间范围查询。\n */"),
    ("    /**\n     * header format:\n     * magic code(4) + begin timestamp(8) + end timestamp(8) + slot num(4) + index num(4)\n     */",
     "    /**\n     * 索引文件头格式：magic(4) + 起始时间(8) + 结束时间(8) + 槽位数(4) + 索引项数(4)\n     */"),
    ("    /**\n     * hash slot\n     */",
     "    /** Hash 槽：存储索引项链表头 offset。 */"),
    ("    private static final int INVALID_INDEX = 0;",
     "    /** 无效索引项标记值。 */\n    private static final int INVALID_INDEX = 0;"),
    ("    private static final int MAX_QUERY_COUNT = 512;",
     "    /** 单次查询最大返回索引项数。 */\n    private static final int MAX_QUERY_COUNT = 512;"),
    ("    private final ReadWriteLock fileReadWriteLock;",
     "    /** 索引文件读写锁。 */\n    private final ReadWriteLock fileReadWriteLock;"),
    ("    private final AtomicReference<IndexStatusEnum> fileStatus;",
     "    /** 索引文件状态：UNSEALED / SEALED / UPLOAD。 */\n    private final AtomicReference<IndexStatusEnum> fileStatus;"),
    ("    public void start() {",
     "    /** 启动索引文件（分层存储索引服务调用）。 */\n    public void start() {"),
    ("    public AppendResult putKey(\n        String topic, int topicId, int queueId, Set<String> keySet, long offset, int size, long timestamp) {",
     "    /** 批量写入索引项：keySet 中每个 key 映射到 CommitLog offset + 大小 + 时间戳。 */\n    public AppendResult putKey(\n        String topic, int topicId, int queueId, Set<String> keySet, long offset, int size, long timestamp) {"),
    ("    public CompletableFuture<List<IndexItem>> queryAsync(\n        String topic, String key, int maxCount, long beginTime, long endTime) {",
     "    /** 异步按 topic+key 与时间范围查询索引项列表。 */\n    public CompletableFuture<List<IndexItem>> queryAsync(\n        String topic, String key, int maxCount, long beginTime, long endTime) {"),
]


def emit() -> None:
    lines = [
        '"""RocketMQ 5.5.0 wave50b store/tieredstore [15:30] Chinese annotation replacements."""',
        "",
        "R: dict[str, list[tuple[str, str]]] = {}",
        "",
    ]
    for rel, reps in R.items():
        lines.append(f"R[{rel!r}] = [")
        for old, new in reps:
            lines.append(f"    ({old!r}, {new!r}),")
        lines.append("]")
        lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(R)} files)")
    for rel, reps in R.items():
        print(f"  {rel}: {len(reps)} replacements")


if __name__ == "__main__":
    emit()
