"""Large-file JavaDoc replacements for RxJava wave-1b [15:30]."""

CONNECTABLE_FLOWABLE: list[tuple[str, str]] = [
    (
        "/**\n * A {@code ConnectableFlowable} resembles an ordinary {@link Flowable}, except that it does not begin\n * emitting items when it is subscribed to, but only when its {@link #connect} method is called. In this way you\n * can wait for all intended {@link Subscriber}s to {@link Flowable#subscribe} to the {@code Flowable}\n * before the {@code Flowable} begins emitting items.\n * <p>\n * <img width=\"640\" height=\"510\" src=\"https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/publishConnect.v3.png\" alt=\"\">\n * <p>\n * When the upstream terminates, the {@code ConnectableFlowable} remains in this terminated state and,\n * depending on the actual underlying implementation, relays cached events to late {@code Subscriber}s.\n * In order to reuse and restart this {@code ConnectableFlowable}, the {@link #reset()} method has to be called.\n * When called, this {@code ConnectableFlowable} will appear as fresh, unconnected source to new {@code Subscriber}s.\n * Disposing the connection will reset the {@code ConnectableFlowable} to its fresh state and there is no need to call\n * {@code reset()} in this case.\n * <p>\n * Note that although {@link #connect()} and {@link #reset()} are safe to call from multiple threads, it is recommended\n * a dedicated thread or business logic manages the connection or resetting of a {@code ConnectableFlowable} so that\n * there is no unwanted signal loss due to early {@code connect()} or {@code reset()} calls while {@code Subscriber}s are\n * still being subscribed to this {@code ConnectableFlowable} to receive signals from the get-go.\n * <p>\n * @see <a href=\"https://github.com/ReactiveX/RxJava/wiki/Connectable-Observable-Operators\">RxJava Wiki: Connectable Observable Operators</a>\n * @param <T>\n *          the type of items emitted by the {@code ConnectableFlowable}\n * @since 2.0.0\n */",
        "/**\n * {@code ConnectableFlowable} 类似普通 {@link Flowable}，但不会在订阅时立即开始发射元素，\n * 仅在其 {@link #connect} 方法被调用后才开始。这样你可以等待所有预期的 {@link Subscriber}\n * 对 {@code Flowable} 执行 {@link Flowable#subscribe} 之后，再让 {@code Flowable} 开始发射。\n * <p>\n * <img width=\"640\" height=\"510\" src=\"https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/publishConnect.v3.png\" alt=\"\">\n * <p>\n * 当上游终止时，{@code ConnectableFlowable} 保持该终止状态，\n * 并根据底层实现将缓存的事件转发给迟到的 {@code Subscriber}。\n * 若要复用并重启此 {@code ConnectableFlowable}，必须调用 {@link #reset()} 方法。\n * 调用后，此 {@code ConnectableFlowable} 对新 {@code Subscriber} 将呈现为全新的未连接源。\n * 释放连接会将 {@code ConnectableFlowable} 重置为初始状态，此情况下无需再调用 {@code reset()}。\n * <p>\n * 尽管 {@link #connect()} 与 {@link #reset()} 可从多线程安全调用，仍建议由专用线程或业务逻辑\n * 管理 {@code ConnectableFlowable} 的连接或重置，以避免在 {@code Subscriber} 仍在订阅、\n * 尚未从一开始就接收信号时，过早调用 {@code connect()} 或 {@code reset()} 造成意外信号丢失。\n * <p>\n * @see <a href=\"https://github.com/ReactiveX/RxJava/wiki/Connectable-Observable-Operators\">RxJava Wiki: Connectable Observable Operators</a>\n * @param <T>\n *          {@code ConnectableFlowable} 发射元素的类型\n * @since 2.0.0\n */",
    ),
    (
        "    /**\n     * Instructs the {@code ConnectableFlowable} to begin emitting the items from its underlying\n     * {@link Flowable} to its {@link Subscriber}s.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>The behavior is determined by the implementor of this abstract class.</dd>\n     * </dl>\n     *\n     * @param connection\n     *          the action that receives the connection subscription before the subscription to source happens\n     *          allowing the caller to synchronously disconnect a synchronous source\n     * @throws NullPointerException if {@code connection} is {@code null}\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
        "    /**\n     * 指示 {@code ConnectableFlowable} 开始将其底层 {@link Flowable} 的元素发射给 {@link Subscriber}。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>行为由本抽象类的实现者决定。</dd>\n     * </dl>\n     *\n     * @param connection\n     *          在订阅源之前接收连接订阅的操作，\n     *          允许调用方同步断开同步源\n     * @throws NullPointerException 若 {@code connection} 为 {@code null}\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
    ),
    (
        "    /**\n     * Resets this {@code ConnectableFlowable} into its fresh state if it has terminated.\n     * <p>\n     * Calling this method on a fresh or active {@code ConnectableFlowable} has no effect.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>The behavior is determined by the implementor of this abstract class.</dd>\n     * </dl>\n     * @since 3.0.0\n     */",
        "    /**\n     * 若本 {@code ConnectableFlowable} 已终止，则将其重置为初始状态。\n     * <p>\n     * 对全新或活跃的 {@code ConnectableFlowable} 调用此方法无效果。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>行为由本抽象类的实现者决定。</dd>\n     * </dl>\n     * @since 3.0.0\n     */",
    ),
    (
        "    /**\n     * Instructs the {@code ConnectableFlowable} to begin emitting the items from its underlying\n     * {@link Flowable} to its {@link Subscriber}s.\n     * <p>\n     * To disconnect from a synchronous source, use the {@link #connect(io.reactivex.rxjava4.functions.Consumer)} method.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>The behavior is determined by the implementor of this abstract class.</dd>\n     * </dl>\n     *\n     * @return the subscription representing the connection\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
        "    /**\n     * 指示 {@code ConnectableFlowable} 开始将其底层 {@link Flowable} 的元素发射给 {@link Subscriber}。\n     * <p>\n     * 若要断开同步源，请使用 {@link #connect(io.reactivex.rxjava4.functions.Consumer)} 方法。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>行为由本抽象类的实现者决定。</dd>\n     * </dl>\n     *\n     * @return 表示连接的订阅\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
    ),
    (
        "    /**\n     * Returns a {@link Flowable} that stays connected to this {@code ConnectableFlowable} as long as there\n     * is at least one subscription to this {@code ConnectableFlowable}.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by the upstream\n     *  {@code ConnectableFlowable}'s backpressure behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     * @return the new {@code Flowable} instance\n     * @see <a href=\"http://reactivex.io/documentation/operators/refcount.html\">ReactiveX documentation: RefCount</a>\n     * @see #refCount(int)\n     * @see #refCount(long, TimeUnit)\n     * @see #refCount(int, long, TimeUnit)\n     */",
        "    /**\n     * 返回一个 {@link Flowable}，只要本 {@code ConnectableFlowable} 至少存在一个订阅，\n     * 它就保持与本 {@code ConnectableFlowable} 的连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游\n     *  {@code ConnectableFlowable} 的背压策略决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * @return 新的 {@code Flowable} 实例\n     * @see <a href=\"http://reactivex.io/documentation/operators/refcount.html\">ReactiveX documentation: RefCount</a>\n     * @see #refCount(int)\n     * @see #refCount(long, TimeUnit)\n     * @see #refCount(int, long, TimeUnit)\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableFlowable} if the number of subscribed\n     * subscriber reaches the specified count and disconnect if all subscribers have unsubscribed.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by the upstream\n     *  {@code ConnectableFlowable}'s backpressure behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param subscriberCount the number of subscribers required to connect to the upstream\n     * @return the new {@link Flowable} instance\n     * @throws IllegalArgumentException if {@code subscriberCount} is non-positive\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 subscriber 数量达到指定值时连接上游 {@code ConnectableFlowable}，\n     * 若所有 subscriber 均已取消订阅则断开连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游\n     *  {@code ConnectableFlowable} 的背压策略决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param subscriberCount 连接上游所需的 subscriber 数量\n     * @return 新的 {@link Flowable} 实例\n     * @throws IllegalArgumentException 若 {@code subscriberCount} 非正数\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableFlowable} if the number of subscribed\n     * subscriber reaches 1 and disconnect after the specified\n     * timeout if all subscribers have unsubscribed.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by the upstream\n     *  {@code ConnectableFlowable}'s backpressure behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the {@code computation} {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout the time to wait before disconnecting after all subscribers unsubscribed\n     * @param unit the time unit of the timeout\n     * @return the new {@link Flowable} instance\n     * @throws NullPointerException if {@code unit} is {@code null}\n     * @see #refCount(long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 subscriber 数量达到 1 时连接上游 {@code ConnectableFlowable}，\n     * 若所有 subscriber 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游\n     *  {@code ConnectableFlowable} 的背压策略决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在 {@code computation} {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout 所有 subscriber 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @return 新的 {@link Flowable} 实例\n     * @throws NullPointerException 若 {@code unit} 为 {@code null}\n     * @see #refCount(long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableFlowable} if the number of subscribed\n     * subscriber reaches 1 and disconnect after the specified\n     * timeout if all subscribers have unsubscribed.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by the upstream\n     *  {@code ConnectableFlowable}'s backpressure behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the specified {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout the time to wait before disconnecting after all subscribers unsubscribed\n     * @param unit the time unit of the timeout\n     * @param scheduler the target scheduler to wait on before disconnecting\n     * @return the new {@link Flowable} instance\n     * @throws NullPointerException if {@code unit} or {@code scheduler} is {@code null}\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 subscriber 数量达到 1 时连接上游 {@code ConnectableFlowable}，\n     * 若所有 subscriber 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游\n     *  {@code ConnectableFlowable} 的背压策略决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在指定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout 所有 subscriber 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @param scheduler 断开连接前等待的目标调度器\n     * @return 新的 {@link Flowable} 实例\n     * @throws NullPointerException 若 {@code unit} 或 {@code scheduler} 为 {@code null}\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableFlowable} if the number of subscribed\n     * subscriber reaches the specified count and disconnect after the specified\n     * timeout if all subscribers have unsubscribed.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by the upstream\n     *  {@code ConnectableFlowable}'s backpressure behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the {@code computation} {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param subscriberCount the number of subscribers required to connect to the upstream\n     * @param timeout the time to wait before disconnecting after all subscribers unsubscribed\n     * @param unit the time unit of the timeout\n     * @return the new {@link Flowable} instance\n     * @throws NullPointerException if {@code unit} is {@code null}\n     * @throws IllegalArgumentException if {@code subscriberCount} is non-positive\n     * @see #refCount(int, long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 subscriber 数量达到指定值时连接上游 {@code ConnectableFlowable}，\n     * 若所有 subscriber 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游\n     *  {@code ConnectableFlowable} 的背压策略决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在 {@code computation} {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param subscriberCount 连接上游所需的 subscriber 数量\n     * @param timeout 所有 subscriber 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @return 新的 {@link Flowable} 实例\n     * @throws NullPointerException 若 {@code unit} 为 {@code null}\n     * @throws IllegalArgumentException 若 {@code subscriberCount} 非正数\n     * @see #refCount(int, long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableFlowable} if the number of subscribed\n     * subscriber reaches the specified count and disconnect after the specified\n     * timeout if all subscribers have unsubscribed.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by the upstream\n     *  {@code ConnectableFlowable}'s backpressure behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the specified {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param subscriberCount the number of subscribers required to connect to the upstream\n     * @param timeout the time to wait before disconnecting after all subscribers unsubscribed\n     * @param unit the time unit of the timeout\n     * @param scheduler the target scheduler to wait on before disconnecting\n     * @return the new {@link Flowable} instance\n     * @throws NullPointerException if {@code unit} or {@code scheduler} is {@code null}\n     * @throws IllegalArgumentException if {@code subscriberCount} is non-positive\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 subscriber 数量达到指定值时连接上游 {@code ConnectableFlowable}，\n     * 若所有 subscriber 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游\n     *  {@code ConnectableFlowable} 的背压策略决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在指定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param subscriberCount 连接上游所需的 subscriber 数量\n     * @param timeout 所有 subscriber 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @param scheduler 断开连接前等待的目标调度器\n     * @return 新的 {@link Flowable} 实例\n     * @throws NullPointerException 若 {@code unit} 或 {@code scheduler} 为 {@code null}\n     * @throws IllegalArgumentException 若 {@code subscriberCount} 非正数\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Returns a {@link Flowable} that automatically connects (at most once) to this {@code ConnectableFlowable}\n     * when the first {@link Subscriber} subscribes.\n     * <p>\n     * <img width=\"640\" height=\"392\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.f.png\" alt=\"\">\n     * <p>\n     * The connection happens after the first subscription and happens at most once\n     * during the lifetime of the returned {@code Flowable}. If this {@code ConnectableFlowable}\n     * terminates, the connection is never renewed, no matter how {@code Subscriber}s come\n     * and go. Use {@link #refCount()} to renew a connection or dispose an active\n     * connection when all {@code Subscriber}s have cancelled their {@link Subscription}s.\n     * <p>\n     * This overload does not allow disconnecting the connection established via\n     * {@link #connect(Consumer)}. Use the {@link #autoConnect(int, Consumer)} overload\n     * to gain access to the {@link Disposable} representing the only connection.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by\n     *  the upstream {@code ConnectableFlowable}'s behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>{@code autoConnect} does not operate by default on a particular {@link Scheduler}.</dd>\n     * </dl>\n     *\n     * @return a new {@code Flowable} instance that automatically connects to this {@code ConnectableFlowable}\n     *         when the first {@code Subscriber} subscribes\n     * @see #refCount()\n     * @see #autoConnect(int, Consumer)\n     */",
        "    /**\n     * 返回一个 {@link Flowable}，在首个 {@link Subscriber} 订阅时自动（至多一次）连接本 {@code ConnectableFlowable}。\n     * <p>\n     * <img width=\"640\" height=\"392\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.f.png\" alt=\"\">\n     * <p>\n     * 连接在首次订阅后发生，且在返回的 {@code Flowable} 生命周期内至多发生一次。\n     * 若本 {@code ConnectableFlowable} 终止，无论 {@code Subscriber} 如何增减，连接都不会恢复。\n     * 使用 {@link #refCount()} 可在所有 {@code Subscriber} 取消 {@link Subscription} 时\n     * 恢复连接或释放活跃连接。\n     * <p>\n     * 此重载无法断开通过 {@link #connect(Consumer)} 建立的连接。\n     * 使用 {@link #autoConnect(int, Consumer)} 重载可获取表示唯一连接的 {@link Disposable}。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游 {@code ConnectableFlowable} 决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>{@code autoConnect} 默认不在特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     *\n     * @return 在首个 {@code Subscriber} 订阅时自动连接本 {@code ConnectableFlowable} 的新 {@code Flowable} 实例\n     * @see #refCount()\n     * @see #autoConnect(int, Consumer)\n     */",
    ),
    (
        "    /**\n     * Returns a {@link Flowable} that automatically connects (at most once) to this {@code ConnectableFlowable}\n     * when the specified number of {@link Subscriber}s subscribe to it.\n     * <p>\n     * <img width=\"640\" height=\"392\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.f.png\" alt=\"\">\n     * <p>\n     * The connection happens after the given number of subscriptions and happens at most once\n     * during the lifetime of the returned {@code Flowable}. If this {@code ConnectableFlowable}\n     * terminates, the connection is never renewed, no matter how {@code Subscriber}s come\n     * and go. Use {@link #refCount()} to renew a connection or dispose an active\n     * connection when all {@code Subscriber}s have cancelled their {@link Subscription}s.\n     * <p>\n     * This overload does not allow disconnecting the connection established via\n     * {@link #connect(Consumer)}. Use the {@link #autoConnect(int, Consumer)} overload\n     * to gain access to the {@link Disposable} representing the only connection.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by\n     *  the upstream {@code ConnectableFlowable}'s behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>{@code autoConnect} does not operate by default on a particular {@link Scheduler}.</dd>\n     * </dl>\n     *\n     * @param numberOfSubscribers the number of subscribers to await before calling connect\n     *                            on the {@code ConnectableFlowable}. A non-positive value indicates\n     *                            an immediate connection.\n     * @return a new {@code Flowable} instance that automatically connects to this {@code ConnectableFlowable}\n     *         when the specified number of {@code Subscriber}s subscribe to it\n     */",
        "    /**\n     * 返回一个 {@link Flowable}，在指定数量的 {@link Subscriber} 订阅时自动（至多一次）连接本 {@code ConnectableFlowable}。\n     * <p>\n     * <img width=\"640\" height=\"392\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.f.png\" alt=\"\">\n     * <p>\n     * 连接在给定数量的订阅后发生，且在返回的 {@code Flowable} 生命周期内至多发生一次。\n     * 若本 {@code ConnectableFlowable} 终止，无论 {@code Subscriber} 如何增减，连接都不会恢复。\n     * 使用 {@link #refCount()} 可在所有 {@code Subscriber} 取消 {@link Subscription} 时\n     * 恢复连接或释放活跃连接。\n     * <p>\n     * 此重载无法断开通过 {@link #connect(Consumer)} 建立的连接。\n     * 使用 {@link #autoConnect(int, Consumer)} 重载可获取表示唯一连接的 {@link Disposable}。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游 {@code ConnectableFlowable} 决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>{@code autoConnect} 默认不在特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     *\n     * @param numberOfSubscribers 在 {@code ConnectableFlowable} 上调用 connect 前等待的 subscriber 数量。\n     *                            非正数表示立即连接。\n     * @return 在指定数量的 {@code Subscriber} 订阅时自动连接本 {@code ConnectableFlowable} 的新 {@code Flowable} 实例\n     */",
    ),
    (
        "    /**\n     * Returns a {@link Flowable} that automatically connects (at most once) to this {@code ConnectableFlowable}\n     * when the specified number of {@link Subscriber}s subscribe to it and calls the\n     * specified callback with the {@link Disposable} associated with the established connection.\n     * <p>\n     * <img width=\"640\" height=\"392\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.f.png\" alt=\"\">\n     * <p>\n     * The connection happens after the given number of subscriptions and happens at most once\n     * during the lifetime of the returned {@code Flowable}. If this {@code ConnectableFlowable}\n     * terminates, the connection is never renewed, no matter how {@code Subscriber}s come\n     * and go. Use {@link #refCount()} to renew a connection or dispose an active\n     * connection when all {@code Subscriber}s have cancelled their {@link Subscription}s.\n     * <dl>\n     *  <dt><b>Backpressure:</b></dt>\n     *  <dd>The operator itself doesn't interfere with backpressure which is determined by\n     *  the upstream {@code ConnectableFlowable}'s behavior.</dd>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>{@code autoConnect} does not operate by default on a particular {@link Scheduler}.</dd>\n     * </dl>\n     *\n     * @param numberOfSubscribers the number of subscribers to await before calling connect\n     *                            on the {@code ConnectableFlowable}. A non-positive value indicates\n     *                            an immediate connection.\n     * @param connection the callback {@link Consumer} that will receive the {@code Disposable} representing the\n     *                   established connection\n     * @return a new {@code Flowable} instance that automatically connects to this {@code ConnectableFlowable}\n     *         when the specified number of {@code Subscriber}s subscribe to it and calls the\n     *         specified callback with the {@code Disposable} associated with the established connection\n     * @throws NullPointerException if {@code connection} is {@code null}\n     */",
        "    /**\n     * 返回一个 {@link Flowable}，在指定数量的 {@link Subscriber} 订阅时自动（至多一次）连接本 {@code ConnectableFlowable}，\n     * 并以已建立连接关联的 {@link Disposable} 调用指定回调。\n     * <p>\n     * <img width=\"640\" height=\"392\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.f.png\" alt=\"\">\n     * <p>\n     * 连接在给定数量的订阅后发生，且在返回的 {@code Flowable} 生命周期内至多发生一次。\n     * 若本 {@code ConnectableFlowable} 终止，无论 {@code Subscriber} 如何增减，连接都不会恢复。\n     * 使用 {@link #refCount()} 可在所有 {@code Subscriber} 取消 {@link Subscription} 时\n     * 恢复连接或释放活跃连接。\n     * <dl>\n     *  <dt><b>背压：</b></dt>\n     *  <dd>该算子本身不干预背压，背压行为由上游 {@code ConnectableFlowable} 决定。</dd>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>{@code autoConnect} 默认不在特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     *\n     * @param numberOfSubscribers 在 {@code ConnectableFlowable} 上调用 connect 前等待的 subscriber 数量。\n     *                            非正数表示立即连接。\n     * @param connection 将接收表示已建立连接的 {@code Disposable} 的回调 {@link Consumer}\n     * @return 在指定数量的 {@code Subscriber} 订阅时自动连接本 {@code ConnectableFlowable} 并以\n     *         已建立连接关联的 {@code Disposable} 调用指定回调的新 {@code Flowable} 实例\n     * @throws NullPointerException 若 {@code connection} 为 {@code null}\n     */",
    ),
]

CONNECTABLE_OBSERVABLE: list[tuple[str, str]] = [
    (
        "/**\n * A {@code ConnectableObservable} resembles an ordinary {@link Observable}, except that it does not begin\n * emitting items when it is subscribed to, but only when its {@link #connect} method is called. In this way you\n * can wait for all intended {@link Observer}s to {@link Observable#subscribe} to the {@code Observable}\n * before the {@code Observable} begins emitting items.\n * <p>\n * <img width=\"640\" height=\"510\" src=\"https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/publishConnect.v3.png\" alt=\"\">\n * <p>\n * When the upstream terminates, the {@code ConnectableObservable} remains in this terminated state and,\n * depending on the actual underlying implementation, relays cached events to late {@code Observer}s.\n * In order to reuse and restart this {@code ConnectableObservable}, the {@link #reset()} method has to be called.\n * When called, this {@code ConnectableObservable} will appear as fresh, unconnected source to new {@code Observer}s.\n * Disposing the connection will reset the {@code ConnectableObservable} to its fresh state and there is no need to call\n * {@link #reset()} in this case.\n * <p>\n * Note that although {@link #connect()} and {@link #reset()} are safe to call from multiple threads, it is recommended\n * a dedicated thread or business logic manages the connection or resetting of a {@code ConnectableObservable} so that\n * there is no unwanted signal loss due to early {@code connect()} or {@code reset()} calls while {@code Observer}s are\n * still being subscribed to this {@code ConnectableObservable} to receive signals from the get-go.\n *\n * @see <a href=\"https://github.com/ReactiveX/RxJava/wiki/Connectable-Observable-Operators\">RxJava Wiki: Connectable Observable Operators</a>\n * @param <T>\n *          the type of items emitted by the {@code ConnectableObservable}\n */",
        "/**\n * {@code ConnectableObservable} 类似普通 {@link Observable}，但不会在订阅时立即开始发射元素，\n * 仅在其 {@link #connect} 方法被调用后才开始。这样你可以等待所有预期的 {@link Observer}\n * 对 {@code Observable} 执行 {@link Observable#subscribe} 之后，再让 {@code Observable} 开始发射。\n * <p>\n * <img width=\"640\" height=\"510\" src=\"https://github.com/ReactiveX/RxJava/wiki/images/rx-operators/publishConnect.v3.png\" alt=\"\">\n * <p>\n * 当上游终止时，{@code ConnectableObservable} 保持该终止状态，\n * 并根据底层实现将缓存的事件转发给迟到的 {@code Observer}。\n * 若要复用并重启此 {@code ConnectableObservable}，必须调用 {@link #reset()} 方法。\n * 调用后，此 {@code ConnectableObservable} 对新 {@code Observer} 将呈现为全新的未连接源。\n * 释放连接会将 {@code ConnectableObservable} 重置为初始状态，此情况下无需再调用 {@link #reset()}。\n * <p>\n * 尽管 {@link #connect()} 与 {@link #reset()} 可从多线程安全调用，仍建议由专用线程或业务逻辑\n * 管理 {@code ConnectableObservable} 的连接或重置，以避免在 {@code Observer} 仍在订阅、\n * 尚未从一开始就接收信号时，过早调用 {@code connect()} 或 {@code reset()} 造成意外信号丢失。\n *\n * @see <a href=\"https://github.com/ReactiveX/RxJava/wiki/Connectable-Observable-Operators\">RxJava Wiki: Connectable Observable Operators</a>\n * @param <T>\n *          {@code ConnectableObservable} 发射元素的类型\n */",
    ),
    (
        "    /**\n     * Instructs the {@code ConnectableObservable} to begin emitting the items from its underlying\n     * {@link Observable} to its {@link Observer}s.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>The behavior is determined by the implementor of this abstract class.</dd>\n     * </dl>\n     *\n     * @param connection\n     *          the action that receives the connection subscription before the subscription to source happens\n     *          allowing the caller to synchronously disconnect a synchronous source\n     * @throws NullPointerException if {@code connection} is {@code null}\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
        "    /**\n     * 指示 {@code ConnectableObservable} 开始将其底层 {@link Observable} 的元素发射给 {@link Observer}。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>行为由本抽象类的实现者决定。</dd>\n     * </dl>\n     *\n     * @param connection\n     *          在订阅源之前接收连接订阅的操作，\n     *          允许调用方同步断开同步源\n     * @throws NullPointerException 若 {@code connection} 为 {@code null}\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
    ),
    (
        "    /**\n     * Resets this {@code ConnectableObservable} into its fresh state if it has terminated\n     * or has been disposed.\n     * <p>\n     * Calling this method on a fresh or active {@code ConnectableObservable} has no effect.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>The behavior is determined by the implementor of this abstract class.</dd>\n     * </dl>\n     * @since 3.0.0\n     */",
        "    /**\n     * 若本 {@code ConnectableObservable} 已终止或已被释放，则将其重置为初始状态。\n     * <p>\n     * 对全新或活跃的 {@code ConnectableObservable} 调用此方法无效果。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>行为由本抽象类的实现者决定。</dd>\n     * </dl>\n     * @since 3.0.0\n     */",
    ),
    (
        "    /**\n     * Instructs the {@code ConnectableObservable} to begin emitting the items from its underlying\n     * {@link Observable} to its {@link Observer}s.\n     * <p>\n     * To disconnect from a synchronous source, use the {@link #connect(Consumer)} method.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>The behavior is determined by the implementor of this abstract class.</dd>\n     * </dl>\n     *\n     * @return the {@link Disposable} representing the connection\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
        "    /**\n     * 指示 {@code ConnectableObservable} 开始将其底层 {@link Observable} 的元素发射给 {@link Observer}。\n     * <p>\n     * 若要断开同步源，请使用 {@link #connect(Consumer)} 方法。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>行为由本抽象类的实现者决定。</dd>\n     * </dl>\n     *\n     * @return 表示连接的 {@link Disposable}\n     * @see <a href=\"http://reactivex.io/documentation/operators/connect.html\">ReactiveX documentation: Connect</a>\n     */",
    ),
    (
        "    /**\n     * Returns an {@link Observable} that stays connected to this {@code ConnectableObservable} as long as there\n     * is at least one subscription to this {@code ConnectableObservable}.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     * @return a new {@code Observable} instance\n     * @see <a href=\"http://reactivex.io/documentation/operators/refcount.html\">ReactiveX documentation: RefCount</a>\n     * @see #refCount(int)\n     * @see #refCount(long, TimeUnit)\n     * @see #refCount(int, long, TimeUnit)\n     */",
        "    /**\n     * 返回一个 {@link Observable}，只要本 {@code ConnectableObservable} 至少存在一个订阅，\n     * 它就保持与本 {@code ConnectableObservable} 的连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * @return 新的 {@code Observable} 实例\n     * @see <a href=\"http://reactivex.io/documentation/operators/refcount.html\">ReactiveX documentation: RefCount</a>\n     * @see #refCount(int)\n     * @see #refCount(long, TimeUnit)\n     * @see #refCount(int, long, TimeUnit)\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableObservable} if the number of subscribed\n     * observers reaches the specified count and disconnect if all {@link Observer}s have unsubscribed.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param observerCount the number of {@code Observer}s required to connect to the upstream\n     * @return the new {@link Observable} instance\n     * @throws IllegalArgumentException if {@code observerCount} is non-positive\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 observer 数量达到指定值时连接上游 {@code ConnectableObservable}，\n     * 若所有 {@link Observer} 均已取消订阅则断开连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param observerCount 连接上游所需的 {@code Observer} 数量\n     * @return 新的 {@link Observable} 实例\n     * @throws IllegalArgumentException 若 {@code observerCount} 非正数\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableObservable} if the number of subscribed\n     * observers reaches 1 and disconnect after the specified\n     * timeout if all {@link Observer}s have unsubscribed.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the {@code computation} {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout the time to wait before disconnecting after all {@code Observer}s unsubscribed\n     * @param unit the time unit of the timeout\n     * @return the new {@link Observable} instance\n     * @throws NullPointerException if {@code unit} is {@code null}\n     * @see #refCount(long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 observer 数量达到 1 时连接上游 {@code ConnectableObservable}，\n     * 若所有 {@link Observer} 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在 {@code computation} {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout 所有 {@code Observer} 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @return 新的 {@link Observable} 实例\n     * @throws NullPointerException 若 {@code unit} 为 {@code null}\n     * @see #refCount(long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableObservable} if the number of subscribed\n     * observers reaches 1 and disconnect after the specified\n     * timeout if all {@link Observer}s have unsubscribed.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the specified {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout the time to wait before disconnecting after all {@code Observer}s unsubscribed\n     * @param unit the time unit of the timeout\n     * @param scheduler the target scheduler to wait on before disconnecting\n     * @return the new {@link Observable} instance\n     * @throws NullPointerException if {@code unit} or {@code scheduler} is {@code null}\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 observer 数量达到 1 时连接上游 {@code ConnectableObservable}，\n     * 若所有 {@link Observer} 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在指定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param timeout 所有 {@code Observer} 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @param scheduler 断开连接前等待的目标调度器\n     * @return 新的 {@link Observable} 实例\n     * @throws NullPointerException 若 {@code unit} 或 {@code scheduler} 为 {@code null}\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableObservable} if the number of subscribed\n     * observers reaches the specified count and disconnect after the specified\n     * timeout if all {@link Observer}s have unsubscribed.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the {@code computation} {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param observerCount the number of {@code Observer}s required to connect to the upstream\n     * @param timeout the time to wait before disconnecting after all {@code Observer}s unsubscribed\n     * @param unit the time unit of the timeout\n     * @return the new {@link Observable} instance\n     * @throws NullPointerException if {@code unit} or {@code scheduler} is {@code null}\n     * @throws IllegalArgumentException if {@code observerCount} is non-positive\n     * @see #refCount(int, long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 observer 数量达到指定值时连接上游 {@code ConnectableObservable}，\n     * 若所有 {@link Observer} 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在 {@code computation} {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param observerCount 连接上游所需的 {@code Observer} 数量\n     * @param timeout 所有 {@code Observer} 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @return 新的 {@link Observable} 实例\n     * @throws NullPointerException 若 {@code unit} 为 {@code null}\n     * @throws IllegalArgumentException 若 {@code observerCount} 非正数\n     * @see #refCount(int, long, TimeUnit, Scheduler)\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Connects to the upstream {@code ConnectableObservable} if the number of subscribed\n     * observers reaches the specified count and disconnect after the specified\n     * timeout if all {@link Observer}s have unsubscribed.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>This {@code refCount} overload operates on the specified {@link Scheduler}.</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param observerCount the number of {@code Observer}s required to connect to the upstream\n     * @param timeout the time to wait before disconnecting after all {@code Observer}s unsubscribed\n     * @param unit the time unit of the timeout\n     * @param scheduler the target scheduler to wait on before disconnecting\n     * @return the new {@link Observable} instance\n     * @throws NullPointerException if {@code unit} or {@code scheduler} is {@code null}\n     * @throws IllegalArgumentException if {@code observerCount} is non-positive\n     * @since 2.2\n     */",
        "    /**\n     * 当已订阅的 observer 数量达到指定值时连接上游 {@code ConnectableObservable}，\n     * 若所有 {@link Observer} 均已取消订阅，则在指定超时后断开连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>此 {@code refCount} 重载在指定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     * <p>History: 2.1.14 - experimental\n     * @param observerCount 连接上游所需的 {@code Observer} 数量\n     * @param timeout 所有 {@code Observer} 取消订阅后断开连接前的等待时间\n     * @param unit 超时时间单位\n     * @param scheduler 断开连接前等待的目标调度器\n     * @return 新的 {@link Observable} 实例\n     * @throws NullPointerException 若 {@code unit} 或 {@code scheduler} 为 {@code null}\n     * @throws IllegalArgumentException 若 {@code observerCount} 非正数\n     * @since 2.2\n     */",
    ),
    (
        "    /**\n     * Returns an {@link Observable} that automatically connects (at most once) to this {@code ConnectableObservable}\n     * when the first {@link Observer} subscribes.\n     * <p>\n     * <img width=\"640\" height=\"348\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.o.png\" alt=\"\">\n     * <p>\n     * The connection happens after the first subscription and happens at most once\n     * during the lifetime of the returned {@code Observable}. If this {@code ConnectableObservable}\n     * terminates, the connection is never renewed, no matter how {@code Observer}s come\n     * and go. Use {@link #refCount()} to renew a connection or dispose an active\n     * connection when all {@code Observer}s have disposed their {@link Disposable}s.\n     * <p>\n     * This overload does not allow disconnecting the connection established via\n     * {@link #connect(Consumer)}. Use the {@link #autoConnect(int, Consumer)} overload\n     * to gain access to the {@code Disposable} representing the only connection.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>{@code autoConnect} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     *\n     * @return a new {@code Observable} instance that automatically connects to this {@code ConnectableObservable}\n     *         when the first {@code Observer} subscribes\n     */",
        "    /**\n     * 返回一个 {@link Observable}，在首个 {@link Observer} 订阅时自动（至多一次）连接本 {@code ConnectableObservable}。\n     * <p>\n     * <img width=\"640\" height=\"348\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.o.png\" alt=\"\">\n     * <p>\n     * 连接在首次订阅后发生，且在返回的 {@code Observable} 生命周期内至多发生一次。\n     * 若本 {@code ConnectableObservable} 终止，无论 {@code Observer} 如何增减，连接都不会恢复。\n     * 使用 {@link #refCount()} 可在所有 {@code Observer} 释放 {@link Disposable} 时\n     * 恢复连接或释放活跃连接。\n     * <p>\n     * 此重载无法断开通过 {@link #connect(Consumer)} 建立的连接。\n     * 使用 {@link #autoConnect(int, Consumer)} 重载可获取表示唯一连接的 {@code Disposable}。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>{@code autoConnect} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     *\n     * @return 在首个 {@code Observer} 订阅时自动连接本 {@code ConnectableObservable} 的新 {@code Observable} 实例\n     */",
    ),
    (
        "    /**\n     * Returns an {@link Observable} that automatically connects (at most once) to this {@code ConnectableObservable}\n     * when the specified number of {@link Observer}s subscribe to it.\n     * <p>\n     * <img width=\"640\" height=\"348\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.o.png\" alt=\"\">\n     * <p>\n     * The connection happens after the given number of subscriptions and happens at most once\n     * during the lifetime of the returned {@code Observable}. If this {@code ConnectableObservable}\n     * terminates, the connection is never renewed, no matter how {@code Observer}s come\n     * and go. Use {@link #refCount()} to renew a connection or dispose an active\n     * connection when all {@code Observer}s have disposed their {@link Disposable}s.\n     * <p>\n     * This overload does not allow disconnecting the connection established via\n     * {@link #connect(Consumer)}. Use the {@link #autoConnect(int, Consumer)} overload\n     * to gain access to the {@code Disposable} representing the only connection.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>{@code autoConnect} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     *\n     * @param numberOfObservers the number of subscribers to await before calling connect\n     *                            on the {@code ConnectableObservable}. A non-positive value indicates\n     *                            an immediate connection.\n     * @return a new {@code Observable} instance that automatically connects to this {@code ConnectableObservable}\n     *         when the specified number of {@code Observer}s subscribe to it\n     */",
        "    /**\n     * 返回一个 {@link Observable}，在指定数量的 {@link Observer} 订阅时自动（至多一次）连接本 {@code ConnectableObservable}。\n     * <p>\n     * <img width=\"640\" height=\"348\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.o.png\" alt=\"\">\n     * <p>\n     * 连接在给定数量的订阅后发生，且在返回的 {@code Observable} 生命周期内至多发生一次。\n     * 若本 {@code ConnectableObservable} 终止，无论 {@code Observer} 如何增减，连接都不会恢复。\n     * 使用 {@link #refCount()} 可在所有 {@code Observer} 释放 {@link Disposable} 时\n     * 恢复连接或释放活跃连接。\n     * <p>\n     * 此重载无法断开通过 {@link #connect(Consumer)} 建立的连接。\n     * 使用 {@link #autoConnect(int, Consumer)} 重载可获取表示唯一连接的 {@code Disposable}。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>{@code autoConnect} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     *\n     * @param numberOfObservers 在 {@code ConnectableObservable} 上调用 connect 前等待的订阅者数量。\n     *                            非正数表示立即连接。\n     * @return 在指定数量的 {@code Observer} 订阅时自动连接本 {@code ConnectableObservable} 的新 {@code Observable} 实例\n     */",
    ),
    (
        "    /**\n     * Returns an {@link Observable} that automatically connects (at most once) to this {@code ConnectableObservable}\n     * when the specified number of {@link Observer}s subscribe to it and calls the\n     * specified callback with the {@link Disposable} associated with the established connection.\n     * <p>\n     * <img width=\"640\" height=\"348\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.o.png\" alt=\"\">\n     * <p>\n     * The connection happens after the given number of subscriptions and happens at most once\n     * during the lifetime of the returned {@code Observable}. If this {@code ConnectableObservable}\n     * terminates, the connection is never renewed, no matter how {@code Observer}s come\n     * and go. Use {@link #refCount()} to renew a connection or dispose an active\n     * connection when all {@code Observer}s have disposed their {@code Disposable}s.\n     * <dl>\n     *  <dt><b>Scheduler:</b></dt>\n     *  <dd>{@code autoConnect} overload does not operate on any particular {@link Scheduler}.</dd>\n     * </dl>\n     *\n     * @param numberOfObservers the number of subscribers to await before calling connect\n     *                            on the {@code ConnectableObservable}. A non-positive value indicates\n     *                            an immediate connection.\n     * @param connection the callback {@link Consumer} that will receive the {@code Disposable} representing the\n     *                   established connection\n     * @return a new {@code Observable} instance that automatically connects to this {@code ConnectableObservable}\n     *         when the specified number of {@code Observer}s subscribe to it and calls the\n     *         specified callback with the {@code Disposable} associated with the established connection\n     * @throws NullPointerException if {@code connection} is {@code null}\n     */",
        "    /**\n     * 返回一个 {@link Observable}，在指定数量的 {@link Observer} 订阅时自动（至多一次）连接本 {@code ConnectableObservable}，\n     * 并以已建立连接关联的 {@link Disposable} 调用指定回调。\n     * <p>\n     * <img width=\"640\" height=\"348\" src=\"https://raw.github.com/wiki/ReactiveX/RxJava/images/rx-operators/autoConnect.o.png\" alt=\"\">\n     * <p>\n     * 连接在给定数量的订阅后发生，且在返回的 {@code Observable} 生命周期内至多发生一次。\n     * 若本 {@code ConnectableObservable} 终止，无论 {@code Observer} 如何增减，连接都不会恢复。\n     * 使用 {@link #refCount()} 可在所有 {@code Observer} 释放 {@code Disposable} 时\n     * 恢复连接或释放活跃连接。\n     * <dl>\n     *  <dt><b>调度器：</b></dt>\n     *  <dd>{@code autoConnect} 重载不在任何特定 {@link Scheduler} 上运行。</dd>\n     * </dl>\n     *\n     * @param numberOfObservers 在 {@code ConnectableObservable} 上调用 connect 前等待的订阅者数量。\n     *                            非正数表示立即连接。\n     * @param connection 将接收表示已建立连接的 {@code Disposable} 的回调 {@link Consumer}\n     * @return 在指定数量的 {@code Observer} 订阅时自动连接本 {@code ConnectableObservable} 并以\n     *         已建立连接关联的 {@code Disposable} 调用指定回调的新 {@code Observable} 实例\n     * @throws NullPointerException 若 {@code connection} 为 {@code null}\n     */",
    ),
]

LARGE_REPLACEMENTS = {
    "ConnectableFlowable.java": CONNECTABLE_FLOWABLE,
    "ConnectableObservable.java": CONNECTABLE_OBSERVABLE,
}
