#!/usr/bin/env python3
"""Chinese-annotate Alibaba Sentinel 1.8.10 wave-1a core [0:15]."""
from __future__ import annotations
import json, re, shutil
from pathlib import Path

ROOT = Path("/workspace")
VER = ROOT / "sentinel/1.8.10"
ANALYZED = VER / "analyzed"
QUEUE = VER / "_reports/class-queue"
BATCH_FILES = json.loads((QUEUE / "batch.json").read_text())["files"][:15]

COMMON = [
 ("Record statistics and perform rule checking for the given resource.", "对给定资源记录统计并执行规则检查。"),
 ("Record statistics and perform rule checking for the given method.", "对给定方法记录统计并执行规则检查。"),
 ("Checking all {@link Rule}s about the protected method.", "检查受保护方法相关的全部 {@link Rule}。"),
 ("the traffic type (inbound, outbound or internal). This is used\n     *                    to mark whether it can be blocked when the system is unstable,\n     *                    only inbound traffic could be blocked by {@link SystemRule}", "流量类型（入站、出站或内部）。用于标记系统不稳定时是否可被限流，\n     *                    仅入站流量可被 {@link SystemRule} 阻断"),
 ("the traffic type (inbound, outbound or internal). This is used\n     *                     to mark whether it can be blocked when the system is unstable,\n     *                     only inbound traffic could be blocked by {@link SystemRule}", "流量类型（入站、出站或内部）。用于标记系统不稳定时是否可被限流，\n     *                     仅入站流量可被 {@link SystemRule} 阻断"),
 ("the amount of calls within the invocation (e.g. batchCount=2 means request for 2 tokens)", "单次调用内的请求数量（例如 batchCount=2 表示申请 2 个令牌）"),
 ("args for parameter flow control or customized slots", "用于热点参数流控或自定义 Slot 的参数"),
 ("args for parameter flow control", "用于热点参数流控的参数"),
 ("the unique name of the protected resource", "受保护资源的唯一名称"),
 ("the unique name for the protected resource", "受保护资源的唯一名称"),
 ("the unique string for the resource", "资源的唯一字符串标识"),
 ("the protected method", "受保护的方法"),
 ("the {@link Entry} of this invocation (used for mark the invocation complete and get context data)", "本次调用的 {@link Entry}（用于标记调用完成并获取上下文数据）"),
 ("the {@link Entry} of this invocation (used for mark the invocation complete and get context data).", "本次调用的 {@link Entry}（用于标记调用完成并获取上下文数据）。"),
 ("if the block criteria is met", "若满足阻断条件"),
 ("if the block criteria is met (e.g. metric exceeded the threshold of any rules)", "若满足阻断条件（例如指标超过某条规则阈值）"),
 ("true if no rule's threshold is exceeded, otherwise return false.", "若无规则阈值被超过则返回 true，否则返回 false。"),
 ("classification of the resource (e.g. Web or RPC)", "资源分类（例如 Web 或 RPC）"),
 ("the classification of the resource", "资源分类"),
 ("whether the entry is prioritized", "该 Entry 是否具有优先级"),
]

R: dict[str, list[tuple[str,str]]] = {}
R["AsyncEntry.java"] = [
 ("/**\n * The entry for asynchronous resources.\n *\n * @author Eric Zhao\n * @since 0.2.0\n */", "/**\n * 异步资源的 Entry。\n *\n * @author Eric Zhao\n * @since 0.2.0\n */"),
 ("    /**\n     * Remove current entry from local context, but does not exit.\n     */", "    /**\n     * 从本地上下文中移除当前 Entry，但不执行 exit。\n     */"),
 ("    /**\n     * The async context should not be initialized until the node for current resource has been set to current entry.\n     */", "    /**\n     * 异步上下文不应在当前资源的 Node 已设置到当前 Entry 之前初始化。\n     */"),
]
R["Constants.java"] = [
 ("/**\n * Universal constants of Sentinel.\n *\n * @author qinan.qn\n * @author youji.zj\n * @author jialiang.linjl\n * @author Eric Zhao\n */", "/**\n * Sentinel 通用常量。\n *\n * @author qinan.qn\n * @author youji.zj\n * @author jialiang.linjl\n * @author Eric Zhao\n */"),
 ("    /**\n     * A virtual resource identifier for total inbound statistics (since 1.5.0).\n     */", "    /**\n     * 入站总流量的虚拟资源标识（自 1.5.0 起）。\n     */"),
 ("    /**\n     * A virtual resource identifier for cpu usage statistics (since 1.6.1).\n     */", "    /**\n     * CPU 使用率的虚拟资源标识（自 1.6.1 起）。\n     */"),
 ("    /**\n     * A virtual resource identifier for system load statistics (since 1.6.1).\n     */", "    /**\n     * 系统负载的虚拟资源标识（自 1.6.1 起）。\n     */"),
 ("    /**\n     * Global ROOT statistic node that represents the universal parent node.\n     */", "    /**\n     * 全局 ROOT 统计节点，表示通用父节点。\n     */"),
 ("    /**\n     * Global statistic node for inbound traffic. Usually used for {@code SystemRule} checking.\n     */", "    /**\n     * 入站流量的全局统计节点，通常用于 {@code SystemRule} 检查。\n     */"),
 ("    /**\n     * The global switch for Sentinel.\n     */", "    /**\n     * Sentinel 全局开关。\n     */"),
 ("    /**\n     * Order of default processor slots\n     */", "    /**\n     * 默认 ProcessorSlot 顺序\n     */"),
]
R["CtEntry.java"] = [
 ("/**\n * Linked entry within current context.\n *\n * @author jialiang.linjl\n * @author Eric Zhao\n */", "/**\n * 当前上下文中的链式 Entry。\n *\n * @author jialiang.linjl\n * @author Eric Zhao\n */"),
 ("        // The entry should not be associated to NullContext.", "        // Entry 不应关联到 NullContext。"),
 ("    /**\n     * Note: the exit handlers will be called AFTER onExit of slot chain.\n     */", "    /**\n     * 注意：exit 处理器将在 Slot 链的 onExit 之后调用。\n     */"),
 ("            // Null context should exit without clean-up.", "            // NullContext 应直接退出，不做清理。"),
 ("                // Clean previous call stack.", "                // 清理先前的调用栈。"),
 ("                // Go through the onExit hook of all slots.", "                // 依次触发所有 Slot 的 onExit 钩子。"),
 ("                // Go through the existing terminate handlers (associated to this invocation).", "                // 依次执行与本调用关联的终止处理器。"),
 ("                // Restore the call stack.", "                // 恢复调用栈。"),
 ("                    // Default context (auto entered) will be exited automatically.", "                    // 默认上下文（自动进入）将自动退出。"),
 ("                // Clean the reference of context in current entry to avoid duplicate exit.", "                // 清除当前 Entry 中的 context 引用，避免重复 exit。"),
]
R["CtSph.java"] = [
 ("    /**\n     * Same resource({@link ResourceWrapper#equals(Object)}) will share the same\n     * {@link ProcessorSlotChain}, no matter in which {@link Context}.\n     */", "    /**\n     * 相同资源（{@link ResourceWrapper#equals(Object)}）无论在哪个 {@link Context} 中\n     * 都共享同一 {@link ProcessorSlotChain}。\n     */"),
 ("        // The async entry will be removed from current context as soon as it has been created.", "        // 异步 Entry 创建后立即从当前上下文中移除。"),
 ("            // The {@link NullContext} indicates that the amount of context has exceeded the threshold,\n            // so here init the entry only. No rule checking will be done.", "            // {@link NullContext} 表示上下文数量已超过阈值，\n            // 此处仅初始化 Entry，不执行规则检查。"),
 ("            // Using default context.", "            // 使用默认上下文。"),
 ("        // Global switch is turned off, so no rule checking will be done.", "        // 全局开关关闭，不执行规则检查。"),
 ("        // Means processor cache size exceeds {@link Constants.MAX_SLOT_CHAIN_SIZE}, so no rule checking will be done.", "        // 表示 Processor 缓存大小超过 {@link Constants.MAX_SLOT_CHAIN_SIZE}，不执行规则检查。"),
 ("            // Initiate the async context only when the entry successfully passed the slot chain.", "            // 仅在 Entry 成功通过 Slot 链后初始化异步上下文。"),
 ("            // The asynchronous call may take time in background, and current context should not be hanged on it.\n            // So we need to remove current async entry from current context.", "            // 异步调用可能在后台耗时，当前上下文不应挂在其上。\n            // 因此需将当前异步 Entry 从当前上下文中移除。"),
 ("            // When blocked, the async entry will be exited on current context.\n            // The async context will not be initialized.", "            // 被阻断时，异步 Entry 将在当前上下文中 exit。\n            // 异步上下文不会被初始化。"),
 ("            // This should not happen, unless there are errors existing in Sentinel internal.\n            // When this happens, async context is not initialized.", "            // 正常情况下不应发生，除非 Sentinel 内部存在错误。\n            // 发生时异步上下文不会被初始化。"),
 ("        // Global switch is close, no rule checking will do.", "        // 全局开关关闭，不执行规则检查。"),
 ("         * Means amount of resources (slot chain) exceeds {@link Constants.MAX_SLOT_CHAIN_SIZE},\n         * so no rule checking will be done.", "         * 表示资源（Slot 链）数量超过 {@link Constants.MAX_SLOT_CHAIN_SIZE}，\n         * 不执行规则检查。"),
 ("            // This should not happen, unless there are errors existing in Sentinel internal.", "            // 正常情况下不应发生，除非 Sentinel 内部存在错误。"),
 ("    /**\n     * Do all {@link Rule}s checking about the resource.\n     *\n     * <p>Each distinct resource will use a {@link ProcessorSlot} to do rules checking. Same resource will use\n     * same {@link ProcessorSlot} globally. </p>\n     *\n     * <p>Note that total {@link ProcessorSlot} count must not exceed {@link Constants#MAX_SLOT_CHAIN_SIZE},\n     * otherwise no rules checking will do. In this condition, all requests will pass directly, with no checking\n     * or exception.</p>\n     *\n     * @param resourceWrapper resource name\n     * @param count           tokens needed\n     * @param args            arguments of user method call\n     * @return {@link Entry} represents this call\n     * @throws BlockException if any rule's threshold is exceeded\n     */", "    /**\n     * 对资源执行全部 {@link Rule} 检查。\n     *\n     * <p>每个不同资源使用一个 {@link ProcessorSlot} 做规则检查。相同资源全局共享同一\n     * {@link ProcessorSlot}。</p>\n     *\n     * <p>注意 {@link ProcessorSlot} 总数不得超过 {@link Constants#MAX_SLOT_CHAIN_SIZE}，\n     * 否则不做规则检查。此时所有请求直接通过，无检查也无异常。</p>\n     *\n     * @param resourceWrapper 资源名称\n     * @param count           所需令牌数\n     * @param args            用户方法调用参数\n     * @return 表示本次调用的 {@link Entry}\n     * @throws BlockException 若任一规则阈值被超过\n     */"),
 ("    /**\n     * Get {@link ProcessorSlotChain} of the resource. new {@link ProcessorSlotChain} will\n     * be created if the resource doesn't relate one.\n     *\n     * <p>Same resource({@link ResourceWrapper#equals(Object)}) will share the same\n     * {@link ProcessorSlotChain} globally, no matter in which {@link Context}.<p/>\n     *\n     * <p>\n     * Note that total {@link ProcessorSlot} count must not exceed {@link Constants#MAX_SLOT_CHAIN_SIZE},\n     * otherwise null will return.\n     * </p>\n     *\n     * @param resourceWrapper target resource\n     * @return {@link ProcessorSlotChain} of the resource\n     */", "    /**\n     * 获取资源的 {@link ProcessorSlotChain}。若资源尚未关联则创建新的\n     * {@link ProcessorSlotChain}。\n     *\n     * <p>相同资源（{@link ResourceWrapper#equals(Object)}）全局共享同一\n     * {@link ProcessorSlotChain}，与所在 {@link Context} 无关。<p/>\n     *\n     * <p>\n     * 注意 {@link ProcessorSlot} 总数不得超过 {@link Constants#MAX_SLOT_CHAIN_SIZE}，\n     * 否则返回 null。\n     * </p>\n     *\n     * @param resourceWrapper 目标资源\n     * @return 资源的 {@link ProcessorSlotChain}\n     */"),
 ("                    // Entry size limit.", "                    // Entry 数量上限。"),
 ("    /**\n     * Get current size of created slot chains.\n     *\n     * @return size of created slot chains\n     * @since 0.2.0\n     */", "    /**\n     * 获取已创建 Slot 链的当前数量。\n     *\n     * @return 已创建 Slot 链数量\n     * @since 0.2.0\n     */"),
 ("    /**\n     * Reset the slot chain map. Only for internal test.\n     *\n     * @since 0.2.0\n     */", "    /**\n     * 重置 Slot 链映射。仅供内部测试。\n     *\n     * @since 0.2.0\n     */"),
 ("    /**\n     * Only for internal test.\n     *\n     * @since 0.2.0\n     */", "    /**\n     * 仅供内部测试。\n     *\n     * @since 0.2.0\n     */"),
 ("    /**\n     * This class is used for skip context name checking.\n     */", "    /**\n     * 用于跳过上下文名称检查的辅助类。\n     */"),
]
R["Entry.java"] = [
 ("/**\n * Each {@link SphU}#entry() will return an {@link Entry}. This class holds information of current invocation:<br/>\n *\n * <ul>\n * <li>createTime, the create time of this entry, using for rt statistics.</li>\n * <li>current {@link Node}, that is statistics of the resource in current context.</li>\n * <li>origin {@link Node}, that is statistics for the specific origin. Usually the\n * origin could be the Service Consumer's app name, see\n * {@link ContextUtil#enter(String name, String origin)} </li>\n * <li>{@link ResourceWrapper}, that is resource name.</li>\n * <br/>\n * </ul>\n *\n * <p>\n * A invocation tree will be created if we invoke SphU#entry() multi times in the same {@link Context},\n * so parent or child entry may be held by this to form the tree. Since {@link Context} always holds\n * the current entry in the invocation tree, every {@link Entry#exit()} call should modify\n * {@link Context#setCurEntry(Entry)} as parent entry of this.\n * </p>\n *\n * @author qinan.qn\n * @author jialiang.linjl\n * @author leyou(lihao)\n * @author Eric Zhao\n * @see SphU\n * @see Context\n * @see ContextUtil\n */", "/**\n * 每次 {@link SphU}#entry() 返回一个 {@link Entry}。本类保存当前调用的信息：<br/>\n *\n * <ul>\n * <li>createTime，Entry 创建时间，用于 RT 统计。</li>\n * <li>current {@link Node}，即当前上下文中该资源的统计节点。</li>\n * <li>origin {@link Node}，即特定来源的统计节点。来源通常是服务消费者的应用名，见\n * {@link ContextUtil#enter(String name, String origin)} </li>\n * <li>{@link ResourceWrapper}，即资源名称。</li>\n * <br/>\n * </ul>\n *\n * <p>\n * 在同一 {@link Context} 中多次调用 SphU#entry() 会形成调用树，\n * 本类通过 parent 或 child 引用构成该树。由于 {@link Context} 始终持有调用树中的当前 Entry，\n * 每次 {@link Entry#exit()} 都应将 {@link Context#setCurEntry(Entry)} 更新为本 Entry 的父 Entry。\n * </p>\n *\n * @author qinan.qn\n * @author jialiang.linjl\n * @author leyou(lihao)\n * @author Eric Zhao\n * @see SphU\n * @see Context\n * @see ContextUtil\n */"),
 ("    /**\n     * {@link Node} of the specific origin, Usually the origin is the Service Consumer.\n     */", "    /**\n     * 特定来源的 {@link Node}，通常来源为服务消费者。\n     */"),
 ("    /**\n     * Complete the current resource entry and restore the entry stack in context.\n     * Do not need to carry count or args parameter, initialization does\n     * @throws ErrorEntryFreeException if entry in current context does not match current entry\n     */", "    /**\n     * 完成当前资源 Entry 并恢复上下文中的 Entry 栈。\n     * 无需传入 count 或 args 参数，初始化时已携带。\n     * @throws ErrorEntryFreeException 若当前上下文中的 Entry 与当前 Entry 不匹配\n     */"),
 ("    /**\n     * Equivalent to {@link #exit()}. Support try-with-resources since JDK 1.7.\n     *\n     * @since 1.5.0\n     */", "    /**\n     * 等价于 {@link #exit()}。自 JDK 1.7 起支持 try-with-resources。\n     *\n     * @since 1.5.0\n     */"),
 ("    /**\n     * Exit this entry. This method should invoke if and only if once at the end of the resource protection.\n     *\n     * @param count tokens to release.\n     * @param args extra parameters\n     * @throws ErrorEntryFreeException, if {@link Context#getCurEntry()} is not this entry.\n     */", "    /**\n     * 退出本 Entry。应在资源保护结束时且仅调用一次。\n     *\n     * @param count 要释放的令牌数\n     * @param args 额外参数\n     * @throws ErrorEntryFreeException 若 {@link Context#getCurEntry()} 不是本 Entry\n     */"),
 ("    /**\n     * Exit this entry.\n     *\n     * @param count tokens to release.\n     * @param args extra parameters\n     * @return next available entry after exit, that is the parent entry.\n     * @throws ErrorEntryFreeException, if {@link Context#getCurEntry()} is not this entry.\n     */", "    /**\n     * 退出本 Entry。\n     *\n     * @param count 要释放的令牌数\n     * @param args 额外参数\n     * @return exit 后下一个可用 Entry，即父 Entry\n     * @throws ErrorEntryFreeException 若 {@link Context#getCurEntry()} 不是本 Entry\n     */"),
 ("    /**\n     * Get related {@link Node} of the parent {@link Entry}.\n     *\n     * @return\n     */", "    /**\n     * 获取父 {@link Entry} 关联的 {@link Node}。\n     *\n     * @return 父 Entry 的 Node\n     */"),
 ("    /**\n     * Get origin {@link Node} of the this {@link Entry}.\n     *\n     * @return origin {@link Node} of the this {@link Entry}, may be null if no origin specified by\n     * {@link ContextUtil#enter(String name, String origin)}.\n     */", "    /**\n     * 获取本 {@link Entry} 的来源 {@link Node}。\n     *\n     * @return 本 {@link Entry} 的来源 {@link Node}；若未通过\n     * {@link ContextUtil#enter(String name, String origin)} 指定来源则可能为 null\n     */"),
 ("    /**\n     * Like {@code CompletableFuture} since JDK 8, it guarantees specified handler\n     * is invoked when this entry terminated (exited), no matter it's blocked or permitted.\n     * Use it when you did some STATEFUL operations on entries.\n     * \n     * @param handler handler function on the invocation terminates\n     * @since 1.8.0\n     */", "    /**\n     * 类似 JDK 8 的 {@code CompletableFuture}，保证在本 Entry 终止（exit）时调用指定处理器，\n     * 无论被阻断还是放行。\n     * 在 Entry 上执行有状态操作时使用。\n     * \n     * @param handler 调用终止时的处理函数\n     * @since 1.8.0\n     */"),
]
R["EntryType.java"] = [
 ("/**\n * An enum marks resource invocation direction.\n *\n * @author jialiang.linjl\n * @author Yanming Zhou\n */", "/**\n * 标记资源调用方向的枚举。\n *\n * @author jialiang.linjl\n * @author Yanming Zhou\n */"),
 ("    /**\n     * Inbound traffic\n     */", "    /**\n     * 入站流量\n     */"),
 ("    /**\n     * Outbound traffic\n     */", "    /**\n     * 出站流量\n     */"),
]
R["Env.java"] = [
 ("/**\n * Sentinel Env. This class will trigger all initialization for Sentinel.\n *\n * <p>\n * NOTE: to prevent deadlocks, other classes' static code block or static field should\n * NEVER refer to this class.\n * </p>\n *\n * @author jialiang.linjl\n */", "/**\n * Sentinel 环境类。本类触发 Sentinel 的全部初始化。\n *\n * <p>\n * 注意：为防止死锁，其他类的静态代码块或静态字段\n * 绝不应引用本类。\n * </p>\n *\n * @author jialiang.linjl\n */"),
 ("        // If init fails, the process will exit.", "        // 若初始化失败，进程将退出。"),
]
R["ErrorEntryFreeException.java"] = [
 ("/**\n * Represents order mismatch of resource entry and resource exit (pair mismatch).\n *\n * @author qinan.qn\n */", "/**\n * 表示资源 entry 与 exit 顺序不匹配（配对不一致）。\n *\n * @author qinan.qn\n */"),
]
R["ResourceTypeConstants.java"] = [
 ("/**\n * @author Eric Zhao\n * @since 1.7.0\n */", "/**\n * 资源类型常量，用于区分 Web、RPC、网关、数据库等不同资源分类。\n *\n * @author Eric Zhao\n * @since 1.7.0\n */"),
 ("    public static final int COMMON = 0;", "    /** 通用资源类型。 */\n    public static final int COMMON = 0;"),
 ("    public static final int COMMON_WEB = 1;", "    /** Web 资源类型。 */\n    public static final int COMMON_WEB = 1;"),
 ("    public static final int COMMON_RPC = 2;", "    /** RPC 资源类型。 */\n    public static final int COMMON_RPC = 2;"),
 ("    public static final int COMMON_API_GATEWAY = 3;", "    /** API 网关资源类型。 */\n    public static final int COMMON_API_GATEWAY = 3;"),
 ("    public static final int COMMON_DB_SQL = 4;", "    /** 数据库 SQL 资源类型。 */\n    public static final int COMMON_DB_SQL = 4;"),
]
R["Sph.java"] = [
 ("/**\n * The basic interface for recording statistics and performing rule checking for resources.\n *\n * @author qinan.qn\n * @author jialiang.linjl\n * @author leyou\n * @author Eric Zhao\n */", "/**\n * 对资源记录统计并执行规则检查的基础接口。\n *\n * @author qinan.qn\n * @author jialiang.linjl\n * @author leyou\n * @author Eric Zhao\n */"),
 ("    /**\n     * Create a protected asynchronous resource.\n     *\n     * @param name        the unique name for the protected resource\n     * @param trafficType the traffic type (inbound, outbound or internal). This is used\n     *                    to mark whether it can be blocked when the system is unstable,\n     *                    only inbound traffic could be blocked by {@link SystemRule}\n     * @param batchCount  the amount of calls within the invocation (e.g. batchCount=2 means request for 2 tokens)\n     * @param args        args for parameter flow control or customized slots\n     * @return created asynchronous entry\n     * @throws BlockException if the block criteria is met\n     * @since 0.2.0\n     */", "    /**\n     * 创建受保护的异步资源。\n     *\n     * @param name        受保护资源的唯一名称\n     * @param trafficType 流量类型（入站、出站或内部）。用于标记系统不稳定时是否可被限流，\n     *                    仅入站流量可被 {@link SystemRule} 阻断\n     * @param batchCount  单次调用内的请求数量（例如 batchCount=2 表示申请 2 个令牌）\n     * @param args        用于热点参数流控或自定义 Slot 的参数\n     * @return 创建的异步 Entry\n     * @throws BlockException 若满足阻断条件\n     * @since 0.2.0\n     */"),
 ("    /**\n     * Create a protected resource with priority.\n     *\n     * @param name        the unique name for the protected resource\n     * @param trafficType the traffic type (inbound, outbound or internal). This is used\n     *                    to mark whether it can be blocked when the system is unstable,\n     *                    only inbound traffic could be blocked by {@link SystemRule}\n     * @param batchCount  the amount of calls within the invocation (e.g. batchCount=2 means request for 2 tokens)\n     * @param prioritized whether the entry is prioritized\n     * @return the {@link Entry} of this invocation (used for mark the invocation complete and get context data)\n     * @throws BlockException if the block criteria is met\n     * @since 1.4.0\n     */", "    /**\n     * 创建带优先级的受保护资源。\n     *\n     * @param name        受保护资源的唯一名称\n     * @param trafficType 流量类型（入站、出站或内部）。用于标记系统不稳定时是否可被限流，\n     *                    仅入站流量可被 {@link SystemRule} 阻断\n     * @param batchCount  单次调用内的请求数量（例如 batchCount=2 表示申请 2 个令牌）\n     * @param prioritized 该 Entry 是否具有优先级\n     * @return 本次调用的 {@link Entry}（用于标记调用完成并获取上下文数据）\n     * @throws BlockException 若满足阻断条件\n     * @since 1.4.0\n     */"),
 ("    /**\n     * Create a protected resource with priority.\n     *\n     * @param name        the unique name for the protected resource\n     * @param trafficType the traffic type (inbound, outbound or internal). This is used\n     *                    to mark whether it can be blocked when the system is unstable,\n     *                    only inbound traffic could be blocked by {@link SystemRule}\n     * @param batchCount  the amount of calls within the invocation (e.g. batchCount=2 means request for 2 tokens)\n     * @param prioritized whether the entry is prioritized\n     * @param args        args for parameter flow control or customized slots\n     * @return the {@link Entry} of this invocation (used for mark the invocation complete and get context data)\n     * @throws BlockException if the block criteria is met\n     * @since 1.5.0\n     */", "    /**\n     * 创建带优先级的受保护资源。\n     *\n     * @param name        受保护资源的唯一名称\n     * @param trafficType 流量类型（入站、出站或内部）。用于标记系统不稳定时是否可被限流，\n     *                    仅入站流量可被 {@link SystemRule} 阻断\n     * @param batchCount  单次调用内的请求数量（例如 batchCount=2 表示申请 2 个令牌）\n     * @param prioritized 该 Entry 是否具有优先级\n     * @param args        用于热点参数流控或自定义 Slot 的参数\n     * @return 本次调用的 {@link Entry}（用于标记调用完成并获取上下文数据）\n     * @throws BlockException 若满足阻断条件\n     * @since 1.5.0\n     */"),
]
R["SphO.java"] = [
 ("/**\n * Conceptually, physical or logical resource that need protection should be\n * surrounded by an entry. The requests to this resource will be blocked if any\n * criteria is met, eg. when any {@link Rule}'s threshold is exceeded. Once blocked,\n * {@link SphO}#entry() will return false.\n *\n * <p>\n * To configure the criteria, we can use <code>XXXRuleManager.loadRules()</code> to add rules. eg.\n * {@link FlowRuleManager#loadRules(List)}, {@link DegradeRuleManager#loadRules(List)},\n * {@link SystemRuleManager#loadRules(List)}.\n * </p>\n *\n * <p>\n * Following code is an example. {@code \"abc\"} represent a unique name for the\n * protected resource:\n * </p>\n *\n * <pre>\n * public void foo() {\n *    if (SphO.entry(\"abc\")) {\n *        try {\n *            // business logic\n *        } finally {\n *            SphO.exit(); // must exit()\n *        }\n *    } else {\n *        // failed to enter the protected resource.\n *    }\n * }\n * </pre>\n *\n * Make sure {@code SphO.entry()} and {@link SphO#exit()} be paired in the same thread,\n * otherwise {@link ErrorEntryFreeException} will be thrown.\n *\n * @author jialiang.linjl\n * @author leyou\n * @author Eric Zhao\n * @see SphU\n */", "/**\n * 概念上，需要保护的物理或逻辑资源应被 Entry 包裹。若满足任一条件\n *（例如任一 {@link Rule} 阈值被超过），对该资源的请求将被阻断。一旦被阻断，\n * {@link SphO}#entry() 将返回 false。\n *\n * <p>\n * 可通过 <code>XXXRuleManager.loadRules()</code> 配置条件，例如\n * {@link FlowRuleManager#loadRules(List)}、{@link DegradeRuleManager#loadRules(List)}、\n * {@link SystemRuleManager#loadRules(List)}。\n * </p>\n *\n * <p>\n * 示例如下，{@code \"abc\"} 表示受保护资源的唯一名称：\n * </p>\n *\n * <pre>\n * public void foo() {\n *    if (SphO.entry(\"abc\")) {\n *        try {\n *            // 业务逻辑\n *        } finally {\n *            SphO.exit(); // 必须 exit()\n *        }\n *    } else {\n *        // 未能进入受保护资源\n *    }\n * }\n * </pre>\n *\n * 确保 {@code SphO.entry()} 与 {@link SphO#exit()} 在同一线程中配对调用，\n * 否则将抛出 {@link ErrorEntryFreeException}。\n *\n * @author jialiang.linjl\n * @author leyou\n * @author Eric Zhao\n * @see SphU\n */"),
 ("     * @param name the unique name of the protected resource\n     * @return true if no rule's threshold is exceeded, otherwise return false.", "     * @param name 受保护资源的唯一名称\n     * @return 若无规则阈值被超过则返回 true，否则返回 false"),
 ("     * @param method the protected method\n     * @return true if no rule's threshold is exceeded, otherwise return false.", "     * @param method 受保护的方法\n     * @return 若无规则阈值被超过则返回 true，否则返回 false"),
 ("     * Record statistics and perform rule checking for the given method resource.\n     *", "     * 对给定方法资源记录统计并执行规则检查。\n     *"),
]
R["SphResourceTypeSupport.java"] = [
 ("/**\n * @author Eric Zhao\n * @since 1.7.0\n */", "/**\n * 支持按资源类型分类的 Sph 扩展接口。\n *\n * @author Eric Zhao\n * @since 1.7.0\n */"),
 ("    /**\n     * Record statistics and perform rule checking for the given resource with provided classification.\n     *", "    /**\n     * 对给定分类的资源记录统计并执行规则检查。\n     *"),
 ("    /**\n     * Record statistics and perform rule checking for the given resource with the provided classification.\n     *", "    /**\n     * 对给定分类的资源记录统计并执行规则检查。\n     *"),
 ("    /**\n     * Record statistics and perform rule checking for the given resource that indicates an async invocation.\n     *", "    /**\n     * 对表示异步调用的给定资源记录统计并执行规则检查。\n     *"),
]
R["SphU.java"] = [
 ("/**\n * <p>The fundamental Sentinel API for recording statistics and performing rule checking for resources.</p>\n * <p>\n * Conceptually, physical or logical resource that need protection should be\n * surrounded by an entry. The requests to this resource will be blocked if any\n * criteria is met, eg. when any {@link Rule}'s threshold is exceeded. Once blocked,\n * a {@link BlockException} will be thrown.\n * </p>\n * <p>\n * To configure the criteria, we can use <code>XxxRuleManager.loadRules()</code> to load rules.\n * </p>\n *\n * <p>\n * Following code is an example, {@code \"abc\"} represent a unique name for the\n * protected resource:\n * </p>\n *\n * <pre>\n *  public void foo() {\n *     Entry entry = null;\n *     try {\n *        entry = SphU.entry(\"abc\");\n *        // resource that need protection\n *     } catch (BlockException blockException) {\n *         // when goes there, it is blocked\n *         // add blocked handle logic here\n *     } catch (Throwable bizException) {\n *         // business exception\n *         Tracer.trace(bizException);\n *     } finally {\n *         // ensure finally be executed\n *         if (entry != null){\n *             entry.exit();\n *         }\n *     }\n *  }\n * </pre>\n *\n * <p>\n * Make sure {@code SphU.entry()} and {@link Entry#exit()} be paired in the same thread,\n * otherwise {@link ErrorEntryFreeException} will be thrown.\n * </p>\n *\n * @author jialiang.linjl\n * @author Eric Zhao\n * @see SphO\n */", "/**\n * <p>Sentinel 记录资源统计并执行规则检查的基础 API。</p>\n * <p>\n * 概念上，需要保护的物理或逻辑资源应被 Entry 包裹。若满足任一条件\n *（例如任一 {@link Rule} 阈值被超过），对该资源的请求将被阻断，并抛出\n * {@link BlockException}。\n * </p>\n * <p>\n * 可通过 <code>XxxRuleManager.loadRules()</code> 加载规则以配置条件。\n * </p>\n *\n * <p>\n * 示例如下，{@code \"abc\"} 表示受保护资源的唯一名称：\n * </p>\n *\n * <pre>\n *  public void foo() {\n *     Entry entry = null;\n *     try {\n *        entry = SphU.entry(\"abc\");\n *        // 需要保护的资源\n *     } catch (BlockException blockException) {\n *         // 进入此处表示被阻断\n *         // 在此添加阻断处理逻辑\n *     } catch (Throwable bizException) {\n *         // 业务异常\n *         Tracer.trace(bizException);\n *     } finally {\n *         // 确保 finally 被执行\n *         if (entry != null){\n *             entry.exit();\n *         }\n *     }\n *  }\n * </pre>\n *\n * <p>\n * 确保 {@code SphU.entry()} 与 {@link Entry#exit()} 在同一线程中配对调用，\n * 否则将抛出 {@link ErrorEntryFreeException}。\n * </p>\n *\n * @author jialiang.linjl\n * @author Eric Zhao\n * @see SphO\n */"),
 ("     * Record statistics and check all rules of the resource that indicates an async invocation.", "     * 对表示异步调用的资源记录统计并检查全部规则。"),
 ("     * Record statistics and perform rule checking for the given resource. The entry is prioritized.", "     * 对给定资源记录统计并执行规则检查，Entry 具有优先级。"),
]
R["Tracer.java"] = [
 ("/**\n * This class is used to record other exceptions except block exception.\n *\n * @author jialiang.linjl\n * @author Eric Zhao\n */", "/**\n * 用于记录除 BlockException 以外的其他异常。\n *\n * @author jialiang.linjl\n * @author Eric Zhao\n */"),
 ("    /**\n     * Trace provided {@link Throwable} to the resource entry in current context.\n     *\n     * @param e exception to record\n     */", "    /**\n     * 将给定 {@link Throwable} 追踪到当前上下文中的资源 Entry。\n     *\n     * @param e 要记录的异常\n     */"),
 ("    /**\n     * Trace provided {@link Throwable} to current entry in current context.\n     *\n     * @param e     exception to record\n     * @param count exception count to add\n     */", "    /**\n     * 将给定 {@link Throwable} 追踪到当前上下文中的当前 Entry。\n     *\n     * @param e     要记录的异常\n     * @param count 要增加的异常计数\n     */"),
 ("    /**\n     * Trace provided {@link Throwable} to current entry of given entrance context.\n     *\n     * @param e     exception to record\n     * @param context target entrance context\n     * @since 1.8.0\n     */", "    /**\n     * 将给定 {@link Throwable} 追踪到指定入口上下文的当前 Entry。\n     *\n     * @param e       要记录的异常\n     * @param context 目标入口上下文\n     * @since 1.8.0\n     */"),
 ("    /**\n     * Trace provided {@link Throwable} and add exception count to current entry in provided context.\n     *\n     * @param e     exception to record\n     * @param count exception count to add\n     * @since 1.4.2\n     */", "    /**\n     * 将给定 {@link Throwable} 追踪到指定上下文中当前 Entry 并增加异常计数。\n     *\n     * @param e     要记录的异常\n     * @param count 要增加的异常计数\n     * @since 1.4.2\n     */"),
 ("    /**\n     * Trace provided {@link Throwable} to the given resource entry.\n     *\n     * @param e exception to record\n     * @since 1.4.2\n     */", "    /**\n     * 将给定 {@link Throwable} 追踪到指定资源 Entry。\n     *\n     * @param e 要记录的异常\n     * @since 1.4.2\n     */"),
 ("    /**\n     * Set exception to trace. If not set, all Exception except for {@link BlockException} will be traced.\n     * <p>\n     * Note that if both {@link #setExceptionsToIgnore(Class[])} and this method is set,\n     * the ExceptionsToIgnore will be of higher precedence.\n     * </p>\n     *\n     * @param traceClasses the list of exception classes to trace.\n     * @since 1.6.1\n     */", "    /**\n     * 设置要追踪的异常。若未设置，除 {@link BlockException} 外的所有 Exception 都会被追踪。\n     * <p>\n     * 注意若同时设置 {@link #setExceptionsToIgnore(Class[])} 与本方法，\n     * ExceptionsToIgnore 优先级更高。\n     * </p>\n     *\n     * @param traceClasses 要追踪的异常类列表\n     * @since 1.6.1\n     */"),
 ("    /**\n     * Get exception classes to trace.\n     *\n     * @return an array of exception classes to trace.\n     * @since 1.6.1\n     */", "    /**\n     * 获取要追踪的异常类。\n     *\n     * @return 要追踪的异常类数组\n     * @since 1.6.1\n     */"),
 ("    /**\n     * Set exceptions to ignore. if not set, all Exception except for {@link BlockException} will be traced.\n     * <p>\n     * Note that if both {@link #setExceptionsToTrace(Class[])} and this method is set,\n     * the ExceptionsToIgnore will be of higher precedence.\n     * </p>\n     *\n     * @param ignoreClasses the list of exception classes to ignore.\n     * @since 1.6.1\n     */", "    /**\n     * 设置要忽略的异常。若未设置，除 {@link BlockException} 外的所有 Exception 都会被追踪。\n     * <p>\n     * 注意若同时设置 {@link #setExceptionsToTrace(Class[])} 与本方法，\n     * ExceptionsToIgnore 优先级更高。\n     * </p>\n     *\n     * @param ignoreClasses 要忽略的异常类列表\n     * @since 1.6.1\n     */"),
 ("    /**\n     * Get exception classes to ignore.\n     *\n     * @return an array of exception classes to ignore.\n     * @since 1.6.1\n     */", "    /**\n     * 获取要忽略的异常类。\n     *\n     * @return 要忽略的异常类数组\n     * @since 1.6.1\n     */"),
 ("    /**\n     * Get exception predicate\n     * @return the exception predicate.\n     */", "    /**\n     * 获取异常谓词。\n     * @return 异常谓词\n     */"),
 ("    /**\n     * set an exception predicate which indicates the exception should be traced(return true) or ignored(return false)\n     * except for {@link BlockException}\n     * @param exceptionPredicate the exception predicate\n     */", "    /**\n     * 设置异常谓词，指示异常应被追踪（返回 true）还是忽略（返回 false），\n     * {@link BlockException} 除外。\n     * @param exceptionPredicate 异常谓词\n     */"),
 ("    /**\n     * Check whether the throwable should be traced.\n     *\n     * @param t the throwable to check.\n     * @return true if the throwable should be traced, else return false.\n     */", "    /**\n     * 检查 Throwable 是否应被追踪。\n     *\n     * @param t 要检查的 Throwable\n     * @return 若应追踪则返回 true，否则返回 false\n     */"),
]
R["SentinelResource.java"] = [
 ("/**\n * The annotation indicates a definition of Sentinel resource.\n *\n * @author Eric Zhao\n * @author zhaoyuguang\n * @since 0.1.1\n */", "/**\n * 表示 Sentinel 资源定义的注解。\n *\n * @author Eric Zhao\n * @author zhaoyuguang\n * @since 0.1.1\n */"),
 ("    /**\n     * @return name of the Sentinel resource\n     */", "    /**\n     * @return Sentinel 资源名称\n     */"),
 ("    /**\n     * @return the entry type (inbound or outbound), outbound by default\n     */", "    /**\n     * @return Entry 类型（入站或出站），默认为出站\n     */"),
 ("    /**\n     * @return the classification (type) of the resource\n     * @since 1.7.0\n     */", "    /**\n     * @return 资源分类（类型）\n     * @since 1.7.0\n     */"),
 ("    /**\n     * @return name of the block exception function, empty by default\n     */", "    /**\n     * @return 阻断异常处理函数名称，默认为空\n     */"),
 ("    /**\n     * The {@code blockHandler} is located in the same class with the original method by default.\n     * However, if some methods share the same signature and intend to set the same block handler,\n     * then users can set the class where the block handler exists. Note that the block handler method\n     * must be static.\n     *\n     * @return the class where the block handler exists, should not provide more than one classes\n     */", "    /**\n     * {@code blockHandler} 默认与原方法位于同一类。\n     * 若多个方法签名相同且共用同一 blockHandler，\n     * 可指定 blockHandler 所在类。注意 blockHandler 方法必须为 static。\n     *\n     * @return blockHandler 所在类，不应提供多个类\n     */"),
 ("    /**\n     * @return name of the fallback function, empty by default\n     */", "    /**\n     * @return 降级函数名称，默认为空\n     */"),
 ("    /**\n     * The {@code defaultFallback} is used as the default universal fallback method.\n     * It should not accept any parameters, and the return type should be compatible\n     * with the original method.\n     *\n     * @return name of the default fallback method, empty by default\n     * @since 1.6.0\n     */", "    /**\n     * {@code defaultFallback} 用作默认通用降级方法。\n     * 不应接受任何参数，返回类型应与原方法兼容。\n     *\n     * @return 默认降级方法名称，默认为空\n     * @since 1.6.0\n     */"),
 ("    /**\n     * The {@code fallback} is located in the same class with the original method by default.\n     * However, if some methods share the same signature and intend to set the same fallback,\n     * then users can set the class where the fallback function exists. Note that the shared fallback method\n     * must be static.\n     *\n     * @return the class where the fallback method is located (only single class)\n     * @since 1.6.0\n     */", "    /**\n     * {@code fallback} 默认与原方法位于同一类。\n     * 若多个方法签名相同且共用同一 fallback，\n     * 可指定 fallback 所在类。注意共用 fallback 方法必须为 static。\n     *\n     * @return fallback 方法所在类（仅单个类）\n     * @since 1.6.0\n     */"),
 ("    /**\n     * @return the list of exception classes to trace, {@link Throwable} by default\n     * @since 1.5.1\n     */", "    /**\n     * @return 要追踪的异常类列表，默认为 {@link Throwable}\n     * @since 1.5.1\n     */"),
 ("    /**\n     * Indicates the exceptions to be ignored. Note that {@code exceptionsToTrace} should\n     * not appear with {@code exceptionsToIgnore} at the same time, or {@code exceptionsToIgnore}\n     * will be of higher precedence.\n     *\n     * @return the list of exception classes to ignore, empty by default\n     * @since 1.6.0\n     */", "    /**\n     * 指定要忽略的异常。注意 {@code exceptionsToTrace} 不应与\n     * {@code exceptionsToIgnore} 同时出现，否则 {@code exceptionsToIgnore} 优先级更高。\n     *\n     * @return 要忽略的异常类列表，默认为空\n     * @since 1.6.0\n     */"),
]
for fn in ("Sph.java","SphU.java","SphO.java","SphResourceTypeSupport.java"):
    R[fn] = R.get(fn,[]) + COMMON

def apply(text, reps):
    for o,n in reps:
        if o in text: text = text.replace(o,n)
    return text

failures=[]; ok=0
for rel in BATCH_FILES:
    dst = ANALYZED / rel
    name = Path(rel).name
    text = dst.read_text(encoding="utf-8")
    if len(re.findall(r"[\u4e00-\u9fff]", text)) >= 10:
        ok+=1; print(f"SKIP {rel}"); continue
    text = apply(text, R.get(name,[]))
    cn = len(re.findall(r"[\u4e00-\u9fff]", text))
    if cn < 10 or "Licensed under the Apache License" not in text:
        failures.append(f"VALIDATION cn={cn}: {rel}"); continue
    dst.write_text(text, encoding="utf-8"); ok+=1; print(f"OK cn={cn} {rel}")
print(json.dumps({"ok":ok,"failures":failures}))
