"""Large-file replacements for Spring Framework 7.0.8 wave-11 batch [0:20]."""

LARGE_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "Retryable.java": [
        (
            "/**\n * A common annotation specifying retry characteristics for an individual method,\n * or for all proxy-invoked methods in a given class hierarchy if annotated at\n * the type level.\n *\n * <p>Aligned with {@link org.springframework.core.retry.RetryTemplate}\n * as well as Reactor's retry support, either re-invoking an imperative\n * target method or decorating a returned reactive publisher accordingly.\n *\n * <p>For tracking the exceptions encountered by method-level retry processing,\n * consider a {@link org.springframework.resilience.retry.MethodRetryEvent} listener.\n *\n * <p>Inspired by the <a href=\"https://github.com/spring-projects/spring-retry\">Spring Retry</a>\n * project but redesigned as a minimal core retry feature in the Spring Framework.\n *\n * @author Juergen Hoeller\n * @author Sam Brannen\n * @since 7.0\n * @see EnableResilientMethods\n * @see RetryAnnotationBeanPostProcessor\n * @see org.springframework.core.retry.RetryPolicy\n * @see org.springframework.core.retry.RetryTemplate\n * @see reactor.core.publisher.Mono#retryWhen\n * @see reactor.core.publisher.Flux#retryWhen\n */",
            "/**\n * 为单个方法指定重试特征的通用注解；\n * 若在类型级别标注，则对给定类层次结构中所有经代理调用的方法生效。\n *\n * <p>与 {@link org.springframework.core.retry.RetryTemplate}\n * 及 Reactor 重试支持对齐，可重新调用命令式目标方法，\n * 或相应地装饰返回的响应式 Publisher。\n *\n * <p>若要跟踪方法级重试处理中遇到的异常，\n * 可考虑 {@link org.springframework.resilience.retry.MethodRetryEvent} 监听器。\n *\n * <p>受 <a href=\"https://github.com/spring-projects/spring-retry\">Spring Retry</a>\n * 项目启发，但在 Spring Framework 中重新设计为最小核心重试特性。\n *\n * @author Juergen Hoeller\n * @author Sam Brannen\n * @since 7.0\n * @see EnableResilientMethods\n * @see RetryAnnotationBeanPostProcessor\n * @see org.springframework.core.retry.RetryPolicy\n * @see org.springframework.core.retry.RetryTemplate\n * @see reactor.core.publisher.Mono#retryWhen\n * @see reactor.core.publisher.Flux#retryWhen\n */",
        ),
        (
            "\t/**\n\t * Convenient default attribute for {@link #includes()},\n\t * typically used with a single exception type to retry for.\n\t */",
            "\t/**\n\t * {@link #includes()} 的便捷默认属性，\n\t * 通常与单个需重试的异常类型配合使用。\n\t */",
        ),
        (
            "\t/**\n\t * Applicable exception types to attempt a retry for. This attribute\n\t * allows for the convenient specification of assignable exception types.\n\t * <p>The supplied exception types will be matched against an exception\n\t * thrown by a failed invocation as well as nested\n\t * {@linkplain Throwable#getCause() causes}.\n\t * <p>This can optionally be combined with {@link #excludes() excludes} or\n\t * a custom {@link #predicate() predicate}.\n\t * <p>The default is empty, leading to a retry attempt for any exception.\n\t * @see #excludes()\n\t * @see #predicate()\n\t */",
            "\t/**\n\t * 应尝试重试的适用异常类型。本属性便于指定可赋值的异常类型。\n\t * <p>所提供的异常类型将与失败调用抛出的异常及嵌套的\n\t * {@linkplain Throwable#getCause() 原因} 进行匹配。\n\t * <p>可与 {@link #excludes() excludes} 或自定义 {@link #predicate() predicate} 组合使用。\n\t * <p>默认为空，表示对任意异常尝试重试。\n\t * @see #excludes()\n\t * @see #predicate()\n\t */",
        ),
        (
            "\t/**\n\t * Non-applicable exception types to avoid a retry for. This attribute\n\t * allows for the convenient specification of assignable exception types.\n\t * <p>The supplied exception types will be matched against an exception\n\t * thrown by a failed invocation as well as nested\n\t * {@linkplain Throwable#getCause() causes}.\n\t * <p>This can optionally be combined with {@link #includes() includes} or\n\t * a custom {@link #predicate() predicate}.\n\t * <p>The default is empty, leading to a retry attempt for any exception.\n\t * @see #includes()\n\t * @see #predicate()\n\t */",
            "\t/**\n\t * 应避免重试的不适用异常类型。本属性便于指定可赋值的异常类型。\n\t * <p>所提供的异常类型将与失败调用抛出的异常及嵌套的\n\t * {@linkplain Throwable#getCause() 原因} 进行匹配。\n\t * <p>可与 {@link #includes() includes} 或自定义 {@link #predicate() predicate} 组合使用。\n\t * <p>默认为空，表示对任意异常尝试重试。\n\t * @see #includes()\n\t * @see #predicate()\n\t */",
        ),
        (
            "\t/**\n\t * A predicate for filtering applicable exceptions for which an invocation can\n\t * be retried.\n\t * <p>A specified {@link MethodRetryPredicate} implementation will be instantiated\n\t * per method. It can use dependency injection at the constructor level or through\n\t * autowiring annotations, in case it needs access to other beans or facilities.\n\t * <p>This can optionally be combined with {@link #includes() includes} or\n\t * {@link #excludes() excludes}.\n\t * <p>The default is a retry attempt for any exception.\n\t * @see #includes()\n\t * @see #excludes()\n\t */",
            "\t/**\n\t * 过滤可重试调用的适用异常的谓词。\n\t * <p>指定的 {@link MethodRetryPredicate} 实现将按方法实例化。\n\t * 若需访问其他 Bean 或设施，可在构造器级别或通过自动装配注解使用依赖注入。\n\t * <p>可与 {@link #includes() includes} 或 {@link #excludes() excludes} 组合使用。\n\t * <p>默认为对任意异常尝试重试。\n\t * @see #includes()\n\t * @see #excludes()\n\t */",
        ),
        (
            "\t/**\n\t * The maximum number of retry attempts.\n\t * <p>Note that {@code total attempts = 1 initial attempt + maxRetries attempts}.\n\t * Thus, if {@code maxRetries} is set to 4, the annotated method will be invoked\n\t * at least once and at most 5 times.\n\t * <p>The default is 3.\n\t */",
            "\t/**\n\t * 最大重试次数。\n\t * <p>注意：{@code 总尝试次数 = 1 次初始尝试 + maxRetries 次重试}。\n\t * 因此若 {@code maxRetries} 设为 4，带注解方法至少调用 1 次、至多 5 次。\n\t * <p>默认为 3。\n\t */",
        ),
        (
            "\t/**\n\t * The maximum number of retry attempts, as a configurable String.\n\t * <p>A non-empty value specified here overrides the {@link #maxRetries()} attribute.\n\t * <p>This supports Spring-style \"${...}\" placeholders as well as SpEL expressions.\n\t * @see #maxRetries()\n\t */",
            "\t/**\n\t * 可配置字符串形式的最大重试次数。\n\t * <p>此处指定非空值将覆盖 {@link #maxRetries()} 属性。\n\t * <p>支持 Spring 风格 \"${...}\" 占位符及 SpEL 表达式。\n\t * @see #maxRetries()\n\t */",
        ),
        (
            "\t/**\n\t * The maximum amount of elapsed time allowed for the initial invocation and\n\t * any subsequent retry attempts, including delays.\n\t * <p>The default is {@code 0}, which signals that no timeout should be applied.\n\t * <p>The time unit is milliseconds by default but can be overridden via\n\t * {@link #timeUnit}.\n\t * <p>Must be greater than or equal to zero.\n\t * @since 7.0.2\n\t */",
            "\t/**\n\t * 初始调用及后续重试（含延迟）允许的最大耗时。\n\t * <p>默认为 {@code 0}，表示不应用超时。\n\t * <p>时间单位默认为毫秒，可通过 {@link #timeUnit} 覆盖。\n\t * <p>必须大于等于零。\n\t * @since 7.0.2\n\t */",
        ),
        (
            "\t/**\n\t * The timeout, as a duration String.\n\t * <p>A non-empty value specified here overrides the {@link #timeout()} attribute.\n\t * <p>The duration String can be in several formats:\n\t * <ul>\n\t * <li>a plain integer &mdash; which is interpreted to represent a duration in\n\t * milliseconds by default unless overridden via {@link #timeUnit()} (prefer\n\t * using {@link #delay()} in that case)</li>\n\t * <li>any of the known {@link org.springframework.format.annotation.DurationFormat.Style\n\t * DurationFormat.Style}: the {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 ISO8601}\n\t * style or the {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE SIMPLE} style\n\t * &mdash; using the {@link #timeUnit()} as fallback if the string doesn't contain an explicit unit</li>\n\t * <li>one of the above, with Spring-style \"${...}\" placeholders as well as SpEL expressions</li>\n\t * </ul>\n\t * @return the timeout as a String value &mdash; for example, a placeholder, a\n\t * {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 java.time.Duration} compliant value,\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE simple format} compliant value\n\t * @since 7.0.2\n\t * @see #timeout()\n\t */",
            "\t/**\n\t * 字符串形式的超时时间。\n\t * <p>此处指定非空值将覆盖 {@link #timeout()} 属性。\n\t * <p>持续时间字符串可为多种形式：\n\t * <ul>\n\t * <li>纯整数 &mdash; 默认解释为毫秒，除非通过 {@link #timeUnit()} 覆盖（此情况建议使用 {@link #delay()}）</li>\n\t * <li>已知 {@link org.springframework.format.annotation.DurationFormat.Style\n\t * DurationFormat.Style} 之一：{@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 ISO8601}\n\t * 或 {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE SIMPLE} 风格\n\t * &mdash; 若字符串未含显式单位则回退使用 {@link #timeUnit()}</li>\n\t * <li>上述任一种，并支持 Spring 风格 \"${...}\" 占位符及 SpEL 表达式</li>\n\t * </ul>\n\t * @return 字符串形式的超时值 &mdash; 例如占位符、\n\t * 符合 {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 java.time.Duration} 的值，\n\t * 或符合 {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE 简单格式} 的值\n\t * @since 7.0.2\n\t * @see #timeout()\n\t */",
        ),
        (
            "\t/**\n\t * The base delay after the initial invocation. If a multiplier is specified,\n\t * this serves as the initial delay to multiply from.\n\t * <p>The time unit is milliseconds by default but can be overridden via\n\t * {@link #timeUnit}.\n\t * <p>Must be greater than or equal to zero. The default is 1000.\n\t * @see #jitter()\n\t * @see #multiplier()\n\t * @see #maxDelay()\n\t */",
            "\t/**\n\t * 初始调用后的基础延迟。若指定乘数，则作为乘法的初始延迟。\n\t * <p>时间单位默认为毫秒，可通过 {@link #timeUnit} 覆盖。\n\t * <p>必须大于等于零。默认为 1000。\n\t * @see #jitter()\n\t * @see #multiplier()\n\t * @see #maxDelay()\n\t */",
        ),
        (
            "\t/**\n\t * The base delay after the initial invocation, as a duration String.\n\t * <p>A non-empty value specified here overrides the {@link #delay()} attribute.\n\t * <p>The duration String can be in several formats:\n\t * <ul>\n\t * <li>a plain integer &mdash; which is interpreted to represent a duration in\n\t * milliseconds by default unless overridden via {@link #timeUnit()} (prefer\n\t * using {@link #delay()} in that case)</li>\n\t * <li>any of the known {@link org.springframework.format.annotation.DurationFormat.Style\n\t * DurationFormat.Style}: the {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 ISO8601}\n\t * style or the {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE SIMPLE} style\n\t * &mdash; using the {@link #timeUnit()} as fallback if the string doesn't contain an explicit unit</li>\n\t * <li>one of the above, with Spring-style \"${...}\" placeholders as well as SpEL expressions</li>\n\t * </ul>\n\t * @return the initial delay as a String value &mdash; for example a placeholder,\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 java.time.Duration} compliant value\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE simple format} compliant value\n\t * @see #delay()\n\t */",
            "\t/**\n\t * 字符串形式的初始调用后基础延迟。\n\t * <p>此处指定非空值将覆盖 {@link #delay()} 属性。\n\t * <p>持续时间字符串格式参见 {@link #timeoutString()}。\n\t * @return 字符串形式的初始延迟 &mdash; 例如占位符，\n\t * 或符合 {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 java.time.Duration} 的值\n\t * 或符合 {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE 简单格式} 的值\n\t * @see #delay()\n\t */",
        ),
        (
            "\t/**\n\t * A jitter value for the base retry attempt, randomly subtracted or added to\n\t * the calculated delay, resulting in a value between {@code delay - jitter}\n\t * and {@code delay + jitter} but never below the base {@link #delay()} or\n\t * above {@link #maxDelay()}. If a multiplier is specified, it is applied\n\t * to the jitter value as well.\n\t * <p>The time unit is milliseconds by default but can be overridden via\n\t * {@link #timeUnit}.\n\t * <p>The default is 0 (no jitter).\n\t * @see #delay()\n\t * @see #multiplier()\n\t * @see #maxDelay()\n\t */",
            "\t/**\n\t * 基础重试尝试的抖动值，随机加减于计算延迟，\n\t * 结果介于 {@code delay - jitter} 与 {@code delay + jitter} 之间，\n\t * 但不低于基础 {@link #delay()} 或高于 {@link #maxDelay()}。\n\t * 若指定乘数，亦应用于抖动值。\n\t * <p>时间单位默认为毫秒，可通过 {@link #timeUnit} 覆盖。\n\t * <p>默认为 0（无抖动）。\n\t * @see #delay()\n\t * @see #multiplier()\n\t * @see #maxDelay()\n\t */",
        ),
        (
            "\t/**\n\t * A jitter value for the base retry attempt, as a duration String.\n\t * <p>A non-empty value specified here overrides the {@link #jitter()} attribute.\n\t * <p>The duration String can be in several formats:\n\t * <ul>\n\t * <li>a plain integer &mdash; which is interpreted to represent a duration in\n\t * milliseconds by default unless overridden via {@link #timeUnit()} (prefer\n\t * using {@link #jitter()} in that case)</li>\n\t * <li>any of the known {@link org.springframework.format.annotation.DurationFormat.Style\n\t * DurationFormat.Style}: the {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 ISO8601}\n\t * style or the {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE SIMPLE} style\n\t * &mdash; using the {@link #timeUnit()} as fallback if the string doesn't contain an explicit unit</li>\n\t * <li>one of the above, with Spring-style \"${...}\" placeholders as well as SpEL expressions</li>\n\t * </ul>\n\t * @return the initial delay as a String value &mdash; for example a placeholder,\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 java.time.Duration} compliant value\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE simple format} compliant value\n\t * @see #jitter()\n\t */",
            "\t/**\n\t * 字符串形式的基础重试抖动值。\n\t * <p>此处指定非空值将覆盖 {@link #jitter()} 属性。\n\t * <p>持续时间字符串格式参见 {@link #timeoutString()}。\n\t * @return 字符串形式的抖动值\n\t * @see #jitter()\n\t */",
        ),
        (
            "\t/**\n\t * A multiplier for a delay for the next retry attempt, applied\n\t * to the previous delay (starting with {@link #delay()}) as well\n\t * as to the applicable {@link #jitter()} for each attempt.\n\t * <p>The default is 1.0, effectively resulting in a fixed delay.\n\t * @see #delay()\n\t * @see #jitter()\n\t * @see #maxDelay()\n\t */",
            "\t/**\n\t * 下次重试延迟的乘数，应用于前次延迟（从 {@link #delay()} 开始）\n\t * 以及每次尝试适用的 {@link #jitter()}。\n\t * <p>默认为 1.0，即固定延迟。\n\t * @see #delay()\n\t * @see #jitter()\n\t * @see #maxDelay()\n\t */",
        ),
        (
            "\t/**\n\t * A multiplier for a delay for the next retry attempt, as a configurable String.\n\t * <p>A non-empty value specified here overrides the {@link #multiplier()} attribute.\n\t * <p>This supports Spring-style \"${...}\" placeholders as well as SpEL expressions.\n\t * @see #multiplier()\n\t */",
            "\t/**\n\t * 可配置字符串形式的下次重试延迟乘数。\n\t * <p>此处指定非空值将覆盖 {@link #multiplier()} 属性。\n\t * <p>支持 Spring 风格 \"${...}\" 占位符及 SpEL 表达式。\n\t * @see #multiplier()\n\t */",
        ),
        (
            "\t/**\n\t * The maximum delay for any retry attempt, limiting how far {@link #jitter()}\n\t * and {@link #multiplier()} can increase the {@linkplain #delay() delay}.\n\t * <p>The time unit is milliseconds by default but can be overridden via\n\t * {@link #timeUnit}.\n\t * <p>The default is unlimited.\n\t * @see #delay()\n\t * @see #jitter()\n\t * @see #multiplier()\n\t */",
            "\t/**\n\t * 任意重试尝试的最大延迟，限制 {@link #jitter()} 与 {@link #multiplier()}\n\t * 可将 {@linkplain #delay() 延迟} 增大的幅度。\n\t * <p>时间单位默认为毫秒，可通过 {@link #timeUnit} 覆盖。\n\t * <p>默认为无限制。\n\t * @see #delay()\n\t * @see #jitter()\n\t * @see #multiplier()\n\t */",
        ),
        (
            "\t/**\n\t * The maximum delay for any retry attempt, as a duration String.\n\t * <p>A non-empty value specified here overrides the {@link #maxDelay()} attribute.\n\t * <p>The duration String can be in several formats:\n\t * <ul>\n\t * <li>a plain integer &mdash; which is interpreted to represent a duration in\n\t * milliseconds by default unless overridden via {@link #timeUnit()} (prefer\n\t * using {@link #maxDelay()} in that case)</li>\n\t * <li>any of the known {@link org.springframework.format.annotation.DurationFormat.Style\n\t * DurationFormat.Style}: the {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 ISO8601}\n\t * style or the {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE SIMPLE} style\n\t * &mdash; using the {@link #timeUnit()} as fallback if the string doesn't contain an explicit unit</li>\n\t * <li>one of the above, with Spring-style \"${...}\" placeholders as well as SpEL expressions</li>\n\t * </ul>\n\t * @return the initial delay as a String value &mdash; for example a placeholder,\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#ISO8601 java.time.Duration} compliant value\n\t * or a {@link org.springframework.format.annotation.DurationFormat.Style#SIMPLE simple format} compliant value\n\t * @see #maxDelay()\n\t */",
            "\t/**\n\t * 字符串形式的任意重试最大延迟。\n\t * <p>此处指定非空值将覆盖 {@link #maxDelay()} 属性。\n\t * <p>持续时间字符串格式参见 {@link #timeoutString()}。\n\t * @return 字符串形式的最大延迟值\n\t * @see #maxDelay()\n\t */",
        ),
        (
            "\t/**\n\t * The {@link TimeUnit} to use for {@link #delay}, {@link #delayString},\n\t * {@link #jitter}, {@link #jitterString}, {@link #maxDelay}, and\n\t * {@link #maxDelayString}.\n\t * <p>The default is {@link TimeUnit#MILLISECONDS}.\n\t * <p>This attribute is ignored for {@link java.time.Duration} values supplied\n\t * via {@link #delayString}, {@link #jitterString}, or {@link #maxDelayString}.\n\t * @return the {@code TimeUnit} to use\n\t */",
            "\t/**\n\t * 用于 {@link #delay}、{@link #delayString}、{@link #jitter}、{@link #jitterString}、\n\t * {@link #maxDelay} 与 {@link #maxDelayString} 的 {@link TimeUnit}。\n\t * <p>默认为 {@link TimeUnit#MILLISECONDS}。\n\t * <p>通过 {@link #delayString}、{@link #jitterString} 或 {@link #maxDelayString}\n\t * 提供的 {@link java.time.Duration} 值将忽略本属性。\n\t * @return 要使用的 {@code TimeUnit}\n\t */",
        ),
    ],
    "AbstractRetryInterceptor.java": [
        (
            "/**\n * Abstract retry interceptor implementation, adapting a given\n * retry specification to either {@link RetryTemplate} or Reactor.\n *\n * @author Juergen Hoeller\n * @since 7.0\n * @see #getRetrySpec\n * @see RetryTemplate\n * @see Mono#retryWhen\n * @see Flux#retryWhen\n */",
            "/**\n * 抽象重试拦截器实现，将给定的重试规范适配为 {@link RetryTemplate} 或 Reactor。\n *\n * @author Juergen Hoeller\n * @since 7.0\n * @see #getRetrySpec\n * @see RetryTemplate\n * @see Mono#retryWhen\n * @see Flux#retryWhen\n */",
        ),
        (
            "\t/**\n\t * Reactive Streams API present on the classpath?\n\t */",
            "\t/**\n\t * 类路径上是否存在 Reactive Streams API？\n\t */",
        ),
        (
            "\t/**\n\t * Determine the retry specification for the given method on the given target.\n\t * @param method the currently executing method\n\t * @param targetClass the class of the current target object\n\t * @return the retry specification as a {@link MethodRetrySpec}\n\t */",
            "\t/**\n\t * 确定给定目标上给定方法的重试规范。\n\t * @param method 当前执行的方法\n\t * @param targetClass 当前目标对象的类\n\t * @return 以 {@link MethodRetrySpec} 表示的重试规范\n\t */",
        ),
        (
            "\t/**\n\t * Inner class to avoid a hard dependency on Reactive Streams and Reactor at runtime.\n\t */",
            "\t/**\n\t * 内部类，避免在运行时硬依赖 Reactive Streams 与 Reactor。\n\t */",
        ),
    ],
    "MethodRetryEvent.java": [
        (
            "/**\n * Event published for every exception encountered during retryable method invocation.\n * Can be listened to via an {@code ApplicationListener<MethodRetryEvent>} bean or an\n * {@code @EventListener(MethodRetryEvent.class)} method.\n *\n * @author Juergen Hoeller\n * @since 7.0.3\n * @see AbstractRetryInterceptor\n * @see org.springframework.resilience.annotation.Retryable\n * @see org.springframework.context.ApplicationListener\n * @see org.springframework.context.event.EventListener\n */",
            "/**\n * 可重试方法调用过程中遇到的每个异常都会发布此事件。\n * 可通过 {@code ApplicationListener<MethodRetryEvent>} Bean 或\n * {@code @EventListener(MethodRetryEvent.class)} 方法监听。\n *\n * @author Juergen Hoeller\n * @since 7.0.3\n * @see AbstractRetryInterceptor\n * @see org.springframework.resilience.annotation.Retryable\n * @see org.springframework.context.ApplicationListener\n * @see org.springframework.context.event.EventListener\n */",
        ),
        (
            "\t/**\n\t * Create a new event for the given retryable method invocation.\n\t * @param invocation the retryable method invocation\n\t * @param failure the exception encountered\n\t * @param retryAborted whether the current failure led to the retry execution getting aborted\n\t */",
            "\t/**\n\t * 为给定可重试方法调用创建新事件。\n\t * @param invocation 可重试方法调用\n\t * @param failure 遇到的异常\n\t * @param retryAborted 当前失败是否导致重试执行中止\n\t */",
        ),
        (
            "\t/**\n\t * Return the exception encountered.\n\t * <p>This may be an exception thrown by the method or emitted by the reactive\n\t * publisher returned from the method, or a terminal exception on retry\n\t * exhaustion, interruption or timeout.\n\t * <p>For {@link org.springframework.core.retry.RetryTemplate} executions,\n\t * an {@code instanceof RetryException} check identifies a final exception.\n\t * For Reactor pipelines, {@code Exceptions.isRetryExhausted} identifies an\n\t * exhaustion exception, whereas {@code instanceof TimeoutException} reveals\n\t * a timeout scenario.\n\t * @see #isRetryAborted()\n\t * @see org.springframework.core.retry.RetryException\n\t * @see reactor.core.Exceptions#isRetryExhausted\n\t * @see java.util.concurrent.TimeoutException\n\t */",
            "\t/**\n\t * 返回遇到的异常。\n\t * <p>可能是方法抛出的异常、方法返回的响应式 Publisher 发出的异常，\n\t * 或重试用尽、中断或超时时的终止异常。\n\t * <p>对于 {@link org.springframework.core.retry.RetryTemplate} 执行，\n\t * {@code instanceof RetryException} 检查可识别最终异常。\n\t * 对于 Reactor 管道，{@code Exceptions.isRetryExhausted} 识别用尽异常，\n\t * 而 {@code instanceof TimeoutException} 表示超时场景。\n\t * @see #isRetryAborted()\n\t * @see org.springframework.core.retry.RetryException\n\t * @see reactor.core.Exceptions#isRetryExhausted\n\t * @see java.util.concurrent.TimeoutException\n\t */",
        ),
        (
            "\t/**\n\t * Return whether the current failure led to the retry execution getting aborted,\n\t * typically indicating exhaustion, interruption or a timeout scenario.\n\t * <p>If this returns {@code true}, {@link #getFailure()} exposes the final exception\n\t * thrown by the retry infrastructure (rather than thrown by the method itself).\n\t * @see #getFailure()\n\t */",
            "\t/**\n\t * 返回当前失败是否导致重试执行中止，\n\t * 通常表示用尽、中断或超时场景。\n\t * <p>若返回 {@code true}，{@link #getFailure()} 暴露的是重试基础设施抛出的最终异常\n\t *（而非方法本身抛出）。\n\t * @see #getFailure()\n\t */",
        ),
    ],
    "TaskScheduler.java": [
        (
            "/**\n * Task scheduler interface that abstracts the scheduling of\n * {@link Runnable Runnables} based on different kinds of triggers.\n *\n * <p>This interface is separate from {@link SchedulingTaskExecutor} since it\n * usually represents a different kind of backend, i.e. a thread pool with\n * different characteristics and capabilities. Implementations may implement\n * both interfaces if they can handle both kinds of execution characteristics.\n *\n * <p>The 'default' implementation is\n * {@link org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler},\n * wrapping a native {@link java.util.concurrent.ScheduledExecutorService}\n * and adding extended trigger capabilities.\n *\n * <p>This interface is roughly equivalent to a JSR-236\n * {@code ManagedScheduledExecutorService} as supported in Jakarta EE\n * environments but aligned with Spring's {@code TaskExecutor} model.\n *\n * @author Juergen Hoeller\n * @since 3.0\n * @see org.springframework.core.task.TaskExecutor\n * @see java.util.concurrent.ScheduledExecutorService\n * @see org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler\n */",
            "/**\n * 基于不同触发器调度 {@link Runnable Runnables} 的任务调度器接口。\n *\n * <p>本接口与 {@link SchedulingTaskExecutor} 分离，因为通常代表不同后端，\n * 即具有不同特征与能力的线程池。若实现可处理两类执行特征，可同时实现两个接口。\n *\n * <p>\"默认\" 实现为\n * {@link org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler}，\n * 包装原生 {@link java.util.concurrent.ScheduledExecutorService}\n * 并添加扩展触发器能力。\n *\n * <p>本接口大致等价于 Jakarta EE 环境中支持的 JSR-236\n * {@code ManagedScheduledExecutorService}，但与 Spring {@code TaskExecutor} 模型对齐。\n *\n * @author Juergen Hoeller\n * @since 3.0\n * @see org.springframework.core.task.TaskExecutor\n * @see java.util.concurrent.ScheduledExecutorService\n * @see org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler\n */",
        ),
        (
            "\t/**\n\t * Return the clock to use for scheduling purposes.\n\t * @since 5.3\n\t * @see Clock#systemDefaultZone()\n\t */",
            "\t/**\n\t * 返回用于调度目的的时钟。\n\t * @since 5.3\n\t * @see Clock#systemDefaultZone()\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it whenever the trigger\n\t * indicates a next execution time.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param trigger an implementation of the {@link Trigger} interface,\n\t * for example, a {@link org.springframework.scheduling.support.CronTrigger} object\n\t * wrapping a cron expression\n\t * @return a {@link ScheduledFuture} representing pending execution of the task,\n\t * or {@code null} if the given Trigger object never fires (i.e. returns\n\t * {@code null} from {@link Trigger#nextExecution})\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @see org.springframework.scheduling.support.CronTrigger\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在触发器指示下次执行时间时调用。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 触发器触发时要执行的 Runnable\n\t * @param trigger {@link Trigger} 接口的实现，\n\t * 例如包装 cron 表达式的 {@link org.springframework.scheduling.support.CronTrigger} 对象\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}，\n\t * 若给定 Trigger 不再触发（即从 {@link Trigger#nextExecution} 返回 {@code null}）则返回 {@code null}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因（如池过载策略或池正在关闭）未接受任务时\n\t * @see org.springframework.scheduling.support.CronTrigger\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it at the specified execution time.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param startTime the desired execution time for the task\n\t * (if this is in the past, the task will be executed immediately, i.e. as soon as possible)\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @since 5.0\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在指定执行时间调用。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param startTime 任务期望执行时间\n\t *（若已过期，任务将立即执行，即尽快执行）\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @since 5.0\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it at the specified execution time.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param startTime the desired execution time for the task\n\t * (if this is in the past, the task will be executed immediately, i.e. as soon as possible)\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @deprecated as of 6.0, in favor of {@link #schedule(Runnable, Instant)}\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在指定执行时间调用。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param startTime 任务期望执行时间\n\t *（若已过期，任务将立即执行）\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @deprecated 自 6.0 起，请改用 {@link #schedule(Runnable, Instant)}\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it at the specified execution time\n\t * and subsequently with the given period.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param startTime the desired first execution time for the task\n\t * (if this is in the past, the task will be executed immediately, i.e. as soon as possible)\n\t * @param period the interval between successive executions of the task\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if  the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @since 5.0\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在指定执行时间首次调用，随后按给定周期重复。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param startTime 任务期望首次执行时间\n\t *（若已过期，任务将立即执行）\n\t * @param period 连续执行之间的间隔\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @since 5.0\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it at the specified execution time\n\t * and subsequently with the given period.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param startTime the desired first execution time for the task\n\t * (if this is in the past, the task will be executed immediately, i.e. as soon as possible)\n\t * @param period the interval between successive executions of the task (in milliseconds)\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if  the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @deprecated as of 6.0, in favor of {@link #scheduleAtFixedRate(Runnable, Instant, Duration)}\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在指定执行时间首次调用，随后按给定周期（毫秒）重复。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param startTime 任务期望首次执行时间\n\t * @param period 连续执行之间的间隔（毫秒）\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @deprecated 自 6.0 起，请改用 {@link #scheduleAtFixedRate(Runnable, Instant, Duration)}\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, starting as soon as possible and\n\t * invoking it with the given period.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param period the interval between successive executions of the task\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @since 5.0\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，尽快启动并按给定周期重复调用。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param period 连续执行之间的间隔\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @since 5.0\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, starting as soon as possible and\n\t * invoking it with the given period.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param period the interval between successive executions of the task (in milliseconds)\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @deprecated as of 6.0, in favor of {@link #scheduleAtFixedRate(Runnable, Duration)}\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，尽快启动并按给定周期（毫秒）重复调用。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param period 连续执行之间的间隔（毫秒）\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @deprecated 自 6.0 起，请改用 {@link #scheduleAtFixedRate(Runnable, Duration)}\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it at the specified execution time\n\t * and subsequently with the given delay between the completion of one execution\n\t * and the start of the next.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param startTime the desired first execution time for the task\n\t * (if this is in the past, the task will be executed immediately, i.e. as soon as possible)\n\t * @param delay the delay between the completion of one execution and the start of the next\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @since 5.0\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在指定时间首次执行，\n\t * 随后在前次执行完成与下次开始之间保持给定延迟。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param startTime 任务期望首次执行时间\n\t * @param delay 前次执行完成与下次开始之间的延迟\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @since 5.0\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, invoking it at the specified execution time\n\t * and subsequently with the given delay between the completion of one execution\n\t * and the start of the next.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param startTime the desired first execution time for the task\n\t * (if this is in the past, the task will be executed immediately, i.e. as soon as possible)\n\t * @param delay the delay between the completion of one execution and the start of the next\n\t * (in milliseconds)\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @deprecated as of 6.0, in favor of {@link #scheduleWithFixedDelay(Runnable, Instant, Duration)}\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，在指定时间首次执行，\n\t * 随后在前次执行完成与下次开始之间保持给定延迟（毫秒）。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param startTime 任务期望首次执行时间\n\t * @param delay 前次执行完成与下次开始之间的延迟（毫秒）\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @deprecated 自 6.0 起，请改用 {@link #scheduleWithFixedDelay(Runnable, Instant, Duration)}\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, starting as soon as possible and invoking it with\n\t * the given delay between the completion of one execution and the start of the next.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param delay the delay between the completion of one execution and the start of the next\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @since 5.0\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，尽快启动，\n\t * 并在前次执行完成与下次开始之间保持给定延迟。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param delay 前次执行完成与下次开始之间的延迟\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @since 5.0\n\t */",
        ),
        (
            "\t/**\n\t * Schedule the given {@link Runnable}, starting as soon as possible and invoking it with\n\t * the given delay between the completion of one execution and the start of the next.\n\t * <p>Execution will end once the scheduler shuts down or the returned\n\t * {@link ScheduledFuture} gets cancelled.\n\t * @param task the Runnable to execute whenever the trigger fires\n\t * @param delay the delay between the completion of one execution and the start of the next\n\t * (in milliseconds)\n\t * @return a {@link ScheduledFuture} representing pending execution of the task\n\t * @throws org.springframework.core.task.TaskRejectedException if the given task was not accepted\n\t * for internal reasons (for example, a pool overload handling policy or a pool shutdown in progress)\n\t * @deprecated as of 6.0, in favor of {@link #scheduleWithFixedDelay(Runnable, Duration)}\n\t */",
            "\t/**\n\t * 调度给定 {@link Runnable}，尽快启动，\n\t * 并在前次执行完成与下次开始之间保持给定延迟（毫秒）。\n\t * <p>调度器关闭或返回的 {@link ScheduledFuture} 被取消后，执行将结束。\n\t * @param task 要执行的 Runnable\n\t * @param delay 前次执行完成与下次开始之间的延迟（毫秒）\n\t * @return 表示任务待执行状态的 {@link ScheduledFuture}\n\t * @throws org.springframework.core.task.TaskRejectedException 因内部原因未接受任务时\n\t * @deprecated 自 6.0 起，请改用 {@link #scheduleWithFixedDelay(Runnable, Duration)}\n\t */",
        ),
    ],
    "TriggerContext.java": [
        (
            "/**\n * Context object encapsulating last execution times and last completion time\n * of a given task.\n *\n * @author Juergen Hoeller\n * @author Arjen Poutsma\n * @since 3.0\n */",
            "/**\n * 封装给定任务上次执行时间与上次完成时间的上下文对象。\n *\n * @author Juergen Hoeller\n * @author Arjen Poutsma\n * @since 3.0\n */",
        ),
        (
            "\t/**\n\t * Return the clock to use for trigger calculation.\n\t * <p>Defaults to {@link Clock#systemDefaultZone()}.\n\t * @since 5.3\n\t * @see TaskScheduler#getClock()\n\t */",
            "\t/**\n\t * 返回用于触发器计算的时钟。\n\t * <p>默认为 {@link Clock#systemDefaultZone()}。\n\t * @since 5.3\n\t * @see TaskScheduler#getClock()\n\t */",
        ),
        (
            "\t/**\n\t * Return the last <i>scheduled</i> execution time of the task,\n\t * or {@code null} if not scheduled before.\n\t * <p>The default implementation delegates to {@link #lastScheduledExecution()}.\n\t * @deprecated as of 6.0, in favor on {@link #lastScheduledExecution()}\n\t */",
            "\t/**\n\t * 返回任务上次<i>计划</i>执行时间，\n\t * 若此前未调度则返回 {@code null}。\n\t * <p>默认实现委托给 {@link #lastScheduledExecution()}。\n\t * @deprecated 自 6.0 起，请改用 {@link #lastScheduledExecution()}\n\t */",
        ),
        (
            "\t/**\n\t * Return the last <i>scheduled</i> execution time of the task,\n\t * or {@code null} if not scheduled before.\n\t * @since 6.0\n\t */",
            "\t/**\n\t * 返回任务上次<i>计划</i>执行时间，\n\t * 若此前未调度则返回 {@code null}。\n\t * @since 6.0\n\t */",
        ),
        (
            "\t/**\n\t * Return the last <i>actual</i> execution time of the task,\n\t * or {@code null} if not scheduled before.\n\t * <p>The default implementation delegates to {@link #lastActualExecution()}.\n\t * @deprecated as of 6.0, in favor on {@link #lastActualExecution()}\n\t */",
            "\t/**\n\t * 返回任务上次<i>实际</i>执行时间，\n\t * 若此前未调度则返回 {@code null}。\n\t * <p>默认实现委托给 {@link #lastActualExecution()}。\n\t * @deprecated 自 6.0 起，请改用 {@link #lastActualExecution()}\n\t */",
        ),
        (
            "\t/**\n\t * Return the last <i>actual</i> execution time of the task,\n\t * or {@code null} if not scheduled before.\n\t * @since 6.0\n\t */",
            "\t/**\n\t * 返回任务上次<i>实际</i>执行时间，\n\t * 若此前未调度则返回 {@code null}。\n\t * @since 6.0\n\t */",
        ),
        (
            "\t/**\n\t * Return the last completion time of the task,\n\t * or {@code null} if not scheduled before.\n\t * <p>The default implementation delegates to {@link #lastCompletion()}.\n\t * @deprecated as of 6.0, in favor on {@link #lastCompletion()}\n\t */",
            "\t/**\n\t * 返回任务上次完成时间，\n\t * 若此前未调度则返回 {@code null}。\n\t * <p>默认实现委托给 {@link #lastCompletion()}。\n\t * @deprecated 自 6.0 起，请改用 {@link #lastCompletion()}\n\t */",
        ),
        (
            "\t/**\n\t * Return the last completion time of the task,\n\t * or {@code null} if not scheduled before.\n\t * @since 6.0\n\t */",
            "\t/**\n\t * 返回任务上次完成时间，\n\t * 若此前未调度则返回 {@code null}。\n\t * @since 6.0\n\t */",
        ),
    ],
}
