#!/usr/bin/env python3
"""Chinese-annotate Spring Boot 4.1.0 wave-12b batch files [20:40] (logback/structured)."""
from __future__ import annotations
import json, re, shutil, subprocess, sys
from pathlib import Path
ROOT = Path("/workspace")
VER = ROOT / "springboot/4.1.0"
ORIGINAL, ANALYZED, QUEUE = VER / "original", VER / "analyzed", VER / "_reports/class-queue"
BATCH_FILES = Path("/tmp/springboot_w12b.txt").read_text(encoding="utf-8").strip().splitlines()
FILE_REPLACEMENTS = {
"SpringProfileAction.java": [("/**\n * Logback {@link BaseModelAction} for {@code <springProfile>} tags. Allows a section of a\n * Logback configuration to only be enabled when a specific profile is active.\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Andy Wilkinson\n * @see SpringProfileModel\n * @see SpringProfileModelHandler\n */", "/**\n * 用于 {@code <springProfile>} 标签的 Logback {@link BaseModelAction}。\n * 允许 Logback 配置的某一段仅在指定 profile 激活时启用。\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Andy Wilkinson\n * @see SpringProfileModel\n * @see SpringProfileModelHandler\n */")],
"SpringProfileIfNestedWithinSecondPhaseElementSanityChecker.java": [("/**\n * {@link SanityChecker} to ensure that {@code springProfile} elements are not nested\n * within second-phase elements.\n *\n * @author Phillip Webb\n * @see IfNestedWithinSecondPhaseElementSC\n */", "/**\n * {@link SanityChecker}，确保 {@code springProfile} 元素不会嵌套在\n * 第二阶段（second-phase）元素内部。\n * 若嵌套在 {@code <appender>}、{@code <logger>} 或 {@code <root>} 内则发出警告。\n *\n * @author Phillip Webb\n * @see IfNestedWithinSecondPhaseElementSC\n */")],
"SpringProfileModel.java": [("/**\n * Logback {@link NamedModel model} to support {@code <springProfile>} tags.\n *\n * @author Andy Wilkinson\n * @see SpringProfileAction\n * @see SpringProfileModelHandler\n */", "/**\n * 支持 {@code <springProfile>} 标签的 Logback {@link NamedModel model}。\n * 由 {@link SpringProfileAction} 创建，由 {@link SpringProfileModelHandler} 处理。\n * {@code name} 属性指定逗号分隔的 Spring profile 名称列表。\n *\n * @author Andy Wilkinson\n * @see SpringProfileAction\n * @see SpringProfileModelHandler\n */")],
"SpringProfileModelHandler.java": [("/**\n * Logback {@link ModelHandlerBase model handler} to support {@code <springProfile>} tags.\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Andy Wilkinson\n * @see SpringProfileModel\n * @see SpringProfileAction\n */", "/**\n * 支持 {@code <springProfile>} 标签的 Logback {@link ModelHandlerBase model handler}。\n * 根据 Spring {@link Environment} 中的 profile 决定是否跳过该配置段。\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Andy Wilkinson\n * @see SpringProfileModel\n * @see SpringProfileAction\n */")],
"SpringPropertyAction.java": [("/**\n * Logback {@link BaseModelAction} for {@code <springProperty>} tags. Allows Logback\n * properties to be sourced from the Spring environment.\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Madhura Bhave\n * @author Andy Wilkinson\n * @see SpringPropertyModel\n * @see SpringPropertyModelHandler\n */", "/**\n * 用于 {@code <springProperty>} 标签的 Logback {@link BaseModelAction}。\n * 允许 Logback 属性从 Spring 环境中获取。\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Madhura Bhave\n * @author Andy Wilkinson\n * @see SpringPropertyModel\n * @see SpringPropertyModelHandler\n */")],
"SpringPropertyModel.java": [("/**\n * Logback {@link NamedModel model} to support {@code <springProperty>} tags. Allows\n * Logback properties to be sourced from the Spring environment.\n *\n * @author Andy Wilkinson\n * @see SpringPropertyAction\n * @see SpringPropertyModelHandler\n */", "/**\n * 支持 {@code <springProperty>} 标签的 Logback {@link NamedModel model}。\n * 允许 Logback 属性从 Spring 环境中获取。\n * 包含 {@code source}、{@code scope} 与 {@code defaultValue} 属性。\n *\n * @author Andy Wilkinson\n * @see SpringPropertyAction\n * @see SpringPropertyModelHandler\n */")],
"SpringPropertyModelHandler.java": [("/**\n * Logback {@link ModelHandlerBase model handler} to support {@code <springProperty>}\n * tags. Allows Logback properties to be sourced from the Spring environment.\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Madhura Bhave\n * @author Andy Wilkinson\n * @see SpringPropertyAction\n * @see SpringPropertyModel\n */", "/**\n * 支持 {@code <springProperty>} 标签的 Logback {@link ModelHandlerBase model handler}。\n * 从 Spring {@link Environment} 解析属性值并写入 Logback 上下文。\n *\n * @author Phillip Webb\n * @author Eddú Meléndez\n * @author Madhura Bhave\n * @author Andy Wilkinson\n * @see SpringPropertyAction\n * @see SpringPropertyModel\n */")],
"StructuredLogEncoder.java": [("/**\n * {@link Encoder Logback encoder} for structured logging.\n *\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n * @see StructuredLogFormatter\n */", "/**\n * 用于结构化日志的 {@link Encoder Logback encoder}。\n * 通过 {@link StructuredLogFormatterFactory} 创建 ECS、GELF 或 Logstash 格式化器。\n *\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n * @see StructuredLogFormatter\n */")],
"SystemStatusListener.java": [("/**\n * {@link StatusListener} used to print appropriate status messages to {@link System#out}\n * or {@link System#err}. Note that this class extends {@link OnConsoleStatusListener} so\n * that {@link BasicStatusManager#add(StatusListener)} does not add the same listener\n * twice. It also implements a version of retrospectivePrint that can filter status\n * messages by level.\n *\n * @author Dmytro Nosan\n * @author Phillip Webb\n */", "/**\n * 用于将适当的状态消息打印到 {@link System#out} 或 {@link System#err} 的\n * {@link StatusListener}。\n * 继承 {@link OnConsoleStatusListener}，避免 {@link BasicStatusManager#add(StatusListener)}\n * 重复添加同一监听器；并实现可按级别过滤的 retrospectivePrint。\n * 非 debug 模式下仅输出 WARN 及以上级别到 {@link System#err}。\n *\n * @author Dmytro Nosan\n * @author Phillip Webb\n */")],
"WhitespaceThrowableProxyConverter.java": [("/**\n * {@link ThrowableProxyConverter} that adds some additional whitespace around the stack\n * trace.\n *\n * @author Phillip Webb\n * @since 1.0.0\n */", "/**\n * 在堆栈跟踪周围添加额外空白字符的 {@link ThrowableProxyConverter}。\n *\n * @author Phillip Webb\n * @since 1.0.0\n */")],
"CommonStructuredLogFormat.java": [("/**\n * Common structured log formats supported by Spring Boot.\n *\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n */", "/**\n * Spring Boot 支持的常见结构化日志格式。\n *\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n */"), ("\t/**\n\t * <a href=\"https://www.elastic.co/guide/en/ecs/current/ecs-log.html\">Elastic Common\n\t * Schema</a> (ECS) log format.\n\t */", "\t/**\n\t * <a href=\"https://www.elastic.co/guide/en/ecs/current/ecs-log.html\">Elastic Common\n\t * Schema</a>（ECS）日志格式。\n\t */"), ("\t/**\n\t * <a href=\"https://go2docs.graylog.org/current/getting_in_log_data/gelf.html\">Graylog\n\t * Extended Log Format</a> (GELF) log format.\n\t */", "\t/**\n\t * <a href=\"https://go2docs.graylog.org/current/getting_in_log_data/gelf.html\">Graylog\n\t * Extended Log Format</a>（GELF）日志格式。\n\t */"), ("\t/**\n\t * The <a href=\n\t * \"https://github.com/logfellow/logstash-logback-encoder?tab=readme-ov-file#standard-fields\">Logstash</a>\n\t * log format.\n\t */", "\t/**\n\t * <a href=\n\t * \"https://github.com/logfellow/logstash-logback-encoder?tab=readme-ov-file#standard-fields\">Logstash</a>\n\t * 日志格式。\n\t */"), ("\t/**\n\t * Return the ID for this format.\n\t * @return the format identifier\n\t */", "\t/**\n\t * 返回此格式的 ID。\n\t *\n\t * @return the format identifier 格式标识符\n\t */"), ("\t/**\n\t * Find the {@link CommonStructuredLogFormat} for the given ID.\n\t * @param id the format identifier\n\t * @return the associated {@link CommonStructuredLogFormat} or {@code null}\n\t */", "\t/**\n\t * 查找给定 ID 对应的 {@link CommonStructuredLogFormat}。\n\t *\n\t * @param id the format identifier 格式标识符\n\t * @return the associated {@link CommonStructuredLogFormat} or {@code null} 关联格式或 {@code null}\n\t */")],
"ContextPairs.java": [("/**\n * Helper that can be used to add JSON pairs from context data (typically the logger MDC)\n * in the correct location (or drop them altogether).\n *\n * @author Phillip Webb\n * @since 3.5.0\n */", "/**\n * 辅助类，用于从上下文数据（通常为 logger MDC）添加 JSON 键值对，\n * 可放入正确位置或完全丢弃。\n *\n * @author Phillip Webb\n * @since 3.5.0\n */")],
"ElasticCommonSchemaProperties.java": [("/**\n * Properties for Elastic Common Schema structured logging.\n *\n * @param service service details\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n */", "/**\n * Elastic Common Schema（ECS）结构化日志的属性配置。\n *\n * @param service service details 服务详情\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n */")],
"GraylogExtendedLogFormatProperties.java": [("/**\n * Properties for Graylog Extended Log Format structured logging.\n *\n * @param host the application name\n * @param service service details\n * @author Samuel Lissner\n * @author Phillip Webb\n * @since 3.4.0\n */", "/**\n * Graylog Extended Log Format（GELF）结构化日志的属性配置。\n *\n * @param host the application name 应用名称（作为 GELF host）\n * @param service service details 服务详情\n * @author Samuel Lissner\n * @author Phillip Webb\n * @since 3.4.0\n */")],
"JsonWriterStructuredLogFormatter.java": [("/**\n * Base class for {@link StructuredLogFormatter} implementations that generates JSON using\n * a {@link JsonWriter}.\n *\n * @param <E> the log event type\n * @author Phillip Webb\n * @since 3.4.0\n */", "/**\n * 使用 {@link JsonWriter} 生成 JSON 的 {@link StructuredLogFormatter} 实现基类。\n *\n * @param <E> the log event type 日志事件类型\n * @author Phillip Webb\n * @since 3.4.0\n */")],
"StructuredLogFormatter.java": [("/**\n * Formats a log event to a structured log message.\n * <p>\n * Implementing classes can declare the following parameter types in the constructor:\n * <ul>\n * <li>{@link Environment}</li>\n * <li>{@link StructuredLoggingJsonMembersCustomizer}</li>\n * <li>{@link StructuredLoggingJsonMembersCustomizer.Builder}</li>\n * <li>{@link StackTracePrinter} (may be {@code null})</li>\n * <li>{@link ContextPairs}</li>\n * </ul>\n * When using Logback, implementing classes can also use the following parameter types in\n * the constructor:\n * <ul>\n * <li>{@code ch.qos.logback.classic.pattern.ThrowableProxyConverter}</li>\n * </ul>\n *\n * @param <E> the log event type\n * @author Moritz Halbritter\n * @since 3.4.0\n */", "/**\n * 将日志事件格式化为结构化日志消息。\n * <p>\n * 实现类可在构造函数中声明以下参数类型：\n * <ul>\n * <li>{@link Environment}</li>\n * <li>{@link StructuredLoggingJsonMembersCustomizer}</li>\n * <li>{@link StructuredLoggingJsonMembersCustomizer.Builder}</li>\n * <li>{@link StackTracePrinter}（可为 {@code null}）</li>\n * <li>{@link ContextPairs}</li>\n * </ul>\n * 使用 Logback 时，实现类还可在构造函数中使用：\n * <ul>\n * <li>{@code ch.qos.logback.classic.pattern.ThrowableProxyConverter}</li>\n * </ul>\n *\n * @param <E> the log event type 日志事件类型\n * @author Moritz Halbritter\n * @since 3.4.0\n */")],
"StructuredLogFormatterFactory.java": [("/**\n * Factory that can be used to create a fully instantiated {@link StructuredLogFormatter}\n * for either a {@link CommonStructuredLogFormat#getId() common format} or a\n * fully-qualified class name.\n *\n * @param <E> the log even type\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n * @see StructuredLogFormatter\n */", "/**\n * 用于创建完整实例化 {@link StructuredLogFormatter} 的工厂，\n * 支持 {@link CommonStructuredLogFormat#getId() 常见格式} ID 或全限定类名。\n *\n * @param <E> the log even type 日志事件类型\n * @author Moritz Halbritter\n * @author Phillip Webb\n * @since 3.4.0\n * @see StructuredLogFormatter\n */")],
"StructuredLoggingJsonMembersCustomizer.java": [("/**\n * Customizer that can be injected into {@link StructuredLogFormatter} implementations to\n * customize {@link JsonWriter} {@link Members}.\n * <p>\n * An implementation may be provided using the {@code logging.structured.json.customizer}\n * property. Alternatively, implementations can be registered in\n * {@code META-INF/spring.factories} under the key\n * {@code org.springframework.boot.logging.structured.StructuredLoggingJsonMembersCustomizer}.\n * <p>\n * Implementing classes can declare the following parameter types in the constructor:\n * <ul>\n * <li>{@link Environment}</li>\n * </ul>\n * When using Logback, implementing classes can also use the following parameter types in\n * the constructor:\n * <ul>\n * <li>{@code ch.qos.logback.classic.pattern.ThrowableProxyConverter}</li>\n * </ul>\n *\n * @param <T> the type being written\n * @author Phillip Webb\n * @since 3.4.0\n * @see JsonWriterStructuredLogFormatter\n */", "/**\n * 可注入 {@link StructuredLogFormatter} 实现以定制 {@link JsonWriter} {@link Members} 的 customizer。\n * <p>\n * 可通过 {@code logging.structured.json.customizer} 属性提供实现，\n * 或在 {@code META-INF/spring.factories} 中注册，键为\n * {@code org.springframework.boot.logging.structured.StructuredLoggingJsonMembersCustomizer}。\n * <p>\n * 实现类可在构造函数中声明以下参数类型：\n * <ul>\n * <li>{@link Environment}</li>\n * </ul>\n * 使用 Logback 时，还可在构造函数中使用：\n * <ul>\n * <li>{@code ch.qos.logback.classic.pattern.ThrowableProxyConverter}</li>\n * </ul>\n *\n * @param <T> the type being written 被写入的类型\n * @author Phillip Webb\n * @since 3.4.0\n * @see JsonWriterStructuredLogFormatter\n */")],
"StructuredLoggingJsonProperties.java": [("/**\n * Properties that can be used to customize structured logging JSON.\n *\n * @param include the paths that should be included. An empty set includes all names\n * @param exclude the paths that should be excluded. An empty set excludes nothing\n * @param rename a map of path to replacement names\n * @param add a map of additional elements {@link StructuredLoggingJsonMembersCustomizer}\n * @param stackTrace stack trace properties\n * @param customizer the fully qualified names of\n * {@link StructuredLoggingJsonMembersCustomizer} implementations\n * @param context context specific properties\n * @author Phillip Webb\n * @author Yanming Zhou\n */", "/**\n * 用于定制结构化日志 JSON 的属性。\n *\n * @param include the paths that should be included. An empty set includes all names 应包含的路径；空集合表示包含全部\n * @param exclude the paths that should be excluded. An empty set excludes nothing 应排除的路径；空集合表示不排除\n * @param rename a map of path to replacement names 路径到替换名称的映射\n * @param add a map of additional elements {@link StructuredLoggingJsonMembersCustomizer} 附加元素的映射\n * @param stackTrace stack trace properties 堆栈跟踪属性\n * @param customizer the fully qualified names of\n * {@link StructuredLoggingJsonMembersCustomizer} implementations customizer 实现的全限定类名\n * @param context context specific properties 上下文相关属性\n * @author Phillip Webb\n * @author Yanming Zhou\n */")],
"StructuredLoggingJsonPropertiesBeanFactoryInitializationAotProcessor.java": [("/**\n * {@link BeanFactoryInitializationAotProcessor} that registers {@link RuntimeHints} for\n * {@link StructuredLoggingJsonProperties}.\n *\n * @author Dmytro Nosan\n * @author Yanming Zhou\n * @author Phillip Webb\n */", "/**\n * 为 {@link StructuredLoggingJsonProperties} 注册 {@link RuntimeHints} 的\n * {@link BeanFactoryInitializationAotProcessor}。\n * 在 AOT 处理阶段为自定义 {@link StructuredLoggingJsonMembersCustomizer}\n * 与自定义 {@link StackTracePrinter} 注册反射提示。\n *\n * @author Dmytro Nosan\n * @author Yanming Zhou\n * @author Phillip Webb\n */")],
}
def apply_replacements(text, replacements):
    for old, new in replacements:
        if old not in text: raise ValueError(f"Pattern not found: {old[:120]}")
        text = text.replace(old, new, 1)
    return text
def main():
    failures, ok = [], 0
    for rel in BATCH_FILES:
        name = Path(rel).name
        src, dst = ORIGINAL / rel, ANALYZED / rel
        if not src.exists(): failures.append(f"MISSING original: {rel}"); continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        reps = FILE_REPLACEMENTS.get(name, [])
        if not reps: failures.append(f"NO_REPLACEMENTS: {rel}"); continue
        try:
            text = apply_replacements(dst.read_text(encoding="utf-8"), reps)
            cn = len(re.findall(r"[\u4e00-\u9fff]", text))
            if cn < 10 or "Licensed under the Apache License" not in text:
                failures.append(f"VALIDATION cn={cn}: {rel}"); continue
            dst.write_text(text, encoding="utf-8"); ok += 1; print(f"OK {rel}")
        except Exception as e: failures.append(f"{rel}: {e}")
    if ok == len(BATCH_FILES) and not failures:
        subprocess.run([sys.executable, str(ROOT / "scripts/mark_batch_done.py"), "--project", "springboot", "--version", "4.1.0", "--note", "wave12b logging/logback+structured [20:40]", *BATCH_FILES], check=True)
        batch = json.loads((QUEUE / "batch.json").read_text(encoding="utf-8"))
        batch["done"] = len([ln for ln in (QUEUE / "done.txt").read_text(encoding="utf-8").splitlines() if ln.strip()])
        batch["remaining_pending"] = len([ln for ln in (QUEUE / "pending.txt").read_text(encoding="utf-8").splitlines() if ln.strip()])
        (QUEUE / "batch.json").write_text(json.dumps(batch, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"ok": ok, "failures": failures})); return 1 if failures else 0
if __name__ == "__main__": raise SystemExit(main())
