"""Chinese JavaDoc replacements for RocketMQ wave50a store [0:15]."""

R: dict[str, list[tuple[str, str]]] = {
    'store/src/main/java/org/apache/rocketmq/store/MessageStore.java': [
        ('/**\n     * Query at most <code>maxMsgNums</code> messages belonging to <code>topic</code> at <code>queueId</code> starting\n     * from given <code>offset</code>. Resulting messages will further be screened using provided message filter.\n     *\n     * @param group           Consumer group that launches this query.\n     * @param topic           Topic to query.\n     * @param queueId         Queue ID to query.\n     * @param offset          Logical offset to start from.\n     * @param maxMsgNums      Maximum count of messages to query.\n     * @param maxTotalMsgSize Maximum total msg size of the messages\n     * @param messageFilter   Message filter used to screen desired messages.\n     * @return Matched messages.\n     */',
         '/**\n     * 从指定 Topic/队列 offset 起最多拉取 maxMsgNums 条消息。\n     * from given <code>offset</code>. Resulting messages will further be screened using provided message filter.\n     *\n     * @param group           Consumer group that launches this query.\n     * @param topic           Topic to query.\n     * @param queueId         Queue ID to query.\n     * @param offset          Logical offset to start from.\n     * @param maxMsgNums      Maximum count of messages to query.\n     * @param maxTotalMsgSize Maximum total msg size of the messages\n     * @param messageFilter   Message filter used to screen desired messages.\n     * @return Matched messages.\n     */'),
        ('/**\n     * Query at most <code>maxMsgNums</code> messages belonging to <code>topic</code> at <code>queueId</code> starting\n     * from given <code>offset</code>. Resulting messages will further be screened using provided message filter.\n     *\n     * @param group         Consumer group that launches this query.\n     * @param topic         Topic to query.\n     * @param queueId       Queue ID to query.\n     * @param offset        Logical offset to start from.\n     * @param maxMsgNums    Maximum count of messages to query.\n     * @param messageFilter Message filter used to screen desired messages.\n     * @return Matched messages.\n     */',
         '/**\n     * 从指定 Topic/队列 offset 起最多拉取 maxMsgNums 条消息。\n     * from given <code>offset</code>. Resulting messages will further be screened using provided message filter.\n     *\n     * @param group         Consumer group that launches this query.\n     * @param topic         Topic to query.\n     * @param queueId       Queue ID to query.\n     * @param offset        Logical offset to start from.\n     * @param maxMsgNums    Maximum count of messages to query.\n     * @param messageFilter Message filter used to screen desired messages.\n     * @return Matched messages.\n     */'),
        ('/**\n     * Asynchronous get message\n     * @see #getMessage(String, String, int, long, int, int, MessageFilter) getMessage\n     *\n     * @param group           Consumer group that launches this query.\n     * @param topic           Topic to query.\n     * @param queueId         Queue ID to query.\n     * @param offset          Logical offset to start from.\n     * @param maxMsgNums      Maximum count of messages to query.\n     * @param maxTotalMsgSize Maximum total msg size of the messages\n     * @param messageFilter   Message filter used to screen desired messages.\n     * @return Matched messages.\n     */',
         '/**\n     * 异步拉取消息。\n     * @see #getMessage(String, String, int, long, int, int, MessageFilter) getMessage\n     *\n     * @param group           Consumer group that launches this query.\n     * @param topic           Topic to query.\n     * @param queueId         Queue ID to query.\n     * @param offset          Logical offset to start from.\n     * @param maxMsgNums      Maximum count of messages to query.\n     * @param maxTotalMsgSize Maximum total msg size of the messages\n     * @param messageFilter   Message filter used to screen desired messages.\n     * @return Matched messages.\n     */'),
        ('/**\n     * Asynchronous get message\n     * @see #getMessage(String, String, int, long, int, MessageFilter) getMessage\n     *\n     * @param group         Consumer group that launches this query.\n     * @param topic         Topic to query.\n     * @param queueId       Queue ID to query.\n     * @param offset        Logical offset to start from.\n     * @param maxMsgNums    Maximum count of messages to query.\n     * @param messageFilter Message filter used to screen desired messages.\n     * @return Matched messages.\n     */',
         '/**\n     * 异步拉取消息。\n     * @see #getMessage(String, String, int, long, int, MessageFilter) getMessage\n     *\n     * @param group         Consumer group that launches this query.\n     * @param topic         Topic to query.\n     * @param queueId       Queue ID to query.\n     * @param offset        Logical offset to start from.\n     * @param maxMsgNums    Maximum count of messages to query.\n     * @param messageFilter Message filter used to screen desired messages.\n     * @return Matched messages.\n     */'),
        ('/**\n     * Check if the given message has been swapped out of the memory.\n     *\n     * @param topic         topic.\n     * @param queueId       queue ID.\n     * @param consumeOffset consume queue offset.\n     * @return true if the message is no longer in memory; false otherwise.\n     * @deprecated As of RIP-57, replaced by {@link #checkInMemByConsumeOffset(String, int, long, int)}, see <a href="https://github.com/apache/rocketmq/issues/5837">this issue</a> for more details\n     */',
         '/**\n     * 检查消息是否已被换出内存。\n     *\n     * @param topic         topic.\n     * @param queueId       queue ID.\n     * @param consumeOffset consume queue offset.\n     * @return true if the message is no longer in memory; false otherwise.\n     * @deprecated As of RIP-57, replaced by {@link #checkInMemByConsumeOffset(String, int, long, int)}, see <a href="https://github.com/apache/rocketmq/issues/5837">this issue</a> for more details\n     */'),
        ("/**\n     * Will be triggered when a new dispatch request is sent to message store.\n     *\n     * @param dispatchRequest dispatch request\n     * @param doDispatch      do dispatch if true\n     * @param commitLogFile   commit log file\n     * @param isRecover       is from recover process\n     * @param isFileEnd       if the dispatch request represents 'file end'\n     * @throws RocksDBException      only in rocksdb mode\n     */",
         "/**\n     * 向 Store 发送 dispatch 请求时触发。\n     *\n     * @param dispatchRequest dispatch request\n     * @param doDispatch      do dispatch if true\n     * @param commitLogFile   commit log file\n     * @param isRecover       is from recover process\n     * @param isFileEnd       if the dispatch request represents 'file end'\n     * @throws RocksDBException      only in rocksdb mode\n     */"),
        ('/**\n     * Estimate number of messages, within [from, to], which match given filter\n     *\n     * @param topic   Topic name\n     * @param queueId Queue ID\n     * @param from    Lower boundary of the range, inclusive.\n     * @param to      Upper boundary of the range, inclusive.\n     * @param filter  The message filter.\n     * @return Estimate number of messages matching given filter.\n     */',
         '/**\n     * 估算 [from, to] 范围内匹配过滤器的消息数量。\n     *\n     * @param topic   Topic name\n     * @param queueId Queue ID\n     * @param from    Lower boundary of the range, inclusive.\n     * @param to      Upper boundary of the range, inclusive.\n     * @param filter  The message filter.\n     * @return Estimate number of messages matching given filter.\n     */'),
        ('/**\n     * Asynchronous get the store time of the message specified.\n     * @see #getMessageStoreTimeStamp(String, int, long) getMessageStoreTimeStamp\n     *\n     * @param topic              message topic.\n     * @param queueId            queue ID.\n     * @param consumeQueueOffset consume queue offset.\n     * @return store timestamp of the message.\n     */',
         '/**\n     * 异步返回指定消息的存储时间。\n     * @see #getMessageStoreTimeStamp(String, int, long) getMessageStoreTimeStamp\n     *\n     * @param topic              message topic.\n     * @param queueId            queue ID.\n     * @param consumeQueueOffset consume queue offset.\n     * @return store timestamp of the message.\n     */'),
        ('/**\n     * Look up the physical offset of the message whose store timestamp is as specified with specific boundaryType.\n     *\n     * @param topic        Topic of the message.\n     * @param queueId      Queue ID.\n     * @param timestamp    Timestamp to look up.\n     * @param boundaryType Lower or Upper\n     * @return physical offset which matches.\n     */',
         '/**\n     * 按存储时间戳与边界类型查找 CommitLog 物理 offset。\n     *\n     * @param topic        Topic of the message.\n     * @param queueId      Queue ID.\n     * @param timestamp    Timestamp to look up.\n     * @param boundaryType Lower or Upper\n     * @return physical offset which matches.\n     */'),
        ('/**\n     * Asynchronous query messages by given key.\n     * @see #queryMessage(String, String, int, long, long) queryMessage\n     *\n     * @param topic  topic of the message.\n     * @param key    message key.\n     * @param maxNum maximum number of the messages possible.\n     * @param begin  begin timestamp.\n     * @param end    end timestamp.\n     */',
         '/**\n     * 异步按 key 查询消息。\n     * @see #queryMessage(String, String, int, long, long) queryMessage\n     *\n     * @param topic  topic of the message.\n     * @param key    message key.\n     * @param maxNum maximum number of the messages possible.\n     * @param begin  begin timestamp.\n     * @param end    end timestamp.\n     */'),
        ('/**\n     * Store a message into store in async manner, the processor can process the next request rather than wait for\n     * result when result is completed, notify the client in async manner\n     *\n     * @param msg MessageInstance to store\n     * @return a CompletableFuture for the result of store operation\n     */',
         '/**\n     * 异步落盘单条消息；Processor 无需阻塞等待结果。\n     * result when result is completed, notify the client in async manner\n     *\n     * @param msg 待存储消息\n     * @return a CompletableFuture for the result of store operation\n     */'),
        ('/**\n     * Get the offset of the message in the commit log, which is also known as physical offset.\n     *\n     * @param topic              Topic of the message to lookup.\n     * @param queueId            Queue ID.\n     * @param consumeQueueOffset offset of consume queue.\n     * @return physical offset.\n     */',
         '/**\n     * 返回消息在 CommitLog 中的物理 offset。\n     *\n     * @param topic              Topic of the message to lookup.\n     * @param queueId            Queue ID.\n     * @param consumeQueueOffset offset of consume queue.\n     * @return physical offset.\n     */'),
        ('/**\n     * Append data to commit log.\n     *\n     * @param startOffset starting offset.\n     * @param data        data to append.\n     * @param dataStart   the start index of data array\n     * @param dataLength  the length of data array\n     * @return true if success; false otherwise.\n     */',
         '/**\n     * 向 CommitLog 追加数据。\n     *\n     * @param startOffset starting offset.\n     * @param data        data to append.\n     * @param dataStart   the start index of data array\n     * @param dataLength  the length of data array\n     * @return 成功返回 true，否则 false\n     */'),
        ('/**\n     * Get maximum offset of the topic queue.\n     *\n     * @param topic     Topic name.\n     * @param queueId   Queue ID.\n     * @param committed return the max offset in ConsumeQueue if true, or the max offset in CommitLog if false\n     * @return Maximum offset at present.\n     */',
         '/**\n     * 返回 Topic 队列最大消费 offset。\n     *\n     * @param topic     Topic name.\n     * @param queueId   Queue ID.\n     * @param committed return the max offset in ConsumeQueue if true, or the max offset in CommitLog if false\n     * @return Maximum offset at present.\n     */'),
        ('/**\n     * Look up the physical offset of the message whose store timestamp is as specified.\n     *\n     * @param topic     Topic of the message.\n     * @param queueId   Queue ID.\n     * @param timestamp Timestamp to look up.\n     * @return physical offset which matches.\n     */',
         '/**\n     * 按存储时间戳查找对应消息的 CommitLog 物理 offset。\n     *\n     * @param topic     Topic of the message.\n     * @param queueId   Queue ID.\n     * @param timestamp Timestamp to look up.\n     * @return physical offset which matches.\n     */'),
        ('/**\n     * Query messages by given key.\n     *\n     * @param topic  topic of the message.\n     * @param key    message key.\n     * @param maxNum maximum number of the messages possible.\n     * @param begin  begin timestamp.\n     * @param end    end timestamp.\n     */',
         '/**\n     * 按消息 key 查询索引。\n     *\n     * @param topic  topic of the message.\n     * @param key    message key.\n     * @param maxNum maximum number of the messages possible.\n     * @param begin  begin timestamp.\n     * @param end    end timestamp.\n     */'),
        ('/**\n     * Check if the given message is in the page cache.\n     *\n     * @param topic         topic.\n     * @param queueId       queue ID.\n     * @param consumeOffset consume queue offset.\n     * @return true if the message is in page cache; false otherwise.\n     */',
         '/**\n     * 检查消息是否在 PageCache 中。\n     *\n     * @param topic         topic.\n     * @param queueId       queue ID.\n     * @param consumeOffset consume queue offset.\n     * @return true if the message is in page cache; false otherwise.\n     */'),
        ('/**\n     * Get the store time of the message specified.\n     *\n     * @param topic              message topic.\n     * @param queueId            queue ID.\n     * @param consumeQueueOffset consume queue offset.\n     * @return store timestamp of the message.\n     */',
         '/**\n     * 返回指定消息的存储时间。\n     *\n     * @param topic              message topic.\n     * @param queueId            queue ID.\n     * @param consumeQueueOffset consume queue offset.\n     * @return store timestamp of the message.\n     */'),
        ('/**\n     * Check if the given message is in store.\n     *\n     * @param topic         topic.\n     * @param queueId       queue ID.\n     * @param consumeOffset consume queue offset.\n     * @return true if the message is in store; false otherwise.\n     */',
         '/**\n     * 检查消息是否仍在 Store 中。\n     *\n     * @param topic         topic.\n     * @param queueId       queue ID.\n     * @param consumeOffset consume queue offset.\n     * @return true if the message is in store; false otherwise.\n     */'),
        ('/**\n     * Will be triggered when a new message is appended to commit log.\n     *\n     * @param msg           the msg that is appended to commit log\n     * @param result        append message result\n     * @param commitLogFile commit log file\n     */',
         '/**\n     * CommitLog 追加新消息后触发。\n     *\n     * @param msg           the msg that is appended to commit log\n     * @param result        append message result\n     * @param commitLogFile commit log file\n     */'),
        ("/**\n     * Delete topic's consume queue file and unused stats.\n     * This interface allows user delete system topic.\n     *\n     * @param deleteTopics unused topic name set\n     * @return the number of the topics which has been deleted.\n     */",
         '/**\n     * 删除 Topic 消费队列文件及无用统计。\n     * This interface allows user delete system topic.\n     *\n     * @param deleteTopics unused topic name set\n     * @return the number of the topics which has been deleted.\n     */'),
        ('/**\n     * Truncate commitLog and consume queue to certain offset.\n     *\n     * @param offsetToTruncate offset to truncate\n     * @return true if truncate succeed, false otherwise\n     * @throws RocksDBException only in rocksdb mode\n     */',
         '/**\n     * 将 CommitLog 与 CQ 截断到指定 offset。\n     *\n     * @param offsetToTruncate offset to truncate\n     * @return true if truncate succeed, false otherwise\n     * @throws RocksDBException only in rocksdb mode\n     */'),
        ('/**\n     * Look up the message by given commit log offset and size.\n     *\n     * @param commitLogOffset physical offset.\n     * @param size            message size\n     * @return Message whose physical offset is as specified.\n     */',
         '/**\n     * 按 CommitLog offset 与 size 查找消息。\n     *\n     * @param commitLogOffset physical offset.\n     * @param size            message size\n     * @return Message whose physical offset is as specified.\n     */'),
        ('/**\n     * Get the store time of the earliest message in the given queue.\n     *\n     * @param topic   Topic of the messages to query.\n     * @param queueId Queue ID to find.\n     * @return store time of the earliest message.\n     */',
         '/**\n     * 返回指定队列最早消息的存储时间。\n     *\n     * @param topic   Topic of the messages to query.\n     * @param queueId Queue ID to find.\n     * @return store time of the earliest message.\n     */'),
        ('/**\n     * Get the raw commit log data starting from the given offset, across multiple mapped files.\n     *\n     * @param offset starting offset.\n     * @param size   size of data to get\n     * @return commit log data.\n     */',
         '/**\n     * 跨多个 MappedFile 读取原始 CommitLog 数据。\n     *\n     * @param offset starting offset.\n     * @param size   size of data to get\n     * @return commit log data.\n     */'),
        ('/**\n     * Asynchronous get the store time of the earliest message in this store.\n     * @see #getEarliestMessageTime() getEarliestMessageTime\n     *\n     * @return timestamp of the earliest message in this store.\n     */',
         '/**\n     * 异步返回 Store 中最早消息的存储时间。\n     * @see #getEarliestMessageTime() getEarliestMessageTime\n     *\n     * @return timestamp of the earliest message in this store.\n     */'),
        ('/**\n     * Get one message from the specified commit log offset.\n     *\n     * @param commitLogOffset commit log offset.\n     * @param msgSize         message size.\n     * @return wrapped result of the message.\n     */',
         '/**\n     * 从指定 CommitLog offset 读取单条消息。\n     *\n     * @param commitLogOffset commit log offset.\n     * @param msgSize         message size.\n     * @return wrapped result of the message.\n     */'),
        ('/**\n     * Message store runtime information, which should generally contains various statistical information.\n     *\n     * @return runtime information of the message store in format of key-value pairs.\n     */',
         '/**\n     * 存储运行时信息，通常包含各类统计数据。\n     *\n     * @return runtime information of the message store in format of key-value pairs.\n     */'),
        ('/**\n     * Get consume queue of the topic/queue. If consume queue not exist, will create one then return it.\n     * @param topic   Topic.\n     * @param queueId Queue ID.\n     * @return Consume queue.\n     */',
         '/**\n     * 获取 Topic/队列消费队列；不存在时创建并返回。\n     * @param topic   Topic.\n     * @param queueId Queue ID.\n     * @return Consume queue.\n     */'),
        ('/**\n     * Assign a message to queue offset. If there is a race condition, you need to lock/unlock this method\n     * yourself.\n     *\n     * @param msg        message\n     * @throws RocksDBException\n     */',
         '/**\n     * 为消息分配队列 offset；存在竞态时需外部加锁。\n     * yourself.\n     *\n     * @param msg        message\n     * @throws RocksDBException\n     */'),
        ('/**\n     * Increase queue offset in memory table. If there is a race condition, you need to lock/unlock this method\n     *\n     * @param msg        message\n     * @param messageNum message num\n     */',
         '/**\n     * 递增内存位点表中的队列 offset；存在竞态时需外部加锁。\n     *\n     * @param msg        message\n     * @param messageNum message num\n     */'),
        ('/**\n     * Get consume queue of the topic/queue. If consume queue not exist, will return null\n     *\n     * @param topic   Topic.\n     * @param queueId Queue ID.\n     * @return Consume queue.\n     */',
         '/**\n     * 获取 Topic/队列消费队列；不存在时返回 null。\n     *\n     * @param topic   Topic.\n     * @param queueId Queue ID.\n     * @return Consume queue.\n     */'),
        ('/**\n     * Get the raw commit log data starting from the given offset, which should used for replication purpose.\n     *\n     * @param offset starting offset.\n     * @return commit log data.\n     */',
         '/**\n     * 从指定 offset 读取原始 CommitLog 数据（用于复制）。\n     *\n     * @param offset starting offset.\n     * @return commit log data.\n     */'),
        ('/**\n     * Get number of the milliseconds that have been stored in commit log and not yet dispatched to consume queue.\n     *\n     * @return number of the milliseconds to dispatch.\n     */',
         '/**\n     * 返回 CommitLog 中尚未 dispatch 的数据对应的时间跨度（毫秒）。\n     *\n     * @return number of the milliseconds to dispatch.\n     */'),
        ('/**\n     * Store a batch of messages in async manner\n     *\n     * @param messageExtBatch the message batch\n     * @return a CompletableFuture for the result of store operation\n     */',
         '/**\n     * 异步落盘批量消息。\n     *\n     * @param messageExtBatch 批量消息\n     * @return a CompletableFuture for the result of store operation\n     */'),
        ('/**\n     * Check message and return size\n     *\n     * @param byteBuffer\n     * @param checkCRC\n     * @param checkDupInfo\n     * @param readBody\n     * @return DispatchRequest\n     */',
         '/**\n     * 校验消息并返回大小。\n     *\n     * @param byteBuffer\n     * @param checkCRC\n     * @param checkDupInfo\n     * @param readBody\n     * @return DispatchRequest\n     */'),
        ('/**\n     * Look up the message by given commit log offset.\n     *\n     * @param commitLogOffset physical offset.\n     * @return Message whose physical offset is as specified.\n     */',
         '/**\n     * 按 CommitLog 物理 offset 查找消息。\n     *\n     * @param commitLogOffset physical offset.\n     * @return Message whose physical offset is as specified.\n     */'),
        ('/**\n     * Get the minimum offset of the topic queue.\n     *\n     * @param topic   Topic name.\n     * @param queueId Queue ID.\n     * @return Minimum offset at present.\n     */',
         '/**\n     * 返回 Topic 队列最小消费 offset。\n     *\n     * @param topic   Topic name.\n     * @param queueId Queue ID.\n     * @return Minimum offset at present.\n     */'),
        ('/**\n     * Get the total number of the messages in the specified queue.\n     *\n     * @param topic   Topic\n     * @param queueId Queue ID.\n     * @return total number.\n     */',
         '/**\n     * 返回指定队列消息总数。\n     *\n     * @param topic   Topic\n     * @param queueId Queue ID.\n     * @return total number.\n     */'),
        ('/**\n     * Get one message from the specified commit log offset.\n     *\n     * @param commitLogOffset commit log offset.\n     * @return wrapped result of the message.\n     */',
         '/**\n     * 从指定 CommitLog offset 读取单条消息。\n     *\n     * @param commitLogOffset commit log offset.\n     * @return wrapped result of the message.\n     */'),
        ('/**\n     * Get number of the bytes that have been stored in commit log and not yet dispatched to consume queue.\n     *\n     * @return number of the bytes to dispatch.\n     */',
         '/**\n     * 返回已写入 CommitLog 但尚未 dispatch 到 CQ 的字节数。\n     *\n     * @return number of the bytes to dispatch.\n     */'),
        ('/**\n     * Get maximum offset of the topic queue.\n     *\n     * @param topic   Topic name.\n     * @param queueId Queue ID.\n     * @return Maximum offset at present.\n     */',
         '/**\n     * 返回 Topic 队列最大消费 offset。\n     *\n     * @param topic   Topic name.\n     * @param queueId Queue ID.\n     * @return Maximum offset at present.\n     */'),
        ('/**\n     * Clean unused topics which not in retain topic name set.\n     *\n     * @param retainTopics all valid topics.\n     * @return number of the topics deleted.\n     */',
         '/**\n     * 清理不在保留集合中的 Topic。\n     *\n     * @param retainTopics all valid topics.\n     * @return number of the topics deleted.\n     */'),
        ('/**\n     * Init store metrics\n     *\n     * @param meter                     opentelemetry meter\n     * @param attributesBuilderSupplier metrics attributes builder\n     */',
         '/**\n     * 初始化 Store 指标。\n     *\n     * @param meter                     opentelemetry meter\n     * @param attributesBuilderSupplier metrics attributes builder\n     */'),
        ('/**\n     * Calculate the checksum of a certain range of data.\n     *\n     * @param from begin offset\n     * @param to   end offset\n     * @return checksum\n     */',
         '/**\n     * 计算指定数据范围的校验和。\n     *\n     * @param from begin offset\n     * @param to   end offset\n     * @return checksum\n     */'),
        ('/**\n     * Get number of the bytes that have been stored in commit log and not yet flushed to disk.\n     *\n     * @return number of the bytes to flush.\n     */',
         '/**\n     * 返回已写入 CommitLog 但尚未刷盘的字节数。\n     *\n     * @return number of the bytes to flush.\n     */'),
        ('/**\n     * Check if the offset is aligned with one message.\n     *\n     * @param offset offset to check\n     * @return true if aligned, false otherwise\n     */',
         '/**\n     * 检查 offset 是否与单条消息对齐。\n     *\n     * @param offset offset to check\n     * @return true if aligned, false otherwise\n     */'),
        ('/**\n     * Check if the transient store pool is deficient.\n     *\n     * @return true if the transient store pool is running out; false otherwise.\n     */',
         '/**\n     * 检查 TransientStorePool 是否不足。\n     *\n     * @return true if the transient store pool is running out; false otherwise.\n     */'),
        ('/**\n     * Check if the operating system page cache is busy or not.\n     *\n     * @return true if the OS page cache is busy; false otherwise.\n     */',
         '/**\n     * 检查 OS PageCache 是否繁忙。\n     *\n     * @return true if the OS page cache is busy; false otherwise.\n     */'),
        ('/**\n     * Get the store time of the earliest message in this store.\n     *\n     * @return timestamp of the earliest message in this store.\n     */',
         '/**\n     * 返回 Store 中最早消息的存储时间。\n     *\n     * @return timestamp of the earliest message in this store.\n     */'),
        ('/**\n     * Store a batch of messages.\n     *\n     * @param messageExtBatch Message batch.\n     * @return result of storing batch messages.\n     */',
         '/**\n     * 同步落盘批量消息。\n     *\n     * @param messageExtBatch Message batch.\n     * @return result of storing batch messages.\n     */'),
        ('/**\n     * Truncate dirty logic files\n     *\n     * @param phyOffset physical offset\n     * @throws RocksDBException only in rocksdb mode\n     */',
         '/**\n     * 截断脏逻辑文件。\n     *\n     * @param phyOffset physical offset\n     * @throws RocksDBException only in rocksdb mode\n     */'),
        ('/**\n     * Get last mapped file\n     *\n     * @param startOffset\n     * @return true when get the last mapped file, false when get null\n     */',
         '/**\n     * 返回最后一个 MappedFile。\n     *\n     * @param startOffset\n     * @return true when get the last mapped file, false when get null\n     */'),
        ('/**\n     * Store a message into store.\n     *\n     * @param msg Message instance to store\n     * @return result of store operation.\n     */',
         '/**\n     * 同步落盘单条消息。\n     *\n     * @param msg Message instance to store\n     * @return result of store operation.\n     */'),
        ('/**\n     * Flush the message store to persist all data.\n     *\n     * @return maximum offset flushed to persistent storage device.\n     */',
         '/**\n     * 刷盘持久化全部数据。\n     *\n     * @return maximum offset flushed to persistent storage device.\n     */'),
        ('/**\n     * Use FileChannel to get data\n     *\n     * @param offset\n     * @param size\n     * @param byteBuffer\n     * @return\n     */',
         '/**\n     * 通过 FileChannel 读取数据。\n     *\n     * @param offset\n     * @param size\n     * @param byteBuffer\n     * @return\n     */'),
        ('/**\n     * Return the current timestamp of the store.\n     *\n     * @return current time in milliseconds since 1970-01-01.\n     */',
         '/**\n     * 返回 Store 当前时间戳。\n     *\n     * @return current time in milliseconds since 1970-01-01.\n     */'),
        ('/**\n * This class defines contracting interfaces to implement, allowing third-party vendor to use customized message store.\n */',
         '/**\n * 消息存储核心接口：第三方厂商可据此实现自定义存储引擎。\n */'),
        ('/**\n     * Set the number of alive replicas in group.\n     *\n     * @param aliveReplicaNums number of alive replicas\n     */',
         '/**\n     * 设置副本组存活副本数。\n     *\n     * @param aliveReplicaNums number of alive replicas\n     */'),
        ('/**\n     * Get last mapped file and return lase file first Offset\n     *\n     * @return lastMappedFile first Offset\n     */',
         '/**\n     * 返回最后一个 MappedFile 及其首条 offset。\n     *\n     * @return lastMappedFile first Offset\n     */'),
        ("/**\n     * If 'sync disk flush' is configured in this message store\n     *\n     * @return yes if true, no if false\n     */",
         '/**\n     * 是否配置为同步刷盘。\n     *\n     * @return yes if true, no if false\n     */'),
        ('/**\n     * Return how much the slave falls behind.\n     *\n     * @return number of bytes that slave falls behind.\n     */',
         '/**\n     * 返回从节点落后 Master 的字节数。\n     *\n     * @return number of bytes that slave falls behind.\n     */'),
        ('/**\n     * Get lock time in milliseconds of the store by far.\n     *\n     * @return lock time in milliseconds.\n     */',
         '/**\n     * 返回 Store 迄今持锁时间（毫秒）。\n     *\n     * @return lock time in milliseconds.\n     */'),
        ('/**\n     * Get remain transientStoreBuffer numbers\n     *\n     * @return remain transientStoreBuffer numbers\n     */',
         '/**\n     * 返回 TransientStore 缓冲剩余数量。\n     *\n     * @return remain transientStoreBuffer numbers\n     */'),
        ('/**\n     * Destroy this message store. Generally, all persistent files should be removed after invocation.\n     */',
         '/**\n     * 销毁消息存储；通常应删除全部持久化文件。\n     */'),
        ('/**\n     * Get the running information of this store.\n     *\n     * @return message store running info.\n     */',
         '/**\n     * 返回存储运行时信息。\n     *\n     * @return message store running info.\n     */'),
        ('/**\n     * Set broker init max offset.\n     *\n     * @param brokerInitMaxOffset broker init max offset\n     */',
         '/**\n     * 设置 Broker 初始化最大 offset。\n     *\n     * @param brokerInitMaxOffset broker init max offset\n     */'),
        ('/**\n     * Unlock mappedFile\n     *\n     * @param unlockMappedFile the file that needs to be unlocked\n     */',
         '/**\n     * 解锁 MappedFile。\n     *\n     * @param unlockMappedFile the file that needs to be unlocked\n     */'),
        ('/**\n     * Get the allocate-mappedFile service\n     *\n     * @return the allocate-mappedFile service\n     */',
         '/**\n     * 返回 MappedFile 分配服务。\n     *\n     * @return the allocate-mappedFile service\n     */'),
        ('/**\n     * Get the number of alive replicas in group.\n     *\n     * @return number of alive replicas\n     */',
         '/**\n     * 返回副本组存活副本数。\n     *\n     * @return number of alive replicas\n     */'),
        ('/**\n     * Set master flushed offset.\n     *\n     * @param masterFlushedOffset master flushed offset\n     */',
         '/**\n     * 设置 Master 已刷盘 offset。\n     *\n     * @param masterFlushedOffset master flushed offset\n     */'),
        ('/**\n     * Load previously stored messages.\n     *\n     * @return true if success; false otherwise.\n     */',
         '/**\n     * 加载持久化消息与索引数据。\n     *\n     * @return 成功返回 true，否则 false\n     */'),
        ('/**\n     * If this message store is sync master role\n     *\n     * @return yes if true, no if false\n     */',
         '/**\n     * 是否为 SyncMaster 角色。\n     *\n     * @return yes if true, no if false\n     */'),
        ('/**\n     * Get remain how many data to commit\n     *\n     * @return remain how many data to commit\n     */',
         '/**\n     * 返回待 commit 数据量。\n     *\n     * @return remain how many data to commit\n     */'),
        ('/**\n     * Return whether mapped file is empty\n     *\n     * @return whether mapped file is empty\n     */',
         '/**\n     * 返回 MappedFile 是否为空。\n     *\n     * @return whether mapped file is empty\n     */'),
        ('/**\n     * Get metrics view of store\n     *\n     * @return List of metrics selector and view pair\n     */',
         '/**\n     * 返回 Store 指标视图。\n     *\n     * @return List of metrics selector and view pair\n     */'),
        ('/**\n     * Get BrokerStatsManager of the messageStore.\n     *\n     * @return BrokerStatsManager.\n     */',
         '/**\n     * 返回 Broker 统计管理器。\n     *\n     * @return BrokerStatsManager.\n     */'),
        ('/**\n     * Get remain how many data to flush\n     *\n     * @return remain how many data to flush\n     */',
         '/**\n     * 返回待 flush 数据量。\n     *\n     * @return remain how many data to flush\n     */'),
        ('/**\n     * Get master broker message store in process in broker container\n     *\n     * @return\n     */',
         '/**\n     * BrokerContainer 中获取同进程 Master Store。\n     *\n     * @return\n     */'),
        ('/**\n     * Set master broker message store in process\n     *\n     * @param masterStoreInProcess\n     */',
         '/**\n     * 设置同进程 Master Store 引用。\n     *\n     * @param masterStoreInProcess\n     */'),
        ('/**\n     * Get the maximum commit log offset.\n     *\n     * @return maximum commit log offset.\n     */',
         '/**\n     * 返回 CommitLog 最大物理 offset。\n     *\n     * @return maximum commit log offset.\n     */'),
        ('/**\n     * Get the minimum commit log offset.\n     *\n     * @return minimum commit log offset.\n     */',
         '/**\n     * 返回 CommitLog 最小物理 offset。\n     *\n     * @return minimum commit log offset.\n     */'),
        ('/**\n     * Launch this message store.\n     *\n     * @throws Exception if there is any error.\n     */',
         '/**\n     * 启动消息存储（Reput、HA、定时线程等）。\n     *\n     * @throws Exception 启动异常\n     */'),
        ('/**\n     * Get the store checkpoint component\n     *\n     * @return the checkpoint component\n     */',
         '/**\n     * 返回 Store 检查点组件。\n     *\n     * @return the checkpoint component\n     */'),
        ('/**\n     * Get the perf counter component\n     *\n     * @return the perf counter component\n     */',
         '/**\n     * 返回性能计数器。\n     *\n     * @return the perf counter component\n     */'),
        ('/**\n     * Get broker init max offset.\n     *\n     * @return broker max offset in startup\n     */',
         '/**\n     * 返回 Broker 初始化最大 offset。\n     *\n     * @return broker max offset in startup\n     */'),
        ('/**\n     * Add dispatcher.\n     *\n     * @param dispatcher commit log dispatcher to add\n     */',
         '/**\n     * 添加 dispatch 处理器。\n     *\n     * @param dispatcher commit log dispatcher to add\n     */'),
        ('/**\n     * Get whether message store is shutdown\n     *\n     * @return whether shutdown\n     */',
         '/**\n     * 返回 Store 是否已 shutdown。\n     *\n     * @return whether shutdown\n     */'),
        ('/**\n     * Get the message store config\n     *\n     * @return the message store config\n     */',
         '/**\n     * 返回 MessageStore 配置。\n     *\n     * @return the message store config\n     */'),
        ('/**\n     * Get the transient store pool\n     *\n     * @return the transient store pool\n     */',
         '/**\n     * 返回 TransientStorePool。\n     *\n     * @return the transient store pool\n     */'),
        ('/**\n     * Set confirm offset.\n     *\n     * @param phyOffset confirm offset to set.\n     */',
         '/**\n     * 设置 confirm offset。\n     *\n     * @param phyOffset confirm offset to set.\n     */'),
        ('/**\n     * Get the statistics service\n     *\n     * @return the statistics service\n     */',
         '/**\n     * 返回存储统计服务。\n     *\n     * @return the statistics service\n     */'),
        ('/**\n     * Get the dispatcher list.\n     *\n     * @return list of the dispatcher.\n     */',
         '/**\n     * 返回 CommitLog dispatch 处理器列表。\n     *\n     * @return list of the dispatcher.\n     */'),
        ('/**\n     * Get master flushed offset.\n     *\n     * @return master flushed offset\n     */',
         '/**\n     * 返回 Master 已刷盘 offset。\n     *\n     * @return master flushed offset\n     */'),
        ('/**\n     * Get put message hook list\n     *\n     * @return List of PutMessageHook\n     */',
         '/**\n     * 返回落盘 Hook 列表。\n     *\n     * @return List of PutMessageHook\n     */'),
        ('/**\n     * Get state machine version\n     *\n     * @return state machine version\n     */',
         '/**\n     * 返回状态机版本。\n     *\n     * @return state machine version\n     */'),
        ('/**\n     * Get store metrics manager\n     *\n     * @return store metrics manager\n     */',
         '/**\n     * 返回 Store 指标管理器。\n     *\n     * @return store metrics manager\n     */'),
        ('/**\n     * Get the current flushed offset.\n     *\n     * @return flushed offset\n     */',
         '/**\n     * 返回当前已刷盘 offset。\n     *\n     * @return flushed offset\n     */'),
        ('/**\n     * Get send message back hook\n     *\n     * @return SendMessageBackHook\n     */',
         '/**\n     * 返回消息退回 Hook。\n     *\n     * @return SendMessageBackHook\n     */'),
        ('/**\n     * Update HA master address.\n     *\n     * @param newAddr new address.\n     */',
         '/**\n     * 更新 HA Master 地址。\n     *\n     * @param newAddr new address.\n     */'),
        ('/**\n     * Set send message back hook\n     *\n     * @param sendMessageBackHook\n     */',
         '/**\n     * 设置消息退回 Hook。\n     *\n     * @param sendMessageBackHook\n     */'),
        ('/**\n     * Update master address.\n     *\n     * @param newAddr new address.\n     */',
         '/**\n     * 更新 Master 地址。\n     *\n     * @param newAddr new address.\n     */'),
        ('/**\n     * HA runtime information\n     * @return runtime information of ha\n     */',
         '/**\n     * HA 运行时信息。\n     * @return runtime information of ha\n     */'),
        ('/**\n     * Get the system clock\n     *\n     * @return the system clock\n     */',
         '/**\n     * 返回系统时钟。\n     *\n     * @return the system clock\n     */'),
        ('/**\n     * Get confirm offset.\n     *\n     * @return confirm offset.\n     */',
         '/**\n     * 返回 confirm offset。\n     *\n     * @return confirm offset.\n     */'),
        ('/**\n     * Get the queue store\n     *\n     * @return the queue store\n     */',
         '/**\n     * 返回消费队列存储。\n     *\n     * @return the queue store\n     */'),
        ('/**\n     * Get the commit log\n     *\n     * @return the commit log\n     */',
         '/**\n     * 返回 CommitLog 实例。\n     *\n     * @return the commit log\n     */'),
        ('/**\n     * Get the HA service\n     *\n     * @return the HA service\n     */',
         '/**\n     * 返回 HA 服务。\n     *\n     * @return the HA service\n     */'),
        ('/**\n     * Get running flags\n     *\n     * @return running flags\n     */',
         '/**\n     * 返回运行标志。\n     *\n     * @return running flags\n     */'),
        ('/**\n     * Wake up AutoRecoverHAClient to start HA connection.\n     */',
         '/**\n     * 唤醒 AutoRecoverHAClient 建立 HA 连接。\n     */'),
        ('/**\n     * Set physical offset\n     *\n     * @param phyOffset\n     */',
         '/**\n     * 设置物理 offset。\n     *\n     * @param phyOffset\n     */'),
        ('\n    //The following interfaces are used for duplication mode\n',
         '\n    /** 以下接口用于副本/复制模式 */'),
        ('/**\n     * notify message arrive if necessary\n     */',
         '/**\n     * 必要时通知消息到达。\n     */'),
        ('/**\n     * Execute file deletion manually.\n     */',
         '/**\n     * 手动触发过期文件删除。\n     */'),
        ('/**\n     * Clean expired consume queues.\n     */',
         '/**\n     * 清理过期消费队列。\n     */'),
        ('/**\n     * Shutdown this message store.\n     */',
         '/**\n     * 关闭消息存储并释放资源。\n     */'),
        ('/**\n     * Recover topic queue table\n     */',
         '/**\n     * 恢复 Topic 队列表。\n     */'),
        ('public interface MessageStore {',
         '/**\n * 消息存储核心接口：定义 Broker 落盘、读取、索引、HA 同步、位点管理与统计等契约，第三方可基于此实现自定义存储引擎。\n */\npublic interface MessageStore {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/StoreStatsService.java': [
        ('    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('    private static final int MAX_RECORDS_OF_SAMPLING = 60 * 10;',
         '    /** 采样窗口最大记录数（10 分钟）。 */\n    private static final int MAX_RECORDS_OF_SAMPLING = 60 * 10;'),
        ('    private static final int FREQUENCY_OF_SAMPLING = 1000;',
         '    /** 采样频率（毫秒）。 */\n    private static final int FREQUENCY_OF_SAMPLING = 1000;'),
        ('public class StoreStatsService extends ServiceThread {',
         '/**\n * 存储层统计服务：采样记录 put/get TPS、延迟分布桶、Topic 维度计数及磁盘落后指标，周期性打印并供 Broker 查询。\n */\npublic class StoreStatsService extends ServiceThread {'),
        ('    // for putMessageEntireTimeMax',
         '    /** 保护 putMessageEntireTimeMax 的锁 */'),
        ('    // for getMessageEntireTimeMax',
         '    /** 保护 getMessageEntireTimeMax 的锁 */'),
        ('\n    //The rule to define buckets',
         '\n    /** 定义延迟分布桶的规则 */'),
        ('    public String getServiceName(',
         '    /** 返回后台线程服务名。 */\n    public String getServiceName('),
        ('\n    public void run(',
         '\n    /** 后台线程主循环。 */\n\n    public void run('),
        ('    //buckets',
         '    /** 当前采样桶 */'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/config/MessageStoreConfig.java': [
        ('/**\n     * 1. Register to broker after (startTime + disappearTimeAfterStart)\n     * 2. Internal msg exchange will start after (startTime + disappearTimeAfterStart)\n     * A. PopReviveService\n     * B. TimerDequeueGetService\n     */',
         '/**\n * 1. Broker 在 (startTime + disappearTimeAfterStart) 后才注册\n * 2. 内部消息交换（PopReviveService、TimerDequeueGetService 等）也在该时刻后启动\n\n */'),
        ('/**\n     * Maximum size of data to transfer to slave.\n     * NOTE: cannot be larger than HAClient.READ_MAX_BUFFER_SIZE\n     */',
         '/**\n * 向 Slave 传输数据的最大字节数；不可大于 HAClient.READ_MAX_BUFFER_SIZE。\n\n */'),
        ('\n    // The maximum size of message body can be  set in config;count with maxMsgNums * CQ_STORE_UNIT_SIZE(20 || 46)',
         '\n    /** 可配置的最大消息体；与 maxMsgNums * CQ_STORE_UNIT_SIZE 相关 */'),
        ('/**\n     * introduced since 4.0.x. Determine whether to use mutex reentrantLock when putting message.<br/>\n     */',
         '/**\n * 自 4.0.x 起：落盘时是否使用互斥 ReentrantLock。\n\n */'),
        ('    // Used by PutMessage to wait messages be flushed to disk and synchronized in current broker member group.',
         '    /** PutMessage 等待刷盘并在副本组同步完成 */'),
        ('    // This helps detect and truncate old file data that may pass CRC checks but contains invalid offsets.',
         '    /** 帮助检测并截断 CRC 通过但 offset 无效的旧数据 */'),
        ('        // In order to get this value from messageStoreConfig properties file created before v4.4.1.',
         '        /** 兼容 v4.4.1 之前 properties 文件读取该值 */'),
        ('    // The maximum size of message body,default is 4M,4M only for body length,not include others.',
         '    /** 消息体最大长度，默认 4M（仅 body，不含属性） */'),
        ('    // This check adds some overhead,so it may be disabled in cases seeking extreme performance.',
         '    /** 校验有开销，极致性能场景可关闭 */'),
        ('    // This ensures no on-the-wire or on-disk corruption to the messages occurred.',
         '    /** 防止网络或磁盘损坏的消息被消费 */'),
        ('    // Whether check the commitlog offset validity during abnormal recovery.',
         '    /** 异常恢复时是否校验 CommitLog offset 有效性 */'),
        ('    // The number of hours to keep a log file before deleting it (in hours)',
         '    /** 日志文件保留小时数 */'),
        ('    // Used by GroupTransferService to sync messages from master to slave',
         '    /** GroupTransferService 主从同步消息用 */'),
        ('\n    // Maximum length of topic, it will be removed in the future release',
         '\n    /** Topic 最大长度（后续版本移除） */'),
        ('    // How many pages are to be committed when commit data to file',
         '    /** commit 到文件的页数 */'),
        ('    // How many pages are to be flushed when flush ConsumeQueue',
         '    /** ConsumeQueue flush 页数 */'),
        ('\n    // CompactionLog consumeQueue file size, default is 10M',
         '\n    /** Compaction CQ 单文件大小，默认 10M */'),
        ('    // this will be set by pipe of calculate filter bit map.',
         '    /** 由位图计算管道设置 */'),
        ('    // How many pages are to be flushed when flush CommitLog',
         '    /** CommitLog flush 页数 */'),
        ('\n    //The root directory in which the log data is kept',
         '\n    /** 日志数据根目录 */'),
        ('    // Whether check the CRC32 of the records consumed.',
         '    /** 消费时是否校验 CRC32 */'),
        ('    // Flush page size when the disk in warming state',
         '    /** 磁盘预热时的 flush 页大小 */'),
        ('    public static final String MULTI_PATH_SPLITTER =',
         '    /** 多路径 CommitLog 分隔符。 */\n    public static final String MULTI_PATH_SPLITTER ='),
        ('\n    //The directory in which the commitlog is kept',
         '\n    /** CommitLog 存储目录 */'),
        ('\n    //The directory in which the epochFile is kept',
         '\n    /** Epoch 文件目录 */'),
        ('\n    // CompactionLog file size, default is 100M',
         '\n    /** CompactionLog 单文件大小，默认 100M */'),
        ('\n    // Shared byte buffer manager configuration',
         '\n    /** 共享 ByteBuffer 管理器配置 */'),
        ('\n    // Only used if TransientStorePool enabled',
         '\n    /** 仅 TransientStorePool 启用时有效 */'),
        ('\n    // ConsumeQueue file size,default is 30W',
         '\n    /** ConsumeQueue 单文件条目数，默认 30 万 */'),
        ('    // Sleep interval between to corrections',
         '    /** 校正间隔休眠时间 */'),
        ('\n    // TimerLog file size, default is 100M',
         '\n    /** TimerLog 单文件大小，默认 100M */'),
        ('\n    // CommitLog file size,default is 1G',
         '\n    /** CommitLog 单文件大小，默认 1G */'),
        ('    // ConsumeQueue extend file size, 48M',
         '    /** ConsumeQueue 扩展文件大小，48M */'),
        ('    // When to delete,default is at 4 am',
         '    /** 定时删除时刻，默认凌晨 4 点 */'),
        ('    // Force correct min offset interval',
         '    /** 强制校正最小 offset 间隔 */'),
        ('    // ConsumeQueue removal interval',
         '    /** ConsumeQueue 过期删除检查间隔 */'),
        ('    // Flow control for ConsumeQueue',
         '    /** ConsumeQueue 流控阈值 */'),
        ('\n    // DLedger message store config',
         '\n    /** DLedger 存储配置 */'),
        ('    // Bit count of filter bit map.',
         '    /** 过滤器位图 bit 数 */'),
        ('    // ConsumeQueue flush interval',
         '    /** ConsumeQueue 刷盘间隔 */'),
        ('public class MessageStoreConfig {',
         '/**\n * MessageStore 运行时配置：路径、MappedFile 大小、刷盘/清理策略、HA、RocksDB、定时消息、Compaction 等全部可调参数。\n */\npublic class MessageStoreConfig {'),
        ('    // CommitLog removal interval',
         '    /** CommitLog 过期删除检查间隔 */'),
        ('\n    // CommitLog flush interval',
         '\n    /** CommitLog 刷盘间隔 */'),
        ('    // flush data to FileChannel',
         '    /** 将数据 flush 到 FileChannel */'),
        ('    // Resource reclaim interval',
         '    /** 资源回收间隔 */'),
        ('\n    // default, defaultRocksDB',
         '\n    /** 默认 RocksDB 模式标识 */'),
        ('    // enable consume queue ext',
         '    /** 是否启用 ConsumeQueue 扩展文件 */'),
        ('\n    // Whether schedule flush',
         '\n    /** 是否定时 flush */'),
        ('    //For recheck the reput',
         '    /** Reput 复查用 */'),
        ('    // flush data to disk',
         '    /** 将数据 flush 到磁盘 */'),
        ('    //Polish dispatch',
         '    /** Dispatch 优化开关 */'),
        ('\n    // rocksdb mode',
         '\n    /** RocksDB 模式 */'),
        ('    // swap',
         '    /** Swap 相关配置 */'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/dledger/DLedgerCommitLog.java': [
        ('/**\n * Store all metadata downtime for recovery, data protection reliability\n */',
         '/**\n * 存储恢复所需的全部元数据停机信息，保障数据可靠性。\n\n */'),
        ('\n    //The id identifies the broker role, 0 means master, others means slave',
         '\n    /** Broker 角色 ID：0 为 Master，非 0 为 Slave */'),
        ('\n    //This offset separate the old commitlog from dledger commitlog',
         '\n    /** 分隔旧 CommitLog 与 DLedger CommitLog 的 offset */'),
        ('        //the old logic will keep the last file, here to delete it',
         '        /** 旧逻辑保留最后一个文件，此处主动删除 */'),
        ('            //To prevent too much log in defaultMessageStore',
         '            /** 避免 DefaultMessageStore 日志过多 */'),
        ('/**\n             * Serialize message\n             */',
         '/**\n * 序列化消息。\n\n */'),
        ('public class DLedgerCommitLog extends CommitLog {',
         '/**\n * 基于 DLedger 的 CommitLog 实现：将消息写入 Raft 复制日志，支持主从自动切换与 epoch 管理。\n */\npublic class DLedgerCommitLog extends CommitLog {'),
        ('    public SelectMappedBufferResult getData(',
         '    /** 读取映射文件数据。 */\n    public SelectMappedBufferResult getData('),
        ('        public synchronized void release(',
         '        /** 释放引用计数。 */\n        public synchronized void release('),
        ('    public int deleteExpiredFile(',
         '    /** 删除过期索引文件。 */\n    public int deleteExpiredFile('),
        ('\n        public byte[] getData(',
         '\n        /** 读取映射文件数据。 */\n\n        public byte[] getData('),
        ('    public boolean getData(',
         '    /** 读取映射文件数据。 */\n    public boolean getData('),
        ('    public void shutdown(',
         '    /** 关闭并释放资源。 */\n    public void shutdown('),
        ('    public boolean load(',
         '    /** 加载持久化数据。 */\n    public boolean load('),
        ('    public void destroy(',
         '    /** 销毁索引服务。 */\n    public void destroy('),
        ('    public void start(',
         '    /** 启动服务。 */\n    public void start('),
        ('    public long flush(',
         '    /** 刷盘。 */\n    public long flush('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAClient.java': [
        ('/**\n     * Report header buffer size. Schema: slaveMaxOffset. Format:\n     *\n     * <pre>\n     * ┌───────────────────────────────────────────────┐\n     * │                  slaveMaxOffset               │\n     * │                    (8bytes)                   │\n     * ├───────────────────────────────────────────────┤\n     * │                                               │\n     * │                  Report Header                │\n     * </pre>\n     * <p>\n     */',
         '/**\n * 上报头缓冲区大小；协议字段：slaveMaxOffset（8 字节）。\n\n */'),
        ('    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('public class DefaultHAClient extends ServiceThread implements HAClient {',
         '/**\n * 经典 HA 从节点客户端：连接 Master 拉取 CommitLog 并上报 slaveMaxOffset。\n */\npublic class DefaultHAClient extends ServiceThread implements HAClient {'),
        ('    private static final int READ_MAX_BUFFER_SIZE = 1024 * 1024 * 4;',
         '    /** 读缓冲上限（4MB）。 */\n    private static final int READ_MAX_BUFFER_SIZE = 1024 * 1024 * 4;'),
        ('/**\n     * last time that slave reports offset to master.\n     */',
         '/**\n * Slave 最近一次向 Master 上报 offset 的时间。\n\n */'),
        ('/**\n     * last time that slave reads date from master.\n     */',
         '/**\n * Slave 最近一次从 Master 读取数据的时间。\n\n */'),
        ('    private final AtomicReference<String> masterHaAddress =',
         '    /** Master HA 地址（原子引用）。 */\n    private final AtomicReference<String> masterHaAddress ='),
        ('    private volatile HAConnectionState currentState =',
         '    /** 当前 HA 连接状态。 */\n    private volatile HAConnectionState currentState ='),
        ('    private DefaultMessageStore defaultMessageStore;',
         '    /** 所属 DefaultMessageStore。 */\n    private DefaultMessageStore defaultMessageStore;'),
        ('    public static final int REPORT_HEADER_SIZE = 8;',
         '    /** 上报头大小（8 字节 slaveMaxOffset）。 */\n    public static final int REPORT_HEADER_SIZE = 8;'),
        ('\n    public void changeCurrentState(',
         '\n    /** 切换 HA 连接状态。 */\n\n    public void changeCurrentState('),
        ('    public String getServiceName(',
         '    /** 返回后台线程服务名。 */\n    public String getServiceName('),
        ('    public void shutdown(',
         '    /** 关闭并释放资源。 */\n    public void shutdown('),
        ('    public void run(',
         '    /** 后台线程主循环。 */\n    public void run('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/ha/DefaultHAConnection.java': [
        ('/**\n     * Transfer Header buffer size. Schema: physic offset and body size. Format:\n     *\n     * <pre>\n     * ┌───────────────────────────────────────────────┬───────────────────────┐\n     * │                  physicOffset                 │         bodySize      │\n     * │                    (8bytes)                   │         (4bytes)      │\n     * ├───────────────────────────────────────────────┴───────────────────────┤\n     * │                                                                       │\n     * │                           Transfer Header                             │\n     * </pre>\n     * <p>\n     */',
         '/**\n * 传输头缓冲区大小；包含物理 offset 与 body 大小。\n\n */'),
        ('    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('public class DefaultHAConnection implements HAConnection {',
         '/**\n * 经典 HA 主节点连接：向 Slave 传输 CommitLog 数据并接收 offset 上报。\n */\npublic class DefaultHAConnection implements HAConnection {'),
        ('    private volatile HAConnectionState currentState =',
         '    /** 当前 HA 连接状态。 */\n    private volatile HAConnectionState currentState ='),
        ('\n                            // Build Header',
         '\n                            /** 构建传输头 */'),
        ('\n                        // Build Header',
         '\n                        /** 构建传输头 */'),
        ('        public String getServiceName(',
         '        /** 返回后台线程服务名。 */\n        public String getServiceName('),
        ('\n    public void changeCurrentState(',
         '\n    /** 切换 HA 连接状态。 */\n\n    public void changeCurrentState('),
        ('        public void shutdown(',
         '        /** 关闭并释放资源。 */\n        public void shutdown('),
        ('            // Write Header',
         '            /** 写入传输头 */'),
        ('\n            // Write Body',
         '\n            /** 写入消息体 */'),
        ('\n    public void shutdown(',
         '\n    /** 关闭并释放资源。 */\n\n    public void shutdown('),
        ('        public void run(',
         '        /** 后台线程主循环。 */\n        public void run('),
        ('\n    public void start(',
         '\n    /** 启动服务。 */\n\n    public void start('),
        ('\n    public void close(',
         '\n    /** 关闭连接。 */\n\n    public void close('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAClient.java': [
        ('    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('public class AutoSwitchHAClient extends ServiceThread implements HAClient {',
         '/**\n * 自动切换 HA 从节点客户端：握手协商 SyncStateSet、epoch 与异步 Learner 角色后同步数据。\n */\npublic class AutoSwitchHAClient extends ServiceThread implements HAClient {'),
        ('    private static final int READ_MAX_BUFFER_SIZE = 1024 * 1024 * 4;',
         '    /** 读缓冲上限（4MB）。 */\n    private static final int READ_MAX_BUFFER_SIZE = 1024 * 1024 * 4;'),
        ('/**\n     * last time that slave reports offset to master.\n     */',
         '/**\n * Slave 最近一次向 Master 上报 offset 的时间。\n\n */'),
        ('/**\n     * last time that slave reads date from master.\n     */',
         '/**\n * Slave 最近一次从 Master 读取数据的时间。\n\n */'),
        ('    private final AtomicReference<String> masterHaAddress =',
         '    /** Master HA 地址（原子引用）。 */\n    private final AtomicReference<String> masterHaAddress ='),
        ('    public void changeCurrentState(',
         '    /** 切换 HA 连接状态。 */\n    public void changeCurrentState('),
        ('        // Shutdown thread firstly',
         '        /** 先关闭 HA 线程 */'),
        ('    public String getServiceName(',
         '    /** 返回后台线程服务名。 */\n    public String getServiceName('),
        ('        // IsAsyncLearner role',
         '        /** 是否为 AsyncLearner 角色 */'),
        ('        // IsSyncFromLastFile',
         '        /** 是否从最后一个文件同步 */'),
        ('        // Original state',
         '        /** 原始 HA 状态 */'),
        ('    public void shutdown(',
         '    /** 关闭并释放资源。 */\n    public void shutdown('),
        ('    public void run(',
         '    /** 后台线程主循环。 */\n    public void run('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAConnection.java': [
        ('    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('public class AutoSwitchHAConnection implements HAConnection {',
         '/**\n * 自动切换 HA 主节点连接：处理握手、传输 CommitLog 并维护 SyncStateSet 同步状态。\n */\npublic class AutoSwitchHAConnection implements HAConnection {'),
        ('                                // Flag(isAsyncLearner role)',
         '                                /** 标志：AsyncLearner 角色 */'),
        ('                                // Flag(isSyncFromLastFile)',
         '                                /** 标志：是否从末文件同步 */'),
        ('    private volatile HAConnectionState currentState =',
         '    /** 当前 HA 连接状态。 */\n    private volatile HAConnectionState currentState ='),
        ('                                // SlaveBrokerId',
         '                                /** Slave Broker ID */'),
        ('            // Use -1 to stand for Long.max',
         '            /** 用 -1 表示 Long.MAX_VALUE */'),
        ('        protected boolean transferData(',
         '        /** 传输 CommitLog 数据。 */\n        protected boolean transferData('),
        ('        public String getServiceName(',
         '        /** 返回后台线程服务名。 */\n        public String getServiceName('),
        ('\n    public void changeCurrentState(',
         '\n    /** 切换 HA 连接状态。 */\n\n    public void changeCurrentState('),
        ('\n                // Build Header',
         '\n                /** 构建传输头 */'),
        ('\n            // Write Header',
         '\n            /** 写入传输头 */'),
        ('            // Build Header',
         '            /** 构建传输头 */'),
        ('            // Write Header',
         '            /** 写入传输头 */'),
        ('\n            // Write Body',
         '\n            /** 写入消息体 */'),
        ('    public void shutdown(',
         '    /** 关闭并释放资源。 */\n    public void shutdown('),
        ('        public void run(',
         '        /** 后台线程主循环。 */\n        public void run('),
        ('    public void start(',
         '    /** 启动服务。 */\n    public void start('),
        ('    public void close(',
         '    /** 关闭连接。 */\n    public void close('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/ha/autoswitch/AutoSwitchHAService.java': [
        ('/**\n     * Check and maybe add the slave to SyncStateSet. A slave will be added to SyncStateSet if its slaveMaxOffset >=\n     * current confirmOffset, and it is caught up to an offset within the current leader epoch.\n     */',
         '/**\n * 检查并可能将 Slave 加入 SyncStateSet：slaveMaxOffset 追平 confirmOffset 时加入。\n\n */'),
        ('/**\n     * Check and maybe shrink the SyncStateSet.\n     * A slave will be removed from SyncStateSet if (curTime - HaConnection.lastCaughtUpTime) > option(haMaxTimeSlaveNotCatchup)\n     */',
         '/**\n * 检查并可能收缩 SyncStateSet：Slave 长时间未上报 offset 则移除。\n\n */'),
        ('    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('/**\n * SwitchAble ha service, support switch role to master or slave.\n */',
         '/**\n * 可切换角色的 HA 服务：支持 Master/Slave 角色切换与 SyncStateSet 管理。\n\n */'),
        ('public class AutoSwitchHAService extends DefaultHAService {',
         '/**\n * 可切换角色的 HA 服务：管理 SyncStateSet、epoch 文件、主从 truncate 与 HA 连接生命周期。\n */\npublic class AutoSwitchHAService extends DefaultHAService {'),
        ('\n        // Append new epoch to epochFile',
         '\n        /** 向 epoch 文件追加新 epoch */'),
        ('        // Append new epoch to epochFile',
         '        /** 向 epoch 文件追加新 epoch */'),
        ('        public String getServiceName(',
         '        /** 返回后台线程服务名。 */\n        public String getServiceName('),
        ('        // Stop ha client if needed',
         '        /** 必要时停止 HA Client */'),
        ('\n        // Truncate dirty file',
         '\n        /** 截断脏文件 */'),
        ('    public void shutdown(',
         '    /** 关闭并释放资源。 */\n    public void shutdown('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/index/IndexService.java': [
        ('/**\n     * Retries to get or create index file.\n     *\n     * @return {@link IndexFile} or null on failure.\n     */',
         '/**\n * 重试获取或创建 IndexFile。\n * @return {@link IndexFile} 或失败时 null\n\n */'),
        ('    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger LOGGER = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('/**\n     * Maximum times to attempt index file creation.\n     */',
         '/**\n * 创建 IndexFile 的最大重试次数。\n\n */'),
        ('public class IndexService implements CommitLogDispatchStore {',
         '/**\n * 消息索引服务：按 key 维护 IndexFile 链表，支持异步/同步建索引与过期清理。\n */\npublic class IndexService implements CommitLogDispatchStore {'),
        ('                    public void run(',
         '                    /** 后台线程主循环。 */\n                    public void run('),
        ('\n    public void deleteExpiredFile(',
         '\n    /** 删除过期索引文件。 */\n\n    public void deleteExpiredFile('),
        ('            // ascending order',
         '            /** 按时间升序 */'),
        ('\n    public void buildIndex(',
         '\n    /** 构建消息索引。 */\n\n    public void buildIndex('),
        ('\n    public void shutdown(',
         '\n    /** 关闭并释放资源。 */\n\n    public void shutdown('),
        ('\n    public boolean load(',
         '\n    /** 加载持久化数据。 */\n\n    public boolean load('),
        ('\n    public void destroy(',
         '\n    /** 销毁索引服务。 */\n\n    public void destroy('),
        ('\n    public void flush(',
         '\n    /** 刷盘。 */\n\n    public void flush('),
        ('\n    public void start(',
         '\n    /** 启动服务。 */\n\n    public void start('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/kv/CompactionLog.java': [
        ('    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('        // split bytebuffer to avoid encode message again',
         '        /** 拆分 ByteBuffer 避免重复编码 */'),
        ('\n        public void shutdown(',
         '\n        /** 关闭并释放资源。 */\n\n        public void shutdown('),
        ('public class CompactionLog {',
         '/**\n * Compaction 日志：对 KV/Compaction Topic 消息进行合并压缩，维护 Compaction CQ 与 offset 映射。\n */\npublic class CompactionLog {'),
        ('\n        // merge files',
         '\n        /** 合并 Compaction 文件 */'),
        ('\n    public void flush(',
         '\n    /** 刷盘。 */\n\n    public void flush('),
        ('\n    public void load(',
         '\n    /** 加载持久化数据。 */\n\n    public void load('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/logfile/DefaultMappedFile.java': [
        ('/**\n     * If this mapped file belongs to consume queue, this field stores store-timestamp of first message referenced by\n     * this logical queue.\n     */',
         '/**\n * CQ 映射文件时，存储首条引用消息的 store-timestamp。\n\n */'),
        ('/**\n     * Message will put to here first, and then reput to FileChannel if writeBuffer is not null.\n     */',
         '/**\n * 消息先写入 writeBuffer，非空时再 reput 到 FileChannel。\n\n */'),
        ('/**\n     * Configuration flag to use RandomAccessFile instead of MappedByteBuffer for writing\n     */',
         '/**\n * 写路径使用 RandomAccessFile 而非 MappedByteBuffer 的配置开关。\n\n */'),
        ('        // On the windows platform and openjdk 11 method isLoaded0 always returns false.',
         '        /** Windows + OpenJDK11 下 isLoaded0 恒为 false */'),
        ('                // Use MappedByteBuffer for both reading and writing (default behavior)',
         '                /** 读写均使用 MappedByteBuffer（默认） */'),
        ('                // Still create MappedByteBuffer for reading operations',
         '                /** 读路径仍创建 MappedByteBuffer */'),
        ('public class DefaultMappedFile extends AbstractMappedFile {',
         '/**\n * 默认 MappedFile 实现：mmap 或 FileChannel 读写 CommitLog/CQ 映射文件，支持 TransientStorePool。\n */\npublic class DefaultMappedFile extends AbstractMappedFile {'),
        ('    public SelectMappedBufferResult selectMappedBuffer(',
         '    /** 选择映射缓冲区。 */\n    public SelectMappedBufferResult selectMappedBuffer('),
        ('\n    public AppendMessageResult appendMessage(',
         '\n    /** 追加消息。 */\n\n    public AppendMessageResult appendMessage('),
        ('    public AppendMessageResult appendMessage(',
         '    /** 追加消息。 */\n    public AppendMessageResult appendMessage('),
        ('    public long getFileFromOffset(',
         '    /** 按 offset 获取文件起始 offset。 */\n    public long getFileFromOffset('),
        ('    public boolean appendMessage(',
         '    /** 追加消息。 */\n    public boolean appendMessage('),
        ('    public boolean renameTo(',
         '    /** 重命名映射文件。 */\n    public boolean renameTo('),
        ('\n    public boolean getData(',
         '\n    /** 读取映射文件数据。 */\n\n    public boolean getData('),
        ('    public boolean destroy(',
         '    /** 销毁索引服务。 */\n    public boolean destroy('),
        ('    public boolean swapMap(',
         '    /** 交换 mmap 映射。 */\n    public boolean swapMap('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/plugin/AbstractPluginMessageStore.java': [
        ('    public CompletableFuture<GetMessageResult> getMessageAsync(String group, String topic,\n        int queueId, long offset, int maxMsgNums, int maxTotalMsgSize,\n        MessageFilter messageFilter)',
         '    /** 委托 next 执行 getMessageAsync。 */\n    public CompletableFuture<GetMessageResult> getMessageAsync(String group, String topic,\n        int queueId, long offset, int maxMsgNums, int maxTotalMsgSize,\n        MessageFilter messageFilter)'),
        ('    public CompletableFuture<GetMessageResult> getMessageAsync(String group, String topic,\n        int queueId, long offset, int maxMsgNums, MessageFilter messageFilter)',
         '    /** 委托 next 执行 getMessageAsync。 */\n    public CompletableFuture<GetMessageResult> getMessageAsync(String group, String topic,\n        int queueId, long offset, int maxMsgNums, MessageFilter messageFilter)'),
        ('    public GetMessageResult getMessage(String group, String topic, int queueId, long offset,\n        int maxMsgNums, int maxTotalMsgSize, MessageFilter messageFilter)',
         '    /** 委托 next 执行 getMessage。 */\n    public GetMessageResult getMessage(String group, String topic, int queueId, long offset,\n        int maxMsgNums, int maxTotalMsgSize, MessageFilter messageFilter)'),
        ('    public GetMessageResult getMessage(String group, String topic, int queueId, long offset,\n        int maxMsgNums, final MessageFilter messageFilter)',
         '    /** 委托 next 执行 getMessage。 */\n    public GetMessageResult getMessage(String group, String topic, int queueId, long offset,\n        int maxMsgNums, final MessageFilter messageFilter)'),
        ('    public CompletableFuture<Long> getMessageStoreTimeStampAsync(String topic, int queueId,\n        long consumeQueueOffset)',
         '    /** 委托 next 执行 getMessageStoreTimeStampAsync。 */\n    public CompletableFuture<Long> getMessageStoreTimeStampAsync(String topic, int queueId,\n        long consumeQueueOffset)'),
        ('    public long getOffsetInQueueByTime(String topic, int queueId, long timestamp, BoundaryType boundaryType)',
         '    /** 委托 next 执行 getOffsetInQueueByTime。 */\n    public long getOffsetInQueueByTime(String topic, int queueId, long timestamp, BoundaryType boundaryType)'),
        ('    public long getCommitLogOffsetInQueue(String topic, int queueId, long consumeQueueOffset)',
         '    /** 委托 next 执行 getCommitLogOffsetInQueue。 */\n    public long getCommitLogOffsetInQueue(String topic, int queueId, long consumeQueueOffset)'),
        ('    public long getMessageStoreTimeStamp(String topic, int queueId, long consumeQueueOffset)',
         '    /** 委托 next 执行 getMessageStoreTimeStamp。 */\n    public long getMessageStoreTimeStamp(String topic, int queueId, long consumeQueueOffset)'),
        ('    public CompletableFuture<Long> getEarliestMessageTimeAsync(String topic, int queueId)',
         '    /** 委托 next 执行 getEarliestMessageTimeAsync。 */\n    public CompletableFuture<Long> getEarliestMessageTimeAsync(String topic, int queueId)'),
        ('    public List<SelectMappedBufferResult> getBulkCommitLogData(long offset, int size)',
         '    /** 委托 next 执行 getBulkCommitLogData。 */\n    public List<SelectMappedBufferResult> getBulkCommitLogData(long offset, int size)'),
        ('    public long getMaxOffsetInQueue(String topic, int queueId, boolean committed)',
         '    /** 委托 next 执行 getMaxOffsetInQueue。 */\n    public long getMaxOffsetInQueue(String topic, int queueId, boolean committed)'),
        ('    public long getOffsetInQueueByTime(String topic, int queueId, long timestamp)',
         '    /** 委托 next 执行 getOffsetInQueueByTime。 */\n    public long getOffsetInQueueByTime(String topic, int queueId, long timestamp)'),
        ('    public ConsumeQueueInterface getConsumeQueue(String topic, int queueId)',
         '    /** 委托 next 执行 getConsumeQueue。 */\n    public ConsumeQueueInterface getConsumeQueue(String topic, int queueId)'),
        ('public abstract class AbstractPluginMessageStore implements MessageStore {',
         '/**\n * MessageStore 插件抽象基类：将接口调用委托给 next 链，便于扩展存储能力。\n */\npublic abstract class AbstractPluginMessageStore implements MessageStore {'),
        ('    public boolean getData(long offset, int size, ByteBuffer byteBuffer)',
         '    /** 委托 next 执行 getData。 */\n    public boolean getData(long offset, int size, ByteBuffer byteBuffer)'),
        ('    public List<Pair<InstrumentSelector, ViewBuilder>> getMetricsView()',
         '    /** 委托 next 执行 getMetricsView。 */\n    public List<Pair<InstrumentSelector, ViewBuilder>> getMetricsView()'),
        ('    public AllocateMappedFileService getAllocateMappedFileService()',
         '    /** 委托 next 执行 getAllocateMappedFileService。 */\n    public AllocateMappedFileService getAllocateMappedFileService()'),
        ('    public long getEarliestMessageTime(String topic, int queueId)',
         '    /** 委托 next 执行 getEarliestMessageTime。 */\n    public long getEarliestMessageTime(String topic, int queueId)'),
        ('    public long getMessageTotalInQueue(String topic, int queueId)',
         '    /** 委托 next 执行 getMessageTotalInQueue。 */\n    public long getMessageTotalInQueue(String topic, int queueId)'),
        ('    public SelectMappedBufferResult getCommitLogData(long offset)',
         '    /** 委托 next 执行 getCommitLogData。 */\n    public SelectMappedBufferResult getCommitLogData(long offset)'),
        ('    public long getMaxOffsetInQueue(String topic, int queueId)',
         '    /** 委托 next 执行 getMaxOffsetInQueue。 */\n    public long getMaxOffsetInQueue(String topic, int queueId)'),
        ('    public long getMinOffsetInQueue(String topic, int queueId)',
         '    /** 委托 next 执行 getMinOffsetInQueue。 */\n    public long getMinOffsetInQueue(String topic, int queueId)'),
        ('    public LinkedList<CommitLogDispatcher> getDispatcherList()',
         '    /** 委托 next 执行 getDispatcherList。 */\n    public LinkedList<CommitLogDispatcher> getDispatcherList()'),
        ('    public SendMessageBackHook getSendMessageBackHook()',
         '    /** 委托 next 执行 getSendMessageBackHook。 */\n    public SendMessageBackHook getSendMessageBackHook()'),
        ('    public List<PutMessageHook> getPutMessageHookList()',
         '    /** 委托 next 执行 getPutMessageHookList。 */\n    public List<PutMessageHook> getPutMessageHookList()'),
        ('    public StoreMetricsManager getStoreMetricsManager()',
         '    /** 委托 next 执行 getStoreMetricsManager。 */\n    public StoreMetricsManager getStoreMetricsManager()'),
        ('    public boolean getLastMappedFile(long startOffset)',
         '    /** 委托 next 执行 getLastMappedFile。 */\n    public boolean getLastMappedFile(long startOffset)'),
        ('    public BrokerStatsManager getBrokerStatsManager()',
         '    /** 委托 next 执行 getBrokerStatsManager。 */\n    public BrokerStatsManager getBrokerStatsManager()'),
        ('    public MessageStoreConfig getMessageStoreConfig()',
         '    /** 委托 next 执行 getMessageStoreConfig。 */\n    public MessageStoreConfig getMessageStoreConfig()'),
        ('    public TransientStorePool getTransientStorePool()',
         '    /** 委托 next 执行 getTransientStorePool。 */\n    public TransientStorePool getTransientStorePool()'),
        ('    public ConsumeQueueStoreInterface getQueueStore()',
         '    /** 委托 next 执行 getQueueStore。 */\n    public ConsumeQueueStoreInterface getQueueStore()'),
        ('    public MessageStoreStateMachine getStateMachine()',
         '    /** 委托 next 执行 getStateMachine。 */\n    public MessageStoreStateMachine getStateMachine()'),
        ('    public HashMap<String, String> getRuntimeInfo()',
         '    /** 委托 next 执行 getRuntimeInfo。 */\n    public HashMap<String, String> getRuntimeInfo()'),
        ('    public StoreStatsService getStoreStatsService()',
         '    /** 委托 next 执行 getStoreStatsService。 */\n    public StoreStatsService getStoreStatsService()'),
        ('    public TimerMessageStore getTimerMessageStore()',
         '    /** 委托 next 执行 getTimerMessageStore。 */\n    public TimerMessageStore getTimerMessageStore()'),
        ('    public long getTimingMessageCount(String topic)',
         '    /** 委托 next 执行 getTimingMessageCount。 */\n    public long getTimingMessageCount(String topic)'),
        ('    public boolean isTransientStorePoolDeficient()',
         '    /** 委托 next 执行 isTransientStorePoolDeficient。 */\n    public boolean isTransientStorePoolDeficient()'),
        ('    public MessageStore getMasterStoreInProcess()',
         '    /** 委托 next 执行 getMasterStoreInProcess。 */\n    public MessageStore getMasterStoreInProcess()'),
        ('    public boolean isOffsetAligned(long offset)',
         '    /** 委托 next 执行 isOffsetAligned。 */\n    public boolean isOffsetAligned(long offset)'),
        ('    public StoreCheckpoint getStoreCheckpoint()',
         '    /** 委托 next 执行 getStoreCheckpoint。 */\n    public StoreCheckpoint getStoreCheckpoint()'),
        ('    public HARuntimeInfo getHARuntimeInfo()',
         '    /** 委托 next 执行 getHARuntimeInfo。 */\n    public HARuntimeInfo getHARuntimeInfo()'),
        ('    public int getAliveReplicaNumInGroup()',
         '    /** 委托 next 执行 getAliveReplicaNumInGroup。 */\n    public int getAliveReplicaNumInGroup()'),
        ('    public RunningFlags getRunningFlags()',
         '    /** 委托 next 执行 getRunningFlags。 */\n    public RunningFlags getRunningFlags()'),
        ('    public long getEarliestMessageTime()',
         '    /** 委托 next 执行 getEarliestMessageTime。 */\n    public long getEarliestMessageTime()'),
        ('    public long getStateMachineVersion()',
         '    /** 委托 next 执行 getStateMachineVersion。 */\n    public long getStateMachineVersion()'),
        ('    public long getMasterFlushedOffset()',
         '    /** 委托 next 执行 getMasterFlushedOffset。 */\n    public long getMasterFlushedOffset()'),
        ('    public long getBrokerInitMaxOffset()',
         '    /** 委托 next 执行 getBrokerInitMaxOffset。 */\n    public long getBrokerInitMaxOffset()'),
        ('    public SystemClock getSystemClock()',
         '    /** 委托 next 执行 getSystemClock。 */\n    public SystemClock getSystemClock()'),
        ('    public long getLastFileFromOffset()',
         '    /** 委托 next 执行 getLastFileFromOffset。 */\n    public long getLastFileFromOffset()'),
        ('    public boolean isMappedFilesEmpty()',
         '    /** 委托 next 执行 isMappedFilesEmpty。 */\n    public boolean isMappedFilesEmpty()'),
        ('    public boolean isOSPageCacheBusy()',
         '    /** 委托 next 执行 isOSPageCacheBusy。 */\n    public boolean isOSPageCacheBusy()'),
        ('    public String getRunningDataInfo()',
         '    /** 委托 next 执行 getRunningDataInfo。 */\n    public String getRunningDataInfo()'),
        ('    public boolean isSyncDiskFlush()',
         '    /** 委托 next 执行 isSyncDiskFlush。 */\n    public boolean isSyncDiskFlush()'),
        ('    public HAService getHaService()',
         '    /** 委托 next 执行 getHaService。 */\n    public HAService getHaService()'),
        ('    public CommitLog getCommitLog()',
         '    /** 委托 next 执行 getCommitLog。 */\n    public CommitLog getCommitLog()'),
        ('    public long getConfirmOffset()',
         '    /** 委托 next 执行 getConfirmOffset。 */\n    public long getConfirmOffset()'),
        ('    public long getMaxPhyOffset()',
         '    /** 委托 next 执行 getMaxPhyOffset。 */\n    public long getMaxPhyOffset()'),
        ('    public long getMinPhyOffset()',
         '    /** 委托 next 执行 getMinPhyOffset。 */\n    public long getMinPhyOffset()'),
        ('    public long getFlushedWhere()',
         '    /** 委托 next 执行 getFlushedWhere。 */\n    public long getFlushedWhere()'),
        ('    public boolean isSyncMaster()',
         '    /** 委托 next 执行 isSyncMaster。 */\n    public boolean isSyncMaster()'),
        ('    public MessageStore getNext()',
         '    /** 委托 next 执行 getNext。 */\n    public MessageStore getNext()'),
        ('    protected MessageStore next;',
         '    /** 插件链下一层 MessageStore。 */\n    protected MessageStore next;'),
        ('    public boolean isShutdown()',
         '    /** 委托 next 执行 isShutdown。 */\n    public boolean isShutdown()'),
        ('    public boolean getData(',
         '    /** 读取映射文件数据。 */\n    public boolean getData('),
        ('    public void shutdown()',
         '    /** 委托 next 执行 shutdown。 */\n    public void shutdown()'),
        ('    public void shutdown(',
         '    /** 关闭并释放资源。 */\n    public void shutdown('),
        ('    public boolean load()',
         '    /** 委托 next 执行 load。 */\n    public boolean load()'),
        ('    public void destroy()',
         '    /** 委托 next 执行 destroy。 */\n    public void destroy()'),
        ('    public boolean load(',
         '    /** 加载持久化数据。 */\n    public boolean load('),
        ('    public void destroy(',
         '    /** 销毁索引服务。 */\n    public void destroy('),
        ('    public void start()',
         '    /** 委托 next 执行 start。 */\n    public void start()'),
        ('    public void start(',
         '    /** 启动服务。 */\n    public void start('),
        ('    public long flush(',
         '    /** 刷盘。 */\n    public long flush('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/queue/BatchConsumeQueue.java': [
        ("/**\n     * BatchConsumeQueue's store unit. Format:\n     * <pre>\n     * ┌─────────────────────────┬───────────┬────────────┬──────────┬─────────────┬─────────┬───────────────┬─────────┐\n     * │CommitLog Physical Offset│ Body Size │Tag HashCode│Store time│msgBaseOffset│batchSize│compactedOffset│reserved │\n     * │        (8 Bytes)        │ (4 Bytes) │ (8 Bytes)  │(8 Bytes) │(8 Bytes)    │(2 Bytes)│   (4 Bytes)   │(4 Bytes)│\n     * ├─────────────────────────┴───────────┴────────────┴──────────┴─────────────┴─────────┴───────────────┴─────────┤\n     * │                                                  Store Unit                                                   │\n     * │                                                                                                               │\n     * </pre>\n     * BatchConsumeQueue's store unit. Size:\n     * CommitLog Physical Offset(8) + Body Size(4) + Tag HashCode(8) + Store time(8) +\n     * msgBaseOffset(8) + batchSize(2) + compactedOffset(4) + reserved(4)= 46 Bytes\n     */",
         '/**\n * BatchConsumeQueue 存储单元格式说明。\n\n */'),
        ('/**\n     * Gets SelectMappedBufferResult by batch-message offset\n     * Node: the caller is responsible for the release of SelectMappedBufferResult\n     * @param msgOffset\n     * @return SelectMappedBufferResult\n     */',
         '/**\n * 按批量消息 offset 获取 SelectMappedBufferResult；调用方负责 release。\n\n */'),
        ('            // the timestamp is too small. so we decide to result first BCQ file.',
         '            /** 时间戳过小，返回第一个 BCQ 文件 */'),
        ('public class BatchConsumeQueue implements ConsumeQueueInterface {',
         '/**\n * 批量消费队列（BCQ）：每条 CQ 单元对应一批消息的 CommitLog 物理范围，提升批量消费效率。\n */\npublic class BatchConsumeQueue implements ConsumeQueueInterface {'),
        ('            // the offset is too small.',
         '            /** offset 过小 */'),
        ('    public int deleteExpiredFile(',
         '    /** 删除过期索引文件。 */\n    public int deleteExpiredFile('),
        ('        // iterate all BCQ files',
         '        /** 遍历全部 BCQ 文件 */'),
        ('        public void release(',
         '        /** 释放引用计数。 */\n        public void release('),
        ('    public boolean shutdown(',
         '    /** 关闭并释放资源。 */\n    public boolean shutdown('),
        ('    public boolean flush(',
         '    /** 刷盘。 */\n    public boolean flush('),
        ('    public boolean load(',
         '    /** 加载持久化数据。 */\n    public boolean load('),
        ('    public void recover(',
         '    /** 恢复 CompactionLog。 */\n    public void recover('),
        ('    public void destroy(',
         '    /** 销毁索引服务。 */\n    public void destroy('),
        ('    public void swapMap(',
         '    /** 交换 mmap 映射。 */\n    public void swapMap('),
    ],
    'store/src/main/java/org/apache/rocketmq/store/queue/CombineConsumeQueueStore.java': [
        ('    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);',
         '    /** 存储模块日志。 */\n    private static final Logger log = LoggerFactory.getLogger(LoggerName.STORE_LOGGER_NAME);'),
        ('public class CombineConsumeQueueStore implements ConsumeQueueStoreInterface {',
         '/**\n * 组合消费队列存储：按 Topic 类型在文件型 CQ 与 RocksDB CQ 之间路由读写。\n */\npublic class CombineConsumeQueueStore implements ConsumeQueueStoreInterface {'),
        ('    // consume queue store for assign offset and increase offset.',
         '    /** 分配/递增 offset 的 CQ 存储 */'),
        ('        // make sure assignOffsetStore can be fully recovered',
         '        /** 确保 assignOffsetStore 可完整恢复 */'),
        ('\n    // current read consume queue store.',
         '\n    /** 当前读 CQ 存储 */'),
        ('\n    // Inner consume queue store.',
         '\n    /** 内部文件型 CQ 存储 */'),
        ('    public boolean shutdown(',
         '    /** 关闭并释放资源。 */\n    public boolean shutdown('),
        ('    public boolean load(',
         '    /** 加载持久化数据。 */\n    public boolean load('),
        ('    public void recover(',
         '    /** 恢复 CompactionLog。 */\n    public void recover('),
        ('    public void destroy(',
         '    /** 销毁索引服务。 */\n    public void destroy('),
        ('    public void start(',
         '    /** 启动服务。 */\n    public void start('),
        ('    public void flush(',
         '    /** 刷盘。 */\n    public void flush('),
    ],
}
