"""Wave 14b medium replacements."""
MEDIUM_REPLACEMENTS = {
"BeanValidationBeanRegistrationAotProcessor.java": [
("AOT {@code BeanRegistrationAotProcessor} that adds additional hints\n * required for {@link ConstraintValidator}s.","AOT {@code BeanRegistrationAotProcessor}，为 {@link ConstraintValidator} 添加额外提示。"),
("Inner class to avoid a hard dependency on the Bean Validation API at runtime.","内部类，避免运行时对 Bean Validation API 的硬依赖。"),
],
"MethodValidationPostProcessor.java": [
("A convenient {@link BeanPostProcessor} implementation that delegates to a\n * JSR-303 provider for performing method-level validation on annotated methods.","便捷的 {@link BeanPostProcessor} 实现，委托 JSR-303 提供者\n * 对带注解方法执行方法级校验。"),
("Applicable methods have JSR-303 constraint annotations on their parameters\n * and/or on their return value (in the latter case specified at the method level,\n * typically as inline annotation), for example:","适用方法的参数和/或返回值（后者在方法级指定，通常为内联注解）\n * 带有 JSR-303 约束注解，例如："),
("In case of validation errors, the interceptor can raise\n * {@link ConstraintViolationException}, or adapt the violations to\n * {@link MethodValidationResult} and raise {@link MethodValidationException}.","校验出错时，拦截器可抛出 {@link ConstraintViolationException}，\n * 或将违例适配为 {@link MethodValidationResult} 并抛出 {@link MethodValidationException}。"),
("Target classes with such annotated methods need to be annotated with Spring's\n * {@link Validated} annotation at the type level, for their methods to be searched for\n * inline constraint annotations. Validation groups can be specified through {@code @Validated}\n * as well. By default, JSR-303 will validate against its default group only.","含此类注解方法的目标类需在类型级标注 Spring 的 {@link Validated} 注解，\n * 以便搜索内联约束注解。也可通过 {@code @Validated} 指定校验分组。\n * 默认情况下，JSR-303 仅针对默认分组校验。"),
("Set the 'validated' annotation type.\n\t * The default validated annotation type is the {@link Validated} annotation.\n\t * <p>This setter property exists so that developers can provide their own\n\t * (non-Spring-specific) annotation type to indicate that a class is supposed\n\t * to be validated in the sense of applying method validation.\n\t * @param validatedAnnotationType the desired annotation type","设置 \"validated\" 注解类型。\n\t * 默认 validated 注解类型为 {@link Validated} 注解。\n\t * <p>此 setter 属性使开发者可提供自己的（非 Spring 专用）注解类型，\n\t * 表示类应进行方法校验意义上的校验。\n\t * @param validatedAnnotationType 所需的注解类型"),
("Set the JSR-303 ValidatorFactory to delegate to for validating methods,\n\t * using its default Validator.\n\t * <p>Default is the default ValidatorFactory's default Validator.","设置用于校验方法的 JSR-303 ValidatorFactory 委托对象，\n\t * 使用其默认 Validator。\n\t * <p>默认为默认 ValidatorFactory 的默认 Validator。"),
("Set the JSR-303 Validator to delegate to for validating methods.\n\t * <p>Default is the default ValidatorFactory's default Validator.","设置用于校验方法的 JSR-303 Validator 委托对象。\n\t * <p>默认为默认 ValidatorFactory 的默认 Validator。"),
("Set a lazily initialized Validator to delegate to for validating methods.","设置用于校验方法的延迟初始化 Validator 委托对象。"),
("Whether to adapt {@link ConstraintViolation}s to {@link MethodValidationResult}.\n\t * <p>By default {@code false} in which case\n\t * {@link jakarta.validation.ConstraintViolationException} is raised in case of\n\t * violations. When set to {@code true}, {@link MethodValidationException}\n\t * is raised instead with the method validation results.","是否将 {@link ConstraintViolation} 适配为 {@link MethodValidationResult}。\n\t * <p>默认为 {@code false}，此时违例时抛出\n\t * {@link jakarta.validation.ConstraintViolationException}。\n\t * 设为 {@code true} 时，改为抛出带方法校验结果的 {@link MethodValidationException}。"),
("Create AOP advice for method validation purposes, to be applied\n\t * with a pointcut for the specified 'validated' annotation.\n\t * @param validator a Supplier for the Validator to use\n\t * @return the interceptor to use (typically, but not necessarily,\n\t * a {@link MethodValidationInterceptor} or subclass thereof)","创建用于方法校验的 AOP 通知，与指定 \"validated\" 注解的切点配合应用。\n\t * @param validator 要使用的 Validator 的 Supplier\n\t * @return 要使用的拦截器（通常但不一定是 {@link MethodValidationInterceptor} 或其子类）"),
],
"MethodValidator.java": [
("Contract to apply method validation and handle the results.\n * Exposes methods that return {@link MethodValidationResult}, and methods that\n * handle the results, by default raising {@link MethodValidationException}.","应用方法校验并处理结果的契约。\n * 暴露返回 {@link MethodValidationResult} 的方法，\n * 以及处理结果的方法，默认抛出 {@link MethodValidationException}。"),
("Determine the applicable validation groups. By default, obtained from an\n\t * {@link org.springframework.validation.annotation.Validated @Validated}\n\t * annotation on the method, or on the class level.\n\t * @param target the target Object\n\t * @param method the target method\n\t * @return the applicable validation groups as a {@code Class} array\n\t * @deprecated in favor of","确定适用的校验分组。默认从方法或类级的\n\t * {@link org.springframework.validation.annotation.Validated @Validated}\n\t * 注解获取。\n\t * @param target 目标对象\n\t * @param method 目标方法\n\t * @return 适用的校验分组，以 {@code Class} 数组形式\n\t * @deprecated 推荐使用"),
("Validate the given method arguments and return validation results.\n\t * @param target the target Object\n\t * @param method the target method\n\t * @param parameters the parameters, if already created and available\n\t * @param arguments the candidate argument values to validate","校验给定方法参数并返回校验结果。\n\t * @param target 目标对象\n\t * @param method 目标方法\n\t * @param parameters 参数（若已创建且可用）\n\t * @param arguments 要校验的候选参数值"),
("@return the result of validation","@return 校验结果"),
("Delegate to {@link #validateArguments} and handle the validation result,\n\t * by default raising {@link MethodValidationException} in case of errors.\n\t * Implementations may provide alternative handling, for example, injecting\n\t * {@link org.springframework.validation.Errors} into the method.\n\t * @throws MethodValidationException in case of unhandled errors.","委托 {@link #validateArguments} 并处理校验结果，\n\t * 默认在出错时抛出 {@link MethodValidationException}。\n\t * 实现可提供替代处理方式，例如将 {@link org.springframework.validation.Errors} 注入方法。\n\t * @throws MethodValidationException 存在未处理错误时"),
("Validate the given return value and return validation results.\n\t * @param target the target Object\n\t * @param method the target method\n\t * @param returnType the return parameter, if already created and available\n\t * @param returnValue the return value to validate","校验给定返回值并返回校验结果。\n\t * @param target 目标对象\n\t * @param method 目标方法\n\t * @param returnType 返回参数（若已创建且可用）\n\t * @param returnValue 要校验的返回值"),
("Delegate to {@link #validateReturnValue} and handle the validation result,\n\t * by default raising {@link MethodValidationException} in case of errors.\n\t * Implementations may provide alternative handling.\n\t * @throws MethodValidationException in case of unhandled errors.","委托 {@link #validateReturnValue} 并处理校验结果，\n\t * 默认在出错时抛出 {@link MethodValidationException}。\n\t * 实现可提供替代处理方式。\n\t * @throws MethodValidationException 存在未处理错误时"),
],
"ParameterErrors.java": [
("Extension of {@link ParameterValidationResult} created for Object method\n * parameters or return values with nested errors on their properties.","{@link ParameterValidationResult} 的扩展，\n * 为属性上存在嵌套错误的 Object 方法参数或返回值创建。"),
("The base class method {@link #getResolvableErrors()} returns\n * {@link Errors#getAllErrors()}, but this subclass provides access to the same\n * as {@link FieldError}s.","基类方法 {@link #getResolvableErrors()} 返回\n * {@link Errors#getAllErrors()}，但本子类以 {@link FieldError} 形式提供相同访问。"),
("Create a {@code ParameterErrors}.","创建 {@code ParameterErrors}。"),
],
}
