"""Chinese JavaDoc replacements for RocketMQ wave44b tools [15:30]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetadataInRocksDBCommand.java': [
        ('public class ExportMetadataInRocksDBCommand implements SubCommand {',
         '/**\n * exportMetadataInRocksDB 子命令：从本地 RocksDB 元数据目录导出 Topic 或订阅组 KV 配置。\n */\npublic class ExportMetadataInRocksDBCommand implements SubCommand {'),
        ('    private static final String TOPICS_JSON_CONFIG = "topics";',
         '    /** Topic 配置在 RocksDB 中的子目录名。 */\n    private static final String TOPICS_JSON_CONFIG = "topics";'),
        ('    private static final String SUBSCRIPTION_GROUP_JSON_CONFIG = "subscriptionGroups";',
         '    /** 订阅组配置在 RocksDB 中的子目录名。 */\n    private static final String SUBSCRIPTION_GROUP_JSON_CONFIG = "subscriptionGroups";'),
        ('    public String commandName() {',
         '    /** 返回子命令名 exportMetadataInRocksDB。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option pathOption = new Option("p", "path", true,\n            "Absolute path for the metadata directory");',
         '        Option pathOption = new Option("p", "path", true,\n            "元数据根目录的绝对路径");'),
        ('        Option configTypeOption = new Option("t", "configType", true, "Name of kv config, e.g. " +\n            "topics/subscriptionGroups");',
         '        Option configTypeOption = new Option("t", "configType", true, "KV 配置类型，如 topics 或 subscriptionGroups");'),
        ('        Option jsonEnableOption = new Option("j", "jsonEnable", true,\n            "Json format enable, Default: false");',
         '        Option jsonEnableOption = new Option("j", "jsonEnable", true,\n            "是否以 JSON 格式输出，默认 false");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 打开只读 RocksDB 存储并按 configType 导出 KV 条目。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private static void handleExportMetadata(ConfigRocksDBStorage kvStore, String configType, boolean jsonEnable) {',
         '    /** 遍历 KV 存储，按 jsonEnable 选择 JSON 或逐行键值输出。 */\n    private static void handleExportMetadata(ConfigRocksDBStorage kvStore, String configType, boolean jsonEnable) {'),
        ('    private static void iterateKvStore(ConfigRocksDBStorage kvStore, BiConsumer<byte[], byte[]> biConsumer) {',
         '    /** 使用 {@link RocksIterator} 顺序遍历 RocksDB 全部键值对。 */\n    private static void iterateKvStore(ConfigRocksDBStorage kvStore, BiConsumer<byte[], byte[]> biConsumer) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetricsCommand.java': [
        ('public class ExportMetricsCommand implements SubCommand {',
         '/**\n * exportMetrics 子命令：采集集群各 Broker 运行时指标并写入 metrics.json。\n */\npublic class ExportMetricsCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 exportMetrics。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("c", "clusterName", true, "choose a cluster to export");',
         '        Option opt = new Option("c", "clusterName", true, "待导出指标的集群名");'),
        ('        opt = new Option("f", "filePath", true,\n            "export metrics.json path | default /tmp/rocketmq/export");',
         '        opt = new Option("f", "filePath", true,\n            "metrics.json 输出目录，默认 /tmp/rocketmq/export");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)',
         '    /** 遍历集群 Broker，汇总 TPS/磁盘/版本等指标并写入 JSON 文件。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)'),
        ('    private Map<String, Object> getRuntimeVersion(DefaultMQAdminExt defaultMQAdminExt,',
         '    /** 收集 Broker 与客户端版本信息。 */\n    private Map<String, Object> getRuntimeVersion(DefaultMQAdminExt defaultMQAdminExt,'),
        ('    private Map<String, Object> getRuntimeEnv(KVTable kvTable, Properties properties) {',
         '    /** 提取 CPU 线程数与内存等运行环境指标。 */\n    private Map<String, Object> getRuntimeEnv(KVTable kvTable, Properties properties) {'),
        ('    private Map<String, Object> getRuntimeQuota(KVTable kvTable, DefaultMQAdminExt defaultMQAdminExt, String brokerAddr,',
         '    /** 汇总磁盘占用、TPS、日消息量、Topic/Group 数量等配额指标。 */\n    private Map<String, Object> getRuntimeQuota(KVTable kvTable, DefaultMQAdminExt defaultMQAdminExt, String brokerAddr,'),
        ('    private void initTotalMap(Map<String, Double> totalTpsMap, Map<String, Long> totalOneDayNumMap) {',
         '    /** 初始化集群级 TPS 与日消息量累加器为零。 */\n    private void initTotalMap(Map<String, Double> totalTpsMap, Map<String, Long> totalOneDayNumMap) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportPopRecordCommand.java': [
        ('public class ExportPopRecordCommand implements SubCommand {',
         '/**\n * exportPopRecord 子命令：导出 Broker 上 POP 消费模式的消费记录。\n */\npublic class ExportPopRecordCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 exportPopRecord。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option(\n            "c", "clusterName", true, "choose one cluster to export");',
         '        Option opt = new Option(\n            "c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "choose one broker to export");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("d", "dryRun", true, "no actual changes will be made");',
         '        opt = new Option("d", "dryRun", true, "演练模式：为 false 时才实际导出");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 按 -b 单 Broker 或 -c 整集群调用 exportPopRecords 导出记录。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void export(DefaultMQAdminExt adminExt, String brokerAddr, String brokerName, boolean dryRun) {',
         '    /** 对单个 Broker 执行 POP 记录导出并打印结果。 */\n    private void export(DefaultMQAdminExt adminExt, String brokerAddr, String brokerName, boolean dryRun) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/ha/GetSyncStateSetSubCommand.java': [
        ('public class GetSyncStateSetSubCommand implements SubCommand {',
         '/**\n * getSyncStateSet 子命令：从 Controller 拉取 Broker 同步副本集（SyncStateSet）信息。\n */\npublic class GetSyncStateSetSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getSyncStateSet。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("a", "controllerAddress", true, "the address of controller");',
         '        Option opt = new Option("a", "controllerAddress", true, "Controller 地址（必填）");'),
        ('        opt = new Option("c", "clusterName", true, "which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerName", true, "which broker to fetch");',
         '        opt = new Option("b", "brokerName", true, "目标 Broker 名（与 -c 二选一）");'),
        ('        opt = new Option("i", "interval", true, "the interval(second) of get info");',
         '        opt = new Option("i", "interval", true, "轮询间隔（秒），指定后持续刷新输出");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 启动管理客户端，按 -i 决定是否循环拉取 SyncStateSet。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void innerExec(CommandLine commandLine, Options options,\n                           DefaultMQAdminExt defaultMQAdminExt) throws Exception {',
         '    /** 按 -b 或 -c 解析目标 Broker 并打印同步副本集。 */\n    private void innerExec(CommandLine commandLine, Options options,\n                           DefaultMQAdminExt defaultMQAdminExt) throws Exception {'),
        ('    private void printData(String controllerAddress, List<String> brokerNames,\n                           DefaultMQAdminExt defaultMQAdminExt) throws Exception {',
         '    /** 调用 getInSyncStateData 并格式化输出 InSync/NotInSync 副本列表。 */\n    private void printData(String controllerAddress, List<String> brokerNames,\n                           DefaultMQAdminExt defaultMQAdminExt) throws Exception {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/ha/HAStatusSubCommand.java': [
        ('public class HAStatusSubCommand implements SubCommand {',
         '/**\n * haStatus 子命令：查询 Broker 主从 HA 复制运行时状态与连接详情。\n */\npublic class HAStatusSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 haStatus。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("c", "clusterName", true, "which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "which broker to fetch");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("i", "interval", true, "the interval(second) of get info");',
         '        opt = new Option("i", "interval", true, "轮询间隔（秒），指定后持续刷新输出");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 启动管理客户端，按 -i 决定是否循环拉取 HA 状态。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void innerExec(CommandLine commandLine, Options options,\n        DefaultMQAdminExt defaultMQAdminExt) throws Exception {',
         '    /** 按 -b 单 Broker 或 -c 集群 Master 逐一打印 HA 状态。 */\n    private void innerExec(CommandLine commandLine, Options options,\n        DefaultMQAdminExt defaultMQAdminExt) throws Exception {'),
        ('    private void printStatus(String brokerAddr, DefaultMQAdminExt defaultMQAdminExt) throws Exception {',
         '    /** 区分 Master/Slave 角色，输出复制偏移、传输速率与同步状态。 */\n    private void printStatus(String brokerAddr, DefaultMQAdminExt defaultMQAdminExt) throws Exception {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/lite/GetBrokerLiteInfoSubCommand.java': [
        ('public class GetBrokerLiteInfoSubCommand implements SubCommand {',
         '/**\n * getBrokerLiteInfo 子命令：查询 Broker 上 LMQ/Lite 消息存储的运行时摘要。\n */\npublic class GetBrokerLiteInfoSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getBrokerLiteInfo。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "Broker address");',
         '        Option opt = new Option("b", "brokerAddr", true, "Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name");',
         '        opt = new Option("c", "cluster", true, "集群名（与 -b 二选一）");'),
        ('        opt = new Option("d", "showDetail", false, "Show topic and group detail info");',
         '        opt = new Option("d", "showDetail", false, "是否输出 Topic/Group 元数据详情");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 按 Broker 或集群拉取 Lite 存储统计并表格输出。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    static void printHeader() {',
         '    /** 打印 Lite Broker 信息表头。 */\n    static void printHeader() {'),
        ('    static void printRow(\n        GetBrokerLiteInfoResponseBody responseBody,\n        String brokerAddr,\n        boolean showDetail\n    ) {',
         '    /** 输出单行 Lite 统计；showDetail 时附加 Topic/Group 元数据 JSON。 */\n    static void printRow(\n        GetBrokerLiteInfoResponseBody responseBody,\n        String brokerAddr,\n        boolean showDetail\n    ) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/lite/GetLiteClientInfoSubCommand.java': [
        ('public class GetLiteClientInfoSubCommand implements SubCommand {',
         '/**\n * getLiteClientInfo 子命令：查询 LMQ 父 Topic 下指定客户端的 Lite 消费信息。\n */\npublic class GetLiteClientInfoSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getLiteClientInfo。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("p", "parentTopic", true, "Parent topic name");',
         '        Option opt = new Option("p", "parentTopic", true, "LMQ 父 Topic 名");'),
        ('        opt = new Option("g", "group", true, "Consumer group");',
         '        opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("c", "clientId", true, "Client id");',
         '        opt = new Option("c", "clientId", true, "客户端 clientId");'),
        ('        opt = new Option("s", "showDetail", false, "Show details");',
         '        opt = new Option("s", "showDetail", false, "是否列出已订阅的 Lite Topic 集合");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历父 Topic 路由上各 Broker，拉取指定客户端 Lite 消费状态。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    static void printHeader() {',
         '    /** 打印 Lite 客户端信息表头。 */\n    static void printHeader() {'),
        ('    static void printRow(\n        GetLiteClientInfoResponseBody responseBody,\n        String brokerName,\n        boolean showDetail\n    ) {',
         '    /** 输出单行客户端 Lite Topic 数与最近访问/消费时间。 */\n    static void printRow(\n        GetLiteClientInfoResponseBody responseBody,\n        String brokerName,\n        boolean showDetail\n    ) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/lite/GetLiteGroupInfoSubCommand.java': [
        ('public class GetLiteGroupInfoSubCommand implements SubCommand {',
         '/**\n * getLiteGroupInfo 子命令：查询 LMQ 消费组在各 Broker 上的堆积与 TopK 统计。\n */\npublic class GetLiteGroupInfoSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getLiteGroupInfo。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("p", "parentTopic", true, "Parent topic name");',
         '        Option opt = new Option("p", "parentTopic", true, "LMQ 父 Topic 名");'),
        ('        opt = new Option("g", "group", true, "Consumer group");',
         '        opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("l", "liteTopic", true, "query lite topic detail");',
         '        opt = new Option("l", "liteTopic", true, "指定 Lite Topic 查询单条偏移详情");'),
        ('        opt = new Option("k", "topK", true, "topK value of each broker");',
         '        opt = new Option("k", "topK", true, "各 Broker 返回的 TopK 条数，默认 20");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 汇总各 Broker 堆积量，按 lag 数量或时间输出 TopK Lite Topic。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private static void printOffsetWrapper(boolean queryByLiteTopic, String brokerName, OffsetWrapper offsetWrapper) {',
         '    /** 指定 -l 时输出单 Lite Topic 在各 Broker 上的偏移与堆积。 */\n    private static void printOffsetWrapper(boolean queryByLiteTopic, String brokerName, OffsetWrapper offsetWrapper) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/lite/GetLiteTopicInfoSubCommand.java': [
        ('public class GetLiteTopicInfoSubCommand implements SubCommand {',
         '/**\n * getLiteTopicInfo 子命令：查询 LMQ 父 Topic 下单个 Lite Topic 的偏移与订阅者信息。\n */\npublic class GetLiteTopicInfoSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getLiteTopicInfo。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("p", "parentTopic", true, "Parent topic name");',
         '        Option opt = new Option("p", "parentTopic", true, "LMQ 父 Topic 名");'),
        ('        opt = new Option("l", "liteTopic", true, "Lite topic name");',
         '        opt = new Option("l", "liteTopic", true, "Lite Topic 名");'),
        ('        opt = new Option("s", "showClientId", false, "Show all clientId");',
         '        opt = new Option("s", "showClientId", false, "是否列出全部订阅 clientId@group");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历路由上各 Broker，输出 Lite Topic 偏移区间与分片/订阅数。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/lite/GetParentTopicInfoSubCommand.java': [
        ('public class GetParentTopicInfoSubCommand implements SubCommand {',
         '/**\n * getParentTopicInfo 子命令：查询 LMQ 父 Topic 在各 Broker 上的 TTL 与 Lite 统计。\n */\npublic class GetParentTopicInfoSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getParentTopicInfo。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("p", "parentTopic", true, "Parent topic name");',
         '        Option opt = new Option("p", "parentTopic", true, "LMQ 父 Topic 名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历父 Topic 路由，输出各 Broker 的 TTL、Lite 数量与关联消费组。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/lite/TriggerLiteDispatchSubCommand.java': [
        ('public class TriggerLiteDispatchSubCommand implements SubCommand {',
         '/**\n * triggerLiteDispatch 子命令：手动触发 LMQ 消费组的 Lite 消息分发。\n */\npublic class TriggerLiteDispatchSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 triggerLiteDispatch。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("p", "parentTopic", true, "Parent topic name");',
         '        Option opt = new Option("p", "parentTopic", true, "LMQ 父 Topic 名");'),
        ('        opt = new Option("g", "group", true, "Consumer group");',
         '        opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("c", "clientId", true, "clientId (optional)");',
         '        opt = new Option("c", "clientId", true, "可选，限定单个客户端 clientId");'),
        ('        opt = new Option("b", "brokerName", true, "brokerName (optional)");',
         '        opt = new Option("b", "brokerName", true, "可选，限定单个 Broker 名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历路由 Broker，调用 triggerLiteDispatch 触发 Lite 分发并打印结果。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/CheckMsgSendRTCommand.java': [
        ('public class CheckMsgSendRTCommand implements SubCommand {',
         '/**\n * checkMsgSendRT 子命令：向指定 Topic 循环发送测试消息并统计 RT。\n */\npublic class CheckMsgSendRTCommand implements SubCommand {'),
        ('    private static String brokerName = "";',
         '    /** 最近一次发送命中的 Broker 名。 */\n    private static String brokerName = "";'),
        ('    private static int queueId = 0;',
         '    /** 最近一次发送命中的队列 ID。 */\n    private static int queueId = 0;'),
        ('    public String commandName() {',
         '    /** 返回子命令名 checkMsgSendRT。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "目标 Topic 名");'),
        ('        opt = new Option("a", "amount", true, "message amount | default 100");',
         '        opt = new Option("a", "amount", true, "发送条数，默认 100");'),
        ('        opt = new Option("s", "size", true, "message size | default 128 Byte");',
         '        opt = new Option("s", "size", true, "消息体大小（字节），默认 128");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 轮询队列发送测试消息，逐条打印 RT 并计算平均耗时。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    public String getStringBySize(long size) {',
         '    /** 生成指定长度的测试字符串。 */\n    public String getStringBySize(long size) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/ConsumeMessageCommand.java': [
        ('public class ConsumeMessageCommand implements SubCommand {',
         '/**\n * consumeMessage 子命令：以 Pull 方式拉取并打印 Topic 消息（支持队列/偏移/时间过滤）。\n */\npublic class ConsumeMessageCommand implements SubCommand {'),
        ('    private String topic = null;',
         '    /** 待消费的 Topic 名。 */\n    private String topic = null;'),
        ('    private long messageCount = 128;',
         '    /** 最多拉取的消息条数，默认 128。 */\n    private long messageCount = 128;'),
        ('    private DefaultMQPullConsumer defaultMQPullConsumer;',
         '    /** Pull 消费者实例，可复用。 */\n    private DefaultMQPullConsumer defaultMQPullConsumer;'),
        ('    public enum ConsumeType {\n        /**\n         * Topic only\n         */',
         '    /** 消费模式：按 Topic 全队列、指定队列或指定偏移拉取。 */\n    public enum ConsumeType {\n        /**\n         * 仅按 Topic 遍历全部队列\n         */'),
        ('        /**\n         * Topic brokerName queueId set\n         */',
         '        /**\n         * 指定 brokerName 与 queueId\n         */'),
        ('        /**\n         * Topic brokerName queueId offset set\n         */',
         '        /**\n         * 指定 brokerName、queueId 与起始 offset\n         */'),
        ('    private static long timestampFormat(final String value) {',
         '    /** 解析毫秒时间戳或 yyyy-MM-dd#HH:mm:ss:SSS 格式字符串。 */\n    private static long timestampFormat(final String value) {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 consumeMessage。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("t", "topic", true, "Topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("b", "brokerName", true, "Broker name");',
         '        opt = new Option("b", "brokerName", true, "Broker 名（与 -i 配合）");'),
        ('        opt = new Option("i", "queueId", true, "Queue Id");',
         '        opt = new Option("i", "queueId", true, "队列 ID（需先指定 -b）");'),
        ('        opt = new Option("o", "offset", true, "Queue offset");',
         '        opt = new Option("o", "offset", true, "起始队列偏移（需先指定 -i）");'),
        ('        opt = new Option("g", "consumerGroup", true, "Consumer group name");',
         '        opt = new Option("g", "consumerGroup", true, "Pull 消费组名");'),
        ('        opt = new Option("s", "beginTimestamp ", true,\n                "Begin timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '        opt = new Option("s", "beginTimestamp ", true,\n                "起始时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('        opt = new Option("e", "endTimestamp ", true,\n                "End timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '        opt = new Option("e", "endTimestamp ", true,\n                "结束时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('        opt = new Option("c", "MessageNumber", true, "Number of message to be consumed");',
         '        opt = new Option("c", "MessageNumber", true, "最多消费的消息条数");'),
        ('    public void execute(final CommandLine commandLine, final Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析消费模式与时间范围，按 DEFAULT/BYQUEUE/BYOFFSET 拉取消息。 */\n    public void execute(final CommandLine commandLine, final Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void pullMessageByQueue(MessageQueue mq, long minOffset, long maxOffset) {',
         '    /** 在指定偏移区间内循环 Pull 并打印消息内容。 */\n    private void pullMessageByQueue(MessageQueue mq, long minOffset, long maxOffset) {'),
        ('    private void executeDefault(long timeValueBegin, long timeValueEnd) {',
         '    /** 遍历 Topic 全部队列，按时间与条数限制拉取消息。 */\n    private void executeDefault(long timeValueBegin, long timeValueEnd) {'),
        ('    private void executeByCondition(String brokerName, String queueId, long offset, long timeValueBegin, long timeValueEnd) {',
         '    /** 在指定 Broker/队列/偏移上按时间窗口拉取消息。 */\n    private void executeByCondition(String brokerName, String queueId, long offset, long timeValueBegin, long timeValueEnd) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/DecodeMessageIdCommond.java': [
        ('public class DecodeMessageIdCommond implements SubCommand {',
         '/**\n * DecodeMessageId 子命令：解析 RocketMQ 唯一消息 ID 中的 IP 与生成时间。\n */\npublic class DecodeMessageIdCommond implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 DecodeMessageId。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("i", "messageId", true, "unique message ID");',
         '        Option opt = new Option("i", "messageId", true, "待解析的唯一消息 ID");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 从 messageId 提取生产者 IP 与近似生成时间并打印。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/DumpCompactionLogCommand.java': [
        ('public class DumpCompactionLogCommand implements SubCommand {',
         '/**\n * dumpCompactionLog 子命令：解析 Broker 压缩日志文件并逐条输出 {@link MessageExt}。\n */\npublic class DumpCompactionLogCommand implements SubCommand {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 dumpCompactionLog。 */\n    public String commandName() {'),
        ('        Option opt = new Option("f", "file", true, "to dump file name");',
         '        Option opt = new Option("f", "file", true, "待解析的压缩日志文件路径");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)',
         '    /** 内存映射读取日志文件，按长度前缀逐条解码消息并打印。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)'),
    ],
}
