"""Chinese JavaDoc replacements for springframework wave14a validation validator [17:19]."""

VALIDATION_VALIDATOR_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "SmartValidator.java": [
        (
            "/**\n * Extended variant of the {@link Validator} interface, adding support for\n * validation 'hints'.\n *\n * @author Juergen Hoeller\n * @author Sam Brannen\n * @since 3.1\n */",
            "/**\n * {@link Validator} 接口的扩展变体，增加对校验“提示（hint）”的支持。\n *\n * @author Juergen Hoeller\n * @author Sam Brannen\n * @since 3.1\n */",
        ),
        (
            "\t/**\n\t * Validate the supplied {@code target} object, which must be of a type of {@link Class}\n\t * for which the {@link #supports(Class)} method typically returns {@code true}.\n\t * <p>The supplied {@link Errors errors} instance can be used to report any\n\t * resulting validation errors.\n\t * <p><b>This variant of {@code validate()} supports validation hints, such as\n\t * validation groups against a JSR-303 provider</b> (in which case, the provided hint\n\t * objects need to be annotation arguments of type {@code Class}).\n\t * <p>Note: Validation hints may get ignored by the actual target {@code Validator},\n\t * in which case this method should behave just like its regular\n\t * {@link #validate(Object, Errors)} sibling.\n\t * @param target the object that is to be validated\n\t * @param errors contextual state about the validation process\n\t * @param validationHints one or more hint objects to be passed to the validation engine\n\t * @see jakarta.validation.Validator#validate(Object, Class[])\n\t */",
            "\t/**\n\t * 校验给定 {@code target} 对象，其类型必须是 {@link #supports(Class)} 通常返回 {@code true} 的类型。\n\t * <p>可使用提供的 {@link Errors errors} 实例报告产生的校验错误。\n\t * <p><b>本 {@code validate()} 变体支持校验提示，\n\t * 例如针对 JSR-303 提供者的校验分组</b>（此时提示对象需为 {@code Class} 类型的注解参数）。\n\t * <p>注意：实际目标 {@code Validator} 可能忽略校验提示，\n\t * 此时本方法应与常规 {@link #validate(Object, Errors)} 行为一致。\n\t * @param target 要校验的对象\n\t * @param errors 关于校验过程的上下文状态\n\t * @param validationHints 传递给校验引擎的一个或多个提示对象\n\t * @see jakarta.validation.Validator#validate(Object, Class[])\n\t */",
        ),
        (
            "\t/**\n\t * Validate the supplied value for the specified field on the target type,\n\t * reporting the same validation errors as if the value would be bound to\n\t * the field on an instance of the target class.\n\t * @param targetType the target type\n\t * @param fieldName the name of the field\n\t * @param value the candidate value\n\t * @param errors contextual state about the validation process\n\t * @param validationHints one or more hint objects to be passed to the validation engine\n\t * @since 5.1\n\t * @see jakarta.validation.Validator#validateValue(Class, String, Object, Class[])\n\t */",
            "\t/**\n\t * 校验目标类型上指定字段的给定值，\n\t * 报告与将该值绑定到目标类实例字段时相同的校验错误。\n\t * @param targetType 目标类型\n\t * @param fieldName 字段名\n\t * @param value 候选值\n\t * @param errors 关于校验过程的上下文状态\n\t * @param validationHints 传递给校验引擎的一个或多个提示对象\n\t * @since 5.1\n\t * @see jakarta.validation.Validator#validateValue(Class, String, Object, Class[])\n\t */",
        ),
        (
            "\t/**\n\t * Return a contained validator instance of the specified type, unwrapping\n\t * as far as necessary.\n\t * @param type the class of the object to return\n\t * @param <T> the type of the object to return\n\t * @return a validator instance of the specified type; {@code null} if there\n\t * isn't a nested validator; an exception may be raised if the specified\n\t * validator type does not match.\n\t * @since 6.1\n\t */",
            "\t/**\n\t * 返回指定类型的内部校验器实例，必要时逐层解包。\n\t * @param type 要返回的对象的类\n\t * @param <T> 要返回的对象的类型\n\t * @return 指定类型的校验器实例；若无嵌套校验器则返回 {@code null}；\n\t * 若指定校验器类型不匹配可能抛出异常。\n\t * @since 6.1\n\t */",
        ),
    ],
    "TypedValidator.java": [
        (
            "/**\n * Validator instance returned by {@link Validator#forInstanceOf(Class, BiConsumer)}\n * and {@link Validator#forType(Class, BiConsumer)}.\n *\n * @author Toshiaki Maki\n * @author Arjen Poutsma\n * @since 6.1\n * @param <T> the target object type\n */",
            "/**\n * 由 {@link Validator#forInstanceOf(Class, BiConsumer)} 与\n * {@link Validator#forType(Class, BiConsumer)} 返回的 Validator 实例。\n *\n * @author Toshiaki Maki\n * @author Arjen Poutsma\n * @since 6.1\n * @param <T> 目标对象类型\n */",
        ),
    ],
    "ValidationUtils.java": [
        (
            "/**\n * Utility class offering convenient methods for invoking a {@link Validator}\n * and for rejecting empty fields.\n *\n * <p>Checks for an empty field in {@code Validator} implementations can become\n * one-liners when using {@link #rejectIfEmpty} or {@link #rejectIfEmptyOrWhitespace}.\n *\n * @author Juergen Hoeller\n * @author Dmitriy Kopylenko\n * @since 06.05.2003\n * @see Validator\n * @see Errors\n */",
            "/**\n * 提供调用 {@link Validator} 与拒绝空字段便捷方法的工具类。\n *\n * <p>在 {@code Validator} 实现中，使用 {@link #rejectIfEmpty} 或\n * {@link #rejectIfEmptyOrWhitespace} 可将空字段检查简化为一行代码。\n *\n * @author Juergen Hoeller\n * @author Dmitriy Kopylenko\n * @since 06.05.2003\n * @see Validator\n * @see Errors\n */",
        ),
        (
            "\t/**\n\t * Invoke the given {@link Validator} for the supplied object and\n\t * {@link Errors} instance.\n\t * @param validator the {@code Validator} to be invoked\n\t * @param target the object to bind the parameters to\n\t * @param errors the {@link Errors} instance that should store the errors\n\t * @throws IllegalArgumentException if either of the {@code Validator} or {@code Errors}\n\t * arguments is {@code null}, or if the supplied {@code Validator} does not\n\t * {@link Validator#supports(Class) support} the validation of the supplied object's type\n\t */",
            "\t/**\n\t * 对给定对象与 {@link Errors} 实例调用给定 {@link Validator}。\n\t * @param validator 要调用的 {@code Validator}\n\t * @param target 要绑定参数的对象\n\t * @param errors 应存储错误的 {@link Errors} 实例\n\t * @throws IllegalArgumentException 若 {@code Validator} 或 {@code Errors} 参数为 {@code null}，\n\t * 或给定 {@code Validator} 不 {@link Validator#supports(Class) 支持} 给定对象类型的校验\n\t */",
        ),
        (
            "\t/**\n\t * Invoke the given {@link Validator}/{@link SmartValidator} for the supplied object and\n\t * {@link Errors} instance.\n\t * @param validator the {@code Validator} to be invoked\n\t * @param target the object to bind the parameters to\n\t * @param errors the {@link Errors} instance that should store the errors\n\t * @param validationHints one or more hint objects to be passed to the validation engine\n\t * @throws IllegalArgumentException if either of the {@code Validator} or {@code Errors}\n\t * arguments is {@code null}, or if the supplied {@code Validator} does not\n\t * {@link Validator#supports(Class) support} the validation of the supplied object's type\n\t */",
            "\t/**\n\t * 对给定对象与 {@link Errors} 实例调用给定 {@link Validator}/{@link SmartValidator}。\n\t * @param validator 要调用的 {@code Validator}\n\t * @param target 要绑定参数的对象\n\t * @param errors 应存储错误的 {@link Errors} 实例\n\t * @param validationHints 传递给校验引擎的一个或多个提示对象\n\t * @throws IllegalArgumentException 若 {@code Validator} 或 {@code Errors} 参数为 {@code null}，\n\t * 或给定 {@code Validator} 不 {@link Validator#supports(Class) 支持} 给定对象类型的校验\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code if the value is empty.\n\t * <p>An 'empty' value in this context means either {@code null} or\n\t * the empty string \"\".\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t */",
            "\t/**\n\t * 若值为空，以给定错误码拒绝给定字段。\n\t * <p>此处的“空”指 {@code null} 或空字符串 \"\"。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code and default message\n\t * if the value is empty.\n\t * <p>An 'empty' value in this context means either {@code null} or\n\t * the empty string \"\".\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode error code, interpretable as message key\n\t * @param defaultMessage fallback default message\n\t */",
            "\t/**\n\t * 若值为空，以给定错误码与默认消息拒绝给定字段。\n\t * <p>此处的“空”指 {@code null} 或空字符串 \"\"。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t * @param defaultMessage 后备默认消息\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code and error arguments\n\t * if the value is empty.\n\t * <p>An 'empty' value in this context means either {@code null} or\n\t * the empty string \"\".\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t * @param errorArgs the error arguments, for argument binding via MessageFormat\n\t * (can be {@code null})\n\t */",
            "\t/**\n\t * 若值为空，以给定错误码与错误参数拒绝给定字段。\n\t * <p>此处的“空”指 {@code null} 或空字符串 \"\"。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t * @param errorArgs 错误参数，用于 MessageFormat 参数绑定（可为 {@code null}）\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code, error arguments\n\t * and default message if the value is empty.\n\t * <p>An 'empty' value in this context means either {@code null} or\n\t * the empty string \"\".\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t * @param errorArgs the error arguments, for argument binding via MessageFormat\n\t * (can be {@code null})\n\t * @param defaultMessage fallback default message\n\t */",
            "\t/**\n\t * 若值为空，以给定错误码、错误参数与默认消息拒绝给定字段。\n\t * <p>此处的“空”指 {@code null} 或空字符串 \"\"。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t * @param errorArgs 错误参数，用于 MessageFormat 参数绑定（可为 {@code null}）\n\t * @param defaultMessage 后备默认消息\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code if the value is empty\n\t * or just contains whitespace.\n\t * <p>An 'empty' value in this context means either {@code null},\n\t * the empty string \"\", or consisting wholly of whitespace.\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t */",
            "\t/**\n\t * 若值为空或仅含空白，以给定错误码拒绝给定字段。\n\t * <p>此处的“空”指 {@code null}、空字符串 \"\" 或全为空白字符。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code and default message\n\t * if the value is empty or just contains whitespace.\n\t * <p>An 'empty' value in this context means either {@code null},\n\t * the empty string \"\", or consisting wholly of whitespace.\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t * @param defaultMessage fallback default message\n\t */",
            "\t/**\n\t * 若值为空或仅含空白，以给定错误码与默认消息拒绝给定字段。\n\t * <p>此处的“空”指 {@code null}、空字符串 \"\" 或全为空白字符。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t * @param defaultMessage 后备默认消息\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code and error arguments\n\t * if the value is empty or just contains whitespace.\n\t * <p>An 'empty' value in this context means either {@code null},\n\t * the empty string \"\", or consisting wholly of whitespace.\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t * @param errorArgs the error arguments, for argument binding via MessageFormat\n\t * (can be {@code null})\n\t */",
            "\t/**\n\t * 若值为空或仅含空白，以给定错误码与错误参数拒绝给定字段。\n\t * <p>此处的“空”指 {@code null}、空字符串 \"\" 或全为空白字符。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t * @param errorArgs 错误参数，用于 MessageFormat 参数绑定（可为 {@code null}）\n\t */",
        ),
        (
            "\t/**\n\t * Reject the given field with the given error code, error arguments\n\t * and default message if the value is empty or just contains whitespace.\n\t * <p>An 'empty' value in this context means either {@code null},\n\t * the empty string \"\", or consisting wholly of whitespace.\n\t * <p>The object whose field is being validated does not need to be passed\n\t * in because the {@link Errors} instance can resolve field values by itself\n\t * (it will usually hold an internal reference to the target object).\n\t * @param errors the {@code Errors} instance to register errors on\n\t * @param field the field name to check\n\t * @param errorCode the error code, interpretable as message key\n\t * @param errorArgs the error arguments, for argument binding via MessageFormat\n\t * (can be {@code null})\n\t * @param defaultMessage fallback default message\n\t */",
            "\t/**\n\t * 若值为空或仅含空白，以给定错误码、错误参数与默认消息拒绝给定字段。\n\t * <p>此处的“空”指 {@code null}、空字符串 \"\" 或全为空白字符。\n\t * <p>无需传入被校验字段所属对象，\n\t * 因 {@link Errors} 实例可自行解析字段值\n\t * （通常持有对目标对象的内部引用）。\n\t * @param errors 要注册错误的 {@code Errors} 实例\n\t * @param field 要检查的字段名\n\t * @param errorCode 错误码，可解释为消息键\n\t * @param errorArgs 错误参数，用于 MessageFormat 参数绑定（可为 {@code null}）\n\t * @param defaultMessage 后备默认消息\n\t */",
        ),
    ],
}
