LARGE_A_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "ScheduledExecutorFactoryBean.java": [
        (
            "/**\n * {@link org.springframework.beans.factory.FactoryBean} that sets up\n * a {@link java.util.concurrent.ScheduledExecutorService}\n * (by default: a {@link java.util.concurrent.ScheduledThreadPoolExecutor})\n * and exposes it for bean references.\n *\n * <p>Allows for registration of {@link ScheduledExecutorTask ScheduledExecutorTasks},\n * automatically starting the {@link ScheduledExecutorService} on initialization and\n * cancelling it on destruction of the context. In scenarios that only require static\n * registration of tasks at startup, there is no need to access the\n * {@link ScheduledExecutorService} instance itself in application code at all;\n * {@code ScheduledExecutorFactoryBean} is then just being used for lifecycle integration.\n *\n * <p>For an alternative, you may set up a {@link ScheduledThreadPoolExecutor} instance\n * directly using constructor injection, or use a factory method definition that points\n * to the {@link java.util.concurrent.Executors} class.\n * <b>This is strongly recommended in particular for common {@code @Bean} methods in\n * configuration classes, where this {@code FactoryBean} variant would force you to\n * return the {@code FactoryBean} type instead of {@code ScheduledExecutorService}.</b>\n *\n * <p>Note that {@link java.util.concurrent.ScheduledExecutorService}\n * uses a {@link Runnable} instance that is shared between repeated executions,\n * in contrast to Quartz which instantiates a new Job for each execution.\n *\n * <p><b>WARNING:</b> {@link Runnable Runnables} submitted via a native\n * {@link java.util.concurrent.ScheduledExecutorService} are removed from\n * the execution schedule once they throw an exception. If you would prefer\n * to continue execution after such an exception, switch this FactoryBean's\n * {@link #setContinueScheduledExecutionAfterException \"continueScheduledExecutionAfterException\"}\n * property to \"true\".\n *\n * @author Juergen Hoeller\n * @since 2.0\n * @see #setPoolSize\n * @see #setRemoveOnCancelPolicy\n * @see #setThreadFactory\n * @see ScheduledExecutorTask\n * @see java.util.concurrent.ScheduledExecutorService\n * @see java.util.concurrent.ScheduledThreadPoolExecutor\n */",
            "/**\n * 配置 {@link java.util.concurrent.ScheduledExecutorService}\n *（默认 {@link java.util.concurrent.ScheduledThreadPoolExecutor}）\n * 并暴露为 Bean 引用的 {@link org.springframework.beans.factory.FactoryBean}。\n *\n * <p>允许注册 {@link ScheduledExecutorTask ScheduledExecutorTasks}，\n * 初始化时自动启动 {@link ScheduledExecutorService}，\n * 上下文销毁时取消。若仅需启动时静态注册任务，\n * 应用代码完全无需访问 {@link ScheduledExecutorService} 实例；\n * 此时 {@code ScheduledExecutorFactoryBean} 仅用于生命周期集成。\n *\n * <p>也可通过构造器注入直接配置 {@link ScheduledThreadPoolExecutor}，\n * 或使用指向 {@link java.util.concurrent.Executors} 的工厂方法定义。\n * <b>配置类中常见 {@code @Bean} 方法尤其推荐后者，\n * 因本 {@code FactoryBean} 变体会强制返回 {@code FactoryBean} 类型\n * 而非 {@code ScheduledExecutorService}。</b>\n *\n * <p>注意 {@link java.util.concurrent.ScheduledExecutorService}\n * 在重复执行间共享同一 {@link Runnable} 实例，\n * 与 Quartz 每次执行创建新 Job 不同。\n *\n * <p><b>警告：</b>通过原生 {@link java.util.concurrent.ScheduledExecutorService}\n * 提交的 {@link Runnable Runnable} 一旦抛异常即从调度中移除。\n * 若希望异常后继续执行，请将本 FactoryBean 的\n * {@link #setContinueScheduledExecutionAfterException \"continueScheduledExecutionAfterException\"}\n * 属性设为 \"true\"。\n *\n * @author Juergen Hoeller\n * @since 2.0\n * @see #setPoolSize\n * @see #setRemoveOnCancelPolicy\n * @see #setThreadFactory\n * @see ScheduledExecutorTask\n * @see java.util.concurrent.ScheduledExecutorService\n * @see java.util.concurrent.ScheduledThreadPoolExecutor\n */",
        ),
        (
            "\t/**\n\t * Set the ScheduledExecutorService's pool size.\n\t * Default is 1.\n\t */",
            "\t/**\n\t * 设置 ScheduledExecutorService 的池大小。\n\t * 默认为 1。\n\t */",
        ),
        (
            "\t/**\n\t * Register a list of ScheduledExecutorTask objects with the ScheduledExecutorService\n\t * that this FactoryBean creates. Depending on each ScheduledExecutorTask's settings,\n\t * it will be registered via one of ScheduledExecutorService's schedule methods.\n\t * @see java.util.concurrent.ScheduledExecutorService#schedule(java.lang.Runnable, long, java.util.concurrent.TimeUnit)\n\t * @see java.util.concurrent.ScheduledExecutorService#scheduleWithFixedDelay(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)\n\t * @see java.util.concurrent.ScheduledExecutorService#scheduleAtFixedRate(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)\n\t */",
            "\t/**\n\t * 向本 FactoryBean 创建的 ScheduledExecutorService 注册 ScheduledExecutorTask 列表。\n\t * 根据各 ScheduledExecutorTask 的设置，\n\t * 通过 ScheduledExecutorService 的 schedule 方法之一注册。\n\t * @see java.util.concurrent.ScheduledExecutorService#schedule(java.lang.Runnable, long, java.util.concurrent.TimeUnit)\n\t * @see java.util.concurrent.ScheduledExecutorService#scheduleWithFixedDelay(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)\n\t * @see java.util.concurrent.ScheduledExecutorService#scheduleAtFixedRate(java.lang.Runnable, long, long, java.util.concurrent.TimeUnit)\n\t */",
        ),
        (
            "\t/**\n\t * Set the remove-on-cancel mode on {@link ScheduledThreadPoolExecutor}.\n\t * <p>Default is {@code false}. If set to {@code true}, the target executor will be\n\t * switched into remove-on-cancel mode (if possible, with a soft fallback otherwise).\n\t */",
            "\t/**\n\t * 在 {@link ScheduledThreadPoolExecutor} 上设置 cancel 时移除模式。\n\t * <p>默认为 {@code false}。设为 {@code true} 时，\n\t * 目标执行器将切换为 remove-on-cancel 模式（若可能，否则软回退）。\n\t */",
        ),
        (
            "\t/**\n\t * Specify whether to continue the execution of a scheduled task\n\t * after it threw an exception.\n\t * <p>Default is \"false\", matching the native behavior of a\n\t * {@link java.util.concurrent.ScheduledExecutorService}.\n\t * Switch this flag to \"true\" for exception-proof execution of each task,\n\t * continuing scheduled execution as in the case of successful execution.\n\t * @see java.util.concurrent.ScheduledExecutorService#scheduleAtFixedRate\n\t */",
            "\t/**\n\t * 指定定时任务抛异常后是否继续执行。\n\t * <p>默认为 \"false\"，与 {@link java.util.concurrent.ScheduledExecutorService}\n\t * 原生行为一致。设为 \"true\" 可保证各任务异常后继续调度执行，\n\t * 如同成功执行一样。\n\t * @see java.util.concurrent.ScheduledExecutorService#scheduleAtFixedRate\n\t */",
        ),
        (
            "\t/**\n\t * Specify whether this FactoryBean should expose an unconfigurable\n\t * decorator for the created executor.\n\t * <p>Default is \"false\", exposing the raw executor as bean reference.\n\t * Switch this flag to \"true\" to strictly prevent clients from\n\t * modifying the executor's configuration.\n\t * @see java.util.concurrent.Executors#unconfigurableScheduledExecutorService\n\t */",
            "\t/**\n\t * 指定本 FactoryBean 是否应为创建的执行器暴露不可配置装饰器。\n\t * <p>默认为 \"false\"，将原始执行器作为 Bean 引用暴露。\n\t * 设为 \"true\" 可严格禁止客户端修改执行器配置。\n\t * @see java.util.concurrent.Executors#unconfigurableScheduledExecutorService\n\t */",
        ),
        (
            "\t/**\n\t * Create a new {@link ScheduledExecutorService} instance.\n\t * <p>The default implementation creates a {@link ScheduledThreadPoolExecutor}.\n\t * Can be overridden in subclasses to provide custom {@link ScheduledExecutorService} instances.\n\t * @param poolSize the specified pool size\n\t * @param threadFactory the ThreadFactory to use\n\t * @param rejectedExecutionHandler the RejectedExecutionHandler to use\n\t * @return a new ScheduledExecutorService instance\n\t * @see #afterPropertiesSet()\n\t * @see java.util.concurrent.ScheduledThreadPoolExecutor\n\t */",
            "\t/**\n\t * 创建新的 {@link ScheduledExecutorService} 实例。\n\t * <p>默认实现创建 {@link ScheduledThreadPoolExecutor}。\n\t * 子类可覆盖以提供自定义 {@link ScheduledExecutorService} 实例。\n\t * @param poolSize 指定池大小\n\t * @param threadFactory 使用的 ThreadFactory\n\t * @param rejectedExecutionHandler 使用的 RejectedExecutionHandler\n\t * @return 新的 ScheduledExecutorService 实例\n\t * @see #afterPropertiesSet()\n\t * @see java.util.concurrent.ScheduledThreadPoolExecutor\n\t */",
        ),
        (
            "\t/**\n\t * Register the specified {@link ScheduledExecutorTask ScheduledExecutorTasks}\n\t * on the given {@link ScheduledExecutorService}.\n\t * @param tasks the specified ScheduledExecutorTasks (never empty)\n\t * @param executor the ScheduledExecutorService to register the tasks on.\n\t */",
            "\t/**\n\t * 在指定 {@link ScheduledExecutorService} 上注册\n\t * {@link ScheduledExecutorTask ScheduledExecutorTasks}。\n\t * @param tasks 指定的 ScheduledExecutorTasks（永不为空）\n\t * @param executor 注册任务的 ScheduledExecutorService\n\t */",
        ),
        (
            "\t/**\n\t * Determine the actual Runnable to schedule for the given task.\n\t * <p>Wraps the task's Runnable in a\n\t * {@link org.springframework.scheduling.support.DelegatingErrorHandlingRunnable}\n\t * that will catch and log the Exception. If necessary, it will suppress the\n\t * Exception according to the\n\t * {@link #setContinueScheduledExecutionAfterException \"continueScheduledExecutionAfterException\"}\n\t * flag.\n\t * @param task the ScheduledExecutorTask to schedule\n\t * @return the actual Runnable to schedule (may be a decorator)\n\t */",
            "\t/**\n\t * 确定给定任务实际要调度的 Runnable。\n\t * <p>将任务的 Runnable 包装为\n\t * {@link org.springframework.scheduling.support.DelegatingErrorHandlingRunnable}，\n\t * 捕获并记录异常。必要时根据\n\t * {@link #setContinueScheduledExecutionAfterException \"continueScheduledExecutionAfterException\"}\n\t * 标志抑制异常。\n\t * @param task 待调度的 ScheduledExecutorTask\n\t * @return 实际要调度的 Runnable（可能是装饰器）\n\t */",
        ),
    ],
}
