"""Wave 15b [20:40] Chinese JavaDoc replacements — DataAccessUtils."""

DATAACCESSUTILS_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "DataAccessUtils.java": [
        (
            "/**\n * Miscellaneous utility methods for DAO implementations.\n *\n * <p>Useful with any data access technology.\n *\n * @author Juergen Hoeller\n * @since 1.0.2\n */",
            "/**\n * DAO 实现的杂项工具方法。\n *\n * <p>适用于任何数据访问技术。\n *\n * @author Juergen Hoeller\n * @since 1.0.2\n */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Collection.\n\t * <p>Returns {@code null} if 0 result objects found;\n\t * throws an exception if more than 1 element found.\n\t * @param results the result Collection (can be {@code null})\n\t * @return the single result object, or {@code null} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Collection\n\t */",
            "\t/**\n\t * 从给定 Collection 返回单个结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code null}；\n\t * 若找到多于 1 个元素则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}）\n\t * @return 单个结果对象，若无则返回 {@code null}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个元素时\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Stream.\n\t * <p>Returns {@code null} if 0 result objects found;\n\t * throws an exception if more than 1 element found.\n\t * @param results the result Stream (can be {@code null})\n\t * @return the single result object, or {@code null} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Stream\n\t * @since 6.1\n\t */",
            "\t/**\n\t * 从给定 Stream 返回单个结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code null}；\n\t * 若找到多于 1 个元素则抛出异常。\n\t * @param results 结果 Stream（可为 {@code null}）\n\t * @return 单个结果对象，若无则返回 {@code null}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Stream 中找到多于一个元素时\n\t * @since 6.1\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Iterator.\n\t * <p>Returns {@code null} if 0 result objects found;\n\t * throws an exception if more than 1 element found.\n\t * @param results the result Iterator (can be {@code null})\n\t * @return the single result object, or {@code null} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Iterator\n\t * @since 6.1\n\t */",
            "\t/**\n\t * 从给定 Iterator 返回单个结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code null}；\n\t * 若找到多于 1 个元素则抛出异常。\n\t * @param results 结果 Iterator（可为 {@code null}）\n\t * @return 单个结果对象，若无则返回 {@code null}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Iterator 中找到多于一个元素时\n\t * @since 6.1\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Collection.\n\t * <p>Returns {@code Optional.empty()} if 0 result objects found;\n\t * throws an exception if more than 1 element found.\n\t * @param results the result Collection (can be {@code null})\n\t * @return the single optional result object, or {@code Optional.empty()} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Collection\n\t * @since 6.1\n\t */",
            "\t/**\n\t * 从给定 Collection 返回单个结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code Optional.empty()}；\n\t * 若找到多于 1 个元素则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}）\n\t * @return 单个可选结果对象，若无则返回 {@code Optional.empty()}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个元素时\n\t * @since 6.1\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Stream.\n\t * <p>Returns {@code Optional.empty()} if 0 result objects found;\n\t * throws an exception if more than 1 element found.\n\t * @param results the result Stream (can be {@code null})\n\t * @return the single optional result object, or {@code Optional.empty()} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Stream\n\t * @since 6.1\n\t */",
            "\t/**\n\t * 从给定 Stream 返回单个结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code Optional.empty()}；\n\t * 若找到多于 1 个元素则抛出异常。\n\t * @param results 结果 Stream（可为 {@code null}）\n\t * @return 单个可选结果对象，若无则返回 {@code Optional.empty()}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Stream 中找到多于一个元素时\n\t * @since 6.1\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Iterator.\n\t * <p>Returns {@code Optional.empty()} if 0 result objects found;\n\t * throws an exception if more than 1 element found.\n\t * @param results the result Iterator (can be {@code null})\n\t * @return the single optional result object, or {@code Optional.empty()} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Iterator\n\t * @since 6.1\n\t */",
            "\t/**\n\t * 从给定 Iterator 返回单个结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code Optional.empty()}；\n\t * 若找到多于 1 个元素则抛出异常。\n\t * @param results 结果 Iterator（可为 {@code null}）\n\t * @return 单个可选结果对象，若无则返回 {@code Optional.empty()}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Iterator 中找到多于一个元素时\n\t * @since 6.1\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Collection.\n\t * <p>Throws an exception if 0 or more than 1 element found.\n\t * @param results the result Collection (can be {@code null}\n\t * but is not expected to contain {@code null} elements)\n\t * @return the single result object\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Collection\n\t * @throws EmptyResultDataAccessException if no element at all\n\t * has been found in the given Collection\n\t */",
            "\t/**\n\t * 从给定 Collection 返回单个结果对象。\n\t * <p>若找到 0 个或多于 1 个元素则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}，\n\t * 但不应包含 {@code null} 元素）\n\t * @return 单个结果对象\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个元素时\n\t * @throws EmptyResultDataAccessException 给定 Collection 中未找到任何元素时\n\t */",
        ),
        (
            "\t/**\n\t * Return a single result object from the given Collection.\n\t * <p>Throws an exception if 0 or more than 1 element found.\n\t * @param results the result Collection (can be {@code null}\n\t * and is also expected to contain {@code null} elements)\n\t * @return the single result object\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * element has been found in the given Collection\n\t * @throws EmptyResultDataAccessException if no element at all\n\t * has been found in the given Collection\n\t * @since 5.0.2\n\t */",
            "\t/**\n\t * 从给定 Collection 返回单个结果对象。\n\t * <p>若找到 0 个或多于 1 个元素则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}，\n\t * 且可能包含 {@code null} 元素）\n\t * @return 单个结果对象\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个元素时\n\t * @throws EmptyResultDataAccessException 给定 Collection 中未找到任何元素时\n\t * @since 5.0.2\n\t */",
        ),
        (
            "\t/**\n\t * Return a unique result object from the given Collection.\n\t * <p>Returns {@code null} if 0 result objects found;\n\t * throws an exception if more than 1 instance found.\n\t * @param results the result Collection (can be {@code null})\n\t * @return the unique result object, or {@code null} if none\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * result object has been found in the given Collection\n\t * @see org.springframework.util.CollectionUtils#hasUniqueObject\n\t */",
            "\t/**\n\t * 从给定 Collection 返回唯一结果对象。\n\t * <p>若找到 0 个结果对象则返回 {@code null}；\n\t * 若找到多于 1 个实例则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}）\n\t * @return 唯一结果对象，若无则返回 {@code null}\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个结果对象时\n\t * @see org.springframework.util.CollectionUtils#hasUniqueObject\n\t */",
        ),
        (
            "\t/**\n\t * Return a unique result object from the given Collection.\n\t * <p>Throws an exception if 0 or more than 1 instance found.\n\t * @param results the result Collection (can be {@code null}\n\t * but is not expected to contain {@code null} elements)\n\t * @return the unique result object\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * result object has been found in the given Collection\n\t * @throws EmptyResultDataAccessException if no result object at all\n\t * has been found in the given Collection\n\t * @see org.springframework.util.CollectionUtils#hasUniqueObject\n\t */",
            "\t/**\n\t * 从给定 Collection 返回唯一结果对象。\n\t * <p>若找到 0 个或多于 1 个实例则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}，\n\t * 但不应包含 {@code null} 元素）\n\t * @return 唯一结果对象\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个结果对象时\n\t * @throws EmptyResultDataAccessException 给定 Collection 中未找到任何结果对象时\n\t * @see org.springframework.util.CollectionUtils#hasUniqueObject\n\t */",
        ),
        (
            "\t/**\n\t * Return a unique result object from the given Collection.\n\t * Throws an exception if 0 or more than 1 result objects found,\n\t * of if the unique result object is not convertible to the\n\t * specified required type.\n\t * @param results the result Collection (can be {@code null}\n\t * but is not expected to contain {@code null} elements)\n\t * @return the unique result object\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * result object has been found in the given Collection\n\t * @throws EmptyResultDataAccessException if no result object\n\t * at all has been found in the given Collection\n\t * @throws TypeMismatchDataAccessException if the unique object does\n\t * not match the specified required type\n\t */",
            "\t/**\n\t * 从给定 Collection 返回唯一结果对象。\n\t * 若找到 0 个或多于 1 个结果对象，或唯一结果对象无法转换为\n\t * 指定所需类型，则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}，\n\t * 但不应包含 {@code null} 元素）\n\t * @return 唯一结果对象\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个结果对象时\n\t * @throws EmptyResultDataAccessException 给定 Collection 中未找到任何结果对象时\n\t * @throws TypeMismatchDataAccessException 唯一对象与指定所需类型不匹配时\n\t */",
        ),
        (
            "\t/**\n\t * Return a unique int result from the given Collection.\n\t * Throws an exception if 0 or more than 1 result objects found,\n\t * of if the unique result object is not convertible to an int.\n\t * @param results the result Collection (can be {@code null}\n\t * but is not expected to contain {@code null} elements)\n\t * @return the unique int result\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * result object has been found in the given Collection\n\t * @throws EmptyResultDataAccessException if no result object\n\t * at all has been found in the given Collection\n\t * @throws TypeMismatchDataAccessException if the unique object\n\t * in the collection is not convertible to an int\n\t */",
            "\t/**\n\t * 从给定 Collection 返回唯一 int 结果。\n\t * 若找到 0 个或多于 1 个结果对象，或唯一结果对象无法转换为 int，则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}，\n\t * 但不应包含 {@code null} 元素）\n\t * @return 唯一 int 结果\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个结果对象时\n\t * @throws EmptyResultDataAccessException 给定 Collection 中未找到任何结果对象时\n\t * @throws TypeMismatchDataAccessException 集合中唯一对象无法转换为 int 时\n\t */",
        ),
        (
            "\t/**\n\t * Return a unique long result from the given Collection.\n\t * Throws an exception if 0 or more than 1 result objects found,\n\t * of if the unique result object is not convertible to a long.\n\t * @param results the result Collection (can be {@code null}\n\t * but is not expected to contain {@code null} elements)\n\t * @return the unique long result\n\t * @throws IncorrectResultSizeDataAccessException if more than one\n\t * result object has been found in the given Collection\n\t * @throws EmptyResultDataAccessException if no result object\n\t * at all has been found in the given Collection\n\t * @throws TypeMismatchDataAccessException if the unique object\n\t * in the collection is not convertible to a long\n\t */",
            "\t/**\n\t * 从给定 Collection 返回唯一 long 结果。\n\t * 若找到 0 个或多于 1 个结果对象，或唯一结果对象无法转换为 long，则抛出异常。\n\t * @param results 结果 Collection（可为 {@code null}，\n\t * 但不应包含 {@code null} 元素）\n\t * @return 唯一 long 结果\n\t * @throws IncorrectResultSizeDataAccessException 给定 Collection 中找到多于一个结果对象时\n\t * @throws EmptyResultDataAccessException 给定 Collection 中未找到任何结果对象时\n\t * @throws TypeMismatchDataAccessException 集合中唯一对象无法转换为 long 时\n\t */",
        ),
        (
            "\t/**\n\t * Return a translated exception if this is appropriate,\n\t * otherwise return the given exception as-is.\n\t * @param rawException an exception that we may wish to translate\n\t * @param pet the PersistenceExceptionTranslator to use to perform the translation\n\t * @return a translated persistence exception if translation is possible,\n\t * or the raw exception if it is not\n\t */",
            "\t/**\n\t * 若合适则返回转换后的异常，否则原样返回给定异常。\n\t * @param rawException 可能需要转换的异常\n\t * @param pet 用于执行转换的 PersistenceExceptionTranslator\n\t * @return 若可转换则返回转换后的持久化异常，否则返回原始异常\n\t */",
        ),
    ],
}
