"""Chinese JavaDoc replacements for springframework wave16a TransactionDefinition [14:15]."""

TX_DEFINITION_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "TransactionDefinition.java": [
        (
            "/**\n * Interface that defines Spring-compliant transaction properties.\n * Based on the propagation behavior definitions analogous to EJB CMT attributes.\n *\n * <p>Note that isolation level and timeout settings will not get applied unless\n * an actual new transaction gets started. As only {@link #PROPAGATION_REQUIRED},\n * {@link #PROPAGATION_REQUIRES_NEW}, and {@link #PROPAGATION_NESTED} can cause\n * that, it usually doesn't make sense to specify those settings in other cases.\n * Furthermore, be aware that not all transaction managers will support those\n * advanced features and thus might throw corresponding exceptions when given\n * non-default values.\n *\n * <p>The {@linkplain #isReadOnly() read-only flag} applies to any transaction context,\n * whether backed by an actual resource transaction or operating non-transactionally\n * at the resource level. In the latter case, the flag will only apply to managed\n * resources within the application, such as a Hibernate {@code Session}.\n *\n * @author Juergen Hoeller\n * @since 08.05.2003\n * @see PlatformTransactionManager#getTransaction(TransactionDefinition)\n * @see org.springframework.transaction.support.DefaultTransactionDefinition\n * @see org.springframework.transaction.interceptor.TransactionAttribute\n */",
            "/**\n * 定义符合 Spring 规范的事务属性的接口。\n * 基于与 EJB CMT 属性类似的事务传播行为定义。\n *\n * <p>注意，隔离级别与超时设置仅在真正启动新事务时才会生效。\n * 只有 {@link #PROPAGATION_REQUIRED}、{@link #PROPAGATION_REQUIRES_NEW}\n * 和 {@link #PROPAGATION_NESTED} 能触发新事务，\n * 因此在其他情况下通常无需指定这些设置。\n * 此外，并非所有事务管理器都支持这些高级特性，\n * 给定非默认值时可能抛出相应异常。\n *\n * <p>{@linkplain #isReadOnly() 只读标志}适用于任意事务上下文，\n * 无论是否由实际资源事务支持，或在资源层非事务运行。\n * 后者情况下，该标志仅适用于应用内受管资源，如 Hibernate {@code Session}。\n *\n * @author Juergen Hoeller\n * @since 08.05.2003\n * @see PlatformTransactionManager#getTransaction(TransactionDefinition)\n * @see org.springframework.transaction.support.DefaultTransactionDefinition\n * @see org.springframework.transaction.interceptor.TransactionAttribute\n */",
        ),
        (
            "\t/**\n\t * Support a current transaction; create a new one if none exists.\n\t * Analogous to the EJB transaction attribute of the same name.\n\t * <p>This is typically the default setting of a transaction definition\n\t * and typically defines a transaction synchronization scope.\n\t */",
            "\t/**\n\t * 支持当前事务；若不存在则创建新事务。\n\t * 与同名 EJB 事务属性类似。\n\t * <p>这通常是事务定义的默认设置，\n\t * 并通常定义事务同步范围。\n\t */",
        ),
        (
            "\t/**\n\t * Support a current transaction; execute non-transactionally if none exists.\n\t * Analogous to the EJB transaction attribute of the same name.\n\t * <p><b>NOTE:</b> For transaction managers with transaction synchronization,\n\t * {@code PROPAGATION_SUPPORTS} is slightly different from no transaction\n\t * at all, as it defines a transaction scope that synchronization might apply to.\n\t * As a consequence, the same resources (a JDBC {@code Connection}, a\n\t * Hibernate {@code Session}, etc) will be shared for the entire specified\n\t * scope. Note that the exact behavior depends on the actual synchronization\n\t * configuration of the transaction manager.\n\t * <p>In general, use {@code PROPAGATION_SUPPORTS} with care. In particular, do\n\t * not rely on {@code PROPAGATION_REQUIRED} or {@code PROPAGATION_REQUIRES_NEW}\n\t * <i>within</i> a {@code PROPAGATION_SUPPORTS} scope (which may lead to\n\t * synchronization conflicts at runtime). If such nesting is unavoidable, make sure\n\t * to configure your transaction manager appropriately (typically switching to\n\t * \"synchronization on actual transaction\").\n\t * @see org.springframework.transaction.support.AbstractPlatformTransactionManager#setTransactionSynchronization\n\t * @see org.springframework.transaction.support.AbstractPlatformTransactionManager#SYNCHRONIZATION_ON_ACTUAL_TRANSACTION\n\t */",
            "\t/**\n\t * 支持当前事务；若不存在则以非事务方式执行。\n\t * 与同名 EJB 事务属性类似。\n\t * <p><b>注意：</b>对于支持事务同步的事务管理器，\n\t * {@code PROPAGATION_SUPPORTS} 与完全无事务略有不同，\n\t * 因为它定义了同步可能适用的事务范围。\n\t * 因此相同资源（JDBC {@code Connection}、Hibernate {@code Session} 等）\n\t * 将在整个指定范围内共享。具体行为取决于事务管理器的同步配置。\n\t * <p>一般而言，请谨慎使用 {@code PROPAGATION_SUPPORTS}。\n\t * 尤其不要在 {@code PROPAGATION_SUPPORTS} 范围内\n\t * <i>依赖</i> {@code PROPAGATION_REQUIRED} 或 {@code PROPAGATION_REQUIRES_NEW}\n\t * （可能导致运行时同步冲突）。若无法避免此类嵌套，\n\t * 请适当配置事务管理器（通常切换为 \"synchronization on actual transaction\"）。\n\t * @see org.springframework.transaction.support.AbstractPlatformTransactionManager#setTransactionSynchronization\n\t * @see org.springframework.transaction.support.AbstractPlatformTransactionManager#SYNCHRONIZATION_ON_ACTUAL_TRANSACTION\n\t */",
        ),
        (
            "\t/**\n\t * Support a current transaction; throw an exception if no current transaction\n\t * exists. Analogous to the EJB transaction attribute of the same name.\n\t * <p>Note that transaction synchronization within a {@code PROPAGATION_MANDATORY}\n\t * scope will always be driven by the surrounding transaction.\n\t */",
            "\t/**\n\t * 支持当前事务；若不存在当前事务则抛出异常。\n\t * 与同名 EJB 事务属性类似。\n\t * <p>注意，{@code PROPAGATION_MANDATORY} 范围内的事务同步\n\t * 始终由外围事务驱动。\n\t */",
        ),
        (
            "\t/**\n\t * Create a new transaction, suspending the current transaction if one exists.\n\t * Analogous to the EJB transaction attribute of the same name.\n\t * <p><b>NOTE:</b> Actual transaction suspension will not work out-of-the-box\n\t * on all transaction managers. This in particular applies to\n\t * {@link org.springframework.transaction.jta.JtaTransactionManager},\n\t * which requires the {@code jakarta.transaction.TransactionManager} to be\n\t * made available to it (which is server-specific in standard Jakarta EE).\n\t * <p>A {@code PROPAGATION_REQUIRES_NEW} scope always defines its own\n\t * transaction synchronizations. Existing synchronizations will be suspended\n\t * and resumed appropriately.\n\t * @see org.springframework.transaction.jta.JtaTransactionManager#setTransactionManager\n\t */",
            "\t/**\n\t * 创建新事务，若存在当前事务则将其挂起。\n\t * 与同名 EJB 事务属性类似。\n\t * <p><b>注意：</b>并非所有事务管理器都能开箱即用地实现实际事务挂起。\n\t * 这尤其适用于 {@link org.springframework.transaction.jta.JtaTransactionManager}，\n\t * 它需要可用的 {@code jakarta.transaction.TransactionManager}\n\t * （在标准 Jakarta EE 中因服务器而异）。\n\t * <p>{@code PROPAGATION_REQUIRES_NEW} 范围始终定义自己的事务同步。\n\t * 现有同步将被适当挂起并恢复。\n\t * @see org.springframework.transaction.jta.JtaTransactionManager#setTransactionManager\n\t */",
        ),
        (
            "\t/**\n\t * Do not support a current transaction; rather always execute non-transactionally.\n\t * Analogous to the EJB transaction attribute of the same name.\n\t * <p><b>NOTE:</b> Actual transaction suspension will not work out-of-the-box\n\t * on all transaction managers. This in particular applies to\n\t * {@link org.springframework.transaction.jta.JtaTransactionManager},\n\t * which requires the {@code jakarta.transaction.TransactionManager} to be\n\t * made available to it (which is server-specific in standard Jakarta EE).\n\t * <p>Note that transaction synchronization is <i>not</i> available within a\n\t * {@code PROPAGATION_NOT_SUPPORTED} scope. Existing synchronizations\n\t * will be suspended and resumed appropriately.\n\t * @see org.springframework.transaction.jta.JtaTransactionManager#setTransactionManager\n\t */",
            "\t/**\n\t * 不支持当前事务；始终以非事务方式执行。\n\t * 与同名 EJB 事务属性类似。\n\t * <p><b>注意：</b>并非所有事务管理器都能开箱即用地实现实际事务挂起。\n\t * 这尤其适用于 {@link org.springframework.transaction.jta.JtaTransactionManager}，\n\t * 它需要可用的 {@code jakarta.transaction.TransactionManager}\n\t * （在标准 Jakarta EE 中因服务器而异）。\n\t * <p>注意，{@code PROPAGATION_NOT_SUPPORTED} 范围内<i>不</i>可用事务同步。\n\t * 现有同步将被适当挂起并恢复。\n\t * @see org.springframework.transaction.jta.JtaTransactionManager#setTransactionManager\n\t */",
        ),
        (
            "\t/**\n\t * Do not support a current transaction; throw an exception if a current transaction\n\t * exists. Analogous to the EJB transaction attribute of the same name.\n\t * <p>Note that transaction synchronization is <i>not</i> available within a\n\t * {@code PROPAGATION_NEVER} scope.\n\t */",
            "\t/**\n\t * 不支持当前事务；若存在当前事务则抛出异常。\n\t * 与同名 EJB 事务属性类似。\n\t * <p>注意，{@code PROPAGATION_NEVER} 范围内<i>不</i>可用事务同步。\n\t */",
        ),
        (
            "\t/**\n\t * Execute within a nested transaction if a current transaction exists,\n\t * behaving like {@link #PROPAGATION_REQUIRED} otherwise. There is no\n\t * analogous feature in EJB.\n\t * <p><b>NOTE:</b> Actual creation of a nested transaction will only work on\n\t * specific transaction managers. Out of the box, this only applies to the JDBC\n\t * {@link org.springframework.jdbc.datasource.DataSourceTransactionManager}\n\t * when working on a JDBC 3.0+ driver. Some JTA providers might support\n\t * nested transactions as well.\n\t * @see org.springframework.jdbc.datasource.DataSourceTransactionManager\n\t */",
            "\t/**\n\t * 若存在当前事务则在嵌套事务内执行，\n\t * 否则行为类似 {@link #PROPAGATION_REQUIRED}。EJB 中无对应特性。\n\t * <p><b>注意：</b>嵌套事务的实际创建仅在特定事务管理器上有效。\n\t * 开箱即用情况下，仅适用于使用 JDBC 3.0+ 驱动时的\n\t * {@link org.springframework.jdbc.datasource.DataSourceTransactionManager}。\n\t * 部分 JTA 提供者也可能支持嵌套事务。\n\t * @see org.springframework.jdbc.datasource.DataSourceTransactionManager\n\t */",
        ),
        (
            "\t/**\n\t * Use the default isolation level of the underlying datastore.\n\t * <p>All other levels correspond to the JDBC isolation levels.\n\t * @see java.sql.Connection\n\t */",
            "\t/**\n\t * 使用底层数据存储的默认隔离级别。\n\t * <p>其他级别均对应 JDBC 隔离级别。\n\t * @see java.sql.Connection\n\t */",
        ),
        (
            "\t/**\n\t * Indicates that dirty reads, non-repeatable reads, and phantom reads\n\t * can occur.\n\t * <p>This level allows a row changed by one transaction to be read by another\n\t * transaction before any changes in that row have been committed (a \"dirty read\").\n\t * If any of the changes are rolled back, the second transaction will have\n\t * retrieved an invalid row.\n\t * @see java.sql.Connection#TRANSACTION_READ_UNCOMMITTED\n\t */",
            "\t/**\n\t * 表示可能发生脏读、不可重复读和幻读。\n\t * <p>该级别允许一个事务修改的行在提交前\n\t * 被另一事务读取（\"脏读\"）。\n\t * 若任一修改被回滚，第二事务将读到无效行。\n\t * @see java.sql.Connection#TRANSACTION_READ_UNCOMMITTED\n\t */",
        ),
        (
            "\t/**\n\t * Indicates that dirty reads are prevented; non-repeatable reads and\n\t * phantom reads can occur.\n\t * <p>This level only prohibits a transaction from reading a row with uncommitted\n\t * changes in it.\n\t * @see java.sql.Connection#TRANSACTION_READ_COMMITTED\n\t */",
            "\t/**\n\t * 表示防止脏读；不可重复读和幻读仍可能发生。\n\t * <p>该级别仅禁止事务读取含未提交修改的行。\n\t * @see java.sql.Connection#TRANSACTION_READ_COMMITTED\n\t */",
        ),
        (
            "\t/**\n\t * Indicates that dirty reads and non-repeatable reads are prevented;\n\t * phantom reads can occur.\n\t * <p>This level prohibits a transaction from reading a row with uncommitted changes\n\t * in it, and it also prohibits the situation where one transaction reads a row,\n\t * a second transaction alters the row, and the first transaction re-reads the row,\n\t * getting different values the second time (a \"non-repeatable read\").\n\t * @see java.sql.Connection#TRANSACTION_REPEATABLE_READ\n\t */",
            "\t/**\n\t * 表示防止脏读和不可重复读；幻读仍可能发生。\n\t * <p>该级别禁止读取含未提交修改的行，\n\t * 也禁止一事务读行、第二事务修改行、第一事务再读得到不同值\n\t * （\"不可重复读\"）的情况。\n\t * @see java.sql.Connection#TRANSACTION_REPEATABLE_READ\n\t */",
        ),
        (
            "\t/**\n\t * Indicates that dirty reads, non-repeatable reads, and phantom reads\n\t * are prevented.\n\t * <p>This level includes the prohibitions in {@link #ISOLATION_REPEATABLE_READ}\n\t * and further prohibits the situation where one transaction reads all rows that\n\t * satisfy a {@code WHERE} condition, a second transaction inserts a row\n\t * that satisfies that {@code WHERE} condition, and the first transaction\n\t * re-reads for the same condition, retrieving the additional \"phantom\" row\n\t * in the second read.\n\t * @see java.sql.Connection#TRANSACTION_SERIALIZABLE\n\t */",
            "\t/**\n\t * 表示防止脏读、不可重复读和幻读。\n\t * <p>该级别包含 {@link #ISOLATION_REPEATABLE_READ} 的限制，\n\t * 并进一步禁止：一事务读取满足 {@code WHERE} 条件的所有行，\n\t * 第二事务插入满足该 {@code WHERE} 条件的行，\n\t * 第一事务再次按相同条件读取时得到额外 \"幻\" 行的情况。\n\t * @see java.sql.Connection#TRANSACTION_SERIALIZABLE\n\t */",
        ),
        (
            "\t/**\n\t * Use the default timeout of the underlying transaction system,\n\t * or none if timeouts are not supported.\n\t */",
            "\t/**\n\t * 使用底层事务系统的默认超时，\n\t * 若不支持超时则为无超时。\n\t */",
        ),
        (
            "\t/**\n\t * Return the propagation behavior.\n\t * <p>Must return one of the {@code PROPAGATION_XXX} constants\n\t * defined on {@link TransactionDefinition this interface}.\n\t * <p>The default is {@link #PROPAGATION_REQUIRED}.\n\t * @return the propagation behavior\n\t * @see #PROPAGATION_REQUIRED\n\t * @see org.springframework.transaction.support.TransactionSynchronizationManager#isActualTransactionActive()\n\t */",
            "\t/**\n\t * 返回传播行为。\n\t * <p>必须返回 {@link TransactionDefinition 本接口} 定义的\n\t * {@code PROPAGATION_XXX} 常量之一。\n\t * <p>默认为 {@link #PROPAGATION_REQUIRED}。\n\t * @return 传播行为\n\t * @see #PROPAGATION_REQUIRED\n\t * @see org.springframework.transaction.support.TransactionSynchronizationManager#isActualTransactionActive()\n\t */",
        ),
        (
            "\t/**\n\t * Return the isolation level.\n\t * <p>Must return one of the {@code ISOLATION_XXX} constants defined on\n\t * {@link TransactionDefinition this interface}. Those constants are designed\n\t * to match the values of the same constants on {@link java.sql.Connection}.\n\t * <p>Exclusively designed for use with {@link #PROPAGATION_REQUIRED} or\n\t * {@link #PROPAGATION_REQUIRES_NEW} since it only applies to newly started\n\t * transactions. Consider switching the \"validateExistingTransaction\" flag to\n\t * \"true\" on your transaction manager if you'd like isolation level declarations\n\t * to get rejected when participating in an existing transaction with a different\n\t * isolation level.\n\t * <p>The default is {@link #ISOLATION_DEFAULT}. Note that a transaction manager\n\t * that does not support custom isolation levels will throw an exception when\n\t * given any other level than {@link #ISOLATION_DEFAULT}.\n\t * @return the isolation level\n\t * @see #ISOLATION_DEFAULT\n\t * @see org.springframework.transaction.support.AbstractPlatformTransactionManager#setValidateExistingTransaction\n\t */",
            "\t/**\n\t * 返回隔离级别。\n\t * <p>必须返回 {@link TransactionDefinition 本接口} 定义的\n\t * {@code ISOLATION_XXX} 常量之一，其值与 {@link java.sql.Connection} 上同名常量一致。\n\t * <p>专用于 {@link #PROPAGATION_REQUIRED} 或 {@link #PROPAGATION_REQUIRES_NEW}，\n\t * 因为仅适用于新启动的事务。若希望参与具有不同隔离级别的现有事务时\n\t * 拒绝隔离级别声明，可将事务管理器的 \"validateExistingTransaction\" 标志设为 \"true\"。\n\t * <p>默认为 {@link #ISOLATION_DEFAULT}。不支持自定义隔离级别的事务管理器\n\t * 在收到非 {@link #ISOLATION_DEFAULT} 级别时将抛出异常。\n\t * @return 隔离级别\n\t * @see #ISOLATION_DEFAULT\n\t * @see org.springframework.transaction.support.AbstractPlatformTransactionManager#setValidateExistingTransaction\n\t */",
        ),
        (
            "\t/**\n\t * Return the transaction timeout.\n\t * <p>Must return a number of seconds, or {@link #TIMEOUT_DEFAULT}.\n\t * <p>Exclusively designed for use with {@link #PROPAGATION_REQUIRED} or\n\t * {@link #PROPAGATION_REQUIRES_NEW} since it only applies to newly started\n\t * transactions.\n\t * <p>Note that a transaction manager that does not support timeouts will throw\n\t * an exception when given any other timeout than {@link #TIMEOUT_DEFAULT}.\n\t * <p>The default is {@link #TIMEOUT_DEFAULT}.\n\t * @return the transaction timeout\n\t */",
            "\t/**\n\t * 返回事务超时。\n\t * <p>必须返回秒数，或 {@link #TIMEOUT_DEFAULT}。\n\t * <p>专用于 {@link #PROPAGATION_REQUIRED} 或 {@link #PROPAGATION_REQUIRES_NEW}，\n\t * 因为仅适用于新启动的事务。\n\t * <p>不支持超时的事务管理器在收到非 {@link #TIMEOUT_DEFAULT} 超时时将抛出异常。\n\t * <p>默认为 {@link #TIMEOUT_DEFAULT}。\n\t * @return 事务超时\n\t */",
        ),
        (
            "\t/**\n\t * Return whether to optimize as a read-only transaction.\n\t * <p>The read-only flag applies to any transaction context, whether backed\n\t * by an actual resource transaction ({@link #PROPAGATION_REQUIRED}/\n\t * {@link #PROPAGATION_REQUIRES_NEW}) or operating non-transactionally at\n\t * the resource level ({@link #PROPAGATION_SUPPORTS}). In the latter case,\n\t * the flag will only apply to managed resources within the application,\n\t * such as a Hibernate {@code Session}.\n\t * <p>This just serves as a hint for the actual transaction subsystem;\n\t * it will <i>not necessarily</i> cause failure of write access attempts.\n\t * A transaction manager which cannot interpret the read-only hint will\n\t * <i>not</i> throw an exception when asked for a read-only transaction.\n\t * @return {@code true} if the transaction is to be optimized as read-only\n\t * ({@code false} by default)\n\t * @see org.springframework.transaction.support.TransactionSynchronization#beforeCommit(boolean)\n\t * @see org.springframework.transaction.support.TransactionSynchronizationManager#isCurrentTransactionReadOnly()\n\t */",
            "\t/**\n\t * 返回是否作为只读事务优化。\n\t * <p>只读标志适用于任意事务上下文，无论由实际资源事务\n\t * （{@link #PROPAGATION_REQUIRED}/{@link #PROPAGATION_REQUIRES_NEW}）支持，\n\t * 或在资源层非事务运行（{@link #PROPAGATION_SUPPORTS}）。\n\t * 后者情况下，该标志仅适用于应用内受管资源，如 Hibernate {@code Session}。\n\t * <p>这仅作为实际事务子系统的提示；<i>不必然</i>导致写访问失败。\n\t * 无法解释只读提示的事务管理器在请求只读事务时<i>不会</i>抛出异常。\n\t * @return 若事务应优化为只读则为 {@code true}（默认 {@code false}）\n\t * @see org.springframework.transaction.support.TransactionSynchronization#beforeCommit(boolean)\n\t * @see org.springframework.transaction.support.TransactionSynchronizationManager#isCurrentTransactionReadOnly()\n\t */",
        ),
        (
            "\t/**\n\t * Return the name of this transaction. Can be {@code null}.\n\t * <p>This will be used as the transaction name to be shown in a\n\t * transaction monitor, if applicable.\n\t * <p>In case of Spring's declarative transactions, the exposed name will be\n\t * the {@code fully-qualified class name + \".\" + method name} (by default).\n\t * @return the name of this transaction ({@code null} by default}\n\t * @see org.springframework.transaction.interceptor.TransactionAspectSupport\n\t * @see org.springframework.transaction.support.TransactionSynchronizationManager#getCurrentTransactionName()\n\t */",
            "\t/**\n\t * 返回本事务名称。可为 {@code null}。\n\t * <p>若适用，将作为事务监视器中显示的事务名称。\n\t * <p>对于 Spring 声明式事务，暴露的名称默认为\n\t * {@code 全限定类名 + \".\" + 方法名}。\n\t * @return 本事务名称（默认 {@code null}）\n\t * @see org.springframework.transaction.interceptor.TransactionAspectSupport\n\t * @see org.springframework.transaction.support.TransactionSynchronizationManager#getCurrentTransactionName()\n\t */",
        ),
        (
            "\t/**\n\t * Return an unmodifiable {@code TransactionDefinition} with defaults.\n\t * <p>For customization purposes, use the modifiable\n\t * {@link org.springframework.transaction.support.DefaultTransactionDefinition}\n\t * instead.\n\t * @since 5.2\n\t */",
            "\t/**\n\t * 返回带默认值的不可修改 {@code TransactionDefinition}。\n\t * <p>如需定制，请改用可修改的\n\t * {@link org.springframework.transaction.support.DefaultTransactionDefinition}。\n\t * @since 5.2\n\t */",
        ),
    ],
}
