"""Chinese JavaDoc replacements for RocketMQ wave46a tools [0:7]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicRouteSubCommand.java': [
        ('public class TopicRouteSubCommand implements SubCommand {',
         '/**\n * topicRoute 子命令：查询 Topic 路由信息。\n * <p>支持 JSON 输出或表格列表格式展示 Broker、队列数与权限。\n */\npublic class TopicRouteSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Examine topic route info.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Examine topic route info.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("l", "list", false, "Use list format to print data");',
         '        opt = new Option("l", "list", false, "以表格列表格式输出（默认 JSON）");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 查询 Topic 路由并按选项打印 JSON 或表格。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('    private void printData(TopicRouteData topicRouteData, boolean useListFormat) {',
         '    /** 按 JSON 或表格格式打印路由数据及队列汇总。 */\n    private void printData(TopicRouteData topicRouteData, boolean useListFormat) {'),
        ('        if (!useListFormat) {',
         '        // 未指定 -l 时输出完整 JSON\n        if (!useListFormat) {'),
        ('        for (int i = 0; i < 158; i++) {',
         '        // 打印分隔线后输出队列数汇总\n        for (int i = 0; i < 158; i++) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicStatusSubCommand.java': [
        ('public class TopicStatusSubCommand implements SubCommand {',
         '/**\n * topicStatus 子命令：查询 Topic 各队列位点与写入 TPS。\n * <p>支持通过集群或 LMQ 父 Topic 路由聚合多 Broker 统计。\n */\npublic class TopicStatusSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Examine topic Status info.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Examine topic Status info.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("c", "cluster", true, "cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic（用于路由查找）");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 查询 Topic 各队列 min/max 位点及最后更新时间。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            if (commandLine.hasOption(\'c\')) {',
         '            // 指定集群时遍历 Broker 聚合位点表\n            if (commandLine.hasOption(\'c\')) {'),
        ('            System.out.printf("Topic Put TPS: %s%n", topicStatsTable.getTopicPutTps());',
         '            // 打印 Topic 写入 TPS\n            System.out.printf("Topic Put TPS: %s%n", topicStatsTable.getTopicPutTps());'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateOrderConfCommand.java': [
        ('public class UpdateOrderConfCommand implements SubCommand {',
         '/**\n * updateOrderConf 子命令：管理顺序 Topic 的 Broker 队列映射配置。\n * <p>支持 get/put/delete 三种操作，配置存于 NameServer KV。\n */\npublic class UpdateOrderConfCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Create or update or delete order conf.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Create or update or delete order conf.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("v", "orderConf", true, "set order conf [eg. brokerName1:num;brokerName2:num]");',
         '        opt = new Option("v", "orderConf", true, "顺序配置（如 brokerName1:num;brokerName2:num）");'),
        ('        opt = new Option("m", "method", true, "option type [eg. put|get|delete");',
         '        opt = new Option("m", "method", true, "操作类型：put|get|delete");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 按 method 参数查询、更新或删除顺序 Topic 配置。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            if ("get".equals(type)) {',
         '            // 从 NameServer KV 读取顺序配置\n            if ("get".equals(type)) {'),
        ('            } else if ("put".equals(type)) {',
         '            // 创建或更新顺序 Topic 的 Broker 队列映射\n            } else if ("put".equals(type)) {'),
        ('            } else if ("delete".equals(type)) {',
         '            // 删除指定 Topic 的顺序配置\n            } else if ("delete".equals(type)) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateStaticTopicSubCommand.java': [
        ('public class UpdateStaticTopicSubCommand implements SubCommand {',
         '/**\n * updateStaticTopic 子命令：创建或更新静态 Topic（固定队列数）。\n * <p>支持按集群/Broker 重映射队列，或从映射文件导入配置。\n */\npublic class UpdateStaticTopicSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update or create static topic, which has fixed number of queues.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update or create static topic, which has fixed number of queues.";'),
        ('        opt = new Option("c", "clusters", true, "remapping static topic to clusters, comma separated");',
         '        opt = new Option("c", "clusters", true, "目标集群列表（逗号分隔）");'),
        ('        opt = new Option("b", "brokers", true, "remapping static topic to brokers, comma separated");',
         '        opt = new Option("b", "brokers", true, "目标 Broker 列表（逗号分隔）");'),
        ('        opt = new Option("t", "topic", true, "topic name");',
         '        opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("qn", "totalQueueNum", true, "total queue num");',
         '        opt = new Option("qn", "totalQueueNum", true, "静态 Topic 总队列数");'),
        ('        opt = new Option("mf", "mapFile", true, "The mapping data file name");',
         '        opt = new Option("mf", "mapFile", true, "队列映射数据文件路径");'),
        ('        opt = new Option("fr", "forceReplace", true, "Force replace the old mapping");',
         '        opt = new Option("fr", "forceReplace", true, "是否强制替换已有映射（true/false）");'),
        ('    public void executeFromFile(final CommandLine commandLine, final Options options,\n                        RPCHook rpcHook) throws SubCommandException {',
         '    /** 从映射文件解码配置并更新各 Broker 的静态 Topic 映射。 */\n    public void executeFromFile(final CommandLine commandLine, final Options options,\n                        RPCHook rpcHook) throws SubCommandException {'),
        ('            //double check the config',
         '            // 校验 Topic 名称、epoch 与队列数一致性'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 计算新队列映射、备份旧配置并下发至目标 Broker。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            //get the existed topic config and mapping',
         '            // 读取已有 Topic 配置与队列映射'),
        ('            //add the existed brokers to target brokers',
         '            // 将已有 Broker 并入目标集合以保证映射完整'),
        ('            //calculate the new data',
         '            // 计算新的队列映射并写入临时文件供审阅'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicListSubCommand.java': [
        ('public class UpdateTopicListSubCommand implements SubCommand {',
         '/**\n * updateTopicList 子命令：从 JSON 文件批量创建或更新 Topic。\n * <p>支持指定单个 Broker 或整个集群的全部 Master。\n */\npublic class UpdateTopicListSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "create or update topic in batch";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "create or update topic in batch";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "create topic to which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址");'),
        ('        opt = new Option("c", "clusterName", true, "create topic to which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名称");'),
        ('        opt = new Option("f", "filename", true, "Path to a file with list of org.apache.rocketmq.common.TopicConfig in json format");',
         '        opt = new Option("f", "filename", true, "TopicConfig 列表 JSON 文件路径");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 读取 JSON 文件并向 Broker 或集群批量提交 Topic 配置。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            if (!Files.exists(filePath)) {',
         '            // 文件不存在时提前退出\n            if (!Files.exists(filePath)) {'),
        ('            if (commandLine.hasOption(\'b\')) {',
         '            // 向单个 Broker 提交批量 Topic 配置\n            if (commandLine.hasOption(\'b\')) {'),
        ('            } else if (commandLine.hasOption(\'c\')) {',
         '            // 向集群全部 Master 逐一提交配置\n            } else if (commandLine.hasOption(\'c\')) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicPermSubCommand.java': [
        ('public class UpdateTopicPermSubCommand implements SubCommand {',
         '/**\n * updateTopicPerm 子命令：更新 Topic 读写权限。\n * <p>权限值：2=写、4=读、6=读写；可指定 Broker 或整个集群。\n */\npublic class UpdateTopicPermSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update topic perm.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update topic perm.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "create topic to which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址");'),
        ('        opt = new Option("c", "clusterName", true, "create topic to which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名称");'),
        ('        opt = new Option("t", "topic", true, "topic name");',
         '        opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("p", "perm", true, "set topic\'s permission(2|4|6), intro[2:W; 4:R; 6:RW]");',
         '        opt = new Option("p", "perm", true, "Topic 权限（2=写，4=读，6=读写）");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 读取路由信息并更新指定 Broker 或集群的 Topic 权限。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            //new perm',
         '            // 解析并设置新的读写权限位'),
        ('                for (BrokerData data : brokerDatas) {',
         '                // 按 Master Broker 地址反查 brokerName\n                for (BrokerData data : brokerDatas) {'),
        ('            } else if (commandLine.hasOption(\'c\')) {',
         '            // 向集群全部 Master 批量更新权限\n            } else if (commandLine.hasOption(\'c\')) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/UpdateTopicSubCommand.java': [
        ('public class UpdateTopicSubCommand implements SubCommand {',
         '/**\n * updateTopic 子命令：创建或更新单个 Topic 配置。\n * <p>支持队列数、权限、顺序消息、单元化及自定义属性。\n */\npublic class UpdateTopicSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update or create topic.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update or create topic.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "create topic to which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址");'),
        ('        opt = new Option("c", "clusterName", true, "create topic to which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名称");'),
        ('        opt = new Option("a", "attributes", true, "attribute(+a=b,+c=d,-e)");',
         '        opt = new Option("a", "attributes", true, "Topic 属性（+key=val 增改，-key 删除）");'),
        ('        opt = new Option("t", "topic", true, "topic name");',
         '        opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("r", "readQueueNums", true, "set read queue nums");',
         '        opt = new Option("r", "readQueueNums", true, "读队列数量");'),
        ('        opt = new Option("w", "writeQueueNums", true, "set write queue nums");',
         '        opt = new Option("w", "writeQueueNums", true, "写队列数量");'),
        ('        opt = new Option("p", "perm", true, "set topic\'s permission(2|4|6), intro[2:W 4:R; 6:RW]");',
         '        opt = new Option("p", "perm", true, "Topic 权限（2=写，4=读，6=读写）");'),
        ('        opt = new Option("o", "order", true, "set topic\'s order(true|false)");',
         '        opt = new Option("o", "order", true, "是否顺序 Topic（true/false）");'),
        ('        opt = new Option("u", "unit", true, "is unit topic (true|false)");',
         '        opt = new Option("u", "unit", true, "是否单元化 Topic（true/false）");'),
        ('        opt = new Option("s", "hasUnitSub", true, "has unit sub (true|false)");',
         '        opt = new Option("s", "hasUnitSub", true, "是否含单元订阅（true/false）");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 构建 TopicConfig 并下发至 Broker 或集群，顺序 Topic 同步 orderConf。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            // readQueueNums',
         '            // 解析读队列数（默认 8）'),
        ('            // writeQueueNums',
         '            // 解析写队列数（默认 8）'),
        ('            // perm',
         '            // 解析 Topic 读写权限'),
        ('            if (commandLine.hasOption(\'b\')) {',
         '            // 向单个 Broker 创建或更新 Topic\n            if (commandLine.hasOption(\'b\')) {'),
        ('            } else if (commandLine.hasOption(\'c\')) {',
         '            // 向集群全部 Master 创建 Topic 并设置顺序配置\n            } else if (commandLine.hasOption(\'c\')) {'),
    ],
}
