"""Chinese JavaDoc replacements for RocketMQ wave40b store/queue/rocksdb/stats/timer [15:30]."""

R: dict[str, list[tuple[str, str]]] = {
    'store/src/main/java/org/apache/rocketmq/store/queue/ReferredIterator.java': [
        ('public interface ReferredIterator<T> extends Iterator<T> {',
         '/**\n * 可释放资源的迭代器：遍历完成后须调用 {@link #release()} 释放底层引用。\n */\npublic interface ReferredIterator<T> extends Iterator<T> {'),
        ('/**\n     * Release the referred resources.\n     */',
         '/**\n     * 释放迭代器所引用的底层资源。\n     */'),
        ('    void release();',
         '    /** 释放迭代器引用的底层资源。 */\n    void release();'),
        ('    T nextAndRelease();',
         '    /** 返回下一元素并释放资源。 */\n    T nextAndRelease();'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/queue/RocksDBConsumeQueueTable.java': [
        ("/**\n     * Rocksdb ConsumeQueue's store unit. Format:\n     *\n     * <pre>\n     * ┌─────────────────────────┬───────────┬───────────────────────┬───────────┬───────────┬───────────┬───────────────────────┐\n     * │ Topic Bytes Array Size  │  CTRL_1   │   Topic Bytes Array   │  CTRL_1   │  QueueId  │  CTRL_1   │  ConsumeQueue Offset  │\n     * │        (4 Bytes)        │ (1 Bytes) │       (n Bytes)       │ (1 Bytes) │ (4 Bytes) │ (1 Bytes) │     (8 Bytes)         │\n     * ├─────────────────────────┴───────────┴───────────────────────┴───────────┴───────────┴───────────┴───────────────────────┤\n     * │                                                    Key Unit                                                             │\n     * │                                                                                                                         │\n     * </pre>\n     *\n     * <pre>\n     * ┌─────────────────────────────┬───────────────────┬──────────────────┬──────────────────┐\n     * │  CommitLog Physical Offset  │      Body Size    │   Tag HashCode   │  Msg Store Time  │\n     * │        (8 Bytes)            │      (4 Bytes)    │    (8 Bytes)     │    (8 Bytes)     │\n     * ├─────────────────────────────┴───────────────────┴──────────────────┴──────────────────┤\n     * │                                                    Value Unit                         │\n     * │                                                                                       │\n     * </pre>\n     * ConsumeQueue's store unit. Size:\n     * CommitLog Physical Offset(8) + Body Size(4) + Tag HashCode(8) + Msg Store Time(8) = 28 Bytes\n     */",
         '/**\n     * RocksDB 消费队列存储单元格式说明。\n     *\n     * <pre>\n     * ┌─────────────────────────┬───────────┬───────────────────────┬───────────┬───────────┬───────────┬───────────────────────┐\n     * │ Topic Bytes Array Size  │  CTRL_1   │   Topic Bytes Array   │  CTRL_1   │  QueueId  │  CTRL_1   │  ConsumeQueue Offset  │\n     * │        (4 Bytes)        │ (1 Bytes) │       (n Bytes)       │ (1 Bytes) │ (4 Bytes) │ (1 Bytes) │     (8 Bytes)         │\n     * ├─────────────────────────┴───────────┴───────────────────────┴───────────┴───────────┴───────────┴───────────────────────┤\n     * │                                                    Key Unit                                                             │\n     * │                                                                                                                         │\n     * </pre>\n     *\n     * <pre>\n     * ┌─────────────────────────────┬───────────────────┬──────────────────┬──────────────────┐\n     * │  CommitLog Physical Offset  │      Body Size    │   Tag HashCode   │  Msg Store Time  │\n     * │        (8 Bytes)            │      (4 Bytes)    │    (8 Bytes)     │    (8 Bytes)     │\n     * ├─────────────────────────────┴───────────────────┴──────────────────┴──────────────────┤\n     * │                                                    Value Unit                         │\n     * │                                                                                       │\n     * </pre>\n     * 单条 value 固定 28 字节：物理偏移(8)+消息体长(4)+Tag哈希(8)+存储时间(8)。\n     */'),
        ('/**\n     * When topic is deleted, we clean up its CqUnit in rocksdb.\n     * @param topic\n     * @param queueId\n     * @throws RocksDBException\n     */',
         '/**\n     * Topic 删除时清理其在 RocksDB 中的 CqUnit 记录。\n     * @param topic Topic 名称\n     * @param queueId 队列 ID\n     * @throws RocksDBException RocksDB 操作异常\n     */'),
        ('public RocksDBConsumeQueueTable(ConsumeQueueRocksDBStorage rocksDBStorage, DefaultMessageStore messageStore) {',
         '    /** 绑定 RocksDB 存储与 MessageStore。 */\n    public RocksDBConsumeQueueTable(ConsumeQueueRocksDBStorage rocksDBStorage, DefaultMessageStore messageStore) {'),
        ('    private final ConsumeQueueRocksDBStorage rocksDBStorage;',
         '    /** 底层 RocksDB 存储引擎。 */\n    private final ConsumeQueueRocksDBStorage rocksDBStorage;'),
        ('/**\n * We use RocksDBConsumeQueueTable to store cqUnit.\n */',
         '/**\n * 基于 RocksDB 的消费队列表：持久化 cqUnit 键值对。\n */'),
        ('    private final DefaultMessageStore messageStore;',
         '    /** 所属 MessageStore。 */\n    private final DefaultMessageStore messageStore;'),
        ('    private static final Logger ROCKSDB_LOG =',
         '    /** RocksDB 专用日志。 */\n    private static final Logger ROCKSDB_LOG ='),
        ('    private static final Logger ERROR_LOG =',
         '    /** 存储错误日志。 */\n    private static final Logger ERROR_LOG ='),
        ('    private ColumnFamilyHandle defaultCFH;',
         '    /** 默认列族句柄（cqUnit）。 */\n    private ColumnFamilyHandle defaultCFH;'),
        ('    public static final int CQ_UNIT_SIZE =',
         '    /** cqUnit value 固定长度（28 字节）。 */\n    public static final int CQ_UNIT_SIZE ='),
        ('public class RocksDBConsumeQueueTable {',
         '/**\n * RocksDB 消费队列表：构建/查询/删除 cqUnit，支持按时间与物理偏移二分查找。\n */\npublic class RocksDBConsumeQueueTable {'),
        ('    private static final Logger log =',
         '    /** 存储模块日志。 */\n    private static final Logger log ='),
        ('    public void load() {',
         '    /** 加载默认列族句柄。 */\n    public void load() {'),
        ('    public void buildAndPutCQByteBuffer(final Pair<ByteBuffer, ByteBuffer> cqBBPair, final DispatchEntry request,',
         '    /** 构建 cq key/value 并写入 WriteBatch。 */\n    public void buildAndPutCQByteBuffer(final Pair<ByteBuffer, ByteBuffer> cqBBPair, final DispatchEntry request,'),
        ('    public ByteBuffer getCQInKV(final String topic, final int queueId, final long cqOffset) throws RocksDBException {',
         '    /** 按 topic/queueId/cqOffset 读取 cq value。 */\n    public ByteBuffer getCQInKV(final String topic, final int queueId, final long cqOffset) throws RocksDBException {'),
        ('    public List<ByteBuffer> rangeQuery(final String topic, final int queueId, final long startIndex, final int num) throws RocksDBException {',
         '    /** 批量读取连续 cq offset 的 value 列表。 */\n    public List<ByteBuffer> rangeQuery(final String topic, final int queueId, final long startIndex, final int num) throws RocksDBException {'),
        ('    public void destroyCQ(final String topic, final int queueId, WriteBatch writeBatch) throws RocksDBException {',
         '    /** 删除 topic+queueId 下全部 cq 键范围。 */\n    public void destroyCQ(final String topic, final int queueId, WriteBatch writeBatch) throws RocksDBException {'),
        ('    public long binarySearchInCQByTime(String topic, int queueId, long high, long low, long timestamp,',
         '    /** 在 cq 中按消息存储时间二分查找 offset。 */\n    public long binarySearchInCQByTime(String topic, int queueId, long high, long low, long timestamp,'),
        ('    public PhyAndCQOffset binarySearchInCQ(String topic, int queueId, long high, long low, long targetPhyOffset,',
         '    /** 在 cq 中按 CommitLog 物理偏移二分查找。 */\n    public PhyAndCQOffset binarySearchInCQ(String topic, int queueId, long high, long low, long targetPhyOffset,'),
        ('    public static Pair<ByteBuffer, ByteBuffer> getCQByteBufferPair() {',
         '    /** 分配 Direct ByteBuffer 键值对供 cq 写入复用。 */\n    public static Pair<ByteBuffer, ByteBuffer> getCQByteBufferPair() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/queue/RocksGroupCommitService.java': [
        ('public RocksGroupCommitService(RocksDBConsumeQueueStore store) {',
         '    /** 构造组提交服务。 */\n    public RocksGroupCommitService(RocksDBConsumeQueueStore store) {'),
        ('    private static final int PREFERRED_DISPATCH_REQUEST_COUNT =',
         '    /** 单次组提交 preferred 批大小。 */\n    private static final int PREFERRED_DISPATCH_REQUEST_COUNT ='),
        ('    private final LinkedBlockingQueue<DispatchRequest> buffer;',
         '    /** 待提交的 DispatchRequest 缓冲队列。 */\n    private final LinkedBlockingQueue<DispatchRequest> buffer;'),
        ('public class RocksGroupCommitService extends ServiceThread {',
         '/**\n * RocksDB 消费队列组提交服务：批量聚合 DispatchRequest 后写入 RocksDB。\n */\npublic class RocksGroupCommitService extends ServiceThread {'),
        ('    private final List<DispatchRequest> requests =',
         '    /** 当前批次聚合的请求列表。 */\n    private final List<DispatchRequest> requests ='),
        ('    private final RocksDBConsumeQueueStore store;',
         '    /** 目标 RocksDB 消费队列存储。 */\n    private final RocksDBConsumeQueueStore store;'),
        ('    private static final int MAX_BUFFER_SIZE =',
         '    /** 组提交缓冲队列容量上限。 */\n    private static final int MAX_BUFFER_SIZE ='),
        ('    @Override\n    public String getServiceName() {',
         '    /** {@inheritDoc} */\n    @Override\n    public String getServiceName() {'),
        ('    @Override\n    public void run() {',
         '    /** 后台循环：等待请求并批量组提交。 */\n    @Override\n    public void run() {'),
        ('    public void putRequest(final DispatchRequest request) throws InterruptedException {',
         '    /** 入队分发请求并唤醒提交线程。 */\n    public void putRequest(final DispatchRequest request) throws InterruptedException {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/queue/offset/OffsetEntry.java': [
        ("/**\n     * Topic identifier. For now, it's topic name directly. In the future, we should use fixed length topic identifier.\n     */",
         '/**\n     * Topic 标识；当前直接使用 Topic 名称，后续可改为定长标识。\n     */'),
        ('/**\n     * Flag if the entry is for maximum or minimum\n     */',
         '/**\n     * 标记该条目表示最大值还是最小值。\n     */'),
        ('/**\n     * Maximum or minimum consume-queue offset.\n     */',
         '/**\n     * 消费队列的最大或最小偏移量。\n     */'),
        ('/**\n     * Maximum or minimum commit-log offset.\n     */',
         '/**\n     * CommitLog 的最大或最小物理偏移。\n     */'),
        ('    public OffsetEntryType type;',
         '    /** 最大/最小类型。 */\n    public OffsetEntryType type;'),
        ('/**\n     * Queue ID\n     */',
         '/**\n     * 队列 ID。\n     */'),
        ('public class OffsetEntry {',
         '/**\n * 消费队列与 CommitLog 偏移边界条目（最大/最小）。\n */\npublic class OffsetEntry {'),
        ('    public String topic;',
         '    /** Topic 标识。 */\n    public String topic;'),
        ('    public int queueId;',
         '    /** 队列 ID。 */\n    public int queueId;'),
        ('    public long offset;',
         '    /** 消费队列偏移。 */\n    public long offset;'),
        ('    public long commitLogOffset;',
         '    /** CommitLog 物理偏移。 */\n    public long commitLogOffset;'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/queue/offset/OffsetEntryType.java': [
        ('public enum OffsetEntryType {',
         '/**\n * 偏移条目类型：最大值或最小值。\n */\npublic enum OffsetEntryType {'),
        ('    MAXIMUM,',
         '    /** 最大值边界。 */\n    MAXIMUM,'),
        ('    MINIMUM\n',
         '    /** 最小值边界。 */\n    MINIMUM\n'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/rocksdb/ConsumeQueueCompactionFilterFactory.java': [
        ('public class ConsumeQueueCompactionFilterFactory extends AbstractCompactionFilterFactory<RemoveConsumeQueueCompactionFilter> {',
         '/**\n * 消费队列 Compaction 过滤器工厂：Compaction 时按最小物理偏移清理过期 cqUnit。\n */\npublic class ConsumeQueueCompactionFilterFactory extends AbstractCompactionFilterFactory<RemoveConsumeQueueCompactionFilter> {'),
        ('public ConsumeQueueCompactionFilterFactory(final LongSupplier minPhyOffsetSupplier) {',
         '    /** @param minPhyOffsetSupplier 最小物理偏移供应器 */\n    public ConsumeQueueCompactionFilterFactory(final LongSupplier minPhyOffsetSupplier) {'),
        ('    private final LongSupplier minPhyOffsetSupplier;',
         '    /** 提供当前最小 CommitLog 物理偏移。 */\n    private final LongSupplier minPhyOffsetSupplier;'),
        ('    @Override\n    public String name() {',
         '    /** Compaction 过滤器工厂名称。 */\n    @Override\n    public String name() {'),
        ('    @Override\n    public RemoveConsumeQueueCompactionFilter createCompactionFilter(final AbstractCompactionFilter.Context context) {',
         '    /** 创建带当前最小物理偏移的 Compaction 过滤器。 */\n    @Override\n    public RemoveConsumeQueueCompactionFilter createCompactionFilter(final AbstractCompactionFilter.Context context) {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/rocksdb/ConsumeQueueRocksDBStorage.java': [
        ('public ConsumeQueueRocksDBStorage(final MessageStore messageStore, final String dbPath) {',
         '    /** @param messageStore 所属 MessageStore @param dbPath RocksDB 目录 */\n    public ConsumeQueueRocksDBStorage(final MessageStore messageStore, final String dbPath) {'),
        ('public class ConsumeQueueRocksDBStorage extends AbstractRocksDBStorage {',
         '/**\n * 消费队列 RocksDB 存储引擎：管理默认 CF 与 offset CF。\n */\npublic class ConsumeQueueRocksDBStorage extends AbstractRocksDBStorage {'),
        ('    private ConsumeQueueCompactionFilterFactory compactionFilterFactory;',
         '    /** Compaction 过滤器工厂。 */\n    private ConsumeQueueCompactionFilterFactory compactionFilterFactory;'),
        ('    private volatile ColumnFamilyHandle offsetCFHandle;',
         '    /** offset 列族句柄。 */\n    private volatile ColumnFamilyHandle offsetCFHandle;'),
        ('    public static final byte[] OFFSET_COLUMN_FAMILY =',
         '    /** offset 列族名称字节。 */\n    public static final byte[] OFFSET_COLUMN_FAMILY ='),
        ('    private final MessageStore messageStore;',
         '    /** 所属 MessageStore。 */\n    private final MessageStore messageStore;'),
        ('    protected void initOptions() {',
         '    /** 初始化 DB 与列族选项。 */\n    protected void initOptions() {'),
        ('    protected boolean postLoad() {',
         '    /** 打开 RocksDB 并注册 CQ/Offset 列族。 */\n    protected boolean postLoad() {'),
        ('    protected void preShutdown() {',
         '    /** 关闭 offset CF 与 compaction 过滤器工厂。 */\n    protected void preShutdown() {'),
        ('    public byte[] getCQ(final byte[] keyBytes) throws RocksDBException {',
         '    /** 按 key 读取消费队列 value。 */\n    public byte[] getCQ(final byte[] keyBytes) throws RocksDBException {'),
        ('    public byte[] getOffset(final byte[] keyBytes) throws RocksDBException {',
         '    /** 按 key 读取 offset 列族 value。 */\n    public byte[] getOffset(final byte[] keyBytes) throws RocksDBException {'),
        ('    public List<byte[]> multiGet(final List<ColumnFamilyHandle> cfhList,',
         '    /** 批量 multiGet。 */\n    public List<byte[]> multiGet(final List<ColumnFamilyHandle> cfhList,'),
        ('    public void batchPut(final WriteBatch batch) throws RocksDBException {',
         '    /** 批量写入 WriteBatch。 */\n    public void batchPut(final WriteBatch batch) throws RocksDBException {'),
        ('    public void manualCompaction(final long minPhyOffset) {',
         '    /** 触发手动 Compaction，清理低于 minPhyOffset 的 cqUnit。 */\n    public void manualCompaction(final long minPhyOffset) {'),
        ('    public RocksIterator seekOffsetCF() {',
         '    /** 创建 offset 列族迭代器。 */\n    public RocksIterator seekOffsetCF() {'),
        ('    public ColumnFamilyHandle getOffsetCFHandle() {',
         '    /** 返回 offset 列族句柄。 */\n    public ColumnFamilyHandle getOffsetCFHandle() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/rocksdb/RocksDBOptionsFactory.java': [
        ('/**\n     * Create a rocksdb db options, the user must take care to close it after closing db.\n     * @return\n     */',
         '/**\n     * 创建 RocksDB {@link DBOptions}；关闭 DB 后须由调用方负责关闭该对象。\n     * @return DBOptions 实例\n     */'),
        ('public class RocksDBOptionsFactory {',
         '/**\n * RocksDB 列族与 DB 选项工厂：为 CQ、Offset、Timer 等场景提供调优配置。\n */\npublic class RocksDBOptionsFactory {'),
        ('    public static ColumnFamilyOptions createCQCFOptions(final MessageStore messageStore,',
         '    /** 创建消费队列列族选项（Universal Compaction + Bloom）。 */\n    public static ColumnFamilyOptions createCQCFOptions(final MessageStore messageStore,'),
        ('    public static ColumnFamilyOptions createOffsetCFOptions() {',
         '    /** 创建 offset 列族选项（Level Compaction）。 */\n    public static ColumnFamilyOptions createOffsetCFOptions() {'),
        ('    public static ColumnFamilyOptions createPopCFOptions() {',
         '    /** 创建 Pop 消息列族选项。 */\n    public static ColumnFamilyOptions createPopCFOptions() {'),
        ('    public static ColumnFamilyOptions createTimerCFOptions() {',
         '    /** 创建 Timer 列族选项。 */\n    public static ColumnFamilyOptions createTimerCFOptions() {'),
        ('    public static ColumnFamilyOptions createTransCFOptions() {',
         '    /** 创建事务列族选项。 */\n    public static ColumnFamilyOptions createTransCFOptions() {'),
        ('    public static ColumnFamilyOptions createIndexCFOptions() {',
         '    /** 创建索引列族选项。 */\n    public static ColumnFamilyOptions createIndexCFOptions() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/stats/BrokerStats.java': [
        ('    private volatile long msgPutTotalYesterdayMorning;',
         '    /** 昨日早晨 put 累计快照。 */\n    private volatile long msgPutTotalYesterdayMorning;'),
        ('    private volatile long msgGetTotalYesterdayMorning;',
         '    /** 昨日早晨 get 累计快照。 */\n    private volatile long msgGetTotalYesterdayMorning;'),
        ('public BrokerStats(MessageStore defaultMessageStore) {',
         '    /** @param defaultMessageStore 消息存储实例 */\n    public BrokerStats(MessageStore defaultMessageStore) {'),
        ('    private final MessageStore defaultMessageStore;',
         '    /** 关联的 MessageStore。 */\n    private final MessageStore defaultMessageStore;'),
        ('    private volatile long msgPutTotalTodayMorning;',
         '    /** 今日早晨 put 累计快照。 */\n    private volatile long msgPutTotalTodayMorning;'),
        ('    private volatile long msgGetTotalTodayMorning;',
         '    /** 今日早晨 get 累计快照。 */\n    private volatile long msgGetTotalTodayMorning;'),
        ('    private static final Logger log =',
         '    /** 存储模块日志。 */\n    private static final Logger log ='),
        ('public class BrokerStats {',
         '/**\n * Broker 级消息收发日统计：记录昨日与今日累计 put/get 数量。\n */\npublic class BrokerStats {'),
        ('    public void record() {',
         '    /** 滚动记录昨日/今日消息 put 与 get 累计值。 */\n    public void record() {'),
        ('    public long getMsgPutTotalYesterdayMorning() {',
         '    /** 昨日早晨 put 累计快照。 */\n    public long getMsgPutTotalYesterdayMorning() {'),
        ('    public void setMsgPutTotalYesterdayMorning(long msgPutTotalYesterdayMorning) {',
         '    /** 设置昨日早晨 put 累计快照。 */\n    public void setMsgPutTotalYesterdayMorning(long msgPutTotalYesterdayMorning) {'),
        ('    public long getMsgPutTotalTodayMorning() {',
         '    /** 今日早晨 put 累计快照。 */\n    public long getMsgPutTotalTodayMorning() {'),
        ('    public void setMsgPutTotalTodayMorning(long msgPutTotalTodayMorning) {',
         '    /** 设置今日早晨 put 累计快照。 */\n    public void setMsgPutTotalTodayMorning(long msgPutTotalTodayMorning) {'),
        ('    public long getMsgGetTotalYesterdayMorning() {',
         '    /** 昨日早晨 get 累计快照。 */\n    public long getMsgGetTotalYesterdayMorning() {'),
        ('    public void setMsgGetTotalYesterdayMorning(long msgGetTotalYesterdayMorning) {',
         '    /** 设置昨日早晨 get 累计快照。 */\n    public void setMsgGetTotalYesterdayMorning(long msgGetTotalYesterdayMorning) {'),
        ('    public long getMsgGetTotalTodayMorning() {',
         '    /** 今日早晨 get 累计快照。 */\n    public long getMsgGetTotalTodayMorning() {'),
        ('    public void setMsgGetTotalTodayMorning(long msgGetTotalTodayMorning) {',
         '    /** 设置今日早晨 get 累计快照。 */\n    public void setMsgGetTotalTodayMorning(long msgGetTotalTodayMorning) {'),
        ('    public long getMsgPutTotalTodayNow() {',
         '    /** 当前 put 累计（不含系统 Topic）。 */\n    public long getMsgPutTotalTodayNow() {'),
        ('    public long getMsgGetTotalTodayNow() {',
         '    /** 当前 get 累计（不含系统 Topic）。 */\n    public long getMsgGetTotalTodayNow() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/stats/LmqBrokerStatsManager.java': [
        ('public class LmqBrokerStatsManager extends BrokerStatsManager {',
         '/**\n * LMQ 场景下的 Broker 统计管理器：未启用 LMQ 统计时将 LMQ 前缀归一化。\n */\npublic class LmqBrokerStatsManager extends BrokerStatsManager {'),
        ('public LmqBrokerStatsManager(BrokerConfig brokerConfig) {',
         '    /** @param brokerConfig Broker 配置 */\n    public LmqBrokerStatsManager(BrokerConfig brokerConfig) {'),
        ('    private final BrokerConfig brokerConfig;',
         '    /** Broker 配置。 */\n    private final BrokerConfig brokerConfig;'),
        ('    @Override\n    public void incGroupGetNums(final String group, final String topic, final int incValue) {',
         '    /** LMQ 组名/Topic 归一化后递增 get 次数。 */\n    @Override\n    public void incGroupGetNums(final String group, final String topic, final int incValue) {'),
        ('    @Override\n    public void incGroupGetSize(final String group, final String topic, final int incValue) {',
         '    /** LMQ 组名/Topic 归一化后递增 get 字节量。 */\n    @Override\n    public void incGroupGetSize(final String group, final String topic, final int incValue) {'),
        ('    @Override\n    public void incGroupAckNums(final String group, final String topic, final int incValue) {',
         '    /** LMQ 组名/Topic 归一化后递增 ack 次数。 */\n    @Override\n    public void incGroupAckNums(final String group, final String topic, final int incValue) {'),
        ('    @Override\n    public void incGroupCkNums(final String group, final String topic, final int incValue) {',
         '    /** LMQ 组名/Topic 归一化后递增 ck 次数。 */\n    @Override\n    public void incGroupCkNums(final String group, final String topic, final int incValue) {'),
        ('    @Override\n    public void incGroupGetLatency(final String group, final String topic, final int queueId, final int incValue) {',
         '    /** LMQ 组名/Topic 归一化后记录 get 延迟。 */\n    @Override\n    public void incGroupGetLatency(final String group, final String topic, final int queueId, final int incValue) {'),
        ('    @Override\n    public void incSendBackNums(final String group, final String topic) {',
         '    /** LMQ 组名/Topic 归一化后递增退避次数。 */\n    @Override\n    public void incSendBackNums(final String group, final String topic) {'),
        ('    @Override\n    public double tpsGroupGetNums(final String group, final String topic) {',
         '    /** LMQ 组名/Topic 归一化后查询 get TPS。 */\n    @Override\n    public double tpsGroupGetNums(final String group, final String topic) {'),
        ('    @Override\n    public void recordDiskFallBehindTime(final String group, final String topic, final int queueId,',
         '    /** LMQ 组名/Topic 归一化后记录磁盘落后时间。 */\n    @Override\n    public void recordDiskFallBehindTime(final String group, final String topic, final int queueId,'),
        ('    @Override\n    public void recordDiskFallBehindSize(final String group, final String topic, final int queueId,',
         '    /** LMQ 组名/Topic 归一化后记录磁盘落后字节量。 */\n    @Override\n    public void recordDiskFallBehindSize(final String group, final String topic, final int queueId,'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/timer/Slot.java': [
        ('/**\n * Represents a slot of timing wheel. Format:\n * ┌────────────┬───────────┬───────────┬───────────┬───────────┐\n * │delayed time│ first pos │ last pos  │    num    │   magic   │\n * ├────────────┼───────────┼───────────┼───────────┼───────────┤\n * │   8bytes   │   8bytes  │  8bytes   │   4bytes  │   4bytes  │\n * └────────────┴───────────┴───────────┴───────────┴───────────┘\n */',
         '/**\n * 时间轮槽位数据结构，二进制布局如下：\n * ┌────────────┬───────────┬───────────┬───────────┬───────────┐\n * │delayed time│ first pos │ last pos  │    num    │   magic   │\n * ├────────────┼───────────┼───────────┼───────────┼───────────┤\n * │   8bytes   │   8bytes  │  8bytes   │   4bytes  │   4bytes  │\n * └────────────┴───────────┴───────────┴───────────┴───────────┘\n */'),
        ('public Slot(long timeMs, long firstPos, long lastPos, int num, int magic) {',
         '    /** 构造完整槽位。 */\n    public Slot(long timeMs, long firstPos, long lastPos, int num, int magic) {'),
        ('public Slot(long timeMs, long firstPos, long lastPos) {',
         '    /** 构造空计数槽位。 */\n    public Slot(long timeMs, long firstPos, long lastPos) {'),
        ('    public static final short SIZE = 32;',
         '    /** 槽位序列化大小（32 字节）。 */\n    public static final short SIZE = 32;'),
        ('public class Slot {',
         '/**\n * 时间轮槽位：记录延迟触发时间与 TimerLog 链表头尾位置。\n */\npublic class Slot {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/timer/TimerCheckpoint.java': [
        ('    private volatile long lastReadTimeMs = 0; //if it is slave, need to read from master',
         '    /** 最近一次扫描时间轮的时间（从节点时从主节点同步）。 */\n    private volatile long lastReadTimeMs = 0;'),
        ('    private volatile long masterTimerQueueOffset = 0; // read from master',
         '    /** 主节点 TimerQueue 偏移（从节点读取）。 */\n    private volatile long masterTimerQueueOffset = 0;'),
        ('public TimerCheckpoint(final String scpPath) throws IOException {',
         '    /** 打开或创建 mmap 检查点文件。 */\n    public TimerCheckpoint(final String scpPath) throws IOException {'),
        ('    private volatile long lastTimerLogFlushPos = 0;',
         '    /** TimerLog 已刷盘物理位置。 */\n    private volatile long lastTimerLogFlushPos = 0;'),
        ('    private volatile long lastTimerQueueOffset = 0;',
         '    /** TimerQueue 消费偏移。 */\n    private volatile long lastTimerQueueOffset = 0;'),
        ('    private static final Logger log =',
         '    /** 存储模块日志。 */\n    private static final Logger log ='),
        ('public class TimerCheckpoint {',
         '/**\n * 定时消息检查点：mmap 持久化读取进度、TimerLog 刷盘位与队列偏移。\n */\npublic class TimerCheckpoint {'),
        ('public TimerCheckpoint() {',
         '    /** 空构造（decode 用）。 */\n    public TimerCheckpoint() {'),
        ('    public void shutdown() {',
         '    /** 刷盘并释放 mmap/文件句柄。 */\n    public void shutdown() {'),
        ('    public void flush() {',
         '    /** 将检查点字段写入 mmap 并 force。 */\n    public void flush() {'),
        ('    public static ByteBuffer encode(TimerCheckpoint another) {',
         '    /** 序列化检查点为 ByteBuffer。 */\n    public static ByteBuffer encode(TimerCheckpoint another) {'),
        ('    public static TimerCheckpoint decode(ByteBuffer byteBuffer) {',
         '    /** 从 ByteBuffer 反序列化检查点。 */\n    public static TimerCheckpoint decode(ByteBuffer byteBuffer) {'),
        ('    public void updateDataVersion(long stateVersion) {',
         '    /** 递增数据版本号。 */\n    public void updateDataVersion(long stateVersion) {'),
        ('    public DataVersion getDataVersion() {',
         '    /** 返回数据版本对象。 */\n    public DataVersion getDataVersion() {'),
        ('    public long getLastReadTimeMs() {',
         '    /** 返回最近读取时间轮时间。 */\n    public long getLastReadTimeMs() {'),
        ('    public void setLastReadTimeMs(long lastReadTimeMs) {',
         '    /** 设置最近读取时间轮时间。 */\n    public void setLastReadTimeMs(long lastReadTimeMs) {'),
        ('    public long getLastTimerLogFlushPos() {',
         '    /** 返回 TimerLog 刷盘位置。 */\n    public long getLastTimerLogFlushPos() {'),
        ('    public void setLastTimerLogFlushPos(long lastTimerLogFlushPos) {',
         '    /** 设置 TimerLog 刷盘位置。 */\n    public void setLastTimerLogFlushPos(long lastTimerLogFlushPos) {'),
        ('    public long getLastTimerQueueOffset() {',
         '    /** 返回 TimerQueue 偏移。 */\n    public long getLastTimerQueueOffset() {'),
        ('    public void setLastTimerQueueOffset(long lastTimerQueueOffset) {',
         '    /** 设置 TimerQueue 偏移。 */\n    public void setLastTimerQueueOffset(long lastTimerQueueOffset) {'),
        ('    public long getMasterTimerQueueOffset() {',
         '    /** 返回主节点 TimerQueue 偏移。 */\n    public long getMasterTimerQueueOffset() {'),
        ('    public void setMasterTimerQueueOffset(final long masterTimerQueueOffset) {',
         '    /** 设置主节点 TimerQueue 偏移。 */\n    public void setMasterTimerQueueOffset(final long masterTimerQueueOffset) {'),
        ('    private final DataVersion dataVersion = new DataVersion();',
         '    /** 检查点数据版本。 */\n    private final DataVersion dataVersion = new DataVersion();'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/timer/TimerLog.java': [
        ('public TimerLog(final String storePath, final int fileSize, RunningFlags runningFlags, boolean writeWithoutMmap) {',
         '    /** 完整构造 TimerLog。 */\n    public TimerLog(final String storePath, final int fileSize, RunningFlags runningFlags, boolean writeWithoutMmap) {'),
        ('public TimerLog(final String storePath, final int fileSize) {',
         '    /** 指定路径与文件大小。 */\n    public TimerLog(final String storePath, final int fileSize) {'),
        ('    public final static int UNIT_PRE_SIZE_FOR_METRIC =',
         '    /** 指标类 Timer 单元前缀长度。 */\n    public final static int UNIT_PRE_SIZE_FOR_METRIC ='),
        ('    public final static int UNIT_PRE_SIZE_FOR_MSG =',
         '    /** 消息类 Timer 单元前缀长度。 */\n    public final static int UNIT_PRE_SIZE_FOR_MSG ='),
        ('    private final MappedFileQueue mappedFileQueue;',
         '    /** TimerLog 映射文件队列。 */\n    private final MappedFileQueue mappedFileQueue;'),
        ('    public final static int BLANK_MAGIC_CODE =',
         '    /** TimerLog 文件尾空白块魔数。 */\n    public final static int BLANK_MAGIC_CODE ='),
        ('    public final static int UNIT_SIZE =',
         '    /** 单条 Timer 单元字节长度。 */\n    public final static int UNIT_SIZE ='),
        ('    private final int fileSize;',
         '    /** 单个映射文件大小。 */\n    private final int fileSize;'),
        ('public class TimerLog {',
         '/**\n * 定时消息日志：基于 MappedFileQueue 追加/读取 Timer 单元。\n */\npublic class TimerLog {'),
        ('    public boolean load() {',
         '    /** 加载 TimerLog 映射文件队列。 */\n    public boolean load() {'),
        ('    public long append(byte[] data) {',
         '    /** 追加字节数组到 TimerLog。 */\n    public long append(byte[] data) {'),
        ('    public long append(byte[] data, int pos, int len) {',
         '    /** 追加字节数组指定区间到 TimerLog。 */\n    public long append(byte[] data, int pos, int len) {'),
        ('    public SelectMappedBufferResult getTimerMessage(long offsetPy) {',
         '    /** 按物理偏移读取 Timer 消息体。 */\n    public SelectMappedBufferResult getTimerMessage(long offsetPy) {'),
        ('    public SelectMappedBufferResult getWholeBuffer(long offsetPy) {',
         '    /** 返回包含 offset 的整文件映射缓冲。 */\n    public SelectMappedBufferResult getWholeBuffer(long offsetPy) {'),
        ('    public MappedFileQueue getMappedFileQueue() {',
         '    /** 返回底层 MappedFileQueue。 */\n    public MappedFileQueue getMappedFileQueue() {'),
        ('    public void shutdown() {',
         '    /** 刷盘并清理全部映射资源。 */\n    public void shutdown() {'),
        ('    public int getOffsetForLastUnit() {',
         '    /** 计算当前文件最后一个 Timer 单元的写入偏移（格式变更时需同步修改）。 */\n    public int getOffsetForLastUnit() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/timer/TimerMetrics.java': [
        ('    private final ConcurrentMap<Integer, Metric> timingDistribution =',
         '    /** 延迟桶（秒）-> 分布计数。 */\n    private final ConcurrentMap<Integer, Metric> timingDistribution ='),
        ('    private final ConcurrentMap<String, Metric> timingCount =',
         '    /** Topic -> 定时消息计数。 */\n    private final ConcurrentMap<String, Metric> timingCount ='),
        ('public class TimerMetrics extends ConfigManager {',
         '/**\n * 定时消息指标：按 Topic 与延迟分布桶统计定时消息数量。\n */\npublic class TimerMetrics extends ConfigManager {'),
        ('public String encode(boolean prettyFormat) {',
         '    /** {@inheritDoc} */\n    public String encode(boolean prettyFormat) {'),
        ('public TimerMetrics(String configPath) {',
         '    /** @param configPath 指标持久化路径 */\n    public TimerMetrics(String configPath) {'),
        ('public void decode(String jsonString) {',
         '    /** {@inheritDoc} 从 JSON 恢复指标。 */\n    public void decode(String jsonString) {'),
        ('    private static final Logger log =',
         '    /** 存储模块日志。 */\n    private static final Logger log ='),
        ('public synchronized void persist() {',
         '    /** 原子备份并持久化指标 JSON 文件。 */\n    public synchronized void persist() {'),
        ('    private final String configPath;',
         '    /** 指标 JSON 持久化路径。 */\n    private final String configPath;'),
        ('public String configFilePath() {',
         '    /** {@inheritDoc} */\n    public String configFilePath() {'),
        ('public String encode() {',
         '    /** {@inheritDoc} */\n    public String encode() {'),
        ('    public long updateDistPair(int period, int value) {',
         '    /** 按延迟分布桶累加计数。 */\n    public long updateDistPair(int period, int value) {'),
        ('    public long addAndGet(MessageExt msg, int value) {',
         '    /** 按真实 Topic 累加定时消息计数并刷新版本。 */\n    public long addAndGet(MessageExt msg, int value) {'),
        ('    public Metric getDistPair(Integer period) {',
         '    /** 获取或创建延迟分布桶指标。 */\n    public Metric getDistPair(Integer period) {'),
        ('    public Metric getTopicPair(String topic) {',
         '    /** 获取或创建 Topic 级指标。 */\n    public Metric getTopicPair(String topic) {'),
        ('    public List<Integer> getTimerDistList() {',
         '    /** 返回延迟分布桶边界列表（秒）。 */\n    public List<Integer> getTimerDistList() {'),
        ('    public void setTimerDistList(List<Integer> timerDist) {',
         '    /** 设置延迟分布桶边界。 */\n    public void setTimerDistList(List<Integer> timerDist) {'),
        ('    public long getTimingCount(String topic) {',
         '    /** 查询指定 Topic 定时消息累计数。 */\n    public long getTimingCount(String topic) {'),
        ('    public Map<String, Metric> getTimingCount() {',
         '    /** 返回全部 Topic 定时计数映射。 */\n    public Map<String, Metric> getTimingCount() {'),
        ('    public void cleanMetrics(Set<String> topics) {',
         '    /** 清理不在 Topic 配置中的非系统/LMQ 指标。 */\n    public void cleanMetrics(Set<String> topics) {'),
        ('    public boolean removeTimingCount(String topic) {',
         '    /** 移除指定 Topic 的定时计数。 */\n    public boolean removeTimingCount(String topic) {'),
        ('    public DataVersion getDataVersion() {',
         '    /** 返回指标数据版本。 */\n    public DataVersion getDataVersion() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/timer/TimerRequest.java': [
        ('public TimerRequest(long offsetPy, int sizePy, long delayTime, long enqueueTime, int magic, MessageExt msg) {',
         '    /** 构造带消息体的 Timer 请求。 */\n    public TimerRequest(long offsetPy, int sizePy, long delayTime, long enqueueTime, int magic, MessageExt msg) {'),
        ('public TimerRequest(long offsetPy, int sizePy, long delayTime, long enqueueTime, int magic) {',
         '    /** 构造无消息体的 Timer 请求。 */\n    public TimerRequest(long offsetPy, int sizePy, long delayTime, long enqueueTime, int magic) {'),
        ('    public Set<String> getDeleteList(',
         '    /** 删除 Topic 列表。 */\n    public Set<String> getDeleteList('),
        ('    private Set<String> deleteList;',
         '    /** 待删除 Topic 集合（可选）。 */\n    private Set<String> deleteList;'),
        ('    private final long delayTime;',
         '    /** 延迟触发时间。 */\n    private final long delayTime;'),
        ('    private CountDownLatch latch;',
         '    /** 异步完成同步门闩。 */\n    private CountDownLatch latch;'),
        ('    private final long offsetPy;',
         '    /** CommitLog 物理偏移。 */\n    private final long offsetPy;'),
        ('    public long getEnqueueTime(',
         '    /** 入队时间。 */\n    public long getEnqueueTime('),
        ('    public void setEnqueueTime(',
         '    /** 设置入队时间。 */\n    public void setEnqueueTime('),
        ('    public void setDeleteList(',
         '    /** 设置删除 Topic 列表。 */\n    public void setDeleteList('),
        ('    private final int sizePy;',
         '    /** CommitLog 消息大小。 */\n    private final int sizePy;'),
        ('    private long enqueueTime;',
         '    /** 入队时间戳。 */\n    private long enqueueTime;'),
        ('    private boolean released;',
         '    /** 是否已释放门闩。 */\n    private boolean released;'),
        ('    public long getDelayTime(',
         '    /** 延迟时间。 */\n    public long getDelayTime('),
        ('    public MessageExt getMsg(',
         '    /** 关联消息。 */\n    public MessageExt getMsg('),
        ('    private final int magic;',
         '    /** Timer 单元魔数/类型标识。 */\n    private final int magic;'),
        ('    public long getOffsetPy(',
         '    /** CommitLog 物理偏移。 */\n    public long getOffsetPy('),
        ('public class TimerRequest {',
         '/**\n * 定时消息处理请求：封装物理偏移、延迟时间与同步门闩。\n */\npublic class TimerRequest {'),
        ('    private MessageExt msg;',
         '    /** 关联的消息体（可选）。 */\n    private MessageExt msg;'),
        ('    private boolean succ;',
         '    /** 处理是否成功。 */\n    private boolean succ;'),
        ('    public int getSizePy(',
         '    /** 消息体大小。 */\n    public int getSizePy('),
        ('    public void setLatch(',
         '    /** 设置同步门闩。 */\n    public void setLatch('),
        ('    public int getMagic(',
         '    /** 魔数。 */\n    public int getMagic('),
        ('    public void setMsg(',
         '    /** 设置关联消息。 */\n    public void setMsg('),
        ('    public void idempotentRelease() {',
         '    /** 幂等释放同步门闩（默认成功）。 */\n    public void idempotentRelease() {'),
        ('    public void idempotentRelease(boolean succ) {',
         '    /** 幂等释放同步门闩并记录结果。 */\n    public void idempotentRelease(boolean succ) {'),
        ('    public boolean isSucc() {',
         '    /** 返回处理是否成功。 */\n    public boolean isSucc() {'),
    ],
}
