"""Chinese JavaDoc replacements for springframework wave24b JDBC callback interfaces."""

CALLBACK_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "InterruptibleBatchPreparedStatementSetter.java": [
        (
            "/**\n * Extension of the {@link BatchPreparedStatementSetter} interface,\n * adding a batch exhaustion check.\n *\n * <p>This interface allows you to signal the end of a batch rather than\n * having to determine the exact batch size upfront. Batch size is still\n * being honored, but it is now the maximum size of the batch.\n *\n * <p>The {@link #isBatchExhausted} method is called after each call to\n * {@link #setValues} to determine whether there were some values added,\n * or if the batch was determined to be complete and no additional values\n * were provided during the last call to {@code setValues}.\n *\n * <p>Consider extending the\n * {@link org.springframework.jdbc.core.support.AbstractInterruptibleBatchPreparedStatementSetter}\n * base class instead of implementing this interface directly, using a single\n * {@code setValuesIfAvailable} callback method that checks for available\n * values and sets them, returning whether values have actually been provided.\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @since 2.0\n * @see JdbcTemplate#batchUpdate(String, BatchPreparedStatementSetter)\n * @see org.springframework.jdbc.core.support.AbstractInterruptibleBatchPreparedStatementSetter\n */",
            "/**\n * {@link BatchPreparedStatementSetter} 接口的扩展，增加了批次耗尽检查。\n *\n * <p>本接口允许标记批次结束，而无需事先确定确切的批次大小。\n * 批次大小仍然生效，但现仅作为批次的最大上限。\n *\n * <p>每次调用 {@link #setValues} 后都会调用 {@link #isBatchExhausted}，\n * 以判断本次是否添加了新值，或批次是否已确定完成\n * （即最后一次 {@code setValues} 调用未提供额外值）。\n *\n * <p>建议扩展\n * {@link org.springframework.jdbc.core.support.AbstractInterruptibleBatchPreparedStatementSetter}\n * 基类而非直接实现本接口：只需实现单个 {@code setValuesIfAvailable} 回调，\n * 检查可用值并设置，同时返回是否实际提供了值。\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @since 2.0\n * @see JdbcTemplate#batchUpdate(String, BatchPreparedStatementSetter)\n * @see org.springframework.jdbc.core.support.AbstractInterruptibleBatchPreparedStatementSetter\n */",
        ),
        (
            "\t/**\n\t * Return whether the batch is complete, that is, whether there were no\n\t * additional values added during the last {@code setValues} call.\n\t * <p><b>NOTE:</b> If this method returns {@code true}, any parameters\n\t * that might have been set during the last {@code setValues} call will\n\t * be ignored! Make sure that you set a corresponding internal flag if you\n\t * detect exhaustion <i>at the beginning</i> of your {@code setValues}\n\t * implementation, letting this method return {@code true} based on the flag.\n\t * @param i index of the statement we're issuing in the batch, starting from 0\n\t * @return whether the batch is already exhausted\n\t * @see #setValues\n\t * @see org.springframework.jdbc.core.support.AbstractInterruptibleBatchPreparedStatementSetter#setValuesIfAvailable\n\t */",
            "\t/**\n\t * 返回批次是否已完成，即最后一次 {@code setValues} 调用是否未添加额外值。\n\t * <p><b>注意：</b>若此方法返回 {@code true}，最后一次 {@code setValues} 调用\n\t * 中可能已设置的任何参数都将被忽略！若在 {@code setValues} 实现\n\t * <i>开头</i>检测到耗尽，请设置相应的内部标志，\n\t * 让此方法基于该标志返回 {@code true}。\n\t * @param i 批次中当前语句的索引，从 0 开始\n\t * @return 批次是否已耗尽\n\t * @see #setValues\n\t * @see org.springframework.jdbc.core.support.AbstractInterruptibleBatchPreparedStatementSetter#setValuesIfAvailable\n\t */",
        ),
    ],
    "ParameterDisposer.java": [
        (
            "/**\n * Interface to be implemented by objects that can close resources\n * allocated by parameters like {@code SqlLobValue} objects.\n *\n * <p>Typically implemented by {@code PreparedStatementCreators} and\n * {@code PreparedStatementSetters} that support {@link DisposableSqlTypeValue}\n * objects (for example, {@code SqlLobValue}) as parameters.\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @since 1.1\n * @see PreparedStatementCreator\n * @see PreparedStatementSetter\n * @see DisposableSqlTypeValue\n * @see org.springframework.jdbc.core.support.SqlLobValue\n */",
            "/**\n * 由能够关闭参数（如 {@code SqlLobValue} 对象）所分配资源的对象实现的接口。\n *\n * <p>通常由支持 {@link DisposableSqlTypeValue}\n * 对象（例如 {@code SqlLobValue}）作为参数的\n * {@code PreparedStatementCreators} 和 {@code PreparedStatementSetters} 实现。\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @since 1.1\n * @see PreparedStatementCreator\n * @see PreparedStatementSetter\n * @see DisposableSqlTypeValue\n * @see org.springframework.jdbc.core.support.SqlLobValue\n */",
        ),
        (
            "\t/**\n\t * Close the resources allocated by parameters that the implementing\n\t * object holds, for example in case of a DisposableSqlTypeValue\n\t * (like an SqlLobValue).\n\t * @see DisposableSqlTypeValue#cleanup()\n\t * @see org.springframework.jdbc.core.support.SqlLobValue#cleanup()\n\t */",
            "\t/**\n\t * 关闭实现对象持有的、由参数分配的资源，\n\t * 例如 DisposableSqlTypeValue（如 SqlLobValue）的情况。\n\t * @see DisposableSqlTypeValue#cleanup()\n\t * @see org.springframework.jdbc.core.support.SqlLobValue#cleanup()\n\t */",
        ),
    ],
    "ParameterMapper.java": [
        (
            "/**\n * Implement this interface when parameters need to be customized based\n * on the connection. We might need to do this to make use of proprietary\n * features, available only with a specific Connection type.\n *\n * @author Rod Johnson\n * @author Thomas Risberg\n * @see CallableStatementCreatorFactory#newCallableStatementCreator(ParameterMapper)\n * @see org.springframework.jdbc.object.StoredProcedure#execute(ParameterMapper)\n */",
            "/**\n * 当参数需基于连接进行定制时实现此接口。\n * 可能需要利用特定 Connection 类型才能使用的专有特性。\n *\n * @author Rod Johnson\n * @author Thomas Risberg\n * @see CallableStatementCreatorFactory#newCallableStatementCreator(ParameterMapper)\n * @see org.springframework.jdbc.object.StoredProcedure#execute(ParameterMapper)\n */",
        ),
        (
            "\t/**\n\t * Create a Map of input parameters, keyed by name.\n\t * @param con a JDBC connection. This is useful (and the purpose of this interface)\n\t * if we need to do something RDBMS-specific with a proprietary Connection\n\t * implementation class. This class conceals such proprietary details. However,\n\t * it is best to avoid using such proprietary RDBMS features if possible.\n\t * @return a Map of input parameters, keyed by name (never {@code null})\n\t * @throws SQLException if an SQLException is encountered setting\n\t * parameter values (that is, there's no need to catch SQLException)\n\t */",
            "\t/**\n\t * 创建以名称为键的输入参数 Map。\n\t * @param con JDBC 连接。若需对专有 Connection 实现类\n\t * 执行 RDBMS 特定操作，此参数很有用（也是本接口的用途）。\n\t * 此类封装了这类专有细节；但如有可能，最好避免使用这类专有 RDBMS 特性。\n\t * @return 以名称为键的输入参数 Map（永不为 {@code null}）\n\t * @throws SQLException 若设置参数值时遇到 SQLException\n\t * （即无需捕获 SQLException）\n\t */",
        ),
    ],
    "ParameterizedPreparedStatementSetter.java": [
        (
            "/**\n * Parameterized callback interface used by the {@link JdbcTemplate} class for\n * batch updates.\n *\n * <p>This interface sets values on a {@link java.sql.PreparedStatement} provided\n * by the JdbcTemplate class, for each of a number of updates in a batch using the\n * same SQL. Implementations are responsible for setting any necessary parameters.\n * SQL with placeholders will already have been supplied.\n *\n * <p>Implementations <i>do not</i> need to concern themselves with SQLExceptions\n * that may be thrown from operations they attempt. The JdbcTemplate class will\n * catch and handle SQLExceptions appropriately.\n *\n * @author Nicolas Fabre\n * @author Thomas Risberg\n * @since 3.1\n * @param <T> the argument type\n * @see JdbcTemplate#batchUpdate(String, java.util.Collection, int, ParameterizedPreparedStatementSetter)\n */",
            "/**\n * {@link JdbcTemplate} 类用于批量更新的参数化回调接口。\n *\n * <p>本接口在 JdbcTemplate 提供的 {@link java.sql.PreparedStatement} 上，\n * 为使用相同 SQL 的一批更新中的每次更新设置值。\n * 实现者负责设置所有必要参数；带占位符的 SQL 已预先提供。\n *\n * <p>实现者<i>无需</i>关心其操作可能抛出的 SQLExceptions。\n * JdbcTemplate 会适当捕获并处理 SQLExceptions。\n *\n * @author Nicolas Fabre\n * @author Thomas Risberg\n * @since 3.1\n * @param <T> 参数类型\n * @see JdbcTemplate#batchUpdate(String, java.util.Collection, int, ParameterizedPreparedStatementSetter)\n */",
        ),
        (
            "\t/**\n\t * Set parameter values on the given PreparedStatement.\n\t * @param ps the PreparedStatement to invoke setter methods on\n\t * @param argument the object containing the values to be set\n\t * @throws SQLException if an SQLException is encountered (i.e. there is no need to catch SQLException)\n\t */",
            "\t/**\n\t * 在给定 PreparedStatement 上设置参数值。\n\t * @param ps 要调用 setter 方法的 PreparedStatement\n\t * @param argument 包含待设置值的对象\n\t * @throws SQLException 若遇到 SQLException（即无需捕获 SQLException）\n\t */",
        ),
    ],
    "PreparedStatementCallback.java": [
        (
            "/**\n * Generic callback interface for code that operates on a PreparedStatement.\n * Allows to execute any number of operations on a single PreparedStatement,\n * for example a single {@code executeUpdate} call or repeated\n * {@code executeUpdate} calls with varying parameters.\n *\n * <p>Used internally by JdbcTemplate, but also useful for application code.\n * Note that the passed-in PreparedStatement can have been created by the\n * framework or by a custom PreparedStatementCreator. However, the latter is\n * hardly ever necessary, as most custom callback actions will perform updates\n * in which case a standard PreparedStatement is fine. Custom actions will\n * always set parameter values themselves, so that PreparedStatementCreator\n * capability is not needed either.\n *\n * @author Juergen Hoeller\n * @since 16.03.2004\n * @param <T> the result type\n * @see JdbcTemplate#execute(String, PreparedStatementCallback)\n * @see JdbcTemplate#execute(PreparedStatementCreator, PreparedStatementCallback)\n */",
            "/**\n * 在 PreparedStatement 上执行代码的通用回调接口。\n * 允许在单个 PreparedStatement 上执行任意次操作，\n * 例如单次 {@code executeUpdate} 调用，或带不同参数的多次 {@code executeUpdate} 调用。\n *\n * <p>由 JdbcTemplate 内部使用，应用代码同样适用。\n * 注意传入的 PreparedStatement 可能由框架或自定义 PreparedStatementCreator 创建。\n * 但后者几乎不需要——大多数自定义回调执行更新，标准 PreparedStatement 即可。\n * 自定义操作总会自行设置参数值，因此也无需 PreparedStatementCreator 能力。\n *\n * @author Juergen Hoeller\n * @since 16.03.2004\n * @param <T> 结果类型\n * @see JdbcTemplate#execute(String, PreparedStatementCallback)\n * @see JdbcTemplate#execute(PreparedStatementCreator, PreparedStatementCallback)\n */",
        ),
        (
            "\t/**\n\t * Gets called by {@code JdbcTemplate.execute} with an active JDBC\n\t * PreparedStatement. Does not need to care about closing the Statement\n\t * or the Connection, or about handling transactions: this will all be\n\t * handled by Spring's JdbcTemplate.\n\t * <p><b>NOTE:</b> Any ResultSets opened should be closed in finally blocks\n\t * within the callback implementation. Spring will close the Statement\n\t * object after the callback returned, but this does not necessarily imply\n\t * that the ResultSet resources will be closed: the Statement objects might\n\t * get pooled by the connection pool, with {@code close} calls only\n\t * returning the object to the pool but not physically closing the resources.\n\t * <p>If called without a thread-bound JDBC transaction (initiated by\n\t * DataSourceTransactionManager), the code will simply get executed on the\n\t * JDBC connection with its transactional semantics. If JdbcTemplate is\n\t * configured to use a JTA-aware DataSource, the JDBC connection and thus\n\t * the callback code will be transactional if a JTA transaction is active.\n\t * <p>Allows for returning a result object created within the callback, i.e.\n\t * a domain object or a collection of domain objects. Note that there's\n\t * special support for single step actions: see JdbcTemplate.queryForObject etc.\n\t * A thrown RuntimeException is treated as application exception, it gets\n\t * propagated to the caller of the template.\n\t * @param ps active JDBC PreparedStatement\n\t * @return a result object, or {@code null} if none\n\t * @throws SQLException if thrown by a JDBC method, to be auto-converted\n\t * to a DataAccessException by an SQLExceptionTranslator\n\t * @throws DataAccessException in case of custom exceptions\n\t * @see JdbcTemplate#queryForObject(String, Class, Object...)\n\t * @see JdbcTemplate#queryForList(String, Object...)\n\t */",
            "\t/**\n\t * 由 {@code JdbcTemplate.execute} 调用，传入活动的 JDBC PreparedStatement。\n\t * 无需关心关闭 Statement 或 Connection，也无需处理事务——均由 Spring JdbcTemplate 负责。\n\t * <p><b>注意：</b>回调实现中打开的 ResultSet 应在 finally 块中关闭。\n\t * Spring 在回调返回后关闭 Statement 对象，但这不一定意味着 ResultSet 资源已关闭：\n\t * Statement 可能被连接池复用，{@code close} 仅将对象归还池中，\n\t * 未必物理关闭底层资源。\n\t * <p>若无线程绑定的 JDBC 事务（由 DataSourceTransactionManager 启动），\n\t * 代码将直接在 JDBC 连接上按其事务语义执行。\n\t * 若 JdbcTemplate 配置为使用 JTA 感知 DataSource，\n\t * 且 JTA 事务处于活动状态，则 JDBC 连接及回调代码均在事务中运行。\n\t * <p>允许返回回调内创建的结果对象，如领域对象或领域对象集合。\n\t * 单步操作有专门支持：参见 JdbcTemplate.queryForObject 等。\n\t * 抛出的 RuntimeException 视为应用异常，会传播给模板调用方。\n\t * @param ps 活动的 JDBC PreparedStatement\n\t * @return 结果对象，若无则 {@code null}\n\t * @throws SQLException 若 JDBC 方法抛出，将由 SQLExceptionTranslator 自动转换为 DataAccessException\n\t * @throws DataAccessException 自定义异常时\n\t * @see JdbcTemplate#queryForObject(String, Class, Object...)\n\t * @see JdbcTemplate#queryForList(String, Object...)\n\t */",
        ),
    ],
    "PreparedStatementCreator.java": [
        (
            "/**\n * One of the two central callback interfaces used by the JdbcTemplate class.\n * This interface creates a PreparedStatement given a connection, provided\n * by the JdbcTemplate class. Implementations are responsible for providing\n * SQL and any necessary parameters.\n *\n * <p>Implementations <i>do not</i> need to concern themselves with\n * SQLExceptions that may be thrown from operations they attempt.\n * The JdbcTemplate class will catch and handle SQLExceptions appropriately.\n *\n * <p>A PreparedStatementCreator should also implement the SqlProvider interface\n * if it is able to provide the SQL it uses for PreparedStatement creation.\n * This allows for better contextual information in case of exceptions.\n *\n * @author Rod Johnson\n * @see JdbcTemplate#execute(PreparedStatementCreator, PreparedStatementCallback)\n * @see JdbcTemplate#query(PreparedStatementCreator, RowCallbackHandler)\n * @see JdbcTemplate#update(PreparedStatementCreator)\n * @see SqlProvider\n */",
            "/**\n * JdbcTemplate 类使用的两个核心回调接口之一。\n * 本接口在给定连接上创建 PreparedStatement，连接由 JdbcTemplate 提供。\n * 实现者负责提供 SQL 及所有必要参数。\n *\n * <p>实现者<i>无需</i>关心其操作可能抛出的 SQLExceptions。\n * JdbcTemplate 会适当捕获并处理 SQLExceptions。\n *\n * <p>若 PreparedStatementCreator 能提供创建 PreparedStatement 所用的 SQL，\n * 还应实现 SqlProvider 接口，以便异常时提供更丰富的上下文信息。\n *\n * @author Rod Johnson\n * @see JdbcTemplate#execute(PreparedStatementCreator, PreparedStatementCallback)\n * @see JdbcTemplate#query(PreparedStatementCreator, RowCallbackHandler)\n * @see JdbcTemplate#update(PreparedStatementCreator)\n * @see SqlProvider\n */",
        ),
        (
            "\t/**\n\t * Create a statement in this connection. Allows implementations to use\n\t * PreparedStatements. The JdbcTemplate will close the created statement.\n\t * @param con the connection used to create statement\n\t * @return a prepared statement\n\t * @throws SQLException there is no need to catch SQLExceptions\n\t * that may be thrown in the implementation of this method.\n\t * The JdbcTemplate class will handle them.\n\t */",
            "\t/**\n\t * 在此连接上创建语句。允许实现者使用 PreparedStatement。\n\t * JdbcTemplate 将关闭创建的语句。\n\t * @param con 用于创建语句的连接\n\t * @return PreparedStatement\n\t * @throws SQLException 实现中可能抛出的 SQLException 无需捕获，\n\t * JdbcTemplate 会处理。\n\t */",
        ),
    ],
    "PreparedStatementSetter.java": [
        (
            "/**\n * General callback interface used by the {@link JdbcTemplate} class.\n *\n * <p>This interface sets values on a {@link java.sql.PreparedStatement} provided\n * by the JdbcTemplate class, for each of a number of updates in a batch using the\n * same SQL. Implementations are responsible for setting any necessary parameters.\n * SQL with placeholders will already have been supplied.\n *\n * <p>It's easier to use this interface than {@link PreparedStatementCreator}:\n * The JdbcTemplate will create the PreparedStatement, with the callback\n * only being responsible for setting parameter values.\n *\n * <p>Implementations <i>do not</i> need to concern themselves with\n * SQLExceptions that may be thrown from operations they attempt.\n * The JdbcTemplate class will catch and handle SQLExceptions appropriately.\n *\n * @author Rod Johnson\n * @since March 2, 2003\n * @see JdbcTemplate#update(String, PreparedStatementSetter)\n * @see JdbcTemplate#query(String, PreparedStatementSetter, ResultSetExtractor)\n */",
            "/**\n * {@link JdbcTemplate} 类使用的通用回调接口。\n *\n * <p>本接口在 JdbcTemplate 提供的 {@link java.sql.PreparedStatement} 上\n * 为使用相同 SQL 的一批更新中的每次更新设置值。\n * 实现者负责设置所有必要参数；带占位符的 SQL 已预先提供。\n *\n * <p>使用本接口比 {@link PreparedStatementCreator} 更简单：\n * JdbcTemplate 创建 PreparedStatement，回调只需负责设置参数值。\n *\n * <p>实现者<i>无需</i>关心其操作可能抛出的 SQLExceptions。\n * JdbcTemplate 会适当捕获并处理 SQLExceptions。\n *\n * @author Rod Johnson\n * @since March 2, 2003\n * @see JdbcTemplate#update(String, PreparedStatementSetter)\n * @see JdbcTemplate#query(String, PreparedStatementSetter, ResultSetExtractor)\n */",
        ),
        (
            "\t/**\n\t * Set parameter values on the given PreparedStatement.\n\t * @param ps the PreparedStatement to invoke setter methods on\n\t * @throws SQLException if an SQLException is encountered\n\t * (i.e. there is no need to catch SQLException)\n\t */",
            "\t/**\n\t * 在给定 PreparedStatement 上设置参数值。\n\t * @param ps 要调用 setter 方法的 PreparedStatement\n\t * @throws SQLException 若遇到 SQLException（即无需捕获 SQLException）\n\t */",
        ),
    ],
    "ResultSetExtractor.java": [
        (
            "/**\n * Callback interface used by {@link JdbcTemplate}'s query methods.\n * Implementations of this interface perform the actual work of extracting\n * results from a {@link java.sql.ResultSet}, but don't need to worry\n * about exception handling. {@link java.sql.SQLException SQLExceptions}\n * will be caught and handled by the calling JdbcTemplate.\n *\n * <p>This interface is mainly used within the JDBC framework itself.\n * A {@link RowMapper} is usually a simpler choice for ResultSet processing,\n * mapping one result object per row instead of one result object for\n * the entire ResultSet.\n *\n * <p>Note: In contrast to a {@link RowCallbackHandler}, a ResultSetExtractor\n * object is typically stateless and thus reusable, as long as it doesn't\n * access stateful resources (such as output streams when streaming LOB\n * contents) or keep result state within the object.\n *\n * @author Rod Johnson\n * @author Juergen Hoeller\n * @since April 24, 2003\n * @param <T> the result type\n * @see JdbcTemplate\n * @see RowCallbackHandler\n * @see RowMapper\n * @see org.springframework.jdbc.core.support.AbstractLobStreamingResultSetExtractor\n */",
            "/**\n * {@link JdbcTemplate} 查询方法使用的回调接口。\n * 本接口的实现负责从 {@link java.sql.ResultSet} 提取结果的实际工作，\n * 但无需关心异常处理——{@link java.sql.SQLException SQLExceptions}\n * 由调用方 JdbcTemplate 捕获并处理。\n *\n * <p>本接口主要在 JDBC 框架内部使用。\n * 处理 ResultSet 时 {@link RowMapper} 通常是更简单的选择，\n * 每行映射一个结果对象，而非整个 ResultSet 映射一个结果对象。\n *\n * <p>注意：与 {@link RowCallbackHandler} 不同，ResultSetExtractor\n * 通常是无状态的，因此可重用——只要不访问有状态资源\n * （如流式 LOB 内容时的输出流）或在对象内保留结果状态。\n *\n * @author Rod Johnson\n * @author Juergen Hoeller\n * @since April 24, 2003\n * @param <T> 结果类型\n * @see JdbcTemplate\n * @see RowCallbackHandler\n * @see RowMapper\n * @see org.springframework.jdbc.core.support.AbstractLobStreamingResultSetExtractor\n */",
        ),
        (
            "\t/**\n\t * Implementations must implement this method to process the entire ResultSet.\n\t * @param rs the ResultSet to extract data from. Implementations should\n\t * not close this: it will be closed by the calling JdbcTemplate.\n\t * @return an arbitrary result object, or {@code null} if none\n\t * (the extractor will typically be stateful in the latter case).\n\t * @throws SQLException if an SQLException is encountered getting column\n\t * values or navigating (that is, there's no need to catch SQLException)\n\t * @throws DataAccessException in case of custom exceptions\n\t */",
            "\t/**\n\t * 实现者必须实现本方法以处理整个 ResultSet。\n\t * @param rs 要提取数据的 ResultSet。实现者不应关闭它——\n\t * 将由调用方 JdbcTemplate 关闭。\n\t * @return 任意结果对象，若无则 {@code null}\n\t * （后一种情况下提取器通常是有状态的）。\n\t * @throws SQLException 若获取列值或导航时遇到 SQLException\n\t * （即无需捕获 SQLException）\n\t * @throws DataAccessException 自定义异常时\n\t */",
        ),
    ],
    "RowCallbackHandler.java": [
        (
            "/**\n * An interface used by {@link JdbcTemplate} and\n * {@link org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate\n * NamedParameterJdbcTemplate} for processing rows of a\n * {@link java.sql.ResultSet} on a per-row basis. Implementations of\n * this interface perform the actual work of processing each row\n * but don't need to worry about exception handling.\n * {@link java.sql.SQLException SQLExceptions} will be caught and handled\n * by the calling {@code JdbcTemplate} or {@code NamedParameterJdbcTemplate}.\n *\n * <p>In contrast to a {@link ResultSetExtractor}, a {@code RowCallbackHandler}\n * object is typically stateful: it keeps the result state within the\n * object, to be available for later inspection. See\n * {@link RowCountCallbackHandler} for a usage example.\n *\n * <p>Consider using a {@link RowMapper} instead if you need to map\n * exactly one result object per row, assembling them into a List.\n *\n * @author Rod Johnson\n * @author Juergen Hoeller\n * @see JdbcTemplate\n * @see org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate NamedParameterJdbcTemplate\n * @see RowMapper\n * @see ResultSetExtractor\n * @see RowCountCallbackHandler\n */",
            "/**\n * {@link JdbcTemplate} 和\n * {@link org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate\n * NamedParameterJdbcTemplate} 用于逐行处理 {@link java.sql.ResultSet}\n * 行的接口。本接口的实现负责处理每一行的实际工作，\n * 但无需关心异常处理——{@link java.sql.SQLException SQLExceptions}\n * 由调用方 {@code JdbcTemplate} 或 {@code NamedParameterJdbcTemplate} 捕获并处理。\n *\n * <p>与 {@link ResultSetExtractor} 不同，{@code RowCallbackHandler}\n * 通常是有状态的：在对象内保留结果状态，供后续检查。\n * 用法示例参见 {@link RowCountCallbackHandler}。\n *\n * <p>若需每行映射恰好一个结果对象并组装为 List，\n * 建议使用 {@link RowMapper}。\n *\n * @author Rod Johnson\n * @author Juergen Hoeller\n * @see JdbcTemplate\n * @see org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate NamedParameterJdbcTemplate\n * @see RowMapper\n * @see ResultSetExtractor\n * @see RowCountCallbackHandler\n */",
        ),
        (
            "\t/**\n\t * Implementations must implement this method to process each row of data\n\t * in the {@link ResultSet}. This method should not call {@code next()} on\n\t * the {@code ResultSet}; it is only supposed to extract values of the current\n\t * row.\n\t * <p>Exactly what the implementation chooses to do is up to it:\n\t * a trivial implementation might simply count rows, while another\n\t * implementation might build an XML document.\n\t * @param rs the {@code ResultSet} to process (pre-initialized for the current row)\n\t * @throws SQLException if an {@code SQLException} is encountered getting\n\t * column values (that is, there's no need to catch {@code SQLException})\n\t */",
            "\t/**\n\t * 实现者必须实现本方法以处理 {@link ResultSet} 中的每一行数据。\n\t * 此方法不应在 {@code ResultSet} 上调用 {@code next()}；\n\t * 只应提取当前行的值。\n\t * <p>具体做什么由实现者决定：简单实现可能仅计数行数，\n\t * 复杂实现可能构建 XML 文档。\n\t * @param rs 要处理的 {@code ResultSet}（针对当前行预先初始化）\n\t * @throws SQLException 若获取列值时遇到 {@code SQLException}\n\t * （即无需捕获 {@code SQLException}）\n\t */",
        ),
    ],
    "RowMapper.java": [
        (
            "/**\n * An interface used by {@link JdbcTemplate} for mapping rows of a\n * {@link java.sql.ResultSet} on a per-row basis. Implementations of this\n * interface perform the actual work of mapping each row to a result object\n * but don't need to worry about exception handling.\n * {@link java.sql.SQLException SQLExceptions} will be caught and handled\n * by the calling {@code JdbcTemplate}.\n *\n * <p>Typically used either for {@code JdbcTemplate}'s query methods or for\n * {@code out} parameters of stored procedures. {@code RowMapper} objects are\n * typically stateless and thus reusable; they are an ideal choice for\n * implementing row-mapping logic in a single place.\n *\n * <p>Alternatively, consider subclassing\n * {@link org.springframework.jdbc.object.MappingSqlQuery} from the\n * {@code jdbc.object} package: instead of working with separate\n * {@code JdbcTemplate} and {@code RowMapper} objects, you can build executable\n * query objects (containing row-mapping logic) in that style.\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @param <T> the result type\n * @see JdbcTemplate\n * @see RowCallbackHandler\n * @see ResultSetExtractor\n * @see org.springframework.jdbc.object.MappingSqlQuery\n */",
            "/**\n * {@link JdbcTemplate} 用于逐行映射 {@link java.sql.ResultSet} 行的接口。\n * 本接口的实现负责将每一行映射到结果对象的实际工作，\n * 但无需关心异常处理——{@link java.sql.SQLException SQLExceptions}\n * 由调用方 {@code JdbcTemplate} 捕获并处理。\n *\n * <p>通常用于 {@code JdbcTemplate} 的查询方法或存储过程的 {@code out} 参数。\n * {@code RowMapper} 对象通常是无状态的，因此可重用；\n * 是在单一位置实现行映射逻辑的理想选择。\n *\n * <p>或者，考虑从 {@code jdbc.object} 包子类化\n * {@link org.springframework.jdbc.object.MappingSqlQuery}：\n * 可以该风格构建包含行映射逻辑的可执行查询对象，\n * 而非分别使用 {@code JdbcTemplate} 和 {@code RowMapper}。\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @param <T> 结果类型\n * @see JdbcTemplate\n * @see RowCallbackHandler\n * @see ResultSetExtractor\n * @see org.springframework.jdbc.object.MappingSqlQuery\n */",
        ),
        (
            "\t/**\n\t * Implementations must implement this method to map each row of data in the\n\t * {@code ResultSet}. This method should not call {@code next()} on the\n\t * {@code ResultSet}; it is only supposed to map values of the current row.\n\t * @param rs the {@code ResultSet} to map (pre-initialized for the current row)\n\t * @param rowNum the number of the current row\n\t * @return the result object for the current row (may be {@code null})\n\t * @throws SQLException if an SQLException is encountered while getting\n\t * column values (that is, there's no need to catch SQLException)\n\t */",
            "\t/**\n\t * 实现者必须实现本方法以映射 {@code ResultSet} 中的每一行数据。\n\t * 此方法不应在 {@code ResultSet} 上调用 {@code next()}；\n\t * 只应映射当前行的值。\n\t * @param rs 要映射的 {@code ResultSet}（针对当前行预先初始化）\n\t * @param rowNum 当前行号\n\t * @return 当前行的结果对象（可能为 {@code null}）\n\t * @throws SQLException 若获取列值时遇到 SQLException\n\t * （即无需捕获 SQLException）\n\t */",
        ),
    ],
}
