"""Chinese annotation replacements for Redisson 4.7.0 wave-51b api [15:30]."""
from __future__ import annotations

_A = "redisson/src/main/java/org/redisson/api/"

W51B_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    'redisson/src/main/java/org/redisson/api/SetIntersectionArgs.java': [
        ('/**\n * Arguments object for RScoredSortedSet.readIntersection() methods.\n *\n * @author seakider\n *\n */', '/**\n * RScoredSortedSet.readIntersection() 方法的参数对象。\n *\n * @author seakider\n *\n */'),
        ('/**\n     * Defines arguments object that\n     * intersect with current ScoredSortedSet\n     *\n     * @param names names of the specified ScoredSortedSets.\n     * @return arguments object\n     */', '/**\n     * 定义与当前 ScoredSortedSet 求交集的参数对象。\n     *\n     * @param names 指定的 ScoredSortedSet 名称\n     * @return 参数对象\n     */'),
    ],
    'SetIntersectionArgs.java': [
        ('/**\n * Arguments object for RScoredSortedSet.readIntersection() methods.\n *\n * @author seakider\n *\n */', '/**\n * RScoredSortedSet.readIntersection() 方法的参数对象。\n *\n * @author seakider\n *\n */'),
        ('/**\n     * Defines arguments object that\n     * intersect with current ScoredSortedSet\n     *\n     * @param names names of the specified ScoredSortedSets.\n     * @return arguments object\n     */', '/**\n     * 定义与当前 ScoredSortedSet 求交集的参数对象。\n     *\n     * @param names 指定的 ScoredSortedSet 名称\n     * @return 参数对象\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/SetIntersectionParams.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * {@link SetIntersectionArgs} 的默认实现，\n * 封装有序集合交集读操作的键名、权重与聚合参数。\n *\n * @author seakider\n *\n */'),
    ],
    'SetIntersectionParams.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * {@link SetIntersectionArgs} 的默认实现，\n * 封装有序集合交集读操作的键名、权重与聚合参数。\n *\n * @author seakider\n *\n */'),
    ],
    'redisson/src/main/java/org/redisson/api/SetReadArgs.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * 有序集合读操作（交集/并集）的可选参数。\n *\n * @author seakider\n *\n */'),
        ('/**\n     * Defines a weight multiplier for each ScoredSortedSet\n     *\n     * @param weights weight multiplier\n     * @return arguments object\n     */', '/**\n     * 为每个 ScoredSortedSet 定义权重乘数。\n     *\n     * @param weights 权重乘数\n     * @return 参数对象\n     */'),
        ('/**\n     * Defines aggregation method\n     *\n     * @param aggregate score aggregation mode\n     * @return arguments object\n     */', '/**\n     * 定义分数聚合方式。\n     *\n     * @param aggregate 分数聚合模式\n     * @return 参数对象\n     */'),
    ],
    'SetReadArgs.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * 有序集合读操作（交集/并集）的可选参数。\n *\n * @author seakider\n *\n */'),
        ('/**\n     * Defines a weight multiplier for each ScoredSortedSet\n     *\n     * @param weights weight multiplier\n     * @return arguments object\n     */', '/**\n     * 为每个 ScoredSortedSet 定义权重乘数。\n     *\n     * @param weights 权重乘数\n     * @return 参数对象\n     */'),
        ('/**\n     * Defines aggregation method\n     *\n     * @param aggregate score aggregation mode\n     * @return arguments object\n     */', '/**\n     * 定义分数聚合方式。\n     *\n     * @param aggregate 分数聚合模式\n     * @return 参数对象\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/SetReadArgsParam.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * {@link SetReadArgs} 的基类实现，保存键名、权重与聚合方式。\n *\n * @author seakider\n *\n */'),
    ],
    'SetReadArgsParam.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * {@link SetReadArgs} 的基类实现，保存键名、权重与聚合方式。\n *\n * @author seakider\n *\n */'),
    ],
    'redisson/src/main/java/org/redisson/api/SetUnionArgs.java': [
        ('/**\n * Arguments object for RScoredSortedSet.readUnion() methods.\n *\n * @author seakider\n *\n */', '/**\n * RScoredSortedSet.readUnion() 方法的参数对象。\n *\n * @author seakider\n *\n */'),
        ('/**\n     * Define arguments object that\n     * union with current ScoredSortedSet\n     *\n     * @param names names of the specified ScoredSortedSets.\n     * @return arguments object\n     */', '/**\n     * 定义与当前 ScoredSortedSet 求并集的参数对象。\n     *\n     * @param names 指定的 ScoredSortedSet 名称\n     * @return 参数对象\n     */'),
    ],
    'SetUnionArgs.java': [
        ('/**\n * Arguments object for RScoredSortedSet.readUnion() methods.\n *\n * @author seakider\n *\n */', '/**\n * RScoredSortedSet.readUnion() 方法的参数对象。\n *\n * @author seakider\n *\n */'),
        ('/**\n     * Define arguments object that\n     * union with current ScoredSortedSet\n     *\n     * @param names names of the specified ScoredSortedSets.\n     * @return arguments object\n     */', '/**\n     * 定义与当前 ScoredSortedSet 求并集的参数对象。\n     *\n     * @param names 指定的 ScoredSortedSet 名称\n     * @return 参数对象\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/SetUnionParams.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * {@link SetUnionArgs} 的默认实现，\n * 封装有序集合并集读操作的键名、权重与聚合参数。\n *\n * @author seakider\n *\n */'),
    ],
    'SetUnionParams.java': [
        ('/**\n *\n * @author seakider\n *\n */', '/**\n * {@link SetUnionArgs} 的默认实现，\n * 封装有序集合并集读操作的键名、权重与聚合参数。\n *\n * @author seakider\n *\n */'),
    ],
    'redisson/src/main/java/org/redisson/api/SortOrder.java': [
        ('/**\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 有序集合的排序方向。\n * <p>\n * {@link #ASC} 升序，{@link #DESC} 降序。\n *\n * @author Nikita Koksharov\n *\n */'),
    ],
    'SortOrder.java': [
        ('/**\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 有序集合的排序方向。\n * <p>\n * {@link #ASC} 升序，{@link #DESC} 降序。\n *\n * @author Nikita Koksharov\n *\n */'),
    ],
    'redisson/src/main/java/org/redisson/api/SyncArgs.java': [
        ('/**\n * Interface defining parameters for queue synchronization.\n * These parameters control how queue operations are synchronized with secondary Valkey or Redis nodes.\n *\n * @param <T> type\n * @author Nikita Koksharov\n */', '/**\n * 定义队列同步参数的接口；\n * 控制队列操作如何与 Valkey 或 Redis 从节点同步。\n *\n * @param <T> 参数对象类型\n * @author Nikita Koksharov\n */'),
        ('/**\n     * Sets the synchronization mode to be used for current operation.\n     * <p>\n     * Default value is SyncMode.AUTO\n     *\n     * @param syncMode the synchronization mode\n     * @return arguments object\n     * @see SyncMode\n     */', '/**\n     * 设置当前操作使用的同步模式。\n     * <p>\n     * Default value is SyncMode.AUTO\n     *\n     * @param syncMode 同步模式\n     * @return 参数对象\n     * @see SyncMode\n     */'),
        ('/**\n     * Sets the behavior when synchronization with secondary nodes fails.\n     * <p>\n     * Default value is SyncFailureMode.LOG_WARNING\n     *\n     * @param syncFailureMode the failure handling mode\n     * @return The current instance for method chaining\n     * @see SyncFailureMode\n     */', '/**\n     * 设置与从节点同步失败时的处理方式。\n     * <p>\n     * Default value is SyncFailureMode.LOG_WARNING\n     *\n     * @param syncFailureMode 失败处理模式\n     * @return 当前实例，支持链式调用\n     * @see SyncFailureMode\n     */'),
        ('/**\n     * Sets the timeout duration for synchronization of the current operation.\n     * Defines how long the system will wait for acknowledgment from secondary nodes.\n     * <p>\n     * Default value is 1 second.\n     *\n     * @param timeout The maximum time to wait for synchronization to complete\n     * @return arguments object\n     */', '/**\n     * 设置当前操作的同步超时时间；\n     * 即等待从节点确认的最长时间。\n     * <p>\n     * Default value is 1 second.\n     *\n     * @param timeout 等待同步完成的最长时间\n     * @return 参数对象\n     */'),
    ],
    'SyncArgs.java': [
        ('/**\n * Interface defining parameters for queue synchronization.\n * These parameters control how queue operations are synchronized with secondary Valkey or Redis nodes.\n *\n * @param <T> type\n * @author Nikita Koksharov\n */', '/**\n * 定义队列同步参数的接口；\n * 控制队列操作如何与 Valkey 或 Redis 从节点同步。\n *\n * @param <T> 参数对象类型\n * @author Nikita Koksharov\n */'),
        ('/**\n     * Sets the synchronization mode to be used for current operation.\n     * <p>\n     * Default value is SyncMode.AUTO\n     *\n     * @param syncMode the synchronization mode\n     * @return arguments object\n     * @see SyncMode\n     */', '/**\n     * 设置当前操作使用的同步模式。\n     * <p>\n     * Default value is SyncMode.AUTO\n     *\n     * @param syncMode 同步模式\n     * @return 参数对象\n     * @see SyncMode\n     */'),
        ('/**\n     * Sets the behavior when synchronization with secondary nodes fails.\n     * <p>\n     * Default value is SyncFailureMode.LOG_WARNING\n     *\n     * @param syncFailureMode the failure handling mode\n     * @return The current instance for method chaining\n     * @see SyncFailureMode\n     */', '/**\n     * 设置与从节点同步失败时的处理方式。\n     * <p>\n     * Default value is SyncFailureMode.LOG_WARNING\n     *\n     * @param syncFailureMode 失败处理模式\n     * @return 当前实例，支持链式调用\n     * @see SyncFailureMode\n     */'),
        ('/**\n     * Sets the timeout duration for synchronization of the current operation.\n     * Defines how long the system will wait for acknowledgment from secondary nodes.\n     * <p>\n     * Default value is 1 second.\n     *\n     * @param timeout The maximum time to wait for synchronization to complete\n     * @return arguments object\n     */', '/**\n     * 设置当前操作的同步超时时间；\n     * 即等待从节点确认的最长时间。\n     * <p>\n     * Default value is 1 second.\n     *\n     * @param timeout 等待同步完成的最长时间\n     * @return 参数对象\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/SyncFailureMode.java': [
        ('/**\n * Defines the behavior modes when synchronization with Valkey or Redis secondary nodes\n * fails.\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * 定义与 Valkey 或 Redis 从节点同步失败时的行为模式。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * When synchronization fails, throw an exception to the caller.\n     * <p>\n     * This mode is useful in scenarios where synchronization failures should\n     * be immediately visible and handled by the application code.\n     * </p>\n     */', '/**\n     * 同步失败时向调用方抛出异常。\n     * <p>\n     * 适用于需要应用代码立即感知并处理同步失败的场景。\n     * </p>\n     */'),
        ('/**\n     * When synchronization fails, log a warning message but continue execution.\n     * <p>\n     * This mode is suitable for non-critical synchronization operations where\n     * the application can continue functioning despite synchronization issues.\n     * </p>\n     */', '/**\n     * 同步失败时记录警告日志并继续执行。\n     * <p>\n     * 适用于非关键同步操作，即使同步异常应用仍可继续运行。\n     * </p>\n     */'),
    ],
    'SyncFailureMode.java': [
        ('/**\n * Defines the behavior modes when synchronization with Valkey or Redis secondary nodes\n * fails.\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * 定义与 Valkey 或 Redis 从节点同步失败时的行为模式。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * When synchronization fails, throw an exception to the caller.\n     * <p>\n     * This mode is useful in scenarios where synchronization failures should\n     * be immediately visible and handled by the application code.\n     * </p>\n     */', '/**\n     * 同步失败时向调用方抛出异常。\n     * <p>\n     * 适用于需要应用代码立即感知并处理同步失败的场景。\n     * </p>\n     */'),
        ('/**\n     * When synchronization fails, log a warning message but continue execution.\n     * <p>\n     * This mode is suitable for non-critical synchronization operations where\n     * the application can continue functioning despite synchronization issues.\n     * </p>\n     */', '/**\n     * 同步失败时记录警告日志并继续执行。\n     * <p>\n     * 适用于非关键同步操作，即使同步异常应用仍可继续运行。\n     * </p>\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/SyncMode.java': [
        ('/**\n * Defines the synchronization modes used for replication with Valkey or Redis replica instances.\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * 定义与 Valkey 或 Redis 副本实例复制时的同步模式。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Ensures data durability by blocking until write operations are confirmed as persisted to the\n     * memory and the Append-Only File (AOF) on the primary Redis instance and replicas if the AOF persistence feature is enabled.\n     * If AOF persistence is unavailable, falls back to blocking until replica instances acknowledge\n     * that write operations have been applied to memory.\n     * If neither durability mechanism is available, proceeds without synchronization guarantees.\n     *\n     */', '/**\n     * 通过阻塞直至写操作在主节点及副本的内存与 AOF 中持久化确认来保证数据持久性（启用 AOF 时）；\n     * 若 AOF 不可用，则退化为阻塞直至副本确认写操作已写入内存；\n     * 若两种机制均不可用，则不提供同步保证继续执行。\n     *\n     */'),
        ('/**\n     * Ensures data durability by blocking until replica instances acknowledge that write operations have been applied to memory.\n     */', '/**\n     * 阻塞直至副本确认写操作已写入内存，以保证数据持久性。\n     */'),
        ('/**\n     * Ensures data durability by blocking until write operations are confirmed as persisted to the\n     * Append-Only File (AOF) on the primary Redis instance and replicas.\n     * <p>\n     * NOTE: Redis 7.2.0+ or any Valkey version is required\n     *\n     */', '/**\n     * 阻塞直至主节点及副本的 AOF 确认写操作已持久化，以保证数据持久性。\n     * <p>\n     * NOTE: Redis 7.2.0+ or any Valkey version is required\n     *\n     */'),
    ],
    'SyncMode.java': [
        ('/**\n * Defines the synchronization modes used for replication with Valkey or Redis replica instances.\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * 定义与 Valkey 或 Redis 副本实例复制时的同步模式。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Ensures data durability by blocking until write operations are confirmed as persisted to the\n     * memory and the Append-Only File (AOF) on the primary Redis instance and replicas if the AOF persistence feature is enabled.\n     * If AOF persistence is unavailable, falls back to blocking until replica instances acknowledge\n     * that write operations have been applied to memory.\n     * If neither durability mechanism is available, proceeds without synchronization guarantees.\n     *\n     */', '/**\n     * 通过阻塞直至写操作在主节点及副本的内存与 AOF 中持久化确认来保证数据持久性（启用 AOF 时）；\n     * 若 AOF 不可用，则退化为阻塞直至副本确认写操作已写入内存；\n     * 若两种机制均不可用，则不提供同步保证继续执行。\n     *\n     */'),
        ('/**\n     * Ensures data durability by blocking until replica instances acknowledge that write operations have been applied to memory.\n     */', '/**\n     * 阻塞直至副本确认写操作已写入内存，以保证数据持久性。\n     */'),
        ('/**\n     * Ensures data durability by blocking until write operations are confirmed as persisted to the\n     * Append-Only File (AOF) on the primary Redis instance and replicas.\n     * <p>\n     * NOTE: Redis 7.2.0+ or any Valkey version is required\n     *\n     */', '/**\n     * 阻塞直至主节点及副本的 AOF 确认写操作已持久化，以保证数据持久性。\n     * <p>\n     * NOTE: Redis 7.2.0+ or any Valkey version is required\n     *\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/TDigestInfo.java': [
        ('/**\n * t-digest information returned by the {@code TDIGEST.INFO} command.\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * {@code TDIGEST.INFO} 命令返回的 t-digest 信息。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Returns the compression factor of the sketch.\n     *\n     * @return compression\n     */', '/**\n     * 返回草图的压缩因子。\n     *\n     * @return 压缩因子\n     */'),
        ('/**\n     * Returns the number of centroids the sketch can hold.\n     *\n     * @return capacity\n     */', '/**\n     * 返回草图可容纳的质心数量。\n     *\n     * @return 容量\n     */'),
        ('/**\n     * Returns the number of merged centroids.\n     *\n     * @return merged nodes\n     */', '/**\n     * 返回已合并的质心数量。\n     *\n     * @return 已合并质心数\n     */'),
        ('/**\n     * Returns the number of buffered, not yet merged centroids.\n     *\n     * @return unmerged nodes\n     */', '/**\n     * 返回尚未合并的缓冲质心数量。\n     *\n     * @return 未合并质心数\n     */'),
        ('/**\n     * Returns the total weight of merged centroids.\n     *\n     * @return merged weight\n     */', '/**\n     * 返回已合并质心的总权重。\n     *\n     * @return 已合并权重\n     */'),
        ('/**\n     * Returns the total weight of buffered, not yet merged centroids.\n     *\n     * @return unmerged weight\n     */', '/**\n     * 返回尚未合并缓冲质心的总权重。\n     *\n     * @return 未合并权重\n     */'),
        ('/**\n     * Returns the number of observations added to the sketch.\n     *\n     * @return observations\n     */', '/**\n     * 返回已添加到草图的观测值数量。\n     *\n     * @return 观测值数量\n     */'),
        ('/**\n     * Returns the number of compaction operations performed on the sketch.\n     *\n     * @return total compressions\n     */', '/**\n     * 返回草图执行的压缩（compaction）次数。\n     *\n     * @return 压缩次数\n     */'),
        ('/**\n     * Returns the number of bytes allocated for the sketch.\n     *\n     * @return memory usage in bytes\n     */', '/**\n     * 返回草图占用的字节数。\n     *\n     * @return 内存占用（字节）\n     */'),
    ],
    'TDigestInfo.java': [
        ('/**\n * t-digest information returned by the {@code TDIGEST.INFO} command.\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * {@code TDIGEST.INFO} 命令返回的 t-digest 信息。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Returns the compression factor of the sketch.\n     *\n     * @return compression\n     */', '/**\n     * 返回草图的压缩因子。\n     *\n     * @return 压缩因子\n     */'),
        ('/**\n     * Returns the number of centroids the sketch can hold.\n     *\n     * @return capacity\n     */', '/**\n     * 返回草图可容纳的质心数量。\n     *\n     * @return 容量\n     */'),
        ('/**\n     * Returns the number of merged centroids.\n     *\n     * @return merged nodes\n     */', '/**\n     * 返回已合并的质心数量。\n     *\n     * @return 已合并质心数\n     */'),
        ('/**\n     * Returns the number of buffered, not yet merged centroids.\n     *\n     * @return unmerged nodes\n     */', '/**\n     * 返回尚未合并的缓冲质心数量。\n     *\n     * @return 未合并质心数\n     */'),
        ('/**\n     * Returns the total weight of merged centroids.\n     *\n     * @return merged weight\n     */', '/**\n     * 返回已合并质心的总权重。\n     *\n     * @return 已合并权重\n     */'),
        ('/**\n     * Returns the total weight of buffered, not yet merged centroids.\n     *\n     * @return unmerged weight\n     */', '/**\n     * 返回尚未合并缓冲质心的总权重。\n     *\n     * @return 未合并权重\n     */'),
        ('/**\n     * Returns the number of observations added to the sketch.\n     *\n     * @return observations\n     */', '/**\n     * 返回已添加到草图的观测值数量。\n     *\n     * @return 观测值数量\n     */'),
        ('/**\n     * Returns the number of compaction operations performed on the sketch.\n     *\n     * @return total compressions\n     */', '/**\n     * 返回草图执行的压缩（compaction）次数。\n     *\n     * @return 压缩次数\n     */'),
        ('/**\n     * Returns the number of bytes allocated for the sketch.\n     *\n     * @return memory usage in bytes\n     */', '/**\n     * 返回草图占用的字节数。\n     *\n     * @return 内存占用（字节）\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/TimeSeriesEntry.java': [
        ('/**\n * Time-series collection entry\n *\n * @author Nikita Koksharov\n *\n * @param <V> value type\n * @param <L> label type\n */', '/**\n * 时间序列集合条目。\n *\n * @author Nikita Koksharov\n *\n * @param <V> 值类型\n * @param <L> 标签类型\n */'),
    ],
    'TimeSeriesEntry.java': [
        ('/**\n * Time-series collection entry\n *\n * @author Nikita Koksharov\n *\n * @param <V> value type\n * @param <L> label type\n */', '/**\n * 时间序列集合条目。\n *\n * @author Nikita Koksharov\n *\n * @param <V> 值类型\n * @param <L> 标签类型\n */'),
    ],
    'redisson/src/main/java/org/redisson/api/TopKInfo.java': [
        ('/**\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * {@code TOPK.INFO} 命令返回的 Top-K 草图信息。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Returns the number of top items the Top-K keeps track of.\n     *\n     * @return number of top items (k)\n     */', '/**\n     * 返回 Top-K 跟踪的最高频元素数量。\n     *\n     * @return 跟踪的最高频元素数（k）\n     */'),
        ('/**\n     * Returns the number of counters in each array (width).\n     *\n     * @return width\n     */', '/**\n     * 返回每个计数器数组的宽度（width）。\n     *\n     * @return 计数器数组宽度\n     */'),
        ('/**\n     * Returns the number of counter arrays (depth).\n     *\n     * @return depth\n     */', '/**\n     * 返回计数器数组层数（depth）。\n     *\n     * @return 计数器数组层数\n     */'),
        ('/**\n     * Returns the probability of a counter being decreased on collision.\n     *\n     * @return counter decay probability\n     */', '/**\n     * 返回计数器冲突时被衰减的概率。\n     *\n     * @return 计数器衰减概率\n     */'),
    ],
    'TopKInfo.java': [
        ('/**\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * {@code TOPK.INFO} 命令返回的 Top-K 草图信息。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Returns the number of top items the Top-K keeps track of.\n     *\n     * @return number of top items (k)\n     */', '/**\n     * 返回 Top-K 跟踪的最高频元素数量。\n     *\n     * @return 跟踪的最高频元素数（k）\n     */'),
        ('/**\n     * Returns the number of counters in each array (width).\n     *\n     * @return width\n     */', '/**\n     * 返回每个计数器数组的宽度（width）。\n     *\n     * @return 计数器数组宽度\n     */'),
        ('/**\n     * Returns the number of counter arrays (depth).\n     *\n     * @return depth\n     */', '/**\n     * 返回计数器数组层数（depth）。\n     *\n     * @return 计数器数组层数\n     */'),
        ('/**\n     * Returns the probability of a counter being decreased on collision.\n     *\n     * @return counter decay probability\n     */', '/**\n     * 返回计数器冲突时被衰减的概率。\n     *\n     * @return 计数器衰减概率\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/TransactionOptions.java': [
        ('/**\n * Configuration for Transaction.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 事务配置。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Defines timeout for Redis response. \n     * Starts to countdown when transaction has been successfully sent.\n     * <p>\n     * Default is <code>3000 milliseconds</code>\n     * \n     * @param timeout value\n     * @param unit value\n     * @return self instance\n     */', '/**\n     * 定义 Redis 响应超时；\n     * 从事务成功发送后开始计时。\n     * <p>\n     * Default is <code>3000 milliseconds</code>\n     * \n     * @param timeout 超时值\n     * @param unit 时间单位\n     * @return 当前实例\n     */'),
        ("/**\n     * Defines attempts amount to send transaction\n     * if it hasn't been sent already.\n     * <p>\n     * Default is <code>3 attempts</code>\n     * \n     * @param retryAttempts value\n     * @return self instance\n     */", '/**\n     * 定义事务尚未成功发送时的重试次数。\n     * <p>\n     * Default is <code>3 attempts</code>\n     * \n     * @param retryAttempts 重试次数\n     * @return 当前实例\n     */'),
        ("/**\n     * Defines time interval for each attempt to send transaction \n     * if it hasn't been sent already.\n     * <p>\n     * Default is <code>1500 milliseconds</code>\n     * \n     * @param retryInterval time interval\n     * @param retryIntervalUnit time interval unit\n     * @return self instance\n     */", '/**\n     * 定义事务尚未成功发送时每次重试的间隔时间。\n     * <p>\n     * Default is <code>1500 milliseconds</code>\n     * \n     * @param retryInterval 重试间隔\n     * @param retryIntervalUnit 重试间隔单位\n     * @return 当前实例\n     */'),
        ('/**\n     * Use {@link #syncSlaves} method instead.\n     *\n     * @param syncTimeout synchronization timeout\n     * @param syncUnit synchronization timeout time unit\n     * @return self instance\n     */', '/**\n     * 请改用 {@link #syncSlaves} 方法。\n     *\n     * @param syncTimeout 同步超时\n     * @param syncUnit 同步超时时间单位\n     * @return 当前实例\n     */'),
        ('/**\n     * Synchronize write operations execution within defined timeout\n     * across specified amount of Redis slave nodes.\n     * <p>\n     * Default slaves value is <code>0</code> which means available slaves\n     * at the moment of execution and <code>-1</code> means no sync at all.\n     * <p>\n     * Default timeout value is <code>5000 milliseconds</code>\n     * NOTE: Redis 3.0+ required\n     *\n     * @param slaves slaves amount for synchronization.\n     *                 Default value is <code>0</code> which means available slaves\n     *                 at the moment of execution and <code>-1</code> means no sync at all.\n     * @param timeout synchronization timeout\n     * @param unit synchronization timeout time unit\n     * @return self instance\n     */', '/**\n     * 在指定超时内，将写操作同步到指定数量的 Redis 从节点。\n     * <p>\n     * Default slaves value is <code>0</code> which means available slaves\n     * at the moment of execution and <code>-1</code> means no sync at all.\n     * <p>\n     * Default timeout value is <code>5000 milliseconds</code>\n     * NOTE: Redis 3.0+ required\n     *\n     * @param slaves 参与同步的从节点数量\n     *                 Default value is <code>0</code> which means available slaves\n     *                 at the moment of execution and <code>-1</code> means no sync at all.\n     * @param timeout 同步超时\n     * @param unit 同步超时时间单位\n     * @return 当前实例\n     */'),
        ("/**\n     * If transaction hasn't been committed within <code>timeout</code> it will rollback automatically.\n     * Set <code>-1</code> to disable.\n     * <p>\n     * Default is <code>5000 milliseconds</code>\n     * \n     * @param timeout in milliseconds\n     * @param timeoutUnit timeout time unit\n     * @return self instance\n     */", '/**\n     * 若事务在 <code>timeout</code> 内未提交则自动回滚；\n     * 设为 <code>-1</code> 可禁用。\n     * <p>\n     * Default is <code>5000 milliseconds</code>\n     * \n     * @param timeout 超时时间\n     * @param timeoutUnit 超时时间单位\n     * @return 当前实例\n     */'),
    ],
    'TransactionOptions.java': [
        ('/**\n * Configuration for Transaction.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 事务配置。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Defines timeout for Redis response. \n     * Starts to countdown when transaction has been successfully sent.\n     * <p>\n     * Default is <code>3000 milliseconds</code>\n     * \n     * @param timeout value\n     * @param unit value\n     * @return self instance\n     */', '/**\n     * 定义 Redis 响应超时；\n     * 从事务成功发送后开始计时。\n     * <p>\n     * Default is <code>3000 milliseconds</code>\n     * \n     * @param timeout 超时值\n     * @param unit 时间单位\n     * @return 当前实例\n     */'),
        ("/**\n     * Defines attempts amount to send transaction\n     * if it hasn't been sent already.\n     * <p>\n     * Default is <code>3 attempts</code>\n     * \n     * @param retryAttempts value\n     * @return self instance\n     */", '/**\n     * 定义事务尚未成功发送时的重试次数。\n     * <p>\n     * Default is <code>3 attempts</code>\n     * \n     * @param retryAttempts 重试次数\n     * @return 当前实例\n     */'),
        ("/**\n     * Defines time interval for each attempt to send transaction \n     * if it hasn't been sent already.\n     * <p>\n     * Default is <code>1500 milliseconds</code>\n     * \n     * @param retryInterval time interval\n     * @param retryIntervalUnit time interval unit\n     * @return self instance\n     */", '/**\n     * 定义事务尚未成功发送时每次重试的间隔时间。\n     * <p>\n     * Default is <code>1500 milliseconds</code>\n     * \n     * @param retryInterval 重试间隔\n     * @param retryIntervalUnit 重试间隔单位\n     * @return 当前实例\n     */'),
        ('/**\n     * Use {@link #syncSlaves} method instead.\n     *\n     * @param syncTimeout synchronization timeout\n     * @param syncUnit synchronization timeout time unit\n     * @return self instance\n     */', '/**\n     * 请改用 {@link #syncSlaves} 方法。\n     *\n     * @param syncTimeout 同步超时\n     * @param syncUnit 同步超时时间单位\n     * @return 当前实例\n     */'),
        ('/**\n     * Synchronize write operations execution within defined timeout\n     * across specified amount of Redis slave nodes.\n     * <p>\n     * Default slaves value is <code>0</code> which means available slaves\n     * at the moment of execution and <code>-1</code> means no sync at all.\n     * <p>\n     * Default timeout value is <code>5000 milliseconds</code>\n     * NOTE: Redis 3.0+ required\n     *\n     * @param slaves slaves amount for synchronization.\n     *                 Default value is <code>0</code> which means available slaves\n     *                 at the moment of execution and <code>-1</code> means no sync at all.\n     * @param timeout synchronization timeout\n     * @param unit synchronization timeout time unit\n     * @return self instance\n     */', '/**\n     * 在指定超时内，将写操作同步到指定数量的 Redis 从节点。\n     * <p>\n     * Default slaves value is <code>0</code> which means available slaves\n     * at the moment of execution and <code>-1</code> means no sync at all.\n     * <p>\n     * Default timeout value is <code>5000 milliseconds</code>\n     * NOTE: Redis 3.0+ required\n     *\n     * @param slaves 参与同步的从节点数量\n     *                 Default value is <code>0</code> which means available slaves\n     *                 at the moment of execution and <code>-1</code> means no sync at all.\n     * @param timeout 同步超时\n     * @param unit 同步超时时间单位\n     * @return 当前实例\n     */'),
        ("/**\n     * If transaction hasn't been committed within <code>timeout</code> it will rollback automatically.\n     * Set <code>-1</code> to disable.\n     * <p>\n     * Default is <code>5000 milliseconds</code>\n     * \n     * @param timeout in milliseconds\n     * @param timeoutUnit timeout time unit\n     * @return self instance\n     */", '/**\n     * 若事务在 <code>timeout</code> 内未提交则自动回滚；\n     * 设为 <code>-1</code> 可禁用。\n     * <p>\n     * Default is <code>5000 milliseconds</code>\n     * \n     * @param timeout 超时时间\n     * @param timeoutUnit 超时时间单位\n     * @return 当前实例\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/WorkerOptions.java': [
        ('/**\n * Configuration for RExecutorService workers.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * RExecutorService 工作线程配置。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Defines workers amount used to execute tasks.\n     * Default is <code>1</code>.\n     * \n     * @param workers workers amount\n     * @return self instance\n     */', '/**\n     * 定义用于执行任务的工作线程数量。\n     * Default is <code>1</code>.\n     * \n     * @param workers 工作线程数量\n     * @return 当前实例\n     */'),
        ('/**\n     * Use {@code tasksInjector(new SpringTasksInjector(beanFactory)} instead.\n     *\n     * @param beanFactory Spring BeanFactory instance\n     * @return self instance\n     */', '/**\n     * 请改用 {@code tasksInjector(new SpringTasksInjector(beanFactory))}。\n     *\n     * @param beanFactory Spring BeanFactory 实例\n     * @return 当前实例\n     */'),
        ("/**\n     * Defines TasksInjector instance to execute tasks with CDI.\n     * For example, Spring's '@Autowired', '@Value' or JSR-330's '@Inject' annotation.\n     *\n     * @param tasksInjector task\n     * @return self instance\n     *\n     * @see SpringTasksInjector\n     */", '/**\n     * 定义用于 CDI 注入的任务执行器；\n     * 例如 Spring 的 {@code @Autowired}、{@code @Value} 或 JSR-330 的 {@code @Inject}。\n     *\n     * @param tasksInjector 任务注入器\n     * @return 当前实例\n     *\n     * @see SpringTasksInjector\n     */'),
        ('/**\n     * Defines custom ExecutorService to execute tasks.\n     * {@link Config#setExecutor(ExecutorService)} is used by default.\n     * \n     * @param executorService custom ExecutorService\n     * @return self instance\n     */', '/**\n     * 定义用于执行任务的自定义 {@link ExecutorService}；\n     * 默认使用 {@link Config#setExecutor(ExecutorService)}。\n     * \n     * @param executorService 自定义 ExecutorService\n     * @return 当前实例\n     */'),
        ('/**\n     * Defines task timeout since task execution start moment\n     *\n     * @param timeout timeout of task\n     * @param unit time unit\n     * @return self instance\n     */', '/**\n     * 定义自任务开始执行起的超时时间。\n     *\n     * @param timeout 任务超时\n     * @param unit 时间单位\n     * @return 当前实例\n     */'),
        ('/**\n     * Defines the lateness threshold for scheduled tasks.\n     * <p>\n     * If a worker picks up a scheduled task later than this threshold past its\n     * intended execution time, the task is skipped instead of executed.\n     * <p>\n     * Default is <code>null</code> - disabled, all missed tasks run immediately.\n     *\n     * @param threshold maximum allowed lateness\n     * @return self instance\n     */', '/**\n     * 定义定时任务的迟到阈值。\n     * <p>\n     * 若工作线程在计划执行时间超过该阈值后才领取任务，则跳过而非执行。\n     * <p>\n     * Default is <code>null</code> - disabled, all missed tasks run immediately.\n     *\n     * @param threshold 允许的最大迟到时间\n     * @return 当前实例\n     */'),
        ('/**\n     * Adds task listener\n     *\n     * @see org.redisson.api.executor.TaskSuccessListener\n     * @see org.redisson.api.executor.TaskFailureListener\n     * @see org.redisson.api.executor.TaskStartedListener\n     * @see org.redisson.api.executor.TaskFinishedListener\n     *\n     * @param listener - task listener\n     * @return self instance\n     */', '/**\n     * 添加任务监听器。\n     *\n     * @see org.redisson.api.executor.TaskSuccessListener\n     * @see org.redisson.api.executor.TaskFailureListener\n     * @see org.redisson.api.executor.TaskStartedListener\n     * @see org.redisson.api.executor.TaskFinishedListener\n     *\n     * @param listener 任务监听器\n     * @return 当前实例\n     */'),
    ],
    'WorkerOptions.java': [
        ('/**\n * Configuration for RExecutorService workers.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * RExecutorService 工作线程配置。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('/**\n     * Defines workers amount used to execute tasks.\n     * Default is <code>1</code>.\n     * \n     * @param workers workers amount\n     * @return self instance\n     */', '/**\n     * 定义用于执行任务的工作线程数量。\n     * Default is <code>1</code>.\n     * \n     * @param workers 工作线程数量\n     * @return 当前实例\n     */'),
        ('/**\n     * Use {@code tasksInjector(new SpringTasksInjector(beanFactory)} instead.\n     *\n     * @param beanFactory Spring BeanFactory instance\n     * @return self instance\n     */', '/**\n     * 请改用 {@code tasksInjector(new SpringTasksInjector(beanFactory))}。\n     *\n     * @param beanFactory Spring BeanFactory 实例\n     * @return 当前实例\n     */'),
        ("/**\n     * Defines TasksInjector instance to execute tasks with CDI.\n     * For example, Spring's '@Autowired', '@Value' or JSR-330's '@Inject' annotation.\n     *\n     * @param tasksInjector task\n     * @return self instance\n     *\n     * @see SpringTasksInjector\n     */", '/**\n     * 定义用于 CDI 注入的任务执行器；\n     * 例如 Spring 的 {@code @Autowired}、{@code @Value} 或 JSR-330 的 {@code @Inject}。\n     *\n     * @param tasksInjector 任务注入器\n     * @return 当前实例\n     *\n     * @see SpringTasksInjector\n     */'),
        ('/**\n     * Defines custom ExecutorService to execute tasks.\n     * {@link Config#setExecutor(ExecutorService)} is used by default.\n     * \n     * @param executorService custom ExecutorService\n     * @return self instance\n     */', '/**\n     * 定义用于执行任务的自定义 {@link ExecutorService}；\n     * 默认使用 {@link Config#setExecutor(ExecutorService)}。\n     * \n     * @param executorService 自定义 ExecutorService\n     * @return 当前实例\n     */'),
        ('/**\n     * Defines task timeout since task execution start moment\n     *\n     * @param timeout timeout of task\n     * @param unit time unit\n     * @return self instance\n     */', '/**\n     * 定义自任务开始执行起的超时时间。\n     *\n     * @param timeout 任务超时\n     * @param unit 时间单位\n     * @return 当前实例\n     */'),
        ('/**\n     * Defines the lateness threshold for scheduled tasks.\n     * <p>\n     * If a worker picks up a scheduled task later than this threshold past its\n     * intended execution time, the task is skipped instead of executed.\n     * <p>\n     * Default is <code>null</code> - disabled, all missed tasks run immediately.\n     *\n     * @param threshold maximum allowed lateness\n     * @return self instance\n     */', '/**\n     * 定义定时任务的迟到阈值。\n     * <p>\n     * 若工作线程在计划执行时间超过该阈值后才领取任务，则跳过而非执行。\n     * <p>\n     * Default is <code>null</code> - disabled, all missed tasks run immediately.\n     *\n     * @param threshold 允许的最大迟到时间\n     * @return 当前实例\n     */'),
        ('/**\n     * Adds task listener\n     *\n     * @see org.redisson.api.executor.TaskSuccessListener\n     * @see org.redisson.api.executor.TaskFailureListener\n     * @see org.redisson.api.executor.TaskStartedListener\n     * @see org.redisson.api.executor.TaskFinishedListener\n     *\n     * @param listener - task listener\n     * @return self instance\n     */', '/**\n     * 添加任务监听器。\n     *\n     * @see org.redisson.api.executor.TaskSuccessListener\n     * @see org.redisson.api.executor.TaskFailureListener\n     * @see org.redisson.api.executor.TaskStartedListener\n     * @see org.redisson.api.executor.TaskFinishedListener\n     *\n     * @param listener 任务监听器\n     * @return 当前实例\n     */'),
    ],
}
