"""Chinese JavaDoc replacements for springframework wave16a transaction managers [9:12]."""

TX_MANAGERS_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "PlatformTransactionManager.java": [
        (
            "/**\n * This is the central interface in Spring's imperative transaction infrastructure.\n * Applications can use this directly, but it is not primarily meant as an API:\n * Typically, applications will work with either TransactionTemplate or\n * declarative transaction demarcation through AOP.\n *\n * <p>For implementors, it is recommended to derive from the provided\n * {@link org.springframework.transaction.support.AbstractPlatformTransactionManager}\n * class, which pre-implements the defined propagation behavior and takes care\n * of transaction synchronization handling. Subclasses have to implement\n * template methods for specific states of the underlying transaction,\n * for example: begin, suspend, resume, commit.\n *\n * <p>A classic implementation of this strategy interface is\n * {@link org.springframework.transaction.jta.JtaTransactionManager}. However,\n * in common single-resource scenarios, Spring's specific transaction managers\n * for example, JDBC, JPA, JMS are preferred choices.\n *\n * @author Rod Johnson\n * @author Juergen Hoeller\n * @since 16.05.2003\n * @see org.springframework.transaction.support.TransactionTemplate\n * @see org.springframework.transaction.interceptor.TransactionInterceptor\n * @see org.springframework.transaction.ReactiveTransactionManager\n * @see ConfigurableTransactionManager\n */",
            "/**\n * Spring 命令式事务基础设施的核心接口。\n * 应用可直接使用，但主要并非作为 API 设计：\n * 通常应用通过 TransactionTemplate 或 AOP 声明式事务划分工作。\n *\n * <p>对实现者，建议继承提供的\n * {@link org.springframework.transaction.support.AbstractPlatformTransactionManager}\n * 类，其预实现定义的传播行为并处理事务同步。\n * 子类需实现底层事务特定状态的模板方法，\n * 例如 begin、suspend、resume、commit。\n *\n * <p>本策略接口的经典实现为\n * {@link org.springframework.transaction.jta.JtaTransactionManager}。\n * 但在常见单资源场景中，Spring 特定事务管理器\n * （如 JDBC、JPA、JMS）更受青睐。\n *\n * @author Rod Johnson\n * @author Juergen Hoeller\n * @since 16.05.2003\n * @see org.springframework.transaction.support.TransactionTemplate\n * @see org.springframework.transaction.interceptor.TransactionInterceptor\n * @see org.springframework.transaction.ReactiveTransactionManager\n * @see ConfigurableTransactionManager\n */",
        ),
        (
            "\t/**\n\t * Return a currently active transaction or create a new one, according to\n\t * the specified propagation behavior.\n\t * <p>Note that parameters like isolation level or timeout will only be applied\n\t * to new transactions, and thus be ignored when participating in active ones.\n\t * <p>Furthermore, not all transaction definition settings will be supported\n\t * by every transaction manager: A proper transaction manager implementation\n\t * should throw an exception when unsupported settings are encountered.\n\t * <p>An exception to the above rule is the read-only flag, which should be\n\t * ignored if no explicit read-only mode is supported. Essentially, the\n\t * read-only flag is just a hint for potential optimization.\n\t * @param definition the TransactionDefinition instance (can be {@code null} for defaults),\n\t * describing propagation behavior, isolation level, timeout etc.\n\t * @return transaction status object representing the new or current transaction\n\t * @throws TransactionException in case of lookup, creation, or system errors\n\t * @throws IllegalTransactionStateException if the given transaction definition\n\t * cannot be executed (for example, if a currently active transaction is in\n\t * conflict with the specified propagation behavior)\n\t * @see TransactionDefinition#getPropagationBehavior\n\t * @see TransactionDefinition#getIsolationLevel\n\t * @see TransactionDefinition#getTimeout\n\t * @see TransactionDefinition#isReadOnly\n\t */",
            "\t/**\n\t * 根据指定传播行为返回当前活动事务或创建新事务。\n\t * <p>注意，隔离级别、超时等参数仅应用于新事务，\n\t * 参与现有活动事务时将被忽略。\n\t * <p>此外，并非所有事务定义设置都被每个事务管理器支持：\n\t * 合适实现遇到不支持的设置时应抛出异常。\n\t * <p>上述规则的例外是只读标志：若不支持显式只读模式应被忽略。\n\t * 本质上只读标志只是潜在优化的提示。\n\t * @param definition TransactionDefinition 实例（可为 {@code null} 使用默认值），\n\t * 描述传播行为、隔离级别、超时等\n\t * @return 表示新事务或当前事务的状态对象\n\t * @throws TransactionException 查找、创建或系统错误时\n\t * @throws IllegalTransactionStateException 给定事务定义无法执行时\n\t * （例如当前活动事务与指定传播行为冲突）\n\t * @see TransactionDefinition#getPropagationBehavior\n\t * @see TransactionDefinition#getIsolationLevel\n\t * @see TransactionDefinition#getTimeout\n\t * @see TransactionDefinition#isReadOnly\n\t */",
        ),
        (
            "\t/**\n\t * Commit the given transaction, with regard to its status. If the transaction\n\t * has been marked rollback-only programmatically, perform a rollback.\n\t * <p>If the transaction wasn't a new one, omit the commit for proper\n\t * participation in the surrounding transaction. If a previous transaction\n\t * has been suspended to be able to create a new one, resume the previous\n\t * transaction after committing the new one.\n\t * <p>Note that when the commit call completes, no matter if normally or\n\t * throwing an exception, the transaction must be fully completed and\n\t * cleaned up. No rollback call should be expected in such a case.\n\t * <p>Depending on the concrete transaction manager setup, {@code commit}\n\t * may propagate {@link org.springframework.dao.DataAccessException} as well,\n\t * either from before-commit flushes or from the actual commit step.\n\t * @param status object returned by the {@code getTransaction} method\n\t * @throws UnexpectedRollbackException in case of an unexpected rollback\n\t * that the transaction coordinator initiated\n\t * @throws HeuristicCompletionException in case of a transaction failure\n\t * caused by a heuristic decision on the side of the transaction coordinator\n\t * @throws TransactionSystemException in case of commit or system errors\n\t * (typically caused by fundamental resource failures)\n\t * @throws IllegalTransactionStateException if the given transaction\n\t * is already completed (that is, committed or rolled back)\n\t * @see TransactionStatus#setRollbackOnly\n\t */",
            "\t/**\n\t * 根据状态提交给定事务。若事务已被编程式标记为仅回滚，则执行回滚。\n\t * <p>若非新事务，为正确参与外围事务则省略 commit。\n\t * 若先前事务被挂起以创建新事务，\n\t * 提交新事务后恢复先前事务。\n\t * <p>注意，commit 调用完成时（无论正常还是抛异常），\n\t * 事务必须已完全完成并清理。此时不应再期望 rollback 调用。\n\t * <p>取决于具体事务管理器配置，{@code commit} 也可能传播\n\t * {@link org.springframework.dao.DataAccessException}，\n\t * 来自 commit 前 flush 或实际 commit 步骤。\n\t * @param status {@code getTransaction} 方法返回的对象\n\t * @throws UnexpectedRollbackException 事务协调器发起意外回滚时\n\t * @throws HeuristicCompletionException 事务协调器启发式决策导致失败时\n\t * @throws TransactionSystemException commit 或系统错误时\n\t * （通常由根本性资源失败引起）\n\t * @throws IllegalTransactionStateException 给定事务已完成\n\t * （已提交或已回滚）时\n\t * @see TransactionStatus#setRollbackOnly\n\t */",
        ),
        (
            "\t/**\n\t * Perform a rollback of the given transaction.\n\t * <p>If the transaction wasn't a new one, just set it rollback-only for proper\n\t * participation in the surrounding transaction. If a previous transaction\n\t * has been suspended to be able to create a new one, resume the previous\n\t * transaction after rolling back the new one.\n\t * <p><b>Do not call rollback on a transaction if commit threw an exception.</b>\n\t * The transaction will already have been completed and cleaned up when commit\n\t * returns, even in case of a commit exception. Consequently, a rollback call\n\t * after commit failure will lead to an IllegalTransactionStateException.\n\t * <p>Depending on the concrete transaction manager setup, {@code rollback}\n\t * may propagate {@link org.springframework.dao.DataAccessException} as well.\n\t * @param status object returned by the {@code getTransaction} method\n\t * @throws TransactionSystemException in case of rollback or system errors\n\t * (typically caused by fundamental resource failures)\n\t * @throws IllegalTransactionStateException if the given transaction\n\t * is already completed (that is, committed or rolled back)\n\t */",
            "\t/**\n\t * 对给定事务执行回滚。\n\t * <p>若非新事务，为正确参与外围事务仅将其设为仅回滚。\n\t * 若先前事务被挂起以创建新事务，\n\t * 回滚新事务后恢复先前事务。\n\t * <p><b>若 commit 已抛异常，请勿对事务调用 rollback。</b>\n\t * commit 返回时事务已完全完成并清理，即使 commit 异常亦然。\n\t * 因此 commit 失败后调用 rollback 将导致 IllegalTransactionStateException。\n\t * <p>取决于具体事务管理器配置，{@code rollback} 也可能传播\n\t * {@link org.springframework.dao.DataAccessException}。\n\t * @param status {@code getTransaction} 方法返回的对象\n\t * @throws TransactionSystemException rollback 或系统错误时\n\t * （通常由根本性资源失败引起）\n\t * @throws IllegalTransactionStateException 给定事务已完成\n\t * （已提交或已回滚）时\n\t */",
        ),
    ],
    "ReactiveTransactionManager.java": [
        (
            "/**\n * This is the central interface in Spring's reactive transaction infrastructure.\n * Applications can use this directly, but it is not primarily meant as an API:\n * Typically, applications will work with either transactional operators or\n * declarative transaction demarcation through AOP.\n *\n * @author Mark Paluch\n * @author Juergen Hoeller\n * @since 5.2\n * @see org.springframework.transaction.reactive.TransactionalOperator\n * @see org.springframework.transaction.interceptor.TransactionInterceptor\n * @see org.springframework.transaction.PlatformTransactionManager\n * @see ConfigurableTransactionManager\n */",
            "/**\n * Spring 响应式事务基础设施的核心接口。\n * 应用可直接使用，但主要并非作为 API 设计：\n * 通常应用通过事务操作符或 AOP 声明式事务划分工作。\n *\n * @author Mark Paluch\n * @author Juergen Hoeller\n * @since 5.2\n * @see org.springframework.transaction.reactive.TransactionalOperator\n * @see org.springframework.transaction.interceptor.TransactionInterceptor\n * @see org.springframework.transaction.PlatformTransactionManager\n * @see ConfigurableTransactionManager\n */",
        ),
        (
            "\t/**\n\t * Emit a currently active reactive transaction or create a new one, according to\n\t * the specified propagation behavior.\n\t * <p>Note that parameters like isolation level or timeout will only be applied\n\t * to new transactions, and thus be ignored when participating in active ones.\n\t * <p>Furthermore, not all transaction definition settings will be supported\n\t * by every transaction manager: A proper transaction manager implementation\n\t * should throw an exception when unsupported settings are encountered.\n\t * <p>An exception to the above rule is the read-only flag, which should be\n\t * ignored if no explicit read-only mode is supported. Essentially, the\n\t * read-only flag is just a hint for potential optimization.\n\t * <p>Note: In contrast to {@link PlatformTransactionManager}, exceptions\n\t * are propagated through the reactive pipeline returned from this method.\n\t * @param definition the TransactionDefinition instance,\n\t * describing propagation behavior, isolation level, timeout etc.\n\t * @return transaction status object representing the new or current transaction\n\t * @throws TransactionException in case of lookup, creation, or system errors\n\t * @throws IllegalTransactionStateException if the given transaction definition\n\t * cannot be executed (for example, if a currently active transaction is in\n\t * conflict with the specified propagation behavior)\n\t * @see TransactionDefinition#getPropagationBehavior\n\t * @see TransactionDefinition#getIsolationLevel\n\t * @see TransactionDefinition#getTimeout\n\t * @see TransactionDefinition#isReadOnly\n\t */",
            "\t/**\n\t * 根据指定传播行为发出当前活动响应式事务或创建新事务。\n\t * <p>注意，隔离级别、超时等参数仅应用于新事务，\n\t * 参与现有活动事务时将被忽略。\n\t * <p>此外，并非所有事务定义设置都被每个事务管理器支持：\n\t * 合适实现遇到不支持的设置时应抛出异常。\n\t * <p>上述规则的例外是只读标志：若不支持显式只读模式应被忽略。\n\t * 本质上只读标志只是潜在优化的提示。\n\t * <p>注意：与 {@link PlatformTransactionManager} 不同，\n\t * 异常通过本方法返回的响应式管道传播。\n\t * @param definition TransactionDefinition 实例，\n\t * 描述传播行为、隔离级别、超时等\n\t * @return 表示新事务或当前事务的状态对象\n\t * @throws TransactionException 查找、创建或系统错误时\n\t * @throws IllegalTransactionStateException 给定事务定义无法执行时\n\t * （例如当前活动事务与指定传播行为冲突）\n\t * @see TransactionDefinition#getPropagationBehavior\n\t * @see TransactionDefinition#getIsolationLevel\n\t * @see TransactionDefinition#getTimeout\n\t * @see TransactionDefinition#isReadOnly\n\t */",
        ),
        (
            "\t/**\n\t * Commit the given transaction, with regard to its status. If the transaction\n\t * has been marked rollback-only programmatically, perform a rollback.\n\t * <p>If the transaction wasn't a new one, omit the commit for proper\n\t * participation in the surrounding transaction. If a previous transaction\n\t * has been suspended to be able to create a new one, resume the previous\n\t * transaction after committing the new one.\n\t * <p>Note that when the commit call completes, no matter if normally or\n\t * propagating an exception, the transaction must be fully completed and\n\t * cleaned up. No rollback call should be expected in such a case.\n\t * <p>Note: In contrast to {@link PlatformTransactionManager}, exceptions\n\t * are propagated through the reactive pipeline returned from this method.\n\t * Also, depending on the transaction manager implementation, {@code commit}\n\t * may propagate {@link org.springframework.dao.DataAccessException} as well.\n\t * @param transaction object returned by the {@code getTransaction} method\n\t * @throws UnexpectedRollbackException in case of an unexpected rollback\n\t * that the transaction coordinator initiated\n\t * @throws HeuristicCompletionException in case of a transaction failure\n\t * caused by a heuristic decision on the side of the transaction coordinator\n\t * @throws TransactionSystemException in case of commit or system errors\n\t * (typically caused by fundamental resource failures)\n\t * @throws IllegalTransactionStateException if the given transaction\n\t * is already completed (that is, committed or rolled back)\n\t * @see ReactiveTransaction#setRollbackOnly\n\t */",
            "\t/**\n\t * 根据状态提交给定事务。若事务已被编程式标记为仅回滚，则执行回滚。\n\t * <p>若非新事务，为正确参与外围事务则省略 commit。\n\t * 若先前事务被挂起以创建新事务，\n\t * 提交新事务后恢复先前事务。\n\t * <p>注意，commit 调用完成时（无论正常还是传播异常），\n\t * 事务必须已完全完成并清理。此时不应再期望 rollback 调用。\n\t * <p>注意：与 {@link PlatformTransactionManager} 不同，\n\t * 异常通过本方法返回的响应式管道传播。\n\t * 此外，取决于事务管理器实现，{@code commit} 也可能传播\n\t * {@link org.springframework.dao.DataAccessException}。\n\t * @param transaction {@code getTransaction} 方法返回的对象\n\t * @throws UnexpectedRollbackException 事务协调器发起意外回滚时\n\t * @throws HeuristicCompletionException 事务协调器启发式决策导致失败时\n\t * @throws TransactionSystemException commit 或系统错误时\n\t * （通常由根本性资源失败引起）\n\t * @throws IllegalTransactionStateException 给定事务已完成\n\t * （已提交或已回滚）时\n\t * @see ReactiveTransaction#setRollbackOnly\n\t */",
        ),
        (
            "\t/**\n\t * Perform a rollback of the given transaction.\n\t * <p>If the transaction wasn't a new one, just set it rollback-only for proper\n\t * participation in the surrounding transaction. If a previous transaction\n\t * has been suspended to be able to create a new one, resume the previous\n\t * transaction after rolling back the new one.\n\t * <p><b>Do not call rollback on a transaction if commit failed.</b>\n\t * The transaction will already have been completed and cleaned up when commit\n\t * returns, even in case of a commit exception. Consequently, a rollback call\n\t * after commit failure will lead to an IllegalTransactionStateException.\n\t * <p>Note: In contrast to {@link PlatformTransactionManager}, exceptions\n\t * are propagated through the reactive pipeline returned from this method.\n\t * Also, depending on the transaction manager implementation, {@code rollback}\n\t * may propagate {@link org.springframework.dao.DataAccessException} as well.\n\t * @param transaction object returned by the {@code getTransaction} method\n\t * @throws TransactionSystemException in case of rollback or system errors\n\t * (typically caused by fundamental resource failures)\n\t * @throws IllegalTransactionStateException if the given transaction\n\t * is already completed (that is, committed or rolled back)\n\t */",
            "\t/**\n\t * 对给定事务执行回滚。\n\t * <p>若非新事务，为正确参与外围事务仅将其设为仅回滚。\n\t * 若先前事务被挂起以创建新事务，\n\t * 回滚新事务后恢复先前事务。\n\t * <p><b>若 commit 失败，请勿对事务调用 rollback。</b>\n\t * commit 返回时事务已完全完成并清理，即使 commit 异常亦然。\n\t * 因此 commit 失败后调用 rollback 将导致 IllegalTransactionStateException。\n\t * <p>注意：与 {@link PlatformTransactionManager} 不同，\n\t * 异常通过本方法返回的响应式管道传播。\n\t * 此外，取决于事务管理器实现，{@code rollback} 也可能传播\n\t * {@link org.springframework.dao.DataAccessException}。\n\t * @param transaction {@code getTransaction} 方法返回的对象\n\t * @throws TransactionSystemException rollback 或系统错误时\n\t * （通常由根本性资源失败引起）\n\t * @throws IllegalTransactionStateException 给定事务已完成\n\t * （已提交或已回滚）时\n\t */",
        ),
    ],
}
