"""Chinese JavaDoc replacements for Spring Boot 4.1.0 wave16a Binder."""

BINDER_REPLACEMENTS: list[tuple[str, str]] = [
    (
        "/**\n * A container object which Binds objects from one or more\n * {@link ConfigurationPropertySource ConfigurationPropertySources}.\n *\n * @author Phillip Webb\n * @author Madhura Bhave\n * @since 2.0.0\n */",
        "/**\n * 从一个或多个 {@link ConfigurationPropertySource 配置属性源} 绑定对象的容器。\n * 负责将配置属性解析、转换并填充到目标对象（JavaBean 或值对象）。\n *\n * @author Phillip Webb\n * @author Madhura Bhave\n * @since 2.0.0\n */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources. A\n\t * {@link DefaultFormattingConversionService} will be used for all conversion.\n\t * @param sources the sources used for binding\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t * 所有类型转换均使用 {@link DefaultFormattingConversionService}。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources. A\n\t * {@link DefaultFormattingConversionService} will be used for all conversion.\n\t * @param sources the sources used for binding\n\t */\n\tpublic Binder(Iterable<ConfigurationPropertySource> sources) {",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t * 所有类型转换均使用 {@link DefaultFormattingConversionService}。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t */\n\tpublic Binder(Iterable<ConfigurationPropertySource> sources) {",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources.\n\t * @param sources the sources used for binding\n\t * @param placeholdersResolver strategy to resolve any property placeholders\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t * @param placeholdersResolver strategy to resolve any property placeholders 占位符解析策略\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources.\n\t * @param sources the sources used for binding\n\t * @param placeholdersResolver strategy to resolve any property placeholders\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService})\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t * @param placeholdersResolver strategy to resolve any property placeholders 占位符解析策略\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService}) 值转换服务（{@code null} 时使用 {@link ApplicationConversionService}）\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources.\n\t * @param sources the sources used for binding\n\t * @param placeholdersResolver strategy to resolve any property placeholders\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService})\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo}.\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t * @param placeholdersResolver strategy to resolve any property placeholders 占位符解析策略\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService}) 值转换服务（{@code null} 时使用 {@link ApplicationConversionService}）\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo} 配置 PropertyEditor 的初始化器（无需时可 {@code null}，常调用 {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo}）\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources.\n\t * @param sources the sources used for binding\n\t * @param placeholdersResolver strategy to resolve any property placeholders\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService})\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo}.\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding\n\t * @since 2.2.0\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t * @param placeholdersResolver strategy to resolve any property placeholders 占位符解析策略\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService}) 值转换服务\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo} PropertyEditor 初始化器\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding 未指定时使用的默认绑定处理器\n\t * @since 2.2.0\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources.\n\t * @param sources the sources used for binding\n\t * @param placeholdersResolver strategy to resolve any property placeholders\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService})\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo}.\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding\n\t * @param constructorProvider the constructor provider which provides the bind\n\t * constructor to use when binding\n\t * @since 2.2.1\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t * @param placeholdersResolver strategy to resolve any property placeholders 占位符解析策略\n\t * @param conversionService the conversion service to convert values (or {@code null}\n\t * to use {@link ApplicationConversionService}) 值转换服务\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo} PropertyEditor 初始化器\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding 默认绑定处理器\n\t * @param constructorProvider the constructor provider which provides the bind\n\t * constructor to use when binding 提供绑定构造器的构造器提供者\n\t * @since 2.2.1\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance for the specified sources.\n\t * @param sources the sources used for binding\n\t * @param placeholdersResolver strategy to resolve any property placeholders\n\t * @param conversionServices the conversion services to convert values (or\n\t * {@code null} to use {@link ApplicationConversionService})\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo}.\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding\n\t * @param constructorProvider the constructor provider which provides the bind\n\t * constructor to use when binding\n\t * @since 2.5.0\n\t */",
        "\t/**\n\t * 为指定属性源创建新的 {@link Binder} 实例。\n\t *\n\t * @param sources the sources used for binding 用于绑定的属性源\n\t * @param placeholdersResolver strategy to resolve any property placeholders 占位符解析策略\n\t * @param conversionServices the conversion services to convert values (or\n\t * {@code null} to use {@link ApplicationConversionService}) 值转换服务列表（{@code null} 时使用 {@link ApplicationConversionService}）\n\t * @param propertyEditorInitializer initializer used to configure the property editors\n\t * that can convert values (or {@code null} if no initialization is required). Often\n\t * used to call {@link ConfigurableListableBeanFactory#copyRegisteredEditorsTo} PropertyEditor 初始化器\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding 默认绑定处理器\n\t * @param constructorProvider the constructor provider which provides the bind\n\t * constructor to use when binding 构造器提供者\n\t * @since 2.5.0\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Class} using this binder's\n\t * {@link ConfigurationPropertySource property sources}.\n\t * @param name the configuration property name to bind\n\t * @param target the target class\n\t * @param <T> the bound type\n\t * @return the binding result (never {@code null})\n\t * @see #bind(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
        "\t/**\n\t * 使用本 binder 的 {@link ConfigurationPropertySource 属性源} 绑定指定目标 {@link Class}。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target class 目标类\n\t * @param <T> the bound type 绑定类型\n\t * @return the binding result (never {@code null}) 绑定结果（永不为 {@code null}）\n\t * @see #bind(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Bindable} using this binder's\n\t * {@link ConfigurationPropertySource property sources}.\n\t * @param name the configuration property name to bind\n\t * @param target the target bindable\n\t * @param <T> the bound type\n\t * @return the binding result (never {@code null})\n\t * @see #bind(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
        "\t/**\n\t * 使用本 binder 的 {@link ConfigurationPropertySource 属性源} 绑定指定 {@link Bindable}。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target bindable 目标 Bindable\n\t * @param <T> the bound type 绑定类型\n\t * @return the binding result (never {@code null}) 绑定结果（永不为 {@code null}）\n\t * @see #bind(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Bindable} using this binder's\n\t * {@link ConfigurationPropertySource property sources}.\n\t * @param name the configuration property name to bind\n\t * @param target the target bindable\n\t * @param handler the bind handler (may be {@code null})\n\t * @param <T> the bound type\n\t * @return the binding result (never {@code null})\n\t */",
        "\t/**\n\t * 使用本 binder 的 {@link ConfigurationPropertySource 属性源} 绑定指定 {@link Bindable}。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target bindable 目标 Bindable\n\t * @param handler the bind handler (may be {@code null}) 绑定处理器（可为 {@code null}）\n\t * @param <T> the bound type 绑定类型\n\t * @return the binding result (never {@code null}) 绑定结果（永不为 {@code null}）\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Class} using this binder's\n\t * {@link ConfigurationPropertySource property sources} or create a new instance of\n\t * the specified target {@link Class} if the result of the binding is {@code null}.\n\t * @param name the configuration property name to bind\n\t * @param target the target class\n\t * @param <T> the bound type\n\t * @return the bound or created object\n\t * @since 2.2.0\n\t * @see #bind(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
        "\t/**\n\t * 绑定指定 {@link Class}；若绑定结果为 {@code null} 则创建新实例。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target class 目标类\n\t * @param <T> the bound type 绑定类型\n\t * @return the bound or created object 绑定或新创建的对象\n\t * @since 2.2.0\n\t * @see #bind(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Bindable} using this binder's\n\t * {@link ConfigurationPropertySource property sources} or create a new instance using\n\t * the type of the {@link Bindable} if the result of the binding is {@code null}.\n\t * @param name the configuration property name to bind\n\t * @param target the target bindable\n\t * @param <T> the bound type\n\t * @return the bound or created object\n\t * @since 2.2.0\n\t * @see #bindOrCreate(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
        "\t/**\n\t * 绑定指定 {@link Bindable}；若结果为 {@code null} 则按 {@link Bindable} 类型创建新实例。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target bindable 目标 Bindable\n\t * @param <T> the bound type 绑定类型\n\t * @return the bound or created object 绑定或新创建的对象\n\t * @since 2.2.0\n\t * @see #bindOrCreate(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Bindable} using this binder's\n\t * {@link ConfigurationPropertySource property sources} or create a new instance using\n\t * the type of the {@link Bindable} if the result of the binding is {@code null}.\n\t * @param name the configuration property name to bind\n\t * @param target the target bindable\n\t * @param handler the bind handler\n\t * @param <T> the bound type\n\t * @return the bound or created object\n\t * @since 2.2.0\n\t * @see #bindOrCreate(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
        "\t/**\n\t * 绑定指定 {@link Bindable}；若结果为 {@code null} 则创建新实例。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target bindable 目标 Bindable\n\t * @param handler the bind handler 绑定处理器\n\t * @param <T> the bound type 绑定类型\n\t * @return the bound or created object 绑定或新创建的对象\n\t * @since 2.2.0\n\t * @see #bindOrCreate(ConfigurationPropertyName, Bindable, BindHandler)\n\t */",
    ),
    (
        "\t/**\n\t * Bind the specified target {@link Bindable} using this binder's\n\t * {@link ConfigurationPropertySource property sources} or create a new instance using\n\t * the type of the {@link Bindable} if the result of the binding is {@code null}.\n\t * @param name the configuration property name to bind\n\t * @param target the target bindable\n\t * @param handler the bind handler (may be {@code null})\n\t * @param <T> the bound or created type\n\t * @return the bound or created object\n\t * @since 2.2.0\n\t */",
        "\t/**\n\t * 绑定指定 {@link Bindable}；若结果为 {@code null} 则创建新实例。\n\t *\n\t * @param name the configuration property name to bind 要绑定的配置属性名\n\t * @param target the target bindable 目标 Bindable\n\t * @param handler the bind handler (may be {@code null}) 绑定处理器（可为 {@code null}）\n\t * @param <T> the bound or created type 绑定或创建的类型\n\t * @return the bound or created object 绑定或新创建的对象\n\t * @since 2.2.0\n\t */",
    ),
    (
        "\t\t\t\t// We might still be able to bind it using the recursive binders",
        "\t\t\t\t// 转换器未找到时，仍可能通过递归 binder 完成绑定",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance from the specified environment.\n\t * @param environment the environment source (must have attached\n\t * {@link ConfigurationPropertySources})\n\t * @return a {@link Binder} instance\n\t */",
        "\t/**\n\t * 从指定 {@link Environment} 创建新的 {@link Binder} 实例。\n\t *\n\t * @param environment the environment source (must have attached\n\t * {@link ConfigurationPropertySources}) 环境源（须已附加 {@link ConfigurationPropertySources}）\n\t * @return a {@link Binder} instance {@link Binder} 实例\n\t */",
    ),
    (
        "\t/**\n\t * Create a new {@link Binder} instance from the specified environment.\n\t * @param environment the environment source (must have attached\n\t * {@link ConfigurationPropertySources})\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding\n\t * @return a {@link Binder} instance\n\t * @since 2.2.0\n\t */",
        "\t/**\n\t * 从指定 {@link Environment} 创建新的 {@link Binder} 实例。\n\t *\n\t * @param environment the environment source (must have attached\n\t * {@link ConfigurationPropertySources}) 环境源（须已附加 {@link ConfigurationPropertySources}）\n\t * @param defaultBindHandler the default bind handler to use if none is specified when\n\t * binding 未指定时使用的默认绑定处理器\n\t * @return a {@link Binder} instance {@link Binder} 实例\n\t * @since 2.2.0\n\t */",
    ),
    (
        "\t/**\n\t * Context used when binding and the {@link BindContext} implementation.\n\t */",
        "\t/**\n\t * 绑定过程中使用的上下文，也是 {@link BindContext} 的实现。\n\t */",
    ),
]
