"""Chinese JavaDoc replacements for RocketMQ wave42b tools [15:30]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/admin/MQAdminUtils.java': [
        ('public class MQAdminUtils {',
         '/**\n * MQ 管理工具类：封装集群/Topic 元数据刷新、静态 Topic 重映射及物理/逻辑统计转换等管理操作。\n */\npublic class MQAdminUtils {'),
        ('    public static ClientMetadata getBrokerMetadata(DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 拉取并刷新集群 Broker 元数据，返回 {@link ClientMetadata}。 */\n    public static ClientMetadata getBrokerMetadata(DefaultMQAdminExt defaultMQAdminExt)'),
        ('    public static ClientMetadata getBrokerAndTopicMetadata(String topic, DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 刷新集群元数据并加载指定 Topic 路由信息。 */\n    public static ClientMetadata getBrokerAndTopicMetadata(String topic, DefaultMQAdminExt defaultMQAdminExt)'),
        ('    public static void refreshClusterInfo(DefaultMQAdminExt defaultMQAdminExt, ClientMetadata clientMetadata)',
         '    /** 从 NameServer 拉取集群信息并写入 clientMetadata；集群为空则抛异常。 */\n    public static void refreshClusterInfo(DefaultMQAdminExt defaultMQAdminExt, ClientMetadata clientMetadata)'),
        ('    public static void refreshTopicRouteInfo(String topic, DefaultMQAdminExt defaultMQAdminExt, ClientMetadata clientMetadata)',
         '    /** 查询 Topic 路由并刷新到 clientMetadata；Topic 不存在时忽略。 */\n    public static void refreshTopicRouteInfo(String topic, DefaultMQAdminExt defaultMQAdminExt, ClientMetadata clientMetadata)'),
        ('    public static Set<String> getAllBrokersInSameCluster(Collection<String> brokers, DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 根据给定 Broker 集合，返回其所在集群内的全部 Broker 名。 */\n    public static Set<String> getAllBrokersInSameCluster(Collection<String> brokers, DefaultMQAdminExt defaultMQAdminExt)'),
        ('    public static  void completeNoTargetBrokers(Map<String, TopicConfigAndQueueMapping> brokerConfigMap, DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 为同集群内尚未出现在 brokerConfigMap 中的 Broker 补全占位 Topic 映射配置。 */\n    public static  void completeNoTargetBrokers(Map<String, TopicConfigAndQueueMapping> brokerConfigMap, DefaultMQAdminExt defaultMQAdminExt)'),
        ('    public static void checkIfMasterAlive(Collection<String> brokers, DefaultMQAdminExt defaultMQAdminExt, ClientMetadata clientMetadata)',
         '    /** 校验各 Broker 的 Master 地址是否可解析，否则抛异常。 */\n    public static void checkIfMasterAlive(Collection<String> brokers, DefaultMQAdminExt defaultMQAdminExt, ClientMetadata clientMetadata)'),
        ('        //If some succeed, and others fail, it will cause inconsistent data',
         '        // 部分成功、部分失败会导致各 Broker 间数据不一致'),
        ('    public static void remappingStaticTopic(String topic, Set<String> brokersToMapIn, Set<String> brokersToMapOut, Map<String, TopicConfigAndQueueMapping> brokerConfigMap, int blockSeqSize, boolean force, DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 静态 Topic 重映射：分五步切换 Leader、禁止旧 Leader 写入、计算逻辑偏移并同步全集群。 */\n    public static void remappingStaticTopic(String topic, Set<String> brokersToMapIn, Set<String> brokersToMapOut, Map<String, TopicConfigAndQueueMapping> brokerConfigMap, int blockSeqSize, boolean force, DefaultMQAdminExt defaultMQAdminExt)'),
        ('        // now do the remapping\n        //Step1: let the new leader can be written without the logicOffset',
         '        // 开始重映射\n        // 步骤1：允许新 Leader 在无 logicOffset 时可写入'),
        ('        //Step2: forbid to write of old leader',
         '        // 步骤2：禁止旧 Leader 写入'),
        ('        //Step3: decide the logic offset',
         '        // 步骤3：确定逻辑偏移量'),
        ('                //TO DO check the max offset, will it return -1?',
         '                // TODO：校验 maxOffset 是否可能返回 -1'),
        ('                //fresh the new leader',
         '                // 刷新新 Leader 映射信息'),
        ('        //Step4: write to the new leader with logic offset',
         '        // 步骤4：带 logicOffset 写入新 Leader'),
        ('        //Step5: write the non-target brokers',
         '        // 步骤5：同步非目标 Broker 配置'),
        ('    public static Map<String, TopicConfigAndQueueMapping> examineTopicConfigAll(String topic, DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 遍历集群全部 Broker，拉取指定静态 Topic 的配置与队列映射。 */\n    public static Map<String, TopicConfigAndQueueMapping> examineTopicConfigAll(String topic, DefaultMQAdminExt defaultMQAdminExt)'),
        ('        //check all the brokers',
         '        // 检查集群内全部 Broker'),
        ('                //allow the config is null',
         '                // 允许配置为 null（Topic 尚未创建）'),
        ('    public static Map<String, TopicConfigAndQueueMapping> examineTopicConfigFromRoute(String topic, TopicRouteData topicRouteData, DefaultMQAdminExt defaultMQAdminExt)',
         '    /** 仅根据 Topic 路由中的 Broker 列表拉取各 Broker 上的 Topic 配置。 */\n    public static Map<String, TopicConfigAndQueueMapping> examineTopicConfigFromRoute(String topic, TopicRouteData topicRouteData, DefaultMQAdminExt defaultMQAdminExt)'),
        ('    public static void convertPhysicalTopicStats(String topic, Map<String, TopicConfigAndQueueMapping> brokerConfigMap, TopicStatsTable topicStatsTable)',
         '    /** 将物理队列的 Topic 统计（min/max offset）聚合转换为逻辑队列维度的统计。 */\n    public static void convertPhysicalTopicStats(String topic, Map<String, TopicConfigAndQueueMapping> brokerConfigMap, TopicStatsTable topicStatsTable)'),
        ('    public static ConsumeStats convertPhysicalConsumeStats(Map<String, TopicConfigAndQueueMapping> brokerConfigMap, ConsumeStats physicalResult)',
         '    /** 将物理队列的消费进度转换为静态 Topic 逻辑队列维度的 {@link ConsumeStats}。 */\n    public static ConsumeStats convertPhysicalConsumeStats(Map<String, TopicConfigAndQueueMapping> brokerConfigMap, ConsumeStats physicalResult)'),
        ('            long lastTimestamp = -1; //maybe need to be polished',
         '            long lastTimestamp = -1; // 时间戳选取逻辑后续可优化'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/admin/api/BrokerOperatorResult.java': [
        ('public class BrokerOperatorResult {',
         '/**\n * Broker 批量操作结果：分别记录成功与失败的 Broker 标识列表。\n */\npublic class BrokerOperatorResult {'),
        ('    private List<String> successList;',
         '    /** 操作成功的 Broker 列表。 */\n    private List<String> successList;'),
        ('    private List<String> failureList;',
         '    /** 操作失败的 Broker 列表。 */\n    private List<String> failureList;'),
        ('    public List<String> getSuccessList() {',
         '    /** 返回成功列表。 */\n    public List<String> getSuccessList() {'),
        ('    public void setSuccessList(List<String> successList) {',
         '    /** 设置成功列表。 */\n    public void setSuccessList(List<String> successList) {'),
        ('    public List<String> getFailureList() {',
         '    /** 返回失败列表。 */\n    public List<String> getFailureList() {'),
        ('    public void setFailureList(List<String> failureList) {',
         '    /** 设置失败列表。 */\n    public void setFailureList(List<String> failureList) {'),
        ('    @Override\n    public String toString() {',
         '    /** 返回包含 successList 与 failureList 的字符串表示。 */\n    @Override\n    public String toString() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/admin/api/MessageTrack.java': [
        ('public class MessageTrack {',
         '/**\n * 消息轨迹查询结果：描述某消费组对指定消息的投递/消费状态。\n */\npublic class MessageTrack {'),
        ('    private String consumerGroup;',
         '    /** 消费组名称。 */\n    private String consumerGroup;'),
        ('    private TrackType trackType;',
         '    /** 轨迹类型（已消费、过滤、未消费等）。 */\n    private TrackType trackType;'),
        ('    private String exceptionDesc;',
         '    /** 异常描述（轨迹异常时非空）。 */\n    private String exceptionDesc;'),
        ('    public String getConsumerGroup() {',
         '    /** 返回消费组名称。 */\n    public String getConsumerGroup() {'),
        ('    public void setConsumerGroup(String consumerGroup) {',
         '    /** 设置消费组名称。 */\n    public void setConsumerGroup(String consumerGroup) {'),
        ('    public TrackType getTrackType() {',
         '    /** 返回轨迹类型。 */\n    public TrackType getTrackType() {'),
        ('    public void setTrackType(TrackType trackType) {',
         '    /** 设置轨迹类型。 */\n    public void setTrackType(TrackType trackType) {'),
        ('    public String getExceptionDesc() {',
         '    /** 返回异常描述。 */\n    public String getExceptionDesc() {'),
        ('    public void setExceptionDesc(String exceptionDesc) {',
         '    /** 设置异常描述。 */\n    public void setExceptionDesc(String exceptionDesc) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/admin/api/TrackType.java': [
        ('public enum TrackType {',
         '/**\n * 消息轨迹类型枚举：标识消费组对消息的处理状态。\n */\npublic enum TrackType {'),
        ('    CONSUMED,',
         '    /** 消息已被正常消费。 */\n    CONSUMED,'),
        ('    CONSUMED_BUT_FILTERED,',
         '    /** 消息已投递但被消费端过滤丢弃。 */\n    CONSUMED_BUT_FILTERED,'),
        ('    PULL,',
         '    /** 消息处于 Pull 消费模式处理中。 */\n    PULL,'),
        ('    NOT_CONSUME_YET,',
         '    /** 消息尚未被消费。 */\n    NOT_CONSUME_YET,'),
        ('    NOT_ONLINE,',
         '    /** 消费端当前不在线。 */\n    NOT_ONLINE,'),
        ('    CONSUME_BROADCASTING,',
         '    /** 广播消费模式下已投递。 */\n    CONSUME_BROADCASTING,'),
        ('    UNKNOWN',
         '    /** 未知或无法判定的轨迹状态。 */\n    UNKNOWN'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/admin/common/AdminToolHandler.java': [
        ('public interface AdminToolHandler {',
         '/**\n * 管理工具命令处理器接口：封装可执行的管理操作并返回统一结果。\n */\npublic interface AdminToolHandler {'),
        ('    AdminToolResult doExecute() throws Exception;',
         '    /** 执行管理操作，成功或失败均封装为 {@link AdminToolResult}。 */\n    AdminToolResult doExecute() throws Exception;'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/admin/common/AdminToolResult.java': [
        ('public class AdminToolResult<T> {',
         '/**\n * 管理工具统一返回体：包含 success、code、errorMsg 与泛型 data 载荷。\n */\npublic class AdminToolResult<T> {'),
        ('    private boolean success;',
         '    /** 操作是否成功。 */\n    private boolean success;'),
        ('    private int code;',
         '    /** 结果码，对应 {@link AdminToolsResultCodeEnum}。 */\n    private int code;'),
        ('    private String errorMsg;',
         '    /** 错误或提示信息。 */\n    private String errorMsg;'),
        ('    private T data;',
         '    /** 业务数据载荷。 */\n    private T data;'),
        ('    public AdminToolResult(boolean success, int code, String errorMsg, T data) {',
         '    /** 构造完整结果对象。 */\n    public AdminToolResult(boolean success, int code, String errorMsg, T data) {'),
        ('    public static AdminToolResult success(Object data) {',
         '    /** 构造成功结果，code 为 {@link AdminToolsResultCodeEnum#SUCCESS}。 */\n    public static AdminToolResult success(Object data) {'),
        ('    public static AdminToolResult failure(AdminToolsResultCodeEnum errorCodeEnum, String errorMsg) {',
         '    /** 构造失败结果（无 data）。 */\n    public static AdminToolResult failure(AdminToolsResultCodeEnum errorCodeEnum, String errorMsg) {'),
        ('    public static AdminToolResult failure(AdminToolsResultCodeEnum errorCodeEnum, String errorMsg, Object data) {',
         '    /** 构造失败结果（附带部分 data）。 */\n    public static AdminToolResult failure(AdminToolsResultCodeEnum errorCodeEnum, String errorMsg, Object data) {'),
        ('    public boolean isSuccess() {',
         '    /** 返回是否成功。 */\n    public boolean isSuccess() {'),
        ('    public int getCode() {',
         '    /** 返回结果码。 */\n    public int getCode() {'),
        ('    public String getErrorMsg() {',
         '    /** 返回错误信息。 */\n    public String getErrorMsg() {'),
        ('    public T getData() {',
         '    /** 返回业务数据。 */\n    public T getData() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/admin/common/AdminToolsResultCodeEnum.java': [
        ('public enum AdminToolsResultCodeEnum {',
         '/**\n * 管理工具结果码枚举：区分成功与各类远程/业务错误。\n */\npublic enum AdminToolsResultCodeEnum {'),
        ('    /**\n     *\n     */\n    SUCCESS(200),',
         '    /** 操作成功。 */\n    SUCCESS(200),'),
        ('    REMOTING_ERROR(-1001),',
         '    /** Remoting 通信异常。 */\n    REMOTING_ERROR(-1001),'),
        ('    MQ_BROKER_ERROR(-1002),',
         '    /** Broker 端返回错误。 */\n    MQ_BROKER_ERROR(-1002),'),
        ('    MQ_CLIENT_ERROR(-1003),',
         '    /** 客户端异常。 */\n    MQ_CLIENT_ERROR(-1003),'),
        ('    INTERRUPT_ERROR(-1004),',
         '    /** 线程中断异常。 */\n    INTERRUPT_ERROR(-1004),'),
        ('    TOPIC_ROUTE_INFO_NOT_EXIST(-2001),',
         '    /** Topic 路由信息不存在。 */\n    TOPIC_ROUTE_INFO_NOT_EXIST(-2001),'),
        ('    CONSUMER_NOT_ONLINE(-2002),',
         '    /** 消费端不在线。 */\n    CONSUMER_NOT_ONLINE(-2002),'),
        ('    BROADCAST_CONSUMPTION(-2003);',
         '    /** 广播消费模式下无法精确追踪。 */\n    BROADCAST_CONSUMPTION(-2003);'),
        ('    private int code;',
         '    /** 数值结果码。 */\n    private int code;'),
        ('    AdminToolsResultCodeEnum(int code) {',
         '    /** 绑定数值码。 */\n    AdminToolsResultCodeEnum(int code) {'),
        ('    public int getCode() {',
         '    /** 返回数值结果码。 */\n    public int getCode() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/CommandUtil.java': [
        ('public class CommandUtil {',
         '/**\n * mqadmin 命令行工具辅助类：按集群/Broker 名解析 Master/Slave 地址。\n */\npublic class CommandUtil {'),
        ('    private static final String ERROR_MESSAGE = "Make sure the specified clusterName exists or the name server connected to is correct.";',
         '    /** 集群名不存在或 NameServer 连接异常时的提示信息。 */\n    private static final String ERROR_MESSAGE = "Make sure the specified clusterName exists or the name server connected to is correct.";'),
        ('    public static final String NO_MASTER_PLACEHOLDER = "NO_MASTER";',
         '    /** 无 Master 时的占位键。 */\n    public static final String NO_MASTER_PLACEHOLDER = "NO_MASTER";'),
        ('    public static Map<String/*master addr*/, List<String>/*slave addr*/> fetchMasterAndSlaveDistinguish(',
         '    /** 按集群名拉取 Master 地址到 Slave 地址列表的映射。 */\n    public static Map<String/*master addr*/, List<String>/*slave addr*/> fetchMasterAndSlaveDistinguish('),
        ('    public static Set<String> fetchMasterAddrByClusterName(final MQAdminExt adminExt, final String clusterName)',
         '    /** 返回指定集群内全部 Broker 的 Master 地址集合。 */\n    public static Set<String> fetchMasterAddrByClusterName(final MQAdminExt adminExt, final String clusterName)'),
        ('    public static Set<String> fetchMasterAndSlaveAddrByClusterName(final MQAdminExt adminExt, final String clusterName)',
         '    /** 返回指定集群内全部 Broker（Master + Slave）地址集合。 */\n    public static Set<String> fetchMasterAndSlaveAddrByClusterName(final MQAdminExt adminExt, final String clusterName)'),
        ('    public static String fetchMasterAddrByBrokerName(final MQAdminExt adminExt,\n        final String brokerName)',
         '    /** 根据 Broker 名解析 Master 地址；不存在则抛异常。 */\n    public static String fetchMasterAddrByBrokerName(final MQAdminExt adminExt,\n        final String brokerName)'),
        ('    public static Set<String> fetchMasterAndSlaveAddrByBrokerName(final MQAdminExt adminExt, final String brokerName)',
         '    /** 返回指定 Broker 的全部角色地址（Master + Slave）。 */\n    public static Set<String> fetchMasterAndSlaveAddrByBrokerName(final MQAdminExt adminExt, final String brokerName)'),
        ('    public static Set<String> fetchBrokerNameByClusterName(final MQAdminExt adminExt, final String clusterName)',
         '    /** 返回集群内全部 Broker 名称；集群不存在则抛异常。 */\n    public static Set<String> fetchBrokerNameByClusterName(final MQAdminExt adminExt, final String clusterName)'),
        ('    public static String fetchBrokerNameByAddr(final MQAdminExt adminExt, final String addr)',
         '    /** 根据 Broker 地址反查 Broker 名称。 */\n    public static String fetchBrokerNameByAddr(final MQAdminExt adminExt, final String addr)'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/MQAdminStartup.java': [
        ('public class MQAdminStartup {',
         '/**\n * mqadmin 命令行入口：注册全部 {@link SubCommand} 子命令并解析执行。\n */\npublic class MQAdminStartup {'),
        ('    protected static final List<SubCommand> SUB_COMMANDS = new ArrayList<>();',
         '    /** 已注册的全部子命令列表。 */\n    protected static final List<SubCommand> SUB_COMMANDS = new ArrayList<>();'),
        ('    private static final String ROCKETMQ_HOME = MixAll.ROCKETMQ_HOME_DIR;',
         '    /** RocketMQ 安装目录，用于加载 ACL 配置。 */\n    private static final String ROCKETMQ_HOME = MixAll.ROCKETMQ_HOME_DIR;'),
        ('    public static void main(String[] args) {',
         '    /** JVM 入口，委托 {@link #main0} 执行。 */\n    public static void main(String[] args) {'),
        ('    public static void main0(String[] args, RPCHook rpcHook) {',
         '    /** 解析命令行参数、设置 NameServer 地址并分发到对应子命令。 */\n    public static void main0(String[] args, RPCHook rpcHook) {'),
        ('        //PackageConflictDetect.detectFastjson();',
         '        // PackageConflictDetect.detectFastjson(); // 可选：检测 fastjson 版本冲突'),
        ('    public static void initCommand() {',
         '    /** 注册 mqadmin 支持的全部子命令（Topic/Broker/Consumer/ACL 等）。 */\n    public static void initCommand() {'),
        ('        //for producer',
         '        // 生产者相关命令'),
        ('        // lite topic related',
         '        // Lite Topic 相关命令'),
        ('    private static void printHelp() {',
         '    /** 无参数时打印常用子命令列表。 */\n    private static void printHelp() {'),
        ('    private static SubCommand findSubCommand(final String name) {',
         '    /** 按命令名或别名查找已注册的子命令。 */\n    private static SubCommand findSubCommand(final String name) {'),
        ('    private static String[] parseSubArgs(String[] args) {',
         '    /** 剥离首个子命令名，返回剩余参数数组。 */\n    private static String[] parseSubArgs(String[] args) {'),
        ('    public static void initCommand(SubCommand command) {',
         '    /** 将单个子命令注册到 SUB_COMMANDS 列表。 */\n    public static void initCommand(SubCommand command) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/SubCommand.java': [
        ('public interface SubCommand {',
         '/**\n * mqadmin 子命令接口：定义命令名、描述、CLI 选项构建与执行逻辑。\n */\npublic interface SubCommand {'),
        ('    String commandName();',
         '    /** 子命令名称（mqadmin 第一参数）。 */\n    String commandName();'),
        ('    default String commandAlias() {',
         '    /** 子命令别名，默认 null。 */\n    default String commandAlias() {'),
        ('    String commandDesc();',
         '    /** 子命令简短描述，用于 help 输出。 */\n    String commandDesc();'),
        ('    Options buildCommandlineOptions(final Options options);',
         '    /** 在公共选项基础上追加本子命令专属 CLI 选项。 */\n    Options buildCommandlineOptions(final Options options);'),
        ('    void execute(final CommandLine commandLine, final Options options, RPCHook rpcHook) throws SubCommandException;',
         '    /** 解析完成后执行子命令逻辑；失败抛 {@link SubCommandException}。 */\n    void execute(final CommandLine commandLine, final Options options, RPCHook rpcHook) throws SubCommandException;'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/SubCommandException.java': [
        ('public class SubCommandException extends Exception {',
         '/**\n * mqadmin 子命令执行异常：封装命令失败时的错误信息。\n */\npublic class SubCommandException extends Exception {'),
        ('    /**\n     * @param msg Message.\n     */\n    public SubCommandException(String msg) {',
         '    /**\n     * @param msg 错误消息。\n     */\n    public SubCommandException(String msg) {'),
        ('    public SubCommandException(String format, Object... args) {',
         '    /** 使用 {@link String#format} 构造格式化错误消息。 */\n    public SubCommandException(String format, Object... args) {'),
        ('    /**\n     * @param msg Message.\n     * @param cause Cause.\n     */\n    public SubCommandException(String msg, Throwable cause) {',
         '    /**\n     * @param msg 错误消息。\n     * @param cause 根因异常。\n     */\n    public SubCommandException(String msg, Throwable cause) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/CopyAclsSubCommand.java': [
        ('public class CopyAclsSubCommand implements SubCommand {',
         '/**\n * copyAcl 子命令：将源 Broker 上的 ACL 规则复制到目标 Broker。\n */\npublic class CopyAclsSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Copy acl to cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Copy acl to cluster.";'),
        ('        Option opt = new Option("f", "fromBroker", true, "the source broker that the acls copy from");',
         '        Option opt = new Option("f", "fromBroker", true, "ACL 复制来源 Broker");'),
        ('        opt = new Option("t", "toBroker", true, "the target broker that the acls copy to");',
         '        opt = new Option("t", "toBroker", true, "ACL 复制目标 Broker");'),
        ('        opt = new Option("s", "subjects", true, "the subject list of acl to copy.");',
         '        opt = new Option("s", "subjects", true, "待复制的 ACL subject 列表（逗号分隔，可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 读取源 Broker ACL，在目标 Broker 上创建或更新对应规则。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/CopyUsersSubCommand.java': [
        ('public class CopyUsersSubCommand implements SubCommand {',
         '/**\n * copyUser 子命令：将源 Broker 上的用户账户复制到目标 Broker。\n */\npublic class CopyUsersSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Copy user to cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Copy user to cluster.";'),
        ('        Option opt = new Option("f", "fromBroker", true, "the source broker that the users copy from");',
         '        Option opt = new Option("f", "fromBroker", true, "用户复制来源 Broker");'),
        ('        opt = new Option("t", "toBroker", true, "the target broker that the users copy to");',
         '        opt = new Option("t", "toBroker", true, "用户复制目标 Broker");'),
        ('        opt = new Option("u", "usernames", true, "the username list of user to copy.");',
         '        opt = new Option("u", "usernames", true, "待复制的用户名列表（逗号分隔，可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 读取源 Broker 用户，在目标 Broker 上创建或更新对应账户。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/CreateAclSubCommand.java': [
        ('public class CreateAclSubCommand implements SubCommand {',
         '/**\n * createAcl 子命令：在指定集群或 Broker 上创建 ACL 访问控制规则。\n */\npublic class CreateAclSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Create acl to cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Create acl to cluster.";'),
        ('        Option opt = new Option("c", "clusterName", true, "create acl to which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "create acl to which broker");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("s", "subject", true, "the subject of acl to create.");',
         '        opt = new Option("s", "subject", true, "ACL 主体（用户名或角色）");'),
        ('        opt = new Option("r", "resources", true, "the resources of acl to create");',
         '        opt = new Option("r", "resources", true, "ACL 资源列表（逗号分隔）");'),
        ('        opt = new Option("a", "actions", true, "the actions of acl to create");',
         '        opt = new Option("a", "actions", true, "ACL 操作权限列表（逗号分隔）");'),
        ('        opt = new Option("i", "sourceIp", true, "the sourceIps of acl to create");',
         '        opt = new Option("i", "sourceIp", true, "来源 IP 白名单（逗号分隔，可选）");'),
        ('        opt = new Option("d", "decision", true, "the decision of acl to create");',
         '        opt = new Option("d", "decision", true, "ACL 决策（Allow/Deny）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 上调用 createAcl。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/CreateUserSubCommand.java': [
        ('public class CreateUserSubCommand implements SubCommand {',
         '/**\n * createUser 子命令：在指定集群或 Broker 上创建用户账户。\n */\npublic class CreateUserSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Create user to cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Create user to cluster.";'),
        ('        Option opt = new Option("c", "clusterName", true, "create user to which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "create user to which broker");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("u", "username", true, "the username of user to create.");',
         '        opt = new Option("u", "username", true, "待创建的用户名");'),
        ('        opt = new Option("p", "password", true, "the password of user to create");',
         '        opt = new Option("p", "password", true, "用户密码");'),
        ('        opt = new Option("t", "userType", true, "the userType of user to create");',
         '        opt = new Option("t", "userType", true, "用户类型（可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 上调用 createUser。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
}
