"""Chinese annotation replacements for Redisson 4.7.0 wave-49a api [0:15]."""
from __future__ import annotations

_A = "redisson/src/main/java/org/redisson/api/"

W49A_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    'redisson/src/main/java/org/redisson/api/RRemoteService.java': [
        ('/**\n * Allows to execute object methods remotely between Redisson instances (Server side and Client side instances in terms of remote invocation).\n * <p>\n * <b>1. Server side instance (worker instance).</b> Register object with RRemoteService instance. \n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * <br>\n * // register remote service before any remote invocation<br>\n * remoteService.register(SomeServiceInterface.class, someServiceImpl);\n * </code>\n * <p>\n * <b>2. Client side instance.</b> Invokes method remotely.\n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * SomeServiceInterface service = remoteService.get(SomeServiceInterface.class);<br>\n * <br>\n * String result = service.doSomeStuff(1L, "secondParam", new AnyParam());\n * </code>\n * <p>\n * There are two timeouts during execution:\n * <p>\n * <b>Acknowledge (Ack) timeout.</b>Client side instance waits for acknowledge message from Server side instance.\n * <p>\n * If acknowledge has not been received by Client side instance then <code>RemoteServiceAckTimeoutException</code> will be thrown. \n * And next invocation attempt can be made.\n * <p>\n * If acknowledge has not been received Client side instance but Server side instance has received invocation message already. \n * In this case invocation will be skipped, due to ack timeout checking by Server side instance. \n * <p>\n * <b>Execution timeout.</b> Client side instance received acknowledge message. If it hasn\'t received any result or error \n * from server side during execution timeout then <code>RemoteServiceTimeoutException</code> will be thrown.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 支持 Redisson 实例之间远程调用对象方法（服务端 Worker 与客户端调用方）。\n * <p>\n * <b>1. 服务端（Worker 实例）。</b> 向 {@link RRemoteService} 注册实现对象。\n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * <br>\n * // register remote service before any remote invocation<br>\n * remoteService.register(SomeServiceInterface.class, someServiceImpl);\n * </code>\n * <p>\n * <b>2. 客户端。</b> 通过动态代理远程调用方法。\n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * SomeServiceInterface service = remoteService.get(SomeServiceInterface.class);<br>\n * <br>\n * String result = service.doSomeStuff(1L, "secondParam", new AnyParam());\n * </code>\n * <p>\n * 执行过程中涉及两类超时：\n * <p>\n * <b>确认（Ack）超时。</b> 客户端等待服务端确认消息。\n * <p>\n * 若客户端未收到确认则抛出 <code>RemoteServiceAckTimeoutException</code>，\n * 可重试下一次调用。\n * <p>\n * 若客户端未收到确认但服务端已收到调用消息，\n * 服务端会因 Ack 超时而跳过该次执行。\n * <p>\n * <b>执行超时。</b> 客户端已收到确认；若在执行超时内未收到结果或错误，\n * 则抛出 <code>RemoteServiceTimeoutException</code>。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Returns free workers amount available for invocations \n     * \n     * @param remoteInterface - remote service interface\n     * @return workers amount\n     */', '    /**\n     * 返回可用于处理远程调用的空闲 Worker 数量\n     * \n     * @param remoteInterface - remote service interface\n     * @return Worker 数量\n     */'),
        ('    /**\n     * Returns pending invocations amount for handling in free workers.\n     * \n     * @param remoteInterface - remote service interface\n     * @return invocations amount\n     */', '    /**\n     * 返回等待空闲 Worker 处理的待执行远程调用数量\n     * \n     * @param remoteInterface - remote service interface\n     * @return 待处理调用数量\n     */'),
        ('    /**\n     * Register remote service with single worker\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @param object - remote service object\n     */', '    /**\n     * 注册远程服务，使用单个 Worker 处理调用\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @param object - remote service object\n     */'),
        ('    /**\n     * Deregister all workers for remote service\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     */', '    /**\n     * 注销指定远程服务的全部 Worker\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     */'),
        ('    /**\n     * Get remote service object for remote invocations.\n     * <p>\n     * This method is a shortcut for\n     * <pre>\n     *     get(remoteInterface, RemoteInvocationOptions.defaults())\n     * </pre>\n     *\n     * @see RemoteInvocationOptions#defaults()\n     * @see #get(Class, RemoteInvocationOptions)\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @return remote service instance\n     */', '    /**\n     * 获取用于远程调用的动态代理对象。\n     * <p>\n     * This method is a shortcut for\n     * <pre>\n     *     get(remoteInterface, RemoteInvocationOptions.defaults())\n     * </pre>\n     *\n     * @see RemoteInvocationOptions#defaults()\n     * @see #get(Class, RemoteInvocationOptions)\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @return 远程服务代理实例\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RRingBuffer.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacity(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 基于环形缓冲区的队列；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacity(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ("    /**\n     * Sets capacity of the queue only if it wasn't set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */", '    /**\n     * 仅当容量尚未设置时设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    /**\n     * Returns remaining capacity of this queue\n     * \n     * @return remaining capacity\n     */', '    /**\n     * 返回队列剩余可用容量\n     * \n     * @return 剩余容量\n     */'),
        ("    /**\n     * Retrieves, but doesn't remove, the newest (most recently added) element of this buffer,\n     * or returns <code>null</code> if this buffer is empty.\n     *\n     * @return the newest element, or <code>null</code> if this buffer is empty\n     */", '    /**\n     * 查看但不移除缓冲区最新（最近添加）的元素；\n     * 缓冲区为空时返回 <code>null</code>。\n     *\n     * @return 最新元素；空缓冲区时为 <code>null</code>\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RRingBufferAsync.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacityAsync(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 环形缓冲区队列的异步 API；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacityAsync(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ("    /**\n     * Sets capacity of the queue only if it wasn't set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */", '    /**\n     * 仅当容量尚未设置时异步设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    RFuture<V> peekLastAsync();', '    /** 异步查看缓冲区最新元素（不移除）。 */\n    RFuture<V> peekLastAsync();'),
    ],
    'redisson/src/main/java/org/redisson/api/RRingBufferReactive.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacity(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 环形缓冲区队列的 Reactor 响应式 API；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacity(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ('    /**\n     * Sets queue capacity only if it is not set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */', '    /**\n     * 仅当容量尚未设置时设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    Mono<V> peekLast();', '    /** 响应式查看缓冲区最新元素（不移除）。 */\n    Mono<V> peekLast();'),
    ],
    'redisson/src/main/java/org/redisson/api/RRingBufferRx.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacity(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 环形缓冲区队列的 RxJava3 API；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacity(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ('    /**\n     * Sets queue capacity only if it is not set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */', '    /**\n     * 仅当容量尚未设置时设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    Maybe<V> peekLast();', '    /** RxJava 查看缓冲区最新元素（不移除）。 */\n    Maybe<V> peekLast();'),
    ],
    'redisson/src/main/java/org/redisson/api/RScheduledExecutorService.java': [
        ('/**\n * Redis based implementation of {@link java.util.concurrent.ScheduledExecutorService}\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 基于 Redis 的分布式 {@link java.util.concurrent.ScheduledExecutorService} 实现。\n * <p>任务序列化后存入 Redis，由 Worker 节点按调度时间执行；\n * 支持延迟、固定速率、固定延迟及 Cron 表达式。\n * \n * @author Nikita Koksharov\n *\n */'),
        ("    /**\n     * Synchronously schedules a Runnable task for execution asynchronously\n     * after the given <code>delay</code>. Returns a RScheduledFuture representing that task.\n     * The Future's {@code get} method will return the given result upon successful completion.\n     *\n     * @param command the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return a ScheduledFuture representing pending completion of\n     *         the task and whose {@code get()} method will return\n     *         {@code null} upon completion\n     */", '    /**\n     * 在指定延迟后调度 {@link Runnable} 任务执行，返回 {@link RScheduledFuture}。\n     *\n     * @param command the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return 表示任务待完成状态的 {@link RScheduledFuture}，\n     *         完成后 {@code get()} 返回 {@code null}\n     */'),
        ('    /**\n     * Synchronously schedules a Runnable task for execution asynchronously\n     * after the given <code>initialDelay</code>, and subsequently with the given\n     * <code>period</code>.\n     * Subsequent executions are stopped if any execution of the task throws an exception.\n     * Otherwise, task could be terminated via cancellation or\n     * termination of the executor.\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return a ScheduledFuture representing pending completion of\n     *         the task, and whose {@code get()} method will throw an\n     *         exception upon cancellation\n     */', '    /**\n     * 以固定速率周期性调度 {@link Runnable} 任务（首次延迟 {@code initialDelay}，\n     * 之后每隔 {@code period} 执行一次）。\n     * 任一次执行抛异常则停止后续调度；也可通过取消或关闭执行器终止。\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return 表示任务待完成状态的 {@link RScheduledFuture}\n     */'),
        ('    /**\n     * Synchronously schedules a Runnable task for execution asynchronously\n     * cron schedule object.\n     * Subsequent executions are stopped if any execution of the task throws an exception.\n     * Otherwise, task could be terminated via cancellation or\n     * termination of the executor.\n     *\n     * @param task the task to execute\n     * @param cronSchedule cron schedule object\n     * @return future object\n     */', '    /**\n     * 按 Cron 表达式调度 {@link Runnable} 任务。\n     * 任一次执行抛异常则停止后续调度；也可通过取消或关闭执行器终止。\n     *\n     * @param task the task to execute\n     * @param cronSchedule cron schedule object\n     * @return {@link RScheduledFuture} 对象\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RScheduledExecutorServiceAsync.java': [
        ('/**\n * Redis based implementation of {@link java.util.concurrent.ScheduledExecutorService}\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 分布式调度执行器的异步 API。\n * <p>各方法返回 {@link RScheduledFuture}，支持监听器与异步回调。\n * \n * @author Nikita Koksharov\n *\n */'),
        ("    /**\n     * Schedules a Runnable task for execution asynchronously\n     * after the given <code>delay</code>. Returns a RScheduledFuture representing that task.\n     * The Future's {@code get} method will return the given result upon successful completion.\n     *\n     * @param task the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return RScheduledFuture with listeners support\n     */", '    /**\n     * 在指定延迟后异步调度 {@link Runnable} 任务。\n     *\n     * @param task the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return 支持监听器的 {@link RScheduledFuture}\n     */'),
        ('    /**\n     * Schedules a Runnable task for execution asynchronously\n     * after the given <code>initialDelay</code>, and subsequently with the given\n     * <code>period</code>.\n     * Subsequent executions are stopped if any execution of the task throws an exception.\n     * Otherwise, task could be terminated via cancellation or\n     * termination of the executor.\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return RScheduledFuture with listeners support\n     */', '    /**\n     * 以固定速率异步周期性调度 {@link Runnable} 任务。\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return 支持监听器的 {@link RScheduledFuture}\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RScheduledFuture.java': [
        ('/**\n * \n * @author Nikita Koksharov\n *\n * @param <V> value\n */', '/**\n * 分布式调度任务的 Future 接口。\n * <p>扩展 {@link RExecutorFuture} 与 {@link java.util.concurrent.ScheduledFuture}，\n * 支持取消、延迟查询及 Redisson 任务监听器。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 任务返回值类型\n */'),
    ],
    'redisson/src/main/java/org/redisson/api/RScript.java': [
        ('/**\n * API for Redis Lua scripts execution.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本执行 API。\n * <p>支持 {@code EVAL}/{@code EVALSHA}、脚本加载与缓存管理；\n * 集群模式下可按 {@link Mode} 路由到主/从节点。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('        /**\n         * Execute script as read operation\n         */', '        /**\n         * 以只读模式执行脚本（路由到从节点）\n         */'),
        ('        /**\n         * Execute script as write operation\n         */', '        /**\n         * 以读写模式执行脚本（路由到主节点）\n         */'),
        ('    /**\n     * Executes Lua script stored in Redis scripts cache by SHA-1 digest\n     * \n     * @param <R> - type of result\n     * @param mode - execution mode\n     * @param shaDigest - SHA-1 digest\n     * @param returnType - return type\n     * @param keys - keys available through KEYS param in script\n     * @param values - values available through ARGV param in script\n     * @return result object\n     */', '    /**\n     * 通过 SHA-1 摘要执行 Redis 脚本缓存中的 Lua 脚本\n     * \n     * @param <R> - type of result\n     * @param mode - execution mode\n     * @param shaDigest - SHA-1 digest\n     * @param returnType - return type\n     * @param keys - keys available through KEYS param in script\n     * @param values - values available through ARGV param in script\n     * @return 脚本执行结果\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * 将 Lua 脚本加载到 Redis 脚本缓存并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     */', '    /**\n     * 清空 Redis Lua 脚本缓存\n     * \n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RScriptAsync.java': [
        ('/**\n * Async interface for Redis Script feature\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本异步 API。\n * <p>各方法返回 {@link RFuture}，适用于 Netty 异步回调模型。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     * @return void\n     */', '    /**\n     * 异步清空 Redis Lua 脚本缓存\n     * \n     * @return void\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * 异步加载 Lua 脚本到 Redis 缓存并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
        ('    /**\n     * Kills currently executed Lua script\n     * \n     * @return void\n     */', '    /**\n     * 异步终止当前正在执行的 Lua 脚本\n     * \n     * @return void\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RScriptReactive.java': [
        ('/**\n * Reactive interface for Redis Script feature\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本的 Reactor 响应式 API。\n * <p>各方法返回 {@link Mono}，与 Project Reactor 集成。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     * @return void\n     */', '    /**\n     * 响应式清空 Redis Lua 脚本缓存\n     * \n     * @return void\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * 响应式加载 Lua 脚本并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RScriptRx.java': [
        ('/**\n * RxJava2 interface for Redis Script feature\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本的 RxJava3 API。\n * <p>各方法返回 {@link Maybe}、{@link Single}、{@link Completable} 等类型。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     * @return void\n     */', '    /**\n     * RxJava 清空 Redis Lua 脚本缓存\n     * \n     * @return void\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * RxJava 加载 Lua 脚本并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RSearch.java': [
        ('/**\n * API for RediSearch module\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * RediSearch 模块同步 API。\n * <p>封装索引创建、全文检索、聚合、混合向量搜索、\n * 拼写检查与同义词等 {@code FT.*} 命令。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Creates an index.\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndex("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */', '    /**\n     * 创建 RediSearch 索引。\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndex("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */'),
        ('    /**\n     * Executes search over defined index using defined query.\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return search result\n     */', '    /**\n     * 在指定索引上执行全文检索。\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return 检索结果\n     */'),
        ('    /**\n     * Performs hybrid search combining text search and vector similarity\n     * using the FT.HYBRID command.\n     * <p>\n     * Requires Redis Stack 8.4.0 or higher.\n     * <p>\n     * Usage example:\n     * <pre>\n     * SearchResult result = search.hybridSearch("myIndex",\n     *     HybridQueryArgs.query("laptop")\n     *         .vectorSimilarity("@embedding", "$vec")\n     *         .nearestNeighbors(10)\n     *         .params(Map.of("vec", vectorBytes))\n     *         .limit(0, 10));\n     * </pre>\n     *\n     * @param indexName the name of the index\n     * @param args hybrid query arguments\n     * @return search result\n     */', '    /**\n     * 通过 {@code FT.HYBRID} 执行文本检索与向量相似度混合搜索。\n     * <p>\n     * Requires Redis Stack 8.4.0 or higher.\n     * <p>\n     * Usage example:\n     * <pre>\n     * SearchResult result = search.hybridSearch("myIndex",\n     *     HybridQueryArgs.query("laptop")\n     *         .vectorSimilarity("@embedding", "$vec")\n     *         .nearestNeighbors(10)\n     *         .params(Map.of("vec", vectorBytes))\n     *         .limit(0, 10));\n     * </pre>\n     *\n     * @param indexName the name of the index\n     * @param args hybrid query arguments\n     * @return 混合检索结果\n     */'),
        ('    /**\n     * Deletes index by name\n     *\n     * @param indexName index name\n     */', '    /**\n     * 按名称删除索引（不删除关联文档）\n     *\n     * @param indexName index name\n     */'),
        ('    /**\n     * Returns list of all created indexes\n     *\n     * @return list of indexes\n     */', '    /**\n     * 返回所有已创建索引的名称列表\n     *\n     * @return 索引名称列表\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RSearchAsync.java': [
        ('/**\n * Asynchronous API for RediSearch module\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * RediSearch 模块异步 API。\n * <p>各方法返回 {@link RFuture}，适用于 Netty 异步回调模型。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Creates an index.\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndexAsync("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */', '    /**\n     * 异步创建 RediSearch 索引。\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndexAsync("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */'),
        ('    /**\n     * Executes search over defined index using defined query.\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.searchAsync("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return search result\n     */', '    /**\n     * 异步在指定索引上执行全文检索。\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.searchAsync("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return 检索结果\n     */'),
        ('    /**\n     * Returns list of all created indexes\n     *\n     * @return list of indexes\n     */', '    /**\n     * 异步返回所有已创建索引的名称列表\n     *\n     * @return 索引名称列表\n     */'),
    ],
    'redisson/src/main/java/org/redisson/api/RSearchReactive.java': [
        ('/**\n * Reactive API for RediSearch module\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * RediSearch 模块 Reactor 响应式 API。\n * <p>各方法返回 {@link Mono}，与 Project Reactor 集成。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Creates an index.\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.create("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */', '    /**\n     * 响应式创建 RediSearch 索引。\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.create("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */'),
        ('    /**\n     * Executes search over defined index using defined query.\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return search result\n     */', '    /**\n     * 响应式在指定索引上执行全文检索。\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return 检索结果\n     */'),
        ('    /**\n     * Returns list of all created indexes\n     *\n     * @return list of indexes\n     */', '    /**\n     * 响应式返回所有已创建索引的名称列表\n     *\n     * @return 索引名称列表\n     */'),
    ],
    'RRemoteService.java': [
        ('/**\n * Allows to execute object methods remotely between Redisson instances (Server side and Client side instances in terms of remote invocation).\n * <p>\n * <b>1. Server side instance (worker instance).</b> Register object with RRemoteService instance. \n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * <br>\n * // register remote service before any remote invocation<br>\n * remoteService.register(SomeServiceInterface.class, someServiceImpl);\n * </code>\n * <p>\n * <b>2. Client side instance.</b> Invokes method remotely.\n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * SomeServiceInterface service = remoteService.get(SomeServiceInterface.class);<br>\n * <br>\n * String result = service.doSomeStuff(1L, "secondParam", new AnyParam());\n * </code>\n * <p>\n * There are two timeouts during execution:\n * <p>\n * <b>Acknowledge (Ack) timeout.</b>Client side instance waits for acknowledge message from Server side instance.\n * <p>\n * If acknowledge has not been received by Client side instance then <code>RemoteServiceAckTimeoutException</code> will be thrown. \n * And next invocation attempt can be made.\n * <p>\n * If acknowledge has not been received Client side instance but Server side instance has received invocation message already. \n * In this case invocation will be skipped, due to ack timeout checking by Server side instance. \n * <p>\n * <b>Execution timeout.</b> Client side instance received acknowledge message. If it hasn\'t received any result or error \n * from server side during execution timeout then <code>RemoteServiceTimeoutException</code> will be thrown.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 支持 Redisson 实例之间远程调用对象方法（服务端 Worker 与客户端调用方）。\n * <p>\n * <b>1. 服务端（Worker 实例）。</b> 向 {@link RRemoteService} 注册实现对象。\n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * <br>\n * // register remote service before any remote invocation<br>\n * remoteService.register(SomeServiceInterface.class, someServiceImpl);\n * </code>\n * <p>\n * <b>2. 客户端。</b> 通过动态代理远程调用方法。\n * <p>\n * <code>\n * RRemoteService remoteService = redisson.getRemoteService();<br>\n * SomeServiceInterface service = remoteService.get(SomeServiceInterface.class);<br>\n * <br>\n * String result = service.doSomeStuff(1L, "secondParam", new AnyParam());\n * </code>\n * <p>\n * 执行过程中涉及两类超时：\n * <p>\n * <b>确认（Ack）超时。</b> 客户端等待服务端确认消息。\n * <p>\n * 若客户端未收到确认则抛出 <code>RemoteServiceAckTimeoutException</code>，\n * 可重试下一次调用。\n * <p>\n * 若客户端未收到确认但服务端已收到调用消息，\n * 服务端会因 Ack 超时而跳过该次执行。\n * <p>\n * <b>执行超时。</b> 客户端已收到确认；若在执行超时内未收到结果或错误，\n * 则抛出 <code>RemoteServiceTimeoutException</code>。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Returns free workers amount available for invocations \n     * \n     * @param remoteInterface - remote service interface\n     * @return workers amount\n     */', '    /**\n     * 返回可用于处理远程调用的空闲 Worker 数量\n     * \n     * @param remoteInterface - remote service interface\n     * @return Worker 数量\n     */'),
        ('    /**\n     * Returns pending invocations amount for handling in free workers.\n     * \n     * @param remoteInterface - remote service interface\n     * @return invocations amount\n     */', '    /**\n     * 返回等待空闲 Worker 处理的待执行远程调用数量\n     * \n     * @param remoteInterface - remote service interface\n     * @return 待处理调用数量\n     */'),
        ('    /**\n     * Register remote service with single worker\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @param object - remote service object\n     */', '    /**\n     * 注册远程服务，使用单个 Worker 处理调用\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @param object - remote service object\n     */'),
        ('    /**\n     * Deregister all workers for remote service\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     */', '    /**\n     * 注销指定远程服务的全部 Worker\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     */'),
        ('    /**\n     * Get remote service object for remote invocations.\n     * <p>\n     * This method is a shortcut for\n     * <pre>\n     *     get(remoteInterface, RemoteInvocationOptions.defaults())\n     * </pre>\n     *\n     * @see RemoteInvocationOptions#defaults()\n     * @see #get(Class, RemoteInvocationOptions)\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @return remote service instance\n     */', '    /**\n     * 获取用于远程调用的动态代理对象。\n     * <p>\n     * This method is a shortcut for\n     * <pre>\n     *     get(remoteInterface, RemoteInvocationOptions.defaults())\n     * </pre>\n     *\n     * @see RemoteInvocationOptions#defaults()\n     * @see #get(Class, RemoteInvocationOptions)\n     *\n     * @param <T> type of remote service\n     * @param remoteInterface - remote service interface\n     * @return 远程服务代理实例\n     */'),
    ],
    'RRingBuffer.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacity(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 基于环形缓冲区的队列；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacity(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ("    /**\n     * Sets capacity of the queue only if it wasn't set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */", '    /**\n     * 仅当容量尚未设置时设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    /**\n     * Returns remaining capacity of this queue\n     * \n     * @return remaining capacity\n     */', '    /**\n     * 返回队列剩余可用容量\n     * \n     * @return 剩余容量\n     */'),
        ("    /**\n     * Retrieves, but doesn't remove, the newest (most recently added) element of this buffer,\n     * or returns <code>null</code> if this buffer is empty.\n     *\n     * @return the newest element, or <code>null</code> if this buffer is empty\n     */", '    /**\n     * 查看但不移除缓冲区最新（最近添加）的元素；\n     * 缓冲区为空时返回 <code>null</code>。\n     *\n     * @return 最新元素；空缓冲区时为 <code>null</code>\n     */'),
    ],
    'RRingBufferAsync.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacityAsync(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 环形缓冲区队列的异步 API；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacityAsync(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ("    /**\n     * Sets capacity of the queue only if it wasn't set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */", '    /**\n     * 仅当容量尚未设置时异步设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    RFuture<V> peekLastAsync();', '    /** 异步查看缓冲区最新元素（不移除）。 */\n    RFuture<V> peekLastAsync();'),
    ],
    'RRingBufferReactive.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacity(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 环形缓冲区队列的 Reactor 响应式 API；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacity(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ('    /**\n     * Sets queue capacity only if it is not set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */', '    /**\n     * 仅当容量尚未设置时设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    Mono<V> peekLast();', '    /** 响应式查看缓冲区最新元素（不移除）。 */\n    Mono<V> peekLast();'),
    ],
    'RRingBufferRx.java': [
        ('/**\n * RingBuffer based queue evicts elements from the head if queue capacity became full.\n * <p>\n * The head element removed if new element added and queue is full. \n * <p>\n * Must be initialized with capacity size {@link #trySetCapacity(int)} before usage.\n * \n * @author Nikita Koksharov\n *\n * @param <V> value type\n */', '/**\n * 环形缓冲区队列的 RxJava3 API；容量满时从队首淘汰最旧元素。\n * <p>\n * 队列已满时再添加元素会移除队首元素。\n * <p>\n * 使用前须先通过 {@link #trySetCapacity(int)} 初始化容量。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 元素类型\n */'),
        ('    /**\n     * Sets queue capacity only if it is not set before.\n     *\n     * @param capacity - queue capacity\n     * @return <code>true</code> if capacity set successfully\n     *         <code>false</code> if capacity already set\n     */', '    /**\n     * 仅当容量尚未设置时设置队列容量。\n     *\n     * @param capacity - queue capacity\n     * @return 设置成功则为 <code>true</code>，容量已存在则为 <code>false</code>\n     */'),
        ('    Maybe<V> peekLast();', '    /** RxJava 查看缓冲区最新元素（不移除）。 */\n    Maybe<V> peekLast();'),
    ],
    'RScheduledExecutorService.java': [
        ('/**\n * Redis based implementation of {@link java.util.concurrent.ScheduledExecutorService}\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 基于 Redis 的分布式 {@link java.util.concurrent.ScheduledExecutorService} 实现。\n * <p>任务序列化后存入 Redis，由 Worker 节点按调度时间执行；\n * 支持延迟、固定速率、固定延迟及 Cron 表达式。\n * \n * @author Nikita Koksharov\n *\n */'),
        ("    /**\n     * Synchronously schedules a Runnable task for execution asynchronously\n     * after the given <code>delay</code>. Returns a RScheduledFuture representing that task.\n     * The Future's {@code get} method will return the given result upon successful completion.\n     *\n     * @param command the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return a ScheduledFuture representing pending completion of\n     *         the task and whose {@code get()} method will return\n     *         {@code null} upon completion\n     */", '    /**\n     * 在指定延迟后调度 {@link Runnable} 任务执行，返回 {@link RScheduledFuture}。\n     *\n     * @param command the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return 表示任务待完成状态的 {@link RScheduledFuture}，\n     *         完成后 {@code get()} 返回 {@code null}\n     */'),
        ('    /**\n     * Synchronously schedules a Runnable task for execution asynchronously\n     * after the given <code>initialDelay</code>, and subsequently with the given\n     * <code>period</code>.\n     * Subsequent executions are stopped if any execution of the task throws an exception.\n     * Otherwise, task could be terminated via cancellation or\n     * termination of the executor.\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return a ScheduledFuture representing pending completion of\n     *         the task, and whose {@code get()} method will throw an\n     *         exception upon cancellation\n     */', '    /**\n     * 以固定速率周期性调度 {@link Runnable} 任务（首次延迟 {@code initialDelay}，\n     * 之后每隔 {@code period} 执行一次）。\n     * 任一次执行抛异常则停止后续调度；也可通过取消或关闭执行器终止。\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return 表示任务待完成状态的 {@link RScheduledFuture}\n     */'),
        ('    /**\n     * Synchronously schedules a Runnable task for execution asynchronously\n     * cron schedule object.\n     * Subsequent executions are stopped if any execution of the task throws an exception.\n     * Otherwise, task could be terminated via cancellation or\n     * termination of the executor.\n     *\n     * @param task the task to execute\n     * @param cronSchedule cron schedule object\n     * @return future object\n     */', '    /**\n     * 按 Cron 表达式调度 {@link Runnable} 任务。\n     * 任一次执行抛异常则停止后续调度；也可通过取消或关闭执行器终止。\n     *\n     * @param task the task to execute\n     * @param cronSchedule cron schedule object\n     * @return {@link RScheduledFuture} 对象\n     */'),
    ],
    'RScheduledExecutorServiceAsync.java': [
        ('/**\n * Redis based implementation of {@link java.util.concurrent.ScheduledExecutorService}\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * 分布式调度执行器的异步 API。\n * <p>各方法返回 {@link RScheduledFuture}，支持监听器与异步回调。\n * \n * @author Nikita Koksharov\n *\n */'),
        ("    /**\n     * Schedules a Runnable task for execution asynchronously\n     * after the given <code>delay</code>. Returns a RScheduledFuture representing that task.\n     * The Future's {@code get} method will return the given result upon successful completion.\n     *\n     * @param task the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return RScheduledFuture with listeners support\n     */", '    /**\n     * 在指定延迟后异步调度 {@link Runnable} 任务。\n     *\n     * @param task the task to execute\n     * @param delay the time from now to delay execution\n     * @param unit the time unit of the delay parameter\n     * @return 支持监听器的 {@link RScheduledFuture}\n     */'),
        ('    /**\n     * Schedules a Runnable task for execution asynchronously\n     * after the given <code>initialDelay</code>, and subsequently with the given\n     * <code>period</code>.\n     * Subsequent executions are stopped if any execution of the task throws an exception.\n     * Otherwise, task could be terminated via cancellation or\n     * termination of the executor.\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return RScheduledFuture with listeners support\n     */', '    /**\n     * 以固定速率异步周期性调度 {@link Runnable} 任务。\n     *\n     * @param task the task to execute\n     * @param initialDelay the time to delay first execution\n     * @param period the period between successive executions\n     * @param unit the time unit of the initialDelay and period parameters\n     * @return 支持监听器的 {@link RScheduledFuture}\n     */'),
    ],
    'RScheduledFuture.java': [
        ('/**\n * \n * @author Nikita Koksharov\n *\n * @param <V> value\n */', '/**\n * 分布式调度任务的 Future 接口。\n * <p>扩展 {@link RExecutorFuture} 与 {@link java.util.concurrent.ScheduledFuture}，\n * 支持取消、延迟查询及 Redisson 任务监听器。\n * \n * @author Nikita Koksharov\n *\n * @param <V> 任务返回值类型\n */'),
    ],
    'RScript.java': [
        ('/**\n * API for Redis Lua scripts execution.\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本执行 API。\n * <p>支持 {@code EVAL}/{@code EVALSHA}、脚本加载与缓存管理；\n * 集群模式下可按 {@link Mode} 路由到主/从节点。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('        /**\n         * Execute script as read operation\n         */', '        /**\n         * 以只读模式执行脚本（路由到从节点）\n         */'),
        ('        /**\n         * Execute script as write operation\n         */', '        /**\n         * 以读写模式执行脚本（路由到主节点）\n         */'),
        ('    /**\n     * Executes Lua script stored in Redis scripts cache by SHA-1 digest\n     * \n     * @param <R> - type of result\n     * @param mode - execution mode\n     * @param shaDigest - SHA-1 digest\n     * @param returnType - return type\n     * @param keys - keys available through KEYS param in script\n     * @param values - values available through ARGV param in script\n     * @return result object\n     */', '    /**\n     * 通过 SHA-1 摘要执行 Redis 脚本缓存中的 Lua 脚本\n     * \n     * @param <R> - type of result\n     * @param mode - execution mode\n     * @param shaDigest - SHA-1 digest\n     * @param returnType - return type\n     * @param keys - keys available through KEYS param in script\n     * @param values - values available through ARGV param in script\n     * @return 脚本执行结果\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * 将 Lua 脚本加载到 Redis 脚本缓存并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     */', '    /**\n     * 清空 Redis Lua 脚本缓存\n     * \n     */'),
    ],
    'RScriptAsync.java': [
        ('/**\n * Async interface for Redis Script feature\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本异步 API。\n * <p>各方法返回 {@link RFuture}，适用于 Netty 异步回调模型。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     * @return void\n     */', '    /**\n     * 异步清空 Redis Lua 脚本缓存\n     * \n     * @return void\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * 异步加载 Lua 脚本到 Redis 缓存并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
        ('    /**\n     * Kills currently executed Lua script\n     * \n     * @return void\n     */', '    /**\n     * 异步终止当前正在执行的 Lua 脚本\n     * \n     * @return void\n     */'),
    ],
    'RScriptReactive.java': [
        ('/**\n * Reactive interface for Redis Script feature\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本的 Reactor 响应式 API。\n * <p>各方法返回 {@link Mono}，与 Project Reactor 集成。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     * @return void\n     */', '    /**\n     * 响应式清空 Redis Lua 脚本缓存\n     * \n     * @return void\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * 响应式加载 Lua 脚本并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
    ],
    'RScriptRx.java': [
        ('/**\n * RxJava2 interface for Redis Script feature\n * \n * @author Nikita Koksharov\n *\n */', '/**\n * Redis Lua 脚本的 RxJava3 API。\n * <p>各方法返回 {@link Maybe}、{@link Single}、{@link Completable} 等类型。\n * \n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Flushes Lua script cache.\n     * \n     * @return void\n     */', '    /**\n     * RxJava 清空 Redis Lua 脚本缓存\n     * \n     * @return void\n     */'),
        ('    /**\n     * Loads Lua script into Redis scripts cache and returns its SHA-1 digest\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 digest\n     */', '    /**\n     * RxJava 加载 Lua 脚本并返回 SHA-1 摘要\n     * \n     * @param luaScript - lua script\n     * @return SHA-1 摘要\n     */'),
    ],
    'RSearch.java': [
        ('/**\n * API for RediSearch module\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * RediSearch 模块同步 API。\n * <p>封装索引创建、全文检索、聚合、混合向量搜索、\n * 拼写检查与同义词等 {@code FT.*} 命令。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Creates an index.\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndex("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */', '    /**\n     * 创建 RediSearch 索引。\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndex("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */'),
        ('    /**\n     * Executes search over defined index using defined query.\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return search result\n     */', '    /**\n     * 在指定索引上执行全文检索。\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return 检索结果\n     */'),
        ('    /**\n     * Performs hybrid search combining text search and vector similarity\n     * using the FT.HYBRID command.\n     * <p>\n     * Requires Redis Stack 8.4.0 or higher.\n     * <p>\n     * Usage example:\n     * <pre>\n     * SearchResult result = search.hybridSearch("myIndex",\n     *     HybridQueryArgs.query("laptop")\n     *         .vectorSimilarity("@embedding", "$vec")\n     *         .nearestNeighbors(10)\n     *         .params(Map.of("vec", vectorBytes))\n     *         .limit(0, 10));\n     * </pre>\n     *\n     * @param indexName the name of the index\n     * @param args hybrid query arguments\n     * @return search result\n     */', '    /**\n     * 通过 {@code FT.HYBRID} 执行文本检索与向量相似度混合搜索。\n     * <p>\n     * Requires Redis Stack 8.4.0 or higher.\n     * <p>\n     * Usage example:\n     * <pre>\n     * SearchResult result = search.hybridSearch("myIndex",\n     *     HybridQueryArgs.query("laptop")\n     *         .vectorSimilarity("@embedding", "$vec")\n     *         .nearestNeighbors(10)\n     *         .params(Map.of("vec", vectorBytes))\n     *         .limit(0, 10));\n     * </pre>\n     *\n     * @param indexName the name of the index\n     * @param args hybrid query arguments\n     * @return 混合检索结果\n     */'),
        ('    /**\n     * Deletes index by name\n     *\n     * @param indexName index name\n     */', '    /**\n     * 按名称删除索引（不删除关联文档）\n     *\n     * @param indexName index name\n     */'),
        ('    /**\n     * Returns list of all created indexes\n     *\n     * @return list of indexes\n     */', '    /**\n     * 返回所有已创建索引的名称列表\n     *\n     * @return 索引名称列表\n     */'),
    ],
    'RSearchAsync.java': [
        ('/**\n * Asynchronous API for RediSearch module\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * RediSearch 模块异步 API。\n * <p>各方法返回 {@link RFuture}，适用于 Netty 异步回调模型。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Creates an index.\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndexAsync("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */', '    /**\n     * 异步创建 RediSearch 索引。\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.createIndexAsync("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */'),
        ('    /**\n     * Executes search over defined index using defined query.\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.searchAsync("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return search result\n     */', '    /**\n     * 异步在指定索引上执行全文检索。\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.searchAsync("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return 检索结果\n     */'),
        ('    /**\n     * Returns list of all created indexes\n     *\n     * @return list of indexes\n     */', '    /**\n     * 异步返回所有已创建索引的名称列表\n     *\n     * @return 索引名称列表\n     */'),
    ],
    'RSearchReactive.java': [
        ('/**\n * Reactive API for RediSearch module\n *\n * @author Nikita Koksharov\n *\n */', '/**\n * RediSearch 模块 Reactor 响应式 API。\n * <p>各方法返回 {@link Mono}，与 Project Reactor 集成。\n *\n * @author Nikita Koksharov\n *\n */'),
        ('    /**\n     * Creates an index.\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.create("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */', '    /**\n     * 响应式创建 RediSearch 索引。\n     * <p>\n     * Code example:\n     * <pre>\n     *             search.create("idx", IndexOptions.defaults()\n     *                                     .on(IndexType.HASH)\n     *                                     .prefix(Arrays.asList("doc:")),\n     *                                     FieldIndex.text("t1"),\n     *                                     FieldIndex.tag("t2").withSuffixTrie());\n     * </pre>\n     *\n     * @param indexName index name\n     * @param options index options\n     * @param fields fields\n     */'),
        ('    /**\n     * Executes search over defined index using defined query.\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return search result\n     */', '    /**\n     * 响应式在指定索引上执行全文检索。\n     * <p>\n     * Code example:\n     * <pre>\n     * SearchResult r = s.search("idx", "*", QueryOptions.defaults()\n     *                                                   .returnAttributes(new ReturnAttribute("t1"), new ReturnAttribute("t2")));\n     * </pre>\n     *\n     * @param indexName index name\n     * @param query query value\n     * @param options query options\n     * @return 检索结果\n     */'),
        ('    /**\n     * Returns list of all created indexes\n     *\n     * @return list of indexes\n     */', '    /**\n     * 响应式返回所有已创建索引的名称列表\n     *\n     * @return 索引名称列表\n     */'),
    ],
}

