"""Chinese JavaDoc replacements for RocketMQ wave43b tools [15:30]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetBrokerEpochSubCommand.java': [
        ('public class GetBrokerEpochSubCommand implements SubCommand {',
         '/**\n * getBrokerEpoch 子命令：拉取 Broker 的 Epoch 条目，用于 HA 复制与偏移区间校验。\n */\npublic class GetBrokerEpochSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getBrokerEpoch。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        group.addOption(new Option("c", "clusterName", true, "which cluster"));',
         '        group.addOption(new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）"));'),
        ('        group.addOption(new Option("b", "brokerName", true, "which broker to fetch"));',
         '        group.addOption(new Option("b", "brokerName", true, "目标 Broker 名（与 -c 二选一）"));'),
        ('        Option opt = new Option("i", "interval", true, "the interval(second) of get info");',
         '        Option opt = new Option("i", "interval", true, "轮询间隔（秒），指定后持续刷新输出");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 启动管理客户端，按 -i 决定是否循环拉取 Epoch 信息。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('    private void innerExec(CommandLine commandLine, Options options,\n        DefaultMQAdminExt defaultMQAdminExt) throws Exception {',
         '    /** 按 -b 或 -c 解析目标 Broker 并打印 Epoch 数据。 */\n    private void innerExec(CommandLine commandLine, Options options,\n        DefaultMQAdminExt defaultMQAdminExt) throws Exception {'),
        ('    private void printData(Set<String> brokers, DefaultMQAdminExt defaultMQAdminExt) throws Exception {',
         '    /** 遍历 Broker 地址，拉取 {@link EpochEntryCache} 并格式化输出各 Epoch 区间。 */\n    private void printData(Set<String> brokers, DefaultMQAdminExt defaultMQAdminExt) throws Exception {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetColdDataFlowCtrInfoSubCommand.java': [
        ('public class GetColdDataFlowCtrInfoSubCommand implements SubCommand {',
         '/**\n * getColdDataFlowCtrInfo 子命令：查询 Broker 冷数据流控运行时表与阈值配置。\n */\npublic class GetColdDataFlowCtrInfoSubCommand implements SubCommand {'),
        ('    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");',
         '    /** 时间戳格式化器，用于将毫秒值转为可读时间。 */\n    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getColdDataFlowCtrInfo。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "get from which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "指定 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "get from which cluster");',
         '        opt = new Option("c", "clusterName", true, "指定集群名，遍历 Master/Slave 查询");'),
        ('    public void execute(final CommandLine commandLine, final Options options, final RPCHook rpcHook)',
         '    /** 按 Broker 或集群拉取冷数据流控信息并打印。 */\n    public void execute(final CommandLine commandLine, final Options options, final RPCHook rpcHook)'),
        ('    protected void getAndPrint(final MQAdminExt defaultMQAdminExt, final String printPrefix, final String addr)',
         '    /** 拉取指定地址的冷流控 JSON，格式化时间字段后输出。 */\n    protected void getAndPrint(final MQAdminExt defaultMQAdminExt, final String printPrefix, final String addr)'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/RemoveColdDataFlowCtrGroupConfigSubCommand.java': [
        ('public class RemoveColdDataFlowCtrGroupConfigSubCommand implements SubCommand {',
         '/**\n * removeColdDataFlowCtrGroupConfig 子命令：从冷数据流控配置中移除指定消费组。\n */\npublic class RemoveColdDataFlowCtrGroupConfigSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 removeColdDataFlowCtrGroupConfig。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "update which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "update which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名，批量移除各 Master 配置");'),
        ('        opt = new Option("g", "consumerGroup", true, "the consumer group will remove from the config");',
         '        opt = new Option("g", "consumerGroup", true, "待从冷流控配置中移除的消费组名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 在指定 Broker 或集群全部 Master 上移除消费组冷读阈值配置。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/ResetMasterFlushOffsetSubCommand.java': [
        ('public class ResetMasterFlushOffsetSubCommand implements SubCommand {',
         '/**\n * resetMasterFlushOffset 子命令：在 Slave Broker 上重置 Master 刷盘偏移量。\n */\npublic class ResetMasterFlushOffsetSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 resetMasterFlushOffset。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "which broker to reset");',
         '        Option opt = new Option("b", "brokerAddr", true, "待重置的 Slave Broker 地址");'),
        ('        opt = new Option("o", "offset", true, "the offset to reset at");',
         '        opt = new Option("o", "offset", true, "要设置的 Master 刷盘偏移量");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 调用 {@link DefaultMQAdminExt#resetMasterFlushOffset} 重置指定偏移。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/SendMsgStatusCommand.java': [
        ('public class SendMsgStatusCommand implements SubCommand {',
         '/**\n * sendMsgStatus 子命令：向指定 Broker 发送测试消息并输出 RT 与 {@link SendResult}。\n */\npublic class SendMsgStatusCommand implements SubCommand {'),
        ('    private static Message buildMessage(final String topic, final int messageSize) throws UnsupportedEncodingException {',
         '    /** 构造指定大小的测试 {@link Message}，Topic 为 Broker 名。 */\n    private static Message buildMessage(final String topic, final int messageSize) throws UnsupportedEncodingException {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 sendMsgStatus。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerName", true, "Broker Name e.g. clusterName_brokerName as DefaultCluster_broker-a");',
         '        Option opt = new Option("b", "brokerName", true, "Broker 名，如 DefaultCluster_broker-a");'),
        ('        opt = new Option("s", "messageSize", true, "Message Size, Default: 128");',
         '        opt = new Option("s", "messageSize", true, "消息体大小（字节），默认 128");'),
        ('        opt = new Option("c", "count", true, "send message count, Default: 50");',
         '        opt = new Option("c", "count", true, "发送次数，默认 50");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 启动生产者，预热一条消息后循环发送并打印耗时。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/SwitchTimerEngineSubCommand.java': [
        ('public class SwitchTimerEngineSubCommand implements SubCommand {',
         '/**\n * switchTimerEngine 子命令：切换 Broker 定时消息的存储引擎（RocksDB 时间线 / 文件时间轮）。\n */\npublic class SwitchTimerEngineSubCommand implements SubCommand {'),
        ('    private static final String ROCKSDB_TIMELINE = "ROCKSDB_TIMELINE";',
         '    /** RocksDB 时间线引擎显示名。 */\n    private static final String ROCKSDB_TIMELINE = "ROCKSDB_TIMELINE";'),
        ('    private static final String FILE_TIME_WHEEL = "FILE_TIME_WHEEL";',
         '    /** 文件时间轮引擎显示名。 */\n    private static final String FILE_TIME_WHEEL = "FILE_TIME_WHEEL";'),
        ('    public String commandName() {',
         '    /** 返回子命令名 switchTimerEngine。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "update which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "update which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名，批量切换各 Master");'),
        ('        opt = new Option("e", "engineType", true, "R/F, R for rocksdb timeline engine, F for file time wheel engine");',
         '        opt = new Option("e", "engineType", true, "引擎类型：R=RocksDB 时间线，F=文件时间轮");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 校验 engineType 后在 Broker 或集群 Master 上切换定时消息引擎。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/UpdateBrokerConfigSubCommand.java': [
        ('public class UpdateBrokerConfigSubCommand implements SubCommand {',
         '/**\n * updateBrokerConfig 子命令：在线更新 Broker 运行时配置项（键值对）。\n */\npublic class UpdateBrokerConfigSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 updateBrokerConfig。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "update which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "update which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名，批量更新各 Broker");'),
        ('        opt = new Option("a", "updateAllBroker", true, "update all brokers include slave");',
         '        opt = new Option("a", "updateAllBroker", true, "是否包含 Slave 一并更新（与 -c 配合）");'),
        ('        opt = new Option("k", "key", true, "config key");',
         '        opt = new Option("k", "key", true, "配置项键名");'),
        ('        opt = new Option("v", "value", true, "config value");',
         '        opt = new Option("v", "value", true, "配置项新值");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 构造 Properties 并在指定 Broker 或集群上调用 updateBrokerConfig。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/UpdateColdDataFlowCtrGroupConfigSubCommand.java': [
        ('public class UpdateColdDataFlowCtrGroupConfigSubCommand implements SubCommand {',
         '/**\n * updateColdDataFlowCtrGroupConfig 子命令：新增或更新消费组冷数据读流控阈值。\n */\npublic class UpdateColdDataFlowCtrGroupConfigSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 updateColdDataFlowCtrGroupConfig。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "brokerAddr", true, "update which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "update which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名，批量更新各 Master");'),
        ('        opt = new Option("g", "consumerGroup", true, "specific consumerGroup");',
         '        opt = new Option("g", "consumerGroup", true, "消费组名（作为配置键）");'),
        ('        opt = new Option("v", "threshold", true, "cold read threshold value");',
         '        opt = new Option("v", "threshold", true, "冷读流控阈值");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 将消费组与阈值写入 Properties，在 Broker 或集群上更新冷流控配置。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/cluster/CLusterSendMsgRTCommand.java': [
        ('public class CLusterSendMsgRTCommand implements SubCommand {',
         '/**\n * clusterRT 子命令：对各集群 Broker 循环发送测试消息并统计平均 RT。\n */\npublic class CLusterSendMsgRTCommand implements SubCommand {'),
        ('    public static void main(String[] args) {',
         '    /** 占位 main，无独立入口逻辑。 */\n    public static void main(String[] args) {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 clusterRT。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("a", "amount", true, "message amount | default 100");',
         '        Option opt = new Option("a", "amount", true, "每个 Broker 发送条数，默认 100");'),
        ('        opt = new Option("s", "size", true, "message size | default 128 Byte");',
         '        opt = new Option("s", "size", true, "消息体大小（字节），默认 128");'),
        ('        opt = new Option("c", "cluster", true, "cluster name | default display all cluster");',
         '        opt = new Option("c", "cluster", true, "集群名，缺省则遍历全部集群");'),
        ('        opt = new Option("p", "print log", true, "print as tlog | default false");',
         '        opt = new Option("p", "print log", true, "是否以 tlog 格式输出，默认 false");'),
        ('        opt = new Option("m", "machine room", true, "machine room name | default noname");',
         '        opt = new Option("m", "machine room", true, "机房标识（tlog 模式），默认 noname");'),
        ('        opt = new Option("i", "interval", true, "print interval | default 10 seconds");',
         '        opt = new Option("i", "interval", true, "轮询间隔（秒），默认 10");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 无限循环对各 Broker 压测发送并输出 RT、成功/失败计数。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    public String getStringBySize(long size) {',
         '    /** 生成指定长度的测试字符串。 */\n    public String getStringBySize(long size) {'),
        ('    public String getCurTime() {',
         '    /** 返回 GMT+8 时区的当前时间字符串。 */\n    public String getCurTime() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/cluster/ClusterListSubCommand.java': [
        ('public class ClusterListSubCommand implements SubCommand {',
         '/**\n * clusterList 子命令：列出集群内 Broker 基础或扩展运行时统计信息。\n */\npublic class ClusterListSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 clusterList。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("m", "moreStats", false, "Print more stats");',
         '        Option opt = new Option("m", "moreStats", false, "输出昨日/今日进出 TPS 等扩展统计");'),
        ('        opt = new Option("i", "interval", true, "specify intervals numbers, it is in seconds");',
         '        opt = new Option("i", "interval", true, "轮询间隔（秒），指定后循环刷新");'),
        ('        opt = new Option("c", "clusterName", true, "which cluster");',
         '        opt = new Option("c", "clusterName", true, "过滤指定集群名，缺省显示全部");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取集群信息，按 -m 选择基础或扩展视图，支持 -i 定时刷新。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('    private Set<String> getTargetClusterNames(String clusterName, ClusterInfo clusterInfo) {',
         '    /** 解析目标集群名集合：空则返回全部集群。 */\n    private Set<String> getTargetClusterNames(String clusterName, ClusterInfo clusterInfo) {'),
        ('    private void printClusterMoreStats(final Set<String> clusterNames,',
         '    /** 打印各 Broker 昨日/今日消息进出总量统计。 */\n    private void printClusterMoreStats(final Set<String> clusterNames,'),
        ('    private void printClusterBaseInfo(final Set<String> clusterNames,',
         '    /** 打印各 Broker TPS、队列积压、定时消息进度等基础运行时指标。 */\n    private void printClusterBaseInfo(final Set<String> clusterNames,'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/connection/ConsumerConnectionSubCommand.java': [
        ('public class ConsumerConnectionSubCommand implements SubCommand {',
         '/**\n * consumerConnection 子命令：查询消费组在线连接、客户端版本与订阅关系。\n */\npublic class ConsumerConnectionSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 consumerConnection。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "consumerGroup", true, "consumer group name");',
         '        Option opt = new Option("g", "consumerGroup", true, "消费组名");'),
        ('        opt = new Option("b", "brokerAddr", true, "broker address");',
         '        opt = new Option("b", "brokerAddr", true, "可选，指定 Broker 地址查询");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 {@link ConsumerConnection} 并打印连接列表、订阅表与消费模式。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/connection/ProducerConnectionSubCommand.java': [
        ('public class ProducerConnectionSubCommand implements SubCommand {',
         '/**\n * producerConnection 子命令：查询指定 Topic 下生产者组的在线连接与版本。\n */\npublic class ProducerConnectionSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 producerConnection。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "producerGroup", true, "producer group name");',
         '        Option opt = new Option("g", "producerGroup", true, "生产者组名");'),
        ('        opt = new Option("t", "topic", true, "topic name");',
         '        opt = new Option("t", "topic", true, "Topic 名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 {@link ProducerConnection} 并逐行打印客户端连接信息。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java': [
        ('public class ConsumerProgressSubCommand implements SubCommand {',
         '/**\n * consumerProgress 子命令：查询消费组各队列偏移、堆积量与消费 TPS。\n */\npublic class ConsumerProgressSubCommand implements SubCommand {'),
        ('    private static final Logger log = LoggerFactory.getLogger(ConsumerProgressSubCommand.class);',
         '    /** 日志记录器。 */\n    private static final Logger log = LoggerFactory.getLogger(ConsumerProgressSubCommand.class);'),
        ('    public String commandName() {',
         '    /** 返回子命令名 consumerProgress。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "groupName", true, "consumer group name");',
         '        Option opt = new Option("g", "groupName", true, "消费组名（缺省则扫描全部重试组）");'),
        ('        opt = new Option("t", "topicName", true, "topic name");',
         '        opt = new Option("t", "topicName", true, "可选，限定 Topic 的消费进度");'),
        ('        Option optionShowClientIP = new Option("s", "showClientIP", true, "Show Client IP per Queue");',
         '        Option optionShowClientIP = new Option("s", "showClientIP", true, "是否显示各队列分配的客户端 IP");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic，用于路由查询");'),
        ('    private Map<MessageQueue, String> getMessageQueueAllocationResult(DefaultMQAdminExt defaultMQAdminExt,',
         '    /** 汇总各消费实例当前分配的 {@link MessageQueue} 与客户端 IP。 */\n    private Map<MessageQueue, String> getMessageQueueAllocationResult(DefaultMQAdminExt defaultMQAdminExt,'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 按 -g 查询单组进度，或扫描全部 %RETRY% 消费组汇总列表。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('                        // ignore',
         '                        // 忽略时间戳格式化异常'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerStatusSubCommand.java': [
        ('public class ConsumerStatusSubCommand implements SubCommand {',
         '/**\n * consumerStatus 子命令：导出消费组各实例内部运行态（订阅、Rebalance、ProcessQueue）。\n */\npublic class ConsumerStatusSubCommand implements SubCommand {'),
        ('    public static void main(String[] args) {',
         '    /** 本地调试入口，连接 127.0.0.1:9876 执行 consumerStatus。 */\n    public static void main(String[] args) {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 consumerStatus。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "consumerGroup", true, "consumer group name");',
         '        Option opt = new Option("g", "consumerGroup", true, "消费组名");'),
        ('        opt = new Option("i", "clientId", true, "The consumer\'s client id");',
         '        opt = new Option("i", "clientId", true, "可选，指定单个消费者 clientId");'),
        ('        opt = new Option("b", "brokerAddr", true, "broker address");',
         '        opt = new Option("b", "brokerAddr", true, "可选，指定 Broker 地址查询连接");'),
        ('        opt = new Option("s", "jstack", false, "Run jstack command in the consumer progress");',
         '        opt = new Option("s", "jstack", false, "是否在消费端执行 jstack 采集线程栈");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取各实例 {@link ConsumerRunningInfo}，分析订阅/Rebalance 并写入本地文件。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerSubCommand.java': [
        ('public class ConsumerSubCommand implements SubCommand {',
         '/**\n * consumer 子命令：综合查询消费组连接、运行态与 Rebalance 分析结果。\n */\npublic class ConsumerSubCommand implements SubCommand {'),
        ('    public static void main(String[] args) {',
         '    /** 本地调试入口，连接 127.0.0.1:9876 执行 consumer 命令。 */\n    public static void main(String[] args) {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 consumer。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "consumerGroup", true, "consumer group name");',
         '        Option opt = new Option("g", "consumerGroup", true, "消费组名");'),
        ('        opt = new Option("s", "jstack", false, "Run jstack command in the consumer progress");',
         '        opt = new Option("s", "jstack", false, "是否在消费端执行 jstack 采集线程栈");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历消费组全部连接，导出运行态并分析订阅一致性与 Rebalance 状态。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
}

# Merge GroupConsumeInfo annotations into ConsumerProgressSubCommand entry
R['tools/src/main/java/org/apache/rocketmq/tools/command/consumer/ConsumerProgressSubCommand.java'].extend([
    ('class GroupConsumeInfo implements Comparable<GroupConsumeInfo> {',
     '/**\n * 消费组汇总信息：用于 consumerProgress 无 -g 时批量展示各重试组状态。\n */\nclass GroupConsumeInfo implements Comparable<GroupConsumeInfo> {'),
    ('    private String group;',
     '    /** 消费组名。 */\n    private String group;'),
    ('    private int version;',
     '    /** 组内最低客户端协议版本号。 */\n    private int version;'),
    ('    private int count;',
     '    /** 在线消费实例数量。 */\n    private int count;'),
    ('    private ConsumeType consumeType;',
     '    /** 消费类型（Push/Pull）。 */\n    private ConsumeType consumeType;'),
    ('    private MessageModel messageModel;',
     '    /** 消息模式（集群/广播）。 */\n    private MessageModel messageModel;'),
    ('    private int consumeTps;',
     '    /** 消费 TPS。 */\n    private int consumeTps;'),
    ('    private long diffTotal;',
     '    /** 总堆积量（BrokerOffset - ConsumerOffset 之和）。 */\n    private long diffTotal;'),
    ('    public String getGroup() {',
     '    /** 返回消费组名。 */\n    public String getGroup() {'),
    ('    public void setGroup(String group) {',
     '    /** 设置消费组名。 */\n    public void setGroup(String group) {'),
    ('    public String consumeTypeDesc() {',
     '    /** 返回 PULL/PUSH 描述；离线时返回空串。 */\n    public String consumeTypeDesc() {'),
    ('    public String messageModelDesc() {',
     '    /** Push 模式下返回消息模型描述。 */\n    public String messageModelDesc() {'),
    ('    public String versionDesc() {',
     '    /** 返回最低客户端版本描述。 */\n    public String versionDesc() {'),
    ('    @Override\n    public int compareTo(GroupConsumeInfo o) {',
     '    /** 按在线数、堆积量降序排序。 */\n    @Override\n    public int compareTo(GroupConsumeInfo o) {'),
])
