"""Chinese JavaDoc replacements for RocketMQ wave43a tools [0:15]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/DeleteAclSubCommand.java': [
        ('public class DeleteAclSubCommand implements SubCommand {',
         '/**\n * deleteAcl 子命令：从指定集群或 Broker 删除 ACL 访问控制规则。\n */\npublic class DeleteAclSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Delete acl from cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Delete acl from cluster.";'),
        ('        Option opt = new Option("c", "clusterName", true, "delete acl from which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "delete acl from which broker");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("s", "subject", true, "the subject of acl to delete.");',
         '        opt = new Option("s", "subject", true, "待删除 ACL 的主体（用户名或角色）");'),
        ('        opt = new Option("r", "resources", true, "the resources of acl to delete");',
         '        opt = new Option("r", "resources", true, "待删除 ACL 资源（可选，逗号分隔）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 上调用 deleteAcl。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历主从 Broker 逐一删除 ACL\n                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/DeleteUserSubCommand.java': [
        ('public class DeleteUserSubCommand implements SubCommand {',
         '/**\n * deleteUser 子命令：从指定集群或 Broker 删除用户账户。\n */\npublic class DeleteUserSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Delete user from cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Delete user from cluster.";'),
        ('        Option opt = new Option("c", "clusterName", true, "delete acl from which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "delete user from which broker");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("u", "username", true, "the username of user to delete.");',
         '        opt = new Option("u", "username", true, "待删除的用户名");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 上调用 deleteUser。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历主从 Broker 逐一删除用户\n                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/GetAclSubCommand.java': [
        ('    private static final String FORMAT = "%-16s  %-10s  %-22s  %-20s  %-24s  %-10s%n";',
         '    /** ACL 策略表格输出格式。 */\n    private static final String FORMAT = "%-16s  %-10s  %-22s  %-20s  %-24s  %-10s%n";'),
        ('public class GetAclSubCommand implements SubCommand {',
         '/**\n * getAcl 子命令：查询指定 Broker 或集群上的 ACL 规则详情。\n */\npublic class GetAclSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get acl from cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get acl from cluster.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "get acl for which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "查询目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "get acl for specified cluster");',
         '        opt = new Option("c", "clusterName", true, "查询目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("s", "subject", true, "the subject of acl to get");',
         '        opt = new Option("s", "subject", true, "ACL 主体过滤（可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 ACL 信息并以表格形式打印策略条目。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：仅查询各 Master Broker 上的 ACL\n                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);'),
        ('    private void printAcl(AclInfo acl) {',
         '    /** 格式化输出单条 ACL 及其策略条目。 */\n    private void printAcl(AclInfo acl) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/GetUserSubCommand.java': [
        ('    private static final String FORMAT = "%-16s  %-22s  %-22s  %-22s%n";',
         '    /** 用户信息表格输出格式。 */\n    private static final String FORMAT = "%-16s  %-22s  %-22s  %-22s%n";'),
        ('public class GetUserSubCommand implements SubCommand {',
         '/**\n * getUser 子命令：查询指定 Broker 或集群上的用户账户信息。\n */\npublic class GetUserSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get user from cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get user from cluster.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "get user for which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "查询目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "get user for specified cluster");',
         '        opt = new Option("c", "clusterName", true, "查询目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("u", "username", true, "the username of user to get");',
         '        opt = new Option("u", "username", true, "待查询的用户名（可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取用户信息并以表格形式打印。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                for (String masterAddr : masterSet) {\n                    UserInfo userInfo = defaultMQAdminExt.getUser(masterAddr, username);\n                    if (userInfo != null) {\n                        printUser(userInfo);\n                        break;\n                    }\n                }',
         '                // 集群模式：遍历 Master 直到找到匹配用户\n                for (String masterAddr : masterSet) {\n                    UserInfo userInfo = defaultMQAdminExt.getUser(masterAddr, username);\n                    if (userInfo != null) {\n                        printUser(userInfo);\n                        break;\n                    }\n                }'),
        ('    private void printUser(UserInfo user) {',
         '    /** 格式化输出单个用户信息。 */\n    private void printUser(UserInfo user) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/ListAclSubCommand.java': [
        ('    private static final String FORMAT = "%-16s  %-10s  %-22s  %-20s  %-24s  %-10s%n";',
         '    /** ACL 列表表格输出格式。 */\n    private static final String FORMAT = "%-16s  %-10s  %-22s  %-20s  %-24s  %-10s%n";'),
        ('public class ListAclSubCommand implements SubCommand {',
         '/**\n * listAcl 子命令：列出指定 Broker 或集群上的 ACL 规则。\n */\npublic class ListAclSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "List acl from cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "List acl from cluster.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "list acl for which broker.");',
         '        Option opt = new Option("b", "brokerAddr", true, "查询目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "list acl for specified cluster.");',
         '        opt = new Option("c", "clusterName", true, "查询目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("s", "subject", true, "the subject of acl to filter.");',
         '        opt = new Option("s", "subject", true, "按 ACL 主体过滤（可选）");'),
        ('        opt = new Option("r", "resource", true, "the resource of acl to filter.");',
         '        opt = new Option("r", "resource", true, "按 ACL 资源过滤（可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 ACL 列表并以表格形式打印全部策略条目。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('    private void printAcl(List<AclInfo> acls) {',
         '    /** 格式化输出 ACL 列表及其策略条目。 */\n    private void printAcl(List<AclInfo> acls) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/ListUserSubCommand.java': [
        ('    private static final String FORMAT = "%-16s  %-22s  %-22s  %-22s%n";',
         '    /** 用户列表表格输出格式。 */\n    private static final String FORMAT = "%-16s  %-22s  %-22s  %-22s%n";'),
        ('public class ListUserSubCommand implements SubCommand {',
         '/**\n * listUser 子命令：列出指定 Broker 或集群上的用户账户。\n */\npublic class ListUserSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "List user from cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "List user from cluster.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "list user for which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "查询目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "list user for specified cluster");',
         '        opt = new Option("c", "clusterName", true, "查询目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("f", "filter", true, "the filter to list users");',
         '        opt = new Option("f", "filter", true, "用户名过滤条件（可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取用户列表并以表格形式打印。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                        printUsers(userInfos);\n                        System.out.printf("get user from %s success.%n", masterAddr);\n                        break;',
         '                        printUsers(userInfos);\n                        // 集群模式：首个有数据的 Master 即返回\n                        System.out.printf("get user from %s success.%n", masterAddr);\n                        break;'),
        ('    private void printUsers(List<UserInfo> users) {',
         '    /** 格式化输出用户列表。 */\n    private void printUsers(List<UserInfo> users) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/UpdateAclSubCommand.java': [
        ('public class UpdateAclSubCommand implements SubCommand {',
         '/**\n * updateAcl 子命令：更新指定集群或 Broker 上的 ACL 访问控制规则。\n */\npublic class UpdateAclSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update acl to cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update acl to cluster.";'),
        ('        Option opt = new Option("c", "clusterName", true, "update acl to which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "update acl to which broker");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("s", "subject", true, "the subject of acl to update.");',
         '        opt = new Option("s", "subject", true, "ACL 主体（用户名或角色）");'),
        ('        opt = new Option("r", "resources", true, "the resources of acl to update");',
         '        opt = new Option("r", "resources", true, "ACL 资源列表（逗号分隔）");'),
        ('        opt = new Option("a", "actions", true, "the actions of acl to update");',
         '        opt = new Option("a", "actions", true, "ACL 操作权限列表（逗号分隔）");'),
        ('        opt = new Option("d", "decision", true, "the decision of acl to update");',
         '        opt = new Option("d", "decision", true, "ACL 决策（Allow/Deny）");'),
        ('        opt = new Option("i", "sourceIp", true, "the sourceIps of acl to update");',
         '        opt = new Option("i", "sourceIp", true, "来源 IP 白名单（逗号分隔，可选）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 上调用 updateAcl。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历主从 Broker 逐一更新 ACL\n                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/auth/UpdateUserSubCommand.java': [
        ('public class UpdateUserSubCommand implements SubCommand {',
         '/**\n * updateUser 子命令：更新指定集群或 Broker 上的用户账户信息。\n */\npublic class UpdateUserSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update user to cluster.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update user to cluster.";'),
        ('        Option opt = new Option("c", "clusterName", true, "update user to which cluster");',
         '        Option opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "update user to which broker");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("u", "username", true, "the username of user to update.");',
         '        opt = new Option("u", "username", true, "待更新的用户名");'),
        ('        opt = new Option("p", "password", true, "the password of user to update");',
         '        opt = new Option("p", "password", true, "新密码（与 -t/-s 三选一）");'),
        ('        opt = new Option("t", "userType", true, "the userType of user to update");',
         '        opt = new Option("t", "userType", true, "用户类型（与 -p/-s 三选一）");'),
        ('        opt = new Option("s", "userStatus", true, "the userStatus of user to update");',
         '        opt = new Option("s", "userStatus", true, "用户状态（与 -p/-t 三选一）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 上调用 updateUser。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历主从 Broker 逐一更新用户\n                Set<String> brokerAddrSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/BrokerConsumeStatsSubCommand.java': [
        ('public class BrokerConsumeStatsSubCommand implements SubCommand {',
         '/**\n * brokerConsumeStats 子命令：拉取 Broker 上各消费组的消费进度与堆积差值。\n */\npublic class BrokerConsumeStatsSubCommand implements SubCommand {'),
        ('    private DefaultMQAdminExt defaultMQAdminExt;',
         '    /** 复用的 MQAdmin 客户端实例。 */\n    private DefaultMQAdminExt defaultMQAdminExt;'),
        ('    private DefaultMQAdminExt createMQAdminExt(RPCHook rpcHook) throws SubCommandException {',
         '    /** 懒创建并启动 {@link DefaultMQAdminExt}，避免重复初始化。 */\n    private DefaultMQAdminExt createMQAdminExt(RPCHook rpcHook) throws SubCommandException {'),
        ('    public String commandDesc() {\n        return "Fetch broker consume stats data.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Fetch broker consume stats data.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "Broker address");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址");'),
        ('        opt = new Option("t", "timeoutMillis", true, "request timeout Millis");',
         '        opt = new Option("t", "timeoutMillis", true, "请求超时时间（毫秒，默认 50000）");'),
        ('        opt = new Option("l", "level", true, "threshold of print diff");',
         '        opt = new Option("l", "level", true, "仅输出堆积量不低于该阈值的队列");'),
        ('        opt = new Option("o", "order", true, "order topic");',
         '        opt = new Option("o", "order", true, "是否按顺序 Topic 统计（true/false）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取消费统计并按 Topic/Group/队列维度打印偏移与堆积差。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('                            if (diff < diffLevel) {\n                                continue;\n                            }',
         '                            // 过滤低于阈值的堆积差\n                            if (diff < diffLevel) {\n                                continue;\n                            }'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/BrokerStatusSubCommand.java': [
        ('public class BrokerStatusSubCommand implements SubCommand {',
         '/**\n * brokerStatus 子命令：查询 Broker 运行时状态指标（KV 键值对）。\n */\npublic class BrokerStatusSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Fetch broker runtime status data.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Fetch broker runtime status data.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "Broker address");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 Broker 运行时统计并按字典序打印。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('                Set<String> masterSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历主从 Broker 分别打印运行时状态\n                Set<String> masterSet =\n                    CommandUtil.fetchMasterAndSlaveAddrByClusterName(defaultMQAdminExt, clusterName);'),
        ('    public void printBrokerRuntimeStats(final DefaultMQAdminExt defaultMQAdminExt, final String brokerAddr,\n        final boolean printBroker)',
         '    /** 拉取并格式化输出 Broker 运行时 KV 指标。 */\n    public void printBrokerRuntimeStats(final DefaultMQAdminExt defaultMQAdminExt, final String brokerAddr,\n        final boolean printBroker)'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/CleanExpiredCQSubCommand.java': [
        ('public class CleanExpiredCQSubCommand implements SubCommand {',
         '/**\n * cleanExpiredCQ 子命令：清理 Broker 上过期的 ConsumeQueue 文件。\n */\npublic class CleanExpiredCQSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Clean expired ConsumeQueue on broker.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Clean expired ConsumeQueue on broker.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "Broker address");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "cluster", true, "clustername");',
         '        opt = new Option("c", "cluster", true, "目标集群名（与 -b 二选一）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 触发 Broker 清理过期 ConsumeQueue 并输出 success/false。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/CleanUnusedTopicCommand.java': [
        ('public class CleanUnusedTopicCommand implements SubCommand {',
         '/**\n * cleanUnusedTopic 子命令：清理 Broker 上未被引用的 Topic 数据。\n */\npublic class CleanUnusedTopicCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Clean unused topic on broker.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Clean unused topic on broker.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "Broker address");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "cluster", true, "cluster name");',
         '        opt = new Option("c", "cluster", true, "目标集群名（与 -b 二选一）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 触发 Broker 清理无用 Topic 并输出 success/false。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/CommitLogSetReadAheadSubCommand.java': [
        ('    private static final String MADV_RANDOM = "1";',
         '    /** madvise 随机读模式（MADV_RANDOM）。 */\n    private static final String MADV_RANDOM = "1";'),
        ('    private static final String MADV_NORMAL = "0";',
         '    /** madvise 默认顺序读模式（MADV_NORMAL）。 */\n    private static final String MADV_NORMAL = "0";'),
        ('public class CommitLogSetReadAheadSubCommand implements SubCommand {',
         '/**\n * setCommitLogReadAheadMode 子命令：设置 CommitLog 文件的 read-ahead 预读模式。\n */\npublic class CommitLogSetReadAheadSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Set read ahead mode for all commitlog files.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Set read ahead mode for all commitlog files.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "set which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "set which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("m", "commitLogReadAheadMode", true, "set the CommitLog read ahead mode; 0 is default, 1 random read");',
         '        opt = new Option("m", "commitLogReadAheadMode", true, "CommitLog 预读模式：0 默认顺序读，1 随机读");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)',
         '    /** 校验模式参数并对指定 Broker 或集群设置 CommitLog 预读策略。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)'),
        ('                Map<String, List<String>> masterAndSlaveMap = CommandUtil.fetchMasterAndSlaveDistinguish(defaultMQAdminExt, clusterName);',
         '                // 集群模式：分别对 Master 及其 Slave 设置预读模式\n                Map<String, List<String>> masterAndSlaveMap = CommandUtil.fetchMasterAndSlaveDistinguish(defaultMQAdminExt, clusterName);'),
        ('    protected void setAndPrint(final MQAdminExt defaultMQAdminExt, final String printPrefix, final String addr, final String mode)',
         '    /** 调用远程接口设置预读模式并打印结果。 */\n    protected void setAndPrint(final MQAdminExt defaultMQAdminExt, final String printPrefix, final String addr, final String mode)'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/DeleteExpiredCommitLogSubCommand.java': [
        ('/**\n * MQAdmin command which deletes expired CommitLog files\n */',
         '/**\n * deleteExpiredCommitLog 子命令：删除 Broker 上过期的 CommitLog 文件。\n */'),
        ('    public String commandDesc() {\n        return "Delete expired CommitLog files.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Delete expired CommitLog files.";'),
        ('        Option opt = new Option("n", "namesrvAddr", true, "Name server address");',
         '        Option opt = new Option("n", "namesrvAddr", true, "NameServer 地址（可选，覆盖默认配置）");'),
        ('        opt = new Option("b", "brokerAddr", true, "Broker address");',
         '        opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "cluster", true, "clustername");',
         '        opt = new Option("c", "cluster", true, "目标集群名（与 -b 二选一）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 触发 Broker 删除过期 CommitLog 并输出 success/false。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/broker/GetBrokerConfigCommand.java': [
        ('public class GetBrokerConfigCommand implements SubCommand {',
         '/**\n * getBrokerConfig 子命令：查询 Broker 运行时配置项（Properties）。\n */\npublic class GetBrokerConfigCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get broker config by cluster or special broker.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get broker config by cluster or special broker.";'),
        ('        group.addOption(new Option("b", "brokerAddr", true, "get which broker"));',
         '        group.addOption(new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）"));'),
        ('        group.addOption(new Option("c", "clusterName", true, "get which cluster"));',
         '        group.addOption(new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）"));'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 Broker 配置并按 key=value 格式打印。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {'),
        ('                Map<String, List<String>> masterAndSlaveMap\n                    = CommandUtil.fetchMasterAndSlaveDistinguish(defaultMQAdminExt, clusterName);',
         '                // 集群模式：分别拉取 Master 及其 Slave 的配置\n                Map<String, List<String>> masterAndSlaveMap\n                    = CommandUtil.fetchMasterAndSlaveDistinguish(defaultMQAdminExt, clusterName);'),
        ('    protected void getAndPrint(final MQAdminExt defaultMQAdminExt, final String printPrefix, final String addr)',
         '    /** 拉取指定 Broker 配置并以 key=value 格式输出。 */\n    protected void getAndPrint(final MQAdminExt defaultMQAdminExt, final String printPrefix, final String addr)'),
        ('        if (addr.equals(CommandUtil.NO_MASTER_PLACEHOLDER)) {',
         '        // 占位符表示该 Broker 无 Master，跳过\n        if (addr.equals(CommandUtil.NO_MASTER_PLACEHOLDER)) {'),
    ],
}
