"""RocketMQ 5.5.0 wave48a client/consumer/transaction [0:15] replacements."""

R: dict[str, list[tuple[str, str]]] = {}

R['broker/src/main/java/org/apache/rocketmq/broker/transaction/queue/TransactionalMessageServiceImpl.java'] = [
    ('public class TransactionalMessageServiceImpl implements TransactionalMessageService {', '/**\n * 基于 Half/Op Topic 队列的事务消息服务实现：prepare 写入半消息，\n * 定时回查未决事务，根据 commit/rollback 投递或删除半消息。\n * 配合 {@link TransactionalMessageBridge} 访问 MessageStore。\n */\npublic class TransactionalMessageServiceImpl implements TransactionalMessageService {'),
    ('    private static final int PULL_MSG_RETRY_NUMBER = 1;', '    /** 拉取 Op/Half 消息失败时的重试次数。 */\n    private static final int PULL_MSG_RETRY_NUMBER = 1;'),
    ('    private static final int MAX_PROCESS_TIME_LIMIT = 60000;', '    /** 单次事务回查批处理最大耗时（毫秒）。 */\n    private static final int MAX_PROCESS_TIME_LIMIT = 60000;'),
    ('    private static final int MAX_RETRY_TIMES_FOR_ESCAPE = 10;', '    /** Op 消息缺失时 escape 重试上限。 */\n    private static final int MAX_RETRY_TIMES_FOR_ESCAPE = 10;'),
    ('    private static final int MAX_RETRY_COUNT_WHEN_HALF_NULL = 1;', '    /** Half 消息为空时的最大重试次数。 */\n    private static final int MAX_RETRY_COUNT_WHEN_HALF_NULL = 1;'),
    ('    private static final int OP_MSG_PULL_NUMS = 32;', '    /** 单次从 Op Topic 拉取的消息条数。 */\n    private static final int OP_MSG_PULL_NUMS = 32;'),
    ('    private static final int SLEEP_WHILE_NO_OP = 1000;', '    /** 无 Op 消息可拉时的休眠间隔（毫秒）。 */\n    private static final int SLEEP_WHILE_NO_OP = 1000;'),
    ('    private final ConcurrentHashMap<Integer, MessageQueueOpContext> deleteContext = new ConcurrentHashMap<>();', '    /** queueId → Op 消息批量删除上下文。 */\n    private final ConcurrentHashMap<Integer, MessageQueueOpContext> deleteContext = new ConcurrentHashMap<>();'),
    ('    private ConcurrentHashMap<MessageQueue, MessageQueue> opQueueMap = new ConcurrentHashMap<>();', '    /** Half 队列 → 对应 Op 队列映射。 */\n    private ConcurrentHashMap<MessageQueue, MessageQueue> opQueueMap = new ConcurrentHashMap<>();'),
    ('                // single thread', '                // 单线程顺序处理，避免并发回查冲突'),
    ('    /**\n     * Read op message, parse op message, and fill removeMap\n     *\n     * @param removeMap Half message to be remove, key:halfOffset, value: opOffset.\n     * @param opQueue Op message queue.\n     * @param pullOffsetOfOp The begin offset of op message queue.\n     * @param miniOffset The current minimum offset of half message queue.\n     * @param opMsgMap Half message offset in op message\n     * @param doneOpOffset Stored op messages that have been processed.\n     * @return Op message result.\n     */', '    /**\n     * 拉取并解析 Op 消息，填充待删除 Half 消息的 removeMap。\n     *\n     * @param removeMap 待删除半消息映射，key 为 halfOffset，value 为 opOffset\n     * @param opQueue Op 消息队列\n     * @param pullOffsetOfOp Op 队列起始拉取 offset\n     * @param miniOffset Half 队列当前最小 offset\n     * @param opMsgMap Op offset → 关联 half offset 集合\n     * @param doneOpOffset 已处理完毕的 Op offset 列表\n     * @return Op 消息拉取结果\n     */'),
    ('    /**\n     * If return true, skip this msg\n     *\n     * @param removeMap Op message map to determine whether a half message was responded by producer.\n     * @param doneOpOffset Op Message which has been checked.\n     * @param msgExt Half message\n     * @return Return true if put success, otherwise return false.\n     */', '    /**\n     * 校验半消息是否已有 Producer 响应；返回 true 则跳过该消息。\n     *\n     * @param removeMap Op 消息映射，判定半消息是否已被 Producer 确认\n     * @param doneOpOffset 已校验的 Op 消息 offset\n     * @param msgExt 半消息\n     * @return 成功处理返回 true，否则 false\n     */'),
    ('    /**\n     * Write messageExt to Half topic again\n     *\n     * @param messageExt Message will be write back to queue\n     * @return Put result can used to determine the specific results of storage.\n     */', '    /**\n     * 将半消息重新写回 Half Topic（回查未决时延后投递）。\n     *\n     * @param messageExt 待写回的消息\n     * @return 落盘结果，可用于判断存储是否成功\n     */'),
    ('    /**\n     * Read half message from Half Topic\n     *\n     * @param mq Target message queue, in this method, it means the half message queue.\n     * @param offset Offset in the message queue.\n     * @param nums Pull message number.\n     * @return Messages pulled from half message queue.\n     */', '    /**\n     * 从 Half Topic 拉取半消息。\n     *\n     * @param mq 目标队列（此处为 Half 消息队列）\n     * @param offset 队列内 offset\n     * @param nums 拉取条数\n     * @return 拉取到的半消息列表\n     */'),
    ('    /**\n     * Read op message from Op Topic\n     *\n     * @param mq Target Message Queue\n     * @param offset Offset in the message queue\n     * @param nums Pull message number\n     * @return Messages pulled from operate message queue.\n     */', '    /**\n     * 从 Op Topic 拉取操作消息（记录 commit/rollback 对应的 half offset）。\n     *\n     * @param mq 目标 Op 消息队列\n     * @param offset 队列内 offset\n     * @param nums 拉取条数\n     * @return 拉取到的 Op 消息\n     */'),
    ('                        // wait for the interval', '                        // 等待批量删除间隔后再提交'),
]

R['client/src/main/java/org/apache/rocketmq/client/ClientConfig.java'] = [
    ('/**\n * Client Common configuration\n */', '/**\n * RocketMQ 客户端公共配置基类：NameServer 地址、心跳间隔、TLS/VIP 通道、\n * 消息轨迹、流式请求类型及发送容错等参数，Producer/Consumer 均继承此类。\n */'),
    ('    /**\n     * Pulling topic information interval from the named server\n     */', '    /** 从 NameServer 拉取 Topic 路由信息的间隔（毫秒）。 */'),
    ('    /**\n     * Heartbeat interval in microseconds with message broker\n     */', '    /** 与 Broker 心跳间隔（毫秒；注释误写为微秒，实际为毫秒）。 */'),
    ('    /**\n     * Offset persistent interval for consumer\n     */', '    /** 消费位点持久化间隔（毫秒）。 */'),
    ('    /**\n     * Enable stream request type will inject a RPCHook to add corresponding request type to remoting layer.\n     * And it will also generate a different client id to prevent unexpected reuses of MQClientInstance.\n     */', '    /**\n     * 启用流式请求类型：注入 RPCHook 标记 Remoting 请求类型，\n     * 并生成不同的 clientId 以避免 MQClientInstance 被意外复用。\n     */'),
    ('    /**\n     * Enable the fault tolerance mechanism of the client sending process.\n     * DO NOT OPEN when ORDER messages are required.\n     * Turning on will interfere with the queue selection functionality,\n     * possibly conflicting with the order message.\n     */', '    /**\n     * 启用发送侧容错（延迟探测与 Broker 隔离）。\n     * 顺序消息场景请勿开启，否则会干扰队列选择逻辑。\n     */'),
    ('    /**\n     * The switch for message trace\n     */', '    /** 是否开启消息轨迹追踪。 */'),
    ('    /**\n     * The name value of message trace topic. If not set, the default trace topic name will be used.\n     */', '    /** 消息轨迹 Topic 名称；未设置时使用默认轨迹 Topic。 */'),
    ('    public String buildMQClientId() {', '    /** 构造 clientId：clientIP@instanceName[@unitName][@STREAM]。 */\n    public String buildMQClientId() {'),
    ('    /**\n     * Domain name mode access way does not support the delimiter(;), and only one domain name can be set.\n     *\n     * @param namesrvAddr name server address\n     */', '    /**\n     * 设置 NameServer 地址；域名模式不支持分号分隔，仅允许单个域名。\n     *\n     * @param namesrvAddr NameServer 地址\n     */'),
    ('    public void setClientCallbackExecutorThreads(int clientCallbackExecutorThreads) {', '    /** 设置客户端异步回调线程池大小。 */\n    public void setClientCallbackExecutorThreads(int clientCallbackExecutorThreads) {'),
    ('    public void setPollNameServerInterval(int pollNameServerInterval) {', '    /** 设置从 NameServer 拉取路由的间隔（毫秒）。 */\n    public void setPollNameServerInterval(int pollNameServerInterval) {'),
]

R['client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPushConsumer.java'] = [
    ('/**\n * In most scenarios, this is the mostly recommended class to consume messages.\n * </p>\n * Technically speaking, this push client is virtually a wrapper of the underlying pull service. Specifically, on\n * arrival of messages pulled from brokers, it roughly invokes the registered callback handler to feed the messages.\n * </p>\n * See quickstart/Consumer in the example module for a typical usage.\n * </p>\n *\n * <p>\n * <strong>Thread Safety:</strong> After initialization, the instance can be regarded as thread-safe.\n * </p>\n */', '/**\n * Push 模式消费者（推荐）：底层仍为 Pull，拉取到消息后回调 {@link MessageListener}。\n * 示例见 example 模块 quickstart/Consumer。\n * <p><strong>线程安全：</strong>初始化完成后可视为线程安全。\n */'),
    ('    /**\n     * Internal implementation. Most of the functions herein are delegated to it.\n     */', '    /** 内部实现，大部分逻辑委托给 {@link DefaultMQPushConsumerImpl}。 */'),
    ('    /**\n     * Consumers of the same role is required to have exactly same subscriptions and consumerGroup to correctly achieve\n     * load balance. It\'s required and needs to be globally unique.\n     * </p>\n     * See <a href="https://rocketmq.apache.org/docs/introduction/02concepts">here</a> for further discussion.\n     */', '    /**\n     * 消费组名：同组消费者须订阅一致以实现负载均衡，全局唯一。\n     * 详见 <a href="https://rocketmq.apache.org/docs/introduction/02concepts">概念文档</a>。\n     */'),
    ('    /**\n     * Message model defines the way how messages are delivered to each consumer clients.\n     * </p>\n     * RocketMQ supports two message models: clustering and broadcasting. If clustering is set, consumer clients with\n     * the same {@link #consumerGroup} would only consume shards of the messages subscribed, which achieves load\n     * balances; Conversely, if the broadcasting is set, each consumer client will consume all subscribed messages\n     * separately.\n     * </p>\n     * This field defaults to clustering.\n     */', '    /**\n     * 消息模型：CLUSTERING（集群，同组分摊队列）或 BROADCASTING（广播，每实例消费全量）。\n     * 默认 CLUSTERING。\n     */'),
    ('    /**\n     * Consuming point on consumer booting.\n     * </p>\n     * There are three consuming points:\n     * <ul>\n     * <li>\n     * <code>CONSUME_FROM_LAST_OFFSET</code>: consumer clients pick up where it stopped previously.\n     * If it were a newly booting up consumer client, according aging of the consumer group, there are two\n     * cases:\n     * <ol>\n     * <li>\n     * if the consumer group is created so recently that the earliest message being subscribed has yet\n     * expired, which means the consumer group represents a lately launched business, consuming will\n     * start from the very beginning;\n     * </li>\n     * <li>\n     * if the earliest message being subscribed has expired, consuming will start from the latest\n     * messages, meaning messages born prior to the booting timestamp would be ignored.\n     * </li>\n     * </ol>\n     * </li>\n     * <li>\n     * <code>CONSUME_FROM_FIRST_OFFSET</code>: Consumer client will start from earliest messages available.\n     * </li>\n     * <li>\n     * <code>CONSUME_FROM_TIMESTAMP</code>: Consumer client will start from specified timestamp, which means\n     * messages born prior to {@link #consumeTimestamp} will be ignored\n     * </li>\n     * </ul>\n     */', '    /**\n     * 启动时的消费位点策略：\n     * <ul>\n     * <li>CONSUME_FROM_LAST_OFFSET：从上次位点继续；新组视消息是否过期决定从头或最新</li>\n     * <li>CONSUME_FROM_FIRST_OFFSET：从最早可用消息开始</li>\n     * <li>CONSUME_FROM_TIMESTAMP：从 {@link #consumeTimestamp} 指定时刻开始</li>\n     * </ul>\n     */'),
    ('    /**\n     * Backtracking consumption time with second precision. Time format is\n     * 20131223171201<br>\n     * Implying Seventeen twelve and 01 seconds on December 23, 2013 year<br>\n     * Default backtracking consumption time Half an hour ago.\n     */', '    /** 按时间戳回溯消费的起始时刻，格式 yyyyMMddHHmmss；默认半小时前。 */'),
    ('    /**\n     * Queue allocation algorithm specifying how message queues are allocated to each consumer clients.\n     */', '    /** 队列分配策略，决定 Topic 下各队列如何分配给同组消费者。 */'),
    ('    /**\n     * Subscription relationship\n     */', '    /** 订阅关系：topic → 订阅表达式（Tag/SQL）。 */'),
    ('    /**\n     * Message listener\n     */', '    /** 消息监听器（并发或顺序）。 */'),
    ('    /**\n     * Listener to call if message queue assignment is changed.\n     */', '    /** Rebalance 导致队列分配变更时的回调。 */'),
    ('    /**\n     * Offset Storage\n     */', '    /** 消费位点存储（本地/远程）。 */'),
    ('    /**\n     * Minimum consumer thread number\n     */', '    /** 消费线程池最小线程数。 */'),
    ('    /**\n     * Max consumer thread number\n     */', '    /** 消费线程池最大线程数。 */'),
    ('    /**\n     * Threshold for dynamic adjustment of the number of thread pool\n     */', '    /** 动态扩缩消费线程池的队列堆积阈值。 */'),
    ('    /**\n     * Concurrently max span offset.it has no effect on sequential consumption\n     */', '    /** 并发消费时单队列最大位点跨度（顺序消费无效）。 */'),
    ('    /**\n     * Flow control threshold on queue level, each message queue will cache at most 1000 messages by default,\n     * Consider the {@code pullBatchSize}, the instantaneous value may exceed the limit\n     */', '    /** 单队列本地缓存消息条数流控阈值（默认 1000；瞬时可能因 pullBatchSize 超限）。 */'),
    ("    /**\n     * Flow control threshold on queue level, means max num of messages waiting to ack.\n     * in contrast with pull threshold, once a message is popped, it's considered the beginning of consumption.\n     */", '    /** POP 模式单队列待 ACK 消息数流控阈值（POP 即视为开始消费）。 */'),
    ("    /**\n     * Limit the cached message size on queue level, each message queue will cache at most 100 MiB messages by default,\n     * Consider the {@code pullBatchSize}, the instantaneous value may exceed the limit\n     *\n     * <p>\n     * The size(MB) of a message only measured by message body, so it's not accurate\n     */", '    /** 单队列本地缓存消息体大小上限（MiB，默认 100；仅统计 body 大小）。 */'),
    ("    /**\n     * Flow control threshold on topic level, default value is -1(Unlimited)\n     * <p>\n     * The value of {@code pullThresholdForQueue} will be overwritten and calculated based on\n     * {@code pullThresholdForTopic} if it isn't unlimited\n     * <p>\n     * For example, if the value of pullThresholdForTopic is 1000 and 10 message queues are assigned to this consumer,\n     * then pullThresholdForQueue will be set to 100\n     */", '    /** Topic 级消息条数流控（-1 不限）；非 -1 时按分配队列数均摊到 pullThresholdForQueue。 */'),
    ("    /**\n     * Limit the cached message size on topic level, default value is -1 MiB(Unlimited)\n     * <p>\n     * The value of {@code pullThresholdSizeForQueue} will be overwritten and calculated based on\n     * {@code pullThresholdSizeForTopic} if it isn't unlimited\n     * <p>\n     * For example, if the value of pullThresholdSizeForTopic is 1000 MiB and 10 message queues are\n     * assigned to this consumer, then pullThresholdSizeForQueue will be set to 100 MiB\n     */", '    /** Topic 级缓存大小流控（MiB，-1 不限）；非 -1 时均摊到各队列。 */'),
    ('    /**\n     * Message pull Interval\n     */', '    /** 拉取间隔（毫秒），>0 时限流拉取频率。 */'),
    ('    /**\n     * Batch consumption size\n     */', '    /** 单次回调消费的最大消息条数。 */'),
    ('    /**\n     * Batch pull size\n     */', '    /** 单次从 Broker 拉取的最大消息条数。 */'),
    ('    /**\n     * Whether update subscription relationship when every pull\n     */', '    /** 是否每次 Pull 时更新订阅关系。 */'),
    ('    /**\n     * Whether the unit of subscription group\n     */', '    /** 是否为单元化订阅组。 */'),
    ('    /**\n     * Max re-consume times.\n     * In concurrently mode, -1 means 16;\n     * In orderly mode, -1 means Integer.MAX_VALUE.\n     * If messages are re-consumed more than {@link #maxReconsumeTimes} before success.\n     */', '    /** 最大重试次数：并发模式 -1 表示 16，顺序模式 -1 表示 Integer.MAX_VALUE。 */'),
    ('    /**\n     * Suspending pulling time for cases requiring slow pulling like flow-control scenario.\n     */', '    /** 流控等场景下暂停拉取的时长（毫秒）。 */'),
    ('    /**\n     * Maximum amount of time in minutes a message may block the consuming thread.\n     */', '    /** 单条消息允许阻塞消费线程的最长时间（分钟）。 */'),
    ('    /**\n     * Maximum amount of invisible time in millisecond of a message, rang is [5000, 300000]\n     */', '    /** POP 消息不可见时长（毫秒），范围 [5000, 300000]。 */'),
    ('    /**\n     * Batch pop size. range is [1, 32]\n     */', '    /** POP 批量条数，范围 [1, 32]。 */'),
    ('    /**\n     * Maximum time to await message consuming when shutdown consumer, 0 indicates no await.\n     */', '    /** shutdown 时等待在途消费完成的最长时间（毫秒），0 表示不等待。 */'),
    ('    /**\n     * Interface of asynchronous transfer data\n     */', '    /** 消息轨迹异步分发器。 */'),
    ('    // force to use client rebalance', '    // 强制使用客户端 Rebalance'),
    ('    /**\n     * Default constructor.\n     */', '    /** 默认构造：默认消费组 + 平均分配策略。 */'),
    ('    /**\n     * Constructor specifying consumer group.\n     *\n     * @param consumerGroup Consumer group.\n     */', '    /**\n     * 指定消费组构造。\n     *\n     * @param consumerGroup 消费组名\n     */'),
    ('    /**\n     * Constructor specifying RPC hook.\n     *\n     * @param rpcHook RPC hook to execute before each remoting command.\n     */', '    /**\n     * 指定 RPC Hook 构造。\n     *\n     * @param rpcHook 每次 Remoting 请求前执行的 Hook\n     */'),
]

R['client/src/main/java/org/apache/rocketmq/client/consumer/DefaultMQPullConsumer.java'] = [
    ('/**\n * @deprecated Default pulling consumer. This class will be removed in 2022, and a better implementation\n * {@link DefaultLitePullConsumer} is recommend to use in the scenario of actively pulling messages.\n */', '/**\n * @deprecated 传统 Pull 消费者（2022 年后移除），主动拉取场景请改用 {@link DefaultLitePullConsumer}。\n */'),
    ('    /**\n     * Do the same thing for the same Group, the application must be set,and guarantee Globally unique\n     */', '    /** 消费组名，同组须一致且全局唯一。 */'),
    ('    /**\n     * Long polling mode, the Consumer connection max suspend time, it is not recommended to modify\n     */', '    /** 长轮询模式下 Broker 挂起连接的最长时间（毫秒），不建议修改。 */'),
    ('    /**\n     * Long polling mode, the Consumer connection timeout(must greater than brokerSuspendMaxTimeMillis), it is not\n     * recommended to modify\n     */', '    /** 长轮询模式下消费者连接超时（须大于 brokerSuspendMaxTimeMillis），不建议修改。 */'),
    ('    /**\n     * The socket timeout in milliseconds\n     */', '    /** Pull 请求 Socket 超时（毫秒）。 */'),
    ('    /**\n     * Consumption pattern,default is clustering\n     */', '    /** 消费模式，默认 CLUSTERING 集群消费。 */'),
    ('    /**\n     * Message queue listener\n     */', '    /** 队列分配变更监听器。 */'),
    ('    /**\n     * Offset Storage\n     */', '    /** 消费位点存储。 */'),
    ('    /**\n     * Topic set you want to register\n     */', '    /** 待注册订阅的 Topic 集合。 */'),
    ('    /**\n     * Queue allocation algorithm\n     */', '    /** 队列分配算法。 */'),
    ('    /**\n     * Whether the unit of subscription group\n     */', '    /** 是否为单元化订阅组。 */'),
    ('    /**\n     * Constructor specifying namespace, consumer group and RPC hook.\n     *\n     * @param consumerGroup Consumer group.\n     * @param rpcHook RPC hook to execute before each remoting command.\n     */', '    /**\n     * 指定命名空间、消费组与 RPC Hook 构造。\n     *\n     * @param consumerGroup 消费组名\n     * @param rpcHook 每次 Remoting 请求前执行的 Hook\n     */'),
    ('    /**\n     * This method will be removed in a certain version after April 5, 2020, so please do not use this method.\n     */', '    /** @deprecated 2020-04-05 后将移除，请勿使用。 */'),
]

R['client/src/main/java/org/apache/rocketmq/client/consumer/DefaultLitePullConsumer.java'] = [
    ('public class DefaultLitePullConsumer extends ClientConfig implements LitePullConsumer {', '/**\n * Lite Pull 消费者：轻量级主动拉取 API，支持 subscribe/assign、自动/手动提交位点，\n * 适用于需要精确控制拉取节奏的场景。底层由 {@link DefaultLitePullConsumerImpl} 实现。\n */\npublic class DefaultLitePullConsumer extends ClientConfig implements LitePullConsumer {'),
    ('    /**\n     * Consumers belonging to the same consumer group share a group id. The consumers in a group then divides the topic\n     * as fairly amongst themselves as possible by establishing that each queue is only consumed by a single consumer\n     * from the group. If all consumers are from the same group, it functions as a traditional message queue. Each\n     * message would be consumed by one consumer of the group only. When multiple consumer groups exist, the flow of the\n     * data consumption model aligns with the traditional publish-subscribe model. The messages are broadcast to all\n     * consumer groups.\n     */', '    /** 消费组 ID：同组内队列唯一分配，实现负载均衡；多组间为发布订阅模型。 */'),
    ('    /**\n     * Long polling mode, the Consumer connection max suspend time, it is not recommended to modify\n     */', '    /** 长轮询 Broker 挂起最长时间（毫秒），不建议修改。 */'),
    ('    /**\n     * Long polling mode, the Consumer connection timeout(must greater than brokerSuspendMaxTimeMillis), it is not\n     * recommended to modify\n     */', '    /** 长轮询连接超时（须大于 brokerSuspendMaxTimeMillis），不建议修改。 */'),
    ('    /**\n     * The socket timeout in milliseconds\n     */', '    /** Pull Socket 超时（毫秒）。 */'),
    ('    /**\n     * Consumption pattern,default is clustering\n     */', '    /** 消费模式，默认 CLUSTERING。 */'),
    ('    /**\n     * Message queue listener\n     */', '    /** 队列分配变更监听器。 */'),
    ('    /**\n     * Offset Storage\n     */', '    /** 消费位点存储。 */'),
    ('    /**\n     * Queue allocation algorithm\n     */', '    /** 队列分配策略。 */'),
    ('    /**\n     * Whether the unit of subscription group\n     */', '    /** 是否为单元化订阅组。 */'),
    ('    /**\n     * The flag for auto commit offset\n     */', '    /** 是否自动提交消费位点。 */'),
    ('    /**\n     * Pull thread number\n     */', '    /** Pull 工作线程数。 */'),
    ('    /**\n     * Minimum commit offset interval time in milliseconds.\n     */', '    /** 自动提交位点的最小间隔（毫秒）。 */'),
    ('    /**\n     * Maximum commit offset interval time in milliseconds.\n     */', '    /** 自动提交位点的最大间隔（毫秒）。 */'),
    ('    /**\n     * Maximum number of messages pulled each time.\n     */', '    /** 单次拉取最大消息条数。 */'),
    ('    /**\n     * Flow control threshold for consume request, each consumer will cache at most 10000 consume requests by default.\n     * Consider the {@code pullBatchSize}, the instantaneous value may exceed the limit\n     */', '    /** 全局消费请求缓存流控阈值（默认 10000 条）。 */'),
    ('    /**\n     * Consume max span offset.\n     */', '    /** 消费位点最大跨度。 */'),
    ('    /**\n     * Flow control threshold on queue level, each message queue will cache at most 1000 messages by default, Consider\n     * the {@code pullBatchSize}, the instantaneous value may exceed the limit\n     */', '    /** 单队列本地缓存消息条数流控阈值。 */'),
    ("    /**\n     * Limit the cached message size on queue level, each message queue will cache at most 100 MiB messages by default,\n     * Consider the {@code pullBatchSize}, the instantaneous value may exceed the limit\n     *\n     * <p>\n     * The size of a message only measured by message body, so it's not accurate\n     */", '    /** 单队列缓存消息体大小上限（MiB，仅统计 body）。 */'),
    ('    /**\n     * The poll timeout in milliseconds\n     */', '    /** poll() 阻塞超时（毫秒）。 */'),
    ('    /**\n     * Interval time in in milliseconds for checking changes in topic metadata.\n     */', '    /** Topic 元数据变更检测间隔（毫秒）。 */'),
    ('    /**\n     * Backtracking consumption time with second precision. Time format is 20131223171201<br> Implying Seventeen twelve\n     * and 01 seconds on December 23, 2013 year<br> Default backtracking consumption time Half an hour ago.\n     */', '    /** 按时间戳回溯的起始时刻，格式 yyyyMMddHHmmss；默认半小时前。 */'),
    ('    /**\n     * Interface of asynchronous transfer data\n     */', '    /** 消息轨迹分发器。 */'),
    ('    /**\n     * Default constructor.\n     */', '    /** 默认构造。 */'),
    ('    /**\n     * Constructor specifying consumer group.\n     *\n     * @param consumerGroup Consumer group.\n     */', '    /**\n     * 指定消费组构造。\n     *\n     * @param consumerGroup 消费组名\n     */'),
    ('    /**\n     * Constructor specifying RPC hook.\n     *\n     * @param rpcHook RPC hook to execute before each remoting command.\n     */', '    /**\n     * 指定 RPC Hook 构造。\n     *\n     * @param rpcHook Remoting 请求 Hook\n     */'),
    ('    /**\n     * Constructor specifying consumer group, RPC hook\n     *\n     * @param consumerGroup Consumer group.\n     * @param rpcHook       RPC hook to execute before each remoting command.\n     */', '    /**\n     * 指定消费组与 RPC Hook 构造。\n     *\n     * @param consumerGroup 消费组名\n     * @param rpcHook Remoting 请求 Hook\n     */'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/MQAdminImpl.java'] = [
    ('public class MQAdminImpl {', '/**\n * 客户端管理 API 实现：创建 Topic、查询路由/位点、按时间检索 offset、\n * 消息查询等，供 Producer/Consumer 及 tools 模块调用。\n */\npublic class MQAdminImpl {'),
    ('    private final MQClientInstance mQClientFactory;', '    /** 所属 MQClientInstance 工厂。 */\n    private final MQClientInstance mQClientFactory;'),
    ('    private long timeoutMillis = 6000;', '    /** Remoting 调用默认超时（毫秒）。 */\n    private long timeoutMillis = 6000;'),
    ('    public void createTopic(String key, String newTopic, int queueNum) throws MQClientException {', '    /** 在 key 对应路由的各 Master Broker 上创建 Topic。 */\n    public void createTopic(String key, String newTopic, int queueNum) throws MQClientException {'),
    ('    public List<MessageQueue> fetchPublishMessageQueues(String topic) throws MQClientException {', '    /** 获取 Topic 可用于发布的 MessageQueue 列表（去 namespace）。 */\n    public List<MessageQueue> fetchPublishMessageQueues(String topic) throws MQClientException {'),
    ('    public Set<MessageQueue> fetchSubscribeMessageQueues(String topic) throws MQClientException {', '    /** 获取 Topic 可用于订阅的 MessageQueue 集合。 */\n    public Set<MessageQueue> fetchSubscribeMessageQueues(String topic) throws MQClientException {'),
    ('        // default return lower boundary offset when there are more than one offsets.', '        // 多个 offset 匹配时默认返回下界（最早）'),
    ('    public long searchOffset(MessageQueue mq, long timestamp, BoundaryType boundaryType) throws MQClientException {', '    /** 按时间戳在指定队列上检索消费位点（支持 UPPER/LOWER 边界）。 */\n    public long searchOffset(MessageQueue mq, long timestamp, BoundaryType boundaryType) throws MQClientException {'),
    ('    public long maxOffset(MessageQueue mq) throws MQClientException {', '    /** 查询队列最大 offset。 */\n    public long maxOffset(MessageQueue mq) throws MQClientException {'),
    ('    public long minOffset(MessageQueue mq) throws MQClientException {', '    /** 查询队列最小 offset。 */\n    public long minOffset(MessageQueue mq) throws MQClientException {'),
    ('    public QueryResult queryMessage(String topic, String key, int maxNum, long begin,\n        long end) throws MQClientException,\n        InterruptedException {', '    /** 按 topic/key/时间范围查询历史消息。 */\n    public QueryResult queryMessage(String topic, String key, int maxNum, long begin,\n        long end) throws MQClientException,\n        InterruptedException {'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/MQClientAPIImpl.java'] = [
    ('public class MQClientAPIImpl implements NameServerUpdateCallback, StartAndShutdown {', '/**\n * RocketMQ 客户端 Remoting API 核心实现：封装与 NameServer/Broker 的全部 RPC，\n * 包括发送、Pull/POP、位点管理、事务、管理命令等。单实例对应一个 RemotingClient。\n */\npublic class MQClientAPIImpl implements NameServerUpdateCallback, StartAndShutdown {'),
    ('    private static boolean sendSmartMsg =', '    /** 是否启用智能消息发送优化（系统属性控制）。 */\n    private static boolean sendSmartMsg ='),
    ('    private final RemotingClient remotingClient;', '    /** 底层 Netty Remoting 客户端。 */\n    private final RemotingClient remotingClient;'),
    ('    private final TopAddressing topAddressing;', '    /** HTTP 方式获取 NameServer 地址列表。 */\n    private final TopAddressing topAddressing;'),
    ('    private final ClientRemotingProcessor clientRemotingProcessor;', '    /** 处理 Broker 主动下发的请求（事务回查、消费组变更等）。 */\n    private final ClientRemotingProcessor clientRemotingProcessor;'),
    ('    private String nameSrvAddr = null;', '    /** 当前 NameServer 地址（可动态更新）。 */\n    private String nameSrvAddr = null;'),
    ('    private ClientConfig clientConfig;', '    /** 客户端配置引用。 */\n    private ClientConfig clientConfig;'),
    ('        // Inject stream rpc hook first to make reserve field signature', '        // 先注入流式 RPC Hook，保证扩展字段签名顺序'),
    ('    public List<String> getNameServerAddressList() {', '    /** 返回当前 NameServer 地址列表。 */\n    public List<String> getNameServerAddressList() {'),
    ('    public void updateNameServerAddressList(final String addrs) {', '    /** 更新 NameServer 地址列表（TopAddressing 回调）。 */\n    public void updateNameServerAddressList(final String addrs) {'),
    ('    public void start() {', '    /** 启动 RemotingClient。 */\n    public void start() {'),
    ('    public void shutdown() {', '    /** 关闭 RemotingClient。 */\n    public void shutdown() {'),
    ('    public SendResult sendMessage(', '    /** 同步/异步/单向发送消息到 Broker。 */\n    public SendResult sendMessage('),
    ('    public PullResult pullMessage(', '    /** 从 Broker Pull 消息（支持长轮询与过滤）。 */\n    public PullResult pullMessage('),
    ('    public void popMessageAsync(', '    /** 异步 POP 消息；结果通过 PopCallback 回调。 */\n    public void popMessageAsync('),
    ('    public void popLiteMessageAsync(', '    /** 异步 Lite POP 消息。 */\n    public void popLiteMessageAsync('),
    ('    public void ackMessageAsync(', '    /** 异步 ACK POP 消息。 */\n    public void ackMessageAsync('),
    ('    public void batchAckMessageAsync(', '    /** 异步批量 ACK POP 消息。 */\n    public void batchAckMessageAsync('),
    ('    public void changeInvisibleTimeAsync(//', '    /** 异步修改 POP 消息不可见时间。 */\n    public void changeInvisibleTimeAsync(//'),
    ('            // This means it is not an inner batch', '            // 非内部批量消息'),
    ('        // it is a pop command if pop time greater than 0, we should set the check point info to extraInfo field', '        // popTime>0 为 POP 命令，须将 checkpoint 写入 extraInfo'),
    ('                    // we should set the check point info to extraInfo field , if the command is popMsg', '                    // POP 命令须将 checkpoint 写入 extraInfo'),
    ('                    // find pop ck offset', '                    // 解析 POP checkpoint offset'),
    ('                            // process LMQ', '                            // Lite/LMQ 多队列分发处理'),
    ('                            // LMQ topic has only 1 queue, which queue id is 0', '                            // LMQ topic 仅 1 个队列，queueId 恒为 0'),
    ('    /**\n     * Build queue offset sorted map\n     *\n     * @param topic pop consumer topic\n     * @param msgFoundList popped message list\n     * @return sorted map, key is topicMark@queueId, value is sorted msg queueOffset list\n     */', '    /**\n     * 构建 POP 结果的 queue offset 有序映射。\n     *\n     * @param topic POP 消费 topic\n     * @param msgFoundList 已 POP 消息列表\n     * @return key 为 topicMark@queueId，value 为有序 queueOffset 列表\n     */'),
    ('                // process LMQ', '                // LMQ 多队列 offset 解析'),
    ('                // LMQ topic has only 1 queue, which queue id is 0', '                // LMQ 仅 queueId=0'),
    ('            // Value of POP_CK is used to determine whether it is a pop retry,', '            // PROPERTY_POP_CK 用于判定是否为 POP 重试（topic 可能被 Broker 改写）'),
    ('    public MessageExt viewMessage(final String addr, final String topic, final long phyoffset, final long timeoutMillis)', '    /** 按物理 offset 查看单条消息详情。 */\n    public MessageExt viewMessage(final String addr, final String topic, final long phyoffset, final long timeoutMillis)'),
    ('                //If namespace not null , reset Topic without namespace.', '                // 有 namespace 时还原为用户 topic'),
    ('        // default return lower boundary offset when there are more than one offsets.', '        // 多 offset 匹配时默认返回下界'),
    ('    public long getMaxOffset(final String addr, final MessageQueue messageQueue, final long timeoutMillis)', '    /** 查询队列最大 offset。 */\n    public long getMaxOffset(final String addr, final MessageQueue messageQueue, final long timeoutMillis)'),
    ('    public long getMinOffset(final String addr, final MessageQueue messageQueue, final long timeoutMillis)', '    /** 查询队列最小 offset。 */\n    public long getMinOffset(final String addr, final MessageQueue messageQueue, final long timeoutMillis)'),
    ('    public long queryConsumerOffset(', '    /** 向 Broker 查询消费组在指定队列上的已提交 offset。 */\n    public long queryConsumerOffset('),
    ('    public void updateConsumerOffset(', '    /** 同步更新消费位点到 Broker。 */\n    public void updateConsumerOffset('),
    ('    public void endTransactionOneway(', '    /** 单向发送事务 commit/rollback 请求。 */\n    public void endTransactionOneway('),
    ('        // offset is -1 means offset is null', '        // offset 为 -1 表示 null'),
    ('                    // fill dataVersion before break the loop to compatible with old version server', '                    // 退出循环前填充 dataVersion，兼容旧版 Broker'),
    ("                    // the server side don't support totalGroupNum, all data is returned", '                    // 服务端不支持分页，一次返回全部消费组'),
    ("                    // the server side don't support totalTopicNum, all data is returned", '                    // 服务端不支持 Topic 分页，一次返回全部'),
    ('        // Get controller leader address.', '        // 获取 Controller Leader 地址'),
    ('    public GroupForbidden updateAndGetGroupForbidden(String addr, UpdateGroupForbiddenRequestHeader requestHeader,', '    /** 更新并获取消费组禁发/禁订状态。 */\n    public GroupForbidden updateAndGetGroupForbidden(String addr, UpdateGroupForbiddenRequestHeader requestHeader,'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/admin/MqClientAdminImpl.java'] = [
    ('public class MqClientAdminImpl implements MqClientAdmin {', '/**\n * 客户端管理接口 {@link MqClientAdmin} 的 Remoting 实现：\n * 消息查询、消费统计、消费组管理、Topic 运维等异步 CompletableFuture API。\n */\npublic class MqClientAdminImpl implements MqClientAdmin {'),
    ('    private final RemotingClient remotingClient;', '    /** 共享 Remoting 客户端。 */\n    private final RemotingClient remotingClient;'),
    ('    public CompletableFuture<List<MessageExt>> queryMessage(String address, boolean uniqueKeyFlag, boolean decompressBody,', '    /** 异步查询消息；支持按 uniqKey 或普通 key 过滤。 */\n    public CompletableFuture<List<MessageExt>> queryMessage(String address, boolean uniqueKeyFlag, boolean decompressBody,'),
    ('    public CompletableFuture<TopicStatsTable> getTopicStatsInfo(String address,', '    /** 异步获取 Topic 消费/生产统计。 */\n    public CompletableFuture<TopicStatsTable> getTopicStatsInfo(String address,'),
    ('    public CompletableFuture<ConsumeStats> getConsumeStats(String address,', '    /** 异步获取消费组堆积与 TPS 统计。 */\n    public CompletableFuture<ConsumeStats> getConsumeStats(String address,'),
    ('    public CompletableFuture<ConsumerConnection> getConsumerConnectionList(String address,', '    /** 异步查询消费组在线连接与订阅。 */\n    public CompletableFuture<ConsumerConnection> getConsumerConnectionList(String address,'),
    ('    public CompletableFuture<ConsumerRunningInfo> getConsumerRunningInfo(String address,', '    /** 异步获取消费者运行时信息（线程池、订阅、位点等）。 */\n    public CompletableFuture<ConsumerRunningInfo> getConsumerRunningInfo(String address,'),
    ('    public CompletableFuture<Map<MessageQueue, Long>> invokeBrokerToResetOffset(String address,', '    /** 异步调用 Broker 重置消费位点。 */\n    public CompletableFuture<Map<MessageQueue, Long>> invokeBrokerToResetOffset(String address,'),
    ('    public CompletableFuture<TopicList> queryTopicsByConsumer(String address,', '    /** 异步查询指定消费组订阅的 Topic 列表。 */\n    public CompletableFuture<TopicList> queryTopicsByConsumer(String address,'),
    ('    public CompletableFuture<ClusterInfo> getBrokerClusterInfo(String address, long timeoutMillis) {', '    /** 异步从 NameServer 获取集群路由信息。 */\n    public CompletableFuture<ClusterInfo> getBrokerClusterInfo(String address, long timeoutMillis) {'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java'] = [
    ('public class ConsumeMessageConcurrentlyService implements ConsumeMessageService {', '/**\n * Push 并发消费服务：线程池调度 {@link ConsumeConcurrentlyRequest}，\n * 调用 {@link MessageListenerConcurrently} 并处理 RECONSUME_LATER/SUCCESS。\n */\npublic class ConsumeMessageConcurrentlyService implements ConsumeMessageService {'),
    ('    private final DefaultMQPushConsumerImpl defaultMQPushConsumerImpl;', '    /** 所属 Push 消费者实现。 */\n    private final DefaultMQPushConsumerImpl defaultMQPushConsumerImpl;'),
    ('    private final MessageListenerConcurrently messageListener;', '    /** 用户注册的并发监听器。 */\n    private final MessageListenerConcurrently messageListener;'),
    ('    private final BlockingQueue<Runnable> consumeRequestQueue;', '    /** 消费任务队列。 */\n    private final BlockingQueue<Runnable> consumeRequestQueue;'),
    ('    private final ThreadPoolExecutor consumeExecutor;', '    /** 消费工作线程池。 */\n    private final ThreadPoolExecutor consumeExecutor;'),
    ('    private final ScheduledExecutorService scheduledExecutorService;', '    /** 定时任务（清理过期消息等）。 */\n    private final ScheduledExecutorService scheduledExecutorService;'),
    ('    private final ScheduledExecutorService cleanExpireMsgExecutors;', '    /** 过期消息清理专用调度器。 */\n    private final ScheduledExecutorService cleanExpireMsgExecutors;'),
    ('                    // Maybe message is expired and cleaned, just ignore it.', '                    // 消息可能已过期被清理，忽略'),
    ('        // Wrap topic with namespace before sending back message.', '        // SendBack 前为 topic 包装 namespace'),
    ('    public void submitConsumeRequest(', '    /** 提交一批消息到消费线程池。 */\n    public void submitConsumeRequest('),
    ('    public void submitPopConsumeRequest(', '    /** 提交 POP 模式消费请求。 */\n    public void submitPopConsumeRequest('),
    ('    public void shutdown(long awaitTerminateMillis) {', '    /** 关闭线程池并等待在途任务。 */\n    public void shutdown(long awaitTerminateMillis) {'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageOrderlyService.java'] = [
    ('public class ConsumeMessageOrderlyService implements ConsumeMessageService {', '/**\n * Push 顺序消费服务：按 MessageQueue 加锁保证单队列串行，\n * 调用 {@link MessageListenerOrderly}，支持 SUSPEND/SUCCESS。\n */\npublic class ConsumeMessageOrderlyService implements ConsumeMessageService {'),
    ('    private final static long MAX_TIME_CONSUME_CONTINUOUSLY =', '    /** 单队列连续消费最长时间（毫秒），超时释放锁避免饿死。 */\n    private final static long MAX_TIME_CONSUME_CONTINUOUSLY ='),
    ('    private final MessageQueueLock messageQueueLock = new MessageQueueLock();', '    /** 队列级互斥锁，保证顺序消费。 */\n    private final MessageQueueLock messageQueueLock = new MessageQueueLock();'),
    ('    private volatile boolean stopped = false;', '    /** 服务是否已停止。 */\n    private volatile boolean stopped = false;'),
    ('    private final DefaultMQPushConsumerImpl defaultMQPushConsumerImpl;', '    /** 所属 Push 消费者实现。 */\n    private final DefaultMQPushConsumerImpl defaultMQPushConsumerImpl;'),
    ('    private final MessageListenerOrderly messageListener;', '    /** 用户注册的顺序监听器。 */\n    private final MessageListenerOrderly messageListener;'),
    ('    private final ThreadPoolExecutor consumeExecutor;', '    /** 消费线程池（每队列串行）。 */\n    private final ThreadPoolExecutor consumeExecutor;'),
    ('    public void submitConsumeRequest(', '    /** 提交顺序消费请求（同队列互斥）。 */\n    public void submitConsumeRequest('),
    ('    public void submitPopConsumeRequest(', '    /** 提交 POP 顺序消费请求。 */\n    public void submitPopConsumeRequest('),
    ('    public void shutdown(long awaitTerminateMillis) {', '    /** 关闭服务并释放队列锁。 */\n    public void shutdown(long awaitTerminateMillis) {'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopConcurrentlyService.java'] = [
    ('public class ConsumeMessagePopConcurrentlyService implements ConsumeMessageService {', '/**\n * POP 并发消费服务：消费 POP 拉取的消息，成功后异步 ACK，\n * 失败则修改不可见时间或 SendBack 重试。\n */\npublic class ConsumeMessagePopConcurrentlyService implements ConsumeMessageService {'),
    ('    private final DefaultMQPushConsumerImpl defaultMQPushConsumerImpl;', '    /** 所属 Push 消费者实现。 */\n    private final DefaultMQPushConsumerImpl defaultMQPushConsumerImpl;'),
    ('    private final MessageListenerConcurrently messageListener;', '    /** 并发消息监听器。 */\n    private final MessageListenerConcurrently messageListener;'),
    ('    private final ThreadPoolExecutor consumeExecutor;', '    /** POP 消费线程池。 */\n    private final ThreadPoolExecutor consumeExecutor;'),
    ('    public void submitPopConsumeRequest(', '    /** 提交 POP 并发消费任务。 */\n    public void submitPopConsumeRequest('),
    ('    public void shutdown(long awaitTerminateMillis) {', '    /** 关闭 POP 消费线程池。 */\n    public void shutdown(long awaitTerminateMillis) {'),
    ('    class ConsumeRequest implements Runnable {', '    /** 单次 POP 批次消费任务。 */\n    class ConsumeRequest implements Runnable {'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessagePopOrderlyService.java'] = [
    ('public class ConsumeMessagePopOrderlyService implements ConsumeMessageService {', '/**\n * POP 顺序消费服务：按队列加锁串行处理 POP 消息，\n * 保证同队列 FIFO 语义。\n */\npublic class ConsumeMessagePopOrderlyService implements ConsumeMessageService {'),
    ('    private final ConcurrentSet<ConsumeRequest> consumeRequestSet = new ConcurrentSet<>();', '    /** 进行中的 POP 顺序消费请求集合。 */\n    private final ConcurrentSet<ConsumeRequest> consumeRequestSet = new ConcurrentSet<>();'),
    ('    private final MessageQueueLock messageQueueLock = new MessageQueueLock();', '    /** 队列消费互斥锁。 */\n    private final MessageQueueLock messageQueueLock = new MessageQueueLock();'),
    ('    private final MessageQueueLock consumeRequestLock = new MessageQueueLock();', '    /** 消费请求提交互斥锁。 */\n    private final MessageQueueLock consumeRequestLock = new MessageQueueLock();'),
    ('    private volatile boolean stopped = false;', '    /** 服务停止标志。 */\n    private volatile boolean stopped = false;'),
    ('    private final MessageListenerOrderly messageListener;', '    /** 顺序消息监听器。 */\n    private final MessageListenerOrderly messageListener;'),
    ('    public void submitPopConsumeRequest(', '    /** 提交 POP 顺序消费请求。 */\n    public void submitPopConsumeRequest('),
    ('    public void shutdown(long awaitTerminateMillis) {', '    /** 关闭 POP 顺序消费服务。 */\n    public void shutdown(long awaitTerminateMillis) {'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultLitePullConsumerImpl.java'] = [
    ('public class DefaultLitePullConsumerImpl implements MQConsumerInner {', '/**\n * {@link DefaultLitePullConsumer} 内部实现：管理 subscribe/assign、\n * Pull 任务调度、位点提交与 Rebalance。\n */\npublic class DefaultLitePullConsumerImpl implements MQConsumerInner {'),
    ('    private static final String NOT_RUNNING_EXCEPTION_MESSAGE = "The consumer not running, please start it first.";', '    /** 消费者未启动时的异常提示。 */\n    private static final String NOT_RUNNING_EXCEPTION_MESSAGE = "The consumer not running, please start it first.";'),
    ('    private static final String SUBSCRIPTION_CONFLICT_EXCEPTION_MESSAGE = "Subscribe and assign are mutually exclusive.";', '    /** subscribe 与 assign 互斥时的异常提示。 */\n    private static final String SUBSCRIPTION_CONFLICT_EXCEPTION_MESSAGE = "Subscribe and assign are mutually exclusive.";'),
    ('    /**\n     * the type of subscription\n     */', '    /** 订阅类型：NONE / SUBSCRIBE / ASSIGN。 */'),
    ('    // only for test purpose, will be modified by reflection in unit test.', '    // 仅测试用，单测中通过反射修改'),
    ('        // If subscribe function invoke before start function, then update topic subscribe info after initialization.', '        // start 前已 subscribe 则在初始化后更新订阅信息'),
    ('        // If assign function invoke before start function, then update pull task after initialization.', '        // start 前已 assign 则在初始化后更新 Pull 任务'),
    ('        // Check consumerGroup', '        // 校验 consumerGroup 非空'),
    ('        // Check consumerGroup name is not equal default consumer group name.', '        // 禁止使用默认消费组名'),
    ('        // Check messageModel is not null.', '        // 校验 messageModel'),
    ('        // Check allocateMessageQueueStrategy is not null', '        // 校验队列分配策略非空'),
    ('                //If namespace not null , reset Topic without namespace.', '                // 有 namespace 时还原 topic'),
    ('    /**\n     * Delay some time when exception occur\n     */', '    /** Pull 异常后的退避延迟（毫秒）。 */'),
    ('    /**\n     * Flow control interval when message cache is full\n     */', '    /** 本地缓存满时的流控间隔（毫秒）。 */'),
    ('    /**\n     * Flow control interval when broker return flow control\n     */', '    /** Broker 流控时的退避间隔（毫秒）。 */'),
    ('    /**\n     * Delay some time when suspend pull service\n     */', '    /** 暂停 Pull 时的延迟（毫秒）。 */'),
    ('    /**\n     * subscribe data by customizing messageQueueListener\n     *\n     * @param topic\n     * @param subExpression\n     * @param messageQueueListener\n     * @throws MQClientException\n     */', '    /**\n     * 订阅 Topic 并注册自定义 {@link MessageQueueListener}。\n     *\n     * @param topic Topic 名称\n     * @param subExpression 订阅表达式\n     * @param messageQueueListener 队列变更回调\n     * @throws MQClientException 订阅冲突或参数非法\n     */'),
    ('    /**\n     * Specify offset commit\n     *\n     * @param messageQueues\n     * @param persist\n     */', '    /**\n     * 手动提交指定队列的消费位点。\n     *\n     * @param messageQueues 队列 → offset 映射\n     * @param persist 是否持久化到 Broker\n     */'),
    ('    /**\n     * Get the queue assigned in subscribe mode\n     *\n     * @return\n     */', '    /**\n     * 获取 subscribe 模式下当前分配的队列集合。\n     *\n     * @return 已分配 MessageQueue 集合\n     */'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPullConsumerImpl.java'] = [
    ('/**\n * This class will be removed in 2022, and a better implementation {@link DefaultLitePullConsumerImpl} is recommend to use\n * in the scenario of actively pulling messages.\n */', '/**\n * @deprecated 传统 Pull 实现（2022 后移除），请改用 {@link DefaultLitePullConsumerImpl}。\n */'),
    ('    private final DefaultMQPullConsumer defaultMQPullConsumer;', '    /** 关联的 Pull 消费者门面。 */\n    private final DefaultMQPullConsumer defaultMQPullConsumer;'),
    ('    private PullAPIWrapper pullAPIWrapper;', '    /** 封装 Pull 请求与长轮询。 */\n    private PullAPIWrapper pullAPIWrapper;'),
    ('    private RebalanceImpl rebalanceImpl = new RebalancePullImpl(this);', '    /** Pull 模式 Rebalance 实现。 */\n    private RebalanceImpl rebalanceImpl = new RebalancePullImpl(this);'),
    ('        // check if has info in memory, otherwise invoke api.', '        // 内存无路由则调用 NameServer API'),
    ('        //If namespace is not null , reset Topic without namespace.', '        // 有 namespace 时还原 topic'),
    ('        // check consumerGroup', '        // 校验 consumerGroup'),
    ('        // consumerGroup', '        // 消费组名校验'),
    ('        // messageModel', '        // 消费模式校验'),
    ('        // allocateMessageQueueStrategy', '        // 队列分配策略校验'),
    ("    //Don't use this deprecated setter, which will be removed soon.", '    // 勿用此已废弃 setter，即将移除'),
    ('    public PullResult pullBlockIfNotFound(MessageQueue mq, String subExpression, long offset, int maxNums)', '    /** 阻塞 Pull：无消息时长轮询直至有数据或超时。 */\n    public PullResult pullBlockIfNotFound(MessageQueue mq, String subExpression, long offset, int maxNums)'),
    ('    public PullResult pull(MessageQueue mq, String subExpression, long offset, int maxNums)', '    /** 非阻塞 Pull 一次。 */\n    public PullResult pull(MessageQueue mq, String subExpression, long offset, int maxNums)'),
]

R['client/src/main/java/org/apache/rocketmq/client/impl/consumer/DefaultMQPushConsumerImpl.java'] = [
    ('    /**\n     * Delay some time when exception occur\n     */', '    /** Pull 异常后的退避延迟（毫秒）。 */'),
    ('    /**\n     * Flow control interval when message cache is full\n     */', '    /** 本地消息缓存满时的流控间隔（毫秒）。 */'),
    ('    /**\n     * Flow control interval when broker return flow control\n     */', '    /** Broker 返回流控时的退避间隔（毫秒）。 */'),
    ('    /**\n     * Delay some time when suspend pull service\n     */', '    /** 暂停 Pull 时的延迟（毫秒）。 */'),
    ('    private final RebalanceImpl rebalanceImpl = new RebalancePushImpl(this);', '    /** Push 模式 Rebalance 实现。 */\n    private final RebalanceImpl rebalanceImpl = new RebalancePushImpl(this);'),
    ('    private PullAPIWrapper pullAPIWrapper;', '    /** Pull API 封装（Push 底层仍用 Pull）。 */\n    private PullAPIWrapper pullAPIWrapper;'),
    ('    private ConsumeMessageService consumeMessageService;', '    /** Pull 模式消费服务（并发/顺序）。 */\n    private ConsumeMessageService consumeMessageService;'),
    ('    private ConsumeMessageService consumeMessagePopService;', '    /** POP 模式消费服务。 */\n    private ConsumeMessageService consumeMessagePopService;'),
    ('    //10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h', '    // POP 延迟级别（秒）：10s 30s 1m … 2h'),
    ('    // only for test purpose, will be modified by reflection in unit test.', '    // 仅单测用，反射可修改'),
    ('        //POPTODO think of pop mode orderly implementation later.', '        // POPTODO：POP 顺序模式待完善'),
    ('            //here the broker should be polished', '            // TODO：Broker 侧逻辑待优化'),
    ('        // default reconsume times: 16', '        // 默认最大重试 16 次'),
    ('                    //POPTODO reuse Executor ?', '                    // POPTODO：是否复用 Executor'),
    ('                // POPTODO', '                // POPTODO 待实现'),
    ('        // allocateMessageQueueStrategy', '        // 校验队列分配策略'),
    ('        // subscription', '        // 校验订阅关系'),
    ('        // messageListener', '        // 校验消息监听器'),
    ('        // consumeThreadMin', '        // 校验最小消费线程数'),
    ('        // consumeThreadMax', '        // 校验最大消费线程数'),
    ("        // consumeThreadMin can't be larger than consumeThreadMax", '        // consumeThreadMin 不能大于 consumeThreadMax'),
    ('        // consumeConcurrentlyMaxSpan', '        // 校验并发最大跨度'),
    ('        // pullThresholdForQueue', '        // 校验单队列流控阈值'),
    ('        // pullThresholdForTopic', '        // 校验 Topic 级流控'),
    ('        // pullThresholdSizeForQueue', '        // 校验单队列大小流控'),
    ('            // pullThresholdSizeForTopic', '            // 校验 Topic 级大小流控'),
    ('        // pullInterval', '        // 校验拉取间隔'),
    ('        // consumeMessageBatchMaxSize', '        // 校验批量消费大小'),
    ('        // pullBatchSize', '        // 校验 Pull 批量大小'),
    ('        // popInvisibleTime', '        // 校验 POP 不可见时间'),
    ('        // popBatchNums', '        // 校验 POP 批量条数'),
    ('                                        // removeProcessQueue will also remove offset to cancel the frozen status.', '                                        // removeProcessQueue 同时移除位点以解除冻结'),
    ('    public synchronized void start() throws MQClientException {', '    /** 启动消费者：注册 Client、Rebalance、Pull 与消费服务。 */\n    public synchronized void start() throws MQClientException {'),
    ('    public void shutdown() {', '    /** 关闭消费者并释放资源。 */\n    public void shutdown() {'),
    ('    public void pullMessage(final PullRequest pullRequest) {', '    /** Pull 循环入口：拉取消息并提交消费服务。 */\n    public void pullMessage(final PullRequest pullRequest) {'),
    ('    void popMessage(final PopRequest popRequest) {', '    /** POP 循环入口：POP 消息并提交 POP 消费服务。 */\n    void popMessage(final PopRequest popRequest) {'),
]
