"""Chinese JavaDoc replacements for RocketMQ wave41a store/timer/tieredstore [0:15]."""

R: dict[str, list[tuple[str, str]]] = {
    'store/src/main/java/org/apache/rocketmq/store/timer/TimerWheel.java': [
        ('/**\n     * Perform backup operation.\n     * <p>\n     * Select snapshot file based on the provided flag, write current buffer content to a temporary file,\n     * then rename the temporary file to the formal snapshot file. If rename fails, delete the temporary file.\n     * Finally clean up expired snapshot files.\n     *\n     * @param flushWhere Flag used to select snapshot file.\n     * @throws IOException If I/O error occurs during backup process.\n     */',
         '/**\n\n     * 执行时间轮快照备份：按 flag 选择快照文件，写入临时文件后原子重命名。\n * @param flushWhere 用于选择快照文件的 flag\n * @throws IOException 备份过程 I/O 异常\n     * <p>\n     * Select snapshot file based on the provided flag, write current buffer content to a temporary file,\n     * then rename the temporary file to the formal snapshot file. If rename fails, delete the temporary file.\n     * Finally clean up expired snapshot files.\n     *\n     * @param flushWhere Flag used to select snapshot file.\n     * @throws IOException 备份过程 I/O 异常\n     \n     */'),
        ('/**\n     * Clean up expired snapshot files.\n     * <p>\n     * This method will find and delete all snapshot files with flags smaller than the specified value\n     * under the current file name, keeping the two snapshot files with the largest flags.\n     */',
         '/**\n\n     * 清理过期快照：删除 flag 较小的快照文件，保留 flag 最大的两个。\n     * <p>\n     * This method will find and delete all snapshot files with flags smaller than the specified value\n     * under the current file name, keeping the two snapshot files with the largest flags.\n     \n     */'),
        ('/**\n     * Select snapshot file name based on flag.\n     *\n     * @param flag Flag used to select or identify snapshot file.\n     * @return Name of the snapshot file.\n     */',
         '/**\n\n     * 根据 flag 选择快照文件名。\n * @param flag 快照标识 flag\n * @return 快照文件路径\n     *\n     * @param flag Flag used to select or identify snapshot file.\n     * @return 快照文件路径\n     \n     */'),
        ('/**\n     * Get the maximum flag from existing snapshot files.\n     *\n     * @return The maximum flag value, or -1 if no snapshot files exist\n     */',
         '/**\n\n     * 获取已有快照文件中的最大 flag。\n * @return 最大 flag，无快照时返回 -1\n     *\n     * @return 最大 flag，无快照时返回 -1\n     \n     */'),
        ('public void putSlot(long timeMs, long firstPos, long lastPos, int num, int magic) {',
         '    /** 写入槽位及计数与魔数。 */\n    public void putSlot(long timeMs, long firstPos, long lastPos, int num, int magic) {'),
        ('public void reviseSlot(long timeMs, long firstPos, long lastPos, boolean force) {',
         '    /** 修正槽位偏移，可选强制覆盖。 */\n    public void reviseSlot(long timeMs, long firstPos, long lastPos, boolean force) {'),
        ('public TimerWheel(String fileName, int slotsTotal, int precisionMs)',
         '    /** 构造时间轮（无快照偏移）。 */\n    public TimerWheel(String fileName, int slotsTotal, int precisionMs)'),
        ('public void putSlot(long timeMs, long firstPos, long lastPos) {',
         '    /** 写入槽位首尾物理偏移。 */\n    public void putSlot(long timeMs, long firstPos, long lastPos) {'),
        ('public static long getMaxSnapshotFlag(String timerWheelPath)',
         '    /** 返回时间轮目录下最大快照 flag。 */\n    public static long getMaxSnapshotFlag(String timerWheelPath)'),
        ('public long checkPhyPos(long timeStartMs, long maxOffset) {',
         '    /** 检查时间轮存储偏移是否超过 TimerLog 最大偏移。 */\n    public long checkPhyPos(long timeStartMs, long maxOffset) {'),
        ('    public static final String TIMER_WHEEL_FILE_NAME =',
         '    /** 时间轮文件名前缀。 */\n    public static final String TIMER_WHEEL_FILE_NAME ='),
        ('    public static final int BLANK = -1, IGNORE = -2;',
         '    /** 槽位空白/忽略占位常量。 */\n    public static final int BLANK = -1, IGNORE = -2;'),
        ('    private final MappedByteBuffer mappedByteBuffer;',
         '    /** mmap 映射的时间轮文件缓冲。 */\n    private final MappedByteBuffer mappedByteBuffer;'),
        ('/**\n     * Wrapper class for file and flag\n     */',
         '/**\n\n     * 快照文件与 flag 的包装类\n     \n     */'),
        ('public long getAllNum(long timeStartMs) {',
         '    /** 统计从起始时间起的槽位消息总数。 */\n    public long getAllNum(long timeStartMs) {'),
        ('    private final ByteBuffer byteBuffer;',
         '    /** 堆外 Direct 缓冲，读写槽位数据。 */\n    private final ByteBuffer byteBuffer;'),
        ('public int getSlotIndex(long timeMs) {',
         '    /** 计算时间对应的槽位索引。 */\n    public int getSlotIndex(long timeMs) {'),
        ('    private static final Logger log =',
         '    /** 存储模块日志。 */\n    private static final Logger log ='),
        ('public void shutdown(boolean flush) {',
         '    /** 关闭时间轮，可选是否刷盘。 */\n    public void shutdown(boolean flush) {'),
        ('public Slot getRawSlot(long timeMs) {',
         '    /** 读取原始槽位数据（测试用）。 */\n    public Slot getRawSlot(long timeMs) {'),
        ('public void cleanExpiredSnapshot() {',
         '    /** 清理过期快照文件。 */\n    public void cleanExpiredSnapshot() {'),
        ('public void backup(long flushWhere)',
         '    /** 按 flag 备份时间轮到快照文件。 */\n    public void backup(long flushWhere)'),
        ('public Slot getSlot(long timeMs) {',
         '    /** 按毫秒时间获取槽位（精度对齐）。 */\n    public Slot getSlot(long timeMs) {'),
        ('    public final int precisionMs;',
         '    /** 槽位时间精度（毫秒）。 */\n    public final int precisionMs;'),
        ('public long getNum(long timeMs) {',
         '    /** 返回指定时间槽位的消息计数。 */\n    public long getNum(long timeMs) {'),
        ('    public final int slotsTotal;',
         '    /** 时间轮槽位总数（实际索引为 2 倍）。 */\n    public final int slotsTotal;'),
        ('public String getFileName() {',
         '    /** 返回时间轮文件路径。 */\n    public String getFileName() {'),
        ('public void shutdown() {',
         '    /** 关闭全部线程池。 */\n    public void shutdown() {'),
        ('public class TimerWheel',
         '/**\n * 定时消息时间轮：基于 mmap/堆外缓冲管理槽位，支持快照备份与恢复。\n */\npublic class TimerWheel'),
        ('public void flush() {',
         '    /** 将 Direct 缓冲变更同步到 mmap 并 force。 */\n    public void flush() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/timer/rocksdb/TimerRocksDBRecord.java': [
        ('public static TimerRocksDBRecord decode(byte[] key, byte[] value) {',
         '    /** 从 key/value 解码 Timer 记录。 */\n    public static TimerRocksDBRecord decode(byte[] key, byte[] value) {'),
        ('    public static final byte TIMER_ROCKSDB_DELETE =',
         '    /** RocksDB 删除操作标志。 */\n    public static final byte TIMER_ROCKSDB_DELETE ='),
        ('    public static final byte TIMER_ROCKSDB_UPDATE =',
         '    /** RocksDB 更新操作标志。 */\n    public static final byte TIMER_ROCKSDB_UPDATE ='),
        ('    public static final byte TIMER_ROCKSDB_PUT =',
         '    /** RocksDB 写入操作标志。 */\n    public static final byte TIMER_ROCKSDB_PUT ='),
        ('    private static final Logger logError =',
         '    /** 存储错误日志。 */\n    private static final Logger logError ='),
        ('    private MessageExt messageExt;',
         '    /** 关联的消息体（可选）。 */\n    private MessageExt messageExt;'),
        ('public class TimerRocksDBRecord',
         '/**\n * Timer RocksDB 键值记录：序列化延迟时间、唯一键与 CommitLog 物理位置。\n */\npublic class TimerRocksDBRecord'),
        ('public byte[] getValueBytes() {',
         '    /** 序列化为 RocksDB value 字节。 */\n    public byte[] getValueBytes() {'),
        ('    private long queueOffset;',
         '    /** 消费队列逻辑偏移。 */\n    private long queueOffset;'),
        ('public byte[] getKeyBytes() {',
         '    /** 序列化为 RocksDB key 字节。 */\n    public byte[] getKeyBytes() {'),
        ('    private long checkPoint;',
         '    /** 检查点偏移。 */\n    private long checkPoint;'),
        ('    private byte actionFlag;',
         '    /** 操作类型标志（put/delete/update）。 */\n    private byte actionFlag;'),
        ('    private long delayTime;',
         '    /** 延迟触发时间戳。 */\n    private long delayTime;'),
        ('    private String uniqKey;',
         '    /** 定时消息唯一键。 */\n    private String uniqKey;'),
        ('    private long offsetPy;',
         '    /** CommitLog 物理偏移。 */\n    private long offsetPy;'),
        ('    private int sizePy;',
         '    /** CommitLog 消息体大小。 */\n    private int sizePy;'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/transaction/TransMessageRocksDBStore.java': [
        ('public Integer getCheckTimes(String topic, String uniqKey, Long offsetPy) {',
         '    /** 查询事务消息回查次数。 */\n    public Integer getCheckTimes(String topic, String uniqKey, Long offsetPy)'),
        ('    protected BlockingQueue<TransRocksDBRecord> originTransMsgQueue;',
         '    /** 待构建事务索引的记录队列。 */\n    protected BlockingQueue<TransRocksDBRecord> originTransMsgQueue;'),
        ('public void buildTransIndex(DispatchRequest dispatchRequest) {',
         '    /** 从 CommitLog 分发请求构建事务索引记录。 */\n    public void buildTransIndex(DispatchRequest dispatchRequest) {'),
        ('public void deletePrepareMessage(MessageExt messageExt) {',
         '    /** 写入 op 半消息删除 prepare 消息。 */\n    public void deletePrepareMessage(MessageExt messageExt) {'),
        ('public MessageExt getMessage(long offsetPy, int sizePy) {',
         '    /** 按物理偏移与大小读取 CommitLog 消息。 */\n    public MessageExt getMessage(long offsetPy, int sizePy) {'),
        ('    private static final int DEFAULT_CAPACITY =',
         '    /** 事务索引构建队列默认容量。 */\n    private static final int DEFAULT_CAPACITY ='),
        ('    private static final String REMOVE_TAG =',
         '    /** 删除半事务消息的操作 Tag。 */\n    private static final String REMOVE_TAG ='),
        ('    private static final Logger logError =',
         '    /** 存储错误日志。 */\n    private static final Logger logError ='),
        ('    private static final int BATCH_SIZE =',
         '    /** 批量写入 RocksDB 的批大小。 */\n    private static final int BATCH_SIZE ='),
        ('public class TransMessageRocksDBStore',
         '/**\n * 基于 RocksDB 的事务消息存储：从 CommitLog 分发构建事务索引并异步写入 RocksDB。\n */\npublic class TransMessageRocksDBStore'),
        ('    private static final Logger log =',
         '    /** 存储模块日志。 */\n    private static final Logger log ='),
        ('public void shutdown() {',
         '    /** 关闭全部线程池。 */\n    public void shutdown() {'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/transaction/TransRocksDBRecord.java': [
        ('public static TransRocksDBRecord decode(byte[] key, byte[] value) {',
         '    /** 从 key/value 解码事务记录。 */\n    public static TransRocksDBRecord decode(byte[] key, byte[] value) {'),
        ('    private static final String KEY_SPLIT =',
         '    /** 事务 key 中 topic 与 uniqKey 分隔符。 */\n    private static final String KEY_SPLIT ='),
        ('    private static final Logger logError =',
         '    /** 存储错误日志。 */\n    private static final Logger logError ='),
        ('    public static final int VALUE_LENGTH =',
         '    /** RocksDB value 固定长度。 */\n    public static final int VALUE_LENGTH ='),
        ('    private MessageExt messageExt;',
         '    /** 关联的消息体（可选）。 */\n    private MessageExt messageExt;'),
        ('public class TransRocksDBRecord',
         '/**\n * 事务 RocksDB 记录：编码 topic、uniqKey、物理偏移与回查次数。\n */\npublic class TransRocksDBRecord'),
        ('    private int checkTimes = 0;',
         '    /** 事务回查次数。 */\n    private int checkTimes = 0;'),
        ('public byte[] getValueBytes() {',
         '    /** 序列化为 RocksDB value 字节。 */\n    public byte[] getValueBytes() {'),
        ('public byte[] getKeyBytes() {',
         '    /** 序列化为 RocksDB key 字节。 */\n    public byte[] getKeyBytes() {'),
        ('    private String uniqKey;',
         '    /** 定时消息唯一键。 */\n    private String uniqKey;'),
        ('    private boolean delete;',
         '    /** 是否标记删除。 */\n    private boolean delete;'),
        ('    private boolean isOp;',
         '    /** 是否为操作（op）半消息。 */\n    private boolean isOp;'),
        ('    private int sizePy;',
         '    /** CommitLog 消息体大小。 */\n    private int sizePy;'),
    ],
    'store/src/main/java/org/apache/rocketmq/store/util/LibC.java': [
        ('    /* invalidate mappings & caches */',
         '    /** 使映射与缓存失效。 */\n    /* invalidate mappings & caches */'),
        ('    /* sync memory asynchronously */',
         '    /** 异步同步内存到磁盘。 */\n    /* sync memory asynchronously */'),
        ('    /* synchronous memory sync */',
         '    /** 同步刷盘内存映射。 */\n    /* synchronous memory sync */'),
        ('    int MADV_WILLNEED = 3;',
         '    /** madvise 预读提示。 */\n    int MADV_WILLNEED = 3;'),
        ('    int MADV_DONTNEED = 4;',
         '    /** madvise 释放页缓存提示。 */\n    int MADV_DONTNEED = 4;'),
        ('    int MS_SYNC = 0x0004;',
         '    /** msync 同步刷盘标志。 */\n    int MS_SYNC = 0x0004;'),
        ('    int MADV_NORMAL = 0;',
         '    /** madvise 正常访问模式。 */\n    int MADV_NORMAL = 0;'),
        ('    int MADV_RANDOM = 1;',
         '    /** madvise 随机访问模式。 */\n    int MADV_RANDOM = 1;'),
        ('public interface LibC',
         '/**\n * JNA 封装的 libc 接口：提供 mlock、madvise、msync 等内存映射系统调用。\n */\npublic interface LibC'),
        ('    LibC INSTANCE =',
         '    /** libc 单例实例。 */\n    LibC INSTANCE ='),
    ],
    'store/src/main/java/org/apache/rocketmq/store/util/PerfCounter.java': [
        ('    private final AtomicInteger[] count;',
         '    /** 按耗时索引的计数桶数组。 */\n    private final AtomicInteger[] count;'),
        ('    private final AtomicLong allCount;',
         '    /** 当前窗口累计计数。 */\n    private final AtomicLong allCount;'),
        ('    private String prefix = "DEFAULT";',
         '    /** 日志前缀标识。 */\n    private String prefix = "DEFAULT";'),
        ('public void flow(long cost, int num) {',
         '    /** 记录指定数量的耗时样本。 */\n    public void flow(long cost, int num) {'),
        ('public void flow(long cost) {',
         '    /** 记录一次耗时样本。 */\n    public void flow(long cost) {'),
        ('public float getLastTps() {',
         '    /** 返回最近一次统计窗口 TPS。 */\n    public float getLastTps() {'),
        ('public void startTick() {',
         '    /** 开始计时采样。 */\n    public void startTick() {'),
        ('public class PerfCounter',
         '/**\n * 延迟分布性能计数器：按耗时桶统计 TPS 与 TP 分位值。\n */\npublic class PerfCounter'),
        ('public void endTick() {',
         '    /** 结束计时并记录耗时。 */\n    public void endTick() {'),
        ('public void print() {',
         '    /** 输出 TP 分位与延迟分布统计。 */\n    public void print() {'),
        ('public void reset() {',
         '    /** 重置计数桶与窗口。 */\n    public void reset() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/MessageStoreExecutor.java': [
        ('    public final BlockingQueue<Runnable> bufferCommitThreadPoolQueue;',
         '    /** 缓冲提交线程池任务队列。 */\n    public final BlockingQueue<Runnable> bufferCommitThreadPoolQueue;'),
        ('    public final ScheduledExecutorService commonExecutor;',
         '    /** 分层存储通用调度线程池。 */\n    public final ScheduledExecutorService commonExecutor;'),
        ('    public final ExecutorService bufferCommitExecutor;',
         '    /** 缓冲提交线程池。 */\n    public final ExecutorService bufferCommitExecutor;'),
        ('public static MessageStoreExecutor getInstance() {',
         '    /** 返回单例执行器。 */\n    public static MessageStoreExecutor getInstance() {'),
        ('public class MessageStoreExecutor',
         '/**\n * 分层存储线程池单例：管理缓冲提交/拉取与文件回收执行器。\n */\npublic class MessageStoreExecutor'),
        ('public void shutdown() {',
         '    /** 关闭全部线程池。 */\n    public void shutdown() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/AppendResult.java': [
        ('/**\n     * An unknown error occurred during the append operation.\n     */',
         '/**\n\n     * 追加过程中发生未知错误。\n     \n     */'),
        ('/**\n     * The buffer used for the append operation is full.\n     */',
         '/**\n\n     * 追加缓冲区已满。\n     \n     */'),
        ('/**\n     * The file is closed and cannot accept more data.\n     */',
         '/**\n\n     * 文件已关闭，无法接受数据。\n     \n     */'),
        ('/**\n     * The file is full and cannot accept more data.\n     */',
         '/**\n\n     * 文件已满，无法继续写入。\n     \n     */'),
        ('/**\n     * The append operation was successful.\n     */',
         '/**\n\n     * 追加写入成功。\n     \n     */'),
        ('    UNKNOWN_ERROR',
         '    /** 未知错误。 */\n    UNKNOWN_ERROR'),
        ('    BUFFER_FULL,',
         '    /** 追加缓冲区已满。 */\n    BUFFER_FULL,'),
        ('    FILE_CLOSED,',
         '    /** 文件已关闭。 */\n    FILE_CLOSED,'),
        ('    FILE_FULL,',
         '    /** 文件已满。 */\n    FILE_FULL,'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/FileSegmentType.java': [
        ('public static FileSegmentType valueOf(int fileType) {',
         '    /** 按编码解析文件段类型。 */\n    public static FileSegmentType valueOf(int fileType)'),
        ('public enum FileSegmentType',
         '/**\n * 分层存储文件段类型：CommitLog、ConsumeQueue 或 Index。\n */\npublic enum FileSegmentType'),
        ('public int getCode() {',
         '    /** 返回文件段类型编码。 */\n    public int getCode() {'),
        ('    CONSUME_QUEUE(1),',
         '    /** ConsumeQueue 文件段。 */\n    CONSUME_QUEUE(1),'),
        ('    COMMIT_LOG(0),',
         '    /** CommitLog 文件段。 */\n    COMMIT_LOG(0),'),
        ('    INDEX(2);',
         '    /** Index 文件段。 */\n    INDEX(2);'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/GetMessageResultExt.java': [
        ('/**\n     * Due to the message fetched from the object storage is sequential,\n     * do message filtering occurs after the data retrieval.\n     */',
         '/**\n\n     * 对象存储按序拉取消息，过滤在数据读取完成后执行。\n * @param messageFilter 消息过滤器\n * @return 过滤后的拉取结果\n     * do message filtering occurs after the data retrieval.\n     \n     */'),
        ('public void addMessageExt(SelectMappedBufferResult bufferResult, long queueOffset, long tagCode) {',
         '    /** 添加消息并记录 tagCode。 */\n    public void addMessageExt(SelectMappedBufferResult bufferResult, long queueOffset, long tagCode) {'),
        ('public GetMessageResult doFilterMessage(MessageFilter messageFilter) {',
         '    /** 对顺序拉取结果执行 CQ/CommitLog 过滤。 */\n    public GetMessageResult doFilterMessage(MessageFilter messageFilter) {'),
        ('    private final List<Long> tagCodeList;',
         '    /** 与消息列表对应的 Tag 哈希码。 */\n    private final List<Long> tagCodeList;'),
        ('public List<Long> getTagCodeList() {',
         '    /** 返回 tagCode 列表。 */\n    public List<Long> getTagCodeList() {'),
        ('public class GetMessageResultExt',
         '/**\n * 扩展拉取结果：携带 tagCode 列表，支持对象存储顺序读取后的过滤。\n */\npublic class GetMessageResultExt'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/GroupCommitContext.java': [
        ('    private List<SelectMappedBufferResult> bufferList;',
         '    /** 待释放的映射缓冲列表。 */\n    private List<SelectMappedBufferResult> bufferList;'),
        ('    private List<DispatchRequest> dispatchRequests;',
         '    /** 组提交产生的 DispatchRequest 列表。 */\n    private List<DispatchRequest> dispatchRequests;'),
        ('public void setEndOffset(long endOffset) {',
         '    /** 设置组提交结束偏移。 */\n    public void setEndOffset(long endOffset)'),
        ('public class GroupCommitContext',
         '/**\n * 分层存储组提交上下文：聚合待上传缓冲与 DispatchRequest。\n */\npublic class GroupCommitContext'),
        ('public long getEndOffset() {',
         '    /** 返回组提交结束偏移。 */\n    public long getEndOffset() {'),
        ('    private long endOffset;',
         '    /** 组提交结束的消费队列偏移。 */\n    private long endOffset;'),
        ('public void release() {',
         '    /** 释放缓冲并清空请求列表。 */\n    public void release() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/common/SelectBufferResult.java': [
        ('    private final ByteBuffer byteBuffer;',
         '    /** 堆外 Direct 缓冲，读写槽位数据。 */\n    private final ByteBuffer byteBuffer;'),
        ('public AtomicLong getAccessCount() {',
         '    /** 返回访问计数器。 */\n    public AtomicLong getAccessCount() {'),
        ('public ByteBuffer getByteBuffer() {',
         '    /** 返回消息 ByteBuffer。 */\n    public ByteBuffer getByteBuffer() {'),
        ('public class SelectBufferResult',
         '/**\n * 分层存储选缓冲结果：封装 ByteBuffer、偏移、大小与 tagCode。\n */\npublic class SelectBufferResult'),
        ('    private final long tagCode;',
         '    /** 消息 Tag 哈希码。 */\n    private final long tagCode;'),
        ('public long getStartOffset() {',
         '    /** 返回起始物理偏移。 */\n    public long getStartOffset() {'),
        ('public long getTagCode() {',
         '    /** 返回 Tag 哈希码。 */\n    public long getTagCode() {'),
        ('public int getSize() {',
         '    /** 返回消息大小。 */\n    public int getSize() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcher.java': [
        ('CompletableFuture<Boolean> doScheduleDispatch(FlatFileInterface flatFile, boolean force);',
         '    /** 调度异步组提交上传。 */\n    CompletableFuture<Boolean> doScheduleDispatch(FlatFileInterface flatFile, boolean force);'),
        ('public interface MessageStoreDispatcher',
         '/**\n * 分层存储 CommitLog 分发器：调度异步上传与组提交。\n */\npublic interface MessageStoreDispatcher'),
        ('void shutdown();',
         '    /** 关闭分发服务。 */\n    void shutdown();'),
        ('void start();',
         '    /** 启动分发服务。 */\n    void start();'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreDispatcherImpl.java': [
        ('/**\n     * Building indexes with offsetId is no longer supported because offsetId has changed in tiered storage\n     */',
         '/**\n\n     * 分层存储中 offsetId 已变更，不再支持基于 offsetId 建索引。\n * @param topicId Topic 数值 ID\n * @param request 分发请求\n     \n     */'),
        ('public void constructIndexFile(long topicId, GroupCommitContext groupCommitContext) {',
         '    /** 异步构建索引文件并释放上下文。 */\n    public void constructIndexFile(long topicId, GroupCommitContext groupCommitContext) {'),
        ('    protected final Map<FlatFileInterface, GroupCommitContext> failedGroupCommitMap;',
         '    /** 组提交失败时缓存的上下文。 */\n    protected final Map<FlatFileInterface, GroupCommitContext> failedGroupCommitMap;'),
        ('public CompletableFuture<Boolean> commitAsync(FlatFileInterface flatFile) {',
         '    /** 异步提交 FlatFile 到对象存储。 */\n    public CompletableFuture<Boolean> commitAsync(FlatFileInterface flatFile)'),
        ('public void constructIndexFile0(long topicId, DispatchRequest request) {',
         '    /** 为单条 DispatchRequest 写入索引 key。 */\n    public void constructIndexFile0(long topicId, DispatchRequest request) {'),
        ('public void dispatchWithSemaphore(FlatFileInterface flatFile) {',
         '    /** 在信号量控制下触发分发。 */\n    public void dispatchWithSemaphore(FlatFileInterface flatFile) {'),
        ('    protected final TieredMessageStore messageStore;',
         '    /** 所属分层 MessageStore。 */\n    protected final TieredMessageStore messageStore;'),
        ('    protected final FlatFileStore flatFileStore;',
         '    /** 扁平文件存储。 */\n    protected final FlatFileStore flatFileStore;'),
        ('public void dispatch(DispatchRequest request) {',
         '    /** 接收 CommitLog 分发并注册 FlatFile。 */\n    public void dispatch(DispatchRequest request) {'),
        ('public void releaseClosedPendingGroupCommit() {',
         '    /** 释放已关闭 FlatFile 的挂起组提交上下文。 */\n    public void releaseClosedPendingGroupCommit() {'),
        ('    protected final Semaphore semaphore;',
         '    /** 限制并发分发任务数。 */\n    protected final Semaphore semaphore;'),
        ('public class MessageStoreDispatcherImpl',
         '/**\n * 分层存储分发实现：扫描本地 CQ 并组提交到对象存储，失败时缓存上下文。\n */\npublic class MessageStoreDispatcherImpl'),
        ('public class MessageStoreDispatcher',
         '/**\n * 分层存储 CommitLog 分发器：调度异步上传与组提交。\n */\npublic class MessageStoreDispatcher'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFetcher.java': [
        ('/**\n     * Asynchronous get message\n     *\n     * @param group         Consumer group that launches this query.\n     * @param topic         Topic to query.\n     * @param queueId       Queue ID to query.\n     * @param offset        Logical offset to start from.\n     * @param maxCount      Maximum count of messages to query.\n     * @param messageFilter Message filter used to screen desired messages.\n     * @return Matched messages.\n     */',
         '/**\n\n     * 异步拉取消息。\n     *\n     * @param group 发起查询的消费者组。\n     * @param topic 待查询 Topic。\n     * @param queueId 待查询队列 ID。\n     * @param offset 起始逻辑偏移。\n     * @param maxCount 最多拉取消息条数。\n     * @param messageFilter 消息过滤器。\n     * @return 匹配的消息结果。\n     \n     */'),
        ('/**\n     * Asynchronous query messages by given key.\n     *\n     * @param topic    Topic of the message.\n     * @param key      Message key.\n     * @param maxCount Maximum count of the messages possible.\n     * @param begin    Begin timestamp.\n     * @param end      End timestamp.\n     */',
         '/**\n\n     * 按 key 异步查询消息。\n     *\n     * @param topic 消息 Topic。\n     * @param key 消息 Key。\n     * @param maxCount 最多返回消息条数。\n     * @param begin 起始时间戳。\n     * @param end 结束时间戳。\n     \n     */'),
        ('/**\n     * Look up the physical offset of the message whose store timestamp is as specified.\n     *\n     * @param topic     Topic of the message.\n     * @param queueId   Queue ID.\n     * @param timestamp Timestamp to look up.\n     * @return physical offset which matches.\n     */',
         '/**\n\n     * 按存储时间戳查找匹配的消费队列偏移。\n     *\n     * @param topic 消息 Topic。\n     * @param queueId 队列 ID。\n     * @param timestamp 待查找的时间戳。\n     * @return 匹配的消费队列偏移。\n     \n     */'),
        ('/**\n     * Asynchronous get the store time of the message specified.\n     *\n     * @param topic              Message topic.\n     * @param queueId            Queue ID.\n     * @param consumeQueueOffset Consume queue offset.\n     * @return store timestamp of the message.\n     */',
         '/**\n\n     * 异步获取指定消费队列偏移对应消息的存储时间戳。\n     *\n     * @param topic 消息 Topic。\n     * @param queueId 队列 ID。\n     * @param consumeQueueOffset 消费队列逻辑偏移。\n     * @return 消息存储时间戳。\n     \n     */'),
        ('/**\n     * Asynchronous get the store time of the earliest message in this store.\n     *\n     * @return timestamp of the earliest message in this store.\n     */',
         '/**\n\n     * 异步获取该队列最早消息的存储时间戳。\n     *\n     * @return 该 Store 中最早消息存储时间戳\n     \n     */'),
        ('CompletableFuture<Long> getEarliestMessageTimeAsync(String topic, int queueId);',
         '    /** 异步获取最早消息存储时间。 */\n    CompletableFuture<Long> getEarliestMessageTimeAsync(String topic, int queueId);'),
        ('CompletableFuture<QueryMessageResult> queryMessageAsync(',
         '    /** 按 key 异步查询消息。 */\n    CompletableFuture<QueryMessageResult> queryMessageAsync('),
        ('CompletableFuture<GetMessageResult> getMessageAsync(',
         '    /** 异步拉取消息。 */\n    CompletableFuture<GetMessageResult> getMessageAsync('),
        ('public interface MessageStoreFetcher',
         '/**\n * 分层存储异步消息拉取接口：支持按时间/偏移查询与 key 检索。\n */\npublic interface MessageStoreFetcher'),
    ],
}
