"""Chinese JavaDoc replacements for RocketMQ wave44a tools [0:15]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/DeleteSubscriptionGroupCommand.java': [
        ('public class DeleteSubscriptionGroupCommand implements SubCommand {',
         '/**\n * deleteSubGroup 子命令：从 Broker 或集群删除订阅组（消费组）。\n * <p>集群模式下可同时清理重试 Topic 与死信 Topic。\n */\npublic class DeleteSubscriptionGroupCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Delete subscription group from broker.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Delete subscription group from broker.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "delete subscription group from which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "delete subscription group from which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("g", "groupName", true, "subscription group name");',
         '        opt = new Option("g", "groupName", true, "待删除的订阅组（消费组）名称");'),
        ('        opt = new Option("r", "removeOffset", true, "remove offset");',
         '        opt = new Option("r", "removeOffset", true, "是否同时删除消费位点（true/false）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并在目标 Broker 或集群上删除订阅组。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            // groupName\n            String groupName = commandLine.getOptionValue(\'g\').trim();',
         '            // 解析订阅组名与是否清理位点\n            String groupName = commandLine.getOptionValue(\'g\').trim();'),
        ('                Set<String> masterSet = CommandUtil.fetchMasterAddrByClusterName(adminExt, clusterName);',
         '                // 集群模式：遍历各 Master Broker 删除订阅组\n                Set<String> masterSet = CommandUtil.fetchMasterAddrByClusterName(adminExt, clusterName);'),
        ('                try {\n                    adminExt.deleteTopic(MixAll.RETRY_GROUP_TOPIC_PREFIX + groupName, clusterName);',
         '                // 清理该消费组对应的重试 Topic 与死信 Topic\n                try {\n                    adminExt.deleteTopic(MixAll.RETRY_GROUP_TOPIC_PREFIX + groupName, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/GetConsumerConfigSubCommand.java': [
        ('public class GetConsumerConfigSubCommand implements SubCommand {',
         '/**\n * getConsumerConfig 子命令：按订阅组名查询各 Broker 上的消费组配置。\n * <p>通过反射打印 {@link SubscriptionGroupConfig} 全部非空字段。\n */\npublic class GetConsumerConfigSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get consumer config by subscription group name.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get consumer config by subscription group name.";'),
        ('        Option opt = new Option("g", "groupName", true, "subscription group name");',
         '        Option opt = new Option("g", "groupName", true, "待查询的订阅组（消费组）名称");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历集群全部 Broker，拉取并打印订阅组配置字段。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            for (Entry<String, BrokerData> brokerEntry : clusterInfo.getBrokerAddrTable().entrySet()) {',
         '            // 遍历路由表中的每个 Broker\n            for (Entry<String, BrokerData> brokerEntry : clusterInfo.getBrokerAddrTable().entrySet()) {'),
        ('                Field[] fields = config.getClass().getDeclaredFields();',
         '                // 反射遍历配置对象全部字段并打印\n                Field[] fields = config.getClass().getDeclaredFields();'),
        ('    private String getClusterName(String brokeName, Map<String, Set<String>> clusterAddrTable) {',
         '    /** 根据 Broker 名反查所属集群名。 */\n    private String getClusterName(String brokeName, Map<String, Set<String>> clusterAddrTable) {'),
        ('class ConsumerConfigInfo {',
         '/** 封装单个 Broker 上的消费组配置查询结果。 */\nclass ConsumerConfigInfo {'),
        ('    public ConsumerConfigInfo(String clusterName, String brokerName, SubscriptionGroupConfig subscriptionGroupConfig) {',
         '    /** 构造消费组配置信息条目。 */\n    public ConsumerConfigInfo(String clusterName, String brokerName, SubscriptionGroupConfig subscriptionGroupConfig) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/SetConsumeModeSubCommand.java': [
        ('public class SetConsumeModeSubCommand implements SubCommand {',
         '/**\n * setConsumeMode 子命令：为指定 Topic 与消费组设置消息拉取模式（PULL/POP）。\n * <p>POP 模式可配置共享队列数量 popShareQueueNum。\n */\npublic class SetConsumeModeSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Set consume message mode. pull/pop etc.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Set consume message mode. pull/pop etc.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "create subscription group to which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "create subscription group to which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("t", "topicName", true, "topic name");',
         '        opt = new Option("t", "topicName", true, "Topic 名称");'),
        ('        opt = new Option("g", "groupName", true, "consumer group name");',
         '        opt = new Option("g", "groupName", true, "消费组名称");'),
        ('        opt = new Option("m", "mode", true, "consume mode. PULL/POP");',
         '        opt = new Option("m", "mode", true, "消费模式：PULL 或 POP");'),
        ('        opt = new Option("q", "popShareQueueNum", true, "num of queue which share in pop mode");',
         '        opt = new Option("q", "popShareQueueNum", true, "POP 模式下共享队列数量（可选）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)\n            throws SubCommandException {',
         '    /** 解析 CLI 参数并调用 setMessageRequestMode 设置消费模式。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)\n            throws SubCommandException {'),
        ('                Set<String> masterSet =\n                        CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历各 Master Broker 设置消费模式\n                Set<String> masterSet =\n                        CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/StartMonitoringSubCommand.java': [
        ('public class StartMonitoringSubCommand implements SubCommand {',
         '/**\n * startMonitoring 子命令：启动 RocketMQ 集群监控服务。\n * <p>使用默认 {@link MonitorConfig} 与 {@link DefaultMonitorListener} 持续采集指标。\n */\npublic class StartMonitoringSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Start Monitoring.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Start Monitoring.";'),
        ('    public Options buildCommandlineOptions(Options options) {\n        return options;',
         '    /** 本命令无需额外 CLI 参数。 */\n    public Options buildCommandlineOptions(Options options) {\n        return options;'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 创建并启动 {@link MonitorService}，阻塞运行直至异常退出。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            MonitorService monitorService =\n                new MonitorService(new MonitorConfig(), new DefaultMonitorListener(), rpcHook);',
         '            // 以默认配置与监听器启动监控服务\n            MonitorService monitorService =\n                new MonitorService(new MonitorConfig(), new DefaultMonitorListener(), rpcHook);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/UpdateSubGroupListSubCommand.java': [
        ('public class UpdateSubGroupListSubCommand implements SubCommand {',
         '/**\n * updateSubGroupList 子命令：从 JSON 文件批量创建或更新订阅组配置。\n * <p>文件内容为 {@link SubscriptionGroupConfig} 数组。\n */\npublic class UpdateSubGroupListSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update or create subscription group in batch";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update or create subscription group in batch";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "create groups to which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "create groups to which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("f", "filename", true,\n            "Path to a file with a list of org.apache.rocketmq.remoting.protocol.subscription.SubscriptionGroupConfig in json format");',
         '        opt = new Option("f", "filename", true,\n            "订阅组配置 JSON 文件路径（SubscriptionGroupConfig 数组）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 读取 JSON 文件并批量提交订阅组配置到 Broker 或集群。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            final List<SubscriptionGroupConfig> groupConfigs = JSON.parseArray(groupConfigListBytes, SubscriptionGroupConfig.class);',
         '            // 解析 JSON 为订阅组配置列表\n            final List<SubscriptionGroupConfig> groupConfigs = JSON.parseArray(groupConfigListBytes, SubscriptionGroupConfig.class);'),
        ('                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：向各 Master Broker 批量提交配置\n                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/consumer/UpdateSubGroupSubCommand.java': [
        ('public class UpdateSubGroupSubCommand implements SubCommand {',
         '/**\n * updateSubGroup 子命令：创建或更新单个订阅组（消费组）配置。\n * <p>支持消费开关、广播/顺序消费、重试策略及自定义属性等参数。\n */\npublic class UpdateSubGroupSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update or create subscription group.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update or create subscription group.";'),
        ('        Option opt = new Option("b", "brokerAddr", true, "create subscription group to which broker");',
         '        Option opt = new Option("b", "brokerAddr", true, "目标 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("c", "clusterName", true, "create subscription group to which cluster");',
         '        opt = new Option("c", "clusterName", true, "目标集群名（与 -b 二选一）");'),
        ('        opt = new Option("g", "groupName", true, "consumer group name");',
         '        opt = new Option("g", "groupName", true, "消费组名称");'),
        ('        opt = new Option("s", "consumeEnable", true, "consume enable");',
         '        opt = new Option("s", "consumeEnable", true, "是否允许消费（true/false）");'),
        ('        opt = new Option("m", "consumeFromMinEnable", true, "from min offset");',
         '        opt = new Option("m", "consumeFromMinEnable", true, "是否从最小位点开始消费");'),
        ('        opt = new Option("d", "consumeBroadcastEnable", true, "broadcast");',
         '        opt = new Option("d", "consumeBroadcastEnable", true, "是否启用广播消费");'),
        ('        opt = new Option("o", "consumeMessageOrderly", true, "consume message orderly");',
         '        opt = new Option("o", "consumeMessageOrderly", true, "是否顺序消费消息");'),
        ('        opt = new Option("q", "retryQueueNums", true, "retry queue nums");',
         '        opt = new Option("q", "retryQueueNums", true, "重试队列数量");'),
        ('        opt = new Option("r", "retryMaxTimes", true, "retry max times");',
         '        opt = new Option("r", "retryMaxTimes", true, "最大重试次数");'),
        ('        opt = new Option(null, "attributes", true, "attribute(+a=b,+c=d,-e)");',
         '        opt = new Option(null, "attributes", true, "自定义属性（+a=b,+c=d,-e 格式）");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数构建 SubscriptionGroupConfig 并提交到 Broker 或集群。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            // groupName\n            subscriptionGroupConfig.setGroupName(commandLine.getOptionValue(\'g\').trim());',
         '            // 设置消费组名称\n            subscriptionGroupConfig.setGroupName(commandLine.getOptionValue(\'g\').trim());'),
        ('                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：向各 Master Broker 提交订阅组配置\n                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/container/AddBrokerSubCommand.java': [
        ('public class AddBrokerSubCommand implements SubCommand {',
         '/**\n * addBroker 子命令：向 Broker 容器（Container）动态添加 Broker 实例。\n * <p>通过指定配置文件路径启动新的 Broker 进程。\n */\npublic class AddBrokerSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Add a broker to specified container.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Add a broker to specified container.";'),
        ('        Option opt = new Option("c", "brokerContainerAddr", true, "Broker container address");',
         '        Option opt = new Option("c", "brokerContainerAddr", true, "Broker 容器地址");'),
        ('        opt = new Option("b", "brokerConfigPath", true, "Broker config path");',
         '        opt = new Option("b", "brokerConfigPath", true, "新 Broker 配置文件路径");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并调用 addBrokerToContainer 动态添加 Broker。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/container/RemoveBrokerSubCommand.java': [
        ('public class RemoveBrokerSubCommand implements SubCommand {',
         '/**\n * removeBroker 子命令：从 Broker 容器中移除指定 Broker 实例。\n * <p>通过 clusterName:brokerName:brokerId 三元组标识目标 Broker。\n */\npublic class RemoveBrokerSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Remove a broker from specified container.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Remove a broker from specified container.";'),
        ('        Option opt = new Option("c", "brokerContainerAddr", true, "Broker container address");',
         '        Option opt = new Option("c", "brokerContainerAddr", true, "Broker 容器地址");'),
        ('        opt = new Option("b", "brokerIdentity", true, "Information to identify a broker: clusterName:brokerName:brokerId(dLedgerId for dLedger)");',
         '        opt = new Option("b", "brokerIdentity", true, "Broker 标识：clusterName:brokerName:brokerId（dLedger 用 dLedgerId）");'),
        ('    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 Broker 标识并调用 removeBrokerFromContainer 移除实例。 */\n    public void execute(CommandLine commandLine, Options options,\n        RPCHook rpcHook) throws SubCommandException {'),
        ('            String[] brokerIdentities = commandLine.getOptionValue(\'b\').trim().split(":");',
         '            // 解析 clusterName:brokerName:brokerId 三元组\n            String[] brokerIdentities = commandLine.getOptionValue(\'b\').trim().split(":");'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/controller/CleanControllerBrokerMetaSubCommand.java': [
        ('public class CleanControllerBrokerMetaSubCommand implements SubCommand {',
         '/**\n * cleanBrokerMetadata 子命令：清理 Controller 上指定 Broker 副本的元数据。\n * <p>可指定待清理的 brokerControllerId 列表，或清理存活 Broker。\n */\npublic class CleanControllerBrokerMetaSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Clean metadata of broker on controller.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Clean metadata of broker on controller.";'),
        ('        Option opt = new Option("a", "controllerAddress", true, "The address of controller");',
         '        Option opt = new Option("a", "controllerAddress", true, "Controller 节点地址");'),
        ('        opt = new Option("b", "brokerControllerIdsToClean", true, "The brokerController id list which requires to clean metadata. eg: 1;2;3, means that clean broker-1, broker-2 and broker-3");',
         '        opt = new Option("b", "brokerControllerIdsToClean", true, "待清理的 brokerControllerId 列表，如 1;2;3");'),
        ('        opt = new Option("bn", "brokerName", true, "The broker name of the replicas that require to be manipulated");',
         '        opt = new Option("bn", "brokerName", true, "待操作的 Broker 副本组名称");'),
        ('        opt = new Option("c", "clusterName", true, "The clusterName of broker");',
         '        opt = new Option("c", "clusterName", true, "Broker 所属集群名（非存活清理时必填）");'),
        ('        opt = new Option("l", "cleanLivingBroker", false, "Whether clean up living brokers,default value is false");',
         '        opt = new Option("l", "cleanLivingBroker", false, "是否清理存活 Broker 元数据（默认 false）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 校验参数并调用 cleanControllerBrokerData 清理 Controller 元数据。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('        if (!isCleanLivingBroker && StringUtils.isEmpty(clusterName)) {',
         '        // 非存活清理模式下 clusterName 不能为空\n        if (!isCleanLivingBroker && StringUtils.isEmpty(clusterName)) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerConfigSubCommand.java': [
        ('public class GetControllerConfigSubCommand implements SubCommand {',
         '/**\n * getControllerConfig 子命令：查询 Controller 集群的运行配置。\n * <p>支持传入多个 Controller 地址（分号分隔）。\n */\npublic class GetControllerConfigSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get controller config.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get controller config.";'),
        ('        Option opt = new Option("a", "controllerAddress", true, "Controller address list, eg: 192.168.0.1:9878;192.168.0.2:9878");',
         '        Option opt = new Option("a", "controllerAddress", true, "Controller 地址列表，如 192.168.0.1:9878;192.168.0.2:9878");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取各 Controller 配置并以键值对形式打印。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {'),
        ('            // servers\n            String servers = commandLine.getOptionValue(\'a\');',
         '            // 解析分号分隔的 Controller 地址列表\n            String servers = commandLine.getOptionValue(\'a\');'),
        ('            Map<String, Properties> controllerConfigs = defaultMQAdminExt.getControllerConfig(serverList);',
         '            // 向各 Controller 拉取配置\n            Map<String, Properties> controllerConfigs = defaultMQAdminExt.getControllerConfig(serverList);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/controller/GetControllerMetaDataSubCommand.java': [
        ('public class GetControllerMetaDataSubCommand implements SubCommand {',
         '/**\n * getControllerMetaData 子命令：查询 Controller 集群元数据。\n * <p>输出 Controller 组名、Leader 信息及 Peer 列表。\n */\npublic class GetControllerMetaDataSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get controller cluster\'s metadata.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get controller cluster\'s metadata.";'),
        ('        Option opt = new Option("a", "controllerAddress", true, "the address of controller");',
         '        Option opt = new Option("a", "controllerAddress", true, "Controller 节点地址");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 Controller 元数据并打印组名、Leader 与 Peer 信息。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            final GetMetaDataResponseHeader metaData = defaultMQAdminExt.getControllerMetaData(controllerAddress);',
         '            // 获取 Controller 集群元数据响应\n            final GetMetaDataResponseHeader metaData = defaultMQAdminExt.getControllerMetaData(controllerAddress);'),
        ('            if (StringUtils.isNotEmpty(peers)) {',
         '            // 打印各 Peer Controller 地址\n            if (StringUtils.isNotEmpty(peers)) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/controller/ReElectMasterSubCommand.java': [
        ('public class ReElectMasterSubCommand implements SubCommand {',
         '/**\n * electMaster 子命令：通过 Controller 触发指定 Broker 副本 Master 选举。\n * <p>输出新 Master 地址、Epoch 及同步状态集信息。\n */\npublic class ReElectMasterSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Re-elect the specified broker as master.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Re-elect the specified broker as master.";'),
        ('        Option opt = new Option("a", "controllerAddress", true, "The address of controller");',
         '        Option opt = new Option("a", "controllerAddress", true, "Controller 节点地址");'),
        ('        opt = new Option("b", "brokerId", true, "The id of the broker which requires to become master");',
         '        opt = new Option("b", "brokerId", true, "期望成为 Master 的 Broker ID");'),
        ('        opt = new Option("bn", "brokerName", true, "The broker name of the replicas that require to be manipulated");',
         '        opt = new Option("bn", "brokerName", true, "待操作的 Broker 副本组名称");'),
        ('        opt = new Option("c", "clusterName", true, "the clusterName of broker");',
         '        opt = new Option("c", "clusterName", true, "Broker 所属集群名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 调用 electMaster 触发 Master 选举并打印结果。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            final Pair<ElectMasterResponseHeader, BrokerMemberGroup> pair = defaultMQAdminExt.electMaster(controllerAddress, clusterName, brokerName, brokerId);',
         '            // 向 Controller 发起 Master 选举请求\n            final Pair<ElectMasterResponseHeader, BrokerMemberGroup> pair = defaultMQAdminExt.electMaster(controllerAddress, clusterName, brokerName, brokerId);'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/controller/UpdateControllerConfigSubCommand.java': [
        ('public class UpdateControllerConfigSubCommand implements SubCommand {',
         '/**\n * updateControllerConfig 子命令：更新 Controller 集群的运行配置项。\n * <p>通过 key/value 指定单个配置项，支持多个 Controller 地址。\n */\npublic class UpdateControllerConfigSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update controller config.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update controller config.";'),
        ('        Option opt = new Option("a", "controllerAddress", true, "Controller address list, eg: 192.168.0.1:9878;192.168.0.2:9878");',
         '        Option opt = new Option("a", "controllerAddress", true, "Controller 地址列表，如 192.168.0.1:9878;192.168.0.2:9878");'),
        ('        opt = new Option("k", "key", true, "config key");',
         '        opt = new Option("k", "key", true, "配置项键名");'),
        ('        opt = new Option("v", "value", true, "config value");',
         '        opt = new Option("v", "value", true, "配置项值");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 key/value 并调用 updateControllerConfig 更新配置。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {'),
        ('            // key name\n            String key = commandLine.getOptionValue(\'k\').trim();',
         '            // 解析配置键名\n            String key = commandLine.getOptionValue(\'k\').trim();'),
        ('            // servers\n            String servers = commandLine.getOptionValue(\'a\');',
         '            // 解析分号分隔的 Controller 地址列表\n            String servers = commandLine.getOptionValue(\'a\');'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportConfigsCommand.java': [
        ('public class ExportConfigsCommand implements SubCommand {',
         '/**\n * exportConfigs 子命令：导出指定集群的 Broker 运行配置与规模信息。\n * <p>输出 configs.json，含 brokerConfigs 与 clusterScale。\n */\npublic class ExportConfigsCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Export configs.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Export configs.";'),
        ('        Option opt = new Option("c", "clusterName", true, "choose a cluster to export");',
         '        Option opt = new Option("c", "clusterName", true, "待导出的集群名");'),
        ('        opt = new Option("f", "filePath", true,\n            "export configs.json path | default /tmp/rocketmq/export");',
         '        opt = new Option("f", "filePath", true,\n            "导出目录路径，默认 /tmp/rocketmq/export");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)\n        throws SubCommandException {',
         '    /** 收集 NameServer 与 Broker 配置并写入 configs.json。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)\n        throws SubCommandException {'),
        ('            // name servers\n            List<String> nameServerAddressList = defaultMQAdminExt.getNameServerAddressList();',
         '            // 获取 NameServer 地址列表\n            List<String> nameServerAddressList = defaultMQAdminExt.getNameServerAddressList();'),
        ('            //broker\n            int masterBrokerSize = 0;',
         '            // 遍历集群 Master/Slave 并收集 Broker 配置\n            int masterBrokerSize = 0;'),
        ('    private Properties needBrokerProprties(Properties properties) {',
         '    /** 从完整 Broker 配置中筛选需要导出的关键属性。 */\n    private Properties needBrokerProprties(Properties properties) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/export/ExportMetadataCommand.java': [
        ('    private static final String DEFAULT_FILE_PATH = "/tmp/rocketmq/export";',
         '    /** 默认导出目录路径。 */\n    private static final String DEFAULT_FILE_PATH = "/tmp/rocketmq/export";'),
        ('public class ExportMetadataCommand implements SubCommand {',
         '/**\n * exportMetadata 子命令：导出 Topic 与订阅组元数据。\n * <p>支持按 Broker 或集群导出，可仅导出 Topic 或订阅组。\n */\npublic class ExportMetadataCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Export metadata.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Export metadata.";'),
        ('        Option opt = new Option("c", "clusterName", true, "choose a cluster to export");',
         '        Option opt = new Option("c", "clusterName", true, "待导出的集群名（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokerAddr", true, "choose a broker to export");',
         '        opt = new Option("b", "brokerAddr", true, "待导出的 Broker 地址（与 -c 二选一）");'),
        ('        opt = new Option("f", "filePath", true, "export metadata.json path | default /tmp/rocketmq/export");',
         '        opt = new Option("f", "filePath", true, "导出目录路径，默认 /tmp/rocketmq/export");'),
        ('        opt = new Option("t", "topic", false, "only export topic metadata");',
         '        opt = new Option("t", "topic", false, "仅导出 Topic 元数据");'),
        ('        opt = new Option("g", "subscriptionGroup", false, "only export subscriptionGroup metadata");',
         '        opt = new Option("g", "subscriptionGroup", false, "仅导出订阅组元数据");'),
        ('        opt = new Option("s", "specialTopic", false, "need retryTopic and dlqTopic");',
         '        opt = new Option("s", "specialTopic", false, "是否包含重试 Topic 与死信 Topic");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)\n        throws SubCommandException {',
         '    /** 按 Broker 或集群导出 Topic/订阅组元数据到 JSON 文件。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook)\n        throws SubCommandException {'),
        ('                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);',
         '                // 集群模式：遍历各 Master 合并 Topic 与订阅组元数据\n                Set<String> masterSet =\n                    CommandUtil.fetchMasterAddrByClusterName(defaultMQAdminExt, clusterName);'),
    ],
}
