"""Chinese JavaDoc replacements for springframework wave27b support classes."""

SUPPORT_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "AbstractFallbackSQLExceptionTranslator.java": [
        ('/**\n * Base class for {@link SQLExceptionTranslator} implementations that allow for a\n * fallback to some other {@link SQLExceptionTranslator}, as well as for custom\n * overrides.\n *\n * @author Juergen Hoeller\n * @since 2.5.6\n * @see #doTranslate\n * @see #setFallbackTranslator\n * @see #setCustomTranslator\n */',
         '/**\n * {@link SQLExceptionTranslator} 实现的基类，支持回退到其他 {@link SQLExceptionTranslator}，\n * 以及自定义覆盖。\n *\n * @author Juergen Hoeller\n * @since 2.5.6\n * @see #doTranslate\n * @see #setFallbackTranslator\n * @see #setCustomTranslator\n */'),
        ('\t/** Logger available to subclasses. */',
         '\t/** 供子类使用的 Logger。 */'),
        ('\t/**\n\t * Set the fallback translator to use when this translator cannot find a\n\t * specific match itself.\n\t */',
         '\t/**\n\t * 设置本翻译器无法匹配时使用的回退翻译器。\n\t */'),
        ('\t/**\n\t * Return the fallback exception translator, if any.\n\t * @see #setFallbackTranslator\n\t */',
         '\t/**\n\t * 返回回退异常翻译器（若有）。\n\t * @see #setFallbackTranslator\n\t */'),
        ('\t/**\n\t * Set a custom exception translator to override any match that this translator\n\t * would find. Note that such a custom {@link SQLExceptionTranslator} delegate\n\t * is meant to return {@code null} if it does not have an override itself.\n\t * @since 6.1\n\t */',
         '\t/**\n\t * 设置自定义异常翻译器，覆盖本翻译器可能找到的任何匹配。\n\t * 注意：自定义 {@link SQLExceptionTranslator} 委托在无自身覆盖时应返回 {@code null}。\n\t * @since 6.1\n\t */'),
        ('\t/**\n\t * Return a custom exception translator, if any.\n\t * @since 6.1\n\t * @see #setCustomTranslator\n\t */',
         '\t/**\n\t * 返回自定义异常翻译器（若有）。\n\t * @since 6.1\n\t * @see #setCustomTranslator\n\t */'),
        ('\t/**\n\t * Pre-checks the arguments, calls {@link #doTranslate}, and invokes the\n\t * {@link #getFallbackTranslator() fallback translator} if necessary.\n\t */',
         '\t/**\n\t * 预检查参数，调用 {@link #doTranslate}，必要时调用 {@link #getFallbackTranslator() 回退翻译器}。\n\t */'),
        ('\t/**\n\t * Template method for actually translating the given exception.\n\t * <p>The passed-in arguments will have been pre-checked. Furthermore, this method\n\t * is allowed to return {@code null} to indicate that no exception match has\n\t * been found and that fallback translation should kick in.\n\t * @param task readable text describing the task being attempted\n\t * @param sql the SQL query or update that caused the problem (if known)\n\t * @param ex the offending {@code SQLException}\n\t * @return the DataAccessException, wrapping the {@code SQLException};\n\t * or {@code null} if no exception match found\n\t */',
         '\t/**\n\t * 实际翻译给定异常的模板方法。\n\t * <p>传入参数已预检查；本方法可返回 {@code null} 表示未找到匹配，应启用回退翻译。\n\t * @param task 描述正在尝试任务的可读文本\n\t * @param sql 导致问题的 SQL 查询或更新（若已知）\n\t * @param ex 触发的 {@code SQLException}\n\t * @return 包装 {@code SQLException} 的 DataAccessException；未找到匹配时 {@code null}\n\t */'),
        ('\t/**\n\t * Build a message {@code String} for the given {@link java.sql.SQLException}.\n\t * <p>To be called by translator subclasses when creating an instance of a generic\n\t * {@link org.springframework.dao.DataAccessException} class.\n\t * @param task readable text describing the task being attempted\n\t * @param sql the SQL statement that caused the problem\n\t * @param ex the offending {@code SQLException}\n\t * @return the message {@code String} to use\n\t */',
         '\t/**\n\t * 为给定 {@link java.sql.SQLException} 构建消息 {@code String}。\n\t * <p>翻译器子类创建通用 {@link org.springframework.dao.DataAccessException} 实例时调用。\n\t * @param task 描述正在尝试任务的可读文本\n\t * @param sql 导致问题的 SQL 语句\n\t * @param ex 触发的 {@code SQLException}\n\t * @return 要使用的消息 {@code String}\n\t */'),
    ],
    "CustomSQLErrorCodesTranslation.java": [
        ('/**\n * JavaBean for holding custom JDBC error codes translation for a particular\n * database. The "exceptionClass" property defines which exception will be\n * thrown for the list of error codes specified in the errorCodes property.\n *\n * @author Thomas Risberg\n * @since 1.1\n * @see SQLErrorCodeSQLExceptionTranslator\n */',
         '/**\n * 用于保存特定数据库自定义 JDBC 错误码翻译的 JavaBean。\n * "exceptionClass" 属性定义 errorCodes 属性中列出的错误码将抛出的异常类型。\n *\n * @author Thomas Risberg\n * @since 1.1\n * @see SQLErrorCodeSQLExceptionTranslator\n */'),
        ('\t/**\n\t * Set the SQL error codes to match.\n\t */',
         '\t/**\n\t * 设置要匹配的 SQL 错误码。\n\t */'),
        ('\t/**\n\t * Return the SQL error codes to match.\n\t */',
         '\t/**\n\t * 返回要匹配的 SQL 错误码。\n\t */'),
        ('\t/**\n\t * Set the exception class for the specified error codes.\n\t */',
         '\t/**\n\t * 设置指定错误码对应的异常类。\n\t */'),
        ('\t/**\n\t * Return the exception class for the specified error codes.\n\t */',
         '\t/**\n\t * 返回指定错误码对应的异常类。\n\t */'),
    ],
    "CustomSQLExceptionTranslatorRegistrar.java": [
        ('/**\n * Registry for custom {@link SQLExceptionTranslator} instances for specific databases.\n *\n * @author Thomas Risberg\n * @since 3.1.1\n */',
         '/**\n * 特定数据库自定义 {@link SQLExceptionTranslator} 实例的注册器。\n *\n * @author Thomas Risberg\n * @since 3.1.1\n */'),
        ('\t/**\n\t * Map registry to hold custom translators specific databases.\n\t * Key is the database product name as defined in the\n\t * {@link org.springframework.jdbc.support.SQLErrorCodesFactory}.\n\t */',
         '\t/**\n\t * 保存特定数据库自定义翻译器的映射注册表。\n\t * 键为 {@link org.springframework.jdbc.support.SQLErrorCodesFactory} 中定义的数据库产品名称。\n\t */'),
        ('\t/**\n\t * Setter for a Map of {@link SQLExceptionTranslator} references where the key must\n\t * be the database name as defined in the {@code sql-error-codes.xml} file.\n\t * <p>Note that any existing translators will remain unless there is a match in the\n\t * database name, at which point the new translator will replace the existing one.\n\t */',
         '\t/**\n\t * 设置 {@link SQLExceptionTranslator} 引用映射，键必须为 {@code sql-error-codes.xml} 中定义的数据库名称。\n\t * <p>已有翻译器将保留，除非数据库名称匹配时新翻译器将替换现有翻译器。\n\t */'),
    ],
    "CustomSQLExceptionTranslatorRegistry.java": [
        ('/**\n * Registry for custom {@link SQLExceptionTranslator} instances associated with\n * specific databases allowing for overriding translation based on values\n * contained in the configuration file named "sql-error-codes.xml".\n *\n * @author Thomas Risberg\n * @since 3.1.1\n * @see SQLErrorCodesFactory\n */',
         '/**\n * 与特定数据库关联的自定义 {@link SQLExceptionTranslator} 实例注册表，\n * 允许基于 "sql-error-codes.xml" 配置文件中的值覆盖翻译。\n *\n * @author Thomas Risberg\n * @since 3.1.1\n * @see SQLErrorCodesFactory\n */'),
        ('\t/**\n\t * Keep track of a single instance, so we can return it to classes that request it.\n\t */',
         '\t/**\n\t * 跟踪单例实例，以便返回给请求的类。\n\t */'),
        ('\t/**\n\t * Return the singleton instance.\n\t */',
         '\t/**\n\t * 返回单例实例。\n\t */'),
        ('\t/**\n\t * Map registry to hold custom translators specific databases.\n\t * Key is the database product name as defined in the\n\t * {@link org.springframework.jdbc.support.SQLErrorCodesFactory}.\n\t */',
         '\t/**\n\t * 保存特定数据库自定义翻译器的映射注册表。\n\t * 键为 {@link org.springframework.jdbc.support.SQLErrorCodesFactory} 中定义的数据库产品名称。\n\t */'),
        ('\t/**\n\t * Create a new instance of the {@link CustomSQLExceptionTranslatorRegistry} class.\n\t * <p>Not public to enforce Singleton design pattern.\n\t */',
         '\t/**\n\t * 创建 {@link CustomSQLExceptionTranslatorRegistry} 新实例。\n\t * <p>非 public，以强制单例设计模式。\n\t */'),
        ('\t/**\n\t * Register a new custom translator for the specified database name.\n\t * @param dbName the database name\n\t * @param translator the custom translator\n\t */',
         '\t/**\n\t * 为指定数据库名称注册新的自定义翻译器。\n\t * @param dbName 数据库名称\n\t * @param translator 自定义翻译器\n\t */'),
        ('\t/**\n\t * Find a custom translator for the specified database.\n\t * @param dbName the database name\n\t * @return the custom translator, or {@code null} if none found\n\t */',
         '\t/**\n\t * 查找指定数据库的自定义翻译器。\n\t * @param dbName 数据库名称\n\t * @return 自定义翻译器，未找到时 {@code null}\n\t */'),
    ],
    "DatabaseMetaDataCallback.java": [
        ("/**\n * A callback interface used by the JdbcUtils class. Implementations of this\n * interface perform the actual work of extracting database meta-data, but\n * don't need to worry about exception handling. SQLExceptions will be caught\n * and handled correctly by the JdbcUtils class.\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @param <T> the result type\n * @see JdbcUtils#extractDatabaseMetaData(javax.sql.DataSource, DatabaseMetaDataCallback)\n */",
         '/**\n * JdbcUtils 类使用的回调接口。本接口的实现执行提取数据库元数据的实际工作，\n * 无需担心异常处理——SQLException 将由 JdbcUtils 正确捕获和处理。\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @param <T> 结果类型\n * @see JdbcUtils#extractDatabaseMetaData(javax.sql.DataSource, DatabaseMetaDataCallback)\n */'),
        ("\t/**\n\t * Implementations must implement this method to process the meta-data\n\t * passed in. Exactly what the implementation chooses to do is up to it.\n\t * @param dbmd the DatabaseMetaData to process\n\t * @return a result object extracted from the meta-data\n\t * (can be an arbitrary object, as needed by the implementation)\n\t * @throws SQLException if an SQLException is encountered getting\n\t * column values (that is, there's no need to catch SQLException)\n\t * @throws MetaDataAccessException in case of other failures while\n\t * extracting meta-data (for example, reflection failure)\n\t */",
         '\t/**\n\t * 实现必须实现本方法处理传入的元数据，具体处理逻辑由实现决定。\n\t * @param dbmd 要处理的 DatabaseMetaData\n\t * @return 从元数据提取的结果对象（可为实现所需的任意对象）\n\t * @throws SQLException 获取列值时遇到 SQLException（无需自行捕获）\n\t * @throws MetaDataAccessException 提取元数据时其他失败（如反射失败）\n\t */'),
    ],
    "DatabaseStartupValidator.java": [
        ('/**\n * Bean that checks if a database has already started up. To be referenced\n * via "depends-on" from beans that depend on database startup, like a Hibernate\n * SessionFactory or custom data access objects that access a DataSource directly.\n *\n * <p>Useful to defer application initialization until a database has started up.\n * Particularly appropriate for waiting on a slowly starting Oracle database.\n *\n * @author Juergen Hoeller\n * @author Marten Deinum\n * @since 18.12.2003\n */',
         '/**\n * 检查数据库是否已启动的 Bean。依赖数据库启动的 Bean（如 Hibernate SessionFactory\n * 或直接访问 DataSource 的自定义 DAO）可通过 "depends-on" 引用本 Bean。\n *\n * <p>用于延迟应用初始化直至数据库启动，特别适合等待启动较慢的 Oracle 数据库。\n *\n * @author Juergen Hoeller\n * @author Marten Deinum\n * @since 18.12.2003\n */'),
        ('\t/**\n\t * The default interval.\n\t */',
         '\t/** 默认重试间隔（秒）。 */'),
        ('\t/**\n\t * The default timeout.\n\t */',
         '\t/** 默认超时时间（秒）。 */'),
        ('\t/**\n\t * Set the DataSource to validate.\n\t */',
         '\t/**\n\t * 设置要验证的 DataSource。\n\t */'),
        ('\t/**\n\t * Set the SQL query string to use for validation.\n\t * @deprecated in favor of the JDBC 4.0 connection validation\n\t */',
         '\t/**\n\t * 设置用于验证的 SQL 查询字符串。\n\t * @deprecated 建议使用 JDBC 4.0 连接验证\n\t */'),
        ('\t/**\n\t * Set the interval between validation runs (in seconds).\n\t * Default is {@value #DEFAULT_INTERVAL}.\n\t */',
         '\t/**\n\t * 设置验证重试间隔（秒），默认 {@value #DEFAULT_INTERVAL}。\n\t */'),
        ('\t/**\n\t * Set the timeout (in seconds) after which a fatal exception\n\t * will be thrown. Default is {@value #DEFAULT_TIMEOUT}.\n\t */',
         '\t/**\n\t * 设置超时时间（秒），超时后抛出致命异常，默认 {@value #DEFAULT_TIMEOUT}。\n\t */'),
        ('\t/**\n\t * Check whether the validation query can be executed on a Connection\n\t * from the specified DataSource, with the specified interval between\n\t * checks, until the specified timeout.\n\t */',
         '\t/**\n\t * 检查指定 DataSource 的连接是否可执行验证查询，\n\t * 在指定间隔重试直至超时。\n\t */'),
    ],
    "GeneratedKeyHolder.java": [
        ('/**\n * The standard implementation of the {@link KeyHolder} interface, to be used for\n * holding auto-generated keys (as potentially returned by JDBC insert statements).\n *\n * <p>Create an instance of this class for each insert operation, and pass it\n * to the corresponding {@link org.springframework.jdbc.core.JdbcTemplate} or\n * {@link org.springframework.jdbc.object.SqlUpdate} methods.\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @author Slawomir Dymitrow\n * @since 1.1\n */',
         '/**\n * {@link KeyHolder} 接口的标准实现，用于保存自动生成的主键\n * （可能由 JDBC insert 语句返回）。\n *\n * <p>每次 insert 操作创建本类实例，并传递给相应的\n * {@link org.springframework.jdbc.core.JdbcTemplate} 或\n * {@link org.springframework.jdbc.object.SqlUpdate} 方法。\n *\n * @author Thomas Risberg\n * @author Juergen Hoeller\n * @author Slawomir Dymitrow\n * @since 1.1\n */'),
        ('\t/**\n\t * Create a new GeneratedKeyHolder with a default list.\n\t */',
         '\t/**\n\t * 使用默认列表创建 GeneratedKeyHolder。\n\t */'),
        ('\t/**\n\t * Create a new GeneratedKeyHolder with a given list.\n\t * @param keyList a list to hold maps of keys\n\t */',
         '\t/**\n\t * 使用给定列表创建 GeneratedKeyHolder。\n\t * @param keyList 存放键映射的列表\n\t */'),
    ],
    "JdbcAccessor.java": [
        ('/**\n * Base class for {@link org.springframework.jdbc.core.JdbcTemplate} and\n * other JDBC-accessing DAO helpers, defining common properties such as\n * DataSource and exception translator.\n *\n * <p>Not intended to be used directly.\n * See {@link org.springframework.jdbc.core.JdbcTemplate}.\n *\n * @author Juergen Hoeller\n * @author Sebastien Deleuze\n * @since 28.11.2003\n * @see org.springframework.jdbc.core.JdbcTemplate\n */',
         '/**\n * {@link org.springframework.jdbc.core.JdbcTemplate} 及其他 JDBC 访问 DAO 辅助类的基类，\n * 定义 DataSource 和异常翻译器等公共属性。\n *\n * <p>不供直接使用，参见 {@link org.springframework.jdbc.core.JdbcTemplate}。\n *\n * @author Juergen Hoeller\n * @author Sebastien Deleuze\n * @since 28.11.2003\n * @see org.springframework.jdbc.core.JdbcTemplate\n */'),
        ('\t/** Logger available to subclasses. */',
         '\t/** 供子类使用的 Logger。 */'),
        ('\t/**\n\t * Set the JDBC DataSource to obtain connections from.\n\t */',
         '\t/**\n\t * 设置用于获取连接的 JDBC DataSource。\n\t */'),
        ('\t/**\n\t * Return the DataSource used by this template.\n\t */',
         '\t/**\n\t * 返回本模板使用的 DataSource。\n\t */'),
        ('\t/**\n\t * Obtain the DataSource for actual use.\n\t * @return the DataSource (never {@code null})\n\t * @throws IllegalStateException in case of no DataSource set\n\t * @since 5.0\n\t */',
         '\t/**\n\t * 获取实际使用的 DataSource。\n\t * @return DataSource（永不为 {@code null}）\n\t * @throws IllegalStateException 未设置 DataSource 时\n\t * @since 5.0\n\t */'),
        ('\t/**\n\t * Specify the database product name for the {@code DataSource} that this accessor uses.\n\t * This allows for initializing a {@link SQLErrorCodeSQLExceptionTranslator} without\n\t * obtaining a {@code Connection} from the {@code DataSource} to get the meta-data.\n\t * @param dbName the database product name that identifies the error codes entry\n\t * @see #setExceptionTranslator\n\t * @see SQLErrorCodeSQLExceptionTranslator#setDatabaseProductName\n\t * @see java.sql.DatabaseMetaData#getDatabaseProductName()\n\t */',
         '\t/**\n\t * 指定本访问器使用的 {@code DataSource} 的数据库产品名称。\n\t * 无需从 {@code DataSource} 获取 {@code Connection} 读取元数据即可初始化 {@link SQLErrorCodeSQLExceptionTranslator}。\n\t * @param dbName 标识错误码条目的数据库产品名称\n\t * @see #setExceptionTranslator\n\t * @see SQLErrorCodeSQLExceptionTranslator#setDatabaseProductName\n\t * @see java.sql.DatabaseMetaData#getDatabaseProductName()\n\t */'),
        ('\t/**\n\t * Set the exception translator for this instance.\n\t * <p>A {@link SQLErrorCodeSQLExceptionTranslator} used by default if a user-provided\n\t * `sql-error-codes.xml` file has been found in the root of the classpath. Otherwise,\n\t * {@link SQLExceptionSubclassTranslator} serves as the default translator as of 6.0.\n\t * @see org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator\n\t * @see org.springframework.jdbc.support.SQLExceptionSubclassTranslator\n\t */',
         '\t/**\n\t * 设置本实例的异常翻译器。\n\t * <p>若类路径根目录存在用户提供的 `sql-error-codes.xml`，默认使用 {@link SQLErrorCodeSQLExceptionTranslator}；\n\t * 否则自 6.0 起默认使用 {@link SQLExceptionSubclassTranslator}。\n\t * @see org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator\n\t * @see org.springframework.jdbc.support.SQLExceptionSubclassTranslator\n\t */'),
        ('\t/**\n\t * Return the exception translator to use for this instance,\n\t * creating a default if necessary.\n\t * @see #setExceptionTranslator\n\t */',
         '\t/**\n\t * 返回本实例使用的异常翻译器，必要时创建默认翻译器。\n\t * @see #setExceptionTranslator\n\t */'),
        ('\t/**\n\t * Set whether to lazily initialize the SQLExceptionTranslator for this accessor,\n\t * on first encounter of an SQLException. Default is "true"; can be switched to\n\t * "false" for initialization on startup.\n\t * <p>Early initialization just applies if {@code afterPropertiesSet()} is called.\n\t * @see #getExceptionTranslator()\n\t * @see #afterPropertiesSet()\n\t */',
         '\t/**\n\t * 设置是否在首次遇到 SQLException 时延迟初始化 SQLExceptionTranslator，默认 "true"；\n\t * 设为 "false" 可在启动时初始化。\n\t * <p>提前初始化仅在调用 {@code afterPropertiesSet()} 时生效。\n\t * @see #getExceptionTranslator()\n\t * @see #afterPropertiesSet()\n\t */'),
        ('\t/**\n\t * Return whether to lazily initialize the SQLExceptionTranslator for this accessor.\n\t * @see #getExceptionTranslator()\n\t */',
         '\t/**\n\t * 返回是否延迟初始化 SQLExceptionTranslator。\n\t * @see #getExceptionTranslator()\n\t */'),
        ('\t/**\n\t * Eagerly initialize the exception translator, if demanded,\n\t * creating a default one for the specified DataSource if none set.\n\t */',
         '\t/**\n\t * 按需提前初始化异常翻译器，未设置时为指定 DataSource 创建默认翻译器。\n\t */'),
    ],
    "JdbcTransactionManager.java": [
        ('/**\n * {@link JdbcAccessor}-aligned subclass of the plain {@link DataSourceTransactionManager},\n * adding common JDBC exception translation for the commit and rollback step.\n * Typically used in combination with {@link org.springframework.jdbc.core.JdbcTemplate}\n * which applies the same {@link SQLExceptionTranslator} infrastructure by default.\n *\n * <p>Exception translation is specifically relevant for commit steps in serializable\n * transactions (for example, on Postgres) where concurrency failures may occur late on commit.\n * This allows for throwing {@link org.springframework.dao.ConcurrencyFailureException} to\n * callers instead of {@link org.springframework.transaction.TransactionSystemException}.\n *\n * <p>Analogous to {@code HibernateTransactionManager} and {@code JpaTransactionManager},\n * this transaction manager may throw {@link DataAccessException} from {@link #commit}\n * and possibly also from {@link #rollback}. Calling code should be prepared for handling\n * such exceptions next to {@link org.springframework.transaction.TransactionException},\n * which is generally sensible since {@code TransactionSynchronization} implementations\n * may also throw such exceptions in their {@code flush} and {@code beforeCommit} phases.\n *\n * @author Juergen Hoeller\n * @author Sebastien Deleuze\n * @since 5.3\n * @see DataSourceTransactionManager\n * @see #setDataSource\n * @see #setExceptionTranslator\n */',
         '/**\n * 与 {@link JdbcAccessor} 对齐的 {@link DataSourceTransactionManager} 子类，\n * 为 commit 和 rollback 步骤添加通用 JDBC 异常翻译。\n * 通常与 {@link org.springframework.jdbc.core.JdbcTemplate} 配合使用，\n * 后者默认应用相同的 {@link SQLExceptionTranslator} 基础设施。\n *\n * <p>异常翻译对可串行化事务的 commit 步骤尤为重要（如 Postgres），\n * 并发失败可能在 commit 时才出现，使调用方收到 {@link org.springframework.dao.ConcurrencyFailureException}\n * 而非 {@link org.springframework.transaction.TransactionSystemException}。\n *\n * <p>类似 {@code HibernateTransactionManager} 和 {@code JpaTransactionManager}，\n * 本事务管理器可能在 {@link #commit} 和 {@link #rollback} 时抛出 {@link DataAccessException}。\n * 调用代码应准备好处理此类异常以及 {@link org.springframework.transaction.TransactionException}，\n * 因为 {@code TransactionSynchronization} 实现也可能在 {@code flush} 和 {@code beforeCommit} 阶段抛出此类异常。\n *\n * @author Juergen Hoeller\n * @author Sebastien Deleuze\n * @since 5.3\n * @see DataSourceTransactionManager\n * @see #setDataSource\n * @see #setExceptionTranslator\n */'),
        ('\t/**\n\t * Create a new {@code JdbcTransactionManager} instance.\n\t * A {@code DataSource} has to be set to be able to use it.\n\t * @see #setDataSource\n\t */',
         '\t/**\n\t * 创建 {@code JdbcTransactionManager} 新实例，使用前必须设置 {@code DataSource}。\n\t * @see #setDataSource\n\t */'),
        ('\t/**\n\t * Create a new {@code JdbcTransactionManager} instance.\n\t * @param dataSource the JDBC DataSource to manage transactions for\n\t */',
         '\t/**\n\t * 创建 {@code JdbcTransactionManager} 新实例。\n\t * @param dataSource 要管理事务的 JDBC DataSource\n\t */'),
        ('\t/**\n\t * Specify the database product name for the {@code DataSource} that this\n\t * transaction manager operates on.\n\t * This allows for initializing a {@link SQLErrorCodeSQLExceptionTranslator} without\n\t * obtaining a {@code Connection} from the {@code DataSource} to get the meta-data.\n\t * @param dbName the database product name that identifies the error codes entry\n\t * @see #setExceptionTranslator\n\t * @see SQLErrorCodeSQLExceptionTranslator#setDatabaseProductName\n\t * @see java.sql.DatabaseMetaData#getDatabaseProductName()\n\t * @see JdbcAccessor#setDatabaseProductName\n\t */',
         '\t/**\n\t * 指定本事务管理器操作的 {@code DataSource} 的数据库产品名称。\n\t * 无需从 {@code DataSource} 获取 {@code Connection} 读取元数据即可初始化 {@link SQLErrorCodeSQLExceptionTranslator}。\n\t * @param dbName 标识错误码条目的数据库产品名称\n\t * @see #setExceptionTranslator\n\t * @see SQLErrorCodeSQLExceptionTranslator#setDatabaseProductName\n\t * @see java.sql.DatabaseMetaData#getDatabaseProductName()\n\t * @see JdbcAccessor#setDatabaseProductName\n\t */'),
        ('\t/**\n\t * Set the exception translator for this transaction manager.\n\t * <p>A {@link SQLErrorCodeSQLExceptionTranslator} used by default if a user-provided\n\t * `sql-error-codes.xml` file has been found in the root of the classpath. Otherwise,\n\t * {@link SQLExceptionSubclassTranslator} serves as the default translator as of 6.0.\n\t * @see org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator\n\t * @see org.springframework.jdbc.support.SQLExceptionSubclassTranslator\n\t * @see JdbcAccessor#setExceptionTranslator\n\t */',
         '\t/**\n\t * 设置本事务管理器的异常翻译器。\n\t * <p>若类路径根目录存在用户提供的 `sql-error-codes.xml`，默认使用 {@link SQLErrorCodeSQLExceptionTranslator}；\n\t * 否则自 6.0 起默认使用 {@link SQLExceptionSubclassTranslator}。\n\t * @see org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator\n\t * @see org.springframework.jdbc.support.SQLExceptionSubclassTranslator\n\t * @see JdbcAccessor#setExceptionTranslator\n\t */'),
        ('\t/**\n\t * Return the exception translator to use for this instance,\n\t * creating a default if necessary.\n\t * @see #setExceptionTranslator\n\t */',
         '\t/**\n\t * 返回本实例使用的异常翻译器，必要时创建默认翻译器。\n\t * @see #setExceptionTranslator\n\t */'),
        ('\t/**\n\t * Set whether to lazily initialize the SQLExceptionTranslator for this transaction manager,\n\t * on first encounter of an SQLException. Default is "true"; can be switched to\n\t * "false" for initialization on startup.\n\t * <p>Early initialization just applies if {@code afterPropertiesSet()} is called.\n\t * @see #getExceptionTranslator()\n\t * @see #afterPropertiesSet()\n\t */',
         '\t/**\n\t * 设置是否在首次遇到 SQLException 时延迟初始化 SQLExceptionTranslator，默认 "true"；\n\t * 设为 "false" 可在启动时初始化。\n\t * <p>提前初始化仅在调用 {@code afterPropertiesSet()} 时生效。\n\t * @see #getExceptionTranslator()\n\t * @see #afterPropertiesSet()\n\t */'),
        ('\t/**\n\t * Return whether to lazily initialize the SQLExceptionTranslator for this transaction manager.\n\t * @see #getExceptionTranslator()\n\t */',
         '\t/**\n\t * 返回是否延迟初始化 SQLExceptionTranslator。\n\t * @see #getExceptionTranslator()\n\t */'),
        ('\t/**\n\t * Eagerly initialize the exception translator, if demanded,\n\t * creating a default one for the specified DataSource if none set.\n\t */',
         '\t/**\n\t * 按需提前初始化异常翻译器，未设置时为指定 DataSource 创建默认翻译器。\n\t */'),
        ('\t/**\n\t * This implementation attempts to use the {@link SQLExceptionTranslator},\n\t * falling back to a {@link org.springframework.transaction.TransactionSystemException}.\n\t * @see #getExceptionTranslator()\n\t * @see DataSourceTransactionManager#translateException\n\t */',
         '\t/**\n\t * 本实现尝试使用 {@link SQLExceptionTranslator}，\n\t * 回退到 {@link org.springframework.transaction.TransactionSystemException}。\n\t * @see #getExceptionTranslator()\n\t * @see DataSourceTransactionManager#translateException\n\t */'),
    ],
    "JdbcUtilsRuntimeHints.java": [
        ('/**\n * {@link RuntimeHintsRegistrar} implementation that registers runtime hints for\n * {@link JdbcUtils}.\n *\n * @author Brian Clozel\n * @since 6.2.13\n */',
         '/**\n * {@link RuntimeHintsRegistrar} 实现，为 {@link JdbcUtils} 注册运行时提示。\n *\n * @author Brian Clozel\n * @since 6.2.13\n */'),
    ],
}
