"""Chinese JavaDoc replacements for RocketMQ wave45b tools [15:30]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/offset/CloneGroupOffsetCommand.java': [
        ('public class CloneGroupOffsetCommand implements SubCommand {',
         '/**\n * cloneGroupOffset 子命令：将源消费组的消费位点复制到目标消费组。\n */\npublic class CloneGroupOffsetCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 cloneGroupOffset。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("s", "srcGroup", true, "set source consumer group");',
         '        Option opt = new Option("s", "srcGroup", true, "源消费组名");'),
        ('        opt = new Option("d", "destGroup", true, "set destination consumer group");',
         '        opt = new Option("d", "destGroup", true, "目标消费组名");'),
        ('        opt = new Option("t", "topic", true, "set the topic");',
         '        opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("o", "offline", true, "the group or the topic is offline");',
         '        opt = new Option("o", "offline", true, "消费组或 Topic 是否离线");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 读取源组各队列消费位点，写入目标组对应 Broker 队列。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/offset/GetConsumerStatusCommand.java': [
        ('public class GetConsumerStatusCommand implements SubCommand {',
         '/**\n * getConsumerStatus 子命令：从消费端客户端拉取各队列当前消费位点。\n */\npublic class GetConsumerStatusCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 getConsumerStatus。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "group", true, "set the consumer group");',
         '        Option opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("t", "topic", true, "set the topic");',
         '        opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("i", "originClientId", true, "set the consumer clientId");',
         '        opt = new Option("i", "originClientId", true, "可选，指定客户端 clientId");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 调用 getConsumeStatus 并表格输出 clientId、Broker、队列与 offset。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/offset/ResetOffsetByTimeCommand.java': [
        ('public class ResetOffsetByTimeCommand implements SubCommand {',
         '/**\n * resetOffsetByTime 子命令：按时间戳重置消费位点（无需重启客户端）。\n */\npublic class ResetOffsetByTimeCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 resetOffsetByTime。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "group", true, "set the consumer group");',
         '        Option opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("t", "topic", true, "set the topic");',
         '        opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("s", "timestamp", true, "set the timestamp[now|currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '        opt = new Option("s", "timestamp", true, "目标时间戳（now|毫秒|yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('        opt = new Option("f", "force", true, "set the force rollback by timestamp switch[true|false]. Deprecated.");',
         '        opt = new Option("f", "force", true, "是否强制按时间回滚，默认 true（已废弃）");'),
        ('        opt = new Option("c", "cplus", false, "reset c++ client offset. Deprecated.");',
         '        opt = new Option("c", "cplus", false, "是否重置 C++ 客户端 offset（已废弃）");'),
        ('        opt = new Option("b", "broker", true, "broker addr");',
         '        opt = new Option("b", "broker", true, "Broker 地址（与 -q 配合单队列重置）");'),
        ('        opt = new Option("q", "queue", true, "queue id");',
         '        opt = new Option("q", "queue", true, "队列 ID（需配合 -b）");'),
        ('        opt = new Option("o", "offset", true, "Expect queue offset, not support old version broker");',
         '        opt = new Option("o", "offset", true, "期望队列 offset，旧版 Broker 不支持");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic，用于解析路由");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析时间戳后全量或单队列重置；消费者离线时回退旧版命令。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/offset/ResetOffsetByTimeOldCommand.java': [
        ('    public static void resetOffset(DefaultMQAdminExt defaultMQAdminExt, String clusterName, String consumerGroup,',
         '    /** 调用旧版 resetOffsetByTimestampOld 并打印各队列回滚统计。 */\n    public static void resetOffset(DefaultMQAdminExt defaultMQAdminExt, String clusterName, String consumerGroup,'),
        ('public class ResetOffsetByTimeOldCommand implements SubCommand {',
         '/**\n * resetOffsetByTimeOld 子命令：按时间戳重置消费位点（需重启客户端）。\n */\npublic class ResetOffsetByTimeOldCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 resetOffsetByTimeOld。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "group", true, "set the consumer group");',
         '        Option opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("t", "topic", true, "set the topic");',
         '        opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("s", "timestamp", true, "set the timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '        opt = new Option("s", "timestamp", true, "目标时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('        opt = new Option("f", "force", true, "set the force rollback by timestamp switch[true|false]");',
         '        opt = new Option("f", "force", true, "是否强制按时间回滚，默认 true");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic，用于解析路由");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析时间戳与 force 参数后调用 {@link #resetOffset}。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/offset/SkipAccumulationSubCommand.java': [
        ('public class SkipAccumulationSubCommand implements SubCommand {',
         '/**\n * skipAccumulatedMessage 子命令：跳过当前全部堆积未消费消息。\n */\npublic class SkipAccumulationSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 skipAccumulatedMessage。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("g", "group", true, "set the consumer group");',
         '        Option opt = new Option("g", "group", true, "消费组名");'),
        ('        opt = new Option("t", "topic", true, "set the topic");',
         '        opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("f", "force", true, "set the force rollback by timestamp switch[true|false]");',
         '        opt = new Option("f", "force", true, "是否强制跳过堆积，默认 true");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic，用于解析路由");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 以 timestamp=-1 重置 offset；消费者离线时走旧版 API。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/producer/ProducerSubCommand.java': [
        ('public class ProducerSubCommand implements SubCommand {',
         '/**\n * producer 子命令：查询 Broker 上已连接的生产者实例与状态。\n */\npublic class ProducerSubCommand implements SubCommand {'),
        ('    public static void main(String[] args) {',
         '    /** 本地调试入口，默认连接 127.0.0.1:9876 与指定 Broker。 */\n    public static void main(String[] args) {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 producer。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("b", "broker", true, "broker address");',
         '        Option opt = new Option("b", "broker", true, "目标 Broker 地址");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取 Broker 全部生产者组并逐实例打印连接信息。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/queue/CheckRocksdbCqWriteProgressCommand.java': [
        ('public class CheckRocksdbCqWriteProgressCommand implements SubCommand {',
         '/**\n * checkRocksdbCqWriteProgress 子命令：校验 RocksDB 消费队列与文件 CQ 写入是否一致。\n */\npublic class CheckRocksdbCqWriteProgressCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 checkRocksdbCqWriteProgress。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("c", "cluster", true, "cluster name");',
         '        Option opt = new Option("c", "cluster", true, "集群名");'),
        ('        opt = new Option("n", "nameserverAddr", true, "nameserverAddr");',
         '        opt = new Option("n", "nameserverAddr", true, "NameServer 地址");'),
        ('        opt = new Option("t", "topic", true, "topic name");',
         '        opt = new Option("t", "topic", true, "Topic 名（可选）");'),
        ('        opt = new Option("cf", "checkFrom", true, "check from time");',
         '        opt = new Option("cf", "checkFrom", true, "校验起始时间戳，默认 30 天前");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) {',
         '    /** 遍历集群 Broker 触发 RocksDB CQ 写入进度校验。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/queue/QueryConsumeQueueCommand.java': [
        ('public class QueryConsumeQueueCommand implements SubCommand {',
         '/**\n * queryCq 子命令：按索引区间查询 Broker 消费队列（CQ）条目。\n */\npublic class QueryConsumeQueueCommand implements SubCommand {'),
        ('    public static void main(String[] args) {',
         '    /** 本地调试入口，演示 queryCq 参数解析与执行。 */\n    public static void main(String[] args) {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 queryCq。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("q", "queue", true, "queue num, ie. 1");',
         '        opt = new Option("q", "queue", true, "队列 ID");'),
        ('        opt = new Option("i", "index", true, "start queue index.");',
         '        opt = new Option("i", "index", true, "起始队列索引");'),
        ('        opt = new Option("c", "count", true, "how many.");',
         '        opt = new Option("c", "count", true, "查询条数，默认 10");'),
        ('        opt = new Option("b", "broker", true, "broker addr.");',
         '        opt = new Option("b", "broker", true, "Broker 地址（省略则从路由取首个）");'),
        ('        opt = new Option("g", "consumer", true, "consumer group.");',
         '        opt = new Option("g", "consumer", true, "消费组名（可选，用于过滤数据）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) {',
         '    /** 调用 queryConsumeQueue 并打印订阅、过滤与队列数据。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/stats/StatsAllSubCommand.java': [
        ('    public static void printTopicDetail(final DefaultMQAdminExt admin, final String topic, final boolean activeTopic)',
         '    /** 汇总 Topic 入站 TPS/24h 消息量及各消费组出站与堆积。 */\n    public static void printTopicDetail(final DefaultMQAdminExt admin, final String topic, final boolean activeTopic)'),
        ('    public static long compute24HourSum(BrokerStatsData bsd) {',
         '    /** 优先取日/时/分钟统计 sum 作为近 24 小时消息量。 */\n    public static long compute24HourSum(BrokerStatsData bsd) {'),
        ('public class StatsAllSubCommand implements SubCommand {',
         '/**\n * statsAll 子命令：输出全集群 Topic 与各消费组的 TPS 与堆积统计。\n */\npublic class StatsAllSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 statsAll。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("a", "activeTopic", false, "print active topic only");',
         '        Option opt = new Option("a", "activeTopic", false, "仅输出近 24h 有流量的 Topic");'),
        ('        opt = new Option("t", "topic", true, "print select topic only");',
         '        opt = new Option("t", "topic", true, "仅统计指定 Topic");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历 Topic 列表（跳过重试/DLQ），调用 printTopicDetail 输出表格。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/AllocateMQSubCommand.java': [
        ('public class AllocateMQSubCommand implements SubCommand {',
         '/**\n * allocateMQ 子命令：模拟平均负载策略为 IP 列表分配 {@link MessageQueue}。\n */\npublic class AllocateMQSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 allocateMQ。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名");'),
        ('        opt = new Option("i", "ipList", true, "ipList");',
         '        opt = new Option("i", "ipList", true, "消费者 IP 列表，逗号分隔");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 按 {@link AllocateMessageQueueAveragely} 分配队列并以 JSON 输出。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/DeleteTopicSubCommand.java': [
        ('    public static void deleteTopic(final DefaultMQAdminExt adminExt,',
         '    /** 从集群 Master Broker 与 NameServer 删除指定 Topic。 */\n    public static void deleteTopic(final DefaultMQAdminExt adminExt,'),
        ('public class DeleteTopicSubCommand implements SubCommand {',
         '/**\n * deleteTopic 子命令：从 Broker 与 NameServer 删除 Topic。\n */\npublic class DeleteTopicSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 deleteTopic。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "待删除 Topic 名");'),
        ('        opt = new Option("c", "clusterName", true, "delete topic from which cluster");',
         '        opt = new Option("c", "clusterName", true, "Topic 所在集群名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 校验 -c 集群参数后调用 {@link #deleteTopic}。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/RebalanceResult.java': [
        ('public class RebalanceResult {',
         '/**\n * allocateMQ 命令的 JSON 输出载体：IP 到已分配 {@link MessageQueue} 列表的映射。\n */\npublic class RebalanceResult {'),
        ('    private Map<String/*ip*/, List<MessageQueue>> result = new HashMap<>();',
         '    /** 各消费者 IP 对应的队列分配结果。 */\n    private Map<String/*ip*/, List<MessageQueue>> result = new HashMap<>();'),
        ('    public Map<String, List<MessageQueue>> getResult() {',
         '    /** 返回 IP 到队列列表的映射。 */\n    public Map<String, List<MessageQueue>> getResult() {'),
        ('    public void setResult(final Map<String, List<MessageQueue>> result) {',
         '    /** 设置 IP 到队列列表的映射。 */\n    public void setResult(final Map<String, List<MessageQueue>> result) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/RemappingStaticTopicSubCommand.java': [
        ('public class RemappingStaticTopicSubCommand implements SubCommand {',
         '/**\n * remappingStaticTopic 子命令：重映射静态 Topic 的队列到目标 Broker/集群。\n */\npublic class RemappingStaticTopicSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 remappingStaticTopic。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        opt = new Option("c", "clusters", true, "remapping static topic to clusters, comma separated");',
         '        opt = new Option("c", "clusters", true, "目标集群名，逗号分隔（与 -b 二选一）");'),
        ('        opt = new Option("b", "brokers", true, "remapping static topic to brokers, comma separated");',
         '        opt = new Option("b", "brokers", true, "目标 Broker 名，逗号分隔（与 -c 二选一）");'),
        ('        opt = new Option("t", "topic", true, "topic name");',
         '        opt = new Option("t", "topic", true, "静态 Topic 名");'),
        ('        opt = new Option("mf", "mapFile", true, "The mapping data file name ");',
         '        opt = new Option("mf", "mapFile", true, "映射数据文件路径（可选）");'),
        ('        opt = new Option("fr", "forceReplace", true, "Force replace the old mapping");',
         '        opt = new Option("fr", "forceReplace", true, "是否强制替换旧映射");'),
        ('    public void executeFromFile(final CommandLine commandLine, final Options options,',
         '    /** 从映射文件解码配置并调用 remappingStaticTopic 提交变更。 */\n    public void executeFromFile(final CommandLine commandLine, final Options options,'),
        ('    public void execute(final CommandLine commandLine, final Options options,',
         '    /** 解析目标 Broker/集群，生成新映射并提交；支持 -f 从文件导入。 */\n    public void execute(final CommandLine commandLine, final Options options,'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicClusterSubCommand.java': [
        ('public class TopicClusterSubCommand implements SubCommand {',
         '/**\n * topicClusterList 子命令：查询 Topic 所属的全部集群名。\n */\npublic class TopicClusterSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 topicClusterList。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名");'),
        ('    public void execute(final CommandLine commandLine, final Options options,',
         '    /** 调用 getTopicClusterList 并逐行打印集群名。 */\n    public void execute(final CommandLine commandLine, final Options options,'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/topic/TopicListSubCommand.java': [
        ('public class TopicListSubCommand implements SubCommand {',
         '/**\n * topicList 子命令：从 NameServer 拉取全部 Topic 列表。\n */\npublic class TopicListSubCommand implements SubCommand {'),
        ('    public String commandName() {',
         '    /** 返回子命令名 topicList。 */\n    public String commandName() {'),
        ('    public String commandDesc() {',
         '    /** 返回命令描述。 */\n    public String commandDesc() {'),
        ('        Option opt = new Option("c", "clusterModel", false, "clusterModel");',
         '        Option opt = new Option("c", "clusterModel", false, "集群模式：输出 Topic 所属集群与消费组");'),
        ('    public void execute(final CommandLine commandLine, final Options options,',
         '    /** -c 时表格输出集群/Topic/消费组；否则仅列出 Topic 名。 */\n    public void execute(final CommandLine commandLine, final Options options,'),
        ('    private String findTopicBelongToWhichCluster(final String topic, final ClusterInfo clusterInfo,',
         '    /** 根据 Topic 路由首个 Broker 反查所属集群名。 */\n    private String findTopicBelongToWhichCluster(final String topic, final ClusterInfo clusterInfo,'),
    ],
}
