"""Chinese JavaDoc replacements for RxJava 4.0.0-alpha-21 wave30b JMH xmapz perf [14:28]."""

JMH_W30B_REPLACEMENTS: dict[str, list[tuple[str, str]]] = {
    "src/jmh/java/io/reactivex/rxjava4/xmapz/FlowableSwitchMapMaybePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Flowable switchMap(Flowable::just) 与 switchMap(Maybe.toFlowable)、专用 switchMapMaybe 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object flowablePlain(Blackhole bh) {', '    /** plain：switchMap(Flowable::just) 基准。 */\n    @Benchmark\n    public Object flowablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object flowableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toFlowable 转换路径。 */\n    @Benchmark\n    public Object flowableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object flowableDedicated(Blackhole bh) {', '    /** dedicated：switchMapMaybe 专用算子。 */\n    @Benchmark\n    public Object flowableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/FlowableSwitchMapSinglePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Flowable switchMap(Flowable::just) 与 switchMap(Single.toFlowable)、专用 switchMapSingle 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object flowablePlain(Blackhole bh) {', '    /** plain：switchMap(Flowable::just) 基准。 */\n    @Benchmark\n    public Object flowablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object flowableConvert(Blackhole bh) {', '    /** convert：经 Single.toFlowable 转换路径。 */\n    @Benchmark\n    public Object flowableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object flowableDedicated(Blackhole bh) {', '    /** dedicated：switchMapSingle 专用算子。 */\n    @Benchmark\n    public Object flowableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableConcatMapCompletablePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable concatMap(Observable.empty()) 与 concatMap(Completable.toObservable())、专用 concatMapCompletable 的吞吐对比（空序列）。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：concatMap(Observable.empty()) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Completable.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：concatMapCompletable 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableConcatMapMaybeEmptyPerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable concatMap(Observable.empty()) 与 concatMap(Maybe.empty().toObservable())、专用 concatMapMaybe(empty) 的吞吐对比（空序列）。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：concatMap(Observable.empty()) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：concatMapMaybe(empty) 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableConcatMapMaybePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable concatMap(Observable::just) 与 concatMap(Maybe.toObservable())、专用 concatMapMaybe 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：concatMap(Observable::just) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：concatMapMaybe 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableConcatMapSinglePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable concatMap(Observable::just) 与 concatMap(Single.toObservable())、专用 concatMapSingle 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：concatMap(Observable::just) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Single.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：concatMapSingle 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableFlatMapCompletablePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable flatMap(Observable.empty()) 与 flatMap(Completable.toObservable())、专用 flatMapCompletable 的吞吐对比（空序列）。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：flatMap(Observable.empty()) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Completable.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：flatMapCompletable 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableFlatMapMaybeEmptyPerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable flatMap(Observable.empty()) 与 flatMap(Maybe.empty().toObservable())、专用 flatMapMaybe(empty) 的吞吐对比（空序列）。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：flatMap(Observable.empty()) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：flatMapMaybe(empty) 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableFlatMapMaybePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable flatMap(Observable::just) 与 flatMap(Maybe.toObservable())、专用 flatMapMaybe 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：flatMap(Observable::just) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：flatMapMaybe 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableFlatMapSinglePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable flatMap(Observable::just) 与 flatMap(Single.toObservable())、专用 flatMapSingle 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：flatMap(Observable::just) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Single.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：flatMapSingle 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableSwitchMapCompletablePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable switchMap(Observable.empty()) 与 switchMap(Completable.toObservable())、专用 switchMapCompletable 的吞吐对比（空序列）。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：switchMap(Observable.empty()) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Completable.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：switchMapCompletable 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableSwitchMapMaybeEmptyPerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable switchMap(Observable.empty()) 与 switchMap(Maybe.empty().toObservable())、专用 switchMapMaybe(empty) 的吞吐对比（空序列）。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：switchMap(Observable.empty()) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：switchMapMaybe(empty) 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableSwitchMapMaybePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable switchMap(Observable::just) 与 switchMap(Maybe.toObservable())、专用 switchMapMaybe 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：switchMap(Observable::just) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Maybe.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：switchMapMaybe 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
    "src/jmh/java/io/reactivex/rxjava4/xmapz/ObservableSwitchMapSinglePerf.java": [
        ('@BenchmarkMode(Mode.Throughput)', '/**\n * JMH 基准：Observable switchMap(Observable::just) 与 switchMap(Single.toObservable())、专用 switchMapSingle 的吞吐对比。\n */\n@BenchmarkMode(Mode.Throughput)'),
        ('    @Setup\n    public void setup() {', '    /** 按 count 填充源数组，构造 plain/convert/dedicated 三条基准链路。 */\n    @Setup\n    public void setup() {'),
        ('    @Benchmark\n    public Object observablePlain(Blackhole bh) {', '    /** plain：switchMap(Observable::just) 基准。 */\n    @Benchmark\n    public Object observablePlain(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableConvert(Blackhole bh) {', '    /** convert：经 Single.toObservable 转换路径。 */\n    @Benchmark\n    public Object observableConvert(Blackhole bh) {'),
        ('    @Benchmark\n    public Object observableDedicated(Blackhole bh) {', '    /** dedicated：switchMapSingle 专用算子。 */\n    @Benchmark\n    public Object observableDedicated(Blackhole bh) {'),
    ],
}
