"""Chinese JavaDoc replacements for RocketMQ wave46b tools monitor [7:14]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/DefaultMonitorListener.java': [
        ('public class DefaultMonitorListener implements MonitorListener {',
         '/**\n * {@link MonitorListener} 的默认实现：将监控事件输出到 SLF4J 日志。\n * <p>适用于命令行或独立进程中的轻量级监控场景。\n */\npublic class DefaultMonitorListener implements MonitorListener {'),
        ('    private final static String LOG_PREFIX = "[MONITOR] ";',
         '    /** 监控日志统一前缀。 */\n    private final static String LOG_PREFIX = "[MONITOR] ";'),
        ('    private final static String LOG_NOTIFY = LOG_PREFIX + " [NOTIFY] ";',
         '    /** 需运维关注的告警类日志前缀。 */\n    private final static String LOG_NOTIFY = LOG_PREFIX + " [NOTIFY] ";'),
        ('    private final Logger logger = LoggerFactory.getLogger(DefaultMonitorListener.class);',
         '    /** 本监听器使用的日志记录器。 */\n    private final Logger logger = LoggerFactory.getLogger(DefaultMonitorListener.class);'),
        ('    public DefaultMonitorListener() {',
         '    /** 使用默认日志配置构造监听器。 */\n    public DefaultMonitorListener() {'),
        ('    @Override\n    public void beginRound() {',
         '    /** 一轮监控开始时打印分隔日志。 */\n    @Override\n    public void beginRound() {'),
        ('    @Override\n    public void reportUndoneMsgs(UndoneMsgs undoneMsgs) {',
         '    /** 记录未消费消息积压统计。 */\n    @Override\n    public void reportUndoneMsgs(UndoneMsgs undoneMsgs) {'),
        ('    @Override\n    public void reportFailedMsgs(FailedMsgs failedMsgs) {',
         '    /** 记录近期消费失败消息汇总。 */\n    @Override\n    public void reportFailedMsgs(FailedMsgs failedMsgs) {'),
        ('    @Override\n    public void reportDeleteMsgsEvent(DeleteMsgsEvent deleteMsgsEvent) {',
         '    /** 记录 Broker 偏移量迁移导致的消息删除事件。 */\n    @Override\n    public void reportDeleteMsgsEvent(DeleteMsgsEvent deleteMsgsEvent) {'),
        ('    @Override\n    public void reportConsumerRunningInfo(TreeMap<String, ConsumerRunningInfo> criTable) {',
         '    /** 分析并记录消费者运行态：订阅一致性与队列堆积。 */\n    @Override\n    public void reportConsumerRunningInfo(TreeMap<String, ConsumerRunningInfo> criTable) {'),
        ('        if (criTable == null || criTable.isEmpty()) {',
         '        // 无运行态数据时告警\n        if (criTable == null || criTable.isEmpty()) {'),
        ('            boolean result = ConsumerRunningInfo.analyzeSubscription(criTable);',
         '            // 校验同组各客户端订阅是否一致\n            boolean result = ConsumerRunningInfo.analyzeSubscription(criTable);'),
        ('            Iterator<Entry<String, ConsumerRunningInfo>> it = criTable.entrySet().iterator();',
         '            // 逐客户端分析 ProcessQueue 堆积与延迟\n            Iterator<Entry<String, ConsumerRunningInfo>> it = criTable.entrySet().iterator();'),
        ('    @Override\n    public void endRound() {',
         '    /** 一轮监控结束时打印分隔日志。 */\n    @Override\n    public void endRound() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/DeleteMsgsEvent.java': [
        ('public class DeleteMsgsEvent {',
         '/**\n * 消息被删除（偏移量迁移）事件载体。\n * <p>由 {@link MonitorService} 订阅 {@code RMQ_SYS_OFFSET_MOVED_EVENT} 后构造并上报。\n */\npublic class DeleteMsgsEvent {'),
        ('    private OffsetMovedEvent offsetMovedEvent;',
         '    /** Broker 上报的偏移量迁移详情。 */\n    private OffsetMovedEvent offsetMovedEvent;'),
        ('    private long eventTimestamp;',
         '    /** 事件对应消息的存储时间戳（毫秒）。 */\n    private long eventTimestamp;'),
        ('    public OffsetMovedEvent getOffsetMovedEvent() {',
         '    /** @return 偏移量迁移事件体 */\n    public OffsetMovedEvent getOffsetMovedEvent() {'),
        ('    public void setOffsetMovedEvent(OffsetMovedEvent offsetMovedEvent) {',
         '    /** @param offsetMovedEvent 偏移量迁移事件体 */\n    public void setOffsetMovedEvent(OffsetMovedEvent offsetMovedEvent) {'),
        ('    public long getEventTimestamp() {',
         '    /** @return 事件时间戳（毫秒） */\n    public long getEventTimestamp() {'),
        ('    public void setEventTimestamp(long eventTimestamp) {',
         '    /** @param eventTimestamp 事件时间戳（毫秒） */\n    public void setEventTimestamp(long eventTimestamp) {'),
        ('    @Override\n    public String toString() {',
         '    /** @return 便于日志输出的字符串表示 */\n    @Override\n    public String toString() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/FailedMsgs.java': [
        ('public class FailedMsgs {',
         '/**\n * 消费失败消息统计快照。\n * <p>按消费组与 Topic 维度汇总近期失败条数，供 {@link MonitorListener} 上报。\n */\npublic class FailedMsgs {'),
        ('    private String consumerGroup;',
         '    /** 消费组名称。 */\n    private String consumerGroup;'),
        ('    private String topic;',
         '    /** 业务 Topic 名称。 */\n    private String topic;'),
        ('    private long failedMsgsTotalRecently;',
         '    /** 近期消费失败消息总数。 */\n    private long failedMsgsTotalRecently;'),
        ('    public String getConsumerGroup() {',
         '    /** @return 消费组名称 */\n    public String getConsumerGroup() {'),
        ('    public void setConsumerGroup(String consumerGroup) {',
         '    /** @param consumerGroup 消费组名称 */\n    public void setConsumerGroup(String consumerGroup) {'),
        ('    public String getTopic() {',
         '    /** @return Topic 名称 */\n    public String getTopic() {'),
        ('    public void setTopic(String topic) {',
         '    /** @param topic Topic 名称 */\n    public void setTopic(String topic) {'),
        ('    public long getFailedMsgsTotalRecently() {',
         '    /** @return 近期失败消息总数 */\n    public long getFailedMsgsTotalRecently() {'),
        ('    public void setFailedMsgsTotalRecently(long failedMsgsTotalRecently) {',
         '    /** @param failedMsgsTotalRecently 近期失败消息总数 */\n    public void setFailedMsgsTotalRecently(long failedMsgsTotalRecently) {'),
        ('    @Override\n    public String toString() {',
         '    /** @return 便于日志输出的字符串表示 */\n    @Override\n    public String toString() {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/MonitorConfig.java': [
        ('public class MonitorConfig {',
         '/**\n * 监控服务运行配置。\n * <p>默认从系统属性或环境变量读取 NameServer 地址，轮询间隔默认 60 秒。\n */\npublic class MonitorConfig {'),
        ('    private String namesrvAddr = System.getProperty(MixAll.NAMESRV_ADDR_PROPERTY,',
         '    /** NameServer 地址，优先 JVM 属性 {@link MixAll#NAMESRV_ADDR_PROPERTY}。 */\n    private String namesrvAddr = System.getProperty(MixAll.NAMESRV_ADDR_PROPERTY,'),
        ('    private int roundInterval = 1000 * 60;',
         '    /** 每轮监控任务间隔（毫秒），默认 60 秒。 */\n    private int roundInterval = 1000 * 60;'),
        ('    public String getNamesrvAddr() {',
         '    /** @return NameServer 地址 */\n    public String getNamesrvAddr() {'),
        ('    public void setNamesrvAddr(String namesrvAddr) {',
         '    /** @param namesrvAddr NameServer 地址 */\n    public void setNamesrvAddr(String namesrvAddr) {'),
        ('    public int getRoundInterval() {',
         '    /** @return 监控轮询间隔（毫秒） */\n    public int getRoundInterval() {'),
        ('    public void setRoundInterval(int roundInterval) {',
         '    /** @param roundInterval 监控轮询间隔（毫秒） */\n    public void setRoundInterval(int roundInterval) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/MonitorListener.java': [
        ('public interface MonitorListener {',
         '/**\n * 监控事件回调接口。\n * <p>{@link MonitorService} 每轮巡检完成后通过本接口向业务侧上报各类指标与异常。\n */\npublic interface MonitorListener {'),
        ('    void beginRound();',
         '    /** 一轮监控开始前的钩子。 */\n    void beginRound();'),
        ('    void reportUndoneMsgs(UndoneMsgs undoneMsgs);',
         '    /** 上报指定消费组/Topic 的未消费消息积压情况。\n     * @param undoneMsgs 积压统计快照 */\n    void reportUndoneMsgs(UndoneMsgs undoneMsgs);'),
        ('    void reportFailedMsgs(FailedMsgs failedMsgs);',
         '    /** 上报近期消费失败消息统计。\n     * @param failedMsgs 失败消息统计 */\n    void reportFailedMsgs(FailedMsgs failedMsgs);'),
        ('    void reportDeleteMsgsEvent(DeleteMsgsEvent deleteMsgsEvent);',
         '    /** 上报偏移量迁移导致的消息删除事件。\n     * @param deleteMsgsEvent 删除事件详情 */\n    void reportDeleteMsgsEvent(DeleteMsgsEvent deleteMsgsEvent);'),
        ('    void reportConsumerRunningInfo(TreeMap<String/* clientId */, ConsumerRunningInfo> criTable);',
         '    /** 上报消费组各客户端运行态（按 clientId 索引）。\n     * @param criTable 客户端 ID 到 {@link ConsumerRunningInfo} 的有序映射 */\n    void reportConsumerRunningInfo(TreeMap<String/* clientId */, ConsumerRunningInfo> criTable);'),
        ('    void endRound();',
         '    /** 一轮监控结束后的钩子。 */\n    void endRound();'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/MonitorService.java': [
        ('public class MonitorService {',
         '/**\n * RocketMQ 集群监控主服务。\n * <p>定时拉取重试 Topic 消费进度、消费者运行态，并订阅系统 Topic 捕获偏移量迁移事件。\n * <p>可通过 {@link #main(String[])} 独立进程启动。\n */\npublic class MonitorService {'),
        ('    private final Logger logger = LoggerFactory.getLogger(MonitorService.class);',
         '    /** 服务日志记录器。 */\n    private final Logger logger = LoggerFactory.getLogger(MonitorService.class);'),
        ('    private final ScheduledExecutorService scheduledExecutorService = Executors',
         '    /** 单线程调度器，驱动周期性监控任务。 */\n    private final ScheduledExecutorService scheduledExecutorService = Executors'),
        ('    private final MonitorConfig monitorConfig;',
         '    /** 监控配置（NameServer、轮询间隔等）。 */\n    private final MonitorConfig monitorConfig;'),
        ('    private final MonitorListener monitorListener;',
         '    /** 监控事件回调监听器。 */\n    private final MonitorListener monitorListener;'),
        ('    private final DefaultMQAdminExt defaultMQAdminExt;',
         '    /** 管理端扩展，用于查询 Topic、消费统计与运行态。 */\n    private final DefaultMQAdminExt defaultMQAdminExt;'),
        ('    private final DefaultMQPullConsumer defaultMQPullConsumer = new DefaultMQPullConsumer(',
         '    /** 拉取消费者，用于计算队列最大延迟。 */\n    private final DefaultMQPullConsumer defaultMQPullConsumer = new DefaultMQPullConsumer('),
        ('    private final DefaultMQPushConsumer defaultMQPushConsumer = new DefaultMQPushConsumer(',
         '    /** Push 消费者，订阅系统偏移量迁移事件 Topic。 */\n    private final DefaultMQPushConsumer defaultMQPushConsumer = new DefaultMQPushConsumer('),
        ('    public MonitorService(MonitorConfig monitorConfig, MonitorListener monitorListener, RPCHook rpcHook) {',
         '    /**\n     * 构造监控服务并初始化 Admin/Pull/Push 客户端。\n     * @param monitorConfig 运行配置\n     * @param monitorListener 事件回调\n     * @param rpcHook RPC 钩子（可为 null）\n     */\n    public MonitorService(MonitorConfig monitorConfig, MonitorListener monitorListener, RPCHook rpcHook) {'),
        ('            this.defaultMQPushConsumer.subscribe(TopicValidator.RMQ_SYS_OFFSET_MOVED_EVENT, "*");',
         '            // 订阅 Broker 偏移量迁移系统 Topic\n            this.defaultMQPushConsumer.subscribe(TopicValidator.RMQ_SYS_OFFSET_MOVED_EVENT, "*");'),
        ('                @Override\n                public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,',
         '                /** 解码 OffsetMovedEvent 并转发给监听器。 */\n                @Override\n                public ConsumeConcurrentlyStatus consumeMessage(List<MessageExt> msgs,'),
        ('    public static void main(String[] args) throws MQClientException {',
         '    /** 命令行入口：使用默认配置与 {@link DefaultMonitorListener} 启动监控。 */\n    public static void main(String[] args) throws MQClientException {'),
        ('    public static void main0(String[] args, RPCHook rpcHook) throws MQClientException {',
         '    /**\n     * 可注入 RPCHook 的启动入口，并注册 JVM 关闭钩子。\n     * @param args 命令行参数（当前未使用）\n     * @param rpcHook RPC 钩子\n     */\n    public static void main0(String[] args, RPCHook rpcHook) throws MQClientException {'),
        ('    private String instanceName() {',
         '    /** 基于时间戳与 NameServer 地址生成唯一客户端实例名。 */\n    private String instanceName() {'),
        ('    public void start() throws MQClientException {',
         '    /** 启动 Pull/Admin/Push 客户端并调度首轮监控任务。 */\n    public void start() throws MQClientException {'),
        ('    public void shutdown() {',
         '    /** 关闭全部 MQ 客户端。 */\n    public void shutdown() {'),
        ('    private void startScheduleTask() {',
         '    /** 按 {@link MonitorConfig#getRoundInterval()} 固定速率执行 {@link #doMonitorWork()}。 */\n    private void startScheduleTask() {'),
        ('    public void doMonitorWork() throws RemotingException, MQClientException, InterruptedException {',
         '    /**\n     * 执行一轮完整监控：遍历重试 Topic，上报积压与运行态。\n     * @throws RemotingException 远程调用异常\n     * @throws MQClientException 客户端异常\n     * @throws InterruptedException 线程中断\n     */\n    public void doMonitorWork() throws RemotingException, MQClientException, InterruptedException {'),
        ('            if (topic.startsWith(MixAll.RETRY_GROUP_TOPIC_PREFIX)) {',
         '            // 仅处理 %RETRY% 前缀的重试 Topic，对应各消费组\n            if (topic.startsWith(MixAll.RETRY_GROUP_TOPIC_PREFIX)) {'),
        ('    private void reportUndoneMsgs(final String consumerGroup) {',
         '    /** 按消费组汇总各 Topic 未消费消息并回调监听器。 */\n    private void reportUndoneMsgs(final String consumerGroup) {'),
        ('            HashMap<String/* Topic */, ConsumeStats> csByTopic = new HashMap<>();',
         '            // 将 offset 表按 Topic 维度拆分\n            HashMap<String/* Topic */, ConsumeStats> csByTopic = new HashMap<>();'),
        ('    public void reportConsumerRunningInfo(final String consumerGroup) throws InterruptedException,',
         '    /**\n     * 拉取消费组各在线客户端（≥3.1.8）的运行态并上报。\n     * @param consumerGroup 消费组名称\n     */\n    public void reportConsumerRunningInfo(final String consumerGroup) throws InterruptedException,'),
        ('            if (c.getVersion() < MQVersion.Version.V3_1_8_SNAPSHOT.ordinal()) {',
         '            // 低版本客户端不支持运行态查询\n            if (c.getVersion() < MQVersion.Version.V3_1_8_SNAPSHOT.ordinal()) {'),
        ('    private void computeUndoneMsgs(final UndoneMsgs undoneMsgs, final ConsumeStats consumeStats) {',
         '    /**\n     * 根据消费统计计算总积压、单队列最大积压与最大消费延迟。\n     * @param undoneMsgs 待填充的结果对象\n     * @param consumeStats 该 Topic 的消费统计\n     */\n    private void computeUndoneMsgs(final UndoneMsgs undoneMsgs, final ConsumeStats consumeStats) {'),
        ('            // Delay',
         '            // 通过拉取队列末尾消息估算相对 lastTimestamp 的延迟'),
        ('    private void reportFailedMsgs(final String consumerGroup, final String topic) {',
         '    /** 预留：上报指定消费组/Topic 的失败消息统计（当前为空实现）。 */\n    private void reportFailedMsgs(final String consumerGroup, final String topic) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/monitor/UndoneMsgs.java': [
        ('public class UndoneMsgs {',
         '/**\n * 未消费消息积压统计快照。\n * <p>由 {@link MonitorService#computeUndoneMsgs} 填充后通过 {@link MonitorListener} 上报。\n */\npublic class UndoneMsgs {'),
        ('    private String consumerGroup;',
         '    /** 消费组名称。 */\n    private String consumerGroup;'),
        ('    private String topic;',
         '    /** 业务 Topic 名称。 */\n    private String topic;'),
        ('    private long undoneMsgsTotal;',
         '    /** 全部队列积压消息总数（brokerOffset - consumerOffset 之和）。 */\n    private long undoneMsgsTotal;'),
        ('    private long undoneMsgsSingleMQ;',
         '    /** 单个 MessageQueue 上的最大积压条数。 */\n    private long undoneMsgsSingleMQ;'),
        ('    private long undoneMsgsDelayTimeMills;',
         '    /** 估算的最大消费延迟（毫秒）。 */\n    private long undoneMsgsDelayTimeMills;'),
        ('    public String getConsumerGroup() {',
         '    /** @return 消费组名称 */\n    public String getConsumerGroup() {'),
        ('    public void setConsumerGroup(String consumerGroup) {',
         '    /** @param consumerGroup 消费组名称 */\n    public void setConsumerGroup(String consumerGroup) {'),
        ('    public String getTopic() {',
         '    /** @return Topic 名称 */\n    public String getTopic() {'),
        ('    public void setTopic(String topic) {',
         '    /** @param topic Topic 名称 */\n    public void setTopic(String topic) {'),
        ('    public long getUndoneMsgsTotal() {',
         '    /** @return 总积压条数 */\n    public long getUndoneMsgsTotal() {'),
        ('    public void setUndoneMsgsTotal(long undoneMsgsTotal) {',
         '    /** @param undoneMsgsTotal 总积压条数 */\n    public void setUndoneMsgsTotal(long undoneMsgsTotal) {'),
        ('    public long getUndoneMsgsSingleMQ() {',
         '    /** @return 单队列最大积压 */\n    public long getUndoneMsgsSingleMQ() {'),
        ('    public void setUndoneMsgsSingleMQ(long undoneMsgsSingleMQ) {',
         '    /** @param undoneMsgsSingleMQ 单队列最大积压 */\n    public void setUndoneMsgsSingleMQ(long undoneMsgsSingleMQ) {'),
        ('    public long getUndoneMsgsDelayTimeMills() {',
         '    /** @return 最大消费延迟（毫秒） */\n    public long getUndoneMsgsDelayTimeMills() {'),
        ('    public void setUndoneMsgsDelayTimeMills(long undoneMsgsDelayTimeMills) {',
         '    /** @param undoneMsgsDelayTimeMills 最大消费延迟（毫秒） */\n    public void setUndoneMsgsDelayTimeMills(long undoneMsgsDelayTimeMills) {'),
        ('    @Override\n    public String toString() {',
         '    /** @return 便于日志输出的字符串表示 */\n    @Override\n    public String toString() {'),
    ],
}
