"""Chinese JavaDoc replacements for RocketMQ wave42a tieredstore metadata/provider/stream/util [0:15]."""

R: dict[str, list[tuple[str, str]]] = {
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metadata/entity/FileSegmentMetadata.java': [
        ('public class FileSegmentMetadata',
         '/**\n * 文件段元数据：描述分层存储中单个文件段的路径、类型、偏移、状态与时间戳。\n */\npublic class FileSegmentMetadata'),
        ('    public static final int STATUS_NEW = 0;',
         '    /** 新建状态，尚未封存。 */\n    public static final int STATUS_NEW = 0;'),
        ('    public static final int STATUS_SEALED = 1;',
         '    /** 已封存，不再追加写入。 */\n    public static final int STATUS_SEALED = 1;'),
        ('    public static final int STATUS_DELETED = 2;',
         '    /** 已标记删除。 */\n    public static final int STATUS_DELETED = 2;'),
        ('    @JSONField(ordinal = 1)\n    private String path;',
         '    /** 文件段在元数据中的相对路径。 */\n    @JSONField(ordinal = 1)\n    private String path;'),
        ('    @JSONField(ordinal = 2)\n    private int type;',
         '    /** 文件段类型编码，对应 {@link org.apache.rocketmq.tieredstore.common.FileSegmentType}。 */\n    @JSONField(ordinal = 2)\n    private int type;'),
        ('    @JSONField(ordinal = 3)\n    private long baseOffset;',
         '    /** 文件段起始逻辑偏移。 */\n    @JSONField(ordinal = 3)\n    private long baseOffset;'),
        ('    @JSONField(ordinal = 4)\n    private int status;',
         '    /** 当前状态：新建、封存或删除。 */\n    @JSONField(ordinal = 4)\n    private int status;'),
        ('    @JSONField(ordinal = 5)\n    private long size;',
         '    /** 文件段字节大小。 */\n    @JSONField(ordinal = 5)\n    private long size;'),
        ('    @JSONField(ordinal = 6)\n    private long createTimestamp;',
         '    /** 创建时间戳（毫秒）。 */\n    @JSONField(ordinal = 6)\n    private long createTimestamp;'),
        ('    @JSONField(ordinal = 7)\n    private long beginTimestamp;',
         '    /** 段内最早消息存储时间戳。 */\n    @JSONField(ordinal = 7)\n    private long beginTimestamp;'),
        ('    @JSONField(ordinal = 8)\n    private long endTimestamp;',
         '    /** 段内最晚消息存储时间戳。 */\n    @JSONField(ordinal = 8)\n    private long endTimestamp;'),
        ('    @JSONField(ordinal = 9)\n    private long sealTimestamp;',
         '    /** 封存时间戳（毫秒）。 */\n    @JSONField(ordinal = 9)\n    private long sealTimestamp;'),
        ('    // default constructor is used by fastjson',
         '    // fastjson 反序列化使用的默认构造器'),
        ('    public void markSealed() {',
         '    /** 标记为已封存并记录封存时间。 */\n    public void markSealed() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metadata/entity/QueueMetadata.java': [
        ('public class QueueMetadata',
         '/**\n * 队列元数据：记录 MessageQueue 在分层存储中的最小/最大偏移及更新时间。\n */\npublic class QueueMetadata'),
        ('    @JSONField(ordinal = 1)\n    private MessageQueue queue;',
         '    /** 关联的 MessageQueue（Topic、Broker、QueueId）。 */\n    @JSONField(ordinal = 1)\n    private MessageQueue queue;'),
        ('    @JSONField(ordinal = 2)\n    private long minOffset;',
         '    /** 分层存储中该队列的最小逻辑偏移。 */\n    @JSONField(ordinal = 2)\n    private long minOffset;'),
        ('    @JSONField(ordinal = 3)\n    private long maxOffset;',
         '    /** 分层存储中该队列的最大逻辑偏移。 */\n    @JSONField(ordinal = 3)\n    private long maxOffset;'),
        ('    @JSONField(ordinal = 4)\n    private long updateTimestamp;',
         '    /** 元数据最后更新时间戳。 */\n    @JSONField(ordinal = 4)\n    private long updateTimestamp;'),
        ('    // default constructor is used by fastjson',
         '    // fastjson 反序列化使用的默认构造器'),
        ('    public QueueMetadata(MessageQueue queue, long minOffset, long maxOffset) {',
         '    /** 构造队列元数据并设置当前更新时间。 */\n    public QueueMetadata(MessageQueue queue, long minOffset, long maxOffset) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metadata/entity/TopicMetadata.java': [
        ('public class TopicMetadata',
         '/**\n * Topic 元数据：维护 Topic 数值 ID、名称、保留时长与状态。\n */\npublic class TopicMetadata'),
        ('    @JSONField(ordinal = 1)\n    private long topicId;',
         '    /** Topic 数值 ID，用于索引与路径哈希。 */\n    @JSONField(ordinal = 1)\n    private long topicId;'),
        ('    @JSONField(ordinal = 2)\n    private String topic;',
         '    /** Topic 名称。 */\n    @JSONField(ordinal = 2)\n    private String topic;'),
        ('    @JSONField(ordinal = 3)\n    private int status;',
         '    /** Topic 在分层存储中的状态。 */\n    @JSONField(ordinal = 3)\n    private int status;'),
        ('    @JSONField(ordinal = 4)\n    private long reserveTime;',
         '    /** 消息保留时长（毫秒）。 */\n    @JSONField(ordinal = 4)\n    private long reserveTime;'),
        ('    @JSONField(ordinal = 5)\n    private long updateTimestamp;',
         '    /** 元数据最后更新时间戳。 */\n    @JSONField(ordinal = 5)\n    private long updateTimestamp;'),
        ('    // default constructor is used by fastjson',
         '    // fastjson 反序列化使用的默认构造器'),
        ('    public TopicMetadata(long topicId, String topic, long reserveTime) {',
         '    /** 构造 Topic 元数据并记录更新时间。 */\n    public TopicMetadata(long topicId, String topic, long reserveTime) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsConstant.java': [
        ('public class TieredStoreMetricsConstant',
         '/**\n * 分层存储 OpenTelemetry 指标名与标签常量。\n */\npublic class TieredStoreMetricsConstant'),
        ('    public static final String HISTOGRAM_API_LATENCY =',
         '    /** API 调用延迟直方图指标名。 */\n    public static final String HISTOGRAM_API_LATENCY ='),
        ('    public static final String HISTOGRAM_PROVIDER_RPC_LATENCY =',
         '    /** 存储 Provider RPC 延迟直方图指标名。 */\n    public static final String HISTOGRAM_PROVIDER_RPC_LATENCY ='),
        ('    public static final String HISTOGRAM_UPLOAD_BYTES =',
         '    /** 上传字节数直方图指标名。 */\n    public static final String HISTOGRAM_UPLOAD_BYTES ='),
        ('    public static final String HISTOGRAM_DOWNLOAD_BYTES =',
         '    /** 下载字节数直方图指标名。 */\n    public static final String HISTOGRAM_DOWNLOAD_BYTES ='),
        ('    public static final String GAUGE_DISPATCH_BEHIND =',
         '    /** 分发滞后消息数 Gauge 指标名。 */\n    public static final String GAUGE_DISPATCH_BEHIND ='),
        ('    public static final String GAUGE_DISPATCH_LATENCY =',
         '    /** 分发延迟 Gauge 指标名。 */\n    public static final String GAUGE_DISPATCH_LATENCY ='),
        ('    public static final String COUNTER_MESSAGES_DISPATCH_TOTAL =',
         '    /** 已分发消息总数 Counter 指标名。 */\n    public static final String COUNTER_MESSAGES_DISPATCH_TOTAL ='),
        ('    public static final String COUNTER_MESSAGES_OUT_TOTAL =',
         '    /** 对外输出消息总数 Counter 指标名。 */\n    public static final String COUNTER_MESSAGES_OUT_TOTAL ='),
        ('    public static final String COUNTER_GET_MESSAGE_FALLBACK_TOTAL =',
         '    /** 拉取消息回退下层 Store 次数 Counter 指标名。 */\n    public static final String COUNTER_GET_MESSAGE_FALLBACK_TOTAL ='),
        ('    public static final String GAUGE_CACHE_COUNT =',
         '    /** 预读缓存消息条数 Gauge 指标名。 */\n    public static final String GAUGE_CACHE_COUNT ='),
        ('    public static final String GAUGE_CACHE_BYTES =',
         '    /** 预读缓存占用字节 Gauge 指标名。 */\n    public static final String GAUGE_CACHE_BYTES ='),
        ('    public static final String COUNTER_CACHE_ACCESS =',
         '    /** 缓存访问次数 Counter 指标名。 */\n    public static final String COUNTER_CACHE_ACCESS ='),
        ('    public static final String COUNTER_CACHE_HIT =',
         '    /** 缓存命中次数 Counter 指标名。 */\n    public static final String COUNTER_CACHE_HIT ='),
        ('    public static final String GAUGE_STORAGE_MESSAGE_RESERVE_TIME =',
         '    /** 消息保留时长 Gauge 指标名。 */\n    public static final String GAUGE_STORAGE_MESSAGE_RESERVE_TIME ='),
        ('    public static final String LABEL_OPERATION = "operation";',
         '    /** 操作类型标签名。 */\n    public static final String LABEL_OPERATION = "operation";'),
        ('    public static final String LABEL_SUCCESS = "success";',
         '    /** 操作是否成功标签名。 */\n    public static final String LABEL_SUCCESS = "success";'),
        ('    public static final String LABEL_PATH = "path";',
         '    /** 文件路径标签名。 */\n    public static final String LABEL_PATH = "path";'),
        ('    public static final String LABEL_TOPIC = "topic";',
         '    /** Topic 标签名。 */\n    public static final String LABEL_TOPIC = "topic";'),
        ('    public static final String LABEL_GROUP = "group";',
         '    /** 消费者组标签名。 */\n    public static final String LABEL_GROUP = "group";'),
        ('    public static final String LABEL_QUEUE_ID = "queue_id";',
         '    /** 队列 ID 标签名。 */\n    public static final String LABEL_QUEUE_ID = "queue_id";'),
        ('    public static final String LABEL_FILE_TYPE = "file_type";',
         '    /** 文件段类型标签名。 */\n    public static final String LABEL_FILE_TYPE = "file_type";'),
        ('    // blob constants',
         '    // 对象存储介质常量'),
        ('    public static final String STORAGE_MEDIUM_BLOB = "blob";',
         '    /** 对象存储（Blob）介质标识。 */\n    public static final String STORAGE_MEDIUM_BLOB = "blob";'),
        ('    public static final String OPERATION_API_GET_MESSAGE = "get_message";',
         '    /** getMessage API 操作名。 */\n    public static final String OPERATION_API_GET_MESSAGE = "get_message";'),
        ('    public static final String OPERATION_API_GET_EARLIEST_MESSAGE_TIME = "get_earliest_message_time";',
         '    /** getEarliestMessageTime API 操作名。 */\n    public static final String OPERATION_API_GET_EARLIEST_MESSAGE_TIME = "get_earliest_message_time";'),
        ('    public static final String OPERATION_API_GET_TIME_BY_OFFSET = "get_time_by_offset";',
         '    /** getMessageStoreTimeStamp API 操作名。 */\n    public static final String OPERATION_API_GET_TIME_BY_OFFSET = "get_time_by_offset";'),
        ('    public static final String OPERATION_API_GET_OFFSET_BY_TIME = "get_offset_by_time";',
         '    /** getOffsetInQueueByTime API 操作名。 */\n    public static final String OPERATION_API_GET_OFFSET_BY_TIME = "get_offset_by_time";'),
        ('    public static final String OPERATION_API_QUERY_MESSAGE = "query_message";',
         '    /** queryMessage API 操作名。 */\n    public static final String OPERATION_API_QUERY_MESSAGE = "query_message";'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metrics/TieredStoreMetricsManager.java': [
        ('public class TieredStoreMetricsManager',
         '/**\n * 分层存储指标管理器：注册 OpenTelemetry 指标并采集分发、缓存与存储用量。\n */\npublic class TieredStoreMetricsManager'),
        ('    private static final Logger log = LoggerFactory.getLogger(MessageStoreUtil.TIERED_STORE_LOGGER_NAME);',
         '    /** 分层存储模块日志。 */\n    private static final Logger log = LoggerFactory.getLogger(MessageStoreUtil.TIERED_STORE_LOGGER_NAME);'),
        ('    public static Supplier<AttributesBuilder> attributesBuilderSupplier;',
         '    /** 全局 Attributes 构建器供应器。 */\n    public static Supplier<AttributesBuilder> attributesBuilderSupplier;'),
        ('    private static String storageMedium = STORAGE_MEDIUM_BLOB;',
         '    /** 当前存储介质标识（默认 blob）。 */\n    private static String storageMedium = STORAGE_MEDIUM_BLOB;'),
        ('    public static LongHistogram apiLatency = new NopLongHistogram();',
         '    /** 分层 Store API 延迟直方图。 */\n    public static LongHistogram apiLatency = new NopLongHistogram();'),
        ('    // tiered store provider metrics',
         '    // 分层存储 Provider 侧指标'),
        ('    public static LongHistogram providerRpcLatency = new NopLongHistogram();',
         '    /** Provider RPC 延迟直方图。 */\n    public static LongHistogram providerRpcLatency = new NopLongHistogram();'),
        ('    public static LongHistogram uploadBytes = new NopLongHistogram();',
         '    /** 上传字节数直方图。 */\n    public static LongHistogram uploadBytes = new NopLongHistogram();'),
        ('    public static LongHistogram downloadBytes = new NopLongHistogram();',
         '    /** 下载字节数直方图。 */\n    public static LongHistogram downloadBytes = new NopLongHistogram();'),
        ('    public static ObservableLongGauge dispatchBehind = new NopObservableLongGauge();',
         '    /** 分发滞后消息数 Gauge。 */\n    public static ObservableLongGauge dispatchBehind = new NopObservableLongGauge();'),
        ('    public static ObservableLongGauge dispatchLatency = new NopObservableLongGauge();',
         '    /** 分发延迟 Gauge。 */\n    public static ObservableLongGauge dispatchLatency = new NopObservableLongGauge();'),
        ('    public static LongCounter messagesDispatchTotal = new NopLongCounter();',
         '    /** 已分发消息总数 Counter。 */\n    public static LongCounter messagesDispatchTotal = new NopLongCounter();'),
        ('    public static LongCounter messagesOutTotal = new NopLongCounter();',
         '    /** 对外输出消息总数 Counter。 */\n    public static LongCounter messagesOutTotal = new NopLongCounter();'),
        ('    public static LongCounter fallbackTotal = new NopLongCounter();',
         '    /** 拉取回退下层 Store 次数 Counter。 */\n    public static LongCounter fallbackTotal = new NopLongCounter();'),
        ('    public static ObservableLongGauge cacheCount = new NopObservableLongGauge();',
         '    /** 预读缓存消息条数 Gauge。 */\n    public static ObservableLongGauge cacheCount = new NopObservableLongGauge();'),
        ('    public static ObservableLongGauge cacheBytes = new NopObservableLongGauge();',
         '    /** 预读缓存占用字节 Gauge。 */\n    public static ObservableLongGauge cacheBytes = new NopObservableLongGauge();'),
        ('    public static LongCounter cacheAccess = new NopLongCounter();',
         '    /** 缓存访问次数 Counter。 */\n    public static LongCounter cacheAccess = new NopLongCounter();'),
        ('    public static LongCounter cacheHit = new NopLongCounter();',
         '    /** 缓存命中次数 Counter。 */\n    public static LongCounter cacheHit = new NopLongCounter();'),
        ('    public static ObservableLongGauge storageSize = new NopObservableLongGauge();',
         '    /** Broker 分层存储占用字节 Gauge。 */\n    public static ObservableLongGauge storageSize = new NopObservableLongGauge();'),
        ('    public static ObservableLongGauge storageMessageReserveTime = new NopObservableLongGauge();',
         '    /** 消息保留时长 Gauge。 */\n    public static ObservableLongGauge storageMessageReserveTime = new NopObservableLongGauge();'),
        ('    public static List<Pair<InstrumentSelector, ViewBuilder>> getMetricsView() {',
         '    /** 返回分层存储直方图的自定义分桶 View 配置。 */\n    public static List<Pair<InstrumentSelector, ViewBuilder>> getMetricsView() {'),
        ('    public static void setStorageMedium(String storageMedium) {',
         '    /** 设置存储介质标签值。 */\n    public static void setStorageMedium(String storageMedium) {'),
        ('    public static void init(Meter meter, Supplier<AttributesBuilder> attributesBuilderSupplier,',
         '    /** 注册全部 OpenTelemetry 指标并绑定回调采集逻辑。 */\n    public static void init(Meter meter, Supplier<AttributesBuilder> attributesBuilderSupplier,'),
        ('    public static AttributesBuilder newAttributesBuilder() {',
         '    /** 创建带 storage_type=tiered 与介质标签的 Attributes 构建器。 */\n    public static AttributesBuilder newAttributesBuilder() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/FileSegment.java': [
        ('public abstract class FileSegment implements Comparable<FileSegment>, FileSegmentProvider',
         '/**\n * 文件段抽象基类：管理缓冲追加、异步组提交与偏移校正。\n */\npublic abstract class FileSegment implements Comparable<FileSegment>, FileSegmentProvider'),
        ('    protected static final Long GET_FILE_SIZE_ERROR = -1L;',
         '    /** 获取远程文件大小失败时的返回值。 */\n    protected static final Long GET_FILE_SIZE_ERROR = -1L;'),
        ('    protected final long baseOffset;',
         '    /** 文件段起始逻辑偏移。 */\n    protected final long baseOffset;'),
        ('    protected final String filePath;',
         '    /** 元数据中的相对文件路径。 */\n    protected final String filePath;'),
        ('    protected final FileSegmentType fileType;',
         '    /** 文件段类型。 */\n    protected final FileSegmentType fileType;'),
        ('    protected final MessageStoreConfig storeConfig;',
         '    /** 分层存储配置。 */\n    protected final MessageStoreConfig storeConfig;'),
        ('    protected final long maxSize;',
         '    /** 该类型文件段允许的最大字节数。 */\n    protected final long maxSize;'),
        ('    protected final MessageStoreExecutor executor;',
         '    /** 异步读写线程池执行器。 */\n    protected final MessageStoreExecutor executor;'),
        ('    protected final ReentrantLock fileLock = new ReentrantLock();',
         '    /** 保护缓冲与位置字段的可重入锁。 */\n    protected final ReentrantLock fileLock = new ReentrantLock();'),
        ('    protected final Semaphore commitLock = new Semaphore(1);',
         '    /** 限制同一文件段并发提交的信号量。 */\n    protected final Semaphore commitLock = new Semaphore(1);'),
        ('    protected volatile boolean closed = false;',
         '    /** 文件段是否已关闭。 */\n    protected volatile boolean closed = false;'),
        ('    protected volatile long minTimestamp = Long.MAX_VALUE;',
         '    /** 段内最早消息存储时间戳。 */\n    protected volatile long minTimestamp = Long.MAX_VALUE;'),
        ('    protected volatile long maxTimestamp = Long.MAX_VALUE;',
         '    /** 段内最晚消息存储时间戳。 */\n    protected volatile long maxTimestamp = Long.MAX_VALUE;'),
        ('    protected volatile long commitPosition = 0L;',
         '    /** 已提交到后端的文件内偏移。 */\n    protected volatile long commitPosition = 0L;'),
        ('    protected volatile long appendPosition = 0L;',
         '    /** 已追加到内存缓冲的文件内偏移。 */\n    protected volatile long appendPosition = 0L;'),
        ('    protected volatile List<ByteBuffer> bufferList = new ArrayList<>();',
         '    /** 待组提交的上传缓冲列表。 */\n    protected volatile List<ByteBuffer> bufferList = new ArrayList<>();'),
        ('    protected volatile FileSegmentInputStream fileSegmentInputStream;',
         '    /** 当前进行中的提交输入流。 */\n    protected volatile FileSegmentInputStream fileSegmentInputStream;'),
        ('    protected volatile CompletableFuture<Boolean> flightCommitRequest;',
         '    /** 进行中的异步提交 Future。 */\n    protected volatile CompletableFuture<Boolean> flightCommitRequest;'),
        ('    public void initPosition(long pos) {',
         '    /** 初始化提交与追加位置（恢复场景）。 */\n    public void initPosition(long pos) {'),
        ('    public long getMaxSizeByFileType() {',
         '    /** 按文件段类型返回配置的最大尺寸。 */\n    public long getMaxSizeByFileType() {'),
        ('    protected List<ByteBuffer> borrowBuffer() {',
         '    /** 借出并清空当前待提交缓冲列表。 */\n    protected List<ByteBuffer> borrowBuffer() {'),
        ('    protected void updateTimestamp(long timestamp) {',
         '    /** 更新段内最小/最大消息时间戳。 */\n    protected void updateTimestamp(long timestamp) {'),
        ('    public AppendResult append(ByteBuffer buffer, long timestamp) {',
         '    /** 追加字节缓冲并更新时间与追加位置。 */\n    public AppendResult append(ByteBuffer buffer, long timestamp) {'),
        ('    public boolean needCommit() {',
         '    /** 是否存在未提交的追加数据。 */\n    public boolean needCommit() {'),
        ('    public CompletableFuture<Boolean> commitAsync() {',
         '    /** 异步组提交待上传缓冲到后端存储。 */\n    public CompletableFuture<Boolean> commitAsync() {'),
        ('        // acquire lock',
         '        // 获取提交锁，避免并发提交'),
        ('        // handle last commit error',
         '        // 处理上次提交失败后的偏移校正'),
        ('        // Get root cause here',
         '        // 提取异常根因以校正提交偏移'),
        ('    /**\n     * return true to clear buffer\n     */',
         '    /**\n     * 根据后端报告的文件大小校正 commitPosition；返回 true 表示可清空缓冲。\n     */'),
        ('        // Current we have three offsets here: commit offset, expect offset, file size.',
         '        // 当前存在 commit、期望与远端文件大小三个偏移'),
        ('        // We guarantee that the commit offset is less than or equal to the expect offset.',
         '        // 保证 commit 偏移不超过期望偏移'),
        ('        // Max offset will increase because we can continuously put in new buffers',
         '        // 持续追加时 append 偏移会增大'),
        ('        // We are believing that the file size returned by the server is correct,',
         '        // 假定后端返回的文件大小可信，'),
        ('        // can reset the commit offset to the file size reported by the storage system.',
         '        // 可将 commit 偏移重置为存储系统报告的大小'),
        ('    public ByteBuffer read(long position, int length) {',
         '    /** 同步读取指定区间数据。 */\n    public ByteBuffer read(long position, int length) {'),
        ('    public CompletableFuture<ByteBuffer> readAsync(long position, int length) {',
         '    /** 异步读取已提交区间内的数据。 */\n    public CompletableFuture<ByteBuffer> readAsync(long position, int length) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/FileSegmentFactory.java': [
        ('public class FileSegmentFactory',
         '/**\n * 文件段工厂：按配置反射创建 {@link FileSegment} 实现实例。\n */\npublic class FileSegmentFactory'),
        ('    private final MetadataStore metadataStore;',
         '    /** 元数据存储引用。 */\n    private final MetadataStore metadataStore;'),
        ('    private final MessageStoreConfig storeConfig;',
         '    /** 分层存储配置。 */\n    private final MessageStoreConfig storeConfig;'),
        ('    private final MessageStoreExecutor executor;',
         '    /** 异步 I/O 执行器。 */\n    private final MessageStoreExecutor executor;'),
        ('    private final Constructor<? extends FileSegment> fileSegmentConstructor;',
         '    /** 反射得到的 FileSegment 构造器。 */\n    private final Constructor<? extends FileSegment> fileSegmentConstructor;'),
        ('    public MetadataStore getMetadataStore() {',
         '    /** 返回关联的元数据存储。 */\n    public MetadataStore getMetadataStore() {'),
        ('    public MessageStoreConfig getStoreConfig() {',
         '    /** 返回分层存储配置。 */\n    public MessageStoreConfig getStoreConfig() {'),
        ('    public FileSegment createSegment(FileSegmentType fileType, String filePath, long baseOffset) {',
         '    /** 创建指定类型与偏移的文件段。 */\n    public FileSegment createSegment(FileSegmentType fileType, String filePath, long baseOffset) {'),
        ('    public FileSegment createCommitLogFileSegment(String filePath, long baseOffset) {',
         '    /** 创建 CommitLog 文件段。 */\n    public FileSegment createCommitLogFileSegment(String filePath, long baseOffset) {'),
        ('    public FileSegment createConsumeQueueFileSegment(String filePath, long baseOffset) {',
         '    /** 创建 ConsumeQueue 文件段。 */\n    public FileSegment createConsumeQueueFileSegment(String filePath, long baseOffset) {'),
        ('    public FileSegment createIndexServiceFileSegment(String filePath, long baseOffset) {',
         '    /** 创建 Index 文件段。 */\n    public FileSegment createIndexServiceFileSegment(String filePath, long baseOffset) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/FileSegmentProvider.java': [
        ('public interface FileSegmentProvider',
         '/**\n * 后端文件段 Provider 接口：定义路径、大小、读写与生命周期操作。\n */\npublic interface FileSegmentProvider'),
        ('    /**\n     * Get file path in backend file system\n     *\n     * @return file real path\n     */',
         '    /**\n     * 获取后端文件系统中的文件路径。\n     *\n     * @return 文件实际路径\n     */'),
        ('    /**\n     * Get the real length of the file.\n     * Return 0 if the file does not exist,\n     * Return -1 if system get size failed.\n     *\n     * @return file real size\n     */',
         '    /**\n     * 获取文件实际长度。\n     * 文件不存在时返回 0，获取失败时返回 -1。\n     *\n     * @return 文件实际字节大小\n     */'),
        ('    /**\n     * Is file exists in backend file system\n     *\n     * @return <code>true</code> if file with given path exists; <code>false</code> otherwise\n     */',
         '    /**\n     * 判断后端文件系统中文件是否存在。\n     *\n     * @return 存在返回 <code>true</code>，否则 <code>false</code>\n     */'),
        ('    /**\n     * Create file in backend file system\n     */',
         '    /**\n     * 在后端文件系统中创建文件。\n     */'),
        ('    /**\n     * Destroy file with given path in backend file system\n     */',
         '    /**\n     * 销毁后端文件系统中指定路径的文件。\n     */'),
        ('    /**\n     * Get data from backend file system\n     *\n     * @param position the index from where the file will be read\n     * @param length   the data size will be read\n     * @return data to be read\n     */',
         '    /**\n     * 从后端文件系统读取数据。\n     *\n     * @param position 读取起始文件内偏移\n     * @param length   读取字节数\n     * @return 读取到的数据缓冲\n     */'),
        ('    /**\n     * Put data to backend file system\n     *\n     * @param inputStream data stream\n     * @param position    backend file position to put, used in append mode\n     * @param length      data size in stream\n     * @param append      try to append or create a new file\n     * @return put result, <code>true</code> if data successfully write; <code>false</code> otherwise\n     */',
         '    /**\n     * 向后端文件系统写入数据。\n     *\n     * @param inputStream 待写入的数据流\n     * @param position    写入起始文件内偏移（追加模式）\n     * @param length      流中数据字节数\n     * @param append      是否以追加方式写入\n     * @return 写入成功返回 <code>true</code>，否则 <code>false</code>\n     */'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/MemoryFileSegment.java': [
        ('public class MemoryFileSegment extends FileSegment',
         '/**\n * 内存文件段实现：用于单元测试，数据保存在堆内 ByteBuffer。\n */\npublic class MemoryFileSegment extends FileSegment'),
        ('    protected final ByteBuffer memStore;',
         '    /** 堆内模拟存储缓冲。 */\n    protected final ByteBuffer memStore;'),
        ('    protected CompletableFuture<Boolean> blocker;',
         '    /** 测试用提交阻塞 Future。 */\n    protected CompletableFuture<Boolean> blocker;'),
        ('    protected int size = 0;',
         '    /** 模拟文件大小（checkSize 关闭时使用）。 */\n    protected int size = 0;'),
        ('    protected boolean checkSize = true;',
         '    /** 是否返回固定测试大小 1000。 */\n    protected boolean checkSize = true;'),
        ('    public ByteBuffer getMemStore() {',
         '    /** 返回底层内存缓冲（测试用）。 */\n    public ByteBuffer getMemStore() {'),
        ('    public void setCheckSize(boolean checkSize) {',
         '    /** 设置是否使用固定测试文件大小。 */\n    public void setCheckSize(boolean checkSize) {'),
        ('    public void setSize(int size) {',
         '    /** 设置模拟文件大小。 */\n    public void setSize(int size) {'),
        ('    public CompletableFuture<ByteBuffer> read0(long position, int length) {',
         '    /** 从内存缓冲切片读取指定区间。 */\n    public CompletableFuture<ByteBuffer> read0(long position, int length) {'),
        ('    public CompletableFuture<Boolean> commit0(',
         '    /** 将输入流数据写入内存缓冲（测试用）。 */\n    public CompletableFuture<Boolean> commit0('),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/provider/PosixFileSegment.java': [
        ('/**\n * this class is experimental and may change without notice.\n */',
         '/**\n * 基于本地 POSIX 文件系统的 FileSegment 实现（实验性，可能无预告变更）。\n */'),
        ('    private static final String OPERATION_POSIX_READ = "read";',
         '    /** POSIX 读操作指标标签值。 */\n    private static final String OPERATION_POSIX_READ = "read";'),
        ('    private static final String OPERATION_POSIX_WRITE = "write";',
         '    /** POSIX 写操作指标标签值。 */\n    private static final String OPERATION_POSIX_WRITE = "write";'),
        ('    private final String fullPath;',
         '    /** 本地磁盘完整文件路径。 */\n    private final String fullPath;'),
        ('    private volatile File file;',
         '    /** 底层本地文件对象。 */\n    private volatile File file;'),
        ('    private volatile FileChannel readFileChannel;',
         '    /** 只读 FileChannel。 */\n    private volatile FileChannel readFileChannel;'),
        ('    private volatile FileChannel writeFileChannel;',
         '    /** 读写 FileChannel（提交时 force）。 */\n    private volatile FileChannel writeFileChannel;'),
        ('        // basePath',
         '        // 分层存储根目录'),
        ('        // fullPath: basePath/hash_cluster/broker/topic/queueId/fileType/baseOffset',
         '        // 完整路径：basePath/hash_cluster/broker/topic/queueId/fileType/baseOffset'),
        ('    protected AttributesBuilder newAttributesBuilder() {',
         '    /** 创建带 path 与 file_type 标签的指标 Attributes。 */\n    protected AttributesBuilder newAttributesBuilder() {'),
        ('    public CompletableFuture<ByteBuffer> read0(long position, int length) {',
         '    /** 异步从本地文件读取并记录 RPC 与下载字节指标。 */\n    public CompletableFuture<ByteBuffer> read0(long position, int length) {'),
        ('    public CompletableFuture<Boolean> commit0(',
         '    /** 异步写入本地文件并 force 刷盘，记录上传指标。 */\n    public CompletableFuture<Boolean> commit0('),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/stream/CommitLogInputStream.java': [
        ('public class CommitLogInputStream extends FileSegmentInputStream',
         '/**\n * CommitLog 上传输入流：读取时重写物理偏移字段以匹配分层存储偏移。\n */\npublic class CommitLogInputStream extends FileSegmentInputStream'),
        ('    /**\n     * commitLogOffset is the real physical offset of the commitLog buffer which is being read\n     */',
         '    /** 当前正在读取的 CommitLog 缓冲对应的物理偏移。 */'),
        ('    private final long startCommitLogOffset;',
         '    /** 流起始 CommitLog 物理偏移。 */\n    private final long startCommitLogOffset;'),
        ('    private long commitLogOffset;',
         '    /** 当前读指针对应的 CommitLog 物理偏移。 */\n    private long commitLogOffset;'),
        ('    private final ByteBuffer codaBuffer;',
         '    /** CommitLog 段尾 coda 缓冲（可选）。 */\n    private final ByteBuffer codaBuffer;'),
        ('    private long markCommitLogOffset = -1;',
         '    /** mark 时保存的 CommitLog 偏移。 */\n    private long markCommitLogOffset = -1;'),
        ('                // read from coda buffer',
         '                // 从 coda 尾段缓冲读取'),
        ('                // update flags',
         '                // 更新读指针与偏移'),
        ('                // read from commitLog buffer',
         '                // 从 CommitLog 缓冲读取'),
        ('                // read from converted PHYSICAL_OFFSET_POSITION',
         '                // 从转换后的物理偏移字段读取'),
        ('                // read from next buf',
         '                // 切换到下一段缓冲'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/stream/FileSegmentInputStream.java': [
        ('public class FileSegmentInputStream extends InputStream',
         '/**\n * 文件段上传输入流：串联多个 ByteBuffer 供组提交读取。\n */\npublic class FileSegmentInputStream extends InputStream'),
        ('    /**\n     * file type, can be commitlog, consume queue or indexfile now\n     */',
         '    /** 文件段类型：CommitLog、ConsumeQueue 或 Index。 */'),
        ('    /**\n     * hold bytebuffer\n     */',
         '    /** 待上传的 ByteBuffer 列表。 */'),
        ('    /**\n     * total remaining of bytebuffer list\n     */',
         '    /** ByteBuffer 列表的总可读字节数。 */'),
        ('    /**\n     * readPosition is the now position in the stream\n     */',
         '    /** 当前在流中的全局读位置。 */'),
        ('    /**\n     * curReadBufferIndex is the index of the buffer in uploadBufferList which is being read\n     */',
         '    /** 当前正在读取的 bufferList 索引。 */'),
        ('    /**\n     * readPosInCurBuffer is the position in the buffer which is being read\n     */',
         '    /** 当前 buffer 内的读位置。 */'),
        ('    /**\n     * curBuffer is the buffer which is being read, it is the same as uploadBufferList.get(curReadBufferIndex)\n     */',
         '    /** 当前正在读取的 ByteBuffer，等同于 bufferList.get(curReadBufferIndex)。 */'),
        ('    public synchronized void rewind() {',
         '    /** 重置所有缓冲与读指针到起始位置。 */\n    public synchronized void rewind() {'),
        ('    public int getContentLength() {',
         '    /** 返回流总内容长度。 */\n    public int getContentLength() {'),
        ('            // read from curBuf',
         '            // 从当前 ByteBuffer 读取'),
        ('                // read from next buf',
         '                // 切换到下一段缓冲'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/stream/FileSegmentInputStreamFactory.java': [
        ('public class FileSegmentInputStreamFactory',
         '/**\n * 文件段输入流工厂：按文件段类型构建对应 InputStream。\n */\npublic class FileSegmentInputStreamFactory'),
        ('    public static FileSegmentInputStream build(',
         '    /** 按类型创建 FileSegmentInputStream，CommitLog 使用物理偏移重写流。 */\n    public static FileSegmentInputStream build('),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/util/MessageFormatUtil.java': [
        ('public class MessageFormatUtil',
         '/**\n * 消息格式工具：解析 CommitLog/ConsumeQueue 字段并按 CQ 切分消息缓冲。\n */\npublic class MessageFormatUtil'),
        ('    public static final int MSG_ID_LENGTH = 8 + 8;',
         '    /** MsgId 长度：storeHost(8) + offset(8)。 */\n    public static final int MSG_ID_LENGTH = 8 + 8;'),
        ('    public static final int MAGIC_CODE_POSITION = 4;',
         '    /** 魔数字段在消息头中的偏移。 */\n    public static final int MAGIC_CODE_POSITION = 4;'),
        ('    public static final int QUEUE_OFFSET_POSITION = 20;',
         '    /** 队列逻辑偏移字段偏移。 */\n    public static final int QUEUE_OFFSET_POSITION = 20;'),
        ('    public static final int PHYSICAL_OFFSET_POSITION = 28;',
         '    /** CommitLog 物理偏移字段偏移。 */\n    public static final int PHYSICAL_OFFSET_POSITION = 28;'),
        ('    public static final int SYS_FLAG_OFFSET_POSITION = 36;',
         '    /** 系统标志字段起始偏移（物理偏移字段结束位置）。 */\n    public static final int SYS_FLAG_OFFSET_POSITION = 36;'),
        ('    public static final int STORE_TIMESTAMP_POSITION = 56;',
         '    /** 存储时间戳字段偏移。 */\n    public static final int STORE_TIMESTAMP_POSITION = 56;'),
        ('    public static final int STORE_HOST_POSITION = 64;',
         '    /** storeHost 字段偏移。 */\n    public static final int STORE_HOST_POSITION = 64;'),
        ('    /**\n     * item size:           int, 4 bytes\n     * magic code:          int, 4 bytes\n     * max store timestamp: long, 8 bytes\n     */',
         '    /**\n     * CommitLog coda 大小：itemSize(4) + magicCode(4) + maxStoreTimestamp(8)。\n     */'),
        ('    public static final int COMMIT_LOG_CODA_SIZE = 4 + 8 + 4;',
         '    /** CommitLog 段尾 coda 字节长度。 */\n    public static final int COMMIT_LOG_CODA_SIZE = 4 + 8 + 4;'),
        ('    public static final int BLANK_MAGIC_CODE = 0xBBCCDDEE ^ 1880681586 + 8;',
         '    /** 空白消息魔数，用于跳过 coda 占位。 */\n    public static final int BLANK_MAGIC_CODE = 0xBBCCDDEE ^ 1880681586 + 8;'),
        ('    /**\n     * commit log offset: long, 8 bytes\n     * message size: int, 4 bytes\n     * tag hash code: long, 8 bytes\n     */',
         '    /**\n     * ConsumeQueue 单元大小：commitLogOffset(8) + size(4) + tagHash(8)。\n     */'),
        ('    public static final int CONSUME_QUEUE_UNIT_SIZE = 8 + 4 + 8;',
         '    /** 单条 ConsumeQueue 索引条目字节长度。 */\n    public static final int CONSUME_QUEUE_UNIT_SIZE = 8 + 4 + 8;'),
        ('    public static int getTotalSize(ByteBuffer message) {',
         '    /** 读取消息总大小（含头部）。 */\n    public static int getTotalSize(ByteBuffer message) {'),
        ('    public static long getCommitLogOffset(ByteBuffer message) {',
         '    /** 读取消息 CommitLog 物理偏移。 */\n    public static long getCommitLogOffset(ByteBuffer message) {'),
        ('    public static List<SelectBufferResult> splitMessageBuffer(ByteBuffer cqBuffer, ByteBuffer msgBuffer) {',
         '    /** 按 ConsumeQueue 缓冲切分 CommitLog 消息并校验魔数与长度。 */\n    public static List<SelectBufferResult> splitMessageBuffer(ByteBuffer cqBuffer, ByteBuffer msgBuffer) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/util/MessageStoreUtil.java': [
        ('public class MessageStoreUtil',
         '/**\n * 分层存储通用工具：路径格式化、偏移文件名与人类可读字节数。\n */\npublic class MessageStoreUtil'),
        ('    public static final String TIERED_STORE_LOGGER_NAME = "RocketmqTieredStore";',
         '    /** 分层存储 SLF4J Logger 名称。 */\n    public static final String TIERED_STORE_LOGGER_NAME = "RocketmqTieredStore";'),
        ('    public static final String RMQ_SYS_TIERED_STORE_INDEX_TOPIC = "rmq_sys_INDEX";',
         '    /** 系统 Index Topic 名称。 */\n    public static final String RMQ_SYS_TIERED_STORE_INDEX_TOPIC = "rmq_sys_INDEX";'),
        ('    public static final long BYTE = 1L;',
         '    /** 1 字节常量。 */\n    public static final long BYTE = 1L;'),
        ('    public static final long KB = BYTE << 10;',
         '    /** 1 KB 字节数。 */\n    public static final long KB = BYTE << 10;'),
        ('    public static final long MB = KB << 10;',
         '    /** 1 MB 字节数。 */\n    public static final long MB = KB << 10;'),
        ('    public static final long GB = MB << 10;',
         '    /** 1 GB 字节数。 */\n    public static final long GB = MB << 10;'),
        ('    public static final long TB = GB << 10;',
         '    /** 1 TB 字节数。 */\n    public static final long TB = GB << 10;'),
        ('    public static final long PB = TB << 10;',
         '    /** 1 PB 字节数。 */\n    public static final long PB = TB << 10;'),
        ('    public static final long EB = PB << 10;',
         '    /** 1 EB 字节数。 */\n    public static final long EB = PB << 10;'),
        ('    public static String toHumanReadable(long size) {',
         '    /** 将字节数格式化为 B/KB/MB… 人类可读字符串。 */\n    public static String toHumanReadable(long size) {'),
        ('    public static String getHash(String str) {',
         '    /** 计算字符串 MD5 前 8 位十六进制哈希。 */\n    public static String getHash(String str) {'),
        ('    public static String toFilePath(MessageQueue mq) {',
         '    /** 将 MessageQueue 格式化为 broker/topic/queueId 路径。 */\n    public static String toFilePath(MessageQueue mq) {'),
        ('    public static String getIndexFilePath(String brokerName) {',
         '    /** 返回系统 Index 文件的相对路径。 */\n    public static String getIndexFilePath(String brokerName) {'),
        ('    public static String offset2FileName(final long offset) {',
         '    /** 将逻辑偏移编码为 hash+20 位数字的文件名。 */\n    public static String offset2FileName(final long offset) {'),
        ('    public static long fileName2Offset(final String fileName) {',
         '    /** 从文件名解析逻辑偏移（取末 20 位数字）。 */\n    public static long fileName2Offset(final String fileName) {'),
    ],
}
