"""Chinese JavaDoc replacements for RocketMQ wave45a tools [0:15]."""

R: dict[str, list[tuple[str, str]]] = {
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/PrintMessageByQueueCommand.java': [
        ('public class PrintMessageByQueueCommand implements SubCommand {',
         '/**\n * printMsgByQueue 子命令：按指定 Broker 与队列 ID 拉取并打印 Topic 消息。\n * <p>支持时间范围过滤、Tag 统计及消息体打印。\n */\npublic class PrintMessageByQueueCommand implements SubCommand {'),
        ('    public static long timestampFormat(final String value) {',
         '    /** 将毫秒时间戳或 yyyy-MM-dd#HH:mm:ss:SSS 格式字符串解析为 long。 */\n    public static long timestampFormat(final String value) {'),
        ('    private static void calculateByTag(final List<MessageExt> msgs, final Map<String, AtomicLong> tagCalmap,\n        final boolean calByTag) {',
         '    /** 按 Tag 统计消息数量（calByTag 为 true 时生效）。 */\n    private static void calculateByTag(final List<MessageExt> msgs, final Map<String, AtomicLong> tagCalmap,\n        final boolean calByTag) {'),
        ('    private static void printCalculateByTag(final Map<String, AtomicLong> tagCalmap, final boolean calByTag) {',
         '    /** 打印各 Tag 的消息计数汇总。 */\n    private static void printCalculateByTag(final Map<String, AtomicLong> tagCalmap, final boolean calByTag) {'),
        ('    public static void printMessage(final List<MessageExt> msgs, final String charsetName, boolean printMsg,\n        boolean printBody) {',
         '    /** 按指定字符集打印消息 ID、属性及可选消息体。 */\n    public static void printMessage(final List<MessageExt> msgs, final String charsetName, boolean printMsg,\n        boolean printBody) {'),
        ('    public String commandDesc() {\n        return "Print Message Detail by queueId.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Print Message Detail by queueId.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("a", "brokerName ", true, "broker name");',
         '        opt = new Option("a", "brokerName ", true, "Broker 名称");'),
        ('        opt = new Option("i", "queueId ", true, "queue id");',
         '        opt = new Option("i", "queueId ", true, "队列 ID");'),
        ('        opt = new Option("c", "charsetName ", true, "CharsetName(eg: UTF-8,GBK)");',
         '        opt = new Option("c", "charsetName ", true, "消息体字符集（如 UTF-8、GBK）");'),
        ('        opt = new Option("s", "subExpression ", true, "Subscribe Expression(eg: TagA || TagB)");',
         '        opt = new Option("s", "subExpression ", true, "订阅表达式（如 TagA || TagB）");'),
        ('        opt = new Option("b", "beginTimestamp ", true, "Begin timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '        opt = new Option("b", "beginTimestamp ", true, "起始时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('        opt = new Option("e", "endTimestamp ", true, "End timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '        opt = new Option("e", "endTimestamp ", true, "结束时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('        opt = new Option("p", "print msg", true, "print msg. eg: true | false(default)");',
         '        opt = new Option("p", "print msg", true, "是否打印消息详情（true/false，默认 false）");'),
        ('        opt = new Option("d", "printBody ", true, "print body. eg: true | false(default)");',
         '        opt = new Option("d", "printBody ", true, "是否打印消息体（true/false，默认 false）");'),
        ('        opt = new Option("f", "calculate", true, "calculate by tag. eg: true | false(default)");',
         '        opt = new Option("f", "calculate", true, "是否按 Tag 统计消息数（true/false，默认 false）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取指定队列消息并按选项打印或统计。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            READQ:\n            for (long offset = minOffset; offset < maxOffset; ) {',
         '            // 从 minOffset 逐批拉取直至 maxOffset\n            READQ:\n            for (long offset = minOffset; offset < maxOffset; ) {'),
        ('    static class TagCountBean implements Comparable<TagCountBean> {',
         '    /** Tag 消息计数条目，用于排序输出。 */\n    static class TagCountBean implements Comparable<TagCountBean> {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/PrintMessageSubCommand.java': [
        ('public class PrintMessageSubCommand implements SubCommand {',
         '/**\n * printMsg 子命令：遍历 Topic 全部队列拉取并打印消息详情。\n * <p>支持时间范围、Tag 过滤及 LMQ 父 Topic 路由。\n */\npublic class PrintMessageSubCommand implements SubCommand {'),
        ('    public static long timestampFormat(final String value) {',
         '    /** 将毫秒时间戳或日期字符串解析为 long。 */\n    public static long timestampFormat(final String value) {'),
        ('    public static void printMessage(final List<MessageExt> msgs, final String charsetName, boolean printBody) {',
         '    /** 打印消息 ID、属性及可选消息体内容。 */\n    public static void printMessage(final List<MessageExt> msgs, final String charsetName, boolean printBody) {'),
        ('    public String commandDesc() {\n        return "Print Message Detail.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Print Message Detail.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("c", "charsetName ", true, "CharsetName(eg: UTF-8,GBK)");',
         '        opt = new Option("c", "charsetName ", true, "消息体字符集（如 UTF-8、GBK）");'),
        ('        opt = new Option("s", "subExpression ", true, "Subscribe Expression(eg: TagA || TagB)");',
         '        opt = new Option("s", "subExpression ", true, "订阅表达式（如 TagA || TagB）");'),
        ('            new Option("b", "beginTimestamp ", true,\n                "Begin timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '            new Option("b", "beginTimestamp ", true,\n                "起始时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('            new Option("e", "endTimestamp ", true,\n                "End timestamp[currentTimeMillis|yyyy-MM-dd#HH:mm:ss:SSS]");',
         '            new Option("e", "endTimestamp ", true,\n                "结束时间戳（毫秒或 yyyy-MM-dd#HH:mm:ss:SSS）");'),
        ('            new Option("d", "printBody ", true,\n                "print body");',
         '            new Option("d", "printBody ", true,\n                "是否打印消息体");'),
        ('            new Option("l", "lmqParentTopic", true,\n                "Lmq parent topic, lmq is used to find the route.");',
         '            new Option("l", "lmqParentTopic", true,\n                "LMQ 父 Topic，用于查找路由信息");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历 Topic 各队列拉取消息并打印。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            if (lmqParentTopic != null) {',
         '            // LMQ 模式：通过父 Topic 获取队列再替换为目标 Topic\n            if (lmqParentTopic != null) {'),
        ('                READQ:\n                for (long offset = minOffset; offset < maxOffset; ) {',
         '                // 逐批拉取当前队列消息\n                READQ:\n                for (long offset = minOffset; offset < maxOffset; ) {'),
        ('    public void fillBrokerAddrIfNotExist(DefaultMQPullConsumer defaultMQPullConsumer, MessageQueue messageQueue,\n        String routeTopic) {',
         '    /** 若 Broker 地址缺失，通过 routeTopic 刷新路由表。 */\n    public void fillBrokerAddrIfNotExist(DefaultMQPullConsumer defaultMQPullConsumer, MessageQueue messageQueue,\n        String routeTopic) {'),
        ('            // use lmq parent topic to fill up broker addr table',
         '            // 使用 LMQ 父 Topic 补全 Broker 地址表'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByIdSubCommand.java': [
        ('public class QueryMsgByIdSubCommand implements SubCommand {',
         '/**\n * queryMsgById 子命令：按消息 ID 查询消息详情。\n * <p>支持重发、直接推送消费及消息体格式化输出。\n */\npublic class QueryMsgByIdSubCommand implements SubCommand {'),
        ('    public static void queryById(final DefaultMQAdminExt admin, final String clusterName, final String topic,\n        final String msgId, final Charset msgBodyCharset) throws MQClientException,',
         '    /** 按 msgId 查询消息并打印详情。 */\n    public static void queryById(final DefaultMQAdminExt admin, final String clusterName, final String topic,\n        final String msgId, final Charset msgBodyCharset) throws MQClientException,'),
        ('    public static void printMsg(final DefaultMQAdminExt admin, final MessageExt msg,\n        final Charset msgBodyCharset) throws IOException {',
         '    /** 打印消息元数据、消费轨迹及可选消息体。 */\n    public static void printMsg(final DefaultMQAdminExt admin, final MessageExt msg,\n        final Charset msgBodyCharset) throws IOException {'),
        ('    private static String createBodyFile(MessageExt msg) throws IOException {',
         '    /** 将消息体写入 /tmp/rocketmq/msgbodys 临时文件并返回路径。 */\n    private static String createBodyFile(MessageExt msg) throws IOException {'),
        ('    public String commandDesc() {\n        return "Query Message by Id.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Query Message by Id.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("i", "msgId", true, "Message Id");',
         '        opt = new Option("i", "msgId", true, "消息 ID（支持逗号分隔多个）");'),
        ('        opt = new Option("g", "consumerGroup", true, "consumer group name");',
         '        opt = new Option("g", "consumerGroup", true, "消费组名称（与 -d 配合直接推送）");'),
        ('        opt = new Option("d", "clientId", true, "The consumer\'s client id");',
         '        opt = new Option("d", "clientId", true, "消费者 clientId（与 -g 配合直接推送）");'),
        ('        opt = new Option("s", "sendMessage", true, "resend message");',
         '        opt = new Option("s", "sendMessage", true, "是否重发消息（true/false）");'),
        ('        opt = new Option("u", "unitName", true, "unit name");',
         '        opt = new Option("u", "unitName", true, "单元名称（重发时使用）");'),
        ('        opt = new Option("f", "bodyFormat", true, "print message body by the specified format");',
         '        opt = new Option("f", "bodyFormat", true, "消息体字符集格式（如 UTF-8）");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic（用于路由查找）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析参数并查询、重发或直接推送消息。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void pushMsg(final DefaultMQAdminExt defaultMQAdminExt, final String clusterName,\n        final String consumerGroup, final String clientId,\n        final String topic, final String msgId) {',
         '    /** 向 Push 消费者直接推送指定消息。 */\n    private void pushMsg(final DefaultMQAdminExt defaultMQAdminExt, final String clusterName,\n        final String consumerGroup, final String clientId,\n        final String topic, final String msgId) {'),
        ('                // resend msg by id',
         '                // 按 msgId 查询原消息并重发'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByKeySubCommand.java': [
        ('public class QueryMsgByKeySubCommand implements SubCommand {',
         '/**\n * queryMsgByKey 子命令：按消息 Key 或 Tag 索引查询消息列表。\n * <p>支持时间范围、分页（lastKey）及最大返回条数限制。\n */\npublic class QueryMsgByKeySubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Query Message by Key.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Query Message by Key.";'),
        ('        Option opt = new Option("t", "topic", true, "Topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("k", "msgKey", true, "Message Key");',
         '        opt = new Option("k", "msgKey", true, "消息 Key 或 Tag 值");'),
        ('        opt = new Option("b", "beginTimestamp", true, "Begin timestamp(ms). default:0, eg:1676730526212");',
         '        opt = new Option("b", "beginTimestamp", true, "起始时间戳（毫秒，默认 0）");'),
        ('        opt = new Option("e", "endTimestamp", true, "End timestamp(ms). default:Long.MAX_VALUE, eg:1676730526212");',
         '        opt = new Option("e", "endTimestamp", true, "结束时间戳（毫秒，默认 Long.MAX_VALUE）");'),
        ('        opt = new Option("m", "maxNum", true, "The maximum number of messages returned by the query, default:64");',
         '        opt = new Option("m", "maxNum", true, "最大返回消息数（默认 64）");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic（用于路由查找）");'),
        ('        opt = new Option("p", "keyType", true, "Index key type, default index key type is K, you can use K for keys OR T for tags");',
         '        opt = new Option("p", "keyType", true, "索引类型：K（Key）或 T（Tag），默认 K");'),
        ('        opt = new Option("l", "lastKey", true, "Last Key");',
         '        opt = new Option("l", "lastKey", true, "分页游标（上一页最后一条的 indexKey）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 CLI 参数并调用 queryByKey 查询消息。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void queryByKey(final DefaultMQAdminExt admin, final String cluster, final String topic, final String key, int maxNum, long begin,\n        long end, String keyType, String lastKey)',
         '    /** 按 Key/Tag 索引查询并打印消息 ID、队列 ID 与位点。 */\n    private void queryByKey(final DefaultMQAdminExt admin, final String cluster, final String topic, final String key, int maxNum, long begin,\n        long end, String keyType, String lastKey)'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByOffsetSubCommand.java': [
        ('public class QueryMsgByOffsetSubCommand implements SubCommand {',
         '/**\n * queryMsgByOffset 子命令：按队列位点精确查询单条消息。\n * <p>支持 LMQ routeTopic 路由及消息体格式化输出。\n */\npublic class QueryMsgByOffsetSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Query Message by offset.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Query Message by offset.";'),
        ('        Option opt = new Option("t", "topic", true, "topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("b", "brokerName", true, "Broker Name");',
         '        opt = new Option("b", "brokerName", true, "Broker 名称");'),
        ('        opt = new Option("i", "queueId", true, "Queue Id");',
         '        opt = new Option("i", "queueId", true, "队列 ID");'),
        ('        opt = new Option("o", "offset", true, "Queue Offset");',
         '        opt = new Option("o", "offset", true, "队列消费位点");'),
        ('        opt = new Option("f", "bodyFormat", true, "print message body by the specified format");',
         '        opt = new Option("f", "bodyFormat", true, "消息体字符集格式（如 UTF-8）");'),
        ('        opt = new Option("r", "routeTopic", true, "the topic which is used to find route info");',
         '        opt = new Option("r", "routeTopic", true, "用于查找路由的 Topic（LMQ 场景）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 按位点拉取单条消息并打印详情。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('                // try to find route info by route topic, to support LMQ',
         '                // 通过 routeTopic 预拉取以刷新 LMQ 路由信息'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgByUniqueKeySubCommand.java': [
        ('public class QueryMsgByUniqueKeySubCommand implements SubCommand {',
         '/**\n * queryMsgByUniqueKey 子命令：按消息唯一键（UniqKey）查询消息。\n * <p>支持时间范围、展示全部匹配项及直接推送消费。\n */\npublic class QueryMsgByUniqueKeySubCommand implements SubCommand {'),
        ('    private DefaultMQAdminExt createMQAdminExt(RPCHook rpcHook) throws SubCommandException {',
         '    /** 创建并启动 DefaultMQAdminExt 单例。 */\n    private DefaultMQAdminExt createMQAdminExt(RPCHook rpcHook) throws SubCommandException {'),
        ('    public static void queryById(final DefaultMQAdminExt admin, final String clusterName, final String topic, final String msgId, final boolean showAll, final String startTime, final String endTime) throws MQClientException, InterruptedException, IOException {',
         '    /** 按 UniqKey 查询消息并按 showAll 决定展示条数。 */\n    public static void queryById(final DefaultMQAdminExt admin, final String clusterName, final String topic, final String msgId, final boolean showAll, final String startTime, final String endTime) throws MQClientException, InterruptedException, IOException {'),
        ('    private static void showMessage(final DefaultMQAdminExt admin, MessageExt msg, int index) throws IOException {',
         '    /** 打印单条消息元数据及消费轨迹。 */\n    private static void showMessage(final DefaultMQAdminExt admin, MessageExt msg, int index) throws IOException {'),
        ('    private static String createBodyFile(MessageExt msg, int index) throws IOException {',
         '    /** 将消息体写入临时文件，多条时追加 index 后缀。 */\n    private static String createBodyFile(MessageExt msg, int index) throws IOException {'),
        ('    public String commandDesc() {\n        return "Query Message by Unique key.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Query Message by Unique key.";'),
        ('        Option opt = new Option("i", "msgId", true, "Message Id");',
         '        Option opt = new Option("i", "msgId", true, "消息 UniqKey / msgId");'),
        ('        opt = new Option("g", "consumerGroup", true, "consumer group name");',
         '        opt = new Option("g", "consumerGroup", true, "消费组名称（与 -d 配合直接推送）");'),
        ('        opt = new Option("d", "clientId", true, "The consumer\'s client id");',
         '        opt = new Option("d", "clientId", true, "消费者 clientId");'),
        ('        opt = new Option("t", "topic", true, "The topic of msg");',
         '        opt = new Option("t", "topic", true, "消息所属 Topic");'),
        ('        opt = new Option("a", "showAll", false, "Print all message, the limit is 32");',
         '        opt = new Option("a", "showAll", false, "打印全部匹配消息（最多 32 条）");'),
        ('        opt = new Option("c", "cluster", true, "Cluster name or lmq parent topic, lmq is used to find the route.");',
         '        opt = new Option("c", "cluster", true, "集群名或 LMQ 父 Topic");'),
        ('        opt = new Option("s", "startTime", true, "startTime");',
         '        opt = new Option("s", "startTime", true, "查询起始时间戳（毫秒）");'),
        ('        opt = new Option("e", "endTime", true, "endTime");',
         '        opt = new Option("e", "endTime", true, "查询结束时间戳（毫秒）");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析参数并查询或直接推送消息。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/QueryMsgTraceByIdSubCommand.java': [
        ('public class QueryMsgTraceByIdSubCommand implements SubCommand {',
         '/**\n * queryMsgTraceById 子命令：按消息 ID 查询消息轨迹（Trace）。\n * <p>解析 Trace Topic 中的 Pub/Sub 记录并格式化输出。\n */\npublic class QueryMsgTraceByIdSubCommand implements SubCommand {'),
        ('        Option opt = new Option("i", "msgId", true, "Message Id");',
         '        Option opt = new Option("i", "msgId", true, "消息 ID");'),
        ('        opt = new Option("t", "traceTopic", true, "The name value of message trace topic");',
         '        opt = new Option("t", "traceTopic", true, "消息轨迹 Topic 名称（默认系统 Trace Topic）");'),
        ('        opt = new Option("b", "beginTimestamp", true, "Begin timestamp(ms). default:0, eg:1676730526212");',
         '        opt = new Option("b", "beginTimestamp", true, "起始时间戳（毫秒，默认 0）");'),
        ('        opt = new Option("e", "endTimestamp", true, "End timestamp(ms). default:Long.MAX_VALUE, eg:1676730526212");',
         '        opt = new Option("e", "endTimestamp", true, "结束时间戳（毫秒，默认 Long.MAX_VALUE）");'),
        ('        opt = new Option("c", "maxNum", true, "The maximum number of messages returned by the query, default:64");',
         '        opt = new Option("c", "maxNum", true, "最大返回消息数（默认 64）");'),
        ('    public String commandDesc() {\n        return "Query a message trace.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Query a message trace.";'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析参数并查询消息轨迹。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('    private void queryTraceByMsgId(final DefaultMQAdminExt admin, String traceTopic, String msgId, int maxNum,\n        long begin, long end)',
         '    /** 从 Trace Topic 查询并解码 TraceView 列表。 */\n    private void queryTraceByMsgId(final DefaultMQAdminExt admin, String traceTopic, String msgId, int maxNum,\n        long begin, long end)'),
        ('    private void printMessageTrace(List<TraceView> traceViews) {',
         '    /** 按 Pub/Sub 分组打印消息轨迹详情。 */\n    private void printMessageTrace(List<TraceView> traceViews) {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/message/SendMessageCommand.java': [
        ('public class SendMessageCommand implements SubCommand {',
         '/**\n * sendMessage 子命令：向指定 Topic 发送一条测试消息。\n * <p>支持指定 Broker/队列、Key/Tag 及消息轨迹开关。\n */\npublic class SendMessageCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Send a message.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Send a message.";'),
        ('        Option opt = new Option("t", "topic", true, "Topic name");',
         '        Option opt = new Option("t", "topic", true, "Topic 名称");'),
        ('        opt = new Option("p", "body", true, "UTF-8 string format of the message body");',
         '        opt = new Option("p", "body", true, "消息体（UTF-8 字符串）");'),
        ('        opt = new Option("k", "key", true, "Message keys");',
         '        opt = new Option("k", "key", true, "消息 Key");'),
        ('        opt = new Option("c", "tags", true, "Message tags");',
         '        opt = new Option("c", "tags", true, "消息 Tag");'),
        ('        opt = new Option("b", "broker", true, "Send message to target broker");',
         '        opt = new Option("b", "broker", true, "目标 Broker 名称（与 -i 配合指定队列）");'),
        ('        opt = new Option("i", "qid", true, "Send message to target queue");',
         '        opt = new Option("i", "qid", true, "目标队列 ID（需同时指定 -b）");'),
        ('        opt = new Option("m", "msgTraceEnable", true, "Message Trace Enable, Default: false");',
         '        opt = new Option("m", "msgTraceEnable", true, "是否启用消息轨迹（默认 false）");'),
        ('    private DefaultMQProducer createProducer(RPCHook rpcHook, boolean msgTraceEnable) {',
         '    /** 创建 DefaultMQProducer 单例。 */\n    private DefaultMQProducer createProducer(RPCHook rpcHook, boolean msgTraceEnable) {'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 构建 Message 并发送到指定 Topic 或队列。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/metadata/RocksDBConfigToJsonCommand.java': [
        ('public class RocksDBConfigToJsonCommand implements SubCommand {',
         '/**\n * rocksDBConfigToJson 子命令：将 Broker RocksDB KV 配置导出为 JSON。\n * <p>支持 RPC 模式（远程 Broker）与本地模式（直接读取 RocksDB 目录）。\n */\npublic class RocksDBConfigToJsonCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Convert RocksDB kv config (topics/subscriptionGroups/consumerOffsets) to json. " +',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Convert RocksDB kv config (topics/subscriptionGroups/consumerOffsets) to json. " +'),
        ('        Option configTypeOption = new Option("t", "configType", true, "Name of kv config, e.g. " +\n            "topics/subscriptionGroups/consumerOffsets. Required in local mode and default all in rpc mode.");',
         '        Option configTypeOption = new Option("t", "configType", true, "KV 配置类型：topics/subscriptionGroups/consumerOffsets（本地模式必填，RPC 模式默认全部）");'),
        ('        Option pathOption = new Option("p", "configPath", true,\n            "[local mode] Absolute path to the metadata config directory");',
         '        Option pathOption = new Option("p", "configPath", true,\n            "[本地模式] 元数据配置目录绝对路径");'),
        ('        Option exportPathOption = new Option("e", "exportFile", true,\n            "[local mode] Absolute file path for exporting, auto backup existing file, not directory. If exportFile is provided, will export Json file and ignore [-j].");',
         '        Option exportPathOption = new Option("e", "exportFile", true,\n            "[本地模式] 导出 JSON 文件绝对路径（自动备份已有文件）");'),
        ('        Option jsonEnableOption = new Option("j", "jsonEnable", true,\n            "[local mode] Json format enable, Default: true. If exportFile is provided, will export Json file and ignore [-j].");',
         '        Option jsonEnableOption = new Option("j", "jsonEnable", true,\n            "[本地模式] 是否 JSON 格式化输出（默认 true）");'),
        ('        Option nameserverOption = new Option("n", "nameserverAddr", true,\n            "[rpc mode] nameserverAddr. If nameserverAddr and clusterName are provided, will ignore [-p, -e, -j, -b] args");',
         '        Option nameserverOption = new Option("n", "nameserverAddr", true,\n            "[RPC 模式] NameServer 地址（与 cluster 配合导出集群全部 Broker）");'),
        ('        Option clusterOption = new Option("c", "cluster", true,\n            "[rpc mode] Cluster name. If nameserverAddr and clusterName are provided, will ignore [-p, -e, -j, -b] args");',
         '        Option clusterOption = new Option("c", "cluster", true,\n            "[RPC 模式] 集群名称");'),
        ('        Option brokerAddrOption = new Option("b", "brokerAddr", true,\n            "[rpc mode] Broker address. If brokerAddr is provided, will ignore [-p, -e, -j] args");',
         '        Option brokerAddrOption = new Option("b", "brokerAddr", true,\n            "[RPC 模式] 单个 Broker 地址");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 根据参数选择 RPC 或本地模式导出 RocksDB 配置。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            // [rpc mode] call all brokers in cluster to export to json file',
         '            // RPC 模式：调用集群全部 Broker 导出 JSON'),
        ('            // [local mode] load rocksdb to print or export file',
         '            // 本地模式：直接加载 RocksDB 打印或导出文件'),
        ('    private void handleLocalMode(CommandLine commandLine) {',
         '    /** 本地模式：读取 RocksDB 并打印或写入导出文件。 */\n    private void handleLocalMode(CommandLine commandLine) {'),
        ('    private static Map<String, JSONObject> getConfigMapFromRocksDB(String path,\n        ExportRocksDBConfigToJsonRequestHeader.ConfigType configType) {',
         '    /** 从 RocksDB 目录加载 Topic/订阅组配置并转为 JSON Map。 */\n    private static Map<String, JSONObject> getConfigMapFromRocksDB(String path,\n        ExportRocksDBConfigToJsonRequestHeader.ConfigType configType) {'),
        ('    private void handleRpcMode(CommandLine commandLine, RPCHook rpcHook,\n        List<ExportRocksDBConfigToJsonRequestHeader.ConfigType> type) {',
         '    /** RPC 模式：异步调用 Broker exportRocksDBConfigToJson。 */\n    private void handleRpcMode(CommandLine commandLine, RPCHook rpcHook,\n        List<ExportRocksDBConfigToJsonRequestHeader.ConfigType> type) {'),
        ('    static class RocksDBOffsetSerializeWrapper {',
         '    /** 消费位点 RocksDB 序列化包装类。 */\n    static class RocksDBOffsetSerializeWrapper {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/AddWritePermSubCommand.java': [
        ('public class AddWritePermSubCommand implements SubCommand {',
         '/**\n * addWritePerm 子命令：为指定 Broker 在所有 NameServer 上恢复写权限。\n * <p>Broker 被禁止写入后，可通过此命令重新开放 Topic 写权限。\n */\npublic class AddWritePermSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Add write perm of broker in all name server you defined in the -n param.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Add write perm of broker in all name server you defined in the -n param.";'),
        ('        Option opt = new Option("b", "brokerName", true, "broker name");',
         '        Option opt = new Option("b", "brokerName", true, "目标 Broker 名称");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历全部 NameServer 为 Broker 添加写权限。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/DeleteKvConfigCommand.java': [
        ('public class DeleteKvConfigCommand implements SubCommand {',
         '/**\n * deleteKvConfig 子命令：从 NameServer 删除指定 KV 配置项。\n * <p>通过 namespace 与 key 定位待删除的配置。\n */\npublic class DeleteKvConfigCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Delete KV config.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Delete KV config.";'),
        ('        Option opt = new Option("s", "namespace", true, "set the namespace");',
         '        Option opt = new Option("s", "namespace", true, "KV 配置命名空间");'),
        ('        opt = new Option("k", "key", true, "set the key name");',
         '        opt = new Option("k", "key", true, "配置项键名");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 namespace/key 并调用 deleteKvConfig 删除配置。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            // namespace\n            String namespace = commandLine.getOptionValue(\'s\').trim();\n            // key name\n            String key = commandLine.getOptionValue(\'k\').trim();',
         '            // 解析命名空间与键名\n            String namespace = commandLine.getOptionValue(\'s\').trim();\n            String key = commandLine.getOptionValue(\'k\').trim();'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/GetNamesrvConfigCommand.java': [
        ('public class GetNamesrvConfigCommand implements SubCommand {',
         '/**\n * getNamesrvConfig 子命令：查询 NameServer 运行配置。\n * <p>支持指定多个 NameServer 地址（分号分隔）。\n */\npublic class GetNamesrvConfigCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Get configs of name server.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Get configs of name server.";'),
        ('    public Options buildCommandlineOptions(final Options options) {\n        return options;',
         '    /** 本命令无需额外 CLI 参数（NameServer 地址通过全局 -n 传入）。 */\n    public Options buildCommandlineOptions(final Options options) {\n        return options;'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {',
         '    /** 拉取各 NameServer 配置并以键值对形式打印。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {'),
        ('            // servers\n            String servers = commandLine.getOptionValue(\'n\');',
         '            // 解析分号分隔的 NameServer 地址列表\n            String servers = commandLine.getOptionValue(\'n\');'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/UpdateKvConfigCommand.java': [
        ('public class UpdateKvConfigCommand implements SubCommand {',
         '/**\n * updateKvConfig 子命令：创建或更新 NameServer KV 配置项。\n * <p>通过 namespace、key、value 三元组写入配置。\n */\npublic class UpdateKvConfigCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Create or update KV config.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Create or update KV config.";'),
        ('        Option opt = new Option("s", "namespace", true, "set the namespace");',
         '        Option opt = new Option("s", "namespace", true, "KV 配置命名空间");'),
        ('        opt = new Option("k", "key", true, "set the key name");',
         '        opt = new Option("k", "key", true, "配置项键名");'),
        ('        opt = new Option("v", "value", true, "set the key value");',
         '        opt = new Option("v", "value", true, "配置项值");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析参数并调用 createAndUpdateKvConfig 写入配置。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
        ('            // namespace\n            String namespace = commandLine.getOptionValue(\'s\').trim();\n            // key name\n            String key = commandLine.getOptionValue(\'k\').trim();\n            // key name\n            String value = commandLine.getOptionValue(\'v\').trim();',
         '            // 解析命名空间、键名与值\n            String namespace = commandLine.getOptionValue(\'s\').trim();\n            String key = commandLine.getOptionValue(\'k\').trim();\n            String value = commandLine.getOptionValue(\'v\').trim();'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/UpdateNamesrvConfigCommand.java': [
        ('public class UpdateNamesrvConfigCommand implements SubCommand {',
         '/**\n * updateNamesrvConfig 子命令：更新 NameServer 运行配置项。\n * <p>通过 key/value 指定单个配置，支持多个 NameServer 地址。\n */\npublic class UpdateNamesrvConfigCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Update configs of name server.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Update configs of name server.";'),
        ('        Option opt = new Option("k", "key", true, "config key");',
         '        Option opt = new Option("k", "key", true, "配置项键名");'),
        ('        opt = new Option("v", "value", true, "config value");',
         '        opt = new Option("v", "value", true, "配置项值");'),
        ('    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {',
         '    /** 解析 key/value 并调用 updateNameServerConfig 更新配置。 */\n    public void execute(final CommandLine commandLine, final Options options,\n        final RPCHook rpcHook) throws SubCommandException {'),
        ('            // key name\n            String key = commandLine.getOptionValue(\'k\').trim();\n            // key name\n            String value = commandLine.getOptionValue(\'v\').trim();',
         '            // 解析配置键名与值\n            String key = commandLine.getOptionValue(\'k\').trim();\n            String value = commandLine.getOptionValue(\'v\').trim();'),
        ('            // servers\n            String servers = commandLine.getOptionValue(\'n\');',
         '            // 解析分号分隔的 NameServer 地址列表\n            String servers = commandLine.getOptionValue(\'n\');'),
    ],
    'tools/src/main/java/org/apache/rocketmq/tools/command/namesrv/WipeWritePermSubCommand.java': [
        ('public class WipeWritePermSubCommand implements SubCommand {',
         '/**\n * wipeWritePerm 子命令：清除指定 Broker 在所有 NameServer 上的写权限。\n * <p>用于运维场景下临时禁止 Broker 写入。\n */\npublic class WipeWritePermSubCommand implements SubCommand {'),
        ('    public String commandDesc() {\n        return "Wipe write perm of broker in all name server you defined in the -n param.";',
         '    /** 返回命令描述。 */\n    public String commandDesc() {\n        return "Wipe write perm of broker in all name server you defined in the -n param.";'),
        ('        Option opt = new Option("b", "brokerName", true, "broker name");',
         '        Option opt = new Option("b", "brokerName", true, "目标 Broker 名称");'),
        ('    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {',
         '    /** 遍历全部 NameServer 清除 Broker 写权限。 */\n    public void execute(CommandLine commandLine, Options options, RPCHook rpcHook) throws SubCommandException {'),
    ],
}
