"""Chinese JavaDoc replacements for RocketMQ wave41b tieredstore [15:30]."""

R: dict[str, list[tuple[str, str]]] = {
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreFilter.java': [
        ('public interface MessageStoreFilter {',
         '/**\n * 消息存储 Topic 过滤器：判定 Topic 是否应被分层存储排除。\n */\npublic interface MessageStoreFilter {'),
        ('    boolean filterTopic(String topicName);',
         '    /** 若 Topic 应被过滤（不写入分层存储）则返回 true。 */\n    boolean filterTopic(String topicName);'),
        ('    void addTopicToBlackList(String topicName);',
         '    /** 将 Topic 加入黑名单，后续 {@link #filterTopic} 将排除该 Topic。 */\n    void addTopicToBlackList(String topicName);'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/core/MessageStoreTopicFilter.java': [
        ('public class MessageStoreTopicFilter implements MessageStoreFilter {',
         '/**\n * 基于配置与内置规则的 Topic 过滤器：排除系统 Topic、Revive 前缀、集群/ Broker 名及 LMQ。\n */\npublic class MessageStoreTopicFilter implements MessageStoreFilter {'),
        ('    private final Set<String> topicBlackSet;',
         '    /** Topic 黑名单集合。 */\n    private final Set<String> topicBlackSet;'),
        ('    public MessageStoreTopicFilter(MessageStoreConfig storeConfig) {',
         '    /** 初始化黑名单，默认包含集群名与 Broker 名。 */\n    public MessageStoreTopicFilter(MessageStoreConfig storeConfig) {'),
        ('    @Override\n    public boolean filterTopic(String topicName) {',
         '    /** {@inheritDoc} 空白名、系统 Topic、Revive 前缀、黑名单及 LMQ 均返回 true。 */\n    @Override\n    public boolean filterTopic(String topicName) {'),
        ('    @Override\n    public void addTopicToBlackList(String topicName) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void addTopicToBlackList(String topicName) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/exception/TieredStoreErrorCode.java': [
        ('public enum TieredStoreErrorCode {',
         '/**\n * 分层存储错误码枚举。\n */\npublic enum TieredStoreErrorCode {'),
        ('    /**\n     * Error code for an invalid offset.\n     */\n    ILLEGAL_OFFSET,',
         '    /** 非法偏移量。 */\n    ILLEGAL_OFFSET,'),
        ('    /**\n     * Error code for an invalid parameter.\n     */\n    ILLEGAL_PARAM,',
         '    /** 非法参数。 */\n    ILLEGAL_PARAM,'),
        ('    /**\n     * Error code for an incorrect download length.\n     */\n    DOWNLOAD_LENGTH_NOT_CORRECT,',
         '    /** 下载长度不正确。 */\n    DOWNLOAD_LENGTH_NOT_CORRECT,'),
        ('    /**\n     * Error code for no new data found in the storage system.\n     */\n    NO_NEW_DATA,',
         '    /** 存储系统中无新数据。 */\n    NO_NEW_DATA,'),
        ('    /**\n     * Error code for a storage provider error.\n     */\n    STORAGE_PROVIDER_ERROR,',
         '    /** 存储提供方错误。 */\n    STORAGE_PROVIDER_ERROR,'),
        ('    /**\n     * Error code for an input/output error.\n     */\n    IO_ERROR,',
         '    /** 输入/输出错误。 */\n    IO_ERROR,'),
        ('    /**\n     * Segment has been sealed\n     */\n    SEGMENT_SEALED,',
         '    /** 文件段已封存，不可再写入。 */\n    SEGMENT_SEALED,'),
        ('    /**\n     * Error code for an unknown error.\n     */\n    UNKNOWN',
         '    /** 未知错误。 */\n    UNKNOWN'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/exception/TieredStoreException.java': [
        ('public class TieredStoreException extends RuntimeException {',
         '/**\n * 分层存储运行时异常，携带 {@link TieredStoreErrorCode} 与可选 requestId/position。\n */\npublic class TieredStoreException extends RuntimeException {'),
        ('    private final TieredStoreErrorCode errorCode;',
         '    /** 错误码。 */\n    private final TieredStoreErrorCode errorCode;'),
        ('    private String requestId;',
         '    /** 关联请求 ID（可选）。 */\n    private String requestId;'),
        ('    private long position = -1L;',
         '    /** 出错位置偏移（默认 -1 表示未设置）。 */\n    private long position = -1L;'),
        ('    public TieredStoreException(TieredStoreErrorCode errorCode, String errorMessage) {',
         '    /** 构造带错误码与消息的异常。 */\n    public TieredStoreException(TieredStoreErrorCode errorCode, String errorMessage) {'),
        ('    public TieredStoreErrorCode getErrorCode() {',
         '    /** 返回错误码。 */\n    public TieredStoreErrorCode getErrorCode() {'),
        ('    public String getRequestId() {',
         '    /** 返回请求 ID。 */\n    public String getRequestId() {'),
        ('    public void setRequestId(String requestId) {',
         '    /** 设置请求 ID。 */\n    public void setRequestId(String requestId) {'),
        ('    public long getPosition() {',
         '    /** 返回出错位置。 */\n    public long getPosition() {'),
        ('    public void setPosition(long position) {',
         '    /** 设置出错位置。 */\n    public void setPosition(long position) {'),
        ('    @Override\n    public String toString() {',
         '    /** 附加 requestId 与 position 的字符串表示。 */\n    @Override\n    public String toString() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatAppendFile.java': [
        ('public class FlatAppendFile {',
         '/**\n * 分层存储追加写文件抽象：管理 FileSegment 链表的恢复、滚动、追加、读取与过期清理。\n */\npublic class FlatAppendFile {'),
        ('    protected static final Logger log = LoggerFactory.getLogger(MessageStoreUtil.TIERED_STORE_LOGGER_NAME);',
         '    /** 分层存储模块日志。 */\n    protected static final Logger log = LoggerFactory.getLogger(MessageStoreUtil.TIERED_STORE_LOGGER_NAME);'),
        ('    public static final long GET_FILE_SIZE_ERROR = -1L;',
         '    /** RPC 获取远程文件大小失败时的返回值。 */\n    public static final long GET_FILE_SIZE_ERROR = -1L;'),
        ('    protected final String filePath;',
         '    /** 逻辑文件路径。 */\n    protected final String filePath;'),
        ('    protected final FileSegmentType fileType;',
         '    /** 文件段类型（CommitLog/CQ/Index）。 */\n    protected final FileSegmentType fileType;'),
        ('    protected final MetadataStore metadataStore;',
         '    /** 元数据存储。 */\n    protected final MetadataStore metadataStore;'),
        ('    protected final FileSegmentFactory fileSegmentFactory;',
         '    /** 文件段工厂。 */\n    protected final FileSegmentFactory fileSegmentFactory;'),
        ('    protected final ReentrantReadWriteLock fileSegmentLock;',
         '    /** 文件段表读写锁。 */\n    protected final ReentrantReadWriteLock fileSegmentLock;'),
        ('    protected final CopyOnWriteArrayList<FileSegment> fileSegmentTable;',
         '    /** 按 baseOffset 排序的文件段列表。 */\n    protected final CopyOnWriteArrayList<FileSegment> fileSegmentTable;'),
        ('    protected FlatAppendFile(FileSegmentFactory fileSegmentFactory, FileSegmentType fileType, String filePath) {',
         '    /** 构造并执行 recover 与 recoverFileSize。 */\n    protected FlatAppendFile(FileSegmentFactory fileSegmentFactory, FileSegmentType fileType, String filePath) {'),
        ('    public void recover() {',
         '    /** 从元数据恢复文件段列表并排序。 */\n    public void recover() {'),
        ('    /**\n     * Retrieves the correct file size when initializing the file segment.\n     *\n     * @param fileSegment The file segment to get the size for.\n     * @return The correct length if the remote file exists,\n     *         0 if it does not exist,\n     *         or -1 if the RPC fails.\n     * @see <a href="https://github.com/apache/rocketmq/issues/9544">Related GitHub Issue</a>\n     */',
         '    /**\n     * 初始化文件段时获取远程正确文件大小。\n     *\n     * @param fileSegment 目标文件段\n     * @return 远程存在时返回实际长度，不存在返回 0，RPC 失败返回 -1\n     * @see <a href="https://github.com/apache/rocketmq/issues/9544">Related GitHub Issue</a>\n     */'),
        ('    public long getFileCorrectSize(FileSegment fileSegment) {',
         '    /** 轮询远程 RPC 直至获取有效文件大小。 */\n    public long getFileCorrectSize(FileSegment fileSegment) {'),
        ('    public void recoverFileSize() {',
         '    /** 校正最后一个文件段的 commit 位置与远程大小一致。 */\n    public void recoverFileSize() {'),
        ('    public void initOffset(long offset) {',
         '    /** 表为空时创建首个文件段并刷元数据。 */\n    public void initOffset(long offset) {'),
        ('    public void flushFileSegmentMeta(FileSegment fileSegment) {',
         '    /** 将文件段大小与时间戳写入元数据存储。 */\n    public void flushFileSegmentMeta(FileSegment fileSegment) {'),
        ('    public String getFilePath() {',
         '    /** 返回逻辑文件路径。 */\n    public String getFilePath() {'),
        ('    public FileSegmentType getFileType() {',
         '    /** 返回文件段类型。 */\n    public FileSegmentType getFileType() {'),
        ('    public List<FileSegment> getFileSegmentList() {',
         '    /** 返回文件段列表。 */\n    public List<FileSegment> getFileSegmentList() {'),
        ('    public long getMinOffset() {',
         '    /** 返回最小 baseOffset。 */\n    public long getMinOffset() {'),
        ('    public long getCommitOffset() {',
         '    /** 返回最后一段 commit 偏移。 */\n    public long getCommitOffset() {'),
        ('    public long getAppendOffset() {',
         '    /** 返回最后一段 append 偏移。 */\n    public long getAppendOffset() {'),
        ('    public long getMinTimestamp() {',
         '    /** 返回最早消息时间戳。 */\n    public long getMinTimestamp() {'),
        ('    public long getMaxTimestamp() {',
         '    /** 返回最晚消息时间戳。 */\n    public long getMaxTimestamp() {'),
        ('    public FileSegment rollingNewFile(long offset) {',
         '    /** 滚动创建新文件段并刷元数据。 */\n    public FileSegment rollingNewFile(long offset) {'),
        ('    public FileSegment getFileToWrite() {',
         '    /** 返回当前写入目标（最后一段）。 */\n    public FileSegment getFileToWrite() {'),
        ('    public AppendResult append(ByteBuffer buffer, long timestamp) {',
         '    /** 追加写入；段满时 commit 并滚动新段。 */\n    public AppendResult append(ByteBuffer buffer, long timestamp) {'),
        ('    public CompletableFuture<Boolean> commitAsync() {',
         '    /** 异步 commit 最后一段并刷元数据。 */\n    public CompletableFuture<Boolean> commitAsync() {'),
        ('    public CompletableFuture<ByteBuffer> readAsync(long offset, int length) {',
         '    /** 按全局偏移异步读取，跨段时合并缓冲区。 */\n    public CompletableFuture<ByteBuffer> readAsync(long offset, int length) {'),
        ('    public void shutdown() {',
         '    /** 关闭所有文件段。 */\n    public void shutdown() {'),
        ('    public void destroyExpiredFile(long expireTimestamp) {',
         '    /** 删除 maxTimestamp 早于 expireTimestamp 的过期段。 */\n    public void destroyExpiredFile(long expireTimestamp) {'),
        ('    public void destroy() {',
         '    /** 删除全部文件段。 */\n    public void destroy() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatCommitLogFile.java': [
        ('public class FlatCommitLogFile extends FlatAppendFile {',
         '/**\n * CommitLog 分层扁平文件：支持按时间与最小大小滚动，维护首条消息 queueOffset 缓存。\n */\npublic class FlatCommitLogFile extends FlatAppendFile {'),
        ('    private static final long GET_OFFSET_ERROR = -1L;',
         '    /** 读取首条 queueOffset 失败时的返回值。 */\n    private static final long GET_OFFSET_ERROR = -1L;'),
        ('    private final AtomicLong firstOffset = new AtomicLong(GET_OFFSET_ERROR);',
         '    /** 缓存的首条消息 consume queue offset。 */\n    private final AtomicLong firstOffset = new AtomicLong(GET_OFFSET_ERROR);'),
        ('    public FlatCommitLogFile(FileSegmentFactory fileSegmentFactory, String filePath) {',
         '    /** 构造 CommitLog 文件并从 offset 0 初始化。 */\n    public FlatCommitLogFile(FileSegmentFactory fileSegmentFactory, String filePath) {'),
        ('    /**\n     * Two rules are set here:\n     * 1. Single file must be saved for more than one day as default.\n     * 2. Single file must reach the minimum size before switching.\n     * When calculating storage space, due to the limitation of condition 2,\n     * the actual usage of storage space may be slightly higher than expected.\n     */',
         '    /**\n     * 滚动规则：① 单文件保留超过 interval 毫秒；② 达到 commitLogRollingMinimumSize。\n     * 因规则 ②，实际占用可能略高于预期。\n     */'),
        ('    public boolean tryRollingFile(long interval) {',
         '    /** 满足时间与最小大小时滚动新 CommitLog 段。 */\n    public boolean tryRollingFile(long interval) {'),
        ('    public long getMinOffsetFromFile() {',
         '    /** 同步获取首条消息的 queueOffset。 */\n    public long getMinOffsetFromFile() {'),
        ('    public CompletableFuture<Long> getMinOffsetFromFileAsync() {',
         '    /** 异步读取首条消息 queueOffset 并缓存。 */\n    public CompletableFuture<Long> getMinOffsetFromFileAsync() {'),
        ('    @Override\n    public void destroyExpiredFile(long expireTimestamp) {',
         '    /** 过期清理后若 minOffset 变化则重置 firstOffset 缓存。 */\n    @Override\n    public void destroyExpiredFile(long expireTimestamp) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatConsumeQueueFile.java': [
        ('public class FlatConsumeQueueFile extends FlatAppendFile {',
         '/**\n * ConsumeQueue 分层扁平文件，继承 {@link FlatAppendFile} 的段管理与读写能力。\n */\npublic class FlatConsumeQueueFile extends FlatAppendFile {'),
        ('    public FlatConsumeQueueFile(FileSegmentFactory fileSegmentFactory, String filePath) {',
         '    /** 构造指定路径的 ConsumeQueue 文件。 */\n    public FlatConsumeQueueFile(FileSegmentFactory fileSegmentFactory, String filePath) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatFileFactory.java': [
        ('public class FlatFileFactory {',
         '/**\n * 分层扁平文件工厂：创建 CommitLog、ConsumeQueue 与 Index 三类 FlatAppendFile。\n */\npublic class FlatFileFactory {'),
        ('    private final MetadataStore metadataStore;',
         '    /** 元数据存储。 */\n    private final MetadataStore metadataStore;'),
        ('    private final MessageStoreConfig storeConfig;',
         '    /** 消息存储配置。 */\n    private final MessageStoreConfig storeConfig;'),
        ('    private final FileSegmentFactory fileSegmentFactory;',
         '    /** 底层文件段工厂。 */\n    private final FileSegmentFactory fileSegmentFactory;'),
        ('    @VisibleForTesting\n    public FlatFileFactory(MetadataStore metadataStore, MessageStoreConfig storeConfig) {',
         '    /** 测试用构造，使用默认 MessageStoreExecutor。 */\n    @VisibleForTesting\n    public FlatFileFactory(MetadataStore metadataStore, MessageStoreConfig storeConfig) {'),
        ('    public FlatFileFactory(MetadataStore metadataStore,\n        MessageStoreConfig storeConfig, MessageStoreExecutor executor) {',
         '    /** 指定 executor 的完整构造。 */\n    public FlatFileFactory(MetadataStore metadataStore,\n        MessageStoreConfig storeConfig, MessageStoreExecutor executor) {'),
        ('    public MessageStoreConfig getStoreConfig() {',
         '    /** 返回存储配置。 */\n    public MessageStoreConfig getStoreConfig() {'),
        ('    public MetadataStore getMetadataStore() {',
         '    /** 返回元数据存储。 */\n    public MetadataStore getMetadataStore() {'),
        ('    public FlatCommitLogFile createFlatFileForCommitLog(String filePath) {',
         '    /** 创建 CommitLog 扁平文件。 */\n    public FlatCommitLogFile createFlatFileForCommitLog(String filePath) {'),
        ('    public FlatConsumeQueueFile createFlatFileForConsumeQueue(String filePath) {',
         '    /** 创建 ConsumeQueue 扁平文件。 */\n    public FlatConsumeQueueFile createFlatFileForConsumeQueue(String filePath) {'),
        ('    public FlatAppendFile createFlatFileForIndexFile(String filePath) {',
         '    /** 创建 Index 扁平文件。 */\n    public FlatAppendFile createFlatFileForIndexFile(String filePath) {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatFileInterface.java': [
        ('public interface FlatFileInterface {',
         '/**\n * 分层消息文件统一接口：CommitLog/CQ 追加、commit、按偏移/时间查询与生命周期管理。\n */\npublic interface FlatFileInterface {'),
        ('    long getTopicId();',
         '    /** 返回 Topic 内部 ID。 */\n    long getTopicId();'),
        ('    Lock getFileLock();',
         '    /** 返回文件级互斥锁。 */\n    Lock getFileLock();'),
        ('    MessageQueue getMessageQueue();',
         '    /** 返回所属 MessageQueue。 */\n    MessageQueue getMessageQueue();'),
        ('    boolean isFlatFileInit();',
         '    /** 扁平文件是否已完成初始化。 */\n    boolean isFlatFileInit();'),
        ('    void initOffset(long offset);',
         '    /** 以给定 baseOffset 初始化文件。 */\n    void initOffset(long offset);'),
        ('    boolean rollingFile(long interval);',
         '    /** 按 interval 尝试滚动 CommitLog 文件。 */\n    boolean rollingFile(long interval);'),
        ('    /**\n     * Appends a message to the commit log file\n     *\n     * @param message thByteBuffere message to append\n     * @return append result\n     */',
         '    /**\n     * 向 CommitLog 追加消息。\n     *\n     * @param message 消息字节缓冲\n     * @return 追加结果\n     */'),
        ('    AppendResult appendCommitLog(ByteBuffer message);',
         '    /** {@inheritDoc} */\n    AppendResult appendCommitLog(ByteBuffer message);'),
        ('    AppendResult appendCommitLog(SelectMappedBufferResult message);',
         '    /** 从映射缓冲区追加 CommitLog 消息。 */\n    AppendResult appendCommitLog(SelectMappedBufferResult message);'),
        ('    /**\n     * Append message to consume queue file, but does not commit it immediately\n     *\n     * @param request the dispatch request\n     * @return append result\n     */',
         '    /**\n     * 向 ConsumeQueue 追加索引单元（不立即 commit）。\n     *\n     * @param request 分发请求\n     * @return 追加结果\n     */'),
        ('    AppendResult appendConsumeQueue(DispatchRequest request);',
         '    /** {@inheritDoc} */\n    AppendResult appendConsumeQueue(DispatchRequest request);'),
        ('    void release();',
         '    /** 释放临时资源。 */\n    void release();'),
        ('    long getMinStoreTimestamp();',
         '    /** 最早存储时间戳。 */\n    long getMinStoreTimestamp();'),
        ('    long getMaxStoreTimestamp();',
         '    /** 最晚存储时间戳。 */\n    long getMaxStoreTimestamp();'),
        ('    long getFirstMessageOffset();',
         '    /** 首条消息 consume queue offset。 */\n    long getFirstMessageOffset();'),
        ('    long getCommitLogMinOffset();',
         '    /** CommitLog 最小偏移。 */\n    long getCommitLogMinOffset();'),
        ('    long getCommitLogMaxOffset();',
         '    /** CommitLog 最大 append 偏移。 */\n    long getCommitLogMaxOffset();'),
        ('    long getCommitLogCommitOffset();',
         '    /** CommitLog 已 commit 偏移。 */\n    long getCommitLogCommitOffset();'),
        ('    long getConsumeQueueMinOffset();',
         '    /** ConsumeQueue 最小偏移。 */\n    long getConsumeQueueMinOffset();'),
        ('    long getConsumeQueueMaxOffset();',
         '    /** ConsumeQueue 最大 append 偏移。 */\n    long getConsumeQueueMaxOffset();'),
        ('    long getConsumeQueueCommitOffset();',
         '    /** ConsumeQueue 已 commit 偏移。 */\n    long getConsumeQueueCommitOffset();'),
        ('    /**\n     * Persist commit log file and consume queue file\n     */',
         '    /** 持久化 CommitLog 与 ConsumeQueue。 */'),
        ('    CompletableFuture<Boolean> commitAsync();',
         '    /** {@inheritDoc} */\n    CompletableFuture<Boolean> commitAsync();'),
        ('    /**\n     * Asynchronously retrieves the message at the specified consume queue offset\n     *\n     * @param consumeQueueOffset consume queue offset.\n     * @return the message inner object serialized content\n     */',
         '    /**\n     * 按 consume queue offset 异步读取完整消息体。\n     *\n     * @param consumeQueueOffset 消费队列偏移\n     * @return 消息序列化内容\n     */'),
        ('    CompletableFuture<ByteBuffer> getMessageAsync(long consumeQueueOffset);',
         '    /** {@inheritDoc} */\n    CompletableFuture<ByteBuffer> getMessageAsync(long consumeQueueOffset);'),
        ('    /**\n     * Get message from commitLog file at specified offset and length\n     *\n     * @param offset the offset\n     * @param length the length\n     * @return the message inner object serialized content\n     */',
         '    /**\n     * 从 CommitLog 指定偏移与长度读取消息。\n     *\n     * @param offset 物理偏移\n     * @param length 读取长度\n     * @return 消息序列化内容\n     */'),
        ('    CompletableFuture<ByteBuffer> getCommitLogAsync(long offset, int length);',
         '    /** {@inheritDoc} */\n    CompletableFuture<ByteBuffer> getCommitLogAsync(long offset, int length);'),
        ('    /**\n     * Asynchronously retrieves the consume queue message at the specified queue offset\n     *\n     * @param consumeQueueOffset consume queue offset.\n     * @return the consumer queue unit serialized content\n     */',
         '    /**\n     * 异步读取单条 ConsumeQueue 单元。\n     *\n     * @param consumeQueueOffset 消费队列偏移\n     * @return CQ 单元序列化内容\n     */'),
        ('    CompletableFuture<ByteBuffer> getConsumeQueueAsync(long consumeQueueOffset);',
         '    /** {@inheritDoc} */\n    CompletableFuture<ByteBuffer> getConsumeQueueAsync(long consumeQueueOffset);'),
        ('    /**\n     * Asynchronously reads the message body from the consume queue file at the specified offset and count\n     *\n     * @param consumeQueueOffset the message offset\n     * @param count              the number of messages to read\n     * @return the consumer queue unit serialized content\n     */',
         '    /**\n     * 从指定 CQ offset 起连续读取 count 条 CQ 单元。\n     *\n     * @param consumeQueueOffset 起始偏移\n     * @param count 条数\n     * @return 合并后的 CQ 内容\n     */'),
        ('    CompletableFuture<ByteBuffer> getConsumeQueueAsync(long consumeQueueOffset, int count);',
         '    /** {@inheritDoc} */\n    CompletableFuture<ByteBuffer> getConsumeQueueAsync(long consumeQueueOffset, int count);'),
        ('    /**\n     * Gets the start offset in the consume queue based on the timestamp and boundary type.\n     * The consume queues consist of ordered units, and their storage times are non-decreasing\n     * sequence. If the specified message exists, it returns the offset of either the first\n     * or last message, depending on the boundary type. If the specified message does not exist,\n     * it returns the offset of the next message as the pull offset. For example:\n     * ------------------------------------------------------------\n     *   store time   : 40, 50, 50, 50, 60, 60, 70\n     *   queue offset : 10, 11, 12, 13, 14, 15, 16\n     * ------------------------------------------------------------\n     *   query timestamp | boundary | result (reason)\n     *         35        |    -     |   10 (minimum offset)\n     *         45        |    -     |   11 (next offset)\n     *         50        |   lower  |   11\n     *         50        |   upper  |   13\n     *         60        |    -     |   14 (default to lower)\n     *         75        |    -     |   17 (maximum offset + 1)\n     * ------------------------------------------------------------\n     * @param timestamp    The search time\n     * @param boundaryType \'lower\' or \'upper\' to determine the boundary\n     * @return Returns the offset of the message in the consume queue\n     */',
         '    /**\n     * 按时间戳与边界类型在有序 CQ 上二分查找起始 offset。\n     * 存储时间非递减；命中时按 lower/upper 取首/末条，未命中返回下一条 offset。\n     * 示例：store time 40,50,50,50,60,60,70 对应 offset 10–16；\n     * 查 35→10，45→11，50+lower→11，50+upper→13，60→14，75→17。\n     *\n     * @param timestamp 查询时间戳\n     * @param boundaryType lower 或 upper 边界\n     * @return 消费队列 offset\n     */'),
        ('    CompletableFuture<Long> getQueueOffsetByTimeAsync(long timestamp, BoundaryType boundaryType);',
         '    /** {@inheritDoc} */\n    CompletableFuture<Long> getQueueOffsetByTimeAsync(long timestamp, BoundaryType boundaryType);'),
        ('    boolean isClosed();',
         '    /** 文件是否已关闭。 */\n    boolean isClosed();'),
        ('    /**\n     * Shutdown process\n     */',
         '    /** 关闭文件与后台资源。 */'),
        ('    void shutdown();',
         '    /** {@inheritDoc} */\n    void shutdown();'),
        ('    /**\n     * Destroys expired files\n     */',
         '    /** 删除早于 timestamp 的过期文件段。 */'),
        ('    void destroyExpiredFile(long timestamp);',
         '    /** {@inheritDoc} */\n    void destroyExpiredFile(long timestamp);'),
        ('    /**\n     * Delete file\n     */',
         '    /** 删除全部文件数据。 */'),
        ('    void destroy();',
         '    /** {@inheritDoc} */\n    void destroy();'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/file/FlatFileStore.java': [
        ('public class FlatFileStore {',
         '/**\n * 分层 FlatMessageFile 仓库：加载恢复、过期调度删除与按 MessageQueue 管理文件。\n */\npublic class FlatFileStore {'),
        ('    private static final Logger log = LoggerFactory.getLogger(MessageStoreUtil.TIERED_STORE_LOGGER_NAME);',
         '    /** 分层存储日志。 */\n    private static final Logger log = LoggerFactory.getLogger(MessageStoreUtil.TIERED_STORE_LOGGER_NAME);'),
        ('    private final MetadataStore metadataStore;',
         '    /** 元数据存储。 */\n    private final MetadataStore metadataStore;'),
        ('    private final MessageStoreConfig storeConfig;',
         '    /** 存储配置。 */\n    private final MessageStoreConfig storeConfig;'),
        ('    private final MessageStoreExecutor executor;',
         '    /** 异步任务执行器。 */\n    private final MessageStoreExecutor executor;'),
        ('    private final FlatFileFactory flatFileFactory;',
         '    /** 扁平文件工厂。 */\n    private final FlatFileFactory flatFileFactory;'),
        ('    private final ConcurrentMap<MessageQueue, FlatMessageFile> flatFileConcurrentMap;',
         '    /** MessageQueue → FlatMessageFile 映射。 */\n    private final ConcurrentMap<MessageQueue, FlatMessageFile> flatFileConcurrentMap;'),
        ('    public FlatFileStore(MessageStoreConfig storeConfig, MetadataStore metadataStore, MessageStoreExecutor executor) {',
         '    /** 构造并初始化工厂与并发映射表。 */\n    public FlatFileStore(MessageStoreConfig storeConfig, MetadataStore metadataStore, MessageStoreExecutor executor) {'),
        ('    public boolean load() {',
         '    /** 清空映射并 recover 全部 Topic/Queue 文件。 */\n    public boolean load() {'),
        ('    public void recover() {',
         '    /** 并发恢复各 Topic 下所有 Queue 的 FlatMessageFile。 */\n    public void recover() {'),
        ('    public CompletableFuture<Void> recoverAsync(TopicMetadata topicMetadata) {',
         '    /** 异步恢复单个 Topic 下全部 Queue。 */\n    public CompletableFuture<Void> recoverAsync(TopicMetadata topicMetadata) {'),
        ('    public void scheduleDeleteExpireFile() {',
         '    /** 定时任务：按保留小时数删除各文件过期段。 */\n    public void scheduleDeleteExpireFile() {'),
        ('    public MetadataStore getMetadataStore() {',
         '    /** 返回元数据存储。 */\n    public MetadataStore getMetadataStore() {'),
        ('    public MessageStoreConfig getStoreConfig() {',
         '    /** 返回存储配置。 */\n    public MessageStoreConfig getStoreConfig() {'),
        ('    public FlatFileFactory getFlatFileFactory() {',
         '    /** 返回扁平文件工厂。 */\n    public FlatFileFactory getFlatFileFactory() {'),
        ('    public FlatMessageFile computeIfAbsent(MessageQueue messageQueue) {',
         '    /** 获取或创建指定 Queue 的 FlatMessageFile。 */\n    public FlatMessageFile computeIfAbsent(MessageQueue messageQueue) {'),
        ('    public FlatMessageFile getFlatFile(MessageQueue messageQueue) {',
         '    /** 返回已存在的 FlatMessageFile，不存在则 null。 */\n    public FlatMessageFile getFlatFile(MessageQueue messageQueue) {'),
        ('    public ImmutableList<FlatMessageFile> deepCopyFlatFileToList() {',
         '    /** 深拷贝当前全部 FlatMessageFile 列表。 */\n    public ImmutableList<FlatMessageFile> deepCopyFlatFileToList() {'),
        ('    public void shutdown() {',
         '    /** 关闭全部 FlatMessageFile。 */\n    public void shutdown() {'),
        ('    public void destroyFile(MessageQueue mq) {',
         '    /** 移除并销毁指定 Queue 的文件。 */\n    public void destroyFile(MessageQueue mq) {'),
        ('    public void destroy() {',
         '    /** 关闭并销毁全部文件后清空映射。 */\n    public void destroy() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexFile.java': [
        ('public interface IndexFile extends IndexService {',
         '/**\n * 索引文件接口：扩展 {@link IndexService}，提供时间范围、状态与 compaction 能力。\n */\npublic interface IndexFile extends IndexService {'),
        ('    /**\n     * Enumeration for the status of the index file.\n     */',
         '    /** 索引文件生命周期状态。 */'),
        ('    enum IndexStatusEnum {',
         '    /** 索引文件生命周期状态枚举。 */\n    enum IndexStatusEnum {'),
        ('        SHUTDOWN, UNSEALED, SEALED, UPLOAD',
         '        /** 已关闭 */ SHUTDOWN, /** 未封存 */ UNSEALED, /** 已封存 */ SEALED, /** 已上传 */ UPLOAD'),
        ('    long getTimestamp();',
         '    /** 索引文件起始时间戳。 */\n    long getTimestamp();'),
        ('    long getEndTimestamp();',
         '    /** 索引文件结束时间戳。 */\n    long getEndTimestamp();'),
        ('    IndexStatusEnum getFileStatus();',
         '    /** 当前文件状态。 */\n    IndexStatusEnum getFileStatus();'),
        ('    ByteBuffer doCompaction();',
         '    /** 执行索引 compaction 并返回压缩后缓冲区。 */\n    ByteBuffer doCompaction();'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexItem.java': [
        ('public class IndexItem {',
         '/**\n * 索引项：32 字节（紧凑模式 28 字节）固定布局，含 hash、topicId、queueId、offset 等。\n */\npublic class IndexItem {'),
        ('    public static final int INDEX_ITEM_SIZE = 32;',
         '    /** 标准索引项字节长度。 */\n    public static final int INDEX_ITEM_SIZE = 32;'),
        ('    public static final int COMPACT_INDEX_ITEM_SIZE = 28;',
         '    /** 紧凑索引项字节长度。 */\n    public static final int COMPACT_INDEX_ITEM_SIZE = 28;'),
        ('    private final int hashCode;',
         '    /** 键哈希码。 */\n    private final int hashCode;'),
        ('    private final int topicId;',
         '    /** Topic 内部 ID。 */\n    private final int topicId;'),
        ('    private final int queueId;',
         '    /** 队列 ID。 */\n    private final int queueId;'),
        ('    private final long offset;',
         '    /** CommitLog 物理偏移。 */\n    private final long offset;'),
        ('    private final int size;',
         '    /** 消息体大小。 */\n    private final int size;'),
        ('    private final int timeDiff;',
         '    /** 相对文件基准的时间差。 */\n    private final int timeDiff;'),
        ('    private final int itemIndex;',
         '    /** 在索引文件中的序号。 */\n    private final int itemIndex;'),
        ('    public IndexItem(int topicId, int queueId, long offset, int size, int hashCode, int timeDiff, int itemIndex) {',
         '    /** 全字段构造索引项。 */\n    public IndexItem(int topicId, int queueId, long offset, int size, int hashCode, int timeDiff, int itemIndex) {'),
        ('    public IndexItem(byte[] bytes) {',
         '    /** 从 32 或 28 字节数组反序列化。 */\n    public IndexItem(byte[] bytes) {'),
        ('    public ByteBuffer getByteBuffer() {',
         '    /** 序列化为 32 字节 ByteBuffer。 */\n    public ByteBuffer getByteBuffer() {'),
        ('    public int getHashCode() {',
         '    /** 返回键哈希码。 */\n    public int getHashCode() {'),
        ('    public int getTopicId() {',
         '    /** 返回 Topic ID。 */\n    public int getTopicId() {'),
        ('    public int getQueueId() {',
         '    /** 返回队列 ID。 */\n    public int getQueueId() {'),
        ('    public long getOffset() {',
         '    /** 返回物理偏移。 */\n    public long getOffset() {'),
        ('    public int getSize() {',
         '    /** 返回消息大小。 */\n    public int getSize() {'),
        ('    public int getTimeDiff() {',
         '    /** 返回时间差。 */\n    public int getTimeDiff() {'),
        ('    public int getItemIndex() {',
         '    /** 返回项序号。 */\n    public int getItemIndex() {'),
        ('    @Override\n    public String toString() {',
         '    /** 调试字符串。 */\n    @Override\n    public String toString() {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/index/IndexService.java': [
        ('public interface IndexService {',
         '/**\n * 分层存储索引服务：写入键、按时间范围查询与生命周期管理。\n */\npublic interface IndexService {'),
        ('    void start();',
         '    /** 启动索引后台服务。 */\n    void start();'),
        ('    /**\n     * Puts a key into the index.\n     *\n     * @param topic     The topic of the key.\n     * @param topicId   The ID of the topic.\n     * @param queueId   The ID of the queue.\n     * @param keySet    The set of keys to be indexed.\n     * @param offset    The offset value of the key.\n     * @param size      The size of the key.\n     * @param timestamp The timestamp of the key.\n     * @return The result of the put operation.\n     */',
         '    /**\n     * 将消息键写入索引。\n     *\n     * @param topic Topic 名称\n     * @param topicId Topic 内部 ID\n     * @param queueId 队列 ID\n     * @param keySet 待索引键集合\n     * @param offset CommitLog 偏移\n     * @param size 消息大小\n     * @param timestamp 存储时间戳\n     * @return 写入结果\n     */'),
        ('    AppendResult putKey(',
         '    /** {@inheritDoc} */\n    AppendResult putKey('),
        ('    /**\n     * Asynchronously queries the index for a specific key within a given time range.\n     *\n     * @param topic     The topic of the key.\n     * @param key       The key to be queried.\n     * @param beginTime The start time of the query range.\n     * @param endTime   The end time of the query range.\n     * @return A CompletableFuture that holds the list of IndexItems matching the query.\n     */',
         '    /**\n     * 异步按 Topic、键与时间范围查询索引项。\n     *\n     * @param topic Topic 名称\n     * @param key 查询键\n     * @param maxCount 最大返回条数\n     * @param beginTime 起始时间\n     * @param endTime 结束时间\n     * @return 匹配的 IndexItem 列表\n     */'),
        ('    CompletableFuture<List<IndexItem>> queryAsync(String topic, String key, int maxCount, long beginTime, long endTime);',
         '    /** {@inheritDoc} */\n    CompletableFuture<List<IndexItem>> queryAsync(String topic, String key, int maxCount, long beginTime, long endTime);'),
        ('    default void forceUpload() {',
         '    /** 强制上传索引文件（默认空实现）。 */\n    default void forceUpload() {'),
        ('    /**\n     * Shutdown the index service.\n     */',
         '    /** 优雅关闭索引服务。 */'),
        ('    void shutdown();',
         '    /** {@inheritDoc} */\n    void shutdown();'),
        ('    /**\n     * Force shutdown the index service.\n     */',
         '    /** 强制关闭索引服务。 */'),
        ('    default void forceShutdown() {',
         '    /** {@inheritDoc} 默认调用 shutdown。 */\n    default void forceShutdown() {'),
        ('    /**\n     * Destroys the index service and releases all resources.\n     */',
         '    /** 销毁索引服务并释放全部资源。 */'),
        ('    void destroy();',
         '    /** {@inheritDoc} */\n    void destroy();'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metadata/DefaultMetadataStore.java': [
        ('public class DefaultMetadataStore extends ConfigManager implements MetadataStore {',
         '/**\n * 默认分层元数据存储：Topic/Queue/FileSegment 内存表持久化至 tieredStoreMetadata.json。\n */\npublic class DefaultMetadataStore extends ConfigManager implements MetadataStore {'),
        ('    private static final int DEFAULT_CAPACITY = 1024;',
         '    /** 初始哈希表容量。 */\n    private static final int DEFAULT_CAPACITY = 1024;'),
        ('    private static final String DEFAULT_CONFIG_NAME = "config";',
         '    /** 配置文件目录名。 */\n    private static final String DEFAULT_CONFIG_NAME = "config";'),
        ('    private static final String DEFAULT_FILE_NAME = "tieredStoreMetadata.json";',
         '    /** 元数据 JSON 文件名。 */\n    private static final String DEFAULT_FILE_NAME = "tieredStoreMetadata.json";'),
        ('    private final AtomicLong topicSequenceNumber;',
         '    /** Topic 自增序列号。 */\n    private final AtomicLong topicSequenceNumber;'),
        ('    private final MessageStoreConfig storeConfig;',
         '    /** 存储配置。 */\n    private final MessageStoreConfig storeConfig;'),
        ('    private final ConcurrentMap<String /* topic */, TopicMetadata> topicMetadataTable;',
         '    /** Topic 名 → 元数据。 */\n    private final ConcurrentMap<String /* topic */, TopicMetadata> topicMetadataTable;'),
        ('    private final ConcurrentMap<String /* topic */, ConcurrentMap<Integer, QueueMetadata>> queueMetadataTable;',
         '    /** Topic → (queueId → QueueMetadata)。 */\n    private final ConcurrentMap<String /* topic */, ConcurrentMap<Integer, QueueMetadata>> queueMetadataTable;'),
        ('    // Declare concurrent mapping tables to store file segment metadata\n    // Key: filePath -> Value: <baseOffset, metadata>\n    private final ConcurrentMap<String, ConcurrentMap<Long, FileSegmentMetadata>> commitLogFileSegmentTable;',
         '    /** CommitLog 文件段元数据：filePath → (baseOffset → metadata)。 */\n    private final ConcurrentMap<String, ConcurrentMap<Long, FileSegmentMetadata>> commitLogFileSegmentTable;'),
        ('    private final ConcurrentMap<String, ConcurrentMap<Long, FileSegmentMetadata>> consumeQueueFileSegmentTable;',
         '    /** ConsumeQueue 文件段元数据表。 */\n    private final ConcurrentMap<String, ConcurrentMap<Long, FileSegmentMetadata>> consumeQueueFileSegmentTable;'),
        ('    private final ConcurrentMap<String, ConcurrentMap<Long, FileSegmentMetadata>> indexFileSegmentTable;',
         '    /** Index 文件段元数据表。 */\n    private final ConcurrentMap<String, ConcurrentMap<Long, FileSegmentMetadata>> indexFileSegmentTable;'),
        ('    public DefaultMetadataStore(MessageStoreConfig storeConfig) {',
         '    /** 构造并 load 持久化元数据。 */\n    public DefaultMetadataStore(MessageStoreConfig storeConfig) {'),
        ('    @Override\n    public String encode() {',
         '    /** 序列化为 JSON 字符串。 */\n    @Override\n    public String encode() {'),
        ('    @Override\n    public String encode(boolean prettyFormat) {',
         '    /** 可选 PrettyFormat 的 JSON 编码。 */\n    @Override\n    public String encode(boolean prettyFormat) {'),
        ('    @Override\n    public String configFilePath() {',
         '    /** 返回 tieredStoreMetadata.json 路径。 */\n    @Override\n    public String configFilePath() {'),
        ('    @Override\n    public boolean load() {',
         '    /** 从磁盘加载元数据。 */\n    @Override\n    public boolean load() {'),
        ('    @Override\n    public void decode(String jsonString) {',
         '    /** 从 JSON 反序列化各元数据表。 */\n    @Override\n    public void decode(String jsonString) {'),
        ('    @Override\n    public TopicMetadata getTopic(String topic) {',
         '    /** {@inheritDoc} */\n    @Override\n    public TopicMetadata getTopic(String topic) {'),
        ('    @Override\n    public void iterateTopic(Consumer<TopicMetadata> callback) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void iterateTopic(Consumer<TopicMetadata> callback) {'),
        ('    @Override\n    public TopicMetadata addTopic(String topic, long reserveTime) {',
         '    /** {@inheritDoc} 已存在则返回旧值。 */\n    @Override\n    public TopicMetadata addTopic(String topic, long reserveTime) {'),
        ('    @Override\n    public void updateTopic(TopicMetadata topicMetadata) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void updateTopic(TopicMetadata topicMetadata) {'),
        ('    @Override\n    public void deleteTopic(String topic) {',
         '    /** {@inheritDoc} 同时删除下属 Queue 元数据。 */\n    @Override\n    public void deleteTopic(String topic) {'),
        ('    @Override\n    public QueueMetadata getQueue(MessageQueue mq) {',
         '    /** {@inheritDoc} */\n    @Override\n    public QueueMetadata getQueue(MessageQueue mq) {'),
        ('    @Override\n    public void iterateQueue(String topic, Consumer<QueueMetadata> callback) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void iterateQueue(String topic, Consumer<QueueMetadata> callback) {'),
        ('    @Override\n    public QueueMetadata addQueue(MessageQueue mq, long baseOffset) {',
         '    /** {@inheritDoc} */\n    @Override\n    public QueueMetadata addQueue(MessageQueue mq, long baseOffset) {'),
        ('    @Override\n    public void updateQueue(QueueMetadata metadata) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void updateQueue(QueueMetadata metadata) {'),
        ('    @Override\n    public void deleteQueue(MessageQueue mq) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void deleteQueue(MessageQueue mq) {'),
        ('    @VisibleForTesting\n    public Map<String, ConcurrentMap<Long, FileSegmentMetadata>> getTableByFileType(',
         '    /** 测试用：按文件类型返回段元数据表。 */\n    @VisibleForTesting\n    public Map<String, ConcurrentMap<Long, FileSegmentMetadata>> getTableByFileType('),
        ('    @Override\n    public FileSegmentMetadata getFileSegment(',
         '    /** {@inheritDoc} */\n    @Override\n    public FileSegmentMetadata getFileSegment('),
        ('    @Override\n    public void updateFileSegment(FileSegmentMetadata fileSegmentMetadata) {',
         '    /** {@inheritDoc} 写入后 persist。 */\n    @Override\n    public void updateFileSegment(FileSegmentMetadata fileSegmentMetadata) {'),
        ('    @Override\n    public void iterateFileSegment(Consumer<FileSegmentMetadata> callback) {',
         '    /** {@inheritDoc} 遍历三类文件段。 */\n    @Override\n    public void iterateFileSegment(Consumer<FileSegmentMetadata> callback) {'),
        ('    @Override\n    public void iterateFileSegment(String basePath, FileSegmentType fileType, Consumer<FileSegmentMetadata> callback) {',
         '    /** {@inheritDoc} */\n    @Override\n    public void iterateFileSegment(String basePath, FileSegmentType fileType, Consumer<FileSegmentMetadata> callback) {'),
        ('    @Override\n    public void deleteFileSegment(String filePath, FileSegmentType fileType) {',
         '    /** {@inheritDoc} 删除路径下全部段。 */\n    @Override\n    public void deleteFileSegment(String filePath, FileSegmentType fileType) {'),
        ('    @Override\n    public void deleteFileSegment(String basePath, FileSegmentType fileType, long baseOffset) {',
         '    /** {@inheritDoc} 删除指定 baseOffset 段。 */\n    @Override\n    public void deleteFileSegment(String basePath, FileSegmentType fileType, long baseOffset) {'),
        ('    @Override\n    public void destroy() {',
         '    /** {@inheritDoc} 清空全部表并 persist。 */\n    @Override\n    public void destroy() {'),
        ('    static class TieredMetadataSerializeWrapper extends RemotingSerializable {',
         '    /** JSON 序列化包装类，承载全部元数据表。 */\n    static class TieredMetadataSerializeWrapper extends RemotingSerializable {'),
    ],
    'tieredstore/src/main/java/org/apache/rocketmq/tieredstore/metadata/MetadataStore.java': [
        ('/**\n * Provides tiered metadata storage service to store metadata information of Topic, Queue, FileSegment, etc.\n */',
         '/**\n * 分层元数据存储服务：管理 Topic、Queue、FileSegment 等元信息的 CRUD 与迭代。\n */'),
        ('    /**\n     * Get the metadata information of specified Topic.\n     *\n     * @param topic The name of Topic.\n     * @return The metadata information of specified Topic, or null if it does not exist.\n     */',
         '    /**\n     * 获取指定 Topic 的元数据。\n     *\n     * @param topic Topic 名称\n     * @return 元数据，不存在则 null\n     */'),
        ('    TopicMetadata getTopic(String topic);',
         '    /** {@inheritDoc} */\n    TopicMetadata getTopic(String topic);'),
        ('    /**\n     * Add a new metadata information of Topic.\n     *\n     * @param topic       The name of Topic.\n     * @param reserveTime The reserve time.\n     * @return The newly added metadata information of Topic.\n     */',
         '    /**\n     * 新增 Topic 元数据。\n     *\n     * @param topic Topic 名称\n     * @param reserveTime 保留时长\n     * @return 新建的 TopicMetadata\n     */'),
        ('    TopicMetadata addTopic(String topic, long reserveTime);',
         '    /** {@inheritDoc} */\n    TopicMetadata addTopic(String topic, long reserveTime);'),
        ('    void updateTopic(TopicMetadata topicMetadata);',
         '    /** 更新 Topic 元数据。 */\n    void updateTopic(TopicMetadata topicMetadata);'),
        ('    void iterateTopic(Consumer<TopicMetadata> callback);',
         '    /** 迭代全部 Topic 元数据。 */\n    void iterateTopic(Consumer<TopicMetadata> callback);'),
        ('    void deleteTopic(String topic);',
         '    /** 删除 Topic 及其 Queue 元数据。 */\n    void deleteTopic(String topic);'),
        ('    QueueMetadata getQueue(MessageQueue mq);',
         '    /** 获取指定 MessageQueue 元数据。 */\n    QueueMetadata getQueue(MessageQueue mq);'),
        ('    QueueMetadata addQueue(MessageQueue mq, long baseOffset);',
         '    /** 新增 Queue 元数据。 */\n    QueueMetadata addQueue(MessageQueue mq, long baseOffset);'),
        ('    void updateQueue(QueueMetadata queueMetadata);',
         '    /** 更新 Queue 元数据。 */\n    void updateQueue(QueueMetadata queueMetadata);'),
        ('    void iterateQueue(String topic, Consumer<QueueMetadata> callback);',
         '    /** 迭代指定 Topic 下全部 Queue。 */\n    void iterateQueue(String topic, Consumer<QueueMetadata> callback);'),
        ('    void deleteQueue(MessageQueue mq);',
         '    /** 删除 Queue 元数据。 */\n    void deleteQueue(MessageQueue mq);'),
        ('    FileSegmentMetadata getFileSegment(String basePath, FileSegmentType fileType, long baseOffset);',
         '    /** 获取文件段元数据。 */\n    FileSegmentMetadata getFileSegment(String basePath, FileSegmentType fileType, long baseOffset);'),
        ('    void updateFileSegment(FileSegmentMetadata fileSegmentMetadata);',
         '    /** 更新或插入文件段元数据。 */\n    void updateFileSegment(FileSegmentMetadata fileSegmentMetadata);'),
        ('    void iterateFileSegment(Consumer<FileSegmentMetadata> callback);',
         '    /** 迭代全部类型文件段。 */\n    void iterateFileSegment(Consumer<FileSegmentMetadata> callback);'),
        ('    void iterateFileSegment(String basePath, FileSegmentType fileType, Consumer<FileSegmentMetadata> callback);',
         '    /** 迭代指定路径与类型的文件段。 */\n    void iterateFileSegment(String basePath, FileSegmentType fileType, Consumer<FileSegmentMetadata> callback);'),
        ('    void deleteFileSegment(String basePath, FileSegmentType fileType);',
         '    /** 删除路径下全部文件段元数据。 */\n    void deleteFileSegment(String basePath, FileSegmentType fileType);'),
        ('    void deleteFileSegment(String basePath, FileSegmentType fileType, long baseOffset);',
         '    /** 删除指定 baseOffset 的文件段元数据。 */\n    void deleteFileSegment(String basePath, FileSegmentType fileType, long baseOffset);'),
        ('    void destroy();',
         '    /** 销毁全部元数据。 */\n    void destroy();'),
    ],
}
