# This file is autogenerated by the command `make fix-copies`, do not edit.
# torchvision 占位模块：未安装 torchvision 时视频处理类延迟报错
from ..utils import DummyObject, requires_backends


# TorchvisionBackend：torchvision 占位类：torchvision 后端占位，未安装 torchvision 时延迟报错
class TorchvisionBackend(metaclass=DummyObject):
    _backends = ["torchvision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torchvision"])


# BaseVideoProcessor：torchvision 占位类：基础视频处理器占位，未安装 torchvision 时延迟报错
class BaseVideoProcessor(metaclass=DummyObject):
    _backends = ["torchvision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torchvision"])
