# This file is autogenerated by the command `make fix-copies`, do not edit.
# tokenizers 占位模块：未安装 tokenizers 时 PreTrainedTokenizerFast 延迟报错
from ..utils import DummyObject, requires_backends


# PreTrainedTokenizerFast：tokenizers 占位类：未安装 tokenizers 时延迟报错
class PreTrainedTokenizerFast(metaclass=DummyObject):
    _backends = ["tokenizers"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["tokenizers"])
