# This file is autogenerated by the command `make fix-copies`, do not edit.
# vision 占位模块：未安装 vision 依赖时图像处理 Mixin 类延迟报错
from ..utils import DummyObject, requires_backends


# ImageProcessingMixin：vision 占位类：图像处理 Mixin 占位，未安装 vision 依赖时延迟报错
class ImageProcessingMixin(metaclass=DummyObject):
    _backends = ["vision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["vision"])


# BaseImageProcessor：vision 占位类：基础图像处理器占位，未安装 vision 依赖时延迟报错
class BaseImageProcessor(metaclass=DummyObject):
    _backends = ["vision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["vision"])


# ImageFeatureExtractionMixin：vision 占位类：图像特征提取 Mixin 占位，未安装 vision 依赖时延迟报错
class ImageFeatureExtractionMixin(metaclass=DummyObject):
    _backends = ["vision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["vision"])
