# This file is autogenerated by the command `make fix-copies`, do not edit.
# music 后端占位模块：未安装 music 依赖时 Pop2Piano 类延迟报错
from ..utils import DummyObject, requires_backends


# Pop2PianoFeatureExtractor：music 占位类：未安装 music 依赖时延迟报错
class Pop2PianoFeatureExtractor(metaclass=DummyObject):
    _backends = ["music"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["music"])


# Pop2PianoTokenizer：music 占位类：未安装 music 依赖时延迟报错
class Pop2PianoTokenizer(metaclass=DummyObject):
    _backends = ["music"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["music"])
