# This file is autogenerated by the command `make fix-copies`, do not edit.
# detectron2 占位模块：未安装 detectron2 时 LayoutLMv2 延迟报错
from ..utils import requires_backends


# LayoutLMv2Model：detectron2 占位类：未安装 detectron2 时延迟报错
class LayoutLMv2Model:
    def __init__(self, *args, **kwargs):
        requires_backends(self, ["detectron2"])

    @classmethod
    def from_pretrained(cls, *args, **kwargs):
        requires_backends(cls, ["detectron2"])
