# This file is autogenerated by the command `make fix-copies`, do not edit.
# mistral-common 占位模块：未安装 mistral-common 时延迟报错
from ..utils import DummyObject, requires_backends


# MistralCommonBackend：mistral-common 占位类：未安装 mistral-common 时延迟报错
class MistralCommonBackend(metaclass=DummyObject):
    _backends = ["mistral-common"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["mistral-common"])
