# This file is autogenerated by the command `make fix-copies`, do not edit.
# sentencepiece/tokenizers 占位：慢速分词器转快速分词器转换函数延迟报错
from ..utils import DummyObject, requires_backends


SLOW_TO_FAST_CONVERTERS = None


def convert_slow_tokenizer(*args, **kwargs):
    requires_backends(convert_slow_tokenizer, ["sentencepiece", "tokenizers"])
