# This file is autogenerated by the command `make fix-copies`, do not edit.
# Pop2Piano 多后端占位：essentia/librosa/pretty_midi/scipy/torch 缺失时延迟报错
from ..utils import DummyObject, requires_backends


# Pop2PianoFeatureExtractor：Pop2Piano 多后端占位：essentia/librosa 等缺失时延迟报错
class Pop2PianoFeatureExtractor(metaclass=DummyObject):
    _backends = ["essentia", "librosa", "pretty_midi", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["essentia", "librosa", "pretty_midi", "scipy", "torch"])


# Pop2PianoTokenizer：Pop2Piano 多后端占位：essentia/librosa 等缺失时延迟报错
class Pop2PianoTokenizer(metaclass=DummyObject):
    _backends = ["essentia", "librosa", "pretty_midi", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["essentia", "librosa", "pretty_midi", "scipy", "torch"])


# Pop2PianoProcessor：Pop2Piano 多后端占位：essentia/librosa 等缺失时延迟报错
class Pop2PianoProcessor(metaclass=DummyObject):
    _backends = ["essentia", "librosa", "pretty_midi", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["essentia", "librosa", "pretty_midi", "scipy", "torch"])
