# This file is autogenerated by the command `make fix-copies`, do not edit.
# speech 后端占位模块：未安装 speech 依赖时 AST/Speech2Text 延迟报错
from ..utils import DummyObject, requires_backends


# ASTFeatureExtractor：speech 占位类：未安装 speech 依赖时延迟报错
class ASTFeatureExtractor(metaclass=DummyObject):
    _backends = ["speech"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["speech"])


# Speech2TextFeatureExtractor：speech 占位类：未安装 speech 依赖时延迟报错
class Speech2TextFeatureExtractor(metaclass=DummyObject):
    _backends = ["speech"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["speech"])
