# This file is autogenerated by the command `make fix-copies`, do not edit.
# timm/torchvision 占位模块：未安装 timm 或 torchvision 时延迟报错
from ..utils import DummyObject, requires_backends


# TimmWrapperImageProcessor：timm/torchvision 占位类：未安装依赖时延迟报错
class TimmWrapperImageProcessor(metaclass=DummyObject):
    _backends = ["timm", "torchvision"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["timm", "torchvision"])
