# This file is autogenerated by the command `make fix-copies`, do not edit.
# PyTorch 占位模块：未安装 torch 时 Cache/Generation/Trainer 等类延迟报错
from ..utils import DummyObject, requires_backends


# Cache：PyTorch 占位类：KV cache 基类占位，未安装 torch 时延迟报错
class Cache(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwar# DynamicCache：PyTorch 占位类：动态 KV cache 占位，未安装 torch 时延迟报错
gs):
        requires_backends(self, ["torch"])


class DynamicCache(metaclass=DummyObject):
    _# EncoderDecoderCache：PyTorch 占位类：编解码器 KV cache 占位，未安装 torch 时延迟报错
backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, [# QuantizedCache：PyTorch 占位类：量化 KV cache 占位，未安装 torch 时延迟报错
"torch"])


class EncoderDecoderCache(metaclass=DummyObject):
    _backends = ["torch"]

    def _# StaticCache：PyTorch 占位类：静态 KV cache 占位，未安装 torch 时延迟报错
_init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class QuantizedCache(# GlueDataset：PyTorch 占位类：GLUE 数据集占位，未安装 torch 时延迟报错
metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        re# GlueDataTrainingArguments：PyTorch 占位类：GLUE 训练参数占位，未安装 torch 时延迟报错
quires_backends(self, ["torch"])


class StaticCache(metaclass=DummyObject):
    _backends = ["torch"# SquadDataset：PyTorch 占位类：SQuAD 数据集占位，未安装 torch 时延迟报错
]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


# GlueDa：PyTorch 占位类：GlueDa 占位，未安装 torch 时延迟报错
class GlueDa# SquadDataTrainingArguments：PyTorch 占位类：SQuAD 训练参数占位，未安装 torch 时延迟报错
taset(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
  # AlternatingCodebooksLogitsProcessor：PyTorch 占位类：AlternatingCodebooksLogitsProcessor 占位，未安装 torch 时延迟报错
      requires_backends(self, ["torch"])


class GlueDataTrainingArguments# BayesianDetectorConfig：PyTorch 占位类：BayesianDetectorConfig 占位，未安装 torch 时延迟报错
(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwa# BayesianDetectorModel：PyTorch 占位类：BayesianDetectorModel 占位，未安装 torch 时延迟报错
rgs):
        requires_backends(self, ["torch"])


class SquadDataset(metaclass=DummyObj# ClassifierFreeGuidanceLogitsProcessor：PyTorch 占位类：ClassifierFreeGuidanceLogitsProcessor 占位，未安装 torch 时延迟报错
ect):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs)# EncoderNoRepeatNGramLogitsProcessor：PyTorch 占位类：EncoderNoRepeatNGramLogitsProcessor 占位，未安装 torch 时延迟报错
# SquadDataTrainingArgu：PyTorch 占位类：SquadDataTrainingArgu 占位，未安装 torch 时延迟报错
:
        requires_backends(self, ["torch"])


class SquadDataTrainingArgu# EncoderRepetitionPenaltyLogitsProcessor：PyTorch 占位类：EncoderRepetitionPenaltyLogitsProcessor 占位，未安装 torch 时延迟报错
ments(metaclass=DummyObject):
    _backends = ["torch"]

    def __ini# EosTokenCriter# AlternatingCod：PyTorch 占位类：AlternatingCod 占位，未安装 torch 时延迟报错
ia：PyTorch 占位类：EosTokenCriteria 占位，未安装 torch 时延迟报错
t__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class AlternatingCod# EpsilonLogitsWarper：PyTorch 占位类：EpsilonLogitsWarper 占位，未安装 torch 时延迟报错
ebooksLogitsProcessor(metaclass=Dummy# BayesianDetectorCon：PyTorch 占位类：BayesianDetectorCon 占位，未安装 torch 时延迟报错
Object):
    _backends = ["torch"]

    def __init__(# EtaLogitsWarper：PyTorch 占位类：EtaLogitsWarper 占位，未安装 torch 时延迟报错
self, *args, **kwargs):
        requires_backends(self, ["torch"])


class BayesianDetectorCon# ExponentialDecayLengthPenalty：PyTorch 占位类：ExponentialDecayLengthP# BayesianDetec：PyTorch 占位类：BayesianDetec 占位，未安装 torch 时延迟报错
enalty 占位，未安装 torch 时延迟报错
fig(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *a# ForcedBOSTokenLogitsProcessor：PyTorch 占位类：ForcedBOSTokenLogitsProcessor 占位，未安装 torch 时延迟报错
rgs, **kwargs):
        requires_backends(self, ["torch"])# ClassifierFreeGuidanceLogit：PyTorch 占位类：ClassifierFreeGuidanceLogit 占位，未安装 torch 时延迟报错



class BayesianDetec# ForcedEOSTokenLogitsProcessor：PyTorch 占位类：ForcedEOSTokenLogitsProcessor 占位，未安装 torch 时延迟报错
torModel(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(sel# GenerationMixin：PyTorch 占位类：文本生成 Mixin 占位，未安装 torch 时延迟# EncoderNoRepeatNGra：PyTorch 占位类：EncoderNoRepeatNGra 占位，未安装 torch 时延迟报错
报错
f, *args, **kwargs):
        requires_backends(self, ["torch"])


class ClassifierFreeGuidanceLogit# InfNanRemoveLogitsProcessor：PyTorch 占位类：InfNanRemoveLogitsProcessor 占位，未安装 torch 时延迟报错
sProcessor(metaclass=DummyObject):
    _b# EncoderRepetitionPenaltyLogitsProces：PyTorch 占位类：EncoderRepetitionPenaltyLogitsProces 占位，未安装 torch 时延迟报错
ackends = ["torch"]

    def __init__(sel# LogitNormalization：PyTorch 占位类：LogitNormalization 占位，未安装 torch 时延迟报错
f, *args, **kwargs):
        requires_backends(self, ["torch"])


class EncoderNoRepeatNGra# Logit# EosTokenCriteria：PyTorch 占位类：EosTokenCriteria 占位，未安装 torch 时延迟报错
sProcessor：PyTorch 占位类：logits 处理器基类占位，未安装 torch 时延迟报错
mLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, # LogitsProcessorList：PyTorch 占位类：logits 处理器列表占位，未安装 torch 时延迟报错
**kwargs):
        requires_backends(self, ["torch"])


class EncoderRepetitionPenaltyLogitsProces# MaxLengthCriteria：PyTorch 占位类：MaxLengthCriteria 占位，未安装 torch 时延迟报错
sor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwarg# MaxTimeCriteria：PyTorch 占位类：MaxTimeCriteria 占位，未安装 torch 时延迟报错
s):
        requires_backends(self, ["torch"])


class EosTokenCriteria(metaclass=DummyObject)# MinLengthLogitsProcessor：PyTorch 占位类：MinLengthLogitsProcessor 占位，未安装 torch 时延迟报错
:
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        require# MinNewTokensLengthLogitsProcessor：PyTorch 占位类：MinNewTokensLengthLogitsProcessor 占位，未安装 torch 时延迟报错
s_backends(self, ["torch"])


class E# ExponentialDecayLengthPenalty：PyTorch 占位类：ExponentialDecayLengthPenalty 占位，未安装 torch 时延迟报错
psilonLogitsWarper(metaclass=DummyObjec# MinPLogitsWarper：PyTorch 占位类：MinPLogitsWarper 占位，未安装 torch 时延迟报错
t):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_back# NoBadWordsLogitsProcessor：PyTorch 占位类：NoBadWordsLogitsProcessor 占位，未安装 torch 时延迟报错
ends(self, ["torch"])


class EtaLogitsWarper(metaclass=DummyObject):
    _backends # NoRepeatNGramLogitsProcessor：PyTorch 占位类：NoRepeatNGramLogitsProcessor 占位，未安装 torch 时延迟报错
= ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(s# PrefixConstrainedLogitsProcessor：PyTorch 占位类：PrefixConstrainedLogitsProcessor 占位，未安装 torch 时延迟报错
elf, ["torch"])


class ExponentialDecayLengthPenalty(metaclass=DummyObject):# RepetitionPenaltyLogitsProcessor：PyTorch 占位类：RepetitionPenaltyLogitsProcessor 占位，未安装 torch 时延迟报错

    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        # SequenceBiasLo# GenerationMixin：PyTorch 占位类：文本生成 Mixin 占位，未安装 torch 时延迟报错
gitsProcessor：PyTorch 占位类：SequenceBiasLogitsProcessor 占位，未安装 torch 时延迟报错
requires_backends(self, ["torch"])


class ForcedBOSTokenLogitsProcessor(metaclass# StoppingCriteria：PyTorch 占位类：停止条件基类占位，未安装 torch 时延迟报错
=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_back# StoppingCriteriaList：PyTorch 占位类：停止条件列表占位，未安装 torch 时延迟报错
ends(self, ["torch"])


class ForcedEOSTokenLogitsProcessor(metaclass=DummyObject):
    _backends = ["to# StopStringCriteria：PyTorch 占位类：StopStringCriteria 占位，未安装 torch 时延迟报错
rch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])
# SuppressTokensAtBeginLogitsProcessor：PyTorch 占位类：SuppressTokensAtBeginLogitsProcessor 占位，未安装 torch 时延迟报错


class GenerationMixin(metaclass=DummyObject):
    _backends = ["torch"]# SuppressTokensLogitsProcessor：PyTorch 占位类：SuppressTokensLogitsProcessor 占位，未安装 torch 时延迟报错


    def __init__(self, *args, **kwargs):
     # LogitsProcessor：PyTorch 占位类：logits 处理器基类占位，未安装 torch 时延迟报错
   requires_backends(self, ["tor# SynthIDTextWatermarkDetector：PyTorch 占位类：SynthIDTextWatermarkDetector 占位，未安装 torch 时延迟报错
ch"])


class InfNanRemoveLogitsProcessor(# L：PyTorch 占位类：L 占位，未安装 torch 时延迟报错
metaclass=DummyObject):
    _backends =# SynthIDTextWatermarkingConfig：PyTorch 占位类：SynthIDTextWatermarkingConfig 占位，未安装 torch 时延迟报错
 ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(s# SynthIDTextWatermarkLogitsProcessor：PyTorch 占位类：SynthIDTextWatermarkLogitsProcessor 占位，未安装 torch 时延迟报错
elf, ["torch"])


class LogitNormalization(metaclass=DummyObject):
    _ba# TemperatureLogitsWarper：PyTorch 占位类：TemperatureLogitsWarper 占位，未安装 torch 时延迟报错
ckends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends# TopKLogitsWarper：PyTorch 占位类：TopKLogitsWarper 占位，未安装 torch 时延迟报错
(self, ["torch# MaxTime：PyTorch 占位类：MaxTime 占位，未安装 torch 时延迟报错
"])


class LogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

# TopPLogitsWarper：PyTorch 占位类：TopPLogitsWarper 占位，未安装 torch 时延迟报错
    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class L# TypicalLogitsWarper：PyTorch 占位类：TypicalLogitsWarper 占位，未安装 torch 时延迟报错
ogitsProcessorList(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(sel# UnbatchedClassifierFreeGuidanceLogitsProcessor：PyTorch 占位类：UnbatchedClassifierFreeGuidanceLogitsProcessor 占位，未安装 torch 时延迟报错
f, *args, **kwargs):
        requires_backends(self, ["torch"])# WatermarkDetector：PyTorch 占位类：WatermarkDetector 占位，未安装 torch 时延迟报错



class MaxLengthCriteria(metaclass=DummyObject):
    _backends = ["torch"]

    def __init# WatermarkLogitsProcessor：PyTorch 占位类：WatermarkLogitsProcessor 占位，未安装 torch 时延迟报错
__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class MaxTime# WhisperTimeStampLogitsProcessor：PyTorch 占位类：WhisperTimeStampLogitsProcessor 占位，未安装 torch 时延迟报错
Criteria(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(s# TorchExportableModuleWithStaticCache：PyTorch 占位类：TorchExportableModuleWithStaticCache 占位，未安装 torch 时延迟报错
elf, *args, **kwargs):
        requires_backends(self, ["torch"])


class MinLengthLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
# AttentionMaskInterface：PyTorch 占位类：注意力 mask 接口占位，未安装 torch 时延迟报错
        requires_backends(self, ["torch"])


class MinNewTokensLengthLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])

# GradientCheckpointingLayer：PyTorch 占位类：梯度检查点层占位，未安装 torch 时延迟报错

class MinPLogitsWarper(metaclass=DummyObject):
    _backends = ["# SequenceBiasLogitsProcessor：PyTorch 占位类：SequenceBiasLogitsProcessor 占位，未安装 torch 时延迟报错
torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class NoBadWordsLogitsProcessor(metaclass=DummyObject):
    _backends # AttentionInterface：PyTorch 占位类：注意力接口占位，未安装 torch 时延迟报错
= ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class # PreTrainedModel：PyTorch 占位类：预训练模型基类占位，未安装 torch 时延迟报错
NoRepeatNGramLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, # Adafactor：PyTorch 占位类：Adafactor 优化器占位，未安装 torch 时延迟报错
*args, **kwargs):
        requires_backends(self, ["torch"])


class PrefixConstrainedLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class RepetitionPenaltyLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class SequenceBiasLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class StoppingCriteria(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class StoppingCriteriaList(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class StopStringCriteria(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class SuppressTokensAtBeginLogitsProcessor(metaclass=DummyObject):
    _backends = ["to# Conv1D：PyTorch 占位类：Conv1D 层占位，未安装 torch 时延迟报错
rch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class SuppressTokensLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **# Trainer：PyTorch 占位类：Trainer 训练器占位，未安装 torch 时延迟报错
kwargs):
        requires_backends(self, ["torch"])


class SynthIDTextWatermarkDetector(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["# Seq2SeqTrainer：PyTorch 占位类：Seq2SeqTrainer 训练器占位，未安装 torch 时延迟报错
torch"])


class SynthIDTextWatermarkingConfig(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class SynthIDTextWatermarkLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class TemperatureLogitsWarper(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class TopKLogitsWarper(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class TopPLogitsWarper(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class TypicalLogitsWarper(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class UnbatchedClassifierFreeGuidanceLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class WatermarkDetector(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class WatermarkLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class WhisperTimeStampLogitsProcessor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class TorchExportableModuleWithStaticCache(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


def convert_and_export_with_cache(*args, **kwargs):
    requires_backends(convert_and_export_with_cache, ["torch"])


class AttentionMaskInterface(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


def model_addition_debugger_context(*args, **kwargs):
    requires_backends(model_addition_debugger_context, ["torch"])


class GradientCheckpointingLayer(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


ROPE_INIT_FUNCTIONS = None


def dynamic_rope_update(*args, **kwargs):
    requires_backends(dynamic_rope_update, ["torch"])


class AttentionInterface(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class PreTrainedModel(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


class Adafactor(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


def get_constant_schedule(*args, **kwargs):
    requires_backends(get_constant_schedule, ["torch"])


def get_constant_schedule_with_warmup(*args, **kwargs):
    requires_backends(get_constant_schedule_with_warmup, ["torch"])


def get_cosine_schedule_with_warmup(*args, **kwargs):
    requires_backends(get_cosine_schedule_with_warmup, ["torch"])


def get_cosine_with_hard_restarts_schedule_with_warmup(*args, **kwargs):
    requires_backends(get_cosine_with_hard_restarts_schedule_with_warmup, ["torch"])


def get_inverse_sqrt_schedule(*args, **kwargs):
    requires_backends(get_inverse_sqrt_schedule, ["torch"])


def get_linear_schedule_with_warmup(*args, **kwargs):
    requires_backends(get_linear_schedule_with_warmup, ["torch"])


def get_polynomial_decay_schedule_with_warmup(*args, **kwargs):
    requires_backends(get_polynomial_decay_schedule_with_warmup, ["torch"])


def get_scheduler(*args, **kwargs):
    requires_backends(get_scheduler, ["torch"])


def get_wsd_schedule(*args, **kwargs):
    requires_backends(get_wsd_schedule, ["torch"])


class Conv1D(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


def apply_chunking_to_forward(*args, **kwargs):
    requires_backends(apply_chunking_to_forward, ["torch"])


class Trainer(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])


def torch_distributed_zero_first(*args, **kwargs):
    requires_backends(torch_distributed_zero_first, ["torch"])


class Seq2SeqTrainer(metaclass=DummyObject):
    _backends = ["torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torch"])
