# This file is autogenerated by the command `make fix-copies`, do not edit.
# torchaudio 占位模块：未安装 torchaudio 时语音特征/处理器类延迟报错
from ..utils import DummyObject, requires_backends


# GraniteSpeechFeatureExtractor：torchaudio 占位类：GraniteSpeech 特征提取器占位，未安装 torchaudio 时延迟报错
class GraniteSpeechFeatureExtractor(metaclass=DummyObject):
    _backends = ["torchaudio"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torchaudio"])


# GraniteSpeechProcessor：torchaudio 占位类：GraniteSpeech 处理器占位，未安装 torchaudio 时延迟报错
class GraniteSpeechProcessor(metaclass=DummyObject):
    _backends = ["torchaudio"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torchaudio"])


# MusicgenMelodyFeatureExtractor：torchaudio 占位类：MusicgenMelody 特征提取器占位，未安装 torchaudio 时延迟报错
class MusicgenMelodyFeatureExtractor(metaclass=DummyObject):
    _backends = ["torchaudio"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torchaudio"])


# MusicgenMelodyProcessor：torchaudio 占位类：MusicgenMelody 处理器占位，未安装 torchaudio 时延迟报错
class MusicgenMelodyProcessor(metaclass=DummyObject):
    _backends = ["torchaudio"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["torchaudio"])
